### ISSUE TITLE
Not all invalid characters are being replaced during GraphQL schema inference

### ISSUE THREAD

**Issue by 0x80** [gatsbyjs/gatsby#1021]
A recent commit seems to result in my project package.json being parsed as a source for graphql nodes. It complains about one of my scripts keys not being name compliant. 

```
UNHANDLED REJECTION Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "packageJson___scripts___deploy:production" does not.
    at assertValidName (/Users/me/project/node_modules/graphql/utilities/assertValidName.js:44:11)
    at /Users/me/project/node_modules/graphql/type/definition.js:591:42
    at Array.map (native)
    at defineEnumValues (/Users/me/project/node_modules/graphql/type/definition.js:590:21)
    at new GraphQLEnumType (/Users/me/project/node_modules/graphql/type/definition.js:516:20)
    at inferInputObjectStructureFromNodes (/Users/me/project/node_modules/gatsby/dist/schema/infer-graphql-input-fields.js:220:22)
    at _callee$ (/Users/me/project/node_modules/gatsby/dist/schema/build-node-types.js:98:29)
    at tryCatch (/Users/me/project/node_modules/regenerator-runtime/runtime.js:65:40)
UNHANDLED REJECTION Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "packageJson___scripts___deploy:production" does not.
    at assertValidName (/Users/me/project/node_modules/graphql/utilities/assertValidName.js:44:11)
    at /Users/me/project/node_modules/graphql/type/definition.js:591:42
    at Array.map (native)
    at defineEnumValues (/Users/me/project/node_modules/graphql/type/definition.js:590:21)
    at new GraphQLEnumType (/Users/me/project/node_modules/graphql/type/definition.js:516:20)
    at inferInputObjectStructureFromNodes (/Users/me/project/node_modules/gatsby/dist/schema/infer-graphql-input-fields.js:220:22)
    at _callee$ (/Users/me/project/node_modules/gatsby/dist/schema/build-node-types.js:98:29)
    at tryCatch (/Users/me/project/node_modules/regenerator-runtime/runtime.js:65:40)
```

**Comment by KyleAMathews** [comment]
Yeah, the recent changes unsurfaced a problem with our inferring logic which doesn't cleanup all invalid characters. I'll add a PR in a bit for this.

**Comment by scottyeck** [comment]
@KyleAMathews Per #1025 I think this particular issue was resolved with the latest canary, though I'm now seeing this:

```
UNHANDLED REJECTION Error: sitePluginPluginOptionsInputObject fields must be an object with field names as keys or a function which returns such an object.
    at invariant (/Users/scottyeck/git/fabric/cashmere/node_modules/graphql/jsutils/invariant.js:19:11)
    at GraphQLInputObjectType._defineFieldMap (/Users/scottyeck/git/fabric/cashmere/node_modules/graphql/type/definition.js:648:29)
    at GraphQLInputObjectType.getFields (/Users/scottyeck/git/fabric/cashmere/node_modules/graphql/type/definition.js:639:49)
    at typeMapReducer (/Users/scottyeck/git/fabric/cashmere/node_modules/graphql/type/schema.js:221:26)
    at Array.reduce (native)
    at /Users/scottyeck/git/fabric/cashmere/node_modules/graphql/type/schema.js:214:36
    at Array.forEach (native)
    at typeMapReducer (/Users/scottyeck/git/fabric/cashmere/node_modules/graphql/type/schema.js:207:27)
    at Array.reduce (native)
    at new GraphQLSchema (/Users/scottyeck/git/fabric/cashmere/node_modules/graphql/type/schema.js:95:34)
    at _callee$ (/Users/scottyeck/git/fabric/cashmere/node_modules/gatsby/dist/schema/index.js:37:22)
    at tryCatch (/Users/scottyeck/git/fabric/cashmere/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/scottyeck/git/fabric/cashmere/node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/scottyeck/git/fabric/cashmere/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/scottyeck/git/fabric/cashmere/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/scottyeck/git/fabric/cashmere/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```

**Comment by KyleAMathews** [comment]
#1030 should handle the additional issue @scottyeck found.
