### ISSUE TITLE
Truncated Data URL output from importing images from dependency.

### ISSUE THREAD

**Issue by pr1ntr** [gatsbyjs/gatsby#10309]
## Description

Attempting to `require` an image that is located in a node_modules after adding custom webpack rule leads the image being turned into a truncated data uri.

The custom rule:

```
exports.onCreateWebpackConfig = ({ stage,
                                   rules,
                                   loaders,
                                   plugins,
                                   actions }) => {
  
  const dependencyPath = fs.realpathSync(path.resolve(process.cwd(), '../../', 'node_modules/mt-common'))
  actions.setWebpackConfig({
    module: {
      rules: [{
        test: /\.jsx?$/,
        loader: loaders.js(),
        include: [
          dependencyPath,
        ],
      }, {
          use: [loaders.url(), loaders.file()],
          test: /\.(ico|svg|jpg|jpeg|png|gif|webp)(\?.*)?$/,
          include: [
            dependencyPath,
          ],
      }],
    },
  })
}
```

If I remove `loaders.file()` 
```
 {
          use: [loaders.url()],
          test: /\.(ico|svg|jpg|jpeg|png|gif|webp)(\?.*)?$/,
          include: [
            dependencyPath,
          ],
      }
```
then I get the followign error:

```
ERROR in C:/Users/d4rkl/Projects/MT/dev/mt-common/assets/footer.png
Module build failed (from C:/Users/d4rkl/Projects/MT/dev/mt-site/node_modules/url-loader/dist/cjs.js):
TypeError: Cannot read property 'context' of undefined
    at Object.loader (C:\Users\d4rkl\Projects\MT\dev\mt-site\node_modules\file-loader\dist\index.js:34:49)
    at Object.loader (C:\Users\d4rkl\Projects\MT\dev\mt-site\node_modules\url-loader\dist\index.js:76:19)

```

This is a linked dependency at this moment. But I mitigate that using `fs.realPath`

I get the same result if I don't link the dep (different paths):  

```
ERROR in C:/Users/d4rkl/Projects/MT/dev/mt-site/node_modules/mt-common/public/images/image.png
Module build failed (from C:/Users/d4rkl/Projects/MT/dev/mt-site/node_modules/url-loader/dist/cjs.js):
TypeError: Cannot read property 'context' of undefined
    at Object.loader (C:\Users\d4rkl\Projects\MT\dev\mt-site\node_modules\file-loader\dist\index.js:34:49)
    at Object.loader (C:\Users\d4rkl\Projects\MT\dev\mt-site\node_modules\url-loader\dist\index.js:76:19
)
```

### Steps to reproduce

1. Set up hello world project.
2. import some package with an image in it. (like maybe fontawesome or something with a bunch of svg)
3. Use the custom webpack function above replace path with path of module in question. 
4. Attempt to import the file from node_modules directly or through a js import that contains the require.

### Expected result

It should either write the image properly or create an untruncated data url.

### Actual result

If the image is small the data url is created and is truncated. It does this even for images that are huge.
example: 
`data:image/png;base64,bW9kdWxlLmV4cG9ydHMgPSAiZGF0YTppbWFnZS9wbmc7YmFzZTY0LGJXOWtkV3hsTG1WNGNHOXlkSE1nUFNCZlgzZGxZbkJoWTJ0ZmNIVmliR2xqWDNCaGRHaGZYeUFySUNKemRHRjBhV012YVcxaFoyVXRObVk1TlRRMVlUTmtPV0poWmpGbE5XRm1aR1ZpTXpjeU9Ea3pNRGs0WlRFdWNHNW5JanM9Ig==` 

### Environment

I am running this through webstorm.
`"C:\Program Files\JetBrains\PhpStorm 2018.2.5\bin\runnerw.exe" C:\Users\d4rkl\AppData\Roaming\nvm\v8.10.0\node.exe --preserve-symlinks C:\Users\d4rkl\Projects\MT\dev\mt-site\packages\worker\..\..\node_modules\gatsby\dist\bin\gatsby.js develop --site-id=2`

``` 
  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
```

**EDIT**

I should mention that I am using lerna and yarn workspaces for this project.
the tree looks like this
```
root
  - node_modules/
     - mt-common/ (symlinked here)
  - packages/
      - worker/ (gatsby root)
```
I don't know if this would matter though.

**Comment by pr1ntr** [comment]
**UPDATE**

I removed all custom config and tried to simply import an image from the project dir and still happened.
Then I thought..... well maybe its the Gatsby version.. so I updated Gatsby and all the deps. 

Problem Solved.
