### ISSUE TITLE
Build fails on netlify

### ISSUE THREAD

**Issue by isaac-martin** [gatsbyjs/gatsby#10362]
## Description

Build Errors on Netlify. Build exceeds maximum allowed runtime.
Can build locally running `yarn build` and inside the Netlify docker container, however when on Netlifys build it exceeds maximum allowed runtime. 

### Steps to reproduce
Clone repo - build locally / in Netlify docker container.
https://github.com/smkkstudios/pairity

Am getting some warnings like the below when running in the Netlify docker container
`Warning: a promise was created in a handler at opt/buildhome/repo/node_modules/postcss/lib/lazy-result.js:213:17 but was not returned from it`

`Warning: a promise was created in a handler at /opt/buildhome/repo/node_modules/gatsby-transformer-remark/extend-node-type.js:179:19 but was not returned from it`

### Expected result

Should Build without fail

### Actual result

Fails due to maximum build time exceed

### Environment

```
  System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Browsers:
    Chrome: 70.0.3538.110
    Firefox: 63.0.3
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.0 => 2.0.64
    gatsby-image: ^2.0.22 => 2.0.22
    gatsby-plugin-eslint: ^2.0.1 => 2.0.1
    gatsby-plugin-netlify: ^2.0.0 => 2.0.6
    gatsby-plugin-postcss: ^2.0.2 => 2.0.2
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.4
    gatsby-plugin-react-svg: ^2.0.0-beta1 => 2.0.0
    gatsby-plugin-sharp: ^2.0.5 => 2.0.15
    gatsby-remark-images: ^2.0.1 => 2.0.6
    gatsby-remark-images-contentful: ^2.0.4 => 2.0.4
    gatsby-source-contentful: ^2.0.6 => 2.0.19
    gatsby-transformer-remark: ^2.1.1 => 2.1.15
    gatsby-transformer-sharp: ^2.1.1 => 2.1.9
```

**Comment by isaac-martin** [comment]
The two bluebird warnings point to these two functions;
*gatsby-transformer-remark*
```
    function _getAST() {
      _getAST = (0, _asyncToGenerator2.default)(function* (markdownNode) {
        const cacheKey = astCacheKey(markdownNode);
        const cachedAST = yield cache.get(cacheKey);

        if (cachedAST) {
          return cachedAST;
        } else if (ASTPromiseMap.has(cacheKey)) {
          // We are already generating AST, so let's wait for it
          return yield ASTPromiseMap.get(cacheKey);
        } else {
          const ASTGenerationPromise = getMarkdownAST(markdownNode);
          ASTGenerationPromise.then(markdownAST => {
            cache.set(cacheKey, markdownAST);
            ASTPromiseMap.delete(cacheKey);
          }).catch(err => {
            ASTPromiseMap.delete(cacheKey);
            return err;
          }); // Save new AST to cache and return
          // We can now release promise, as we cached result

          ASTPromiseMap.set(cacheKey, ASTGenerationPromise);
          return ASTGenerationPromise;
        }
      });
      return _getAST.apply(this, arguments);
    }
```
*POSTCSS*
```
  _proto.asyncTick = function asyncTick(resolve, reject) {
    var _this = this;

    if (this.plugin >= this.processor.plugins.length) {
      this.processed = true;
      return resolve();
    }

    try {
      var plugin = this.processor.plugins[this.plugin];
      var promise = this.run(plugin);
      this.plugin += 1;

      if (isPromise(promise)) {
        promise.then(function () {
          _this.asyncTick(resolve, reject);
        }).catch(function (error) {
          _this.handleError(error, plugin);

          _this.processed = true;
          reject(error);
        });
      } else {
        this.asyncTick(resolve, reject);
      }
    } catch (error) {
      this.processed = true;
      reject(error);
    }
  };
```

**Comment by isaac-martin** [comment]
Dug around on this yesterday but still not getting anywhere. If anyone has any pointers on where I should be debugging - will gladly hear them

**Comment by isaac-martin** [comment]
I actually got mine working. I will happily help you debug.

**Comment by sidharthachatterjee** [comment]
@isaac-martin Glad that you got this working

Can you post what it was that was causing this?

Also can I close this issue?

**Comment by isaac-martin** [comment]
So mine was a hanging process - the hanging process was initiated by a package from haiku.ai. The process was hanging on local as well as Netlify, but it wasn't causing the build to fail locally.
