### ISSUE TITLE
Error starting gatsby 1.0.0-alpha13 with blog template

### ISSUE THREAD

**Issue by hugmanrique** [gatsbyjs/gatsby#1039]
I've installed the blog template per the instructions on [https://www.gatsbyjs.org/docs/]() and I get this error while using `gatsby develop` or `gatsby build`:

```
12:44:21 PM: bin/gatsby: time since started: 0.064
12:44:21 PM: bin/cli: time since started: 0.199
12:44:22 PM: lib/bootstrap/index.js time since started: 1.234
12:44:22 PM: open and validate gatsby-config.js: 5.848ms
12:44:22 PM: initial loading: 1196.207ms
12:44:22 PM: copy gatsby files: 32.475ms
12:44:22 PM: calling api handler in /opt/build/repo/node_modules/gatsby/dist/bootstrap/internal-plugins/internal-data-bridge for api sourceNodes
12:44:22 PM: calling api handler in /opt/build/repo/node_modules/gatsby-source-filesystem for api sourceNodes
12:44:25 PM: ---saved redux state
12:44:26 PM: sourcing and parsing nodes: 3512.608ms
12:44:26 PM: calling api handler in /opt/build/repo/node_modules/gatsby-transformer-remark for api extendNodeType
12:44:26 PM: calling api handler in /opt/build/repo/node_modules/gatsby-transformer-remark for api extendNodeType
12:44:26 PM: calling api handler in /opt/build/repo/node_modules/gatsby-transformer-remark for api extendNodeType
12:44:26 PM: calling api handler in /opt/build/repo/node_modules/gatsby-transformer-remark for api extendNodeType
12:44:26 PM: calling api handler in /opt/build/repo/node_modules/gatsby-transformer-remark for api extendNodeType
12:44:26 PM: calling api handler in /opt/build/repo/node_modules/gatsby-transformer-sharp for api extendNodeType
12:44:26 PM: calling api handler in /opt/build/repo/node_modules/gatsby-transformer-sharp for api extendNodeType
12:44:26 PM: calling api handler in /opt/build/repo/node_modules/gatsby-transformer-sharp for api extendNodeType
12:44:26 PM: calling api handler in /opt/build/repo/node_modules/gatsby-transformer-sharp for api extendNodeType
12:44:26 PM: calling api handler in /opt/build/repo/node_modules/gatsby-transformer-sharp for api extendNodeType
12:44:26 PM: UNHANDLED REJECTION Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "0" does not.
at assertValidName (/opt/build/repo/node_modules/graphql/utilities/assertValidName.js:44:11)
at /opt/build/repo/node_modules/graphql/type/definition.js:651:44
at Array.forEach (native)
at GraphQLInputObjectType._defineFieldMap (/opt/build/repo/node_modules/graphql/type/definition.js:650:16)
at GraphQLInputObjectType.getFields (/opt/build/repo/node_modules/graphql/type/definition.js:639:49)
at typeMapReducer (/opt/build/repo/node_modules/graphql/type/schema.js:221:26)
at typeMapReducer (/opt/build/repo/node_modules/graphql/type/schema.js:187:12)
at /opt/build/repo/node_modules/graphql/type/schema.js:224:20
at Array.forEach (native)
at typeMapReducer (/opt/build/repo/node_modules/graphql/type/schema.js:222:28)
at /opt/build/repo/node_modules/graphql/type/schema.js:224:20
at Array.forEach (native)
at typeMapReducer (/opt/build/repo/node_modules/graphql/type/schema.js:222:28)
at Array.reduce (native)
at /opt/build/repo/node_modules/graphql/type/schema.js:214:36
at Array.forEach (native)
12:44:26 PM: ---saved redux state
12:44:26 PM: UNHANDLED REJECTION Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "0" does not.
at assertValidName (/opt/build/repo/node_modules/graphql/utilities/assertValidName.js:44:11)
at /opt/build/repo/node_modules/graphql/type/definition.js:651:44
at Array.forEach (native)
at GraphQLInputObjectType._defineFieldMap (/opt/build/repo/node_modules/graphql/type/definition.js:650:16)
at GraphQLInputObjectType.getFields (/opt/build/repo/node_modules/graphql/type/definition.js:639:49)
at typeMapReducer (/opt/build/repo/node_modules/graphql/type/schema.js:221:26)
at typeMapReducer (/opt/build/repo/node_modules/graphql/type/schema.js:187:12)
at /opt/build/repo/node_modules/graphql/type/schema.js:224:20
at Array.forEach (native)
at typeMapReducer (/opt/build/repo/node_modules/graphql/type/schema.js:222:28)
at /opt/build/repo/node_modules/graphql/type/schema.js:224:20
at Array.forEach (native)
at typeMapReducer (/opt/build/repo/node_modules/graphql/type/schema.js:222:28)
at Array.reduce (native)
at /opt/build/repo/node_modules/graphql/type/schema.js:214:36
at Array.forEach (native)
```

By the looks of it, it has something to do with the Gatsby Sharp transformer and GraphQL. I haven't modified anything from the initial template.

**Comment by ivanoats** [comment]
related? https://github.com/gatsbyjs/gatsby-starter-blog/issues/30 - try the troubleshooting steps there

**Comment by hugmanrique** [comment]
Yes, I was using gatsby@alpha13 instead of alpha15 and npm. Just submitted a PR to reflect the change on the docs
