### ISSUE TITLE
[1.0] using npm produces graphql error for gatsbygram and www

### ISSUE THREAD

**Issue by NEIA20** [gatsbyjs/gatsby#1048]
After using npm install to install dependences for examples/gatsbygram and www, I got this error on npm run build: 

```
UNHANDLED REJECTION Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "0" does not.
    at assertValidName (/Users/Niz/Documents/Fabric/Blog/gatsby/www/node_modules/graphql/utilities/assertValidName.js:44:11)
    at /Users/Niz/Documents/Fabric/Blog/gatsby/www/node_modules/graphql/type/definition.js:651:44
    at Array.forEach (native)
    at GraphQLInputObjectType._defineFieldMap (/Users/Niz/Documents/Fabric/Blog/gatsby/www/node_modules/graphql/type/definition.js:650:16)
    at GraphQLInputObjectType.getFields (/Users/Niz/Documents/Fabric/Blog/gatsby/www/node_modules/graphql/type/definition.js:639:49)
    at typeMapReducer (/Users/Niz/Documents/Fabric/Blog/gatsby/www/node_modules/graphql/type/schema.js:221:26)
    at typeMapReducer (/Users/Niz/Documents/Fabric/Blog/gatsby/www/node_modules/graphql/type/schema.js:187:12)
    at /Users/Niz/Documents/Fabric/Blog/gatsby/www/node_modules/graphql/type/schema.js:224:20
    at Array.forEach (native)
    at typeMapReducer (/Users/Niz/Documents/Fabric/Blog/gatsby/www/node_modules/graphql/type/schema.js:222:28)
    at /Users/Niz/Documents/Fabric/Blog/gatsby/www/node_modules/graphql/type/schema.js:224:20
    at Array.forEach (native)
    at typeMapReducer (/Users/Niz/Documents/Fabric/Blog/gatsby/www/node_modules/graphql/type/schema.js:222:28)
    at Array.reduce (native)
    at /Users/Niz/Documents/Fabric/Blog/gatsby/www/node_modules/graphql/type/schema.js:214:36
    at Array.forEach (native)

```

But if I use yarn to install the dependencies instead, that error goes away and the code builds fine

**Comment by hugmanrique** [comment]
Related: https://github.com/gatsbyjs/gatsby-starter-blog/issues/30 The fix was to use `yarn`, but this should be fixed.

**Comment by KyleAMathews** [comment]
This should be fixed now
