### ISSUE TITLE
["new","--help"].includes is not a function

### ISSUE THREAD

**Issue by kongakong** [gatsbyjs/gatsby#1099]
This is the dockerfile which is used to create a dev environment

```
FROM ubuntu:16.04

RUN apt-get update -y

RUN apt-get install -y npm
RUN apt-get install -y git nodejs-legacy
RUN npm install -g gatsby@next

RUN mkdir -p /app
ADD . /app/gatsby

```

I run the docker machine and try to create a new blog

```
> docker run -it gatsby /bin/bash    
root@f01d9bcbeb1e:/# cd /app/
root@f01d9bcbeb1e:/app# cd gatsby/
root@f01d9bcbeb1e:/app/gatsby# gatsby new blog
bin/gatsby: time since started: 0.405
/usr/local/lib/node_modules/gatsby/dist/gatsby-cli.js:29
  if (["new", "--help"].includes(process.argv[2])) {
                        ^

TypeError: ["new","--help"].includes is not a function
    at useGlobalGatsby (/usr/local/lib/node_modules/gatsby/dist/gatsby-cli.js:29:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby/dist/gatsby-cli.js:46:3)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

Cannot run gatsby at all to retrieve the version info

```
gatsby --version
bin/gatsby: time since started: 0.048
/usr/local/lib/node_modules/gatsby/dist/gatsby-cli.js:29
  if (["new", "--help"].includes(process.argv[2])) {
                        ^
```

Version information of npm and node

```
root@f01d9bcbeb1e:/usr/share/npm/node_modules# npm --version
3.5.2
root@f01d9bcbeb1e:/usr/share/npm/node_modules# node --version
v4.2.6
```

Based on the package.json, the version should be `gatsby@1.0.0-alpha19`

**Comment by KyleAMathews** [comment]
Hmmm looks like `Array.prototype.includes` was only added quite recently to v8 / Node.js (Chrome 47).

If you feel up to it, would love a PR swapping out a more compatible implementation.

**Comment by g8tguy** [comment]
Just use the tested `Gatsby` images as `parent containers`, they are 10 times smaller than `Ubuntu` ones. And work flawlessly [Gatsby](https://hub.docker.com/r/g8tguy/gatsby/)

```Dockerfile
FROM g8tguy/gatsby:v1.0.0-alpha19
# Or 
# FROM g8tguy/gatsby:canary
#
```

**Comment by kongakong** [comment]
I find it easier to use node v6. Here is my updated docker file:

```
FROM ubuntu:16.04

RUN apt-get update -y
RUN apt-get install -y curl
# To install node 6
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y nodejs
# Need make for leveldown, a dependency of nodejs
RUN apt-get install -y build-essential
RUN apt-get install -y git python
RUN npm install -g gatsby@next
```

But @g8tguy has suggested a better solution

**Comment by kongakong** [comment]
@KyleAMathews I am not sure if you still want to tackle the `.includes is not a function` issue. I closed the issue, but feel free to reopen

**Comment by KyleAMathews** [comment]
@kongakong I did a quick fix on a branch I'm working on https://github.com/gatsbyjs/gatsby/commit/bf1eaeab644c75c992edf6eed23bf3bc49570ac0

Thanks for reporting the issue! It'll be out in a release soon.
