### ISSUE TITLE
Error: Cannot find module '../lib/utils/init-starter' on second step of tutorial

### ISSUE THREAD

**Issue by johnbrett** [gatsbyjs/gatsby#11]
Very excited by this, thanks for providing it!

Hit a problem when following the tutorial, to reproduce:

```
$ npm i -g gatsby
$ gatsby new docs-site gh:gatsbyjs/gatsby-starter-documentation

// gives the following stack trace:

Error: Cannot find module '../lib/utils/init-starter'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/n/versions/0.10.25/lib/node_modules/gatsby/bin/new.coffee:2:15)
  at Object.<anonymous> (/usr/local/n/versions/0.10.25/lib/node_modules/gatsby/bin/new.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/usr/local/n/versions/0.10.25/lib/node_modules/gatsby/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/local/n/versions/0.10.25/lib/node_modules/gatsby/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/n/versions/0.10.25/lib/node_modules/gatsby/bin/gatsby-new.js:4:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3
```

Any tips to debug / fix ?

**Comment by johnbrett** [comment]
Thank you :)

**Comment by KyleAMathews** [comment]
No problem! Bummed I missed this before pushing things out.

**Comment by johnbrett** [comment]
Don't be too hard on yourself, really impressive project! Can confirm everything worked for me on latest.

**Comment by KyleAMathews** [comment]
Good to hear it's working :) Sometimes you throw things over the open source wall and have no idea if it actually works for anyone.
