### ISSUE TITLE
Module build failed: Error: Final loader didn't return a Buffer or String

### ISSUE THREAD

**Issue by omattman** [gatsbyjs/gatsby#11180]
Hello.

Receiving following compile error on ```gatsby-develop```:

```
WAIT  Compiling...                                                                                20:37:06
 ERROR  Failed to compile with 1 errors                                                            20:37:14
 error

Module build failed: Error: Final loader didn't return a Buffer or String
    at NormalModule.onModuleBuild (/mnt/c/dev/djb/frontend/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:299:42)
    at nextLoader (/mnt/c/dev/djb/frontend/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at NormalModule.onLoadPitchDone (/mnt/c/dev/djb/frontend/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:262:4)
    at NormalModule.loadPitch (/mnt/c/dev/djb/frontend/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:182:27)
    at NormalModule.doBuild (/mnt/c/dev/djb/frontend/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
    at NormalModule.build (/mnt/c/dev/djb/frontend/node_modules/webpack/lib/NormalModule.js:84:14)
    at Compilation.buildModule (/mnt/c/dev/djb/frontend/node_modules/webpack/lib/Compilation.js:126:9)
    at /mnt/c/dev/djb/frontend/node_modules/webpack/lib/Compilation.js:309:10
    at /mnt/c/dev/djb/frontend/node_modules/webpack/lib/NormalModuleFactory.js:58:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/mnt/c/dev/djb/frontend/node_modules/tapable/lib/Tapable.js:75:69)
    at onDoneResolving (/mnt/c/dev/djb/frontend/node_modules/webpack/lib/NormalModuleFactory.js:38:11)
    at onDoneResolving (/mnt/c/dev/djb/frontend/node_modules/webpack/lib/NormalModuleFactory.js:121:6)
    at /mnt/c/dev/djb/frontend/node_modules/webpack/lib/NormalModuleFactory.js:116:7
    at /mnt/c/dev/djb/frontend/node_modules/webpack/node_modules/async/lib/async.js:726:13
    at /mnt/c/dev/djb/frontend/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at async.forEachOf.async.eachOf (/mnt/c/dev/djb/frontend/node_modules/webpack/node_modules/async/lib/async.js:236:30)
    at _parallel (/mnt/c/dev/djb/frontend/node_modules/webpack/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/mnt/c/dev/djb/frontend/node_modules/webpack/node_modules/async/lib/async.js:731:9)
    at /mnt/c/dev/djb/frontend/node_modules/webpack/lib/NormalModuleFactory.js:109:12
    at /mnt/c/dev/djb/frontend/node_modules/webpack/node_modules/async/lib/async.js:726:13
    at /mnt/c/dev/djb/frontend/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at async.forEachOf.async.eachOf (/mnt/c/dev/djb/frontend/node_modules/webpack/node_modules/async/lib/async.js:236:30)

 @ ./~/css-loader!./~/sass-loader?{"plugins":[]}!./src/layouts/style.scss 6:182280-182291
```

And I have the following package.json:

```
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "@material-ui/core": "^3.3.1",
    "@material-ui/icons": "^3.0.1",
    "gatsby": "^1.9.279",
    "gatsby-cli": "^2.4.8",
    "gatsby-image": "^1.0.55",
    "gatsby-link": "^1.6.46",
    "gatsby-plugin-page-transitions": "^1.0.7",
    "gatsby-plugin-react-helmet": "^2.0.11",
    "gatsby-plugin-sass": "^1.0.26",
    "gatsby-plugin-sharp": "^1.6.48",
    "gatsby-source-wordpress": "^2.0.93",
    "gatsby-transformer-sharp": "^1.6.27",
    "node-sass": "^4.10.0",
    "prop-types": "^15.6.2",
    "react": "^16.3.0",
    "react-dom": "^16.6.0",
    "react-helmet": "^5.2.0",
    "react-html-parser": "^2.0.2",
    "react-media": "^1.8.0",
    "react-player": "^1.6.4",
    "react-share": "^2.3.1",
    "react-swipeable-views": "^0.13.0",
    "react-tabs": "^2.2.2",
    "styled-components": "^4.0.2",
    "typeface-roboto": "0.0.54"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write 'src/**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "eslint": "^5.8.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-node": "^8.0.0",
    "eslint-plugin-promise": "^4.0.1",
    "eslint-plugin-react": "^7.11.1",
    "eslint-plugin-standard": "^4.0.0"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  }
}
```

Haven't been working on the project for approximately two weeks and got back to this. Any ideas?

**Comment by sidharthachatterjee** [comment]
@omattman Could you please link to a minimal reproduction? Looking at the error, it appears something is tripping the `sass-loader` in `src/layouts/style.scss`
