### ISSUE TITLE
Error while building site (gatsby develop)

### ISSUE THREAD

**Issue by mhjadav** [gatsbyjs/gatsby#11519]
Issue resolved after deleting node_modules and .cache folder but not sure what is the root cause so I am logging this issue.

Logs - 

here ./.cache/develop-static-entry.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/mj/Documents/Dreams/ruchir/nx-digital/gatsby-site/.cache/develop-static-entry.js: You gave us a visitor for the node type PrivateName but it's not a valid type
    at verify (/Users/mj/Documents/Dreams/ruchir/nx-digital/gatsby-site/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:143:13)
    at Function.explode (/Users/mj/Documents/Dreams/ruchir/nx-digital/gatsby-site/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:46:3)
    at instantiatePlugin (/Users/mj/Documents/Dreams/ruchir/nx-digital/gatsby-site/node_modules/@babel/core/lib/config/full.js:205:42)
    at cachedFunction (/Users/mj/Documents/Dreams/ruchir/nx-digital/gatsby-site/node_modules/@babel/core/lib/config/caching.js:32:19)
    at loadPluginDescriptor (/Users/mj/Documents/Dreams/ruchir/nx-digital/gatsby-site/node_modules/@babel/core/lib/config/full.js:192:10)
    at config.plugins.map.descriptor (/Users/mj/Documents/Dreams/ruchir/nx-digital/gatsby-site/node_modules/@babel/core/lib/config/full.js:68:16)
    at Array.map (<anonymous>)
    at recurseDescriptors (/Users/mj/Documents/Dreams/ruchir/nx-digital/gatsby-site/node_modules/@babel/core/lib/config/full.js:67:38)
    at loadFullConfig (/Users/mj/Documents/Dreams/ruchir/nx-digital/gatsby-site/node_modules/@babel/core/lib/config/full.js:100:6)
    at process.nextTick (/Users/mj/Documents/Dreams/ruchir/nx-digital/gatsby-site/node_modules/@babel/core/lib/transform.js:28:33)
    at process._tickCallback (internal/process/next_tick.js:61:11)
error There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  WebpackError: ./.cache/develop-static-entry.js

  - bootstrap:35 Function.explode
    lib/webpack/bootstrap:35:1

  - bootstrap:21 cachedFunction
    lib/webpack/bootstrap:21:1

  - bootstrap:57 config.plugins.map.descriptor
    lib/webpack/bootstrap:57:1

  - bootstrap:56 recurseDescriptors
    lib/webpack/bootstrap:56:1

  - bootstrap:50 process._tickCallback
    lib/webpack/bootstrap:50:1

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by sidharthachatterjee** [comment]
Thank you for reporting this, @mhjadav 

Seen this before in https://github.com/babel/babel/issues/8039 but strange because the current version shouldn't do this

Do you by chance have the lock file prior to deleting node_modules and reinstalling?
