### ISSUE TITLE
Cannot use gatsby on mac, Error: Cannot find module './published'

### ISSUE THREAD

**Issue by victorkane** [gatsbyjs/gatsby#118]
Correctly installed gatsby globally as per README, then:

```
$ gatsby new my-test-gatsby-site

or

gatsby new gatsby-documentation-site https://github.com/gatsbyjs/gatsby-starter-documentation

or

gatsby new docs-site gh:gatsbyjs/gatsby-starter-documentation

module.js:338
    throw err;
module.js:338
    throw err;
    ^

Error: Cannot find module './published'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby/bin/new.coffee:10:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby/bin/new.coffee:35:4)
    at Module._compile (module.js:434:26)
    at Object.loadFile (/usr/local/lib/node_modules/gatsby/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
    at Module.load (/usr/local/lib/node_modules/gatsby/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby/bin/gatsby-new.js:5:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3
```

**Comment by scottnonnenberg** [comment]
I ran into that when I had cloned the gatsby repo, instead of `npm install -g gatsby`. The permissions of the `dist` directory were all weird. Had to delete the folder then do a `./scripts/build.sh`. (I'm on node v4.2.4)

**Comment by victorkane** [comment]
In my case I did not clone the gatsby tepo. I did a global install with npm
as per Readme

**Comment by KyleAMathews** [comment]
@victorkane are you on Gatsby 0.7.7? I just did a fresh install and it worked...

**Comment by victorkane** [comment]
Thanks @KyleAMathews! Did fresh install and indeed everything fine (Macbook Pro Yosemite):

### test gastsby

```
$ npm install -g gatsby

$ gatsby --version
0.7.7
$ gatsby new my-test-gatsby-site
$ cd my-test-gatsby-site/
$ gatsby develop
```

Works fine.

```
$ gatsby new gatsby-documentation-site https://github.com/gatsbyjs/gatsby-starter-documentation
$ cd gatsby-documentation-site/
$ gatsby develop
Listening at: http://0.0.0.0:8000
Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.
```

Works fine despite warning (should be using constructor?)

```
$ gatsby new myblog https://github.com/gatsbyjs/gatsby-starter-blog
$ cd myblog
$ gatsby develop
```

Works great!
