### ISSUE TITLE
Unhandled Rejection - 96,000 Page Build

### ISSUE THREAD

**Issue by youmustfight** [gatsbyjs/gatsby#12021]
## Description

Our nonprofit is creating programmatic content for a bunch of different localities and legal needs in the U.S. We've been enjoying Gatsby up to the 12,000 page range, but we recently wanted to expand our legal templates and go zipcode based. This means we've gone from 12,000 pages to 96,000 pages. This has forced me to do builds on a higher performance EC2 instance rather than my Macbook Air.

The build breaks however, right after bootstrap finishes and before I see a consoled message about building JS/CSS bundles. Here's the error message:

```
...
success write out page data — 0.316 s
success write out redirect data — 0.000 s
success onPostBootstrap — 0.051 s

info bootstrap finished - 56.852 s

error Cannot read property 'message' of undefined

  TypeError: Cannot read property 'message' of undefined

  - index.js:71 ConsoleReporter.error
    [upsolve_frontdoor]/[gatsby-cli]/lib/reporter/index.js:71:23

  - index.js:56 ConsoleReporter.panic
    [upsolve_frontdoor]/[gatsby-cli]/lib/reporter/index.js:56:10

  - create-cli.js:16 Promise.resolve.then.err
    [upsolve_frontdoor]/[gatsby-cli]/lib/create-cli.js:16:74

  - util.js:16 tryCatcher
    [upsolve_frontdoor]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [upsolve_frontdoor]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [upsolve_frontdoor]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [upsolve_frontdoor]/[bluebird]/js/release/promise.js:614:10

  - promise.js:690 Promise._settlePromises
    [upsolve_frontdoor]/[bluebird]/js/release/promise.js:690:18

  - async.js:138 _drainQueueStep
    [upsolve_frontdoor]/[bluebird]/js/release/async.js:138:12

  - async.js:131 _drainQueue
    [upsolve_frontdoor]/[bluebird]/js/release/async.js:131:9

  - async.js:147 Async._drainQueues
    [upsolve_frontdoor]/[bluebird]/js/release/async.js:147:5

  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [upsolve_frontdoor]/[bluebird]/js/release/async.js:17:14


error UNHANDLED REJECTION


  TypeError: Cannot read property 'message' of undefined

  - index.js:71 ConsoleReporter.error
    [upsolve_frontdoor]/[gatsby-cli]/lib/reporter/index.js:71:23

  - index.js:56 ConsoleReporter.panic
    [upsolve_frontdoor]/[gatsby-cli]/lib/reporter/index.js:56:10

  - create-cli.js:16 Promise.resolve.then.err
    [upsolve_frontdoor]/[gatsby-cli]/lib/create-cli.js:16:74

  - util.js:16 tryCatcher
    [upsolve_frontdoor]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [upsolve_frontdoor]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [upsolve_frontdoor]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [upsolve_frontdoor]/[bluebird]/js/release/promise.js:614:10

  - promise.js:690 Promise._settlePromises
    [upsolve_frontdoor]/[bluebird]/js/release/promise.js:690:18

  - async.js:138 _drainQueueStep
    [upsolve_frontdoor]/[bluebird]/js/release/async.js:138:12

  - async.js:131 _drainQueue
    [upsolve_frontdoor]/[bluebird]/js/release/async.js:131:9

  - async.js:147 Async._drainQueues
    [upsolve_frontdoor]/[bluebird]/js/release/async.js:147:5

  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [upsolve_frontdoor]/[bluebird]/js/release/async.js:17:14


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! upsolve_frontdoor@1.0.0 build: `npm run clean && node --max_old_space_size=16000 --stack-size=1000000 ./node_modules/.bin/gatsby build --verbose`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the upsolve_frontdoor@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2019-02-23T18_35_03_082Z-debug.log
```

NPM debug-log...
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/ec2-user/.nvm/versions/node/v10.14.0/bin/node',
1 verbose cli   '/home/ec2-user/.nvm/versions/node/v10.14.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v10.14.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle upsolve_frontdoor@1.0.0~prebuild: upsolve_frontdoor@1.0.0
6 info lifecycle upsolve_frontdoor@1.0.0~build: upsolve_frontdoor@1.0.0
7 verbose lifecycle upsolve_frontdoor@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle upsolve_frontdoor@1.0.0~build: PATH: /home/ec2-user/.nvm/versions/node/v10.14.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ec2-user/upsolve_frontdoor/node_modules/.bin:/home/ec2-user/.nvm/versions/node/v10.14.0/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.local/bin:/home/ec2-user/bin
9 verbose lifecycle upsolve_frontdoor@1.0.0~build: CWD: /home/ec2-user/upsolve_frontdoor
10 silly lifecycle upsolve_frontdoor@1.0.0~build: Args: [ '-c',
10 silly lifecycle   'npm run clean && node --max_old_space_size=16000 --stack-size=1000000 ./node_modules/.bin/gatsby build --verbose' ]
11 silly lifecycle upsolve_frontdoor@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle upsolve_frontdoor@1.0.0~build: Failed to exec build script
13 verbose stack Error: upsolve_frontdoor@1.0.0 build: `npm run clean && node --max_old_space_size=16000 --stack-size=1000000 ./node_modules/.bin/gatsby build --verbose`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.14.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.14.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid upsolve_frontdoor@1.0.0
15 verbose cwd /home/ec2-user/upsolve_frontdoor
16 verbose Linux 4.14.88-88.76.amzn2.x86_64
17 verbose argv "/home/ec2-user/.nvm/versions/node/v10.14.0/bin/node" "/home/ec2-user/.nvm/versions/node/v10.14.0/bin/npm" "run" "build"
18 verbose node v10.14.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error upsolve_frontdoor@1.0.0 build: `npm run clean && node --max_old_space_size=16000 --stack-size=1000000 ./node_modules/.bin/gatsby build --verbose`
22 error Exit status 1
23 error Failed at the upsolve_frontdoor@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

*One key note* is that I can successfully build the site if I only do 4,000 cities at a time (3 pages per city). Only when I try building the full set does it break (27,000 cities with 3 pages per city). Two of the three templates are quite large in word count and elements.

### Steps to reproduce

You can except a problem to arise when you just type:
`npm run build` ->
`node --max_old_space_size=16000 --stack-size=1000000 ./node_modules/.bin/gatsby build --verbose`

⚠️ I'm not done yet with a demo project BUT for the time being here is a clone of my repo if you want to look around. The gatsby-node.js file is a little bit crazy:
- https://github.com/youmustfight/gatsby_build_breaker
- https://github.com/youmustfight/gatsby_build_breaker/blob/master/gatsby-node.js#L178
- https://github.com/youmustfight/gatsby_build_breaker/blob/master/package.json#L84

### Expected result

Expected a successful build of all 96,000 pages 🎉 

### Actual result

Seems to break when I'm around  the ~20,000 pages mark

### Environment

```
  System:
    OS: Linux 4.14 Amazon Linux 2
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8151 CPU @ 3.40GHz
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 10.14.0 - ~/.nvm/versions/node/v10.14.0/bin/node
    Yarn: 1.13.0 - ~/.nvm/versions/node/v10.14.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.0/bin/npm
  Languages:
    Python: 2.7.14 - /usr/bin/python
  npmPackages:
    gatsby: ^2.1.17 => 2.1.17
    gatsby-image: ^2.0.26 => 2.0.29
    gatsby-link: ^2.0.12 => 2.0.12
    gatsby-plugin-canonical-urls: ^2.0.10 => 2.0.10
    gatsby-plugin-catch-links: ^2.0.11 => 2.0.11
    gatsby-plugin-feed: ^2.0.13 => 2.0.13
    gatsby-plugin-manifest: ^2.0.19 => 2.0.19
    gatsby-plugin-offline: ^2.0.21 => 2.0.24
    gatsby-plugin-react-helmet: ^3.0.5 => 3.0.6
    gatsby-plugin-react-svg: ^2.0.0 => 2.0.0
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-segment-js: ^3.0.1 => 3.0.1
    gatsby-plugin-sharp: ^2.0.22 => 2.0.22
    gatsby-plugin-sitemap: ^2.0.6 => 2.0.6
    gatsby-plugin-styled-components: ^3.0.6 => 3.0.6
    gatsby-remark-autolink-headers: ^2.0.14 => 2.0.14
    gatsby-remark-copy-linked-files: ^2.0.9 => 2.0.9
    gatsby-remark-images: ^3.0.5 => 3.0.5
    gatsby-remark-prismjs: ^3.2.4 => 3.2.4
    gatsby-remark-responsive-iframe: ^2.0.9 => 2.0.9
    gatsby-source-contentful: ^2.0.32 => 2.0.32
    gatsby-source-filesystem: ^2.0.22 => 2.0.22
    gatsby-transformer-remark: ^2.2.6 => 2.2.6
    gatsby-transformer-sharp: ^2.1.13 => 2.1.14
  npmGlobalPackages:
    gatsby-cli: 2.4.11
```
+ the instance I'm using has 16GB of memory

## Related?
Maybe this is related to https://github.com/gatsbyjs/gatsby/issues/4746 ?

**Comment by freiksenet** [comment]
Thank you for the report! We can't do the build with the linked repro, cause it uses some private packages. I wonder if it's possible to remove them, that would really help us.

Thanks a lot!

**Comment by youmustfight** [comment]
Hey @freiksenet! I just removed the private dependencies and environment requirements.

Found something interesting. For times sake I decide to prune out StaticQuery components and page level queries for things I was grabbing from Contentful. This reduced the graphql query count from around ~96,000 to 83,000.

But most interesting off all, the build was successful!!! 🤔 ??? 

Here are some things I changed touching city pages (since that was triggering the unhandled rejection when getting bigger):

1- 
Removed `gatsby-plugin-segment-js'`
Handles a header injection on each page.
https://github.com/youmustfight/gatsby_build_breaker/commit/45a424f71a3b8c5ddef450e97523bbe507ff2309#diff-b9e136416b90437fa1dac910280b45fcL44

2-
Removed `gatsby-source-contentful`
Just mentioning since I got rid of page/static queries for Contentful content

3-
Removed the StaticQuery(via Contentful) for a "Read User Stories" footer component that sits on **every city page and their various children pages** 
https://github.com/youmustfight/gatsby_build_breaker/commit/688074cc39df4239e60ac71fd27d2f7d27488088#diff-63e9885a01e7bde9d4166e9ae143259aL36

4-
Don't think this matters but just mentioning incase. There is a "Read Bankruptcy Articles" component with another StaticQuery for Contentful but this component is hidden because a property of the footer is false.
File removing StaticQuery - https://github.com/youmustfight/gatsby_build_breaker/commit/688074cc39df4239e60ac71fd27d2f7d27488088#diff-7cbd657bd1049677d146e13113ca766bL67
Logic that hides the component in those state/city templates - https://github.com/youmustfight/gatsby_build_breaker/blob/master/src/components/Layout/Footer.jsx#L50


I'm going to try adding things back in and see if I can get it to break again. Will keep you posted!

**Comment by youmustfight** [comment]
Eh tried removing that component's static query and didn't seem to do anything :/

**Comment by freiksenet** [comment]
Thanks a lot for the repro!

I managed to build it on my thinkpad (though I do have 16GB of RAM). Seems it might be dependent on that.

The big issue atm is that we can't see the actual error because it's swallowed by the console reporter. Could you try running it again with console.log in the "error" function in reporter/index.js? (You can for example edit it directly in node_modules). I'll ask my colleagues if they can get the build to fail too.

**Comment by youmustfight** [comment]
Not sure if this is helpful but some input/outputs for reporter and create-cli

Create-CLI `handlerP`
```
{ _: [ 'build' ],
  help: false,
  h: false,
  version: false,
  v: false,
  verbose: false,
  'no-color': false,
  noColor: false,
  'prefix-paths': false,
  prefixPaths: false,
  'no-uglify': false,
  noUglify: false,
  '$0': 'node_modules/.bin/gatsby',
  'open-tracing-config-file': undefined }
```

Reporter's `panic` function arguments
```
undefined
```

Reporter's `error` function arguments
message => 
```
UNHANDLED REJECTION
```
error =>
```
TypeError: Cannot read property 'message' of undefined
    at ConsoleReporter.error (/home/ec2-user/upsolve/upsolve_frontdoor/node_modules/gatsby-cli/lib/reporter/index.js:82:23)
    at ConsoleReporter.panic (/home/ec2-user/upsolve/upsolve_frontdoor/node_modules/gatsby-cli/lib/reporter/index.js:60:10)
    at Promise.resolve.then.err (/home/ec2-user/upsolve/upsolve_frontdoor/node_modules/gatsby-cli/lib/create-cli.js:20:94)
    at tryCatcher (/home/ec2-user/upsolve/upsolve_frontdoor/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ec2-user/upsolve/upsolve_frontdoor/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ec2-user/upsolve/upsolve_frontdoor/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ec2-user/upsolve/upsolve_frontdoor/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ec2-user/upsolve/upsolve_frontdoor/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/home/ec2-user/upsolve/upsolve_frontdoor/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/ec2-user/upsolve/upsolve_frontdoor/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/ec2-user/upsolve/upsolve_frontdoor/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ec2-user/upsolve/upsolve_frontdoor/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

Create CLI handleP's Promise error handler =>
```
error UNHANDLED REJECTION
```
