### ISSUE TITLE
Build failed with gatsby-transformer-asciidoc in new project

### ISSUE THREAD

**Issue by dumazy** [gatsbyjs/gatsby#13097]
## Description

The build fails to compile after adding `gatsby-transformer-asciidoc` to the plugins.

### Steps to reproduce

Create new project with command: `gatsby new site`
Go into the project: `cd site`
Add asciidoc transformer: `yarn add gatsby-transformer-asciidoc`
Add transformer to plugins in gatsby-config.js: 
```
plugins: [
    'gatsby-transformer-asciidoc', 
    ... //other plugins
],
```
Run `gatsby develop`

### Expected result

Expect build to compile and run

### Actual result

I got the following error message:

 ```
ERROR  Failed to compile with 1 errors                                                                                               23:22:07

 error  in ./.cache/app.js

Module build failed (from ./node_modules/eslint-loader/index.js):
TypeError: Cannot read property 'length' of undefined
    at Function.module.exports.SpecialString._countChars (/Users/frederik.dumazy/.config/yarn/global/node_modules/renderkid/lib/layout/SpecialString.js:139:17)
    at Object.module.exports.SpecialString._getLength (/Users/frederik.dumazy/.config/yarn/global/node_modules/renderkid/lib/layout/SpecialString.js:92:10)
    at Object.length (/Users/frederik.dumazy/.config/yarn/global/node_modules/renderkid/lib/layout/SpecialString.js:170:28)
    at /Users/frederik.dumazy/Developer/Private/dumazy.be/site/node_modules/object-hash/index.js:246:33
    at Array.forEach (<anonymous>)
    at Object._object (/Users/frederik.dumazy/Developer/Private/dumazy.be/site/node_modules/object-hash/index.js:242:21)
    at Object.dispatch (/Users/frederik.dumazy/Developer/Private/dumazy.be/site/node_modules/object-hash/index.js:185:30)
    at /Users/frederik.dumazy/Developer/Private/dumazy.be/site/node_modules/object-hash/index.js:246:18
    at Array.forEach (<anonymous>)
    at Object._object (/Users/frederik.dumazy/Developer/Private/dumazy.be/site/node_modules/object-hash/index.js:242:21)
    at Object._function (/Users/frederik.dumazy/Developer/Private/dumazy.be/site/node_modules/object-hash/index.js:319:14)
    at Object.dispatch (/Users/frederik.dumazy/Developer/Private/dumazy.be/site/node_modules/object-hash/index.js:185:30)
    at /Users/frederik.dumazy/Developer/Private/dumazy.be/site/node_modules/object-hash/index.js:246:18
    at Array.forEach (<anonymous>)
    at Object._object (/Users/frederik.dumazy/Developer/Private/dumazy.be/site/node_modules/object-hash/index.js:242:21)
    at Object.dispatch (/Users/frederik.dumazy/Developer/Private/dumazy.be/site/node_modules/object-hash/index.js:185:30)

 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app

✖ ｢wdm｣: 
ERROR in ./.cache/app.js
Module build failed (from ./node_modules/eslint-loader/index.js):
TypeError: Cannot read property 'length' of undefined
    at Function.module.exports.SpecialString._countChars (/Users/frederik.dumazy/.config/yarn/global/node_modules/renderkid/lib/layout/SpecialString.js:139:17)
    at Object.module.exports.SpecialString._getLength (/Users/frederik.dumazy/.config/yarn/global/node_modules/renderkid/lib/layout/SpecialString.js:92:10)
    at Object.length (/Users/frederik.dumazy/.config/yarn/global/node_modules/renderkid/lib/layout/SpecialString.js:170:28)
    at /Users/frederik.dumazy/Developer/Private/dumazy.be/site/node_modules/object-hash/index.js:246:33
    at Array.forEach (<anonymous>)
    at Object._object (/Users/frederik.dumazy/Developer/Private/dumazy.be/site/node_modules/object-hash/index.js:242:21)
    at Object.dispatch (/Users/frederik.dumazy/Developer/Private/dumazy.be/site/node_modules/object-hash/index.js:185:30)
    at /Users/frederik.dumazy/Developer/Private/dumazy.be/site/node_modules/object-hash/index.js:246:18
    at Array.forEach (<anonymous>)
    at Object._object (/Users/frederik.dumazy/Developer/Private/dumazy.be/site/node_modules/object-hash/index.js:242:21)
    at Object._function (/Users/frederik.dumazy/Developer/Private/dumazy.be/site/node_modules/object-hash/index.js:319:14)
    at Object.dispatch (/Users/frederik.dumazy/Developer/Private/dumazy.be/site/node_modules/object-hash/index.js:185:30)
    at /Users/frederik.dumazy/Developer/Private/dumazy.be/site/node_modules/object-hash/index.js:246:18
    at Array.forEach (<anonymous>)
    at Object._object (/Users/frederik.dumazy/Developer/Private/dumazy.be/site/node_modules/object-hash/index.js:242:21)
    at Object.dispatch (/Users/frederik.dumazy/Developer/Private/dumazy.be/site/node_modules/object-hash/index.js:185:30)
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app commons[2]
ℹ ｢wdm｣: Failed to compile.
```

### Environment
```
System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.10.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 63.0.3
    Safari: 12.1
  npmPackages:
    gatsby: ^2.3.5 => 2.3.5 
    gatsby-image: ^2.0.37 => 2.0.37 
    gatsby-plugin-manifest: ^2.0.26 => 2.0.26 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.11 => 3.0.11 
    gatsby-plugin-sharp: ^2.0.32 => 2.0.32 
    gatsby-source-filesystem: ^2.0.28 => 2.0.28 
    gatsby-transformer-asciidoc: ^1.0.2 => 1.0.2 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17 
```

**Comment by pieh** [comment]
Can you share reproduction?
The example we have ( https://github.com/gatsbyjs/gatsby/tree/master/examples/using-asciidoc ) does work, so there must be some case that we didn't hit there that is causing this.

**Comment by dumazy** [comment]
I've uploaded the reproduction here:
https://github.com/dumazy/gatsby-issue-13097

**Comment by pieh** [comment]
This is very confusing. I definitely can reproduce it with your repro

**Comment by pieh** [comment]
Honestly I have no idea what exactly is happening - it seems like some weirdness with `asciidoctor.js` package (tool that our plugin uses internally) and using builtin `eslint-loader`. As a workaround you can create almost empty `.eslintrc` file in your project that contains just `{}` - this will disable builtin `eslint-loader` and workaround this problem for now.

Seems like one of dependencies of `asciidoctor.js` (`opal-runtime`) is modyfying some global objects. So this is really bug there. It seems like that dependency is pinned to `1.0.11` version in `asciidoctor.js` while `1.0.13` is already released and seems to contain fix for it. So another workaround is to add:
```
  "resolutions": {
    "opal-runtime": "1.0.13"
  },
```
to your `package.json` (if you are using `yarn`)

**Comment by pieh** [comment]
I've found issue that seems semi related (at least altering global / fundamental objects part that cause this issue). So for more proper fix let's track this issue - https://github.com/asciidoctor/asciidoctor.js/issues/651#issuecomment-479873173
