### ISSUE TITLE
[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by vai0** [gatsbyjs/gatsby#13094]
## Description

Since updating to node v10.15.3 from v8.9.4, on build, I'm now seeing the following warning.

```
> gatsby develop --port 9000

success open and validate gatsby-configs — 0.402 s
success load plugins — 0.373 s
success onPreInit — 0.005 s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's not any stale
data
success initialize cache — 0.022 s
success copy gatsby files — 0.060 s
⠁ (node:49346) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
success onPreBootstrap — 1.019 s
success source and transform nodes — 1.725 s
success building schema — 0.440 s
success createPages — 0.066 s
success createPagesStatefully — 0.788 s
...
```

### Steps to reproduce

Am able to reproduce with node.js v10.15.3 on our current site, although it is strange I have not seen others encounter this issue yet with Gatsby. Will eventually try running a gatsby starter in the same node environment.

### Environment

```
  System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 4.4.23 - /nix/store/9fzc7vpqqq0bsxlpm3npgi4z00q9s61z-bash-interactive-4.4-p23/bin/bash
  Binaries:
    Node: 10.15.3 - /nix/store/v2bbzr3wxasxnq9mf7sryl362ahcbsfb-bifrost-env/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /nix/store/v2bbzr3wxasxnq9mf7sryl362ahcbsfb-bifrost-env/bin/npm
  Languages:
    Python: 3.6.6 - /Users/admin/Projects/bifrost/backend/venv/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 65.0.1
    Safari: 12.0
```

**Comment by pieh** [comment]
This doesn't get a lot to go through, I see that we have single use of `new Buffer` in gatsby repository directly ( https://github.com/gatsbyjs/gatsby/blob/6866e76c4f0b02221e6eac93a0582939cae49103/packages/gatsby-remark-images-contentful/src/utils/index.js#L12 ) - so unless you use this plugin this most certainly come from one of dependencies.

What would be helpful, if you could run

```
node --trace-deprecation node_modules/gatsby/dist/bin/gatsby build
```
Which should also print out stack traces for those deprecation notices, that would allow to find where exactly this is happening and see if we can bump dependencies maybe

**Comment by pieh** [comment]
Also I tried this with default starter and it didn't show deprecations there:
```
➜  gatsby-starter-default git:(master) ✗ node --trace-deprecation node_modules/gatsby/dist/bin/gatsby build
success open and validate gatsby-configs — 0.004 s
success load plugins — 0.151 s
success onPreInit — 0.005 s
success delete html and css files from previous builds — 0.023 s
success initialize cache — 0.005 s
success copy gatsby files — 0.062 s
success onPreBootstrap — 0.249 s
success source and transform nodes — 0.146 s
success building schema — 0.179 s
success createPages — 0.000 s
success createPagesStatefully — 0.039 s
success onPreExtractQueries — 0.002 s
success update schema — 0.016 s
success extract queries from components — 0.064 s
success run graphql queries — 0.036 s — 7/7 203.57 queries/second
success write out page data — 0.002 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.110 s

info bootstrap finished - 3.579 s

success Building production JavaScript and CSS bundles — 2.327 s
success Building static HTML for pages — 0.383 s — 4/4 19.69 pages/second
info Done building in 6.293 sec
➜  gatsby-starter-default git:(master) ✗ node -v
v10.15.3
➜  gatsby-starter-default git:(master) ✗ gatsby info

  System:
    OS: macOS 10.14
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Firefox: 66.0.1
    Safari: 12.0
  npmPackages:
    gatsby: ^2.3.5 => 2.3.5
    gatsby-image: ^2.0.37 => 2.0.37
    gatsby-plugin-manifest: ^2.0.26 => 2.0.26
    gatsby-plugin-offline: ^2.0.25 => 2.0.25
    gatsby-plugin-react-helmet: ^3.0.11 => 3.0.11
    gatsby-plugin-sharp: ^2.0.32 => 2.0.32
    gatsby-source-filesystem: ^2.0.28 => 2.0.28
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17

➜  gatsby-starter-default git:(master) ✗
```
So this looks like it comes from dependencies of one of the plugins probably (possibly one of plugins we maintain here, just not use in default starter or in one of community plugins)

**Comment by pieh** [comment]
Oh, actually after enabling ` --pending-deprecation` I can see it:
```
➜  gatsby-starter-default git:(master) ✗ node --trace-deprecation --pending-deprecation node_modules/gatsby/dist/bin/gatsby build
success open and validate gatsby-configs — 0.004 s
success load plugins — 0.148 s
success onPreInit — 0.004 s
success delete html and css files from previous builds — 0.025 s
success initialize cache — 0.005 s
success copy gatsby files — 0.056 s
success onPreBootstrap — 0.258 s
⠁ (node:42328) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (buffer.js:159:11)
    at new Buffer (buffer.js:174:3)
    at Object.<anonymous> (/Users/misiek/dev/gatsby-starter-default/node_modules/load-bmfont/lib/is-binary.js:2:14)
    at Module._compile (/Users/misiek/dev/gatsby-starter-default/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/Users/misiek/dev/gatsby-starter-default/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/misiek/dev/gatsby-starter-default/node_modules/load-bmfont/index.js:10:16)
    at Module._compile (/Users/misiek/dev/gatsby-starter-default/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
success source and transform nodes — 0.157 s
success building schema — 0.179 s
success createPages — 0.000 s
success createPagesStatefully — 0.044 s
success onPreExtractQueries — 0.002 s
success update schema — 0.016 s
success extract queries from components — 0.067 s
success run graphql queries — 0.039 s — 7/7 187.63 queries/second
success write out page data — 0.003 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.116 s
```

**Comment by vai0** [comment]
@pieh 
```
> node --trace-deprecation --pending-deprecation node_modules/gatsby/dist/bin/gatsby build
...
(node:56772) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (buffer.js:159:11)
    at new Buffer (buffer.js:174:3)
    at fetchEloqua (/Users/admin/Projects/bifrost/frontend/gatsby-node.js:47:20)
    at resolve (/Users/admin/Projects/bifrost/frontend/gatsby-node.js:60:20)
    at new Promise (<anonymous>)
    at getElqBaseUrl (/Users/admin/Projects/bifrost/frontend/gatsby-node.js:56:12)
    at resolve (/Users/admin/Projects/bifrost/frontend/gatsby-node.js:98:9)
    at new Promise (<anonymous>)
    at Object.exports.onPreBootstrap (/Users/admin/Projects/bifrost/frontend/gatsby-node.js:97:12)
    at runAPI (/Users/admin/Projects/bifrost/frontend/node_modules/gatsby/dist/utils/api-runner-node.js:212:37)
    at resolve (/Users/admin/Projects/bifrost/frontend/node_modules/gatsby/dist/utils/api-runner-node.js:335:19)
    at Promise._execute (/Users/admin/Projects/bifrost/frontend/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/Users/admin/Projects/bifrost/frontend/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/admin/Projects/bifrost/frontend/node_modules/bluebird/js/release/promise.js:79:10)
    at Promise.mapSeries.plugin (/Users/admin/Projects/bifrost/frontend/node_modules/gatsby/dist/utils/api-runner-node.js:334:16)
    at tryCatcher (/Users/admin/Projects/bifrost/frontend/node_modules/bluebird/js/release/util.js:16:23)
...
```
Seems to be coming from Gatsby's bluebird promise dependency

**Comment by pieh** [comment]
We removed bluebird recently - what's the gatsby version you are using?

**Comment by vai0** [comment]
@pieh  2.3.7

**Comment by anilverma087** [comment]
Getting  same issue do not have Buffer() in  my  code 

can any  bode sugget  where to  make changes 

I am hosting node js api  on IIS with  HTTPS getting  this error

The last 64k of the output generated by the node.exe process to stderr is shown below:

(node:14884) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by Joohangooi** [comment]
@anilverma087 May I ask have you overcome this issue? If yes, may you share how you solve it? appreciate.
