### ISSUE TITLE
[1.0] gatsby-plugin-postcss-sass produces a missing config error

### ISSUE THREAD

**Issue by levibuzolic** [gatsbyjs/gatsby#1346]
Will try and get some time later today to put together a breaking example site, but creating this issue incase I'm missing something obvious.

```bash
$ gatsby develop
success open and validate gatsby-config.js — 0.004 s

One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's not any stale
data

success copy gatsby files — 0.018 s
success source and transform nodes — 0.023 s
success building schema — 0.084 s
success createPages — 0.004 s
success createPagesStatefully — 0.029 s
success extract queries from components — 0.064 s
success run graphql queries — 0.036 s
success write out page data — 0.003 s
success update schema — 0.040 s

bootstrap finished, time since started: 1.392 s

 ERROR  Failed to compile with 22 errors

# ---------- 21 basically identical errors ----------

Module build failed: Error: No PostCSS Config found in: /Users/levi/src/gatsby-test/src/components/TextInput
    at /Users/levi/src/gatsby-test/node_modules/postcss-load-config/index.js:51:26
    at tryCatch (/Users/levi/src/gatsby-test/node_modules/es6-promise/dist/es6-promise.js:416:12)
    at invokeCallback (/Users/levi/src/gatsby-test/node_modules/es6-promise/dist/es6-promise.js:431:13)
    at publish (/Users/levi/src/gatsby-test/node_modules/es6-promise/dist/es6-promise.js:399:7)
    at flush (/Users/levi/src/gatsby-test/node_modules/es6-promise/dist/es6-promise.js:126:5)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)

 @ ./src/components/TextInput/styles.module.scss 4:14-275 13:2-17:4 14:20-281
```

Tried with `postCssPlugins` specified and not specified.

```javascript
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-plugin-postcss-sass',
      options: {
        postCssPlugins: [require('autoprefixer')()]
      }
    },
  ],
}

// also tried

module.exports = {
  plugins: ['gatsby-plugin-postcss-sass'],
}
```

**Comment by levibuzolic** [comment]
Actually looks like it might be an issue with my code. Going to investigate further.
