### ISSUE TITLE
[v1.0]  GraphQL schema build fails if gatsby-config.js contains nested arrays.

### ISSUE THREAD

**Issue by Vagr9K** [gatsbyjs/gatsby#1350]
`gatsby-config.js`
```js
module.exports = {
  siteMetadata: {
    siteTitle: 'Gatsby Material Starter',
    linkPrefix: '/gatsby-material-starter',
    postDefaultCategoryID: '12121212',
    userName: 'Material User',
    userLocation: 'Yerevan, Armenia',
    userAvatar: 'https://api.adorable.io/avatars/150/test.png',
    userDescription: "Yeah, I like animals better than people sometimes... Especially dogs. Dogs are the best. Every time you come home, they act like they haven't seen you in a year. And the good thing about dogs... is they got different dogs for different people.",
    userLinks: [
     ['Website', '//mywebsite.example.local', 'fa fa-link'],
     ['GitHub', '//github.com.local/USER', 'fa fa-github'],
     ['Twitter', '//twitter.local/USER', 'fa fa-twitter'],
     ['Instagram', '//instagram.local/USER', 'fa fa-instagram'],
     ['Facebook', '//facebook.com.local/USER', 'fa fa-facebook'],
     ['Email', 'mailto:gmail.com.local/USER', 'fa fa-envelope'],
    ],
    copyright: 'Copyright © 2017. Material User',
  },
};
```

Error:
```sh
⠂ building schemaUNHANDLED REJECTION TypeError: key.replace is not a function                                                                                                      
    at module.exports (/home/ruben/Git/gatsby-starter-material/node_modules/gatsby/dist/schema/create-key.js:11:14)                                                                
    at /home/ruben/Git/gatsby-starter-material/node_modules/gatsby/dist/schema/infer-graphql-type.js:525:20                                                                        
    at arrayEach (/home/ruben/Git/gatsby-starter-material/node_modules/lodash/lodash.js:537:11)                                                                                    
    at Function.forEach (/home/ruben/Git/gatsby-starter-material/node_modules/lodash/lodash.js:9359:14)                                                                            
    at inferObjectStructureFromNodes (/home/ruben/Git/gatsby-starter-material/node_modules/gatsby/dist/schema/infer-graphql-type.js:475:5)                                         
    at inferGraphQLType (/home/ruben/Git/gatsby-starter-material/node_modules/gatsby/dist/schema/infer-graphql-type.js:100:17)                                                     
    at /home/ruben/Git/gatsby-starter-material/node_modules/gatsby/dist/schema/infer-graphql-type.js:514:23                                                                        
    at /home/ruben/Git/gatsby-starter-material/node_modules/lodash/lodash.js:4944:15                                                                                               
    at baseForOwn (/home/ruben/Git/gatsby-starter-material/node_modules/lodash/lodash.js:3001:24)                                                                                  
    at /home/ruben/Git/gatsby-starter-material/node_modules/lodash/lodash.js:4913:18                                                                                               
    at Function.forEach (/home/ruben/Git/gatsby-starter-material/node_modules/lodash/lodash.js:9359:14)                                                                            
    at inferObjectStructureFromNodes (/home/ruben/Git/gatsby-starter-material/node_modules/gatsby/dist/schema/infer-graphql-type.js:475:5)                                         
    at inferGraphQLType (/home/ruben/Git/gatsby-starter-material/node_modules/gatsby/dist/schema/infer-graphql-type.js:165:19)                                                     
    at /home/ruben/Git/gatsby-starter-material/node_modules/gatsby/dist/schema/infer-graphql-type.js:514:23                                                                        
    at /home/ruben/Git/gatsby-starter-material/node_modules/lodash/lodash.js:4944:15                                                                                               
    at baseForOwn (/home/ruben/Git/gatsby-starter-material/node_modules/lodash/lodash.js:3001:24)  

```

Happens only with nested arrays. Objects in arrays or only one top level array work fine.

EDIT: The offender here is `userLinks` if it's not clear.

**Comment by KyleAMathews** [comment]
This is a known problem and perhaps is not handleable — haven't researched it much since it hasn't come up much before. The problem is arising when Gatsby infers your site's data structure for creating the GraphQL schema.

We need a better error message for sure but for now, avoid nested arrays.

**Comment by Vagr9K** [comment]
OK, got it.

**Comment by KyleAMathews** [comment]
This should be working now!
