### ISSUE TITLE
cjpeg on 32-bit machine

### ISSUE THREAD

**Issue by k-five** [gatsbyjs/gatsby#13599]
## Description

I am using a 32-bit machine. 

### Steps to reproduce

I used the step on doc page:
https://www.gatsbyjs.org/docs/quick-start

Since it is a 32-bit machine I built the `libvips` from source 

here is the full log for **new** project
the `cjpeg -version` has been failed 

```bash
gatsby new  somareact-doc
info Creating new site from git: https://github.com/gatsbyjs/gatsby-starter-default.git
Cloning into 'somareact-doc'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 1548 (delta 15), reused 17 (delta 8), pack-reused 1524
Receiving objects: 100% (1548/1548), 5.68 MiB | 242.00 KiB/s, done.
Resolving deltas: 100% (930/930), done.
Checking connectivity... done.
success Created starter directory layout
info Installing packages...

> sharp@0.21.3 install /var/www/html/front-end/somareact-doc/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Detected globally-installed libvips v8.7.4
info sharp Building from source via node-gyp
make: Entering directory '/var/www/html/front-end/somareact-doc/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  SOLINK_MODULE(target) Release/obj.target/sharp.node
  COPY Release/sharp.node
make: Leaving directory '/var/www/html/front-end/somareact-doc/node_modules/sharp/build'

> gatsby-telemetry@1.0.7 postinstall /var/www/html/front-end/somareact-doc/node_modules/gatsby-telemetry
> node src/postinstall.js


> cwebp-bin@5.0.0 postinstall /var/www/html/front-end/somareact-doc/node_modules/cwebp-bin
> node lib/install.js

  ✔ cwebp pre-build test passed successfully

> mozjpeg@6.0.1 postinstall /var/www/html/front-end/somareact-doc/node_modules/mozjpeg
> node lib/install.js

  ⚠ Command failed: /var/www/html/front-end/somareact-doc/node_modules/mozjpeg/vendor/cjpeg -version
/var/www/html/front-end/somareact-doc/node_modules/mozjpeg/vendor/cjpeg: 1: /var/www/html/front-end/somareact-doc/node_modules/mozjpeg/vendor/cjpeg: ELF: not found
/var/www/html/front-end/somareact-doc/node_modules/mozjpeg/vendor/cjpeg: 2: /var/www/html/front-end/somareact-doc/node_modules/mozjpeg/vendor/cjpeg: �: not found
/var/www/html/front-end/somareact-doc/node_modules/mozjpeg/vendor/cjpeg: 3: /var/www/html/front-end/somareact-doc/node_modules/mozjpeg/vendor/cjpeg: �: not found
/var/www/html/front-end/somareact-doc/node_modules/mozjpeg/vendor/cjpeg: 4: /var/www/html/front-end/somareact-doc/node_modules/mozjpeg/vendor/cjpeg: �j�jI�: not found
/var/www/html/front-end/somareact-doc/node_modules/mozjpeg/vendor/cjpeg: 5: /var/www/html/front-end/somareact-doc/node_modules/mozjpeg/vendor/cjpeg: ▒�j▒�j�@@DDP�tdxK: not found
/var/www/html/front-end/somareact-doc/node_modules/mozjpeg/vendor/cjpeg: 6: /var/www/html/front-end/somareact-doc/node_modules/mozjpeg/vendor/cjpeg: Syntax error: ")" unexpected


  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c autoreconf -fiv
/bin/sh: 1: autoreconf: not found


    at Promise.all.then.arr (/var/www/html/front-end/somareact-doc/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

> pngquant-bin@5.0.2 postinstall /var/www/html/front-end/somareact-doc/node_modules/pngquant-bin
> node lib/install.js

  ✔ pngquant pre-build test passed successfully
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ia32"})

added 1703 packages from 987 contributors and audited 25689 packages in 154.388s
found 0 vulnerabilities

info Initialising git in somareact-doc
Initialized empty Git repository in /var/www/html/front-end/somareact-doc/.git/
info Create initial git commit in somareact-doc
```

then if I run 

```bash
gatsby develop
success open and validate gatsby-configs — 0.025 s
⠁ 
      The dependency "sharp" does not seem to have been built or installed correctly.

      - Try to reinstall packages and look for errors during installation
      - Consult "sharp" installation page at http://sharp.pixelplumbing.com/en/stable/install/
      
      If neither of the above work, please open an issue in https://github.com/gatsbyjs/gatsby/issues
```

It complains about **sharp** while I have installed correctly

### Expected result

It should NOT be 64-bit, right?

```bash
$ pwd
/var/www/html/front-end/somareact-doc/node_modules/mozjpeg/vendor
$ ls
cjpeg
$ ./cjpeg -version
bash: ./cjpeg: cannot execute binary file: Exec format error
$ file cjpeg 
cjpeg: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib, for GNU/Linux 2.6.32, BuildID[sha1]=5bebcbc9d504e1c209d9a532cc72bcc81e21387e, not stripped
```

### Actual result

  - `cjpeg` should be 32-bit
  - somehow notify users about tools requirement like `autoreconf` which here seems I do not have it.
 - 5 times trying, every time 250+MB download && nothing at last!

### Environment

```bash
  System:
    OS: Linux 4.8 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (2) ia32 Intel(R) Pentium(R) Dual  CPU  E2180  @ 2.00GHz
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 8.9.1 - ~/.nvm/versions/node/v8.9.1/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v8.9.1/bin/npm
  Languages:
    Python: 2.7.12 - /usr/bin/python
  Browsers:
    Firefox: 66.0.3
  npmPackages:
    gatsby: ^2.3.27 => 2.3.27 
    gatsby-image: ^2.0.40 => 2.0.40 
    gatsby-plugin-manifest: ^2.0.29 => 2.0.29 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.0.35 => 2.0.35 
    gatsby-source-filesystem: ^2.0.31 => 2.0.31 
    gatsby-transformer-sharp: ^2.1.18 => 2.1.18 
  npmGlobalPackages:
    gatsby-cli: 2.5.9
```

**Comment by pieh** [comment]
I think this should be reported in https://github.com/mozilla/mozjpeg repository, because there is nothing we can do here about it (and we also weren't aware of this problem previously)

Seems like prebuilt binaries are just for x64 (there is no distinction for arch, just platform): https://unpkg.com/mozjpeg@6.0.1/lib/index.js (hence ELF signature stating x64)

and building from source requires `autoreconf` (as you mentioned) - https://unpkg.com/mozjpeg@6.0.1/lib/install.js (but even then I'm not sure if it would build - they have documentation for x32 in https://github.com/mozilla/mozjpeg/blob/master/BUILDING.md but I have no idea if it works, given that `autoreconf` is not mentioned)

**Comment by k-five** [comment]
I expected that a world-class CLI like yours had a better dependency management.
32-bit machines are not new and there are many of them out running. 

> I think this should be reported in https://github.com/mozilla/mozjpeg repository, because there is nothing we can do here about it (and we also weren't aware of this problem previously)

Your CLI should do some kind of checking or prerequisite checking.

> I have no idea if it works, given that autoreconf is not mentioned)

Nether have I.
And thank you for quick reply. You can close the issue.

**Comment by DSchau** [comment]
@k-five sorry for the issue--generally there are a _lot_ of checks we could add, but each check we add introduces complexity which may not be worth the smaller % of people using e.g. a 32-bit machine.

Thanks for reporting!
