### ISSUE TITLE
Error: Cannot find module './showAnalyticsNotification' on installation

### ISSUE THREAD

**Issue by broskoski** [gatsbyjs/gatsby#13603]
## Description

Seeing `Error: Cannot find module './showAnalyticsNotification'` on installation

### Steps to reproduce

- Run ` npm install -g gatsby-cli`

### Expected result

Gatsby CLI should install without error

### Actual result
`Error: Cannot find module './showAnalyticsNotification'`

### Environment

Node v8.10.0

**Comment by broskoski** [comment]
Detailed stack trace:

```
/.nvm/versions/node/v8.10.0/bin/gatsby -> /.nvm/versions/node/v8.10.0/lib/node_modules/gatsby-cli/lib/index.js

> gatsby-telemetry@1.0.8 postinstall /.nvm/versions/node/v8.10.0/lib/node_modules/gatsby-cli/node_modules/gatsby-telemetry
> node src/postinstall.js

module.js:549
    throw err;
    ^

Error: Cannot find module './showAnalyticsNotification'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/.nvm/versions/node/v8.10.0/lib/node_modules/gatsby-cli/node_modules/gatsby-telemetry/src/postinstall.js:1:97)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-telemetry@1.0.8 postinstall: `node src/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gatsby-telemetry@1.0.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by scottschup** [comment]
Similar issue here: 
```
+ npm install -g lerna gatsby-cli
/home/jenkins/.nvm/versions/node/v8.16.0/bin/gatsby -> /home/jenkins/.nvm/versions/node/v8.16.0/lib/node_modules/gatsby-cli/lib/index.js
/home/jenkins/.nvm/versions/node/v8.16.0/bin/lerna -> /home/jenkins/.nvm/versions/node/v8.16.0/lib/node_modules/lerna/cli.js

> gatsby-telemetry@1.0.8 postinstall /home/jenkins/.nvm/versions/node/v8.16.0/lib/node_modules/gatsby-cli/node_modules/gatsby-telemetry
> node src/postinstall.js

module.js:550
    throw err;
    ^

Error: Cannot find module './showAnalyticsNotification'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/jenkins/.nvm/versions/node/v8.16.0/lib/node_modules/gatsby-cli/node_modules/gatsby-telemetry/src/postinstall.js:1:97)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

Gatsby version is `^1.6.5` in `package.json`, gatsby-cli is `^1.1.28`.

Can't replicate locally; error only occurs during Jenkins build job.

**Comment by broskoski** [comment]
Appears to have been fixed in https://github.com/gatsbyjs/gatsby/pull/13605 . 

Clearing npm cache (locally) and retrying worked for me.

**Comment by pieh** [comment]
As @broskoski mentioned - this should be fixed after https://github.com/gatsbyjs/gatsby/pull/13605 - so please re-trigger jenkins job (and potentially update lock files if you use them). Problematic release was `latest` for few minutes, but newest should not have this problem
