### ISSUE TITLE
[1.0] gatsby-plugin-feed errors out

### ISSUE THREAD

**Issue by chiedo** [gatsbyjs/gatsby#1371]
I haven't been able to get this plugin working with the latest npm package.

Has this package been tested and confirmed to be working or is it still a work in progress?

The default query contains [this line](https://github.com/gatsbyjs/gatsby/blob/1.0/packages/gatsby-plugin-feed/src/internals.js#L51) but I'm pretty sure that couldn't work and is instead supposed to be 

```
          filter: {
          	frontmatter: {
            	draft: { ne: true }
          	}
          }
``` 

Even with that change though, I get this large error which is pretty unhelpful as far as debugging is concerned.

```
Error: TypeError: Cannot read property 'markdownRemark' of undefined
    at BlogPostTemplate.render (render-page.js:41920:34)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (render-page.js:15604:31)
    at ReactCompositeComponentWrapper._renderValidatedComponent (render-page.js:15627:33)
    at ReactCompositeComponentWrapper.performInitialMount (render-page.js:15167:31)
    at ReactCompositeComponentWrapper.mountComponent (render-page.js:15063:22)
    at Object.mountComponent (render-page.js:7975:36)
    at ReactCompositeComponentWrapper.performInitialMount (render-page.js:15176:35)
    at ReactCompositeComponentWrapper.mountComponent (render-page.js:15063:22)
    at Object.mountComponent (render-page.js:7975:36)
    at ReactDOMComponent.mountChildren (render-page.js:14204:45),TypeError: Cannot read property 'markdownRemark' of undefined
    at BlogPostTemplate.render (render-page.js:41920:34)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (render-page.js:15604:31)
    at ReactCompositeComponentWrapper._renderValidatedComponent (render-page.js:15627:33)
    at ReactCompositeComponentWrapper.performInitialMount (render-page.js:15167:31)
    at ReactCompositeComponentWrapper.mountComponent (render-page.js:15063:22)
    at Object.mountComponent (render-page.js:7975:36)
    at ReactCompositeComponentWrapper.performInitialMount (render-page.js:15176:35)
    at ReactCompositeComponentWrapper.mountComponent (render-page.js:15063:22)
    at Object.mountComponent (render-page.js:7975:36)
    at ReactDOMComponent.mountChildren (render-page.js:14204:45),TypeError: Cannot read property 'markdownRemark' of undefined
    at BlogPostTemplate.render (render-page.js:41920:34)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (render-page.js:15604:31)
    at ReactCompositeComponentWrapper._renderValidatedComponent (render-page.js:15627:33)
    at ReactCompositeComponentWrapper.performInitialMount (render-page.js:15167:31)
    at ReactCompositeComponentWrapper.mountComponent (render-page.js:15063:22)
    at Object.mountComponent (render-page.js:7975:36)
    at ReactCompositeComponentWrapper.performInitialMount (render-page.js:15176:35)
    at ReactCompositeComponentWrapper.mountComponent (render-page.js:15063:22)
    at Object.mountComponent (render-page.js:7975:36)
    at ReactDOMComponent.mountChildren (render-page.js:14204:45),TypeError: Cannot read property 'charAt' of undefined
    at render-page.js:41400:16
    at Array.map (native)
    at Object.exports.onRenderBody (render-page.js:41397:22)
    at render-page.js:41355:39
    at Array.map (native)
    at module.exports (render-page.js:41353:26)
    at module.exports (render-page.js:179:31)
    at /.../node_modules/static-site-generator-webpack-plugin/index.js:78:15,TypeError: Cannot read property 'charAt' of undefined
    at render-page.js:41400:16
    at Array.map (native)
    at Object.exports.onRenderBody (render-page.js:41397:22)
    at render-page.js:41355:39
    at Array.map (native)
    at module.exports (render-page.js:41353:26)
    at module.exports (render-page.js:179:31)
    at /.../node_modules/static-site-generator-webpack-plugin/index.js:78:15,TypeError: Cannot read property 'charAt' of undefined
    at render-page.js:41400:16
    at Array.map (native)
    at Object.exports.onRenderBody (render-page.js:41397:22)
    at render-page.js:41355:39
    at Array.map (native)
    at module.exports (render-page.js:41353:26)
    at module.exports (render-page.js:179:31)
    at /.../node_modules/static-site-generator-webpack-plugin/index.js:78:15
```

**Comment by KyleAMathews** [comment]
There isn't an example site nor is there any tests yet for this plugin so it could very well be broken. Very much looking for contributions for both!

The easiest way to debug is to ignore that stack trace (which is meaningless for graphql errors) and copy the query into graphiql.

**Comment by chiedo** [comment]
Cool!

I'll tackle this :)

**Comment by chiedo** [comment]
After spending some time looking into this, it looks to be a gatsby-transformer-remark issue.

The basic root query doesn't work after adding the plugin which is why the feed wasn't working!

```
allMarkdownRemark
``

**Comment by chiedo** [comment]
Ignore... That query is working again now.

I'm going to try and find the cause. Something I changed must have interactive as I've been making changes to the codebase today.

**Comment by ericwindmill** [comment]
Did you ever find the cause chiedo? I'm getting this error, but not until after doing a full rebuild, so I don't know where to look. But basically, anywhere that I call `this.props.data...`, data is undefined.

**Comment by chiedo** [comment]
Definitely since my site works now but I wish I could remember @ericwindmill 

That was a long time ago. :(
