### ISSUE TITLE
Developing on port 80

### ISSUE THREAD

**Issue by vavra7** [gatsbyjs/gatsby#13880]
It is not possible to develop on port 80. 

In my case since I am on Ubuntu, first I stop Apache2 occupying port 80.
`sudo service apache2 stop`

Then verifying that port 80 is really free.
`sudo netstat -tulpn | grep :80`

Attempt  to run developing at port 80
`gatsby develop --port 80`

In console shows up: 
"Something is already running at port 80 
Would you like to run the app at another port instead? [Y/n] "

If I hit "n" result is: 
"error UNHANDLED EXCEPTION
Error: listen EACCES: permission denied 127.0.0.1:80"

I tested run gatsby develop for example on port 8888 and it is working fine. A also tried expose some other service to port 80 and it has no problem so port is really free. Only gatsby throws me an exception.

System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 12.1.0 - /usr/bin/node
    npm: 6.9.0 - ~/.npm-global/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 66.0.3
  npmPackages:
    gatsby: ^2.4.1 => 2.4.1 
    gatsby-background-image: ^0.5.2 => 0.5.2 
    gatsby-image: ^2.0.41 => 2.0.41 
    gatsby-plugin-facebook-sdk: ^1.0.6 => 1.0.6 
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1 
    gatsby-plugin-offline: ^2.1.0 => 2.1.0 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.0.36 => 2.0.36 
    gatsby-source-contentful: ^2.0.55 => 2.0.55 
    gatsby-source-filesystem: ^2.0.33 => 2.0.33 
    gatsby-transformer-sharp: ^2.1.19 => 2.1.19 
  npmGlobalPackages:
    gatsby-cli: 2.5.12

**Comment by wardpeet** [comment]
could you try what the following command says? `npx detect-port 80`. We use an upstream package called [detect-port](https://github.com/node-modules/detect-port).

**Comment by vavra7** [comment]
Command returns "41137". What does it mean?

**Comment by wardpeet** [comment]
that means it couldn't get port 80 and found 41137 as a port number so something is odd. could you run `DEBUG=detect-port npx detect-port 80` it will print out some extra info.

**Comment by vavra7** [comment]
on `DEBUG=detect-port npx detect-port 80`:
```
DEBUG=detect-port npx detect-port 80
  detect-port detect free port between [80, 90) +0ms
  detect-port listen null:80 error: Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1209:19)
    at listenInCluster (net.js:1274:12)
    at Server.listen (net.js:1362:7)
    at listen (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:114:10)
    at tryListen (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:63:5)
    at module.exports (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:28:12)
    at Object.<anonymous> (/home/vavra/Projects/dev2/node_modules/detect-port/bin/detect-port:64:3)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
} +4ms
  detect-port listen null:81 error: Error: listen EACCES: permission denied 0.0.0.0:81
    at Server.setupListenHandle [as _listen2] (net.js:1209:19)
    at listenInCluster (net.js:1274:12)
    at Server.listen (net.js:1362:7)
    at listen (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:114:10)
    at tryListen (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:63:5)
    at handleError (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:46:5)
    at /home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:70:16
    at Server.<anonymous> (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:111:12)
    at Server.emit (events.js:196:13)
    at emitErrorNT (net.js:1253:8) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 81
} +2ms
  detect-port listen null:82 error: Error: listen EACCES: permission denied 0.0.0.0:82
    at Server.setupListenHandle [as _listen2] (net.js:1209:19)
    at listenInCluster (net.js:1274:12)
    at Server.listen (net.js:1362:7)
    at listen (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:114:10)
    at tryListen (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:63:5)
    at handleError (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:46:5)
    at /home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:70:16
    at Server.<anonymous> (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:111:12)
    at Server.emit (events.js:196:13)
    at emitErrorNT (net.js:1253:8) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 82
} +0ms
  detect-port listen null:83 error: Error: listen EACCES: permission denied 0.0.0.0:83
    at Server.setupListenHandle [as _listen2] (net.js:1209:19)
    at listenInCluster (net.js:1274:12)
    at Server.listen (net.js:1362:7)
    at listen (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:114:10)
    at tryListen (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:63:5)
    at handleError (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:46:5)
    at /home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:70:16
    at Server.<anonymous> (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:111:12)
    at Server.emit (events.js:196:13)
    at emitErrorNT (net.js:1253:8) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 83
} +1ms
  detect-port listen null:84 error: Error: listen EACCES: permission denied 0.0.0.0:84
    at Server.setupListenHandle [as _listen2] (net.js:1209:19)
    at listenInCluster (net.js:1274:12)
    at Server.listen (net.js:1362:7)
    at listen (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:114:10)
    at tryListen (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:63:5)
    at handleError (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:46:5)
    at /home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:70:16
    at Server.<anonymous> (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:111:12)
    at Server.emit (events.js:196:13)
    at emitErrorNT (net.js:1253:8) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 84
} +0ms
  detect-port listen null:85 error: Error: listen EACCES: permission denied 0.0.0.0:85
    at Server.setupListenHandle [as _listen2] (net.js:1209:19)
    at listenInCluster (net.js:1274:12)
    at Server.listen (net.js:1362:7)
    at listen (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:114:10)
    at tryListen (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:63:5)
    at handleError (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:46:5)
    at /home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:70:16
    at Server.<anonymous> (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:111:12)
    at Server.emit (events.js:196:13)
    at emitErrorNT (net.js:1253:8) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 85
} +0ms
  detect-port listen null:86 error: Error: listen EACCES: permission denied 0.0.0.0:86
    at Server.setupListenHandle [as _listen2] (net.js:1209:19)
    at listenInCluster (net.js:1274:12)
    at Server.listen (net.js:1362:7)
    at listen (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:114:10)
    at tryListen (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:63:5)
    at handleError (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:46:5)
    at /home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:70:16
    at Server.<anonymous> (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:111:12)
    at Server.emit (events.js:196:13)
    at emitErrorNT (net.js:1253:8) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 86
} +0ms
  detect-port listen null:87 error: Error: listen EACCES: permission denied 0.0.0.0:87
    at Server.setupListenHandle [as _listen2] (net.js:1209:19)
    at listenInCluster (net.js:1274:12)
    at Server.listen (net.js:1362:7)
    at listen (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:114:10)
    at tryListen (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:63:5)
    at handleError (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:46:5)
    at /home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:70:16
    at Server.<anonymous> (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:111:12)
    at Server.emit (events.js:196:13)
    at emitErrorNT (net.js:1253:8) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 87
} +0ms
  detect-port listen null:88 error: Error: listen EACCES: permission denied 0.0.0.0:88
    at Server.setupListenHandle [as _listen2] (net.js:1209:19)
    at listenInCluster (net.js:1274:12)
    at Server.listen (net.js:1362:7)
    at listen (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:114:10)
    at tryListen (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:63:5)
    at handleError (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:46:5)
    at /home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:70:16
    at Server.<anonymous> (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:111:12)
    at Server.emit (events.js:196:13)
    at emitErrorNT (net.js:1253:8) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 88
} +1ms
  detect-port listen null:89 error: Error: listen EACCES: permission denied 0.0.0.0:89
    at Server.setupListenHandle [as _listen2] (net.js:1209:19)
    at listenInCluster (net.js:1274:12)
    at Server.listen (net.js:1362:7)
    at listen (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:114:10)
    at tryListen (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:63:5)
    at handleError (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:46:5)
    at /home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:70:16
    at Server.<anonymous> (/home/vavra/Projects/dev2/node_modules/detect-port/lib/detect-port.js:111:12)
    at Server.emit (events.js:196:13)
    at emitErrorNT (net.js:1253:8) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 89
} +0ms
  detect-port port: 90 >= maxPort: 90, give up and use random port +0ms
  detect-port get free null:36469 +0ms
36469
```

on `sudo DEBUG=detect-port npx detect-port 80`:
```
detect-port detect free port between [80, 90) +0ms
  detect-port get free null:80 +3ms
  detect-port get free 0.0.0.0:80 +2ms
  detect-port get free localhost:80 +1ms
  detect-port get free 192.168.10.192:80 +1ms
80
```
It looks like permission error so I run also without "sudo" `DEBUG=detect-port npx detect-port 8888`:
```
  detect-port detect free port between [8888, 8898) +0ms
  detect-port get free null:8888 +3ms
  detect-port get free 0.0.0.0:8888 +2ms
  detect-port get free localhost:8888 +1ms
  detect-port get free 192.168.10.192:8888 +0ms
8888
```
So that makes me a question why does it grand a different rights for different ports? 

By the way `sudo gatsby develop --port 80` doesn't work with response: "sudo: gatsby: command not found"

**Comment by wardpeet** [comment]
It seems like this article explains why https://stackoverflow.com/questions/9164915/node-js-eacces-error-when-listening-on-most-ports

**Comment by vavra7** [comment]
You are right. Following answer from you shared topic solves the issue.

> Give Safe User Permission To Use Port 80
> 
> Remember, we do NOT want to run your applications as the root user, but there is a hitch: your safe user does not have permission to use the default HTTP port (80). You goal is to be able to publish a website that visitors can use by navigating to an easy to use URL like  http://ip:port/
> 
> Unfortunately, unless you sign on as root, you’ll normally have to use a URL like http://ip:port - where port number > 1024.
> 
> A lot of people get stuck here, but the solution is easy. There a few options but this is the one I like. Type the following commands:
> 
```
sudo apt-get install libcap2-bin
sudo setcap cap_net_bind_service=+ep `readlink -f \`which node\``
```
> Now, when you tell a Node application that you want it to run on port 80, it will not complain.

Thank you for help!

**Comment by wardpeet** [comment]
My pleasure! Let me close this one.
