### ISSUE TITLE
[1.0] Dev & Build failing in infer-graphql-type.js

### ISSUE THREAD

**Issue by okcoker** [gatsbyjs/gatsby#1396]
I've been using gatsby for a couple weeks along with a few plugins on the "next" version. Today I decided to clean out my cache and node modules for some reason. After reinstalling I clearly have new versions now but I'm running into a weird build issue.

```
npm run dev

> sean@1.0.0 dev /path
> gatsby develop

success open and validate gatsby-config.js — 0.005 s

One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's not any stale
data

success copy gatsby files — 0.023 s
⡀ source and transform nodesCalling "createNodeField" with "fieldName" is deprecated. Use "name" instead
Calling "createNodeField" with "fieldValue" is deprecated. Use "value" instead
Calling "createNodeField" with "fieldName" is deprecated. Use "name" instead

success source and transform nodes — 0.413 s
success building schema — 0.145 s
success createPages — 0.053 s
success createPagesStatefully — 0.038 s
success extract queries from components — 0.134 s
⠄ run graphql queriesvips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
success run graphql queries — 1.664 s
success write out page data — 0.002 s
⠂ update schemaUNHANDLED REJECTION TypeError: Cannot convert object to primitive value
    at configFromStringAndFormat (/path/node_modules/moment/moment.js:2355:21)
    at configFromStringAndArray (/path/node_modules/moment/moment.js:2460:9)
    at prepareConfig (/path/node_modules/moment/moment.js:2526:9)
    at createFromConfig (/path/node_modules/moment/moment.js:2497:40)
    at createLocalOrUTC (/path/node_modules/moment/moment.js:2584:12)
    at Function.createUTC [as utc] (/path/node_modules/moment/moment.js:87:12)
    at inferGraphQLType (/path/node_modules/gatsby/dist/schema/infer-graphql-type.js:120:27)
    at /path/node_modules/gatsby/dist/schema/infer-graphql-type.js:514:23
    at /path/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/path/node_modules/lodash/lodash.js:3001:24)
    at /path/node_modules/lodash/lodash.js:4913:18
    at Function.forEach (/path/node_modules/lodash/lodash.js:9359:14)
    at inferObjectStructureFromNodes (/path/node_modules/gatsby/dist/schema/infer-graphql-type.js:475:5)
    at inferGraphQLType (/path/node_modules/gatsby/dist/schema/infer-graphql-type.js:165:19)
    at /path/node_modules/gatsby/dist/schema/infer-graphql-type.js:514:23
    at /path/node_modules/lodash/lodash.js:4944:15
⠄ update schema%
```

The fieldName -> name lines I can easily change no problem. The VipsJpeg warnings, I've been ignoring although if you know how to fix those off the top of your head, I'm all ears. 

The weird error that's preventing me from upgrading from 1.0.0-beta.5 is the one on the bottom. It fails within the moment library [here](https://github.com/moment/moment/blob/7589bb8967aca2bda0192595e6e53a12c750aa69/src/lib/create/from-string-and-format.js#L32) where [`exampleValue`](https://github.com/gatsbyjs/gatsby/blob/d030b831f7f97a62dde0690507a4516f37a60b9b/packages/gatsby/src/schema/infer-graphql-type.js#L109) is a simple frontmatter object. I've got about 15 pages but for some reason one of the pages makes things fail. While debugging a bit earlier, I'm not sure what's so special about the POJO where it fails. Above the line before `exampleValue` is passed to `moment.utc`, if I do `exampleValue = Object.assign({}, exampleValue)`. It doesn't fail.

I reverted back to 1.0.0-beta.5 and things build as expected so I'm not sure what exactly has changed. I can debug a little bit more soon but I thought I'd open this issue for reference in case anyone else was running into the issue.

**Comment by KyleAMathews** [comment]
Is there any frontmatter data that's of different types between markdown files?

**Comment by KyleAMathews** [comment]
Also 1.0 is out!

**Comment by okcoker** [comment]
Ok so I tried upgrading back to 1.0.5. In my gatsby-node config, I was building my pages and passing a reference to the next/previous node's frontmatter into the context. Something like:

```js
createPage({
    path: edge.node.fields.slug,
    component: template,
    context: {
        prevFrontmatter: prevNodeFrontmatter,
        nextFrontmatter: nextNodeFrontmatter
    }
});
```
Updating to the following fixed that error:

```js
// Seems like some sort of reference issue?
createPage({
    path: edge.node.fields.slug,
    component: template,
    context: {
        prevFrontmatter: Object.assign({}, prevNodeFrontmatter),
        nextFrontmatter: Object.assign({}, nextNodeFrontmatter)
    }
});
```

I'm now getting another error related to the sitemap plugin but I'll open a separate issue for that.
