### ISSUE TITLE
css-modules example doesn't work

### ISSUE THREAD

**Issue by rossPatton** [gatsbyjs/gatsby#143]
The follow example css-modules code results in an error: 

```javascript
module.exports = function(config, env) {
  config.removeLoader('css');
  config.loader('css', function(cfg) {
    cfg.test = /\.css$/;
    cfg.loader = 'style!css?modules'
    return cfg
  })
  return config;
}; // in the docs there is a paren here which is a bug
```

So, I have the above in a `gatsby.config.js` file, and gatsby appears to recognize it.

So then I attempt to import some css like so:

my css:
```css
.test {
  margin: 0;
}
```

example js:
```jsx
import styles from './css/styles.css'

... react class etc etc etc

render() {
  return <div className={styles.test} />
}
```

Which gets me this error:

```
/Users/ross/.nvm/versions/node/v4.1.0/lib/node_modules/gatsby/node_modules/style-loader/addStyles.js:25
		if(typeof document !== "object") throw new Error("The style-loader cannot be used in a non-browser environment");
^
Error: The style-loader cannot be used in a non-browser environment
    at e.exports (/Users/ross/.nvm/versions/node/v4.1.0/lib/node_modules/gatsby/node_modules/style-loader/addStyles.js:25:1)
    at Object.<anonymous> (webpack:///css/styles.css?c15e:7:1)
    at t (webpack/bootstrap 8908ff69fd9b4d9b6e8b:9:1)
    at Object.<anonymous> (bundle.js:86:446)
    at t (webpack/bootstrap 8908ff69fd9b4d9b6e8b:9:1)
    at Object.<anonymous> (bundle.js:60:13)
    at Object.<anonymous> (bundle.js:60:34)
    at t (webpack/bootstrap 8908ff69fd9b4d9b6e8b:9:1)
    at webpack/bootstrap 8908ff69fd9b4d9b6e8b:19:1
    at webpack/bootstrap 8908ff69fd9b4d9b6e8b:22:1
```

**Comment by KyleAMathews** [comment]
You should only add the style loader for the `develop` stage. When server rendering / building production build, you get the error you're seeing.

Look at the code here: https://github.com/gatsbyjs/gatsby/blob/master/lib/utils/webpack.config.js#L31

Switch on the stage like it does there.

This is not very well documented atm. We need to get a website up soonish to document common things like this.

**Comment by rossPatton** [comment]
ok, well if I continue to use the example on the docs, but check for the `develop` stage, I continue to get the same error.

```javascript
>>> gatsby.config.js

module.exports = function(config, env) {
  if (env === 'develop') {
    config.removeLoader('css');
    config.loader('css', function(cfg) {
      cfg.test = /\.css$/;
      cfg.loader = 'style!css?modules'
      return cfg
    })
  }
}
```

**Comment by rossPatton** [comment]
updated to `0.8.5` and this appears to work now :+1:

**Comment by KyleAMathews** [comment]
oh great! Curious what changed but I'll take it :)
