### ISSUE TITLE
Errors while running the Gatsby CLI command "gatsby new"

### ISSUE THREAD

**Issue by jhabash** [gatsbyjs/gatsby#14447]
## Summary

I have just started using GatsbyJS. I followed the GatsbyJS tutorial (https://www.gatsbyjs.org/tutorial/part-zero/) and installed Node.js and the Gatsby CLI. 

When I tried the command "gatsby new site", I received errors. 

Any help would be greatly appreciated!

## Relevant information

The terminal output:

```
gatsby new testly
info Creating new site from git: https://github.com/gatsbyjs/gatsby-starter-default.git

Cloning into 'testly'...
remote: Enumerating objects: 1692, done.
remote: Total 1692 (delta 0), reused 0 (delta 0), pack-reused 1692
Receiving objects: 100% (1692/1692), 6.20 MiB | 1.56 MiB/s, done.
success Created starter directory layout
info Installing packages...

npm WARN npm npm does not support Node.js v12.3.1
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
events.js:177░░░░░░⸩ ⠋ extract:@babel/plugin-transform-typeof-symbol: sill extract pump@1.0.3
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:250:14)
    at PassThrough.Writable.write (_stream_writable.js:298:5)
    at PassThrough.Writable.end (_stream_writable.js:582:10)
    at ReadEntry.<anonymous> (/Users/user/Development/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at ReadEntry.emit (events.js:205:15)
    at ReadEntry.emit (/Users/user/Development/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/Users/user/Development/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/Users/user/Development/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/Users/user/Development/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/user/Development/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/user/Development/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.<anonymous> (/Users/user/Development/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at Unzip.emit (events.js:200:13)
    at Unzip.emit (/Users/user/Development/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at Unzip.write (/Users/user/Development/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:90:17)
    at Unzip.write (/Users/user/Development/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at writeAfterEnd (_stream_writable.js:252:3)
    at PassThrough.Writable.write (_stream_writable.js:298:5)
    [... lines matching original stack trace ...]
    at Unzip.write (/Users/user/Development/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:90:17)
events.js:177░░░░░░⸩ ⠙ extract:copyfiles: sill extract imagemin@6.1.0
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:250:14)
    at PassThrough.Writable.write (_stream_writable.js:298:5)
    at PassThrough.Writable.end (_stream_writable.js:582:10)
    at ReadEntry.<anonymous> (/Users/user/Development/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at ReadEntry.emit (events.js:205:15)
    at ReadEntry.emit (/Users/user/Development/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/Users/user/Development/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/Users/user/Development/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/Users/user/Development/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/user/Development/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/user/Development/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.<anonymous> (/Users/user/Development/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at Unzip.emit (events.js:200:13)
    at Unzip.emit (/Users/user/Development/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at Unzip.write (/Users/user/Development/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:90:17)
    at Unzip.write (/Users/user/Development/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at writeAfterEnd (_stream_writable.js:252:3)
    at PassThrough.Writable.write (_stream_writable.js:298:5)
    [... lines matching original stack trace ...]
    at Unzip.write (/Users/user/Development/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:90:17)
events.js:177░░░░░░⸩ ⠸ extract:prettier: sill extract globby@6.1.0
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:250:14)
    at PassThrough.Writable.write (_stream_writable.js:298:5)
    at PassThrough.Writable.end (_stream_writable.js:582:10)
    at ReadEntry.<anonymous> (/Users/user/Development/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at ReadEntry.emit (events.js:205:15)
    at ReadEntry.emit (/Users/user/Development/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/Users/user/Development/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/Users/user/Development/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/Users/user/Development/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/user/Development/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/user/Development/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.<anonymous> (/Users/user/Development/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at Unzip.emit (events.js:200:13)
    at Unzip.emit (/Users/user/Development/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at Unzip.write (/Users/user/Development/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:90:17)
    at Unzip.write (/Users/user/Development/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at writeAfterEnd (_stream_writable.js:252:3)
    at PassThrough.Writable.write (_stream_writable.js:298:5)
    [... lines matching original stack trace ...]
    at Unzip.write (/Users/user/Development/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:90:17)
```

After the errors there were some warnings: 

```
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/@nodelib/fs.stat-61767b16/package.json'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/@nodelib/fs.stat-61767b16/README.md'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/MemoryOutputFileSystem.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/Module.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/ModuleBuildError.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/ModuleDependencyError.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/ModuleDependencyWarning.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/ModuleError.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/ModuleFilenameHelpers.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/ModuleNotFoundError.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/ModuleParseError.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/ModuleReason.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/ModuleTemplate.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/ModuleWarning.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/MultiCompiler.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/MultiEntryPlugin.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/MultiModule.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/MultiModuleFactory.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/MultiStats.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/MultiWatching.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/NamedChunksPlugin.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/NamedModulesPlugin.js'
WARN tar ENOENT: no such file or directory, lstat '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/node'
WARN tar ENOENT: no such file or directory, lstat '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/node'
WARN tar ENOENT: no such file or directory, lstat '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/node'
WARN tar ENOENT: no such file or directory, lstat '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/node'
WARN tar ENOENT: no such file or directory, lstat '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/node'
WARN tar ENOENT: no such file or directory, lstat '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/node'
WARN tar ENOENT: no such file or directory, lstat '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/node'
WARN tar ENOENT: no such file or directory, lstat '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/node'
WARN tar ENOENT: no such file or directory, lstat '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/node'
WARN tar ENOENT: no such file or directory, lstat '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/node'
WARN tar ENOENT: no such file or directory, lstat '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/node'
WARN tar ENOENT: no such file or directory, lstat '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/node'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/NodeStuffPlugin.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/NoEmitOnErrorsPlugin.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/NoModeWarning.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-542f08b0/lib/NormalModule.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/xstate-acfccefa/lib/graph.js.map'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/bin-version-check-70de0d61/license'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/bin-version-check-70de0d61/readme.md'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-dev-server-5dc7f0af/client/live.html'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-dev-server-5dc7f0af/client/overlay.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-dev-server-5dc7f0af/client/socket.js'
WARN tar ENOENT: no such file or directory, open '/Users/user/Development/NextWeb3/testly/node_modules/.staging/webpack-dev-server-5dc7f0af/client/sockjs.bundle.js'
npm ERR! cancel after 1 retries!
```
### Environment (if relevant)

  System:
    OS: macOS Sierra 10.12.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.3.1 - ~/.nvm/versions/node/v12.3.1/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v12.3.1/bin/npm
  Languages:
    Python: 2.7.14 - /usr/local/bin/python
  Browsers:
    Chrome: 74.0.3729.169
  npmGlobalPackages:
    gatsby-cli: 2.6.3

**Comment by pieh** [comment]
Error happens during regular `npm install` (one of steps that `gatsby new` does)

This is pretty confusing warning (that could explain subsequent errors)
```
npm WARN npm npm does not support Node.js v12.3.1
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
```
I would try checking https://stackoverflow.com/questions/47226238/npm-warn-npm-npm-does-not-support-node-js-v9-1-0 which seems very similar

**Comment by jhabash** [comment]
It took me a while to figure out what the problem was. 

The solution was to delete the node_modules referred to in the error (/Users/user/Development/node_modules/). This node_modules persisted through every install and re-install of Node, which caused the errors seen above.
