### ISSUE TITLE
NPM and Yarn Errors Installing `gatsby-cli`

### ISSUE THREAD

**Issue by delster** [gatsbyjs/gatsby#14526]
## Description

Installation of `gatsby-cli` fails with both `npm` and yarn` in a clean OS install.

### Steps to reproduce

Windows 10 Pro 64bit, gaming PC with decent specs (i5-9600k, RTX 2060, 16GB DD4, etc), node and yarn and installed. Not sure what else might help here.

### Expected result

`gatsby-cli` should install.

### Actual result

```
C:\GitHub
λ node -v
v10.16.0

C:\GitHub
λ npm -v
6.9.0

C:\GitHub
λ yarn -v
1.16.0

C:\GitHub
λ npm install -g gatsby-cli
npm ERR! Cannot read property 'resolve' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\David\AppData\Roaming\npm-cache\_logs\2019-06-04T00_55_00_646Z-debug.log

C:\GitHub
λ yarn global add gatsby-cli
yarn global v1.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠂ core-js
error C:\Users\David\AppData\Local\Yarn\Data\global\node_modules\gatsby-telemetry: Command failed.
Exit code: 1
Command: node src/postinstall.js
Arguments:
Directory: C:\Users\David\AppData\Local\Yarn\Data\global\node_modules\gatsby-telemetry
Output:
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\Users\David\AppData\Local\Yarn\Data\global\node_modules\gatsby-telemetry\src\postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

### Environment

> Run `gatsby info --clipboard` in your project directory and paste the output here.

Unsurprisingly:
```
C:\GitHub
λ gatsby info --clipboard
'"C:\Users\David\AppData\Local\Yarn\bin\\..\Data\global\node_modules\.bin\gatsby.cmd"' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by delster** [comment]
Appears to be an issue with `npm` and `yarn`, likely to do with PATH issues or whatever. I resolved it by deleting everything and reinstalling 100 different ways until things started magically working.
