### ISSUE TITLE
same error but at different stage  . I couldn't even start the server

### ISSUE THREAD

**Issue by akashkrshukla** [gatsbyjs/gatsby#14789]
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A 

here is my error code 

Looking for JS files in
   /home/akash/appme 

Loading dependency graph...internal/fs/watchers.js:173
    throw error;
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home/akash/appme/node_modules/jest-jasmine2/node_modules'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at NodeWatcher.watchdir (/home/akash/appme/node_modules/sane/src/node_watcher.js:159:22)
    at Walker.<anonymous> (/home/akash/appme/node_modules/sane/src/common.js:109:31)
    at Walker.emit (events.js:200:13)
    at /home/akash/appme/node_modules/walker/lib/walker.js:69:16
    at go$readdir$cb (/home/akash/appme/node_modules/graceful-fs/graceful-fs.js:162:14)
    at FSReqCallback.oncomplete (fs.js:153:23) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/home/akash/appme/node_modules/jest-jasmine2/node_modules',
  filename: '/home/akash/appme/node_modules/jest-jasmine2/node_modules'
}

**Comment by romach** [comment]
@akashkrshukla did you try this solution https://github.com/gatsbyjs/gatsby/issues/11406#issuecomment-458769756?

**Comment by sidharthachatterjee** [comment]
@akashkrshukla `ENOSPC: System limit for number of file watchers reached` is thrown when your system's file watchers limit is hit. The solution @romach linked to should work. 

Closing this for now. Please feel free to reopen if that doesn't help.
