### ISSUE TITLE
Running `gatsby develop` fails with babel errors

### ISSUE THREAD

**Issue by matthewtole** [gatsbyjs/gatsby#1484]
*Node version:* **6.11.0**
*NPM version:* **5.2.0**
*Gatsby version:* **1.1.0**

Trying out Gatsby for the first time, I installed the CLI and created a new site following the instructions. When running `gatsby-develop` I get an error message about Babel being missing: `Error: Entry module not found: Error: Cannot resolve module 'babel'`.

Full console log:

```sh
➜  Personal gatsby new gatsby-site
2017-07-12T14:31:05-0700 <log> init-starter.js:111 (clone) Cloning git repo git://github.com/gatsbyjs/gatsby-starter-default.git to gatsby-site...
2017-07-12T14:31:06-0700 <log> init-starter.js:118 () Created starter directory layout
2017-07-12T14:31:06-0700 <log> init-starter.js:48 (install) Installing packages...

> fsevents@1.1.2 install /Users/mtole/Documents/Personal/gatsby-site/node_modules/fsevents
> node install

[fsevents] Success: "/Users/mtole/Documents/Personal/gatsby-site/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
added 1208 packages in 30.005s

➜  Personal cd gatsby-site
➜  gatsby-site gatsby develop
success open and validate gatsby-config.js — 0.006 s
success copy gatsby files — 0.020 s
success source and transform nodes — 0.022 s
success building schema — 0.136 s
success createPages — 0.007 s
success createPagesStatefully — 0.114 s
success extract queries from components — 0.066 s
success run graphql queries — 0.072 s
success write out page data — 0.004 s
success update schema — 0.065 s

bootstrap finished, time since started: 8.178 s

Error: Entry module not found: Error: Cannot resolve module 'babel' in /Users/mtole/Documents/Personal/gatsby-site
resolve module babel in /Users/mtole/Documents/Personal/gatsby-site
  looking for modules in /Users/mtole/Documents/Personal/gatsby-site/node_modules
    module variation babel-webpack-node-loader
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-webpack-node-loader doesn't exist (module as directory)
      resolve 'file' babel-webpack-node-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-webpack-node-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-webpack-node-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-webpack-node-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-webpack-node-loader.js doesn't exist
    module variation babel-node-loader
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-node-loader doesn't exist (module as directory)
      resolve 'file' babel-node-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-node-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-node-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-node-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-node-loader.js doesn't exist
    module variation babel-loader
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-loader doesn't exist (module as directory)
      resolve 'file' babel-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-loader.js doesn't exist
    module variation babel
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel doesn't exist (module as directory)
      resolve 'file' babel in /Users/mtole/Documents/Personal/gatsby-site/node_modules
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel.js doesn't exist
  looking for modules in /Users/mtole/Documents/Personal/gatsby-site/node_modules
    module variation babel-webpack-node-loader
      resolve 'file' babel-webpack-node-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-webpack-node-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-webpack-node-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-webpack-node-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-webpack-node-loader.js doesn't exist
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-webpack-node-loader doesn't exist (module as directory)
    module variation babel-node-loader
      resolve 'file' babel-node-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-node-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-node-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-node-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-node-loader.js doesn't exist
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-node-loader doesn't exist (module as directory)
    module variation babel-loader
      resolve 'file' babel-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-loader.js doesn't exist
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel-loader doesn't exist (module as directory)
    module variation babel
      resolve 'file' babel in /Users/mtole/Documents/Personal/gatsby-site/node_modules
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel.js doesn't exist
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/babel doesn't exist (module as directory)
  looking for modules in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
    module variation babel-webpack-node-loader
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader doesn't exist (module as directory)
      resolve 'file' babel-webpack-node-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader.js doesn't exist
    module variation babel-node-loader
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader doesn't exist (module as directory)
      resolve 'file' babel-node-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader.js doesn't exist
    module variation babel-loader
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader doesn't exist (module as directory)
      resolve 'file' babel-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader.js doesn't exist
    module variation babel
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel doesn't exist (module as directory)
      resolve 'file' babel in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel.js doesn't exist
  looking for modules in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
    module variation babel-webpack-node-loader
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader doesn't exist (module as directory)
      resolve 'file' babel-webpack-node-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader.js doesn't exist
    module variation babel-node-loader
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader doesn't exist (module as directory)
      resolve 'file' babel-node-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader.js doesn't exist
    module variation babel-loader
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader doesn't exist (module as directory)
      resolve 'file' babel-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader.js doesn't exist
    module variation babel
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel doesn't exist (module as directory)
      resolve 'file' babel in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel.js doesn't exist
  looking for modules in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
    module variation babel-webpack-node-loader
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader doesn't exist (module as directory)
      resolve 'file' babel-webpack-node-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader.js doesn't exist
    module variation babel-node-loader
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader doesn't exist (module as directory)
      resolve 'file' babel-node-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader.js doesn't exist
    module variation babel-loader
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader doesn't exist (module as directory)
      resolve 'file' babel-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader.js doesn't exist
    module variation babel
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel doesn't exist (module as directory)
      resolve 'file' babel in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel.js doesn't exist
  looking for modules in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
    module variation babel-webpack-node-loader
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader doesn't exist (module as directory)
      resolve 'file' babel-webpack-node-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader.js doesn't exist
    module variation babel-node-loader
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader doesn't exist (module as directory)
      resolve 'file' babel-node-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader.js doesn't exist
    module variation babel-loader
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader doesn't exist (module as directory)
      resolve 'file' babel-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader.js doesn't exist
    module variation babel
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel doesn't exist (module as directory)
      resolve 'file' babel in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel.js doesn't exist
  looking for modules in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
    module variation babel-webpack-node-loader
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader doesn't exist (module as directory)
      resolve 'file' babel-webpack-node-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader.js doesn't exist
    module variation babel-node-loader
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader doesn't exist (module as directory)
      resolve 'file' babel-node-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader.js doesn't exist
    module variation babel-loader
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader doesn't exist (module as directory)
      resolve 'file' babel-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader.js doesn't exist
    module variation babel
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel doesn't exist (module as directory)
      resolve 'file' babel in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel.js doesn't exist
  looking for modules in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
    module variation babel-webpack-node-loader
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader doesn't exist (module as directory)
      resolve 'file' babel-webpack-node-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-webpack-node-loader.js doesn't exist
    module variation babel-node-loader
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader doesn't exist (module as directory)
      resolve 'file' babel-node-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-node-loader.js doesn't exist
    module variation babel-loader
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader doesn't exist (module as directory)
      resolve 'file' babel-loader in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel-loader.js doesn't exist
    module variation babel
      /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel doesn't exist (module as directory)
      resolve 'file' babel in /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders
        resolve file
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel.webpack-node-loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel.loader.js doesn't exist
          /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/dist/loaders/babel.js doesn't exist,Error: Source file not found: "render-page.js"
    at Compilation.<anonymous> (/Users/mtole/Documents/Personal/gatsby-site/node_modules/static-site-generator-webpack-plugin/index.js:36:17)
    at Compilation.applyPluginsAsync (/Users/mtole/Documents/Personal/gatsby-site/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/Users/mtole/Documents/Personal/gatsby-site/node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.applyPluginsAsync (/Users/mtole/Documents/Personal/gatsby-site/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/mtole/Documents/Personal/gatsby-site/node_modules/webpack/lib/Compilation.js:567:9)
    at Compilation.next (/Users/mtole/Documents/Personal/gatsby-site/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/node_modules/extract-text-webpack-plugin/index.js:309:4)
    at Compilation.applyPluginsAsync (/Users/mtole/Documents/Personal/gatsby-site/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/Users/mtole/Documents/Personal/gatsby-site/node_modules/webpack/lib/Compilation.js:563:8)
    at Compilation.next (/Users/mtole/Documents/Personal/gatsby-site/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/node_modules/extract-text-webpack-plugin/index.js:285:5)
    at /Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:209:22)
    at ExtractTextPlugin.<anonymous> (/Users/mtole/Documents/Personal/gatsby-site/node_modules/gatsby/node_modules/extract-text-webpack-plugin/index.js:237:10)
    at Compilation.applyPluginsAsync (/Users/mtole/Documents/Personal/gatsby-site/node_modules/tapable/lib/Tapable.js:71:13)
```

**Comment by jbolda** [comment]
There seems to be an issue with npm 5.2. Give yarn a try for the time being.

**Comment by benjaminhoffman** [comment]
@matthewtole closing this issue as it's 5 months old and not much follow up.  If I'm mistaken or you'd like us to continue to investigate, please re-open with add'l context.  Thanks!

**Comment by nxz91** [comment]
I'm getting this as well using yarn. Any ideas? This happened after I did `yarn add react-typeform-embed`

My dependencies are

  "dependencies": {
    "gatsby": "^1.9.277",
    "gatsby-link": "^1.6.46",
    "gatsby-plugin-google-fonts": "^0.0.4",
    "gatsby-plugin-react-helmet": "^2.0.11",
    "react-helmet": "^5.2.0",
    "react-typeform-embed": "^0.1.6"
  },

  "devDependencies": {
    "prettier": "^1.13.7"
  },

Thanks!
