### ISSUE TITLE
Braking change 2.9.9

### ISSUE THREAD

**Issue by n8tb1t** [gatsbyjs/gatsby#14909]
After an update from 2.9.8 to 2.9.9
the `gatsby develop` is broken.
![Untitled](https://user-images.githubusercontent.com/50831958/59767246-52f77700-92bb-11e9-9117-185d480e8759.png)
```
success run static queries - 0.048 s — 2/2 47.50 queries/second
success run page queries - 1.466 s — 27/27 18.49 queries/second
 DONE  Compiled successfully in 9905ms                                                                                                          5:51:44 PM⠀

B:\Meta\Dev\Yarn\Local\Data\global\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

RangeError: Maximum call stack size exceeded
    at Array.values (<anonymous>)
    at Object.console.error (D:\Mount\WorkspaceDev\Node-Projects\gatsby-starter-n8tb1t-blog\node_modules\gatsby-cli\lib\reporter\index.js:216:50)
    at warningWithoutStack (D:\Mount\WorkspaceDev\Node-Projects\gatsby-starter-n8tb1t-blog\node_modules\react-reconciler\cjs\react-reconciler.development.js:100:32)
    at warnAboutUpdateOnUnmounted (D:\Mount\WorkspaceDev\Node-Projects\gatsby-starter-n8tb1t-blog\node_modules\react-reconciler\cjs\react-reconciler.development.js:10458:5)
    at scheduleWork (D:\Mount\WorkspaceDev\Node-Projects\gatsby-starter-n8tb1t-blog\node_modules\react-reconciler\cjs\react-reconciler.development.js:11868:11)
    at Object.enqueueSetState (D:\Mount\WorkspaceDev\Node-Projects\gatsby-starter-n8tb1t-blog\node_modules\react-reconciler\cjs\react-reconciler.development.js:3152:5)
    at GatsbyReporter.Component.setState (D:\Mount\WorkspaceDev\Node-Projects\gatsby-starter-n8tb1t-blog\node_modules\react\cjs\react.development.js:335:16)
    at GatsbyReporter._addMessage (D:\Mount\WorkspaceDev\Node-Projects\gatsby-starter-n8tb1t-blog\node_modules\gatsby-cli\lib\reporter\reporters\ink\reporter.js:132:10)
    at Object.error (D:\Mount\WorkspaceDev\Node-Projects\gatsby-starter-n8tb1t-blog\node_modules\gatsby-cli\lib\reporter\index.js:82:22)
    at Object.console.error (D:\Mount\WorkspaceDev\Node-Projects\gatsby-starter-n8tb1t-blog\node_modules\gatsby-cli\lib\reporter\index.js:216:39)
    at warningWithoutStack (D:\Mount\WorkspaceDev\Node-Projects\gatsby-starter-n8tb1t-blog\node_modules\react-reconciler\cjs\react-reconciler.development.js:100:32)
    at warnAboutUpdateOnUnmounted (D:\Mount\WorkspaceDev\Node-Projects\gatsby-starter-n8tb1t-blog\node_modules\react-reconciler\cjs\react-reconciler.development.js:10458:5)
    at scheduleWork (D:\Mount\WorkspaceDev\Node-Projects\gatsby-starter-n8tb1t-blog\node_modules\react-reconciler\cjs\react-reconciler.development.js:11868:11)
    at Object.enqueueSetState (D:\Mount\WorkspaceDev\Node-Projects\gatsby-starter-n8tb1t-blog\node_modules\react-reconciler\cjs\react-reconciler.development.js:3152:5)
    at GatsbyReporter.Component.setState (D:\Mount\WorkspaceDev\Node-Projects\gatsby-starter-n8tb1t-blog\node_modules\react\cjs\react.development.js:335:16)
    at GatsbyReporter._addMessage (D:\Mount\WorkspaceDev\Node-Projects\gatsby-starter-n8tb1t-blog\node_modules\gatsby-cli\lib\reporter\reporters\ink\reporter.js:132:10)
```

**Comment by n8tb1t** [comment]
And I'm not using `typescript`

**Comment by Powell-v2** [comment]
Looks like that's still an issue. Has the problem been identified?
