### ISSUE TITLE
gatsby-cli fails to create new project

### ISSUE THREAD

**Issue by bilgorajskim** [gatsbyjs/gatsby#15074]
## Description

After installing gatsby-cli with `npm install -g gatsby-cli` and creating a project with `gatsby new` or `gatsby new (starter-url)`, it crashes. The same happens when using Yarn instead of NPM.

**Installing better-opn globally (`npm install -g better-opn`) fixes the issue**

### Steps to reproduce

```
npm install -g gatsby-cli
gatsby new
```

### Expected result

Gatsby should prompt for project name.

### Actual result

It crashes with the following message:

```
/usr/local/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Cannot find module 'better-opn'
Require stack:
- /usr/local/lib/node_modules/gatsby-cli/lib/init-starter.js
- /usr/local/lib/node_modules/gatsby-cli/lib/create-cli.js
- /usr/local/lib/node_modules/gatsby-cli/lib/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby-cli/lib/init-starter.js:32:13)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
```

### Environment

```
  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Safari: 12.1.1
  npmGlobalPackages:
    gatsby-cli: 2.7.1
```

**Comment by YungTosti** [comment]
Duplicate of #15702

**Comment by YungTosti** [comment]
Duplicate of #15703

**Comment by bilgorajskim** [comment]
I see :) I was slower by 4 minutes. Haven't seen it when I started writing this issue.

**Comment by CanRau** [comment]
Just for reference @YungTosti probably meant to link to https://github.com/gatsbyjs/gatsby/issues/15073
