### ISSUE TITLE
Improve stack traces in build 

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#15105]
As mentioned in https://github.com/gatsbyjs/gatsby/issues/14925, it seems that in some cases like the example above, stack traces aren't very helpful
```
(node:54) UnhandledPromiseRejectionWarning: ReferenceError: window is not defined
    at navigate (/srv/public/render-page.js:32363:3)
    at _callee$ (/srv/public/render-page.js:92119:70)
    at tryCatch (/srv/public/render-page.js:1941:40)
    at Generator.invoke [as _invoke] (/srv/public/render-page.js:2167:22)
    at Generator.prototype.<computed> [as throw] (/srv/public/render-page.js:1993:21)
    at asyncGeneratorStep (/srv/public/render-page.js:1131:24)
    at _throw (/srv/public/render-page.js:1157:9)
    at runNextTicks (internal/process/task_queues.js:55:5)
    at listOnTimeout (internal/timers.js:501:9)
    at processTimers (internal/timers.js:475:7)
(node:54) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

We need to improve this as part of our error messaging so that it is easier to track down where such errors originate.

**Comment by taran-gill** [comment]
I'll be happy to take a stab at this over the weekend, if nobody else volunteers.

**Comment by m-allanson** [comment]
I think a good start would be working out how to reproduce a stack trace like this. Normally this sort of error will look like:

<img width="586" alt="Screenshot 2019-06-27 at 14 18 32" src="https://user-images.githubusercontent.com/381801/60269541-8e5efa80-98e6-11e9-8ccf-6849fa4025ec.png">

**Comment by taran-gill** [comment]
Hey, this weekend's a little busy for me and I'm not sure when I can get time to look at this, so I won't assign this to myself and defer to anyone who would like to do this.

**Comment by LekoArts** [comment]
The error message around this issue was improved in the meantime.
