### ISSUE TITLE
Initializing new project

### ISSUE THREAD

**Issue by macsj200** [gatsbyjs/gatsby#1519]
I can't figure out how to get `gatsby new` to generate a project in an existing directory. It keeps breaking with
```
2017-07-15T13:47:03-0700 <error> new.js:12 () Error: Git clone error: fatal: destination path '/Users/maxjohansen/projects/Cal-climbing-website' already exists and is not an empty directory.

    at /Users/maxjohansen/.nvm/versions/node/v7.2.0/lib/node_modules/gatsby/dist/utils/init-starter.js:116:23
    at ChildProcess.exithandler (child_process.js:218:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

**Comment by KyleAMathews** [comment]
Try removing the global Gatsby and reinstalling it.

**Comment by macsj200** [comment]
I ended up just initializing in a new directory and moving up a level. Thanks anyways!
