### ISSUE TITLE
'Downloading remote files' in gatsby-source-filesystem/create-remote-file-node crashes in reporter

### ISSUE THREAD

**Issue by laurenskling** [gatsbyjs/gatsby#15597]
I am getting:
```

TypeError: Cannot read property 'type' of undefined
    at Object.done (/Users/laurens/sites/pauldevries.nl/node_modules/gatsby-cli/lib/reporter/reporters/ink/reporter.js:79:54)
    at Object.done (/Users/laurens/sites/pauldevries.nl/node_modules/gatsby-cli/lib/reporter/index.js:187:18)
    at Queue.queue.on (/Users/laurens/sites/pauldevries.nl/node_modules/gatsby-source-filesystem/create-remote-file-node.js:106:9)
    at Queue.emit (events.js:197:13)
    at Queue._drained (/Users/laurens/sites/pauldevries.nl/node_modules/better-queue/lib/queue.js:469:8)
    at Queue._processNextIfAllowed (/Users/laurens/sites/pauldevries.nl/node_modules/better-queue/lib/queue.js:505:14)
    at Timeout._onTimeout (/Users/laurens/sites/pauldevries.nl/node_modules/better-queue/lib/queue.js:489:12)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
```
when using `gatsby-source-wordpress` to download my wordpress media. The crash is happening in: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/reporter/reporters/ink/reporter.js#L77
I've logged out what is happening here, my `this.state.activities` is empty, so it will not return an `activity`, so `undefined.type` will crash.

**Comment by laurenskling** [comment]
This issue still leaves me unable to use my wordpress images :'(

**Comment by laurenskling** [comment]
I replied before 😱 
i'm still facing this issue...

**Comment by laurenskling** [comment]
In recent versions of Gatsby, this error no longer happens 🎉
