### ISSUE TITLE
iframe tag raises "Cannot read property 'parent' of undefined" error in markdown file

### ISSUE THREAD

**Issue by qas612820704** [gatsbyjs/gatsby#1585]
when I add `iframe` in markdown file like:
```md
<iframe url="http://www.example.com/" width="600" height="400"></iframe>
```

and run `gatsby develop` will raise an error
```bash
UNHANDLED REJECTION TypeError: Cannot read property 'parent' of undefined
```

I use `gatsby-blog-starter`.

I already install  `gatsby-remark-responsive-iframe` and import it in `gatsby-config.js` like:
```
module.exports = {
  ...
  plugins: {
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          ...
          {
            resolve: `gatsby-remark-responsive-iframe`,
            options: {
              wrapperStyle: `margin-bottom: 1.0725rem`,
            },
          },
          ...
```

Can someone help here? Thx!

**Comment by qas612820704** [comment]
error track:
```
UNHANDLED REJECTION TypeError: Cannot read property 'parent' of undefined                                                                                                                      
    at Function.exports.update (/home/lego/workspace/blog/node_modules/gatsby-remark-images/node_modules/cheerio/lib/parse.js:69:25)
    at module.exports (/home/lego/workspace/blog/node_modules/gatsby-remark-images/node_modules/cheerio/lib/parse.js:19:11)
    at Function.exports.load (/home/lego/workspace/blog/node_modules/gatsby-remark-images/node_modules/cheerio/lib/static.js:27:14)
    at _callee3$ (/home/lego/workspace/blog/node_modules/gatsby-remark-images/index.js:196:33) 
    at tryCatch (/home/lego/workspace/blog/node_modules/regenerator-runtime/runtime.js:65:40)  
    at Generator.invoke [as _invoke] (/home/lego/workspace/blog/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/lego/workspace/blog/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/lego/workspace/blog/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/lego/workspace/blog/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14  
    at new Promise (/home/lego/workspace/blog/node_modules/core-js/library/modules/es6.promise.js:191:7)
    at /home/lego/workspace/blog/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12                                       
    at /home/lego/workspace/blog/node_modules/gatsby-remark-images/index.js:308:26                                         
    at Promise._execute (/home/lego/workspace/blog/node_modules/bluebird/js/release/debuggability.js:300:9)                        
    at Promise._resolveFromExecutor (/home/lego/workspace/blog/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/lego/workspace/blog/node_modules/bluebird/js/release/promise.js:79:10)
    at /home/lego/workspace/blog/node_modules/gatsby-remark-images/index.js:188:16 
```

**Comment by KyleAMathews** [comment]
Could you try replicating this with the using-remark example site? https://github.com/gatsbyjs/gatsby/blob/master/examples/using-remark/src/pages/2017-01-02---responsive-images-and-iframes/index.md#iframes-and-video-embeds

**Comment by qas612820704** [comment]
Hi @KyleAMathews, both `examples/using-remark` and `gatsby-starter-blog` work fine.

I don't know what's wrong when I'm modifying.

I'll start my blog again.

If I find out anything, I will put feedback here.

Thx for your response.

**Comment by KyleAMathews** [comment]
Ok good luck. It could be your content so try copying your markdown files into the other site.
