### ISSUE TITLE
Gatsby crashes when `onCreatePage` API modifies page path and the corresponding file is deleted from the filesystem

### ISSUE THREAD

**Issue by ervasive** [gatsbyjs/gatsby#15921]
## Description

If `onCreatePage` API "modifies" pages created by `gatsby-plugin-page-creator` (default src/pages) where it alters the page path, then Gatsby crashes if the corresponding page file is deleted from the filesystem.

I've created a Glitch project which is available [here](https://glitch.com/~gatsby-page-deletion-issue) to make it a little bit easier to reproduce the issue.

### Steps to reproduce

1. Add `onCreatePage` handler that modifies page path. [Here's a simple example that I used to reproduce the issue](https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#removing-trailing-slashes)

2. Run `develop` command

3. Add a sample page to the `src/pages`

4. Delete the page

### Expected result

Gatsby should handle the deletion without crashing

### Actual result

Gatsby crashes with the following output:

```
/rbd/pnpm-volume/88bed991-be5f-425b-8a6b-4648d2bfe23f/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

TypeError: Cannot read property 'internal' of undefined
    at emitter.on.action (/rbd/pnpm-volume/88bed991-be5f-425b-8a6b-4648d2bfe23f/node_modules/gatsby/dist/bootstrap/page-hot-reloader.js:26:22)
    at /rbd/pnpm-volume/88bed991-be5f-425b-8a6b-4648d2bfe23f/node_modules/mitt/dist/mitt.js:1:268
    at Array.map (<anonymous>)
    at Object.emit (/rbd/pnpm-volume/88bed991-be5f-425b-8a6b-4648d2bfe23f/node_modules/mitt/dist/mitt.js:1:252)
    at store.subscribe (/rbd/pnpm-volume/88bed991-be5f-425b-8a6b-4648d2bfe23f/node_modules/gatsby/dist/redux/index.js:74:11)
    at dispatch (/rbd/pnpm-volume/88bed991-be5f-425b-8a6b-4648d2bfe23f/node_modules/redux/lib/redux.js:227:7)
    at action (/rbd/pnpm-volume/88bed991-be5f-425b-8a6b-4648d2bfe23f/node_modules/gatsby/dist/redux/index.js:58:88)
    at /rbd/pnpm-volume/88bed991-be5f-425b-8a6b-4648d2bfe23f/node_modules/redux-thunk/lib/index.js:14:16
    at Object.deleteNode (/rbd/pnpm-volume/88bed991-be5f-425b-8a6b-4648d2bfe23f/node_modules/redux/lib/redux.js:481:12)
    at emitter.on.action (/rbd/pnpm-volume/88bed991-be5f-425b-8a6b-4648d2bfe23f/node_modules/gatsby/dist/internal-plugins/internal-data-bridge/gatsby-node.js:160:23)
    at /rbd/pnpm-volume/88bed991-be5f-425b-8a6b-4648d2bfe23f/node_modules/mitt/dist/mitt.js:1:268
    at Array.map (<anonymous>)
    at Object.emit (/rbd/pnpm-volume/88bed991-be5f-425b-8a6b-4648d2bfe23f/node_modules/mitt/dist/mitt.js:1:252)
    at store.subscribe (/rbd/pnpm-volume/88bed991-be5f-425b-8a6b-4648d2bfe23f/node_modules/gatsby/dist/redux/index.js:74:11)
    at dispatch (/rbd/pnpm-volume/88bed991-be5f-425b-8a6b-4648d2bfe23f/node_modules/redux/lib/redux.js:227:7)
    at action (/rbd/pnpm-volume/88bed991-be5f-425b-8a6b-4648d2bfe23f/node_modules/gatsby/dist/redux/index.js:58:88)
```

### Environment

System:
    OS: Linux 4.4 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (3) x64 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 10.15.3 - /opt/nvm/versions/node/v10/bin/node
    Yarn: 1.15.2 - /opt/nvm/versions/node/v10/bin/yarn
    npm: 6.4.1 - /opt/nvm/versions/node/v10/bin/npm
  Languages:
    Python: 2.7.12 - /usr/bin/python
  npmPackages:
    gatsby: ^2.13.31 => 2.13.31

**Comment by ervasive** [comment]
Does anyone know the reason why the page path is being recreated to delete a page [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-page-creator/src/gatsby-node.js#L72-L78)?

```javascript
store.getState().pages.forEach(page => {
  if (page.component === componentPath) {
    deletePage({
      path: createPath(removedPath),
      component: componentPath,
    })
  }
}
```

Wouldn't it be safe to assume that we can delete a page by simply checking its `componentPath` property? That way if some other plugin changed the `path` of the original page (by removing trailing slashes etc.) it would be deleted without crashing the dev server.

```javascript
store.getState().pages.forEach(page => {
  if (page.component === componentPath) {
    deletePage(page)
  }
}
```

**Comment by ervasive** [comment]
Not stale as far as I know

**Comment by LekoArts** [comment]
Closing this as stale since in the meantime Gatsby v3 and updated related packages were released. Please try with the latest versions and if you still see this problem open a new bug report (it must include a [minimal reproduction][reproduction].

[reproduction]: https://gatsby.dev/reproduction
