### ISSUE TITLE
TypeError: Cannot read property 'some' of undefined in yoga-layout

### ISSUE THREAD

**Issue by raisedadead** [gatsbyjs/gatsby#16141]
## Description

I get this exception thrown at me:

```
/Users/raisedadead/DEV/freeCodeCamp/client/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

TypeError: Cannot read property 'some' of undefined
    at Array.include (/Users/raisedadead/DEV/freeCodeCamp/client/node_modules/gatsby/dist/utils/webpack-utils.js:200:39)
    at Object.str [as resource] (/Users/raisedadead/DEV/freeCodeCamp/client/node_modules/webpack/lib/RuleSet.js:95:17)
    at RuleSet._run (/Users/raisedadead/DEV/freeCodeCamp/client/node_modules/webpack/lib/RuleSet.js:492:30)
    at RuleSet._run (/Users/raisedadead/DEV/freeCodeCamp/client/node_modules/webpack/lib/RuleSet.js:547:10)
    at RuleSet.exec (/Users/raisedadead/DEV/freeCodeCamp/client/node_modules/webpack/lib/RuleSet.js:475:8)
    at asyncLib.parallel (/Users/raisedadead/DEV/freeCodeCamp/client/node_modules/webpack/lib/NormalModuleFactory.js:270:34)
    at /Users/raisedadead/DEV/freeCodeCamp/client/node_modules/neo-async/async.js:6883:13
    at normalResolver.resolve (/Users/raisedadead/DEV/freeCodeCamp/client/node_modules/webpack/lib/NormalModuleFactory.js:215:9)
    at doResolve (/Users/raisedadead/DEV/freeCodeCamp/client/node_modules/enhanced-resolve/lib/Resolver.js:160:12)
    at hook.callAsync (/Users/raisedadead/DEV/freeCodeCamp/client/node_modules/enhanced-resolve/lib/Resolver.js:237:23)
    at _fn0 (eval at create (/Users/raisedadead/DEV/freeCodeCamp/client/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/raisedadead/DEV/freeCodeCamp/client/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:36:23)
    at hook.callAsync (/Users/raisedadead/DEV/freeCodeCamp/client/node_modules/enhanced-resolve/lib/Resolver.js:237:23)
    at _fn0 (eval at create (/Users/raisedadead/DEV/freeCodeCamp/client/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at hook.callAsync (/Users/raisedadead/DEV/freeCodeCamp/client/node_modules/enhanced-resolve/lib/Resolver.js:237:23)
    at _fn0 (eval at create (/Users/raisedadead/DEV/freeCodeCamp/client/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
```

### Steps to reproduce

Updated gatsby and plugins to latest versions:

```
> gatsby info

  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.1 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0.4
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.41 => 2.13.41
    gatsby-cli: ^2.7.20 => 2.7.20
    gatsby-link: ^2.2.3 => 2.2.3
    gatsby-plugin-create-client-paths: ^2.1.3 => 2.1.3
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-manifest: ^2.2.4 => 2.2.4
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2
    gatsby-plugin-sitemap: ^2.2.3 => 2.2.3
    gatsby-remark-prismjs: ^3.3.3 => 3.3.3
    gatsby-source-filesystem: ^2.1.6 => 2.1.6
    gatsby-transformer-remark: ^2.6.9 => 2.6.9
  npmGlobalPackages:
    gatsby-cli: 2.7.0

```

### Expected result

gatsby develop should not throw errors

**Comment by raisedadead** [comment]
Here is commit for the changes: https://github.com/raisedadead/freeCodeCamp/commit/54329c876f4b1bc2e6a44ca7d77812d853aa50a9

**Comment by raisedadead** [comment]
As a troubleshooting measure I have already tried cleaning `.cache` folders, etc. And also tried nuking the `node_modules` and removing the `package-lock.json` and re-installing.

**Comment by slorber** [comment]
@raisedadead I'm reopening because I clearly have a similar error, with     "gatsby": "2.13.62"  and a clean state. It happens in dev and somehow kills the dev experience when this happens.


```
[0] 11:44:14 - Found 0 errors. Watching for file changes.
[1] /Users/sebastienlorber/Desktop/projects/my-gatsby/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
[1]         throw ex;
[1]         ^
[1]
[1] TypeError: Cannot read property 'write' of null
[1]     at Zlib.callback (zlib.js:499:33)
error Command failed with exit code 7.
```
