### ISSUE TITLE
Error: write after end 

### ISSUE THREAD

**Issue by adekbadek** [gatsbyjs/gatsby#1633]
I keep getting the following error in developement:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:439:15)
    at ReadStream.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ReadStream.Readable.push (_stream_readable.js:134:10)
    at onread (fs.js:2004:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:681:17)
```
I was not able to pin-point when exactly it happens, seems random. Any idea what may cause this error? 

I'm on macOS 10.12.5, node v6.9.0, gatsby version 1.0.5

**Comment by benjaminhoffman** [comment]
@adekbadek Thanks for the issue.  There hasn't been much follow up or repro steps for a few months so I'm closing this issue for now.  If you are still having trouble or would like to keep this issue open, feel free to re-open.  Thx!
