### ISSUE TITLE
Issue with gatsby-source-filesystem

### ISSUE THREAD

**Issue by xinranwang** [gatsbyjs/gatsby#1663]
I'm getting the error below after I installed the gatsby-source-filesystem plugin and adding it in the config file.

```
    plugins: [
        {
            resolve: `gatsby-source-filesystem`,
            options: {
                name: `data`,
                path: `${__dirname}/data/`,
            },
        },
        `gatsby-transformer-json`,
    ],

```

```
building schema UNHANDLED REJECTION Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "0" does not.
    at assertValidName (/Users/xinranwang/gatsby-test/node_modules/graphql/utilities/assertValidName.js:44:11)
    at new GraphQLObjectType (/Users/xinranwang/gatsby-test/node_modules/graphql/type/definition.js:298:42)
    at inferGraphQLType (/Users/xinranwang/gatsby-test/node_modules/gatsby/dist/schema/infer-graphql-type.js:163:15)
    at /Users/xinranwang/gatsby-test/node_modules/gatsby/dist/schema/infer-graphql-type.js:514:23
    at arrayEach (/Users/xinranwang/gatsby-test/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/Users/xinranwang/gatsby-test/node_modules/lodash/lodash.js:9359:14)
    at inferObjectStructureFromNodes (/Users/xinranwang/gatsby-test/node_modules/gatsby/dist/schema/infer-graphql-type.js:475:5)
    at inferGraphQLType (/Users/xinranwang/gatsby-test/node_modules/gatsby/dist/schema/infer-graphql-type.js:100:17)
    at /Users/xinranwang/gatsby-test/node_modules/gatsby/dist/schema/infer-graphql-type.js:514:23
    at /Users/xinranwang/gatsby-test/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/Users/xinranwang/gatsby-test/node_modules/lodash/lodash.js:3001:24)
    at /Users/xinranwang/gatsby-test/node_modules/lodash/lodash.js:4913:18
    at Function.forEach (/Users/xinranwang/gatsby-test/node_modules/lodash/lodash.js:9359:14)
    at inferObjectStructureFromNodes (/Users/xinranwang/gatsby-test/node_modules/gatsby/dist/schema/infer-graphql-type.js:475:5)
    at inferGraphQLType (/Users/xinranwang/gatsby-test/node_modules/gatsby/dist/schema/infer-graphql-type.js:100:17)
    at /Users/xinranwang/gatsby-test/node_modules/gatsby/dist/schema/infer-graphql-type.js:514:23
```

**Comment by sebastienfi** [comment]
In your JSON the key must be named and cannot be an integer. This is invalid JSON you have provided.

**Comment by jbolda** [comment]
Is `data` a reserved name? Otherwise what is invalid?

**Comment by jquense** [comment]
The invalid error is due to some data in the JSON files. GraphQL has **extremely** strict rules about what a valid identifier is, much stricter then what constitutes a valid JSON key. 

```json
[
 { '1': 'foo' } 
]
```

if perfectly fine JSON but when a GQL type is being inferred from the data here it will try and create an Object type with a field name: `'0'` which is invalid, since names need to start with an `a-zA-Z`.

My guess is that you have some object that maybe should be an array in your data, or just some data with numerical keys. It's hard to know without seeing the data. Gatsby tries to handle these cases by removing invalid characters from field names but it doesn't accound for this case :\

**Comment by sebastienfi** [comment]
Maybe this should be a PR for the source filesystem plugin.

In WordPress source I included this function to validate the name in respect to GraphQL naming conventions: 

```javascript

/**
 * Validate the GraphQL naming convetions & protect specific fields.
 *
 * @param {any} key
 * @returns the valid name
 */
function getValidName(key) {
  let nkey = key
  const NAME_RX = /^[_a-zA-Z][_a-zA-Z0-9]*$/
  if (!NAME_RX.test(nkey)) {
    nkey = `_${nkey}`.replace(/-/g, `_`).replace(/:/g, `_`)
    if (_verbose)
      console.log(
        colorized.out(
          `Object with key "${key}" breaks GraphQL naming convention. Renamed to "${nkey}"`,
          colorized.color.Font.FgRed
        )
      )
  }
  if (restrictedNodeFields.includes(nkey)) {
    if (_verbose)
      console.log(
        `Restricted field found for ${nkey}. Prefixing with ${conflictFieldPrefix}.`
      )
    nkey = `${conflictFieldPrefix}${nkey}`
  }
  return nkey
}
```
... which is called from a function that parse the JSON reccursively : 
```javascript
/**
 * Add fields recursively
 *
 * @param {any} ent
 * @param {any} newEnt
 * @returns the new node
 */
async function recursiveAddFields(ent, newEnt, createNode) {
  for (let k of Object.keys(ent)) {
    if (!newEnt.hasOwnProperty(k)) {
      let key = getValidName(k)
      if (key !== `acf`) {
        newEnt[key] = ent[k]
        // Nested Objects & Arrays of Objects
        if (typeof ent[key] == `object`) {
          if (!Array.isArray(ent[key]) && ent[key] != null) {
            newEnt[key] = recursiveAddFields(ent[key], {}, createNode)
          } else if (Array.isArray(ent[key])) {
            if (ent[key].length > 0 && typeof ent[key][0] == `object`) {
              ent[k].map((el, i) => {
                newEnt[key][i] = recursiveAddFields(el, {}, createNode)
              })
            }
          }
        }
      }
    }
  }
  return newEnt
}
```

**Comment by xinranwang** [comment]
Thanks everyone. I didn't realize it could be a problem with my json file. It worked after I cleaned it up.

The issue wasn't the key though. I had a array of arrays in the json which was the cause. The error message I got wasn't that helpful. It would be great if it can pinpoint the issue of the json.
