### ISSUE TITLE
First time usage Error: Cannot find module package.json

### ISSUE THREAD

**Issue by zanedev** [gatsbyjs/gatsby#1699]
Hi first time gatsby user here, I installed gatsby globally per the docs using npm and every time I run gatsby I get the error output below.  Wondering if anybody else is having any issues with it?  I'm on Mac OS Sierra, running npm version 3.10.8

npm install --global gatsby-cli
/usr/local/bin/gatsby -> /usr/local/lib/node_modules/gatsby-cli/index.js
/usr/local/lib
└─┬ gatsby-cli@1.0.2 
  ├─┬ babel-runtime@6.25.0 
  │ ├── core-js@2.4.1 
  │ └── regenerator-runtime@0.10.5 
  ├── commander@2.11.0 
  ├── lodash@4.17.4 
  └─┬ resolve-cwd@2.0.0 
    └── resolve-from@3.0.0  

gatsby
{ Error: Cannot find module '/Users/myuser/Projects/package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby-cli/index.js:21:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }

Usage:  [command] [options]

  Options:

    -V, --version  output the version number
    -h, --help     output usage information

  Commands:

    new [rootPath] [starter]  Create new Gatsby project.
To show subcommand help:

    gatsby [command] -h

**Comment by KyleAMathews** [comment]
Just fixed that :-) https://github.com/gatsbyjs/gatsby/commit/81f0e79a5eee368ad826d52013c0ed48588ba7f0

Upgrade by running `npm install -g gatsby-cli@latest`.

Thanks for the bug report!

**Comment by zanedev** [comment]
thanks that fixed this issue. I have another error when creating the project, thought it was related to the other error so I didn't report it first time but its still there after the upgrade

gatsby new myproject
module.js:471
    throw err;
    ^

Error: Cannot find module '../utils/new'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Command.<anonymous> (/usr/local/lib/node_modules/gatsby-cli/index.js:98:20)
    at Command.listener (/usr/local/lib/node_modules/gatsby-cli/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/local/lib/node_modules/gatsby-cli/node_modules/commander/index.js:635:12)
    at Command.parse (/usr/local/lib/node_modules/gatsby-cli/node_modules/commander/index.js:457:21)

**Comment by KyleAMathews** [comment]
Oh oops, lemme fix that too 🤦‍♂️

**Comment by ftroitsky** [comment]
Hi just hit the same in #1700

**Comment by KyleAMathews** [comment]
Ok, try upgrading again to the latest.

Sorry peeps, glad you piped up quickly. Needed more testing clearly.

**Comment by zanedev** [comment]
That did it thanks!  just happened to be my first impression of gatsby but I won't hold it against ya since you fixed it so fast 👍

**Comment by KyleAMathews** [comment]
Haha thanks :-) Hopefully things will go smoother from here :-D
