### ISSUE TITLE
Error: Cannot find module '../utils/new'

### ISSUE THREAD

**Issue by ftroitsky** [gatsbyjs/gatsby#1700]
Hi just installed on node v6.11.2 and immediately hit the issue 
```
module.js:471
    throw err;
    ^

Error: Cannot find module '../utils/new'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Command.<anonymous> (/Users/ftroitsky/.nvm/versions/node/v6.11.2/lib/node_modules/gatsby-cli/index.js:98:20)
    at Command.listener (/Users/ftroitsky/.nvm/versions/node/v6.11.2/lib/node_modules/gatsby-cli/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/Users/ftroitsky/.nvm/versions/node/v6.11.2/lib/node_modules/gatsby-cli/node_modules/commander/index.js:635:12)
    at Command.parse (/Users/ftroitsky/.nvm/versions/node/v6.11.2/lib/node_modules/gatsby-cli/node_modules/commander/index.js:457:21)
```

**Comment by KyleAMathews** [comment]
Should be fixed in the latest version of `gatsby-cli`. Thanks for reporting!

**Comment by ftroitsky** [comment]
I works now! 👍  Thank you!
