### ISSUE TITLE
[gatsby-plugin-typescript] TSX file with exported query does not run query

### ISSUE THREAD

**Issue by berwyn** [gatsbyjs/gatsby#1741]
I'm trying to [build a gatsby project](https://github.com/berwyn/stormtour) and started playing around with using GraphQL queries in it. I followed examples in the [typescript example](https://github.com/gatsbyjs/gatsby/blob/master/examples/using-typescript/src/pages/index.tsx#L21) as well as the [sharp example](https://github.com/gatsbyjs/gatsby/blob/master/examples/image-processing/src/pages/index.js#L313) and neither seem to work, instead I get something to the effect of
```
success createPagesStatefully — 0.032 s
⠁ Failed to parse /Users/berwyn/dev/stormtour/src/pages/index.tsx
{ SyntaxError: Unexpected token (38:2)
    at Parser.pp$5.raise (/Users/berwyn/dev/stormtour/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/berwyn/dev/stormtour/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$8.flowObjectTypeSemicolon (/Users/berwyn/dev/stormtour/node_modules/babylon/lib/index.js:5466:10)
    at Parser.pp$8.flowParseObjectType (/Users/berwyn/dev/stormtour/node_modules/babylon/lib/index.js:5446:16)
    at Parser.pp$8.flowParseInterfaceish (/Users/berwyn/dev/stormtour/node_modules/babylon/lib/index.js:5189:20)
    at Parser.pp$8.flowParseInterface (/Users/berwyn/dev/stormtour/node_modules/babylon/lib/index.js:5206:8)
    at Parser.parseStatement (/Users/berwyn/dev/stormtour/node_modules/babylon/lib/index.js:5858:21)
    at Parser.pp$1.parseBlockBody (/Users/berwyn/dev/stormtour/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/Users/berwyn/dev/stormtour/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/Users/berwyn/dev/stormtour/node_modules/babylon/lib/index.js:1673:17)
    at Object.parse (/Users/berwyn/dev/stormtour/node_modules/babylon/lib/index.js:7246:37)
    at _callee$ (/Users/berwyn/dev/stormtour/node_modules/gatsby/dist/internal-plugins/query-runner/file-parser.js:145:29)
    at tryCatch (/Users/berwyn/dev/stormtour/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/berwyn/dev/stormtour/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/berwyn/dev/stormtour/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/berwyn/dev/stormtour/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30) pos: 774, loc: Position { line: 38, column: 2 } }
success extract queries from components — 0.095 s
```

The site will continue to build and serve, but the `data` node on the props is undefined. Is there something I'm missing about how to use these queries? Of note, the queries run fine if I test them in iQL, they just fail at build time :/

[Here's the query I'm running](https://github.com/berwyn/stormtour/blob/master/src/pages/index.tsx#L185)

**OS**: macOS High Sierra (10.13)
**Node**: 8.2.1
**npm**: 5.3.0
**package.json**:
```json
{
  "dependencies": {
    "@types/react": "^16.0.1",
    "gatsby": "^1.6.6",
    "gatsby-link": "^1.6.5",
    "gatsby-plugin-react-helmet": "^1.0.1",
    "gatsby-plugin-sharp": "^1.6.0",
    "gatsby-plugin-typescript": "^1.4.1",
    "gatsby-source-filesystem": "^1.4.1",
    "gatsby-transformer-sharp": "^1.6.0",
    "graphql": "^0.10.5",
    "material-ui": "^0.18.7",
    "material-ui-icons": "^1.0.0-alpha.19",
    "raw-loader": "^0.5.1",
    "react-helmet": "^5.1.3",
    "react-tap-event-plugin": "^2.0.1",
    "typeface-noto-sans": "0.0.34",
    "typeface-noto-sans-tc": "0.0.31",
    "typescript": "^2.4.2",
    "typestyle": "^1.3.7"
  }
}
```
**gatsby-config.js**:
```js
module.exports = {
  siteMetadata: {
    title: 'Stormtour'
  },
  plugins: [
    'gatsby-plugin-typescript',
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/images`,
        name: 'images',
      },
    },
    'gatsby-plugin-sharp',
    'gatsby-plugin-react-helmet',
    'gatsby-transformer-sharp',
  ]
}
```
**gatsby-node.js**: none
**gatsby-ssr.js**: none
**gatsby-browser.js**: none
**tsconfig.json**: [link](https://github.com/berwyn/stormtour/blob/master/tsconfig.json)

**Comment by KyleAMathews** [comment]
Could you add a PR to the Typescript example that reproduces the error you're seeing? I can check it out then.

**Comment by magicly** [comment]
@berwyn hi,  your problem just happened to me. I found the reason is there need a ';' on 38 line:
```
interface Tag {
  name: string
  avatar: any
}js
```
should be
```js
interface Tag {
  name: string;
  avatar: any;
}
```

**Comment by berwyn** [comment]
I tried your suggestion @magicly but even going through the entire project and adding any omitted semicolons didn't fix the issue. The same error crops up for a different spot in the file and the exported page query isn't run

**Comment by berwyn** [comment]
Upon further examination, I wonder if [this code](https://github.com/gatsbyjs/gatsby/blob/f8956a6449475c1dc364f328ab173857b4e9ebcd/packages/gatsby/src/internal-plugins/query-runner/file-parser.js#L41-L44) might have anything to do with it. My experiments show that `preprocessSource` items in `gatsby-node.js` don't seem to be hit, and with this being the only reference I could find in the codebase, it would make sense that the query extractor is likely receiving unmodified typescript files, which makes sense for both the error and location

**Comment by KyleAMathews** [comment]
@berwyn I disabled this a while ago in the final stages of getting 1.0 ready as it was causing unrelated (to Typescript) troubles. If uncomment the code do things work again?

**Comment by berwyn** [comment]
I was having some troubles getting the dev setup running, but I'll give it another stab tonight and see what I can come up with

**Comment by nickguletskii** [comment]
In other words, Gatsby doesn't support GraphQL queries in non-JS components at the moment. I think this deserves to be mentioned in the documentation to avoid confusion.

**Comment by jquense** [comment]
Gatsby does support queries in non js, and typescript specifically, has code for handling this (and a test).

**Comment by nickguletskii** [comment]
Without `preprocessSource` being called, Gatsby does *not* support queries in TypeScript components. The only examples of GraphQL queries being executed from a TypeScript file I can find are those that can be parsed directly by Babel without TypeScript.

**Comment by jquense** [comment]
My point is it's a bug if it doesn't work. Let's no document the bug but fix it. Folks here don't use TS a lot so it'd great if folks who do could help us out contribute and test a fix, so we can get it all sorted for y'all quickly

**Comment by KyleAMathews** [comment]
This issue was fixed a while ago
