### ISSUE TITLE
gatsby build throws TypeError: Promise resolver null is not a function

### ISSUE THREAD

**Issue by FinnFrotscher** [gatsbyjs/gatsby#17570]
## Description
`gatsby build` throws `TypeError: Promise resolver null is not a function`

### Environment

```
$ gatsby info

  System:
    OS: Linux 4.14 Manjaro Linux undefined
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.16.0 - ~/.nvm/versions/node/v10.15.3/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 3.7.4 - /usr/bin/python
  Browsers:
    Firefox: 69.0
  npmPackages:
    gatsby: ^2.4.3 => 2.4.3
    gatsby-image: ^2.0.41 => 2.0.41
    gatsby-plugin-catch-links: ^2.0.13 => 2.0.13
    gatsby-plugin-copy-files: ^1.0.3 => 1.0.3
    gatsby-plugin-feed: ^2.2.0 => 2.2.0
    gatsby-plugin-google-analytics: ^2.0.19 => 2.0.19
    gatsby-plugin-lodash: ^3.0.5 => 3.0.5
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1
    gatsby-plugin-nprogress: ^2.0.10 => 2.0.10
    gatsby-plugin-offline: ^2.1.0 => 2.1.0
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sharp: ^2.0.37 => 2.0.37
    gatsby-plugin-sitemap: ^2.1.0 => 2.1.0
    gatsby-plugin-twitter: ^2.0.13 => 2.0.13
    gatsby-source-filesystem: ^2.1.19 => 2.1.19
    gatsby-transformer-json: ^2.2.7 => 2.2.7
    gatsby-transformer-sharp: ^2.1.19 => 2.1.19
```

### Steps to reproduce
cannot publish the code.

### Expected result
A working bundle should be output.

### Actual result

```
/usr/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

TypeError: Promise resolver null is not a function
    at new Promise (<anonymous>)
    at exports.default._receive (/home/finn/projects/cb/mother/services/collectivebrain.co/node_modules/jest-worker/build/worker.js:185:19)
    at ChildProcess.emit (events.js:189:13)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by FinnFrotscher** [comment]
## Additional Information
the last line in the following snippet throws the error:
```
  _receive(response /* Should be ParentMessage */) {
    const item = this._queue;

    if (!item) {
      throw new TypeError('Unexpected response with an empty queue');
    }

    const onProcessEnd = item.onProcessEnd;

    console.log(response)
    console.log((_types || _load_types()))

    this._busy = false;
    this._process();

    switch (response[0]) {
      case (_types || _load_types()).PARENT_MESSAGE_OK:
        onProcessEnd(null, response[1]);
        break;

      case (_types || _load_types()).PARENT_MESSAGE_ERROR:
        let error = response[4];

        if (error != null && typeof error === 'object') {
          const extra = error;
          const NativeCtor = global[response[1]];
          const Ctor = typeof NativeCtor === 'function' ? NativeCtor : Error;

          error = new Ctor(response[2]);

```


the two console.logs return
```
success Building production JavaScript and CSS bundles — 8.258 s

[ 1, 'Promise', null, null, { context: { path: '/contact/' } } ]
{ CHILD_MESSAGE_INITIALIZE: 0,
  CHILD_MESSAGE_CALL: 1,
  CHILD_MESSAGE_END: 2,
  PARENT_MESSAGE_OK: 0,
  PARENT_MESSAGE_ERROR: 1 }

/usr/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

TypeError: Promise resolver null is not a function
    at new Promise (<anonymous>)
    at exports.default._receive (/home/finn/projects/cb/mother/services/collectivebrain.co/node_modules/jest-worker/build/worker.js:187:19)
    at ChildProcess.emit (events.js:189:13)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by wardpeet** [comment]
@FinnFrotscher this is mostly an issue with the website itself. No need to log it on yoga-layout as it's not their bug.

To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by FinnFrotscher** [comment]
will do.
