### ISSUE TITLE
MDX GraphiQL error with html field

### ISSUE THREAD

**Issue by zslabs** [gatsbyjs/gatsby#17592]
**Describe the bug**
Cloning down https://github.com/ChristopherBiscardi/gatsby-starter-mdx-basic running the following on GraphiQL:

```
query MyQuery {
  allMdx {
    edges {
      node {
        excerpt
        html
      }
    }
  }
}
```

Returns this:

```
{
  "errors": [
    {
      "message": "String cannot represent value: { context: { sourceMessage: \"gatsby-plugin-mdx: renderMdxBody was unavailable when rendering html.\\n>> This is a bug.\" }, text: \"gatsby-plugin-mdx: renderMdxBody was unavailable when rendering html.\\n>> This is a bug.\", level: \"ERROR\", stack: [], docsUrl: \"https://gatsby.dev/issue-how-to\" }",
      "locations": [
        {
          "line": 5,
          "column": 9
        }
      ],
      "path": [
        "allMdx",
        "edges",
        0,
        "node",
        "html"
      ],
      "stack": [
        "TypeError: String cannot represent value: { context: { sourceMessage: \"gatsby-plugin-mdx: renderMdxBody was unavailable when rendering html.\\n>> This is a bug.\" }, text: \"gatsby-plugin-mdx: renderMdxBody was unavailable when rendering html.\\n>> This is a bug.\", level: \"ERROR\", stack: [], docsUrl: \"https://gatsby.dev/issue-how-to\" }",
        "    at GraphQLScalarType.serializeString [as serialize] (/Users/zach/Sites/my-mdx-starter2/node_modules/graphql/type/scalars.js:159:9)",
        "    at completeLeafValue (/Users/zach/Sites/my-mdx-starter2/node_modules/graphql/execution/execute.js:641:37)",
        "    at completeValue (/Users/zach/Sites/my-mdx-starter2/node_modules/graphql/execution/execute.js:587:12)",
        "    at /Users/zach/Sites/my-mdx-starter2/node_modules/graphql/execution/execute.js:500:16",
        "    at process._tickCallback (internal/process/next_tick.js:68:7)"
      ]
    },
    {
      "message": "String cannot represent value: { context: { sourceMessage: \"gatsby-plugin-mdx: renderMdxBody was unavailable when rendering html.\\n>> This is a bug.\" }, text: \"gatsby-plugin-mdx: renderMdxBody was unavailable when rendering html.\\n>> This is a bug.\", level: \"ERROR\", stack: [], docsUrl: \"https://gatsby.dev/issue-how-to\" }",
      "locations": [
        {
          "line": 5,
          "column": 9
        }
      ],
      "path": [
        "allMdx",
        "edges",
        1,
        "node",
        "html"
      ],
      "stack": [
        "TypeError: String cannot represent value: { context: { sourceMessage: \"gatsby-plugin-mdx: renderMdxBody was unavailable when rendering html.\\n>> This is a bug.\" }, text: \"gatsby-plugin-mdx: renderMdxBody was unavailable when rendering html.\\n>> This is a bug.\", level: \"ERROR\", stack: [], docsUrl: \"https://gatsby.dev/issue-how-to\" }",
        "    at GraphQLScalarType.serializeString [as serialize] (/Users/zach/Sites/my-mdx-starter2/node_modules/graphql/type/scalars.js:159:9)",
        "    at completeLeafValue (/Users/zach/Sites/my-mdx-starter2/node_modules/graphql/execution/execute.js:641:37)",
        "    at completeValue (/Users/zach/Sites/my-mdx-starter2/node_modules/graphql/execution/execute.js:587:12)",
        "    at /Users/zach/Sites/my-mdx-starter2/node_modules/graphql/execution/execute.js:500:16",
        "    at process._tickCallback (internal/process/next_tick.js:68:7)"
      ]
    }
  ],
  "data": {
    "allMdx": {
      "edges": [
        {
          "node": {
            "html": null
          }
        },
        {
          "node": {
            "html": null
          }
        }
      ]
    }
  }
}
```

It looks like this was originally added in https://github.com/ChristopherBiscardi/gatsby-mdx/pull/164 but maybe there's a regression? 

**Expected behavior**
Returns rendered HTML.

Thanks for any help!

**Comment by LekoArts** [comment]
Hi, thanks for the issue and sorry for apparently some misleading docs/poor DX. You can only use the `html` field on build, and not in development/GraphiQL.
Issue to track this: https://github.com/gatsbyjs/gatsby/issues/17210

Please use `body` in all other instances :)
