### ISSUE TITLE
gatsy first install does not build (childImageSharp)

### ISSUE THREAD

**Issue by h20hb** [gatsbyjs/gatsby#17692]
## Description

I just did a fresh gatsby install. When starting the development server the process quits suddendly.

When I remove the "gatsby-plugin-manifest" section from gatsby-config.js, the development server ends a bit later on step "run static queries". Also removing the childImageSharp part from image.js finally starts the development server.

Something seems to go wrong with gatsby-transformer-sharp, but I apart from not starting the development server I don't get any errors.

When updating an existing (and working) gatsby project to the same version I run into the exact same problems. Running gatsby clean and re-installing node_modules didn't help.

 Any help would be much appreciated!

## Steps to reproduce

```
gatsby new test-site
gatsby develop
```

### Expected result

Starting the development build.

### Actual result

```
λ gatsby develop
success open and validate gatsby-configs - 0.089 s
success load plugins - 1.119 s
success onPreInit - 0.088 s
success initialize cache - 0.099 s
success copy gatsby files - 0.182 s
success onPreBootstrap - 0.074 s
success source and transform nodes - 0.364 s
success Add explicit types - 0.071 s
success Add inferred types - 0.269 s
success Processing types - 0.186 s
success building schema - 0.742 s
success createPages - 0.085 s
success createPagesStatefully - 0.142 s
success onPreExtractQueries - 0.076 s
success update schema - 0.107 s
success extract queries from components - 0.430 s
success write out requires - 0.123 s
success write out redirect data - 0.067 s
⠋ onPostBootstrap
⠋ Build manifest and related icons
```

Build process quits here....

### Environment

Gatsby CLI version: 2.7.47
Gatsby version: 2.15.16

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Binaries:
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.15.16 => 2.15.16 
    gatsby-image: ^2.2.19 => 2.2.19 
    gatsby-plugin-manifest: ^2.2.16 => 2.2.16 
    gatsby-plugin-offline: ^3.0.7 => 3.0.7 
    gatsby-plugin-react-helmet: ^3.1.7 => 3.1.7 
    gatsby-plugin-sharp: ^2.2.22 => 2.2.22 
    gatsby-source-filesystem: ^2.1.22 => 2.1.22 
    gatsby-transformer-sharp: ^2.2.14 => 2.2.14

**Comment by h20hb** [comment]
I had everything up-to-date, except for node. Updating to the latest LTS version followed by an npm install fixed the problem... hurrah.

**Comment by JustFly1984** [comment]
Please reopen

I have this weird issue:

I have a gatsby project running it on node 12 for last 3 months. using gatsby-plugin-manifest with dependency sharp@^0.23.0 in yarn.lock

I have a script which removes yarn.lock, node_modules and .cache, and runes yarn to create fresh yarn.lock pretty much often, but today I gon new error:

```
[4/4] 🔨  Building fresh packages...
[6/16] ⡀ sharp
[-/16] ⡀ waiting...
[-/16] ⡀ waiting...
[-/16] ⢀ waiting...
error /Users/justfly/projects/poolotto-gatsby/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /Users/justfly/projects/poolotto-gatsby/node_modules/sharp
Output:
info sharp Using cached /Users/justfly/.npm/_libvips/libvips-8.8.1-darwin-x64.tar.gz
prebuild-install WARN install dlopen(/Users/justfly/projects/poolotto-gatsby/node_modules/sharp/build/Release/sharp.node, 1): Library not loaded: @rpath/libvips-cpp.42.dylib
prebuild-install WARN install   Referenced from: /Users/justfly/projects/poolotto-gatsby/node_modules/sharp/build/Release/sharp.node
prebuild-install WARN install   Reason: image not found
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@12.9.0 | darwin | x64
gyp info find Python using Python version 2.7.15 found at "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/justfly/.nvm/versions/node/v12.9.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/justfly/projects/poolotto-gatsby/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/justfly/.nvm/versions/node/v12.9.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/justfly/Library/Caches/node-gyp/12.9.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/justfly/Library/Caches/node-gyp/12.9.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/justfly/.nvm/versions/node/v12.9.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/justfly/Library/Caches/node-gyp/12.9.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/justfly/projects/poolotto-gatsby/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:25:10: fatal error: 'vips/vips8' file not found
#include <vips/vips8>
         ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/justfly/.nvm/versions/node/v12.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/justfly/.nvm/versions/node/v12.9.0/bin/node" "/Users/justfly/.nvm/versions/node/v12.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/justfly/projects/poolotto-gatsby/node_modules/sharp
gyp ERR! node -v v12.9.0



error Command failed with exit code 1.
```

although if I just remove node_modules and .cache, without removing yarn.lock, everything is installed without an error.

**Comment by JustFly1984** [comment]
<img width="283" alt="Screenshot 2019-09-24 03 11 18" src="https://user-images.githubusercontent.com/2255993/65471746-02bf2080-de79-11e9-89ea-2f3dc1415190.png">
