### ISSUE TITLE
[gatsby-source-wordpress] Failed at the gatsby-example-using-wordpress@1.0.0-beta.6

### ISSUE THREAD

**Issue by AmGarera** [gatsbyjs/gatsby#1774]
Gatsby Version: 1.8.3
NodeJS Version: 8.2.1
MacOS 10.12.6

The only changes made were in the Gatsby-config.js file the rest is stock from the wordpress example, I'm attempting to just run it to build my new front end with Gatsby and it looks like the following

```  module.exports = {
  siteMetadata: {
    title: 'A sample site using gatsby-source-wordpress',
    subtitle: 'Data fetched from a site hosted on wordpress.com'
  },
  plugins: [
    // https://public-api.wordpress.com/wp/v2/sites/gatsbyjsexamplewordpress.wordpress.com/pages/
    /*
     * Gatsby's data processing layer begins with “source”
     * plugins. Here the site sources its data from Wordpress.
     */
    {
      resolve: 'gatsby-source-wordpress',
      options: {
        /*
        * The base URL of the Wordpress site without the trailingslash and the protocol. This is required.
        * Example : 'gatsbyjswpexample.wordpress.com' or 'www.example-site.com'
        */
        baseUrl: 'www.androidtv.news',
        // The protocol. This can be http or https.
        protocol: 'https',
        // Indicates whether the site is hosted on wordpress.com.
        // If false, then the asumption is made that the site is self hosted.
        // If true, then the plugin will source its content on wordpress.com using the JSON REST API V2.
        // If your site is hosted on wordpress.org, then set this to false.
        hostingWPCOM: false,
        // If useACF is true, then the source plugin will try to import the Wordpress ACF Plugin contents.
        // This feature is untested for sites hosted on Wordpress.com
        useACF: false,
        auth: {
          // If auth.user and auth.pass are filled, then the source plugin will be allowed
          // to access endpoints that are protected with .htaccess.
          htaccess_user: '[do-not-include-passwords]',
          htaccess_pass: '[do-not-include-passwords]',
          htaccess_sendImmediately: false,

          // If hostingWPCOM is true then you will need to communicate with wordpress.com API
          // in order to do that you need to create an app (of type Web) at https://developer.wordpress.com/apps/
          // then add your clientId, clientSecret, username, and password here
          wpcom_app_clientSecret: 'NMPnXYFtj2gKas7V1kZyMxr7oLry9V5ZxIyBQGu2txjVHg0GhFz6RYcKopkHICYg',
          wpcom_app_clientId: '54793',
          wpcom_user: 'gatsbyjswpexample@gmail.com',
          wpcom_pass: 'very-secured-password',
        },
        // Set verboseOutput to true to display a verbose output on `npm run develop` or `npm run build`
        // It can help you debug specific API Endpoints problems
        verboseOutput: true,
      },
    },

  ],
}
  ```

**Comment by KyleAMathews** [comment]
What exactly is the problem?

**Comment by sebastienfi** [comment]
I ran with your config and see the error.
Thanks for reporting it.
Error is 👍 
```
success source and transform nodes — 121.526 s
⠄ building schemaName "__jetpack_v4" must not begin with "__", which is reserved by GraphQL introspection. In a future release of graphql this will become a hard error.
    at assertValidName (C:\Projets-Repositories\Gatsby\Gatsby-wp\gatsby\examples\using-wordpress\node_modules\graphql\utilities\assertValidName.js:38:19)
    at C:\Projets-Repositories\Gatsby\Gatsby-wp\gatsby\examples\using-wordpress\node_modules\graphql\type\definition.js:694:44
    at Array.forEach (native)
    at GraphQLInputObjectType._defineFieldMap (C:\Projets-Repositories\Gatsby\Gatsby-wp\gatsby\examples\using-wordpress\node_modules\graphql\type\definition.js:693:16)
    at GraphQLInputObjectType.getFields (C:\Projets-Repositories\Gatsby\Gatsby-wp\gatsby\examples\using-wordpress\node_modules\graphql\type\definition.js:682:49)
    at typeMapReducer (C:\Projets-Repositories\Gatsby\Gatsby-wp\gatsby\examples\using-wordpress\node_modules\graphql\type\schema.js:224:26)
    at C:\Projets-Repositories\Gatsby\Gatsby-wp\gatsby\examples\using-wordpress\node_modules\graphql\type\schema.js:227:20
    at Array.forEach (native)
    at typeMapReducer (C:\Projets-Repositories\Gatsby\Gatsby-wp\gatsby\examples\using-wordpress\node_modules\graphql\type\schema.js:225:28)
    at Array.reduce (native)
    at C:\Projets-Repositories\Gatsby\Gatsby-wp\gatsby\examples\using-wordpress\node_modules\graphql\type\schema.js:217:36
    at Array.forEach (native)
    at typeMapReducer (C:\Projets-Repositories\Gatsby\Gatsby-wp\gatsby\examples\using-wordpress\node_modules\graphql\type\schema.js:210:27)
    at Array.reduce (native)
    at new GraphQLSchema (C:\Projets-Repositories\Gatsby\Gatsby-wp\gatsby\examples\using-wordpress\node_modules\graphql\type\schema.js:98:34)
    at _callee$ (C:\Projets-Repositories\Gatsby\Gatsby-wp\gatsby\examples\using-wordpress\node_modules\gatsby\dist\schema\index.js:54:20)
```

This is a new use case with Jetpack v4, one should implement a function that normalize the names so that the GraphQL scema can build. 
Most likely here https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/gatsby-node.js#L360-L365

**Comment by AmGarera** [comment]
Thanks @sebastienfi so what should I do/ what can be done about this? and @KyleAMathews I can't run gatsby develop without it giving a error code 1 at the end of the command being run.

**Comment by sebastienfi** [comment]
I will investigate in a couple hours and publish a patch ;)

**Comment by AmGarera** [comment]
Thanks @sebastienfi  I'll be looking forward to it!
