### ISSUE TITLE
Gatsbyjs build fails with no error message.

### ISSUE THREAD

**Issue by whmountains** [gatsbyjs/gatsby#1788]
I've tried looking at render-page.js:78868 which fortunately points to one of my components but I can't find any errors.  I think there's supposed to be an error message but it just shows 'Error:' with nothing after it.

```
success Generating CSS — 9.491 s
success Compiling production bundle.js — 17.304 s
⠐ Generating static HTML for pages
error Generating static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND
  Error: 
    Error: 
    
    - render-page.js:78868   Index.render
      render-page.js:78868:35
    
    - render-page.js:15074   ReactCompositeComponentWrapper._renderValidatedComponen      0mtWithoutOwnerOrContext
      render-page.js:15074:31
    
    - render-page.js:15097   ReactCompositeComponentWrapper._renderValidatedComponen      0mt
      render-page.js:15097:33
    
    - render-page.js:14637   ReactCompositeComponentWrapper.performInitialMount
      render-page.js:14637:31
    
    - render-page.js:14533   ReactCompositeComponentWrapper.mountComponent
      render-page.js:14533:22
    
    - render-page.js:7445   [0mObject.mountComponent
      render-page.js:7445:36
    
    - render-page.js:13674   ReactDOMComponent.mountChildren
      render-page.js:13674:45
    
    - render-page.js:10684   ReactDOMComponent._createContentMarkup
      render-page.js:10684:33
    
    - render-page.js:10551   ReactDOMComponent.mountComponent
      render-page.js:10551:30
    
    - render-page.js:7445   [0mObject.mountComponent
      render-page.js:7445:36
```

**Comment by danoc** [comment]
@whmountains – Can you open `public/render-page.js` (usually a gitignore'd file) and look at line 78868?

That might give you a better sense of the issue. It may be related to #1786.

**Comment by whmountains** [comment]
Update, I was able to get the real error message by editing the `createErrorFromString` function in `errors.js`:

```TypeError: Cannot read property 'splashImg' of undefined
    at Index.render (render-page.js:78868:35)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (render-page.js:15074:31)
    at ReactCompositeComponentWrapper._renderValidatedComponent (render-page.js:15097:33)
    at ReactCompositeComponentWrapper.performInitialMount (render-page.js:14637:31)
    at ReactCompositeComponentWrapper.mountComponent (render-page.js:14533:22)
    at Object.mountComponent (render-page.js:7445:36)
    at ReactDOMComponent.mountChildren (render-page.js:13674:45)
    at ReactDOMComponent._createContentMarkup (render-page.js:10684:33)
    at ReactDOMComponent.mountComponent (render-page.js:10551:30)
    at Object.mountComponent (render-page.js:7445:36)
```

So it seems like Gatsby is not parsing the error string correctly.

**Comment by danoc** [comment]
@whmountains – Is `slashImg` supposed to come from `props.data`?

**Comment by whmountains** [comment]
@danoc yes, `splashImg` comes from `props.data`. The relevant code is:

```js
const { splashImg } = this.props.data
```
and the graphql query is:
```graphql
query IndexQuery {
    splashImg: imageSharp(id: { regex: "/splash-full/" }) {
      ...imageInfo
    }
}
```

**Comment by whmountains** [comment]
@danoc Thanks for making the connection to #1786!

**Comment by KyleAMathews** [comment]
This is fixed now https://github.com/gatsbyjs/gatsby/pull/1799 🎉
