### ISSUE TITLE
Unhandled rejection ReferenceError: regenerationRuntime is not defined for advanced-starter demo

### ISSUE THREAD

**Issue by ddiviacchi** [gatsbyjs/gatsby#1815]
Hi,
I was wondering if someone could help guide me on how to troubleshoot this issue that I am recieving a regenerationRuntime when running the gatsby-advanced-starter demo with gatsby develop.  I am not sure but it seems like it could be an issue related to babel.   I am able to run the basic demo with no problems.
success copy gatsby files - 0.159 s
? source and transform nodesUnhandled rejection ReferenceError: regeneratorRuntime is not defined
    at D:\GatsbyAdvancedStarter\node_modules\gatsby-source-filesystem\index.js:8:46
    at Object.<anonymous> (D:\GatsbyAdvancedStarter\node_modules\gatsby-source-filesystem\index.j
s:34:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at D:\GatsbyAdvancedStarter\node_modules\gatsby\dist\redux\index.js:92:23
    at Promise._execute (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\debuggability.
js:300:9)
    at Promise._resolveFromExecutor (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\pr
omise.js:483:18)
    at new Promise (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\promise.js:79:10)
    at exports.loadNodeContent (D:\GatsbyAdvancedStarter\node_modules\gatsby\dist\redux\index.js:
86:12)
    at Object._callee$ (D:\GatsbyAdvancedStarter\node_modules\gatsby-transformer-remark\on-node-c
reate.js:48:20)
    at tryCatch (D:\GatsbyAdvancedStarter\node_modules\regenerator-runtime\runtime.js:65:40)

Unhandled rejection ReferenceError: regeneratorRuntime is not defined
    at D:\GatsbyAdvancedStarter\node_modules\gatsby-source-filesystem\index.js:8:46
    at Object.<anonymous> (D:\GatsbyAdvancedStarter\node_modules\gatsby-source-filesystem\index.j
s:34:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at D:\GatsbyAdvancedStarter\node_modules\gatsby\dist\redux\index.js:92:23
    at Promise._execute (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\debuggability.
js:300:9)
    at Promise._resolveFromExecutor (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\pr
omise.js:483:18)
    at new Promise (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\promise.js:79:10)
    at exports.loadNodeContent (D:\GatsbyAdvancedStarter\node_modules\gatsby\dist\redux\index.js:
86:12)
    at Object._callee$ (D:\GatsbyAdvancedStarter\node_modules\gatsby-transformer-remark\on-node-c
reate.js:48:20)
    at tryCatch (D:\GatsbyAdvancedStarter\node_modules\regenerator-runtime\runtime.js:65:40)

Unhandled rejection ReferenceError: regeneratorRuntime is not defined
    at D:\GatsbyAdvancedStarter\node_modules\gatsby-source-filesystem\index.js:8:46
    at Object.<anonymous> (D:\GatsbyAdvancedStarter\node_modules\gatsby-source-filesystem\index.j
s:34:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at D:\GatsbyAdvancedStarter\node_modules\gatsby\dist\redux\index.js:92:23
    at Promise._execute (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\debuggability.
js:300:9)
    at Promise._resolveFromExecutor (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\pr
omise.js:483:18)
    at new Promise (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\promise.js:79:10)
    at exports.loadNodeContent (D:\GatsbyAdvancedStarter\node_modules\gatsby\dist\redux\index.js:
86:12)
    at Object._callee$ (D:\GatsbyAdvancedStarter\node_modules\gatsby-transformer-remark\on-node-c
reate.js:48:20)
    at tryCatch (D:\GatsbyAdvancedStarter\node_modules\regenerator-runtime\runtime.js:65:40)

? source and transform nodesUnhandled rejection ReferenceError: regeneratorRuntime is not defined
    at D:\GatsbyAdvancedStarter\node_modules\gatsby-source-filesystem\index.js:8:46
    at Object.<anonymous> (D:\GatsbyAdvancedStarter\node_modules\gatsby-source-filesystem\index.j
s:34:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at D:\GatsbyAdvancedStarter\node_modules\gatsby\dist\redux\index.js:92:23
    at Promise._execute (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\debuggability.
js:300:9)
    at Promise._resolveFromExecutor (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\pr
omise.js:483:18)
    at new Promise (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\promise.js:79:10)
    at exports.loadNodeContent (D:\GatsbyAdvancedStarter\node_modules\gatsby\dist\redux\index.js:
86:12)
    at Object._callee$ (D:\GatsbyAdvancedStarter\node_modules\gatsby-transformer-remark\on-node-c
reate.js:48:20)
    at tryCatch (D:\GatsbyAdvancedStarter\node_modules\regenerator-runtime\runtime.js:65:40)

Unhandled rejection ReferenceError: regeneratorRuntime is not defined
    at D:\GatsbyAdvancedStarter\node_modules\gatsby-source-filesystem\index.js:8:46
    at Object.<anonymous> (D:\GatsbyAdvancedStarter\node_modules\gatsby-source-filesystem\index.j
s:34:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at D:\GatsbyAdvancedStarter\node_modules\gatsby\dist\redux\index.js:92:23
    at Promise._execute (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\debuggability.
js:300:9)
    at Promise._resolveFromExecutor (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\pr
omise.js:483:18)
    at new Promise (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\promise.js:79:10)
    at exports.loadNodeContent (D:\GatsbyAdvancedStarter\node_modules\gatsby\dist\redux\index.js:
86:12)
    at Object._callee$ (D:\GatsbyAdvancedStarter\node_modules\gatsby-transformer-remark\on-node-c
reate.js:48:20)
    at tryCatch (D:\GatsbyAdvancedStarter\node_modules\regenerator-runtime\runtime.js:65:40)

Unhandled rejection ReferenceError: regeneratorRuntime is not defined
    at D:\GatsbyAdvancedStarter\node_modules\gatsby-source-filesystem\index.js:8:46
    at Object.<anonymous> (D:\GatsbyAdvancedStarter\node_modules\gatsby-source-filesystem\index.j
s:34:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at D:\GatsbyAdvancedStarter\node_modules\gatsby\dist\redux\index.js:92:23
    at Promise._execute (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\debuggability.
js:300:9)
    at Promise._resolveFromExecutor (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\pr
omise.js:483:18)
    at new Promise (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\promise.js:79:10)
    at exports.loadNodeContent (D:\GatsbyAdvancedStarter\node_modules\gatsby\dist\redux\index.js:
86:12)
    at Object._callee$ (D:\GatsbyAdvancedStarter\node_modules\gatsby-transformer-remark\on-node-c
reate.js:48:20)
    at tryCatch (D:\GatsbyAdvancedStarter\node_modules\regenerator-runtime\runtime.js:65:40)

Unhandled rejection ReferenceError: regeneratorRuntime is not defined
    at D:\GatsbyAdvancedStarter\node_modules\gatsby-source-filesystem\index.js:8:46
    at Object.<anonymous> (D:\GatsbyAdvancedStarter\node_modules\gatsby-source-filesystem\index.j
s:34:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at D:\GatsbyAdvancedStarter\node_modules\gatsby\dist\redux\index.js:92:23
    at Promise._execute (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\debuggability.
js:300:9)
    at Promise._resolveFromExecutor (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\pr
omise.js:483:18)
    at new Promise (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\promise.js:79:10)
    at exports.loadNodeContent (D:\GatsbyAdvancedStarter\node_modules\gatsby\dist\redux\index.js:
86:12)
    at Object._callee$ (D:\GatsbyAdvancedStarter\node_modules\gatsby-transformer-remark\on-node-c
reate.js:48:20)
    at tryCatch (D:\GatsbyAdvancedStarter\node_modules\regenerator-runtime\runtime.js:65:40)

Unhandled rejection ReferenceError: regeneratorRuntime is not defined
    at D:\GatsbyAdvancedStarter\node_modules\gatsby-source-filesystem\index.js:8:46
    at Object.<anonymous> (D:\GatsbyAdvancedStarter\node_modules\gatsby-source-filesystem\index.j
s:34:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at D:\GatsbyAdvancedStarter\node_modules\gatsby\dist\redux\index.js:92:23
    at Promise._execute (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\debuggability.
js:300:9)
    at Promise._resolveFromExecutor (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\pr
omise.js:483:18)
    at new Promise (D:\GatsbyAdvancedStarter\node_modules\bluebird\js\release\promise.js:79:10)
    at exports.loadNodeContent (D:\GatsbyAdvancedStarter\node_modules\gatsby\dist\redux\index.js:
86:12)
    at Object._callee$ (D:\GatsbyAdvancedStarter\node_modules\gatsby-transformer-remark\on-node-c
reate.js:48:20)
    at tryCatch (D:\GatsbyAdvancedStarter\node_modules\regenerator-runtime\runtime.js:65:40)

error Plugin gatsby-transformer-remark returned an error

  ReferenceError: regeneratorRuntime is not defined

  - index.js:8
    [GatsbyAdvancedStarter]/[gatsby-source-filesystem]/index.js:8:46

  - index.js:34 Object.<anonymous>
    [GatsbyAdvancedStarter]/[gatsby-source-filesystem]/index.js:34:2

  - module.js:20 require
    internal/module.js:20:19

  - index.js:92
    [GatsbyAdvancedStarter]/[gatsby]/dist/redux/index.js:92:23

  - debuggability.js:300 Promise._execute
    [GatsbyAdvancedStarter]/[bluebird]/js/release/debuggability.js:300:9

  - promise.js:483 Promise._resolveFromExecutor
    [GatsbyAdvancedStarter]/[bluebird]/js/release/promise.js:483:18

  - promise.js:79 new Promise
    [GatsbyAdvancedStarter]/[bluebird]/js/release/promise.js:79:10

  - index.js:86 exports.loadNodeContent
    [GatsbyAdvancedStarter]/[gatsby]/dist/redux/index.js:86:12

  - on-node-create.js:48 Object._callee$
    [GatsbyAdvancedStarter]/[gatsby-transformer-remark]/on-node-create.js:48:20

error Plugin gatsby-transformer-remark returned an error

  ReferenceError: regeneratorRuntime is not defined

  - index.js:8
    [GatsbyAdvancedStarter]/[gatsby-source-filesystem]/index.js:8:46

  - index.js:34 Object.<anonymous>
    [GatsbyAdvancedStarter]/[gatsby-source-filesystem]/index.js:34:2

  - module.js:20 require
    internal/module.js:20:19

  - index.js:92
    [GatsbyAdvancedStarter]/[gatsby]/dist/redux/index.js:92:23

  - debuggability.js:300 Promise._execute
    [GatsbyAdvancedStarter]/[bluebird]/js/release/debuggability.js:300:9

  - promise.js:483 Promise._resolveFromExecutor
    [GatsbyAdvancedStarter]/[bluebird]/js/release/promise.js:483:18

  - promise.js:79 new Promise
    [GatsbyAdvancedStarter]/[bluebird]/js/release/promise.js:79:10

  - index.js:86 exports.loadNodeContent
    [GatsbyAdvancedStarter]/[gatsby]/dist/redux/index.js:86:12

  - on-node-create.js:48 Object._callee$
    [GatsbyAdvancedStarter]/[gatsby-transformer-remark]/on-node-create.js:48:20

error Plugin gatsby-transformer-remark returned an error

  ReferenceError: regeneratorRuntime is not defined

  - index.js:8
    [GatsbyAdvancedStarter]/[gatsby-source-filesystem]/index.js:8:46

  - index.js:34 Object.<anonymous>
    [GatsbyAdvancedStarter]/[gatsby-source-filesystem]/index.js:34:2

  - module.js:20 require
    internal/module.js:20:19

  - index.js:92
    [GatsbyAdvancedStarter]/[gatsby]/dist/redux/index.js:92:23

  - debuggability.js:300 Promise._execute
    [GatsbyAdvancedStarter]/[bluebird]/js/release/debuggability.js:300:9

  - promise.js:483 Promise._resolveFromExecutor
    [GatsbyAdvancedStarter]/[bluebird]/js/release/promise.js:483:18

  - promise.js:79 new Promise
    [GatsbyAdvancedStarter]/[bluebird]/js/release/promise.js:79:10

  - index.js:86 exports.loadNodeContent
    [GatsbyAdvancedStarter]/[gatsby]/dist/redux/index.js:86:12

  - on-node-create.js:48 Object._callee$
    [GatsbyAdvancedStarter]/[gatsby-transformer-remark]/on-node-create.js:48:20

error Plugin gatsby-transformer-remark returned an error

**Comment by KyleAMathews** [comment]
Which version of node are you on? Yesterday someone had a problem like this until they upgraded to node 6. Also, you could try using Yarn.

**Comment by ddiviacchi** [comment]
Hello, I am on v6.9.4.  I can try with yarn later on and let you know. thanks

________________________________

**Comment by KyleAMathews** [comment]
Closing this as it seems to be related to broken installs not anything Gatsby is doing.
