### ISSUE TITLE
[gatsby-remark-images] bug with [ ] in path

### ISSUE THREAD

**Issue by isoftninja** [gatsbyjs/gatsby#18222]
If in path contains `[ ]` an error occurs -

`
./posts/000.post/ //Ok
./posts/[000]post/ // Error 
`
>/home/user/gatsby-remark-images-bug-with-path/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
throw ex;
^
TypeError: Cannot destructure property `job` of 'undefined' or 'null'.
  at runJobs (/home/user/gatsby-remark-images-bug-with-path/node_modules/gatsby-plugin-sharp/scheduler.js:99:9)
at /home/user/gatsby-remark-images-bug-with-path/node_modules/gatsby-plugin-sharp/scheduler.js:87:7
at /home/user/gatsby-remark-images-bug-with-path/node_modules/gatsby-plugin-sharp/scheduler.js:24:3
at /home/user/gatsby-remark-images-bug-with-path/node_modules/gatsby-plugin-sharp/node_modules/async/queue.js:10:5
at Object.process (/home/user/gatsby-remark-images-bug-with-path/node_modules/gatsby-plugin-sharp/node_modules/async/internal/queue.js:175:17)
at /home/user/gatsby-remark-images-bug-with-path/node_modules/gatsby-plugin-sharp/node_modules/async/internal/queue.js:82:19
at Immediate.<anonymous> (/home/user/gatsby-remark-images-bug-with-path/node_modules/gatsby-plugin-sharp/node_modules/async/internal/setImmediate.js:27:16)

[demo repo](https://github.com/isoftninja/gatsby-remark-images-bug-with-path)

**Comment by isoftninja** [comment]
in node_modules/gatsby-plugin-sharp/scheduler.js
```
_.set(toProcess, jobPath, {
  job: job,
  deferred
});
```
from `lodash` docs - 
```
var object = { 'a': [{ 'b': { 'c': 3 } }] };
 
_.set(object, 'a[0].b.c', 4);
console.log(object.a[0].b.c);
```
`'a[0].b.c',` - square brackets in path match pattern for lodash.
