### ISSUE TITLE
Reserved keyword(s) on data json using gatsby-transformer-json

### ISSUE THREAD

**Issue by acewf** [gatsbyjs/gatsby#18260]
## Reserved keyword "filter"
I am getting the following error, while using gatbsy@2.15.0 and gatsby-transformer-json@2.2.2 or above by having a json file with a key "filter", the development or the build process doesn't work.

not sure @freiksenet as more info why this is happening,
also not sure if this infer just affects only data from json files, or other potential data sources.

using gatbsy@2.14.7 and gatsby-transformer-json@2.2.2 the build work without problems

ex:
```
{
  "filter": {
    "showAll": "Show all",
    "images": "Images",
    "videos": "Videos"
  }
}
```

```
// node@10.12.0
success Add inferred types - 0.137 s

 ERROR

UNHANDLED REJECTION Cannot get field 'id' from type 'DataJsonFilter'. Field does not exist.



  Error: Cannot get field 'id' from type 'DataJsonFilter'. Field does not exist.

  - ObjectTypeComposer.js:227 ObjectTypeComposer.getField
    [gatsby-test-json]/[graphql-compose]/lib/ObjectTypeComposer.js:227:13

  - ObjectTypeComposer.js:839 ObjectTypeComposer.getFieldExtensions
    [gatsby-test-json]/[graphql-compose]/lib/ObjectTypeComposer.js:839:24

  - ObjectTypeComposer.js:863 ObjectTypeComposer.getFieldExtension
    [gatsby-test-json]/[graphql-compose]/lib/ObjectTypeComposer.js:863:29

  - sort.js:80 Object.keys.forEach.fieldName
    [gatsby-test-json]/[gatsby]/dist/schema/types/sort.js:80:35

  - Array.forEach

  - sort.js:78 convert
    [gatsby-test-json]/[gatsby]/dist/schema/types/sort.js:78:23

  - sort.js:103 Object.keys.forEach.fieldName
    [gatsby-test-json]/[gatsby]/dist/schema/types/sort.js:103:35

  - Array.forEach

  - sort.js:78 convert
    [gatsby-test-json]/[gatsby]/dist/schema/types/sort.js:78:23

  - sort.js:36 getFieldsEnum
    [gatsby-test-json]/[gatsby]/dist/schema/types/sort.js:36:18

  - pagination.js:86 getPagination
    [gatsby-test-json]/[gatsby]/dist/schema/types/pagination.js:86:24

  - schema.js:1012 addTypeToRootQuery
    [gatsby-test-json]/[gatsby]/dist/schema/schema.js:1012:24

  - schema.js:242 processTypeComposer
    [gatsby-test-json]/[gatsby]/dist/schema/schema.js:242:13


⠙ building schema
```

### Steps to reproduce
To help out understanding the bug, i created a repo.  
You can find there a gatsby starter, adding on top `gatsby-transformer-json` and a configuration for adding data files with `gatsby-source-filesystem` 

https://github.com/acewf/gatsby-json-transform-issues/commits/master

### Expected result

Schema should be generated and should be able to have development environment running or build successfully the static files 

### Actual result

**gatsby develop** or **gatsby build** process ends

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/pedrom/.nvm/versions/node/v10.12.0/bin/node',
1 verbose cli   '/Users/pedrom/.nvm/versions/node/v10.12.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v10.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle gatsby-starter-default@0.1.0~prebuild: gatsby-starter-default@0.1.0
6 info lifecycle gatsby-starter-default@0.1.0~build: gatsby-starter-default@0.1.0
7 verbose lifecycle gatsby-starter-default@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle gatsby-starter-default@0.1.0~build: PATH: /Users/pedrom/.nvm/versions/node/v10.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/pedrom/works/gatsby-test-json/node_modules/.bin:/Users/pedrom/.nvm/versions/node/v10.12.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle gatsby-starter-default@0.1.0~build: CWD: /Users/pedrom/works/gatsby-test-json
10 silly lifecycle gatsby-starter-default@0.1.0~build: Args: [ '-c', 'gatsby build' ]
11 silly lifecycle gatsby-starter-default@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle gatsby-starter-default@0.1.0~build: Failed to exec build script
13 verbose stack Error: gatsby-starter-default@0.1.0 build: `gatsby build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/pedrom/.nvm/versions/node/v10.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/pedrom/.nvm/versions/node/v10.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid gatsby-starter-default@0.1.0
15 verbose cwd /Users/pedrom/works/gatsby-test-json
16 verbose Darwin 17.7.0
17 verbose argv "/Users/pedrom/.nvm/versions/node/v10.12.0/bin/node" "/Users/pedrom/.nvm/versions/node/v10.12.0/bin/npm" "run" "build"
18 verbose node v10.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error gatsby-starter-default@0.1.0 build: `gatsby build`
22 error Exit status 1
23 error Failed at the gatsby-starter-default@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.12.0 - ~/.nvm/versions/node/v10.12.0/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v10.12.0/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 68.0.2
    Safari: 13.0.1
  npmPackages:
    gatsby: 2.15.0 => 2.15.0
    gatsby-image: ^2.2.24 => 2.2.24
    gatsby-plugin-manifest: ^2.2.20 => 2.2.20
    gatsby-plugin-offline: ^3.0.11 => 3.0.11
    gatsby-plugin-react-helmet: ^3.1.10 => 3.1.10
    gatsby-plugin-sharp: ^2.2.28 => 2.2.28
    gatsby-source-filesystem: ^2.1.29 => 2.1.29
    gatsby-transformer-json: 2.2.12 => 2.2.12
    gatsby-transformer-sharp: ^2.2.20 => 2.2.20

**Comment by pilniczek** [comment]
The same issue for me.
`"gatsby-transformer-json": "^2.2.25",`
I did not found any infomation in documentation. `https://www.gatsbyjs.org/packages/gatsby-transformer-json/`
