### ISSUE TITLE
[gatsby-plugin-mdx] TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by arnaud-deprez** [gatsbyjs/gatsby#18474]
Hi,

Thank you a lot for this great project, keep up the good work !
I've met a bug and didn't find any issue related to it yet (I saw some similar issue with `gatsby-source-wordpress` but it does not look to be linked to this)

## Description

GIVEN: 
- a gatsby project using `typescript` and `gatsby-plugin-mdx`
- a `MDXRenderer` component used with some props like
```jsx
<MDXRenderer author={data.site.siteMetadata.author}>{data.mdx.body}</MDXRenderer>
```
- and the props is used in the mdx file like: 
```mdx
<PhotoCard name={props.author.name} jobTitle={props.author.jobTitle} className="photo-card mb-5 d-lg-none"/>
```

WHEN: 
- performing `gatsby build`

THEN:
- The build failed with `Cannot read property 'name' of undefined`

However, with `gatsby develop`, everything is fine.

### Steps to reproduce

You can reuse directly my website here on `develop` branch: https://github.com/arnaud-deprez/arnaud-deprez.github.io/tree/issue/gatsby-18474.
Just clone it and run `npm run build`, it fails.
While if you do `npm start`, you can browse the website.

The key code are here: 
https://github.com/arnaud-deprez/arnaud-deprez.github.io/blob/issue/gatsby-18474/src/pages/index.tsx#L66 and https://raw.githubusercontent.com/arnaud-deprez/arnaud-deprez.github.io/issue/gatsby-18474/content/index.mdx (where some {props.*} are used).

### Expected result

If it works with `gatsby develop`, it should work with `gatsby build` as well.

### Actual result

```
 ERROR 

gatsby-plugin-mdx
TypeError: Cannot read property 'name' of undefined
    at MDXContent (eval at _construct (evalmachine.<anonymous>:1922:915), <anonymous>:36:24)
    at c (evalmachine.<anonymous>:13796:500)
    at Ua (evalmachine.<anonymous>:13799:16)
    at a.render (evalmachine.<anonymous>:13805:48)
    at a.read (evalmachine.<anonymous>:13804:161)
    at renderToStaticMarkup (evalmachine.<anonymous>:13815:181)
    at ./node_modules/gatsby-plugin-mdx/utils/wrap-root-render-html-entry.js.__webpack_exports__.default (evalmachine.<anonymous>:1949:512)
    at /Users/arnaud/Development/my/static-sites/arnaud-deprez.github.com/node_modules/gatsby-plugin-mdx/utils/render-html.js:157:23
    at Array.map (<anonymous>)
    at /Users/arnaud/Development/my/static-sites/arnaud-deprez.github.com/node_modules/gatsby-plugin-mdx/utils/render-html.js:155:22


 ERROR 

UNHANDLED REJECTION TypeError: Cannot read property 'name' of undefined
    at MDXContent (eval at <anonymous> (evalmachine.<anonymous>:1925:108), <anonymous>:36:24)
    at c (evalmachine.<anonymous>:13796:500)
    at Ua (evalmachine.<anonymous>:13799:16)
    at a.render (evalmachine.<anonymous>:13805:48)
    at a.read (evalmachine.<anonymous>:13804:161)
    at renderToStaticMarkup (evalmachine.<anonymous>:13815:181)
    at ./node_modules/gatsby-plugin-mdx/utils/wrap-root-render-html-entry.js.__webpack_exports__.default (evalmachine.<anonymous>:1949:512)
    at /Users/arnaud/Development/my/static-sites/arnaud-deprez.github.com/node_modules/gatsby-plugin-mdx/utils/render-html.js:157:23
    at Array.map (<anonymous>)
    at /Users/arnaud/Development/my/static-sites/arnaud-deprez.github.com/node_modules/gatsby-plugin-mdx/utils/render-html.js:155:22



  Error: TypeError: Cannot read property 'name' of undefined
```

### Environment

```
gatsby info --clipboard

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.9.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Firefox: 60.8.0
    Safari: 13.0.2
  npmPackages:
    gatsby: 2.15.16 => 2.15.16
    gatsby-plugin-catch-links: 2.1.9 => 2.1.9
    gatsby-plugin-feed: 2.3.12 => 2.3.12
    gatsby-plugin-lunr: 1.5.2 => 1.5.2
    gatsby-plugin-manifest: 2.2.16 => 2.2.16
    gatsby-plugin-mdx: 1.0.42 => 1.0.42
    gatsby-plugin-netlify: 2.1.13 => 2.1.13
    gatsby-plugin-nprogress: 2.1.6 => 2.1.6
    gatsby-plugin-offline: 3.0.7 => 3.0.7
    gatsby-plugin-react-helmet: 3.1.7 => 3.1.7
    gatsby-plugin-sass: 2.1.14 => 2.1.14
    gatsby-plugin-sharp: 2.2.22 => 2.2.22
    gatsby-plugin-sitemap: 2.2.12 => 2.2.12
    gatsby-plugin-typescript: 2.1.8 => 2.1.8
    gatsby-remark-autolink-headers: 2.1.13 => 2.1.13
    gatsby-remark-copy-linked-files: 2.1.19 => 2.1.19
    gatsby-remark-emoji: 0.0.3 => 0.0.3
    gatsby-remark-emojis: 0.3.2 => 0.3.2
    gatsby-remark-images: 3.1.22 => 3.1.22
    gatsby-remark-prismjs: 3.3.13 => 3.3.13
    gatsby-remark-smartypants: 2.1.8 => 2.1.8
    gatsby-source-filesystem: 2.1.22 => 2.1.22
    gatsby-transformer-remark: 2.6.22 => 2.6.22
    gatsby-transformer-sharp: 2.2.14 => 2.2.14
  npmGlobalPackages:
    gatsby-cli: 2.7.47
```

**Comment by pieh** [comment]
This is related to `gatsby-plugin-feed` and either `html` or `excerpt` (or both) fields in query ( https://github.com/arnaud-deprez/arnaud-deprez.github.io/blob/issue/gatsby-18474/gatsby-config.js#L157-L158 ). When this is being executed it's outside of `MDXRenderer` so it doesn't have access to props that you define in your index page

**Comment by pieh** [comment]
Alternatively you could apply:
```
filter: { 
                    frontmatter: { 
                      draft: { 
                        ne: true 
                      }, 
                      title: {
                        ne: "About"
                      }
                    }
                  }
```
filter in feed plugin configuration to ignore about page, which will always fail to generate excerpt/html because of its reliance on additional context/props.

**Comment by arnaud-deprez** [comment]
Hi @pieh,

Thank you very much !

I'm wondering how did you find the issue was actually in another plugin 😮cause the error is definitely not clear and the stack trace does not help
