### ISSUE TITLE
ContentfulAsset's localFile field missing in GraphQL schema using gatsby-source-contentful 

### ISSUE THREAD

**Issue by usotnyk** [gatsbyjs/gatsby#18640]
## Description

I am using gatsby-source-contentful plugin to get data using GraphQL from Contentful into my gatsby site.

Previously I was able to gain access to various fields using the `localFile` field (ex: `publicUrl`, `chilImageSharp`, etc.). However, now whenever I start up my project on my local machine the query fails. These are the details of the error message from GraphiQl:

{
  "errors": [
    {
      "message": "Cannot query field \"localFile\" on type \"ContentfulAsset\".",
      "locations": [
        {
          "line": 29,
          "column": 17
        }
      ],
      "stack": [
        "GraphQLError: Cannot query field \"localFile\" on type \"ContentfulAsset\".",
        "    at Object.Field (/Users/julia-sotnyk/Documents/Inno-projects/VitalWebsite/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:53:31)",
        "    at Object.enter (/Users/julia-sotnyk/Documents/Inno-projects/VitalWebsite/node_modules/graphql/language/visitor.js:324:29)",
        "    at Object.enter (/Users/julia-sotnyk/Documents/Inno-projects/VitalWebsite/node_modules/graphql/language/visitor.js:375:25)",
        "    at visit (/Users/julia-sotnyk/Documents/Inno-projects/VitalWebsite/node_modules/graphql/language/visitor.js:242:26)",
        "    at validate (/Users/julia-sotnyk/Documents/Inno-projects/VitalWebsite/node_modules/graphql/validation/validate.js:73:24)",
        "    at getGraphQLParams.then.then.optionsData (/Users/julia-sotnyk/Documents/Inno-projects/VitalWebsite/node_modules/express-graphql/index.js:121:32)",
        "    at <anonymous>",
        "    at process._tickCallback (internal/process/next_tick.js:189:7)"
      ]
    }
  ]
}

Here is the simplified GraphiQL query (I'm only including the relevant piece):

query allContentfulPage {
  allContentfulPage {
        edges {
          node {
            slug
            title
            sections {
              id
              title
              backgroundImage {
                localFile {
                  publicURL
                  childImageSharp {
                    fluid(quality: 90, maxWidth: 4160) {
                      src
                      srcSet
                      aspectRatio
                      sizes
                      base64
                      srcWebp
                      srcSetWebp
                    }
                  }
                }
              }
            }
          }
        }
      }
    }

### Expected result

App loads with data returned from Contenful using gatsby-source-contentful.

### Actual result

GraphQL query fails, app does not load.

### Environment

System:
    OS: macOS 10.14.6
    CPU: x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0.1
    Safari: 13.0.2
  npmPackages:
    gatsby: ^2.10.4 => 2.13.83 
    gatsby-background-image: ^0.8.5 => 0.8.5 
    gatsby-image: ^2.2.3 => 2.2.14 
    gatsby-plugin-manifest: ^2.2.0 => 2.2.9 
    gatsby-plugin-prefetch-google-fonts: ^1.4.2 => 1.4.3 
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.5 
    gatsby-plugin-sass: ^2.1.0 => 2.1.12 
    gatsby-plugin-sharp: ^2.2.1 => 2.2.18 
    gatsby-source-contentful: ^2.1.8 => 2.1.29 
    gatsby-source-filesystem: ^2.1.0 => 2.1.18 
    gatsby-transformer-remark: ^2.5.0 => 2.6.19 
    gatsby-transformer-sharp: ^2.2.0 => 2.2.12 
  npmGlobalPackages:
    gatsby-cli: 2.4.3

The last I started up the project and the query with `localFile` field was working was 14 days ago. Today is the first time I noticed it stopped working.

Thank you for any leads and ideas on how to get this fixed!

**Comment by usotnyk** [comment]
This issue seems to be revolved with the most recent update to the plugin on Oct. 14th.
