### ISSUE TITLE
Unexpected token import from 'fs-extra'

### ISSUE THREAD

**Issue by karloespiritu** [gatsbyjs/gatsby#189]
I'm using Node v5.6 and Gatsby v0.8.4, and when I run the command - `gatsby new gatsby-site`, I get the following error:

import fs from 'fs-extra'
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/karlo/.nvm/versions/node/v5.6.0/lib/node_modules/gatsby/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/karlo/.nvm/versions/node/v5.6.0/lib/node_modules/gatsby/bin/new.js:16:17)
    at Module._compile (module.js:413:34)

**Comment by KyleAMathews** [comment]
Can you try upgrading to the latest gatsby and try again?

**Comment by karloespiritu** [comment]
Thanks, it works now. I upgraded from v0.8.4 to v0.8.9.
