### ISSUE TITLE
events.js:187 throw er; // Unhandled 'error' event ^

### ISSUE THREAD

**Issue by ikrishnaveni** [gatsbyjs/gatsby#19178]
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [ '/c', 'start', '""', '/b', 'http://localhost:4200/' ]
}.

**Comment by LekoArts** [comment]
Thank you for opening this!

Please follow our issue template as your current issue isn't helpful for us and we won't be able to help you.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by SurajTiwari007** [comment]
solution please i also getting same error

**Comment by belotesagar** [comment]
I am getting below error when I run: ng serve -o
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [ '/c', 'start', '""', '/b', 'http://localhost:4200/' ]
}

**Comment by krishnavenib5** [comment]
Please look over the path to system variables for npm node_modules
or delete the node_modules in the project again you can run the command : `npm install`
                                                                                                                            `npm start`

**Comment by Harshkant87** [comment]
Downgrading the react-script version from 3.0.1 to 2.1.8 worked for me. npm install react-scripts@2.1.8 npm install npm start
