### ISSUE TITLE
[gatsby-transformer-javascript-frontmatter] - typescript interfaces break babel

### ISSUE THREAD

**Issue by moshie** [gatsbyjs/gatsby#19253]
## Description

Cannot get access to fields we export from typescript files. 
Looks like the plugin runs through babel/traverse which fails when trying to read typescript more specifically interfaces.

### Steps to reproduce

1 .Create a fresh gatsby site and pull in this plugin `gatsby-transformer-javascript-frontmatter`
2. create a source in `gatsby-config.js`
3. create a typescript file (.tsx) in the source folder and add an interface to it.
4. export out frontmatter
5. build and navigate to `/___graphql`
6. query for all frontmatter and notice the frontmatter is not there

I did some digging myself and found that it produces this error:

```
{ SyntaxError: Unexpected token (31:6)
    at Object.raise (/Users/david.hewitt/code/shopfront/node_modules/@babel/parser/lib/index.js:6420:17)
    at Object.unexpected (/Users/david.hewitt/code/shopfront/node_modules/@babel/parser/lib/index.js:7773:16)
    at Object.flowObjectTypeSemicolon (/Users/david.hewitt/code/shopfront/node_modules/@babel/parser/lib/index.js:1583:12)
    at Object.flowParseObjectType (/Users/david.hewitt/code/shopfront/node_modules/@babel/parser/lib/index.js:1477:12)
    at Object.flowParsePrimaryType (/Users/david.hewitt/code/shopfront/node_modules/@babel/parser/lib/index.js:1735:21)
    at Object.flowParsePostfixType (/Users/david.hewitt/code/shopfront/node_modules/@babel/parser/lib/index.js:1877:21)
    at Object.flowParsePrefixType (/Users/david.hewitt/code/shopfront/node_modules/@babel/parser/lib/index.js:1897:19)
    at Object.flowParseAnonFunctionWithoutParens (/Users/david.hewitt/code/shopfront/node_modules/@babel/parser/lib/index.js:1902:24)
    at Object.flowParseIntersectionType (/Users/david.hewitt/code/shopfront/node_modules/@babel/parser/lib/index.js:1919:23)
    at Object.flowParseUnionType (/Users/david.hewitt/code/shopfront/node_modules/@babel/parser/lib/index.js:1932:23)
    at Object.flowParseType (/Users/david.hewitt/code/shopfront/node_modules/@babel/parser/lib/index.js:1945:23)
    at Object.flowParseTypeInitialiser (/Users/david.hewitt/code/shopfront/node_modules/@babel/parser/lib/index.js:813:23)
    at Object.flowParseObjectTypeProperty (/Users/david.hewitt/code/shopfront/node_modules/@babel/parser/lib/index.js:1554:27)
    at Object.flowParseObjectType (/Users/david.hewitt/code/shopfront/node_modules/@babel/parser/lib/index.js:1468:36)
    at Object.flowParsePrimaryType (/Users/david.hewitt/code/shopfront/node_modules/@babel/parser/lib/index.js:1735:21)
    at Object.flowParsePostfixType (/Users/david.hewitt/code/shopfront/node_modules/@babel/parser/lib/index.js:1877:21) pos: 1597, loc: Position { line: 31, column: 6 } }
```

### Expected result

You should be able to see the frontmatter from the typescript page.

### Actual result

The plugin errored silently and did not create the node for graphql 

### Environment

```

  System:
    OS: macOS 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.11.3 - ~/.npm-global/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.87
    Firefox: 70.0
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.1.20 => 2.17.7 
    gatsby-cli: ^2.4.5 => 2.8.8 
    gatsby-image: ^2.0.26 => 2.2.30 
    gatsby-link: ^2.0.12 => 2.2.22 
    gatsby-plugin-google-tagmanager: ^2.0.6 => 2.1.15 
    gatsby-plugin-mdx: ^1.0.14 => 1.0.55 
    gatsby-plugin-react-helmet: ^3.1.10 => 3.1.13 
    gatsby-plugin-react-helmet-canonical-urls: ^1.2.0 => 1.3.0 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-remove-trailing-slashes: ^2.0.9 => 2.1.12 
    gatsby-plugin-robots-txt: ^1.3.0 => 1.5.0 
    gatsby-plugin-sitemap: ^2.0.1 => 2.2.19 
    gatsby-plugin-styled-components: ^3.0.0 => 3.1.11 
    gatsby-plugin-typescript: ^2.0.3 => 2.1.15 
    gatsby-source-apiserver: ^2.0.0 => 2.1.3 
    gatsby-source-filesystem: ^2.0.1 => 2.1.35 
    gatsby-transformer-csv: ^2.0.4 => 2.1.15 
    gatsby-transformer-javascript-frontmatter: ^2.0.0 => 2.1.16 
    gatsby-transformer-json: ^2.1.2 => 2.2.16 
```

**Comment by pieh** [comment]
This will need some updates to https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-javascript-frontmatter/src/gatsby-node.js

We are using `@babel/parse` here and would need to swap `flow` plugin with `typescript` for `.ts` and `.tsx` files. We can use `node.extension` to figure out if we should use `flow` or `typescript`. I'm not sure if that's all we need - but worth trying this (you can do dirty check in `node_modules/gatsby-transformer-javascript-frontmatter/gatsby-node.js`) for something like this:

```diff
  const options = {
    sourceType: `module`,
    allowImportExportEverywhere: true,
    plugins: [
      `jsx`,
      `doExpressions`,
      `objectRestSpread`,
      [
        `decorators`,
        {
          decoratorsBeforeExport: true,
        },
      ],
      `classProperties`,
      `exportExtensions`,
      `asyncGenerators`,
      `functionBind`,
      `functionSent`,
      `dynamicImport`,
-     `flow`,
+     _.includes([`ts`, `tsx`], node.extension) ? `typescript` : `flow`,
    ],
  }
```

If this works, we would be interesting in PR for that
