### ISSUE TITLE
Getting error with babel inside Gatsby

### ISSUE THREAD

**Issue by nmn** [gatsbyjs/gatsby#195]
Everytime I try to do `gatsby develop` I get this error.

I've tried the two latest versions of gatsby with the same result.
I tried use the master from github, ran the build scripts, set published to true and then got the same result.

I guess this is connected to the other issue to upgrade to babel 6. But am I just missing something?

```sh
/usr/local/lib/node_modules/gatsby/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126
      if (!option) this.log.error("Unknown option: " + alias + "." + key, ReferenceError);
                           ^

TypeError: Cannot read property 'error' of undefined
  at OptionManager.mergeOptions (/usr/local/lib/node_modules/gatsby/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:28)
  at OptionManager.addConfig (/usr/local/lib/node_modules/gatsby/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
  at OptionManager.findConfigs (/usr/local/lib/node_modules/gatsby/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
  at OptionManager.init (/usr/local/lib/node_modules/gatsby/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
  at compile (/usr/local/lib/node_modules/gatsby/node_modules/babel-core/lib/api/register/node.js:117:22)
  at normalLoader (/usr/local/lib/node_modules/gatsby/node_modules/babel-core/lib/api/register/node.js:199:14)
  at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/gatsby/node_modules/babel-core/lib/api/register/node.js:216:7)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at module.exports (/usr/local/lib/node_modules/gatsby/dist/utils/glob-pages.js:42:13)
  at module.exports (/usr/local/lib/node_modules/gatsby/dist/utils/develop.js:85:37)
  at Object.<anonymous> (/usr/local/lib/node_modules/gatsby/bin/develop.js:36:1)
  at Module._compile (module.js:435:26)
  at Module._extensions..js (module.js:442:10)
  at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/gatsby/node_modules/babel-core/lib/api/register/node.js:214:7)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/gatsby/bin/gatsby-develop.js:4:1)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:136:18)
  at node.js:963:3
```

**Comment by KyleAMathews** [comment]
Are you trying to use Babel 6 with your site?

**Comment by nmn** [comment]
No, I just used Gatsby to generate and the gatsby develop

**Comment by KyleAMathews** [comment]
So you ran:

```
gatsby new test-gatsby-stie
gatsby develop
```

And then see this error?

**Comment by tleunen** [comment]
This is the error I also get when I try to generate and test a gatsby site inside a project using Babel 6.

**Comment by KyleAMathews** [comment]
It's beyond me why but that's how Babel works. As I understand it, Babel looks to parent directories (perhaps until it finds a `.git` directory?) for `.babelrc`. In any case, I've actually been working today on updating Gatsby to Babel 6 so this should be fixed soon.

Just to double-check we understand the problem correctly — if you copy the Gatsby site to its own directory does it work then?

**Comment by KyleAMathews** [comment]
And here's the PR actually :) https://github.com/gatsbyjs/gatsby/pull/197/files

Want to also make Gatsby default to using the locally installed version of Gatsby so not going to merge and release this tonight but if you want to clone the PR and see if that gets you working, that'd be great.

**Comment by tleunen** [comment]
Yes @KyleAMathews, if it's in a complete different directory (or if the babelrc of the parent directory is removed), it works as expected.

I'll test it :)
