### ISSUE TITLE
Error: TypeError: Cannot read property 'allFile' of undefined

### ISSUE THREAD

**Issue by jordwalke** [gatsbyjs/gatsby#1956]
I'm building our [Reason docs](https://github.com/reasonml/reasonml.github.io), and saw this error when running:` ./node_modules/.bin/gatsby build --prefix-paths`.

Is this coming from Gatsby scaffolding, or something in our docs components? It's probably something we're doing wrong, but the stack traces below are pretty unusable. Is there a better way to debug this? Thanks for helping a noob!

```
jwalkes-MacBook:reasonml.github.io jwalke$ ./node_modules/.bin/gatsby build --prefix-paths
success open and validate gatsby-config.js — 0.005 s
success copy gatsby files — 0.027 s
success source and transform nodes — 0.314 s
success building schema — 0.331 s
success createPages — 0.576 s
success createPagesStatefully — 0.068 s
success extract queries from components — 0.284 s
success run graphql queries — 0.105 s
success write out page data — 0.024 s
success update schema — 0.435 s

bootstrap finished, time since started: 3.493 s

Generating CSS
Compiling production bundle.js
Generating static HTML for pages

Error: TypeError: Cannot read property 'allFile' of undefined
    at Guide.render (render-page.js:56466:34)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (render-page.js:15605:31)
    at ReactCompositeComponentWrapper._renderValidatedComponent (render-page.js:15628:33)
    at ReactCompositeComponentWrapper.performInitialMount (render-page.js:15168:31)
    at ReactCompositeComponentWrapper.mountComponent (render-page.js:15064:22)
    at Object.mountComponent (render-page.js:7976:36)
    at ReactCompositeComponentWrapper.performInitialMount (render-page.js:15177:35)
    at ReactCompositeComponentWrapper.mountComponent (render-page.js:15064:22)
    at Object.mountComponent (render-page.js:7976:36)
    at ReactCompositeComponentWrapper.performInitialMount (render-page.js:15177:35),TypeError: Cannot read property 'allFile' of undefined
    at Guide.render (render-page.js:56466:34)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (render-page.js:15605:31)
    at ReactCompositeComponentWrapper._renderValidatedComponent (render-page.js:15628:33)
    at ReactCompositeComponentWrapper.performInitialMount (render-page.js:15168:31)
    at ReactCompositeComponentWrapper.mountComponent (render-page.js:15064:22)
    at Object.mountComponent (render-page.js:7976:36)
    at ReactCompositeComponentWrapper.performInitialMount (render-page.js:15177:35)
    at ReactCompositeComponentWrapper.mountComponent (render-page.js:15064:22)
    at Object.mountComponent (render-page.js:7976:36)
    at ReactCompositeComponentWrapper.performInitialMount (render-page.js:15177:35)

Generating static HTML for pages failed
See our docs page on debugging HTML builds for help https://goo.gl/yL9lND
```

**Comment by markmichon** [comment]
I was able to pull down the  reason docs source branch, yarn install, and build via that command you listed without problem. Maybe a caching issue with yarn? (I've had a few problems related to that lately).

**Comment by KyleAMathews** [comment]
It looks like the error is from https://github.com/reasonml/reasonml.github.io/blob/dd009e3eca8a9a05a6b901d5b739571d4fe8d3ca/src/templates/Guide.js#L27

If you run `gatsby develop` you can see the errors when you try to visit the example or companies page. The only thing I can see odd about those pages is they both have the duplicate markdown/js pages. I'm not entirely sure what you're doing there… anyways, ran out of time to debug more—hope that helps!

**Comment by KyleAMathews** [comment]
Also @jquense is working on better HTML build errors!

![](https://cdn.discordapp.com/attachments/103314369600843776/352212566950543361/unknown.png)

**Comment by jordwalke** [comment]
Do you know why the stack trace says the error occurs on line `(render-page.js:56466:34)`?

**Comment by KyleAMathews** [comment]
It's because we render HTML with this webpack plugin https://github.com/markdalgleish/static-site-generator-webpack-plugin

It first generates a big JS bundle for the site (the `render-page.js`) and then renders pages using that.

You can find the `render-page.js` file in the `public` folder.

But this will soon be a bad memory :-) https://github.com/gatsbyjs/gatsby/pull/1967

**Comment by KyleAMathews** [comment]
Closing out older issues — thanks for everyone that participated on this thread — please open more issues if you need help!
