### ISSUE TITLE
Gatsby build and i18next-xhr-backend crashes

### ISSUE THREAD

**Issue by alvgaona** [gatsbyjs/gatsby#19900]
## Description

Well, I've started a Gatsby App and wanted to add internationalisation to it. Decided to use `i18next` and added my translation namespaces in my locales folder and set up the i18next instance by configuring it. Started by translating only one component and see how it worked.

After all has been set up, I needed my locales directory to be baked into `public/` and for this, I run `gatsby build`. However, this breaks...

The workaround was to remove i18n related functions and objects, running `gatsby build` and then running adding all of that back so the build does not fail. It works with `gastby develop`.

### Steps to reproduce

**Prerequisites**

Install dependencies: 

```
npm install --save i18next i18next-xhr-backend i18next-browser-languagedetector react-i18next
```

**Steps**

1. Configure i18n instance under `src/components/`.

```jsx
import i18n from 'i18next';
import Backend from 'i18next-xhr-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';

i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    ns: ['translations'],
    fallbackLng: 'en',
    debug: true,
    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
    },
  });

export default i18n;
```
2. Create you translation file under `src/locales/en/` by the name of `translations.json` in this case.

```json
{
  "title": "It crashes!",
}
```
4. Create a functional component with something to translate.

```jsx
import React from 'react';
import { useTranslation } from 'react-i18next';
import i18n from '../i18n';

const MockComponent = () => {
  const { t } = useTranslation('translations', i18n);

  return (
    <div>{t('title')}</div>
  );
};

export default MockComponent;
```

4. Configure `gatsby-node.js` to copy locales directory into `public/`.

```javascript
const path = require('path');
const fs = require('fs-extra');

exports.onPostBuild = () => {
  fs.copySync(
    path.join(__dirname, '/src/locales'),
    path.join(__dirname, '/public/locales'),
  );
};
```

5. After this, you should just run `gatsby build`.

### Expected result

It should build successfully and after running `gatsby serve` you should see the message.

### Actual result

This is the actual output

```
gatsby build
success open and validate gatsby-configs - 0.042s
success load plugins - 0.365s
success onPreInit - 0.007s
success delete html and css files from previous builds - 0.018s
success initialize cache - 0.007s
success copy gatsby files - 0.071s
success onPreBootstrap - 0.010s
success createSchemaCustomization - 0.004s
success source and transform nodes - 0.581s
success building schema - 0.901s
success createPages - 0.002s
success createPagesStatefully - 0.111s
success onPreExtractQueries - 0.004s
success update schema - 0.073s
success extract queries from components - 0.533s
success write out requires - 0.006s
success write out redirect data - 0.002s
success onPostBootstrap - 0.002s
⠀
info bootstrap finished - 6.046 s
⠀
success Building production JavaScript and CSS bundles - 30.952s
success Rewriting compilation hashes - 0.005s
success run queries - 31.363s - 10/10 0.32/s
[                            ]   0.001 s 0/8 0% Building static HTML for pages
ReferenceError: XMLHttpRequest is not defined
    at Object.ajax (/Users/alvaro/github.com/site/public/render-page.js:184955:5)
    at Backend.loadUrl (/Users/alvaro/github.com/site/public/render-page.js:185064:20)
    at Backend.read (/Users/alvaro/github.com/site/public/render-page.js:185057:12)
    at Connector.read (/Users/alvaro/github.com/site/public/render-page.js:186707:34)
    at Connector.loadOne (/Users/alvaro/github.com/site/public/render-page.js:186773:12)
    at /Users/alvaro/github.com/site/public/render-page.js:186746:16
    at Array.forEach (<anonymous>)
    at Connector.prepareLoading (/Users/alvaro/github.com/site/public/render-page.js:186745:21)
    at Connector.load (/Users/alvaro/github.com/site/public/render-page.js:186752:12)
    at I18n.loadResources (/Users/alvaro/github.com/site/public/render-page.js:187111:40)
    at I18n.loadNamespaces (/Users/alvaro/github.com/site/public/render-page.js:187321:12)
    at loadNamespaces (/Users/alvaro/github.com/site/public/render-page.js:202618:8)
    at /Users/alvaro/github.com/site/public/render-page.js:202563:66
    at new Promise (<anonymous>)
    at useTranslation (/Users/alvaro/github.com/site/public/render-page.js:202562:9)
failed Building static HTML for pages - 12.201s

 ERROR #95313

Building static HTML failed for path "/"

See our docs page for more info on this error: https://gatsby.dev/debug-html



  Error: Minified React error #294; visit https://reactjs.org/docs/error-decoder.html?invariant=294 for the full message or use the non-minified dev environment for full errors and additional helpful warn  ings.

  - react-dom-server.node.production.min.js:44 a.b.read
    [site]/[react-dom]/cjs/react-dom-server.node.production.min.js:44:107

  - react-dom-server.node.production.min.js:54 renderToString
    [site]/[react-dom]/cjs/react-dom-server.node.production.min.js:54:364

  - render-page.js:569 Module../.cache/static-entry.js.__webpack_exports__.default
    /Users/alvaro/github.com/site/public/render-page.js:569:28

  - render-html.js:35
    [site]/[gatsby]/dist/utils/worker/render-html.js:35:36

  - debuggability.js:384 Promise._execute
    [site]/[bluebird]/js/release/debuggability.js:384:9

  - promise.js:518 Promise._resolveFromExecutor
    [site]/[bluebird]/js/release/promise.js:518:18

  - promise.js:103 new Promise
    [site]/[bluebird]/js/release/promise.js:103:10

  - render-html.js:31
    [site]/[gatsby]/dist/utils/worker/render-html.js:31:37

  - util.js:16 tryCatcher
    [site]/[bluebird]/js/release/util.js:16:23

  - map.js:68 MappingPromiseArray._promiseFulfilled
    [site]/[bluebird]/js/release/map.js:68:38

  - promise_array.js:115 MappingPromiseArray.PromiseArray._iterate
    [site]/[bluebird]/js/release/promise_array.js:115:31

  - promise_array.js:79 MappingPromiseArray.init
    [site]/[bluebird]/js/release/promise_array.js:79:10

  - map.js:37 MappingPromiseArray._asyncInit
    [site]/[bluebird]/js/release/map.js:37:10

  - async.js:97 _drainQueueStep
    [site]/[bluebird]/js/release/async.js:97:12

  - async.js:86 _drainQueue
    [site]/[bluebird]/js/release/async.js:86:9

  - async.js:102 Async._drainQueues
    [site]/[bluebird]/js/release/async.js:102:5



 ERROR

Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in StoreStateProvider
    in App
```

### Environment

```
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.7.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.14 - /usr/local/bin/python
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 70.0.1
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.18.5 => 2.18.5
    gatsby-image: ^2.2.30 => 2.2.34
    gatsby-plugin-i18n: ^1.0.1 => 1.0.1
    gatsby-plugin-manifest: ^2.2.25 => 2.2.30
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6
    gatsby-plugin-offline: ^3.0.17 => 3.0.25
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.16
    gatsby-plugin-react-svg: ^2.1.2 => 2.1.2
    gatsby-plugin-sharp: ^2.2.34 => 2.3.4
    gatsby-plugin-styled-components: ^3.1.11 => 3.1.14
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-filesystem: ^2.1.35 => 2.1.39
    gatsby-transformer-remark: ^2.6.32 => 2.6.38
    gatsby-transformer-sharp: ^2.3.1 => 2.3.6
    gatsby-transformer-yaml: ^2.2.17 => 2.2.18
  npmGlobalPackages:
    gatsby-cli: 2.8.8
```

### Useful Links:
  - Building i18n with Gatsby: https://www.gatsbyjs.org/blog/2017-10-17-building-i18n-with-gatsby/
  - react-i18next: https://react.i18next.com/

**Comment by alvgaona** [comment]
It seems `XMLHttpRequest` is not installed in production build. 🤔

**Comment by LekoArts** [comment]
Thank you for opening this!

This is an issue with `XHR` API not being available in Node context (since Gatsby runs on Node during `gatsby build`).
Please refer to this issue to see how to solve it as it's a general "SSR" problem and not specific to Gatsby:

https://github.com/i18next/i18next-xhr-backend/issues/281

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by alvgaona** [comment]
Thanks for the quick response @LekoArts!

**Comment by Amilight** [comment]
Hi all,
I have hit the same error as well and [article ](https://www.gatsbyjs.com/blog/2017-10-17-building-i18n-with-gatsby/)present on Gatsby blog is a good start but it leaves us at nowhere at ssr part.
Went to other thread provided by @LekoArts but even this does not solve the problem.
I hope we get more beginner friendly articles.
Hope it gets solved.

Anyways , Thank you!
