### ISSUE TITLE
Cannot read property 'bitmap' of undefined

### ISSUE THREAD

**Issue by MuhammedAO** [gatsbyjs/gatsby#20377]
Guys please i have a project i MUST deliver in 2 days time. Help me look into this issue. 
Cannot read property 'bitmap' of undefined

TypeError: Cannot read property 'bitmap' of undefined
    at Potrace._processLoadedImage (C:\Users\HP LAPTOP\Desktop\maloneats\node_modules\potrace\lib\Potrace.js:1000:35)
    at Jimp.<anonymous> (C:\Users\HP LAPTOP\Desktop\maloneats\node_modules\potrace\lib\Potrace.js:1046:14)
    at Timeout._onTimeout (C:\Users\HP LAPTOP\Desktop\maloneats\node_modules\@jimp\core\dist\index.js:331:25)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**Comment by DanielRuf** [comment]
Hi @MuhammedAO,

This seems to be an issue with jimp (thirdparty module).

What did you try so far?
`npm rebuild --force` or `rm -rf node_modules && npm ci` should resolve that.

**Comment by DanielRuf** [comment]
Hi @MuhammedAO,

This seems to be an issue with potrace (thirdparty module).

What did you try so far?
`npm rebuild --force` or `rm -rf node_modules && npm ci` should resolve that.

**Comment by DanielRuf** [comment]
Hi @MuhammedAO,

This seems to be an issue with potrace and jimp (thirdparty modules).

What did you try so far?
`npm rebuild --force` or `rm -rf node_modules && npm ci` should resolve that.

See https://github.com/tooolbox/node-potrace/blob/2682ad11fb3e3742946a7267a069cbb81ce23bcc/lib/Potrace.js#L1003

So `image` seems to be undefined. Are all images with a proper / correct `src`?

**Comment by jonniebigodes** [comment]
@MuhammedAO if you can take a look at #8301 and #12023 and #12552 to see if it helps

**Comment by ZeldOcarina** [comment]
Hi! Did you ever find a way out on this?
