### ISSUE TITLE
Can't create new gatsby site, sharp error

### ISSUE THREAD

**Issue by rjchirinos** [gatsbyjs/gatsby#20410]
## Description

I installed gatsby-cli, but when I tried to create a new gatsby site it throws me an error

### Steps to reproduce

$ gatsby new gatsby-site

### Actual result

```error /home/nileida/Code/gatsby-site/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /home/nileida/Code/gatsby-site/node_modules/sharp
Output:
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linux-x64.tar.gz
ERR! sharp Please delete /home/nileida/.npm/_libvips/libvips-8.8.1-linux-x64.tar.gz as it is not a valid tarball
ERR! sharp zlib: unexpected end of file
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/page/install for required dependencies
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.14.0 | linux | x64
gyp info find Python using Python version 2.7.12 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/nileida/Code/gatsby-site/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/nileida/.cache/node-gyp/12.14.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/nileida/.cache/node-gyp/12.14.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/nileida/.cache/node-gyp/12.14.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/nileida/Code/gatsby-site/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: se entra en el directorio '/home/nileida/Code/gatsby-site/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
make: g++: No se encontró el programa
sharp.target.mk:135: fallo en las instrucciones para el objetivo 'Release/obj.target/sharp/src/common.o'
make: *** [Release/obj.target/sharp/src/common.o] Error 127
make: se sale del directorio '/home/nileida/Code/gatsby-site/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.4.0-53-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nileida/Code/gatsby-site/node_modules/sharp
gyp ERR! node -v v12.14.0





 ERROR 

Command failed with exit code 1: yarnpkg
```

### Environment

```
 System:
    OS: Linux 4.4 Linux Mint 18.1 (Serena)
    CPU: (2) x64 AMD Turion(tm) 64 X2 Mobile Technology TL-50
    Shell: 4.3.46 - /bin/bash
  Binaries:
    Node: 12.14.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.12 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 67.0.4


```

**Comment by tcope25** [comment]
Try deleting `/home/nileida/.npm/_libvips/libvips-8.8.1-linux-x64.tar.gz` and run it again

**Comment by sidharthachatterjee** [comment]
> Please delete /home/nileida/.npm/_libvips/libvips-8.8.1-linux-x64.tar.gz as it is not a valid tarball
> ERR! sharp zlib: unexpected end of file

@rjchirinos Based on this, it looks like the download failed for some reason. Can you delete all dependencies with `rm -rf node_modules` and `/home/nileida/.npm/_libvips/libvips-8.8.1-linux-x64.tar.gz` and try again? 

That should fix this.

**Comment by sidharthachatterjee** [comment]
Looks like https://github.com/lovell/sharp-libvips/issues/35 addresses this issue and the comment resolves it. 

Closing this as it is upstream. Thanks!

**Comment by rowanD72** [comment]
Found this on StackOverflow:
xcode-select --install
brew install gcc
brew reinstall vips
brew info vips
npm I

This fixed my issue.
