### ISSUE TITLE
PR blocked by windows unit tests

### ISSUE THREAD

**Issue by rbutera** [gatsbyjs/gatsby#20468]
I tried to submit a PR for a gatsby starter [(Pull Request #20453](https://github.com/gatsbyjs/gatsby/pull/20453) ) but one of the CI checks is not passing (windows unit tests).

The circleCI log is located here:

https://circleci.com/gh/gatsbyjs/gatsby/301076?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

As you can see, it appears to be an issue with the installation of `@babel/plugin-transform-typescript`:

```
lerna ERR! yarn run prepare stderr:
Error: Cannot find module '@babel/plugin-transform-typescript' from 'C:\Users\circleci\project\packages\gatsby-cli'
    at Function.module.exports [as sync] (C:\Users\circleci\project\node_modules\resolve\lib\sync.js:74:15)
    at resolveStandardizedName (C:\Users\circleci\project\node_modules\@babel\cli\node_modules\@babel\core\lib\config\files\plugins.js:101:31)
    at resolvePlugin (C:\Users\circleci\project\node_modules\@babel\cli\node_modules\@babel\core\lib\config\files\plugins.js:54:10)
    at loadPlugin (C:\Users\circleci\project\node_modules\@babel\cli\node_modules\@babel\core\lib\config\files\plugins.js:62:20)
    at createDescriptor (C:\Users\circleci\project\node_modules\@babel\cli\node_modules\@babel\core\lib\config\config-descriptors.js:154:9)
    at C:\Users\circleci\project\node_modules\@babel\cli\node_modules\@babel\core\lib\config\config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (C:\Users\circleci\project\node_modules\@babel\cli\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPluginDescriptors (C:\Users\circleci\project\node_modules\@babel\cli\node_modules\@babel\core\lib\config\config-descriptors.js:105:10)
    at plugins (C:\Users\circleci\project\node_modules\@babel\cli\node_modules\@babel\core\lib\config\config-descriptors.js:40:19) {
  code: 'MODULE_NOT_FOUND'
}
```

**Comment by sidharthachatterjee** [comment]
That has since been fixed. Please rebase or merge master. Thanks!

**Comment by rbutera** [comment]
@sidharthachatterjee 

thanks for the speedy reply. when I try and merge master I don't see any changes related to this issue?

Please see https://github.com/rbutera/gatsby/compare/master...gatsbyjs:master

**Comment by rbutera** [comment]
@sidharthachatterjee 

nevermind, I just checked and the PR is no longer blocked. Thanks!
