### ISSUE TITLE
Error starting new project compiling

### ISSUE THREAD

**Issue by micka753** [gatsbyjs/gatsby#20474]
Hello, I have this error trying to set up a new Gatsby project.
I'm using node v13.6.0, npm v6.13.4, python 3.7 and visual express 2017
I'm able to install for example bcrypt, I wonder if it's an issue with Linux file path like.

```
$ gatsby new wp-gatsby https://github.com/GatsbyCentral/gatsby-starter-wordpress
info Creating new site from git: https://github.com/GatsbyCentral/gatsby-starter-wordpress.git
Cloning into 'wp-gatsby'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 53 (delta 1), reused 33 (delta 0), pack-reused 0
Unpacking objects: 100% (53/53), done.
[32msuccess[39m Created starter directory layout
[34minfo[39m Installing packages...

> deasync@0.1.16 install C:\xampp\htdocs\wordpress\wp-gatsby\node_modules\deasync
> node ./build.js

`win32-x64-node-12` exists; testing
Binary is fine; exiting

> sharp@0.23.3 install C:\xampp\htdocs\wordpress\wp-gatsby\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached C:\Users\userXX\AppData\Roaming\npm-cache\_libvips\libvips-8.8.1-win32-x64.tar.gz
info sharp Creating C:\xampp\htdocs\wordpress\wp-gatsby\node_modules\sharp\build\Release
info sharp Copying DLLs from C:\xampp\htdocs\wordpress\wp-gatsby\node_modules\sharp\vendor\lib to C:\xampp\htdocs\wordpress\wp-gatsby\node_modules\sharp\build\Release

> node-sass@4.13.0 install C:\xampp\htdocs\wordpress\wp-gatsby\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\userXX\AppData\Roaming\npm-cache\node-sass\4.13.0\win32-x64-72_binding.node

> core-js@2.6.10 postinstall C:\xampp\htdocs\wordpress\wp-gatsby\node_modules\core-js
> node postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> gatsby-telemetry@1.1.39 postinstall C:\xampp\htdocs\wordpress\wp-gatsby\node_modules\gatsby-telemetry
> node src/postinstall.js


> cwebp-bin@5.1.0 postinstall C:\xampp\htdocs\wordpress\wp-gatsby\node_modules\cwebp-bin
> node lib/install.js

  ‼ read ECONNRESET
  ‼ cwebp pre-build test failed
  i compiling from source
  × Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "./configure --disable-shared --prefix="C:\xampp\htdocs\wordpress\wp-gatsby\node_modules\cwebp-bin\vendor" --bindir="C:\xampp\htdocs\wordpress\wp-gatsby\node_modules\cwebp-bin\vendor""
'.' n'est pas reconnu en tant que commande interne
ou externe, un programme ex�cutable ou un fichier de commandes.


    at C:\xampp\htdocs\wordpress\wp-gatsby\node_modules\execa\index.js:231:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)

> mozjpeg@6.0.1 postinstall C:\xampp\htdocs\wordpress\wp-gatsby\node_modules\mozjpeg
> node lib/install.js

  ‼ read ECONNRESET
  ‼ mozjpeg pre-build test failed
  i compiling from source
  × Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "autoreconf -fiv"
'autoreconf' n'est pas reconnu en tant que commande interne
ou externe, un programme ex�cutable ou un fichier de commandes.


    at C:\xampp\htdocs\wordpress\wp-gatsby\node_modules\execa\index.js:231:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)

> pngquant-bin@5.0.2 postinstall C:\xampp\htdocs\wordpress\wp-gatsby\node_modules\pngquant-bin
> node lib/install.js

  ‼ read ECONNRESET
  ‼ pngquant pre-build test failed
  i compiling from source
  × Error: pngquant failed to build, make sure that libpng-dev is installed
    at C:\xampp\htdocs\wordpress\wp-gatsby\node_modules\execa\index.js:231:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
npm WARN rollback Rolling back node-pre-gyp@0.12.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\xampp\htdocs\wordpress\wp-gatsby\node_modules\fsevents\node_modules'
npm WARN gatsby-starter-wordpress@0.1.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@5.0.2 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@5.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\userXX\AppData\Roaming\npm-cache\_logs\2020-01-07T14_33_53_695Z-debug.log

 ERROR

Command failed with exit code 1: npm install



  Error: Command failed with exit code 1: npm install

  - error.js:56 makeError
    [node-v12.14.0-win-x64]/[gatsby-cli]/[execa]/lib/error.js:56:11

  - index.js:114 handlePromise
    [node-v12.14.0-win-x64]/[gatsby-cli]/[execa]/index.js:114:26

  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5
```

**Comment by wardpeet** [comment]
Hey, thanks for opening an issue. Have you tried installing `npm install windows-build-tools -g`? windows-build-tools are probably required.

You can read more about this on https://www.gatsbyjs.org/docs/gatsby-on-windows/#setting-up-your-environment-for-building-native-nodejs-modules.

Please let u know if this fixed or didn't fix your issue.

**Comment by micka753** [comment]
Hello I installed Visual Express because my company is too big to use Visual Studio for free.

**Comment by sidharthachatterjee** [comment]
@micka753 Unsure but there must be an equivalent way to installing build tools? 

If not, I'd recommend [WSL](https://www.gatsbyjs.org/docs/gatsby-on-windows/#windows-subsystem-for-linux) personally

**Comment by jonniebigodes** [comment]
@micka753 have you taken a look at [this](https://github.com/nodejs/node-gyp#option-2) might help you with your issue. You'll probably need to modify the installation following [these steps](https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio?view=vs-2019)

**Comment by sidharthachatterjee** [comment]
@jonniebigodes is absolutely right! 

Marking this as resolved and closing since this isn't strictly a Gatsby issue but feel free to comment if you need any more help on this. Thanks!

**Comment by micka753** [comment]
Thanks for the help, I m not able to modify the configuration of Visual Express (it does not offer more choices than the language packs).
I tried WSL but I can't install WSL 2 because of my Windows version, and was not able to configure access to the Internet with WSL 1.
Still I was able to install Docker, so I'll try Gatsby this way.
Cheers
