### ISSUE TITLE
Couldn't create new gatsby site with CLI

### ISSUE THREAD

**Issue by shanejix** [gatsbyjs/gatsby#20623]
## Description
I couldn't create new gatsby site with CLI.
### Actual result
```
$ gatsby new gatsby-site
info Creating new site from git: https://github.com/gatsbyjs/gatsby-starter-default.git
Cloning into 'gatsby-site'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 28 (delta 2), reused 17 (delta 2), pack-reused 0
Unpacking objects: 100% (28/28), done.
success Created starter directory layout
info Installing packages...
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.11: The platform "win32" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "gatsby > react-hot-loader@4.12.18" has unmet peer dependency "@types/react@^15.0.0 || ^16.0.0".
warning "gatsby > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning "gatsby > gatsby-cli > ink@2.6.0" has unmet peer dependency "@types/react@>=16.8.0".
[4/4] Building fresh packages...
error E:\githubdemo\gatsby-site\node_modules\pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: E:\githubdemo\gatsby-site\node_modules\pngquant-bin
Output:
‼ Command failed: E:\githubdemo\gatsby-site\node_modules\pngquant-bin\vendor\pngquant.exe --version


  ‼ pngquant pre-build test failed
  i compiling from source
  × Error: pngquant failed to build, make sure that libpng-dev is installed
    at E:\githubdemo\gatsby-site\node_modules\bin-build\node_modules\execa\index.js:231:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

 ERROR

Command failed with exit code 1: yarnpkg



  Error: Command failed with exit code 1: yarnpkg

  - error.js:56 makeError
    [npm]/[gatsby-cli]/[execa]/lib/error.js:56:11

  - index.js:114 handlePromise
    [npm]/[gatsby-cli]/[execa]/index.js:114:26

  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5



```

### Environment

```
$ gatsby info

  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0

```

**Comment by vladar** [comment]
Hi @shanejix !

Sorry to hear you're running into an issue. Did you follow all the steps outlined in our [Gatsby on Windows](https://www.gatsbyjs.org/docs/gatsby-on-windows/#setting-up-your-environment-for-building-native-nodejs-modules) docs?

Specifically have you tried installing `npm install windows-build-tools -g`? It should help.

**Comment by shanejix** [comment]
> Hi @shanejix !
> 
> Sorry to hear you're running into an issue. Did you follow all the steps outlined in our [Gatsby on Windows](https://www.gatsbyjs.org/docs/gatsby-on-windows/#setting-up-your-environment-for-building-native-nodejs-modules) docs?
> 
> Specifically have you tried installing `npm install windows-build-tools -g`? It should help.

resolved,thanks!
