### ISSUE TITLE
Error when installing gatsby-remark-images with yarn

### ISSUE THREAD

**Issue by PolGuixe** [gatsbyjs/gatsby#2076]
When I try to add `gatsby-remark-images` with: 

`yarn add gatsby-remark-images`

I am getting this error: 
```
[4/4] 📃  Building fresh packages...
[1/4] ⠁ fsevents
[2/4] ⠁ uws
[3/4] ⠁ pngquant-bin
[4/4] ⠁ sharp: gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
error /Users/polguixe/Developer/projects/other/portfolio/node_modules/pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments: 
Directory: /Users/polguixe/Developer/projects/other/portfolio/node_modules/pngquant-bin
Output:
module.js:491
    throw err;
    ^

Error: Cannot find module 'trim-repeated'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/polguixe/Developer/projects/other/portfolio/node_modules/filenamify/index.js:3:20)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
```

My `package.json` looks like
```
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "classnames": "^2.2.5",
    "gatsby": "^1.8.12",
    "gatsby-link": "^1.6.8",
    "gatsby-plugin-jss": "^1.5.6",
    "gatsby-plugin-react-helmet": "^1.0.3",
    "gatsby-plugin-typography": "^1.7.7",
    "gatsby-source-filesystem": "^1.4.12",
    "gatsby-transformer-remark": "^1.7.7",
    "gatsby-transformer-sharp": "^1.6.5",
    "lodash": "^4.17.4",
    "material-ui": "^1.0.0-beta.8",
    "material-ui-icons": "^1.0.0-beta.5",
    "prop-types": "^15.5.10",
    "react": "^15.6.1",
    "react-emojione": "^3.1.10",
    "react-helmet": "^5.2.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --trailing-comma es5 --no-semi --single-quote --write 'src/**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-eslint": "^7.2.3",
    "babel-preset-flow": "^6.23.0",
    "eslint": "^4.5.0",
    "eslint-config-airbnb": "^15.1.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.3.0",
    "prettier": "^1.5.2"
  }
}
```

**Comment by KyleAMathews** [comment]
What is your versions of node and Yarn?

**Comment by PolGuixe** [comment]
I am using node 6.10.1 and yarn 1.0.1.

**Comment by KyleAMathews** [comment]
Try removing `node_modules` and reinstalling?

**Comment by PolGuixe** [comment]
I have tried that already. Few times. 😅

**Comment by KyleAMathews** [comment]
Have you tried deleting your yarn.lock as well?

**Comment by PolGuixe** [comment]
I just tried. Same result.

**Comment by Jinksi** [comment]
I had the same issue with node v7.1.0.
Upgrading to node 8.50 fixed the issue for me.

**Comment by PolGuixe** [comment]
I have upgraded to node 8.5.0 and I am still having the issue.

**Comment by KyleAMathews** [comment]
Hey, closing out old issues. Please re-open if you have additional questions, thanks!
