### ISSUE TITLE
Cannot find module 'gatsby/graphql'

### ISSUE THREAD

**Issue by Wilmerj** [gatsbyjs/gatsby#20841]
## Description

Bug when install two basic plugins gatsby-transformer-remark and gatsby-source-filesystem

### Steps to reproduce

Install gatsby-transformer-remark and gatsby-source-filesystem and run comand gatsby develop

Versions installed: 

"gatsby-source-filesystem": "^2.1.46"
"gatsby-transformer-remark": "^2.6.48"

### Actual result
success delete html and css files from previous builds — 0.045 s
success open and validate gatsby-config.js — 0.007 s

Your plugins must export known APIs from their gatsby-node.js.
The following exports aren't APIs. Perhaps you made a typo or
your plugin is outdated?

See https://www.gatsbyjs.org/docs/node-apis/ for the list of Gatsby Node APIs
 — The plugin "gatsby-transformer-remark@2.6.48" is exporting a variable named "createSchemaCustomization" which isn't an API.

info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's not any stale
data
success copy gatsby files — 0.053 s
⠂ onPreBootstrap/usr/local/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Cannot find module 'gatsby/graphql'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (/Users/wgarzon/Documents/Ejemplos/gatsby-workshop/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/wgarzon/Documents/Ejemplos/gatsby-workshop/node_modules/gatsby-source-filesystem/extend-file-node.js:5:5)
    at Module._compile (/Users/wgarzon/Documents/Ejemplos/gatsby-workshop/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (/Users/wgarzon/Documents/Ejemplos/gatsby-workshop/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/wgarzon/Documents/Ejemplos/gatsby-workshop/node_modules/gatsby-source-filesystem/gatsby-node.js:259:38)
    at Module._compile (/Users/wgarzon/Documents/Ejemplos/gatsby-workshop/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at runAPI (/Users/wgarzon/Documents/Ejemplos/gatsby-workshop/node_modules/gatsby/dist/utils/api-runner-node.js:87:20)
    at /Users/wgarzon/Documents/Ejemplos/gatsby-workshop/node_modules/gatsby/dist/utils/api-runner-node.js:187:33

**Comment by ascorbic** [comment]
Hi. Is the project code available publicly anywhere, or are you able to provide a reproduction?

**Comment by pieh** [comment]
What version of gatsby are you using? The "Cannot find module 'gatsby/graphql'" could suggest using gatsby v1. Can you provide output of `gatsby info`?

**Comment by sidharthachatterjee** [comment]
@Wilmerj Like @pieh mentioned, the error suggests that you're trying to use v1 of Gatsby which we don't support anymore. Can you try v2 and installing these plugins there? 

That _should_ solve your issue so I'll go ahead and close this for now. In case it doesn't though, please feel free to post more details here and we'll be happy to help. Thanks!
