### ISSUE TITLE
Extend custom Types and Interfaces

### ISSUE THREAD

**Issue by Jhony0311** [gatsbyjs/gatsby#20969]
## Summary
Hey Gatsby people,

I'm starting a project where my data source is a set of JSON files. In order to make them a bit more robust, I would like to get them extender using custom types. I already put something in place for custom types nested inside of a field of my JSON but the things are not working for me when I tried to do an interface for an array.

I was looking into the documentation for schema customization (https://www.gatsbyjs.org/docs/schema-customization/) but the portion for interfaces is not as detailed as I would like in order to complete the setup myself.

I'm thinking that I might be missing to create one resolver for the field that exposes the interface but not sure what is the best way to go for it.

My expectation is to get something like this as an output of the Graphql API:
```
{
    "__typename": "TriVideo",
    "kind": "TriVideo",
}
```
But what I'm getting right now is:
```
{
  "errors": [
    {
      "message": "Cannot read property 'type' of undefined",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "pagesJson",
        "contentBlocks",
        0
      ],
      "stack": [
        "TypeError: Cannot read property 'type' of undefined",
        "    at typeComposer.setResolveType.node (/sandbox/node_modules/gatsby/dist/schema/schema.js:471:57)",
        "    at completeAbstractValue (/sandbox/node_modules/graphql/execution/execute.js:652:21)",
        "    at completeValue (/sandbox/node_modules/graphql/execution/execute.js:585:12)",
        "    at completeValueCatchingError (/sandbox/node_modules/graphql/execution/execute.js:495:19)",
        "    at /sandbox/node_modules/graphql/execution/execute.js:618:25",
        "    at Array.forEach (<anonymous>)",
        "    at forEach (/sandbox/node_modules/iterall/index.js:83:25)",
        "    at completeListValue (/sandbox/node_modules/graphql/execution/execute.js:614:24)",
        "    at completeValue (/sandbox/node_modules/graphql/execution/execute.js:573:12)",
        "    at completeValueCatchingError (/sandbox/node_modules/graphql/execution/execute.js:495:19)",
        "    at resolveField (/sandbox/node_modules/graphql/execution/execute.js:435:10)",
        "    at executeFields (/sandbox/node_modules/graphql/execution/execute.js:275:18)",
        "    at collectAndExecuteSubfields (/sandbox/node_modules/graphql/execution/execute.js:713:10)",
        "    at completeObjectValue (/sandbox/node_modules/graphql/execution/execute.js:703:10)",
        "    at completeValue (/sandbox/node_modules/graphql/execution/execute.js:591:12)",
        "    at /sandbox/node_modules/graphql/execution/execute.js:492:16"
      ]
    },
    {
      "message": "Cannot read property 'type' of undefined",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "pagesJson",
        "contentBlocks",
        1
      ],
      "stack": [
        "TypeError: Cannot read property 'type' of undefined",
        "    at typeComposer.setResolveType.node (/sandbox/node_modules/gatsby/dist/schema/schema.js:471:57)",
        "    at completeAbstractValue (/sandbox/node_modules/graphql/execution/execute.js:652:21)",
        "    at completeValue (/sandbox/node_modules/graphql/execution/execute.js:585:12)",
        "    at completeValueCatchingError (/sandbox/node_modules/graphql/execution/execute.js:495:19)",
        "    at /sandbox/node_modules/graphql/execution/execute.js:618:25",
        "    at Array.forEach (<anonymous>)",
        "    at forEach (/sandbox/node_modules/iterall/index.js:83:25)",
        "    at completeListValue (/sandbox/node_modules/graphql/execution/execute.js:614:24)",
        "    at completeValue (/sandbox/node_modules/graphql/execution/execute.js:573:12)",
        "    at completeValueCatchingError (/sandbox/node_modules/graphql/execution/execute.js:495:19)",
        "    at resolveField (/sandbox/node_modules/graphql/execution/execute.js:435:10)",
        "    at executeFields (/sandbox/node_modules/graphql/execution/execute.js:275:18)",
        "    at collectAndExecuteSubfields (/sandbox/node_modules/graphql/execution/execute.js:713:10)",
        "    at completeObjectValue (/sandbox/node_modules/graphql/execution/execute.js:703:10)",
        "    at completeValue (/sandbox/node_modules/graphql/execution/execute.js:591:12)",
        "    at /sandbox/node_modules/graphql/execution/execute.js:492:16"
      ]
    },
    {
      "message": "Cannot read property 'type' of undefined",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "pagesJson",
        "contentBlocks",
        2
      ],
      "stack": [
        "TypeError: Cannot read property 'type' of undefined",
        "    at typeComposer.setResolveType.node (/sandbox/node_modules/gatsby/dist/schema/schema.js:471:57)",
        "    at completeAbstractValue (/sandbox/node_modules/graphql/execution/execute.js:652:21)",
        "    at completeValue (/sandbox/node_modules/graphql/execution/execute.js:585:12)",
        "    at completeValueCatchingError (/sandbox/node_modules/graphql/execution/execute.js:495:19)",
        "    at /sandbox/node_modules/graphql/execution/execute.js:618:25",
        "    at Array.forEach (<anonymous>)",
        "    at forEach (/sandbox/node_modules/iterall/index.js:83:25)",
        "    at completeListValue (/sandbox/node_modules/graphql/execution/execute.js:614:24)",
        "    at completeValue (/sandbox/node_modules/graphql/execution/execute.js:573:12)",
        "    at completeValueCatchingError (/sandbox/node_modules/graphql/execution/execute.js:495:19)",
        "    at resolveField (/sandbox/node_modules/graphql/execution/execute.js:435:10)",
        "    at executeFields (/sandbox/node_modules/graphql/execution/execute.js:275:18)",
        "    at collectAndExecuteSubfields (/sandbox/node_modules/graphql/execution/execute.js:713:10)",
        "    at completeObjectValue (/sandbox/node_modules/graphql/execution/execute.js:703:10)",
        "    at completeValue (/sandbox/node_modules/graphql/execution/execute.js:591:12)",
        "    at /sandbox/node_modules/graphql/execution/execute.js:492:16"
      ]
    }
  ],
  "data": {
    "pagesJson": {
      "contentBlocks": [
        null,
        null,
        null
      ]
    }
  }
}
```

### Environment
I've created a minimal setup of my local within CodeSandbox
https://codesandbox.io/s/quirky-pare-bk01t

**Comment by devrchancay** [comment]
I think this can help you: https://learnwithjason.dev/advanced-graphql-techniques-in-gatsby

 At first glance everything looks good, I am also in the mobile when I get home I will see the detailed mind on my computer

**Comment by pieh** [comment]
Can you share some minimal reproduction? It's hard to say what's going on without seeing source data and what you schema customization looks like

**Comment by Jhony0311** [comment]
I did, is part of the issue. Here you can see what I have: https://codesandbox.io/s/quirky-pare-bk01t

**Comment by vladar** [comment]
@Jhony0311 Thanks for opening this! We lack documentation on how to create custom interfaces indeed.

The missing piece in your sandbox is defining `resolveType` method for the Block interface. This method accepts an incoming value and decides the specific object type of this value (using some discriminator, in your case `kind`).

So what you could do is to define this interface separately:

```js
exports.createSchemaCustomization = ({ actions, schema }) => {
  const { createTypes } = actions

  const blockInterface = schema.buildInterfaceType({
    name: `Block`,
    fields: {
      kind: `String!`,
    },
    resolveType: value => value.kind,
  })

  const typeDefs = `
        type PagesJson implements Node {
            image: File @fileByRelativePath
            example1: TriVideo
            example2: ThoughtBlock
            example3: TwoColumnWrapped
            contentBlocks: [Block]
        }

        type TriVideo implements Block {
            kind: String!
            video1: String!
            video2: String!
            video3: String!
        }

        type ThoughtBlock implements Block {
            kind: String!
            orientation: String!
            text: String!
        }

        type TwoColumnWrapped implements Block {
            kind: String!
            imageSide: String!
            text: String!
            images: [File!] @fileByRelativePath
        }
    `

  createTypes([blockInterface, typeDefs])
}
```

I've forked your codesandbox, so you can see a working version here: https://codesandbox.io/s/practical-monad-57x37 (also I don't think you need `createResolvers` at all - you only need those when your graphql fields are different from source value fields)

I hope it helps.

**Comment by Jhony0311** [comment]
That worked perfectly @vladar I appreciate it. I also appreciate the explanation, helped me a lot to understand what's happening and what I need to do to accomplish what I'm looking for.

Is there any improvements to the docs that I could help with? I'm not a graphql expert myself but I'll be more than happy to jump on anything that could help people to get things clearer.

**Comment by marcysutton** [comment]
@Jhony0311 we have Using Schema Customization coming up as a workflow to evaluate next quarter. If there are things you feel could be improved in the docs in the meantime, we would welcome a PR! Another way to contribute would be to get a jump start on the workflow evaluation as outlined here (# 15): https://github.com/gatsbyjs/gatsby/issues/13708

**Comment by webrgp** [comment]
While trying to implement this solution in Gatsby v3.13.1 everything builds without issue, but when trying to run a query on GraphiQL I get the following error:

`TypeError: Cannot read property 'type' of undefined`

After a bit of tracing and debugging, I've hit a dead end here:

https://github.com/gatsbyjs/gatsby/blob/664af4d7b945f824ac80f17de53c5f61e1fc8932/packages/gatsby/src/schema/schema.js#L412

I am not sure where to go from here.
