### ISSUE TITLE
gatsby develop -> Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by tleunen** [gatsbyjs/gatsby#210]
I reinstalled gatsby, I guess one of the dependencies was updated and now I get this error when I run `gatsby develop`

```
Debug: internal, implementation, error 
    TypeError: Uncaught error: Cannot read property 'indexOf' of undefined
  at getFilenameFromUrl (/Users/tleunen/dev/tp/node_modules/gatsby/node_modules/webpack-dev-middleware/middleware.js:129:9)
  at webpackDevMiddleware (/Users/tleunen/dev/tp/node_modules/gatsby/node_modules/webpack-dev-middleware/middleware.js:174:18)
  at /Users/tleunen/dev/tp/node_modules/gatsby/node_modules/hapi-webpack-plugin/lib/index.js:58:5
  at /Users/tleunen/dev/tp/node_modules/gatsby/node_modules/hapi/lib/handler.js:311:22
  at iterate (/Users/tleunen/dev/tp/node_modules/gatsby/node_modules/hapi/node_modules/items/lib/index.js:35:13)
  at done (/Users/tleunen/dev/tp/node_modules/gatsby/node_modules/hapi/node_modules/items/lib/index.js:27:25)
  at Function.wrapped [as _next] (/Users/tleunen/dev/tp/node_modules/gatsby/node_modules/hapi/node_modules/hoek/lib/index.js:858:20)
  at Function.internals.continue (/Users/tleunen/dev/tp/node_modules/gatsby/node_modules/hapi/lib/reply.js:105:10)
  at /Users/tleunen/dev/tp/node_modules/gatsby/dist/utils/develop.js:146:25
  at /Users/tleunen/dev/tp/node_modules/gatsby/node_modules/hapi/lib/handler.js:311:22
  at iterate (/Users/tleunen/dev/tp/node_modules/gatsby/node_modules/hapi/node_modules/items/lib/index.js:35:13)
  at Object.exports.serial (/Users/tleunen/dev/tp/node_modules/gatsby/node_modules/hapi/node_modules/items/lib/index.js:38:9)
  at /Users/tleunen/dev/tp/node_modules/gatsby/node_modules/hapi/lib/handler.js:306:15
  at [object Object].internals.Protect.run (/Users/tleunen/dev/tp/node_modules/gatsby/node_modules/hapi/lib/protect.js:56:5)
  at Object.exports.invoke (/Users/tleunen/dev/tp/node_modules/gatsby/node_modules/hapi/lib/handler.js:304:22)
  at [object Object].internals.Request._execute (/Users/tleunen/dev/tp/node_modules/gatsby/node_modules/hapi/lib/request.js:311:13)
  at Domain.<anonymous> (/Users/tleunen/dev/tp/node_modules/gatsby/node_modules/hapi/lib/connection.js:246:25)
  at Domain.run (domain.js:228:14)
  at Server.<anonymous> (/Users/tleunen/dev/tp/node_modules/gatsby/node_modules/hapi/lib/connection.js:244:37)
  at emitTwo (events.js:100:13)
  at Server.emit (events.js:185:7)
  at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:537:12)
  at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
```

After investigation, inside the develop script, this is true `negotiator.mediaType() === 'text/html'`. Therefore, the system tries to load a page at `/html/` but nothing exists there...

**Comment by tleunen** [comment]
So after investigation, it's indeed a dependency. And it's `webpack-dev-middleware`. The version 1.5.1 works, but v1.6.0 doesn't work with gatsby.

**Comment by KyleAMathews** [comment]
https://github.com/webpack/webpack-dev-middleware/commit/b05cd045d83123d410c54627dec937506b8013e3 is what broke things.

There's an open PR to fix it https://github.com/webpack/webpack-dev-middleware/pull/80

**Comment by KyleAMathews** [comment]
Note, this isn't a direct dependency of Gatsby. We depend on https://github.com/SimonDegraeve/hapi-webpack-plugin which depends on webpack-dev-middleware.

**Comment by KyleAMathews** [comment]
1.6.1 of webpack-dev-middleware was released today which rolled-back the regression. https://github.com/webpack/webpack-dev-middleware/commit/8044d042a85848f7b7445f413e78e99e86e904e5
