### ISSUE TITLE
[gatsby-source-contentful] `responsiveSizes` and `resize` error with `image/gif` assets

### ISSUE THREAD

**Issue by lsirivong** [gatsbyjs/gatsby#2120]
These GraphQL queries error out if the contentful space has any assets with `image/gif` content type.

Here's a glitch project showing the issue, connected to a space I created with a single gif asset.

https://purple-cycle.glitch.me/___graphql

Enter this query and you'll see an error
```
{
  allContentfulAsset {
    edges {
      node {
        resize {
          src
        }
      }
    }
  }
}
```

Same with this query:
```
{
  allContentfulAsset {
    edges {
      node {
        responsiveSizes {
          src
        }
      }
    }
  }
}
```

Here's the error log:

```
UNHANDLED REJECTION ReferenceError: pickedHeight is not defined
6:03 PM
    at /app/node_modules/gatsby-source-contentful/extend-node-type.js:262:32
6:03 PM
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
6:03 PM
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
6:03 PM
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
6:03 PM
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
6:03 PM
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)
6:03 PM
    at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)
6:03 PM
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
6:03 PM
    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
6:03 PM
    at runCallback (timers.js:800:20)
6:03 PM
    at tryOnImmediate (timers.js:762:5)
6:03 PM
    at processImmediate [as _immediateCallback] (timers.js:733:5)
6:03 PM
/app/node_modules/bluebird/js/release/async.js:61
6:03 PM
        fn = function () { throw arg; };
6:03 PM
                           ^
6:03 PM
6:03 PM
ReferenceError: pickedHeight is not defined
6:03 PM
    at /app/node_modules/gatsby-source-contentful/extend-node-type.js:262:32
6:03 PM
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
6:03 PM
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
6:03 PM
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
6:03 PM
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
6:03 PM
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)
6:03 PM
    at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)
6:03 PM
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
6:03 PM
    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
6:03 PM
    at runCallback (timers.js:800:20)
6:03 PM
    at tryOnImmediate (timers.js:762:5)
6:03 PM
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

This `pickedHeight` variable is getting referenced before it's defined:

https://github.com/gatsbyjs/gatsby/blob/524ff171cd890b79ce9535d6dc10550c70365d33/packages/gatsby-source-contentful/src/extend-node-type.js#L138
https://github.com/gatsbyjs/gatsby/blob/524ff171cd890b79ce9535d6dc10550c70365d33/packages/gatsby-source-contentful/src/extend-node-type.js#L250

For reference, here's the source for the glitch project:

https://glitch.com/edit/#!/purple-cycle?path=gatsby-config.js:15:1

**Comment by KyleAMathews** [comment]
Thanks for reporting the issue! Would love a PR fixing this!
