### ISSUE TITLE
Tests failing on fresh clone of Gatsby repo.

### ISSUE THREAD

**Issue by TheFirstMe** [gatsbyjs/gatsby#21473]
## Description

I am looking to contribute and followed the steps shown [here](https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/#gatsby-repo-install-instructions). However, the `yarn test` command is failing with exit code 1.

### Steps to reproduce

- Fork the official gatsbyjs/gatsby repository.
- Clone your fork: `git clone --depth=1 https://github.com/<your-username>/gatsby.git`
- Set up repo and install dependencies: `yarn run bootstrap`
- Make sure tests are passing for you: `yarn test`

### Expected result

All tests should pass. 

### Actual result

Test exited with code 1.

```
Summary of all failing tests
 FAIL  packages/gatsby/cache-dir/__tests__/minimal-config.js (39.726s)
  ● Builds cache-dir with minimal config

    : Timeout - Async callback was not invoked within the 30000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 30000ms timeout specified by jest.setTimeout.Error:

      2 | const child = require(`child_process`)
      3 |
    > 4 | it(`Builds cache-dir with minimal config`, done => {
        | ^
      5 |   const args = [
      6 |     require.resolve(`@babel/cli/bin/babel.js`),
      7 |     path.join(__dirname, `..`),

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Object.it (packages/gatsby/cache-dir/__tests__/minimal-config.js:4:1)

 FAIL  packages/gatsby-plugin-sharp/src/__tests__/index.js (78.864s)
  ● gatsby-plugin-sharp › tracedSVG › runs on demand

    : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:

      486 |     })
      487 |
    > 488 |     it(`runs on demand`, async () => {
          |     ^
      489 |       const args = {
      490 |         maxWidth: 100,
      491 |         width: 100,

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.it (packages/gatsby-plugin-sharp/src/__tests__/index.js:488:5)
      at Suite.describe (packages/gatsby-plugin-sharp/src/__tests__/index.js:465:3)
      at Object.describe (packages/gatsby-plugin-sharp/src/__tests__/index.js:50:1)

  ● gatsby-plugin-sharp › duotone › fixed

    expect(received).toMatchSnapshot()

    Snapshot name: `gatsby-plugin-sharp duotone fixed 1`

    - Snapshot
    + Received

      Object {
        "aspectRatio": 1,
    -   "base64": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAAH6ji2bAAAACXBIWXMAAAPoAAAD6AG1e1JrAAABk0lEQVQ4y7VUy07DMBDsf9IDhcauaVM4IajUIuALOFRI/R24wB8AgkpInJKI9ME5zDi24rx5HjZKvOP17Hg2neh8nNjo8CGESGL7sbpwMvrlaepriF4J3dQLMlsXvzbVFCKHLJ3J8+5PRxqlF0OzleFLkSG7Xrp4faiyRaI/Lgs13QhNVB5uCUyUTDyUloidvkjezvyMEB8B4uZkqAHCiR44bYtCcecSirD5XQDmIGzVjOrEiJo4fhvY2jWTG3C6g/TLmZ+8VwEJekWy20+loUSzA5kDp15BKJmXhmD6Iqcjtep5eSArk0ZQPPpqPNAaWiBpbKt0pLgEU2xuIOewTh7rmFWFRH9/M78uaG8yNuox4oYbbrQEhaI4HKEh7mvfS2OE98WR0r6P26zj2ofW5rWowlzY2WduAQxZ14odmNZuMWA0h6wo5pplDxj+MrgnqDM3W32E/QYNxaxN2f7ztNx6qWUCOC3H+F/Y35EU2XCw3QkGhBrHX/WXLbwG4wewoAwMst84t/0jH4ZG36DFLv9m7E/1HjvIa/canAAAAABJRU5ErkJggg==",
    -   "height": 100,
    +   "base64": undefined,
    +   "density": 72,
    +   "originalImg": "/static/1234/7e516/test.png",
        "originalName": "test.png",
    -   "src": "/static/1234/df2e1/test.png",
    -   "srcSet": "/static/1234/df2e1/test.png 1x",
    -   "tracedSVG": undefined,
    -   "width": 100,
    +   "presentationHeight": 100,
    +   "presentationWidth": 100,
    +   "sizes": "(max-width: 100px) 100vw, 100px",
    +   "src": "/static/1234/7e516/test.png",
    +   "srcSet": "/static/1234/7991c/test.png 25w,
    + /static/1234/a1812/test.png 50w,
    + /static/1234/7e516/test.png 100w",
    +   "srcSetType": "image/png",
    +   "tracedSVG": "data:image/svg+xml,%3csvg%20xmlns='http://www.w3.org/2000/svg'%20width='100'%20height='100'%3e%3cpath%20d='M41%2024c-18%207-24%2029-11%2043%2015%2017%2044%208%2046-15%201-19-17-34-35-28'%20fill='red'%20fill-rule='evenodd'/%3e%3c/svg%3e",
      }

      507 |       })
      508 |
    > 509 |       expect(fluidSvg).toMatchSnapshot()
          |                        ^
      510 |     })
      511 |   })
      512 |

      at Object.toMatchSnapshot (packages/gatsby-plugin-sharp/src/__tests__/index.js:509:24)


Snapshot Summary
 › 1 snapshot written from 1 test suite.
 › 1 snapshot failed from 1 test suite. Inspect your code changes or run `yarn run jest -u` to update them.
 › 2 snapshots obsolete from 1 test suite. To remove them all, run `yarn run jest -u`.
   ↳ packages/gatsby-plugin-sharp/src/__tests__/index.js
       • gatsby-plugin-sharp duotone fluid 2
       • gatsby-plugin-sharp duotone fluid 3

Test Suites: 2 failed, 239 passed, 241 total
Tests:       3 failed, 29 skipped, 9 todo, 2339 passed, 2380 total
Snapshots:   1 failed, 2 obsolete, 1 written, 809 passed, 811 total
Time:        525.53s, estimated 624s
Ran all test suites.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "jest" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment

 ```
 System:
    OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 12.15.0 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.4 - /usr/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
```

**Comment by TheFirstMe** [comment]
I am not used to Jest. Is it ok to continue with this copy of the repo?

**Comment by LekoArts** [comment]
Thanks for the issue! Those tests are sometimes flaky, nothing to worry about :) You can continue, thanks for willing to contribute!

**Comment by TheFirstMe** [comment]
@LekoArts Thanks for the update!
