### ISSUE TITLE
cannot import latest gatsby@1

### ISSUE THREAD

**Issue by oprogramador** [gatsbyjs/gatsby#21531]
```
⟩ yarn add gatsby@1
yarn add v1.16.0
warning ../../../package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "gatsby-plugin-postcss-sass > sass-loader@4.1.1" has unmet peer dependency "webpack@^2 || ^2.2.0-rc.0 || ^2.1.0-beta || ^1.12.6".
warning "gatsby-plugin-postcss-sass > gatsby-1-config-extract-plugin > extract-text-webpack-plugin@1.0.1" has unmet peer dependency "webpack@^1.9.11".
warning "gatsby-transformer-remark > graphql-type-json@0.1.4" has unmet peer dependency "graphql@>=0.4.0".
warning " > react-helmet@5.2.1" has unmet peer dependency "react@>=15.0.0".
warning "react-helmet > react-side-effect@1.2.0" has unmet peer dependency "react@^0.13.0 || ^0.14.0 || ^15.0.0 || ^16.0.0".
warning "react-live > create-react-context@0.2.3" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning " > graphql-type-json@0.3.1" has unmet peer dependency "graphql@>=0.8.0".
warning "gatsby > friendly-errors-webpack-plugin@1.7.0" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning "gatsby > postcss-cssnext@2.11.0" has unmet peer dependency "caniuse-db@^1.0.30000652".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ gatsby@1.9.279
info All dependencies
└─ gatsby@1.9.279
✨  Done in 12.23s.

[oprogramador@MacBook-Pro-user-2.local 17:37:55] ~/open-source/project-1 (master ±)
⟩ node
> require('gatsby')
Thrown:
{ Error: Cannot find module 'gatsby'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18) code: 'MODULE_NOT_FOUND' }
> ⏎

[oprogramador@MacBook-Pro-user-2.local 17:38:16] ~/open-source/project-1 (master ±)
⟩ ls -la node_modules/gatsby
total 40
drwxr-xr-x     8 oprogramador  staff    256 Feb 17 17:25 .
drwxr-xr-x  1511 oprogramador  staff  48352 Feb 17 17:37 ..
-rw-r--r--     1 oprogramador  staff  10466 Jan 23 16:49 README.md
drwxr-xr-x     3 oprogramador  staff     96 Feb 17 17:18 __mocks__
drwxr-xr-x    22 oprogramador  staff    704 Feb 17 17:18 cache-dir
drwxr-xr-x    10 oprogramador  staff    320 Feb 17 17:18 dist
drwxr-xr-x     7 oprogramador  staff    224 Feb 17 17:37 node_modules
-rw-r--r--     1 oprogramador  staff   5020 Jan 23 16:49 package.json

[oprogramador@MacBook-Pro-user-2.local 17:38:22] ~/open-source/project-1 (master ±)
⟩ cat node_modules/gatsby/package.json | grep main
  "main": "index.js",
```

the main file specified in `package.json` is `index.js` but it doesn't exist

**Comment by pieh** [comment]
What are you trying to do? `gatsby@1` was not meant to imported. `gatsby@2` also doesn't support something like that in Node.js environment

**Comment by oprogramador** [comment]
@pieh 

in gatsby@2 there's `import { StaticQuery, graphql } from "gatsby"`

I use `graphql` from gatsby@1 as a global variable but I want to have an import instead

**Comment by pieh** [comment]
- There is `StaticQuery` in v1 
- The `graphql` in v2 doesn't trully exist - it gets compiled away, but we did this in v2 so people could import `graphql` from other packages and for it to not cause issues. See actual implementation of `graphql` export from `gatsby`:
  https://github.com/gatsbyjs/gatsby/blob/e0656b735331e9a8e7c93fcf59939cd864e11452/packages/gatsby/cache-dir/gatsby-browser-entry.js#L78-L85

So in v1 there is no way to make actual import. If you need this to get some linting setup pass - you should set - for example using `globals` in `eslint` ( https://eslint.org/docs/user-guide/configuring#specifying-globals )
