### ISSUE TITLE
[query-runner.js] Whenever a GraphQL query fails, query-runner exits with an unhandled rejection

### ISSUE THREAD

**Issue by moigonzalez** [gatsbyjs/gatsby#21730]
###  Description

Whenever I try to run `gatsby develop` or `gatsby build` on an application with a failing GraphQL query, query-runner.js fails with an unhandled rejection:

```
UNHANDLED REJECTION [
  '/es',
  TypeError: Cannot read property '0' of undefined
      at /Users/moigonzalez/flixbus/kingcron/gatsby-flixbus/node_modules/gatsby/dist/query/query-runner.js:63:60
      at Array.map (<anonymous>)
      at module.exports (/Users/moigonzalez/flixbus/kingcron/gatsby-flixbus/node_modules/gatsby/dist/query/query-runner.js:58:44)
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  { elapsed: 938 }
]
```

### Steps to reproduce

1. Make a page query to get data from GraphQL
2. Force an error to happen to this query (e.g. a typo, missing data)
3. Run gatsby develop
4. Check the log and find:

```
info bootstrap finished - 5.446 s
⠀

 ERROR 

UNHANDLED REJECTION [
  '/es',
  TypeError: Cannot read property '0' of undefined
      at .../node_modules/gatsby/dist/query/query-runner.js:63:60
      at Array.map (<anonymous>)
      at module.exports (.../node_modules/gatsby/dist/query/query-runner.js:58:44)
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  { elapsed: 938 }
]



  Error: [
    '/es',
    TypeError: Cannot read property '0' of undefined
  
  - query-runner.js:63 
    [gatsby-flixbus]/[gatsby]/dist/query/query-runner.js:63:60
  
  - Array.map
  
  - query-runner.js:58 module.exports
    [gatsby-flixbus]/[gatsby]/dist/query/query-runner.js:58:44
  
  
  - { elapsed: 938 }
  
  - ]
  
  - index.js:133 process.<anonymous>
    [gatsby-flixbus]/[gatsby]/[gatsby-cli]/lib/index.js:133:14
  
  - index.js:155 processEmit [as emit]
    [gatsby-flixbus]/[signal-exit]/index.js:155:32
  
  - promises.js:207 processPromiseRejections
    internal/process/promises.js:207:33
  
  - task_queues.js:98 processTicksAndRejections
    internal/process/task_queues.js:98:32
  

not finished run queries - 1.043s


———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
43 pages                                             In Progress                                             gatsby-starter-default
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-default@0.1.0 dev: `gatsby develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gatsby-starter-default@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     .../.npm/_logs/2020-02-25T13_51_31_827Z-debug.log
```

### Expected result

The logs should at least show me which query is failing and fail a bit more gracefully.

### Actual result

The build just dies with no relevant information on how to fix my query.

### Environment

```
  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.5.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.2
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.19.7 => 2.19.21
    gatsby-image: ^2.2.39 => 2.2.41
    gatsby-plugin-manifest: ^2.2.39 => 2.2.42
    gatsby-plugin-offline: ^3.0.32 => 3.0.35
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.22
    gatsby-plugin-sass: ^2.1.28 => 2.1.29
    gatsby-plugin-sharp: ^2.4.3 => 2.4.5
    gatsby-source-filesystem: ^2.1.46 => 2.1.48
    gatsby-source-graphql: ^2.1.33 => 2.1.33
    gatsby-transformer-sharp: ^2.3.13 => 2.3.14
  npmGlobalPackages:
    gatsby-cli: 2.8.30
```

**Comment by vladar** [comment]
Hi @moigonzalez !

Sorry to hear you're running into an issue. I tried reproducing it with the steps you outlined but couldn't. I tried adding both validation and runtime errors.

Always getting a valid error message:

<details>
  <summary>SHOW</summary>

```
 ERROR #85901  GRAPHQL                                                            
                                                                                  
There was an error in your GraphQL query:                                         
                                                                                  
Try to repro                                                                      
                                                                                  
   3 |     id                                                                     
   4 |     siteMetadata {                                                         
   5 |       title                                                                
   6 |     }                                                                      
   7 |   }                                                                        
   8 |   allMarkdownRemark(sort: {fields: [frontmatter___date], order: DESC}) {   
   9 |     edges {                                                                
  10 |       node {                                                               
  11 |         id                                                                 
  12 |         excerpt                                                            
> 13 |         err                                                                
     |         ^                                                                  
  14 |         fields {                                                           
  15 |           slug                                                             
  16 |         }                                                                  
  17 |         frontmatter {                                                      
  18 |           date(formatString: "MMMM DD, YYYY1")                             
  19 |           title                                                            
  20 |           description                                                      
  21 |         }                                                                  
  22 |       }                                                                    
  23 |     }                                                                      
                                                                                  
File path: C:/dev/tmp/gatsby-starter-blog/src/pages/index.js                      
Url path: /                                                                       
Plugin: none
```
</details>

I suspect that it may have something to do with your settings OR a specific error you raise. So I need some help from you to reproduce it.

It is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by moigonzalez** [comment]
Thank you so much for looking into this, looks like the error was coming from our GraphQL mishandling non-existing fields. 

I'm Loving Gatsby! Really appreciate your work on it 😄
