### ISSUE TITLE
Cannot read property 'getFileName' of undefined

### ISSUE THREAD

**Issue by zcserei** [gatsbyjs/gatsby#2240]
I am building a starter that uses [emotion](https://emotion.sh/) for styling, and I'm running into a problem whenever I try to build a project or start the development server.

I've published my (still admittedly and willingly barebones) project [here](https://github.com/Holistio/gatsby-emotional-starter).

I tried looking into the relevant files and could not find a solution, my error looks like the following:

` ~/development/ges-test-1  gatsby develop
success delete html files from previous builds — 0.011 s
success open and validate gatsby-config.js — 0.017 s
success copy gatsby files — 0.072 s
success source and transform nodes — 0.054 s
success building schema — 0.196 s
success createLayouts — 0.060 s
success createPages — 0.024 s
success createPagesStatefully — 0.014 s
success extract queries from components — 0.135 s
success run graphql queries — 0.049 s
success write out page data — 0.004 s
success update schema — 0.173 s

info bootstrap finished - 3.024 s

/Users/zcserei/development/ges-test-1/node_modules/gatsby/dist/reporter/prepare-stack-trace.js:31
  var source = map.sourceContentFor(topFrame.getFileName(), true);
                                            ^

TypeError: Cannot read property 'getFileName' of undefined
    at getErrorSource (/Users/zcserei/development/ges-test-1/node_modules/gatsby/dist/reporter/prepare-stack-trace.js:31:45)
    at prepareStackTrace (/Users/zcserei/development/ges-test-1/node_modules/gatsby/dist/reporter/prepare-stack-trace.js:24:21)
    at createErrorFromString (/Users/zcserei/development/ges-test-1/node_modules/gatsby/dist/reporter/errors.js:55:22)
    at /Users/zcserei/development/ges-test-1/node_modules/gatsby/dist/utils/develop-html.js:49:33
    at Compiler.<anonymous> (/Users/zcserei/development/ges-test-1/node_modules/webpack/lib/Compiler.js:194:14)
    at Compiler.emitRecords (/Users/zcserei/development/ges-test-1/node_modules/webpack/lib/Compiler.js:282:37)
    at Compiler.<anonymous> (/Users/zcserei/development/ges-test-1/node_modules/webpack/lib/Compiler.js:187:11)
    at /Users/zcserei/development/ges-test-1/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.applyPluginsAsync (/Users/zcserei/development/ges-test-1/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.afterEmit (/Users/zcserei/development/ges-test-1/node_modules/webpack/lib/Compiler.js:272:8)
    at Compiler.<anonymous> (/Users/zcserei/development/ges-test-1/node_modules/webpack/lib/Compiler.js:267:14)
    at /Users/zcserei/development/ges-test-1/node_modules/async/lib/async.js:52:16
    at done (/Users/zcserei/development/ges-test-1/node_modules/async/lib/async.js:246:17)
    at /Users/zcserei/development/ges-test-1/node_modules/async/lib/async.js:44:16
    at /Users/zcserei/development/ges-test-1/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:112:15)`

I feel like I haven't done anything that isn't obvious, and to be honest, I have no idea what triggers the error.

**Comment by KyleAMathews** [comment]
You're running an older version of Gatsby which is failing when trying to generate the error messege.

I ran `yarn upgrade-interactive` and it gave a proper error message.

**Comment by KyleAMathews** [comment]
Things change quickly so best to stay on latest if can.
