### ISSUE TITLE
@link field extension returns null when destination field has @proxy

### ISSUE THREAD

**Issue by codyml** [gatsbyjs/gatsby#22481]
## Description

I'm writing a schema that looks like this:
```graphql
type Transfer implements Node @dontInfer {
  transferId: ID! @proxy(from: "transfer-id")
}

type Client implements Node @dontInfer {
  clientId: ID! @proxy(from: "client-id")
  transfers: [Transfer]
    @proxy(from: "client-transfers")
    @split(by: "|")
    @link(by: "transferId")
}
```
I'm sourcing data from CSVs and I don't have control over the column header names, hence the `@proxy`s everywhere.  For `Client.transfers`, I wrote a custom extension `@split` that does `String.prototype.split` on the pipe-delimited transfer IDs that it proxies from the source `client-transfers` field.  I was hoping that I could then use the resultant array to link to `Transfer` nodes.  However, a query for `Client.transfers` returns an array of `null`.

The number of `null`s in the returned array matches up with the number of valid client IDs that should be being linked, which made me think that it was mostly working, and when I stuck a console log after [schema/resolvers.js:170](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/resolvers.js#L170), I get the correct nodes logged.  From what I can tell, the `runQuery` call to find the nodes is going all the way with resolving fields when searching for them (`transfer-id` to `transferId` in my case), but the [`map` call on 176](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/resolvers.js#L176) is then returning `null` in their place because it's only looking for the `by` field in the node source fields, and for fields that are proxied like in my case it's not there.

### Steps to reproduce

Here's a codesandbox with it as isolated as I could get it: https://codesandbox.io/s/gallant-dhawan-94bqj

### Expected result

Not sure what change it would require or if it would be possible but it would be great if `@link`ing by `@proxy` fields worked, since it seems so close to working already.  I'm not at all familiar with Gatsby's internals so excuse any dumb questions but is there some way to make that last `map` able to access resolved fields?  I was really excited that it could get me even this far though; either way the project is great to use and thanks so much!

### Actual result

Described above.  Sidenote: if I change the `@link`ed field to the un-proxied one (`transfer-id`), I get
```
TypeError: Cannot read property 'type' of undefined
            at /Users/cml/src/lgu-app/node_modules/gatsby/dist/schema/node-model.js:564:48
            at Array.forEach (<anonymous>)
            at determineResolvableFields (/Users/cml/src/lgu-app/node_modules/gatsby/dist/schema/node-model.js:561:23)
            at LocalNodeModel.runQuery (/Users/cml/src/lgu-app/node_modules/gatsby/dist/schema/node-model.js:190:29)
            at ContextualNodeModel.runQuery (/Users/cml/src/lgu-app/node_modules/gatsby/dist/schema/node-model.js:405:27)
            at /Users/cml/src/lgu-app/node_modules/gatsby/dist/schema/resolvers.js:187:42
            at processTicksAndRejections (internal/process/task_queues.js:97:5)
            at async Promise.all (index 2)
            at async Promise.all (index 0)
            at async Promise.all (index 0)
            at async Promise.all (index 0)
```
...I think because I don't have the un-proxied one in my schema.

### Environment

```
  System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.10.1 - /usr/local/bin/node
    npm: 6.13.7 - /usr/local/bin/npm
  Languages:
    Python: 3.7.6 - /usr/local/opt/python/libexec/bin/python
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 74.0
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.19.21 => 2.19.21 
    gatsby-alias-imports: ^1.0.4 => 1.0.4 
    gatsby-image: ^2.2.43 => 2.3.0 
    gatsby-plugin-catch-links: ^2.1.27 => 2.2.0 
    gatsby-plugin-create-client-paths: ^2.1.23 => 2.2.0 
    gatsby-plugin-mdx: ^1.0.82 => 1.1.0 
    gatsby-plugin-postcss: ^2.1.21 => 2.2.0 
    gatsby-plugin-react-helmet: ^3.1.23 => 3.2.0 
    gatsby-plugin-remove-trailing-slashes: ^2.1.23 => 2.2.0 
    gatsby-plugin-sass: ^2.1.30 => 2.2.0 
    gatsby-plugin-sharp: ^2.4.12 => 2.5.1 
    gatsby-source-filesystem: ^2.1.55 => 2.2.1 
    gatsby-transformer-sharp: ^2.3.18 => 2.4.1 
    gatsby-transformer-yaml: ^2.2.26 => 2.3.0 
```

**Comment by codyml** [comment]
Update: I'm sure this is ill-advised but copying the `link` resolver into my own code with the following change at [`resolvers.js`:177](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/resolvers.js#L177) from
```js
result.find(obj => getValueAt(obj, options.by) === value)
```
to
```js
result.find(obj => getValueAt(obj, options.by) === value || getValueAt(obj, `__gatsby_resolved.${options.by}`) === value)
```
got it working for now for my specific case.
