### ISSUE TITLE
Are dynamic imports supported by default?

### ISSUE THREAD

**Issue by fpoumian** [gatsbyjs/gatsby#2252]
Hi,
I'm trying to leverage [React Loadable](https://github.com/thejameskyle/react-loadable) in order to dynamically import (using the import keyword) a set of components inside one of my Template Components, however, I'm getting an error at compilation time:
```

ERROR  Failed to compile with 1 errors12:53:17 PM

 error  in ./src/templates/IconPage.js

Module parse failed: /media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/babel-loader/lib/index.js?{"plugins":["/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/gatsby/dist/utils/babel-plugin-extract-graphql.js","/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/react-hot-loader/babel.js","/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/babel-plugin-transform-react-jsx-source/lib/index.js","/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/babel-plugin-add-module-exports/lib/index.js","/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/babel-plugin-transform-object-assign/lib/index.js"],"presets":[["/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/babel-preset-env/lib/index.js",{"loose":true,"uglify":true,"modules":"commonjs","targets":{"browsers":["> 1%","last 2 versions","IE >= 9"]},"exclude":["transform-regenerator","transform-es2015-typeof-symbol"]}],"/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/babel-preset-stage-0/lib/index.js","/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/babel-preset-react/lib/index.js"],"cacheDirectory":true}!/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/src/templates/IconPage.js Unexpected token (54:17)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (54:17)
    at Parser.pp$4.raise (/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseReturnStatement (/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/acorn/dist/acorn.js:839:33)
    at Parser.pp$1.parseStatement (/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/acorn/dist/acorn.js:699:34)
    at Parser.pp$1.parseBlock (/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$3.parseFunctionBody (/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/acorn/dist/acorn.js:2105:24)
    at Parser.pp$1.parseFunction (/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/acorn/dist/acorn.js:1065:10)
    at Parser.pp$3.parseExprAtom (/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/acorn/dist/acorn.js:1810:19)
    at Parser.pp$3.parseExprSubscripts (/media/fpoumian/seagate_dev/code/javascript/WebStormProjects/iconsproject/docs/node_modules/acorn/dist/acorn.js:1715:21)

 @ ./.cache/sync-requires.js 12:58-174
```

I also tried using the dynamic import keyword by itself (without React Loadable) and I get the same error. Is the dynamic import keyword not supported yet in Gatsby? Is there any additional webpack/babel plugin that I have to install?

Thanks in advance.

**Comment by KyleAMathews** [comment]
We're on webpack 1 still. The coming Gatsby v2 will bump us to webpack 3. For now you have to use `require.ensure`.

**Comment by fpoumian** [comment]
Ok thanks!

**Comment by creimers** [comment]
@fpoumian Do you happen to have an example of how you got it to work with react-loadable and require.ensure?

**Comment by creimers** [comment]
@fpoumian Never mind, I figured it out. I'm posting my solution here, maybe it'll be usefull for someone else:

```javascript
const loader = () => {
  const promise = new Promise((resolve, reject) => {
    require.ensure([], () => {
      const slider = require('./Slider');
      resolve(slider);
    })
  })
  return promise
}

const LoadableSlider = Loadable({
  loader: loader,
  loading: <div>Loading...</div>
});

```
