### ISSUE TITLE
Cannot find module '../features'

### ISSUE THREAD

**Issue by jhanstra** [gatsbyjs/gatsby#228]
Upgrading to 0.9.0 and getting this error when trying to run `gatsby develop`. Not exactly sure what it means, where it's coming from, or how to fix it.

I saw that 0.9.0 uses a local instance of gatsby instead of global. I uninstalled the global instance but then had no way to run `gatsby develop` command.

Apologies if this is a simple or unrelated issue.
```
jh-gatsby $ gatsby develop
module.js:340
    throw err;
    ^

Error: Cannot find module '../features'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:289:25)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/Users/jhanstra/projects/jh-gatsby/node_modules/caniuse-api/dist/index.js:19:32)
  at Module._compile (module.js:425:26)
  at Module._extensions..js (module.js:432:10)
  at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/gatsby/node_modules/babel-register/lib/node.js:134:7)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/Users/jhanstra/projects/jh-gatsby/node_modules/postcss-cssnext/lib/index.js:11:19)
  at Module._compile (module.js:425:26)
  at Module._extensions..js (module.js:432:10)
  at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/gatsby/node_modules/babel-register/lib/node.js:134:7)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at module (/Users/jhanstra/projects/jh-gatsby/node_modules/gatsby/dist/utils/webpack.config.js:233:50)
  at module.exports (/Users/jhanstra/projects/jh-gatsby/node_modules/gatsby/dist/utils/webpack.config.js:308:12)
  at /Users/jhanstra/projects/jh-gatsby/node_modules/gatsby/dist/utils/develop.js:62:48
  at /Users/jhanstra/projects/jh-gatsby/node_modules/gatsby/dist/utils/glob-pages.js:135:12
  at f (/Users/jhanstra/projects/jh-gatsby/node_modules/once/once.js:17:25)
  at Glob.<anonymous> (/Users/jhanstra/projects/jh-gatsby/node_modules/glob/glob.js:146:7)
  at emitOne (events.js:77:13)
  at Glob.emit (events.js:169:7)
  at Glob._finish (/Users/jhanstra/projects/jh-gatsby/node_modules/glob/glob.js:194:8)
  at done (/Users/jhanstra/projects/jh-gatsby/node_modules/glob/glob.js:179:14)
  at Glob._processGlobStar2 (/Users/jhanstra/projects/jh-gatsby/node_modules/glob/glob.js:631:12)
  at /Users/jhanstra/projects/jh-gatsby/node_modules/glob/glob.js:620:10
  at RES (/Users/jhanstra/projects/jh-gatsby/node_modules/inflight/inflight.js:23:14)
  at f (/Users/jhanstra/projects/jh-gatsby/node_modules/once/once.js:17:25)
  at lstatcb_ (/Users/jhanstra/projects/jh-gatsby/node_modules/glob/glob.js:513:7)
  at RES (/Users/jhanstra/projects/jh-gatsby/node_modules/inflight/inflight.js:23:14)
  at f (/Users/jhanstra/projects/jh-gatsby/node_modules/once/once.js:17:25)
  at FSReqWrap.oncomplete (fs.js:82:15)
```

Other details:
Gatsby version: 0.9.0
Node version: 5.1.0
OS: Mac 10.10.3
`gatsby-node.js` and `gatsby-browser.js` are empty/nonexistent.
`package.json`:
```
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "babel-plugin-add-module-exports": "^0.1.2",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-1": "^6.5.0",
    "front-matter": "^2.0.6",
    "gatsby": "^0.9.0",
    "highlight.js": "^9.2.0",
    "history": "^2.0.1",
    "js-yaml": "^3.5.5",
    "markdown-it": "^6.0.0",
    "markdown-it-abbr": "^1.0.3",
    "markdown-it-attrs": "^0.1.8",
    "markdown-it-deflist": "^2.0.1",
    "markdown-it-footnote": "^2.0.0",
    "markdown-it-sub": "^1.0.0",
    "object-assign": "^4.0.1",
    "react-document-title": "^2.0.1",
    "react-headroom": "^1.8.0",
    "react-responsive-grid": "^0.3.0",
    "react-router": "^2.0.1",
    "toml-js": "0.0.8",
    "typography": "^0.7.0"
  },
  "devDependencies": {
    "babel-preset-react-hmre": "^1.1.1",
    "eslint": "^2.4.0",
    "eslint-config-airbnb": "^6.1.0",
    "eslint-plugin-react": "^4.2.1",
    "gatsby": "^0.9.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "scripts": {
    "lint": "./node_modules/.bin/eslint --ext .js,.jsx --ignore-pattern public .",
    "test": "echo \"Error: no test specified\" && exit 1"
  }
}
```

**Comment by jhanstra** [comment]
Ahh, ignore. Deleting the `node_modules` folder and re-`npm install`ing seems to fix whatever was going on.

**Comment by KyleAMathews** [comment]
Ah the good ol' turn it off and on again trick :-)
