### ISSUE TITLE
[gatsby-source-wordpress] wp.com auth error

### ISSUE THREAD

**Issue by arthurpark** [gatsbyjs/gatsby#2280]
Gatsby version: 1.9.44
node.js version: 8.5.0
OS version: maxOS Sierra 10.12.6 (16G29)
gatsby-source-wordpress version: 2.0.7

I'm trying to use wp.com as backend, but getting an error. I tried to search existing issue but there doesn't seem to be one, and there isn't much example using wp.com so creating this issue.

```
success delete html files from previous builds — 0.005 s
success open and validate gatsby-config.js — 0.003 s
success copy gatsby files — 0.015 s
error Plugin gatsby-source-wordpress returned an error


  TypeError: Cannot read property 'status' of undefined

  - http-exception-handler.js:13 httpExceptionHandler
    [jccc-gatsby]/[gatsby-source-wordpress]/http-exception-handler.js:13:25

  - fetch.js:253 _callee2$
    [jccc-gatsby]/[gatsby-source-wordpress]/fetch.js:253:13

  - Promise

  - fetch.js:267 getWPCOMAccessToken
    [jccc-gatsby]/[gatsby-source-wordpress]/fetch.js:267:18

  - fetch.js:50 _callee$
    [jccc-gatsby]/[gatsby-source-wordpress]/fetch.js:50:20


success source and transform nodes — 0.046 s
success building schema — 0.082 s
success createLayouts — 0.022 s
⠁ [ { GraphQLError: Cannot query field "allWordpressPage" on type "RootQueryType". Did you mean "allSitePage"?
      at Object.Field (/Users/arthurpark/projects/jccc-gatsby/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:66:31)
...truncated
```

I digged little bit and added a log
```
$ gatsby develop
success delete html files from previous builds — 0.006 s
success open and validate gatsby-config.js — 0.004 s
success copy gatsby files — 0.015 s
⠁ ReferenceError: _auth is not defined
    at _callee2$ (/Users/arthurpark/projects/jccc-gatsby/node_modules/gatsby-source-wordpress/fetch.js:232:32)
    at tryCatch (/Users/arthurpark/projects/jccc-gatsby/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/arthurpark/projects/jccc-gatsby/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/arthurpark/projects/jccc-gatsby/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/arthurpark/projects/jccc-gatsby/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/arthurpark/projects/jccc-gatsby/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise (<anonymous>)
    at F (/Users/arthurpark/projects/jccc-gatsby/node_modules/core-js/library/modules/_export.js:35:28)
    at /Users/arthurpark/projects/jccc-gatsby/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at getWPCOMAccessToken (/Users/arthurpark/projects/jccc-gatsby/node_modules/gatsby-source-wordpress/fetch.js:267:18)
    at _callee$ (/Users/arthurpark/projects/jccc-gatsby/node_modules/gatsby-source-wordpress/fetch.js:50:20)
    at tryCatch (/Users/arthurpark/projects/jccc-gatsby/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/arthurpark/projects/jccc-gatsby/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/arthurpark/projects/jccc-gatsby/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/arthurpark/projects/jccc-gatsby/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/arthurpark/projects/jccc-gatsby/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
error Plugin gatsby-source-wordpress returned an error
...truncated
```

The culprit seems to be  `ReferenceError: _auth is not defined` and I think I nailed to
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/fetch.js#L160 
where `_auth` is not defined under `getWPCOMAccessToken` function scope.

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/fetch.js#L29

and here
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/fetch.js#L152

Looks like this could be a simple fix, but before making a PR, just wanted to make sure that this wasn't worked by anyone.

Thanks.

**Comment by KyleAMathews** [comment]
Don't think anyone else is actively using this with wordpress.com so would love you helping maintain it!

**Comment by arthurpark** [comment]
Thanks for quick response!

**Comment by KyleAMathews** [comment]
You too :-)
