### ISSUE TITLE
Fetching SilverStripe data failed Cannot read property 'data' of undefined 

### ISSUE THREAD

**Issue by queenpp** [gatsbyjs/gatsby#22995]
Hi team,

I was able to access __gatsby/graphql and use graphiql and my silverstripe site was working fine too.
when running"gatsby develop", the following errors came up:
success open and validate gatsby-configs - 0.079s
success load plugins - 1.422s
success onPreInit - 0.005s
success initialize cache - 0.015s
success copy gatsby files - 0.146s
success onPreBootstrap - 0.025s
success createSchemaCustomization - 0.018s
Starting to fetch data from SilverStripe
query:
  query {
    sync {
      summary {
        total
        includedClasses {
          className
          shortName
          fields
        }
      }
    }
  }

variables: {}
FetchError: invalid json response body at http://localhost:8888/gatsby-project/__gatsby/graphql reason: Unexpected token < in JSON at position 0
    at /Applications/MAMP/htdocs/gatsby-project/node_modules/isomorphic-fetch/node_modules/node-fetch/lib/body.js:48:31
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async executeQuery (/Applications/MAMP/htdocs/gatsby-project/node_modules/gatsby-source-silverstripe/src/fetch/executeQuery.js:15:18)
    at async fetchSummaryData (/Applications/MAMP/htdocs/gatsby-project/node_modules/gatsby-source-silverstripe/src/fetch/fetchSummaryData.js:5:16)
    at async fetchDataObjects (/Applications/MAMP/htdocs/gatsby-project/node_modules/gatsby-source-silverstripe/src/fetch/fetchDataObjects.js:26:21)
    at async buildDataObjects (/Applications/MAMP/htdocs/gatsby-project/node_modules/gatsby-source-silverstripe/src/build/buildDataObjects.js:31:16)
    at async Object.handleSourceNodes [as sourceNodes] (/Applications/MAMP/htdocs/gatsby-project/node_modules/gatsby-source-silverstripe/src/build/handleSourceNodes.js:6:3) {
  name: 'FetchError',
  message: 'invalid json response body at ' +
    'http://localhost:8888/gatsby-project/__gatsby/graphql reason: ' +
    'Unexpected token < in JSON at position 0',
  type: 'invalid-json'
}

Am i missing a step?
any advice would be much appreciated!

**Comment by LekoArts** [comment]
Thank you for opening this!

We're not maintaining `gatsby-source-silverstripe` so I'd suggest opening an issue on their repository: https://github.com/silverstripe/gatsby-source-silverstripe

Please give them a reproduction of your problem so that they can help you.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
