### ISSUE TITLE
Cannot find module 'cors' in gatsby recipes

### ISSUE THREAD

**Issue by Defite** [gatsbyjs/gatsby#23243]
## Description

After typing `gatsby recipes` I've got the error `Cannot find module 'cors'`.

### Steps to reproduce

1. `mkdir somedir`
2. `npm install -g gatsby-cli@latest`
3. `cd somedir && npm install gatsby@latest`
4. `gatsby recipes`

### Expected result

I should see the list of the recipes.

### Actual result

I got an error:

```
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'cors'
Require stack:
- /usr/local/lib/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/graphql.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/graphql.js:33:14)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/graphql.js'
  ]
}


 ERROR

Command failed with exit code 1: node /usr/local/lib/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/graphql.js 4000



  Error: Command failed with exit code 1: node /usr/local/lib/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/graphq  l.js 4000

  - error.js:56 makeError
    [lib]/[gatsby-cli]/[execa]/lib/error.js:56:11

  - index.js:114 handlePromise
    [lib]/[gatsby-cli]/[execa]/index.js:114:26

  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5
```

### Environment

```

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.113
    Firefox: 74.0.1
    Safari: 13.1
  npmGlobalPackages:
    gatsby-cli: 2.11.10
```

**Comment by LekoArts** [comment]
Please stick to the umbrella issue: https://github.com/gatsbyjs/gatsby/issues/22991

Thanks!
