### ISSUE TITLE
maintenance(www): unit tests: "Not implemented: navigation (except hash changes)"

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#23326]
## Description

The following message prints out several times when running tests on `www`:

```
Error: Not implemented: navigation (except hash changes)
          at module.exports (/Users/tesseralis/Code/gatsby/www/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
          at navigateFetch (/Users/tesseralis/Code/gatsby/www/node_modules/jsdom/lib/jsdom/living/window/navigation.js:77:3)
          at exports.navigate (/Users/tesseralis/Code/gatsby/www/node_modules/jsdom/lib/jsdom/living/window/navigation.js:55:3)
          at Timeout._onTimeout (/Users/tesseralis/Code/gatsby/www/node_modules/jsdom/lib/jsdom/living/nodes/HTMLHyperlinkElementUtils-impl.js:81:7)
          at listOnTimeout (internal/timers.js:549:17)
          at processTimers (internal/timers.js:492:7) undefined
```

The tests still pass, but this pollutes the logs and makes it hard to differentiate between actual errors.

### Context

This seems to be [an issue with JSDOM](https://github.com/jsdom/jsdom/issues/2112), as it doesn't implement navigation. There are several solutions proposed in the thread, but since (I'm assuming) the cause of the error is Gatsby's Link (which is a rapper on Reach Router), I'm not sure the best way to fix it.

## Repro

1. `cd www`
2. `yarn test`

**Comment by copperwall** [comment]
I'm up to look into this, if that's cool

**Comment by AhmedBHameed** [comment]
Any solution to this issue?
