### ISSUE TITLE
Error: Cannot find module 'babel-code-frame'

### ISSUE THREAD

**Issue by johnrackles** [gatsbyjs/gatsby#2333]
gatsby-cli Version: gatsby-cli@1.2.0-alpha.d6b7680b
Node Version: v8.6.0
macOS Version: 10.12.6

When trying to use the latest gatsby-cli, I get the following error:
```bash
$ gatsby
```
produces the following output

```bash
module.js:529
    throw err;
    ^

Error: Cannot find module 'babel-code-frame'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby-cli/lib/reporter/prepare-stack-trace.js:10:22)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by jquense** [comment]
o wonderful the dist tag is wrong there...let me fix this real quick so latest doesn't point here

**Comment by jquense** [comment]
should be fixed, reinstall gatsby-cli and it should give you v1.1.7
