### ISSUE TITLE
gatsby build: pagesTypeError: Cannot read property '_preactCompatRendered' of undefined

### ISSUE THREAD

**Issue by samuelstubbs** [gatsbyjs/gatsby#2346]
having trouble tracking down the issue. can anyone suggest any good tricks for debugging Gatsby?

`TypeError: Cannot read property '_preactCompatRendered' of undefined
    at Object.unmountComponentAtNode (render-page.js:456:27)
    at Template.removePage (render-page.js:34609:26)
    at new Template (render-page.js:34597:12)
    at renderToString (render-page.js:1709:14)
    at renderToString (render-page.js:1797:16)
    at renderToString (render-page.js:1722:12)
    at renderToString (render-page.js:1797:16)
    at renderToString (render-page.js:1797:16)
    at renderToString (render-page.js:1722:12)
    at renderToString (render-page.js:1722:12)
`

**Comment by markmichon** [comment]
@samuelstubbs Does the build work if you disable the preact plugin?

**Comment by samuelstubbs** [comment]
I did, the issue turned out to be an issue with the SASS compiler.
