### ISSUE TITLE
`yarn run bootstrap` on fresh fork of Gatsby monorepo fails

### ISSUE THREAD

**Issue by lukebennett88** [gatsbyjs/gatsby#23670]
## Description

I've just created a fork of the Gatsby repo and am [following the instructions on getting started](https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/).

However when I run `yarn run bootstrap` it fails.

### Steps to reproduce

This is a fresh fork of the repo, I haven't done anything to it.
I created the repo by running: `git clone --depth=1 https://github.com/lukebennett88/gatsby.git`

### Expected result

Bootstrap should not fail.

### Actual result

Here is a dump of my console after running `yarn run bootstrap`:
```
yarn run bootstrap
yarn run v1.21.0
$ yarn
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ npm-run-all -s check-versions "lerna-prepare -- --{@}" --
$ babel-node scripts/check-versions.js
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ lerna run prepare --
lerna notice cli v3.20.2
lerna ERR! yarn run prepare exited 1 in 'gatsby-plugin-catch-links'
lerna ERR! yarn run prepare stdout:
$ cross-env NODE_ENV=production npm run build

> gatsby-plugin-catch-links@2.3.0 build /Users/luke/Sites/Playground/gatsby/packages/gatsby-plugin-catch-links
> babel src --out-dir . --ignore "**/__tests__"

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run prepare stderr:
{ Error: [BABEL] /Users/luke/Sites/Playground/gatsby/packages/gatsby-plugin-catch-links/src/catch-links.js: ENFILE: file table overflow, open '/Users/luke/Sites/Playground/gatsby/node_modules/babel-plugin-dynamic-import-node/utils.js'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:20)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/luke/Sites/Playground/gatsby/node_modules/@babel/plugin-transform-modules-amd/lib/index.js:14:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
  errno: -23,
  syscall: 'open',
  code: 'ENFILE',
  path:
   '/Users/luke/Sites/Playground/gatsby/node_modules/babel-plugin-dynamic-import-node/utils.js' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-plugin-catch-links@2.3.0 build: `babel src --out-dir . --ignore "**/__tests__"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gatsby-plugin-catch-links@2.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/luke/.npm/_logs/2020-05-01T11_58_52_313Z-debug.log
error Command failed with exit code 1.

lerna ERR! yarn run prepare exited 1 in 'gatsby-plugin-catch-links'
lerna WARN complete Waiting for 12 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "lerna-prepare -- --" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment

```
  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.1.0 - /usr/local/bin/fish
  Binaries:
    Node: 10.20.1 - ~/.config/nvm/10.20.1/bin/node
    Yarn: 1.21.0 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.config/nvm/10.20.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.129
    Safari: 13.1
```

**Comment by marcysutton** [comment]
Hi @lukebennett88, can you confirm whether this issue is still happening? It looks specific to Yarn: https://github.com/yarnpkg/yarn/issues/2432

**Comment by lukebennett88** [comment]
Thanks @marcysutton, I think you're right! 
I just cloned the repo again and ran `yarn run bootstrap` and everything installed correctly this time.

**Comment by wardpeet** [comment]
Thank you for opening this, @lukebennett88

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
