### ISSUE TITLE
[gatsby-plugin-mdx]: v1.2.4 causes multiple errors ("warn Query takes too long", "window is not defined", "Error querying the `html` field")

### ISSUE THREAD

**Issue by peter-mouland** [gatsbyjs/gatsby#23714]
## Description

Upgrading from v1.2.1 to v1.2.4 now causes a number of errors:

```sh
warn Query takes too long:
File path: /Users/petermouland/dev/clearscore/global-website.ssg/src/templates/learn-articles.js
URL path: /webview/learn/managing-money/balance-transfer-card-or-personal-loan-which-is-best-for-you
Context: {
    "slug": "/learn/managing-money/balance-transfer-card-or-personal-loan-which-is-best-for-you",
    "locale": "en-gb",
    "market": "gb",
    "heroFileName": "20fa1d677b40338c7e351b860282bf61-heroImage",
    "authorFileName": "8bf973f2a45212f8faa95f6be8563b6a-authorImage",
    "isWebView": true
}
Error parsing bundle asset "/Users/petermouland/dev/clearscore/global-website.ssg/public/0.output.js": no such file
Error parsing bundle asset "/Users/petermouland/dev/clearscore/global-website.ssg/public/1.output.js": no such file
Error parsing bundle asset "/Users/petermouland/dev/clearscore/global-website.ssg/public/output.js": no such file


```

```
 ERROR

gatsby-plugin-mdx: Error querying the `html` field.
        This field is intended for use with RSS feed generation.
        If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
        Original error:
        Error: renderMdxBody was unavailable when rendering html.

```

```

 ERROR

gatsby-plugin-mdx
ReferenceError: window is not defined
    at evalmachine.<anonymous>:1:1
    at Script.runInContext (vm.js:127:20)
    at Script.runInNewContext (vm.js:133:17)
    at module.exports (/Users/petermouland/dev/clearscore/global-website.ssg/node_modules/eval/eval.js:73:12)
    at afterEmit (/Users/petermouland/dev/clearscore/global-website.ssg/node_modules/gatsby-plugin-mdx/utils/render-html.js:81:22)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/petermouland/dev/clearscore/global-website.ssg/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/petermouland/dev/clearscore/global-website.ssg/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/petermouland/dev/clearscore/global-website.ssg/node_modules/webpack/lib/Compiler.js:482:27
    at /Users/petermouland/dev/clearscore/global-website.ssg/node_modules/neo-async/async.js:2818:7
    at done (/Users/petermouland/dev/clearscore/global-website.ssg/node_modules/neo-async/async.js:3522:9)


```

_reverting back to v1.2.1 fixes these errors_

### Steps to reproduce

My data source uses the gatsby-plugin-mdx and @mdx-js plugins :
 - "@mdx-js/mdx": "1.6.1",
 - "@mdx-js/utils": "1.6.1",
 - "@mdx-js/react": "1.6.1",
 - "@mdx-js/runtime": "1.6.1",

I am using mdx to query the **body** (not html) and wordCounts:

```graphql
    learnArticle(slug: { eq: $slug }, locale: { eq: $locale }) {
            childMdx {
                timeToRead
                wordCount {
                    words
                }
                tableOfContents
                body
            }
            ...
    }
```

The data-source is a private db instance, but will try to come up with something to help you debug

### Expected result

standard output and a build that completes without errors

### Actual result

a build that does not complete

### Environment

```

  System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 74.0
    Safari: 13.1
  npmPackages:
    gatsby: 2.21.9 => 2.21.9
    gatsby-link: 2.4.0 => 2.4.0
    gatsby-plugin-html-attributes: 1.0.5 => 1.0.5
    gatsby-plugin-manifest: 2.4.1 => 2.4.1
    gatsby-plugin-mdx: 1.2.4 => 1.2.4
    gatsby-plugin-react-helmet: 3.3.0 => 3.3.0
    gatsby-plugin-react-svg: 3.0.0 => 3.0.0
    gatsby-plugin-s3: 0.3.3 => 0.3.3
    gatsby-plugin-sharp: 2.6.0 => 2.6.0
    gatsby-plugin-svgr: 2.0.2 => 2.0.2
    gatsby-plugin-webpack-bundle-analyser-v2: 1.1.9 => 1.1.9
    gatsby-source-filesystem: 2.3.0 => 2.3.0
    gatsby-transformer-sharp: 2.5.0 => 2.5.0
```

**Comment by BrunoScheufler** [comment]
The same happens for me as well,

```
gatsby-plugin-mdx: Error querying the `html` field.
        This field is intended for use with RSS feed generation.
        If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
        Original error:
        Error: renderMdxBody was unavailable when rendering html
```

using

```
gatsby-plugin-mdx@^1.0.46:
  version "1.2.4"
  resolved "https://registry.yarnpkg.com/gatsby-plugin-mdx/-/gatsby-plugin-mdx-1.2.4.tgz#1c3631228c43e33a120fb603f90dc4641202c1cf"
```

**Comment by wardpeet** [comment]
We reverted the change and everything should be back to normal when using
- gatsby-plugin-mdx@1.2.5
- gatsby-transformer-remark@2.8.5
