### ISSUE TITLE
gatsby-plugin-mdx fails with 2 errors: "ReferenceError: window is not defined" and "Error querying the `html` field", when graphql `timeToRead` field is queried

### ISSUE THREAD

**Issue by calebpitan** [gatsbyjs/gatsby#23756]
## Description

gatsby-plugin-mdx fails with 2 errors: "ReferenceError: window is not defined" and "Error querying the `html` field", when graphql `timeToRead` field is queried, on `gatsby build` command. The error is remedied when the `timeToRead` field is removed from the query.

### Steps to reproduce
Below is the query in my post-layout.js component
```js
export const pageQuery = graphql`
  query BlogPostQuery($id: String) {
    mdx(id: { eq: $id }) {
      id
      body
      timeToRead
      tableOfContents
      parent {
        ... on File {
          id
          name
          mtf: modifiedTime(formatString: "MMM DD, YYYY")
          mtd: modifiedTime(fromNow: true)
        }
      }
    }
`
```

### Expected result

This field is meant to return a digit like `1` or `2` or `5`

### Actual result

```
 ERROR

gatsby-plugin-mdx
ReferenceError: window is not defined
    at evalmachine.<anonymous>:1:1
    at Script.runInContext (vm.js:131:20)
    at Script.runInNewContext (vm.js:137:17)
    at module.exports (C:\Caleb\eaveswall\node_modules\eval\eval.js:73:12)
    at afterEmit (C:\Caleb\eaveswall\node_modules\gatsby-plugin-mdx\utils\render-html.js:81:22)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Caleb\eaveswall\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:18:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Caleb\eaveswall\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Caleb\eaveswall\node_modules\webpack\lib\Compiler.js:482:27
    at C:\Caleb\eaveswall\node_modules\neo-async\async.js:2818:7
    at done (C:\Caleb\eaveswall\node_modules\neo-async\async.js:3522:9)


 ERROR

gatsby-plugin-mdx: Error querying the `html` field.
        This field is intended for use with RSS feed generation.
        If you're trying to use it in application-level code, try querying for `Mdx.body` instead.
        Original error:
        Error: renderMdxBody was unavailable when rendering html.
```

### Environment

```
  System:
    OS: Windows 10 10.0.15063
    CPU: (4) x64 Intel(R) Core(TM) i3-2330M CPU @ 2.20GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.7
  Browsers:
    Edge: 40.15063.0.0
  npmPackages:
    gatsby: ^2.21.9 => 2.21.9 
    gatsby-image: ^2.4.0 => 2.4.0 
    gatsby-plugin-algolia: ^0.6.0 => 0.6.0 
    gatsby-plugin-google-analytics: ^2.3.0 => 2.3.0 
    gatsby-plugin-manifest: ^2.4.1 => 2.4.1 
    gatsby-plugin-mdx: ^1.2.4 => 1.2.4 
    gatsby-plugin-offline: ^3.2.0 => 3.2.0 
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3 
    gatsby-plugin-react-css-modules: ^2.1.21 => 2.3.0 
    gatsby-plugin-react-helmet: ^3.3.0 => 3.3.0 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-sass: ^2.1.30 => 2.3.0 
    gatsby-plugin-sharp: ^2.6.0 => 2.6.0 
    gatsby-plugin-sitemap: ^2.3.1 => 2.4.1 
    gatsby-plugin-styled-components: ^3.2.1 => 3.3.0 
    gatsby-remark-autolink-headers: ^2.2.0 => 2.3.0 
    gatsby-remark-images: ^3.1.49 => 3.3.0 
    gatsby-source-filesystem: ^2.1.46 => 2.3.0 
    gatsby-transformer-json: ^2.3.0 => 2.4.0 
    gatsby-transformer-remark: ^2.6.58 => 2.8.4 
    gatsby-transformer-sharp: ^2.5.0 => 2.5.0 
  npmGlobalPackages:
    gatsby-cli: 2.12.8
```

**Comment by LekoArts** [comment]
Please update `gatsby-plugin-mdx` to `1.2.5` and try again :)

**Comment by calebpitan** [comment]
Yeah, works! Thanks.

**Comment by calebpitan** [comment]
Yeah, works thanks!
