### ISSUE TITLE
gatsby-remark-images not installing 

### ISSUE THREAD

**Issue by dougajmcdonald** [gatsbyjs/gatsby#2419]
Hi all, not 100% sure whether this is the right place for this issue, but I'm struggling to get `gatsby-remark-images` installed via npm.

I'm on windows and I'm aware it needs the `node-gyp / python` malarky so have run `npm install --global --production windows-build-tools` which succeeded and restarted by `cmd` prompt.

At the moment I'm getting the following after running `npm i --save gatsby-remark-images`:

```
C:\github\gatsby-blog>npm i --save gatsby-remark-images
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!

> sharp@0.17.3 install C:\github\gatsby-blog\node_modules\sharp
> node-gyp rebuild


C:\github\gatsby-blog\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Users\douga\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\github\gatsby-blog\node_modules\sharp\build\libvips-cpp.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\douga\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\douga\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\github\gatsby-blog\node_modules\sharp
gyp ERR! node -v v8.1.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN Error: EPERM: operation not permitted, unlink 'C:\github\gatsby-blog\node_modules\duplexer3\package.json'
npm WARN  { Error: EPERM: operation not permitted, unlink 'C:\github\gatsby-blog\node_modules\duplexer3\package.json'
npm WARN   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\github\\gatsby-blog\\node_modules\\duplexer3\\package.json\'',
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'unlink',
npm WARN   path: 'C:\\github\\gatsby-blog\\node_modules\\duplexer3\\package.json' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.17.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.17.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\douga\AppData\Roaming\npm-cache\_logs\2017-10-11T15_51_44_899Z-debug.log
```

I'm not sure quite where this is falling over internally, so unsure where to start debugging, any thoughts?

EDIT: 
Did some more digging and I get the same errors just installing the `gatsby-remark-sharp` plugin too, so I think the issue lies in there. `npm install --save gatsby-plugin-sharp === <same errors>`

**Comment by dougajmcdonald** [comment]
Closing this it was a `sharp` install issue, resolution on the linked issue
