### ISSUE TITLE
[Regression] Gatsby develop cannot find develop-process.js on Windows

### ISSUE THREAD

**Issue by Js-Brecht** [gatsbyjs/gatsby#24238]
## Description

With `gatsby@2.22.0`, an error is now being generated on Windows:

```sh
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'D:devsourcegatsbygatsby-develop-repro
ode_modulesgatsbydistcommandsdevelop-process.js'
Require stack:
- D:\dev\source\gatsby\gatsby-develop-repro\.cache\tmp-9704-KsKNXYqxwyqP
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\dev\source\gatsby\gatsby-develop-repro\.cache\tmp-9704-KsKNXYqxwyqP:2:17)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\dev\\source\\gatsby\\gatsby-develop-repro\\.cache\\tmp-9704-KsKNXYqxwyqP'
  ]
}
```

The issue appears have been introduced by this new change (from #22759):
https://github.com/gatsbyjs/gatsby/blob/bcf721461cc5a7e057bafe2c1f95c70646674b92/packages/gatsby/src/commands/develop.ts#L111-L119

The problem exists because `require("${developProcessPath}")` does not properly escape backslashes.

### Steps to reproduce

This can be recreated with any new gatsby site, as long as it is using the current version of Gatsby.  For convenience, I have created a reproduction [here](https://github.com/Js-Brecht/gatsby-develop-repro).

### Environment

```sh

  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - D:\dev\npm\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - /c/Users/jeremy.albright/.windows-build-tools/python27/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.21.37 => 2.22.0
    gatsby-image: ^2.4.4 => 2.4.4
    gatsby-plugin-manifest: ^2.4.5 => 2.4.6
    gatsby-plugin-offline: ^3.2.3 => 3.2.4
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.1
    gatsby-plugin-sharp: ^2.6.4 => 2.6.6
    gatsby-source-filesystem: ^2.3.4 => 2.3.5
    gatsby-transformer-sharp: ^2.5.2 => 2.5.2
```

**Comment by KyleAMathews** [comment]
Fixed in 2.22.1 — thanks for the bug report and your patience 🙏
