### ISSUE TITLE
Error: Cannot find module 'unified'

### ISSUE THREAD

**Issue by joeshub** [gatsbyjs/gatsby#24466]
## Description

When running develop, the console shows an error regarding missing package called `unified`

### Steps to reproduce

 1. `rm -rf .cache && rm -rf public && npm run develop`
 2. See console error, TLDR missing `unified` package

```
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module 'unified'
Require stack:
- /gatsby/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/parser/index.js
- /gatsby/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/parser/validate.js
- /gatsby/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/validate-steps.js
- /gatsby/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/recipe-machine/index.js
- /gatsby/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/graphql-server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/gatsby/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/parser/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/gatsby/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/parser/index.js',
    '/gatsby/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/parser/validate.js',
    '/gatsby/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/validate-steps.js',
    '/gatsby/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/recipe-machine/index.js',
    '/gatsby/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/graphql-server/server.js'
  ]
}
```

### Expected result

No error

### Actual result

Error

### Environment

```
  System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 76.0.1
    Safari: 13.1
  npmPackages:
    gatsby: ^2.22.10 => 2.22.10
    gatsby-cli: ^2.12.35 => 2.12.35
    gatsby-image: ^2.4.5 => 2.4.5
    gatsby-link: ^2.4.3 => 2.4.3
    gatsby-paginate: ^1.1.1 => 1.1.1
    gatsby-plugin-canonical-urls: ^2.3.2 => 2.3.2
    gatsby-plugin-emotion: ^4.3.2 => 4.3.2
    gatsby-plugin-google-analytics: ^2.3.2 => 2.3.2
    gatsby-plugin-manifest: ^2.4.9 => 2.4.9
    gatsby-plugin-mdx: ^1.2.12 => 1.2.12
    gatsby-plugin-offline: ^3.2.7 => 3.2.7
    gatsby-plugin-page-creator: ^2.3.7 => 2.3.7
    gatsby-plugin-react-helmet-async: ^1.0.16 => 1.0.16
    gatsby-plugin-sharp: ^2.6.9 => 2.6.9
    gatsby-plugin-sitemap: ^2.4.3 => 2.4.3
    gatsby-remark-autolink-headers: ^2.3.3 => 2.3.3
    gatsby-remark-prismjs: ^3.5.2 => 3.5.2
    gatsby-source-filesystem: ^2.3.8 => 2.3.8
    gatsby-transformer-sharp: ^2.5.3 => 2.5.3
  npmGlobalPackages:
    gatsby-cli: 2.12.35
```

**Comment by LekoArts** [comment]
Thank you for opening this!

I created a fresh project with `gatsby`, `react` and `react-dom` and can't replicate the behavior. Also after adding `gatsby-cli` it works fine. So I'd suggest removing `gatsby-cli` from your package.json (it's not needed), removing node_modules, .cache and public, run a fresh `npm install` and try again :)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
