### ISSUE TITLE
[Gatsby Cli] Cannot find module 'detect-port'

### ISSUE THREAD

**Issue by MrUltimate** [gatsbyjs/gatsby#24589]
## Description

When running any `gatsby` command, there's a missing modules error under the `yoga-layout-prebuilt` module.

### Steps to reproduce

Run `gatsby clean` or `gatsby develop`.

### Expected result

Clean cache and start development server

### Actual result

Stack Trace:

```
(base) MacBook-Pro:web $ gatsby develop
/usr/local/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Cannot find module 'detect-port'
Require stack:
- /usr/local/lib/node_modules/gatsby-cli/lib/recipes.js
- /usr/local/lib/node_modules/gatsby-cli/lib/create-cli.js
- /usr/local/lib/node_modules/gatsby-cli/lib/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby-cli/lib/recipes.js:18:42)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/gatsby-cli/lib/recipes.js',
    '/usr/local/lib/node_modules/gatsby-cli/lib/create-cli.js',
    '/usr/local/lib/node_modules/gatsby-cli/lib/index.js'
  ]
}
```

### Environment

`gatsby info --clipboard` does not run.

**Comment by lannonbr** [comment]
What version of gatsby-cli are you using? This was a previous issue that was solved earlier in #24325 with `gatsby-cli@2.12.33`

**Comment by MrUltimate** [comment]
How do I find that out? When I run `npm gatsby-cli -v` I get `6.14.5`

**Comment by lannonbr** [comment]
Try checking out your package-lock.json or yarn.lock file and search for "gatsby-cli"

**Comment by MrUltimate** [comment]
Sorry about that. Just went ahead and install that specific version `npm install -g gatsby-cli@2.12.33`
