### ISSUE TITLE
Can't explicitly set nested inferred types

### ISSUE THREAD

**Issue by seancdavis** [gatsbyjs/gatsby#24910]
## Description

I'm using `gatsby-transformer-remark` and local markdown files as a data source in my project. I'm attempting to explicitly define the frontmatter data schema to protect against missing frontmatter keys that I'm querying for in the project.

This works wonderfully when only going one level deep on inferred types. If I go any deeper than that I run into issues. See below.

### Steps to reproduce

[Here is an example project](https://github.com/seancdavis/gatsby-nested-explicit-types). It's built from the default starter. It's current state is the last step mentioned in this section.

Take a basic markdown file that looks like this:

```md
---
title: Hello World
items:
  - name: Button
    button:
      label: Button Label
      url: /button-url
---

Non mollit dolore pariatur et sunt. Est nostrud deserunt consectetur nostrud. Irure sunt dolore aliquip irure culpa qui. Ex fugiat cupidatat irure esse non aliquip occaecat incididunt est enim ut. Anim culpa et eu ipsum. Laboris sunt non eiusmod amet. Culpa amet laboris Lorem nisi ad aliqua in proident aliquip nulla quis do voluptate mollit.
```

We can query for it with gatsby-transformer-remark like so:

```graphql
{
  allMarkdownRemark(filter: {fileAbsolutePath: {regex: "//test.md/"}}) {
    edges {
      node {
        __typename
        frontmatter {
          __typename
          title
          items {
            __typename
            button {
              __typename
              label
              url
            }
          }
        }
      }
    }
  }
}
```

It returns exactly what I'd expect:

```json
{
  "data": {
    "allMarkdownRemark": {
      "edges": [
        {
          "node": {
            "__typename": "MarkdownRemark",
            "frontmatter": {
              "__typename": "MarkdownRemarkFrontmatter",
              "title": "Hello World",
              "items": [
                {
                  "__typename": "MarkdownRemarkFrontmatterItems",
                  "button": {
                    "__typename": "MarkdownRemarkFrontmatterItemsButton",
                    "label": "Button Label",
                    "url": "/button-url"
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
```

Now, let's say I wanted more control over the frontmatter type so I could make sure all fields were there. I could define schema in my `gatsby-node.js` file like so:

```js
exports.createSchemaCustomization = ({ actions, schema }) => {
  const typeDefs = `
    type MarkdownRemark implements Node {
      frontmatter: Frontmatter
    }

    type Frontmatter {
      title: String
    }
  `
  actions.createTypes(typeDefs)
}
```

This also works as I'd expect using the same query, returning this:

```json
{
  "data": {
    "allMarkdownRemark": {
      "edges": [
        {
          "node": {
            "__typename": "MarkdownRemark",
            "frontmatter": {
              "__typename": "Frontmatter",
              "title": "Hello World",
              "items": [
                {
                  "__typename": "MarkdownRemarkFrontmatterItems",
                  "button": {
                    "__typename": "MarkdownRemarkFrontmatterItemsButton",
                    "label": "Button Label",
                    "url": "/button-url"
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
```

Notice the change here being that the `frontmatter` object now has a type of `Frontmatter`, where it was `MarkdownFrontmatter` previously.

But now I want to take it one step further and control the `items` type. So, in `gatsby-node.js`, I try this:

```js
exports.createSchemaCustomization = ({ actions, schema }) => {
  const typeDefs = `
    type MarkdownRemark implements Node {
      frontmatter: Frontmatter
    }

    type Frontmatter {
      title: String
      items: Item
    }

    type Item {
      name: String
    }
  `
  actions.createTypes(typeDefs)
}
```

Then I run the same query, but now I see the following:

```json
{
  "errors": [
    {
      "message": "Cannot query field \"button\" on type \"Item\".",
      "locations": [
        {
          "line": 11,
          "column": 13
        }
      ],
      "stack": [
        "GraphQLError: Cannot query field \"button\" on type \"Item\".",
        "    at Object.Field (/Users/seancdavis/code/covingtonclassicalacademy-org/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:53:31)",
        "    at Object.enter (/Users/seancdavis/code/covingtonclassicalacademy-org/node_modules/graphql/language/visitor.js:324:29)",
        "    at Object.enter (/Users/seancdavis/code/covingtonclassicalacademy-org/node_modules/graphql/language/visitor.js:375:25)",
        "    at visit (/Users/seancdavis/code/covingtonclassicalacademy-org/node_modules/graphql/language/visitor.js:242:26)",
        "    at validate (/Users/seancdavis/code/covingtonclassicalacademy-org/node_modules/graphql/validation/validate.js:73:24)",
        "    at getGraphQLParams.then.then.optionsData (/Users/seancdavis/code/covingtonclassicalacademy-org/node_modules/express-graphql/index.js:121:32)",
        "    at process._tickCallback (internal/process/next_tick.js:68:7)"
      ]
    }
  ]
}
```

So I add support for the button field in my types definition:

```js
exports.createSchemaCustomization = ({ actions, schema }) => {
  const typeDefs = `
    type MarkdownRemark implements Node {
      frontmatter: Frontmatter
    }

    type Frontmatter {
      title: String
      items: Item
    }

    type Item {
      name: String
      button: Button
    }

    type Button {
      label: String
      url: String
    }
  `
  actions.createTypes(typeDefs)
}
```

That resolves the error, but now I get nothing returned for the button:

```json
{
  "data": {
    "allMarkdownRemark": {
      "edges": [
        {
          "node": {
            "__typename": "MarkdownRemark",
            "frontmatter": {
              "__typename": "Frontmatter",
              "title": "Hello World",
              "items": {
                "__typename": "Item",
                "button": null
              }
            }
          }
        }
      ]
    }
  }
}
```

### Expected result

See above.

### Actual result

See above.

### Environment

```
  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.97
    Firefox: 67.0.4
    Safari: 13.1
  npmPackages:
    gatsby: ^2.20.14 => 2.20.14
    gatsby-background-image: ^1.1.1 => 1.1.1
    gatsby-image: ^2.2.34 => 2.2.41
    gatsby-plugin-catch-links: ^2.1.15 => 2.1.25
    gatsby-plugin-eslint: ^2.0.8 => 2.0.8
    gatsby-plugin-google-analytics: ^2.2.2 => 2.2.2
    gatsby-plugin-manifest: ^2.2.31 => 2.2.41
    gatsby-plugin-netlify: ^2.2.1 => 2.2.1
    gatsby-plugin-offline: ^3.0.27 => 3.0.34
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.22
    gatsby-plugin-sass: ^2.1.28 => 2.1.28
    gatsby-plugin-sharp: ^2.3.5 => 2.4.5
    gatsby-plugin-sitemap: ^2.3.1 => 2.3.1
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-remark-ample: ample/gatsby-remark-ample => 0.3.0
    gatsby-remark-images: ^3.2.2 => 3.2.2
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0
    gatsby-source-filesystem: ^2.1.40 => 2.1.48
    gatsby-transformer-remark: ^2.7.1 => 2.7.1
    gatsby-transformer-sharp: ^2.3.7 => 2.3.14
```

**Comment by herecydev** [comment]
It looks like your:

```
 type Frontmatter {
      title: String
      items: Item
    }
```

should be

```
 type Frontmatter {
      title: String
      items: [Item]
  }
```

But I'm also not sure where you're trying to take this, what's your desired result?

**Comment by seancdavis** [comment]
Thanks, @herecydev! Of course it was a stupid mistake on my part. Writing the schema properly did help fix all the issues listed above.

Taking this approach led to another issue with setting mappings in `gatsby-config.js`. But that's not directly related to the issue here, so I will close.
