### ISSUE TITLE
bug: starters are broken with yarn

### ISSUE THREAD

**Issue by stephencweiss** [gatsbyjs/gatsby#25476]
## Description

Describe the issue that you're seeing.

When following the documentation to create a new starter, example [gatsby-starter-blog](https://www.gatsbyjs.org/starters/gatsbyjs/gatsby-starter-blog/), the build process fails with the default `yarn`.

### Steps to reproduce

```
stephen@Stephens-MBP-2 temp % gatsby new starter-blog-with-redirect https://github.com/gatsbyjs/gatsby-starter-blog
info Creating new site from git:
Cloning into 'starter-blog-with-redirect'...
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 41 (delta 1), reused 23 (delta 0), pack-reused 0
Unpacking objects: 100% (41/41), done.
success Created starter directory layout
info Installing packages...
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "gatsby > @pmmmwh/react-refresh-webpack-plugin@0.3.3" has incorrect peer dependency "react-refresh@^0.8.2".
warning "gatsby > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 17.20s.
info Initialising git in starter-blog-with-redirect
Initialized empty Git repository in /Users/stephen/code/temp/starter-blog-with-redirect/.git/
info Create initial git commit in starter-blog-with-redirect
info
Your new Gatsby site has been successfully bootstrapped. Start developing it by
running:

  cd starter-blog-with-redirect
  gatsby develop
stephen@Stephens-MBP-2 temp % cd starter-blog-with-redirect
stephen@Stephens-MBP-2 starter-blog-with-redirect % gatsby develop
/Users/stephen/code/temp/starter-blog-with-redirect/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Cannot find module '../_lib/requiredArgs/index.js'
Require stack:
- /Users/stephen/code/temp/starter-blog-with-redirect/node_modules/date-fns/toDate/index.js
- /Users/stephen/code/temp/starter-blog-with-redirect/node_modules/date-fns/getDayOfYear/index.js
- /Users/stephen/code/temp/starter-blog-with-redirect/node_modules/gatsby/dist/utils/feedback.js
- /Users/stephen/code/temp/starter-blog-with-redirect/node_modules/gatsby/dist/commands/develop-process.js
- /Users/stephen/code/temp/starter-blog-with-redirect/.cache/tmp-3109-vTevwB94b1Vf
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (/Users/stephen/code/temp/starter-blog-with-redirect/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/stephen/code/temp/starter-blog-with-redirect/node_modules/date-fns/toDate/index.js:8:37)
    at Module._compile (/Users/stephen/code/temp/starter-blog-with-redirect/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (/Users/stephen/code/temp/starter-blog-with-redirect/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/stephen/code/temp/starter-blog-with-redirect/node_modules/date-fns/getDayOfYear/index.js:8:37)
    at Module._compile (/Users/stephen/code/temp/starter-blog-with-redirect/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/stephen/code/temp/starter-blog-with-redirect/node_modules/date-fns/toDate/index.js',
    '/Users/stephen/code/temp/starter-blog-with-redirect/node_modules/date-fns/getDayOfYear/index.js',
    '/Users/stephen/code/temp/starter-blog-with-redirect/node_modules/gatsby/dist/utils/feedback.js',
    '/Users/stephen/code/temp/starter-blog-with-redirect/node_modules/gatsby/dist/commands/develop-process.js',
    '/Users/stephen/code/temp/starter-blog-with-redirect/.cache/tmp-3109-vTevwB94b1Vf'
  ]
}

 ERROR



   ╭──────────────────────────────────────────────╮
   │                                              │
   │     Update available 2.12.51 → 2.12.55       │
   │   Run yarn global add gatsby-cli to update   │
   │                                              │
   ╰──────────────────────────────────────────────╯


stephen@Stephens-MBP-2 starter-blog-with-redirect % yarn global add gatsby-cli
yarn global v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > gatsby@2.23.11" has unmet peer dependency "react@^16.4.2".
warning " > gatsby@2.23.11" has unmet peer dependency "react-dom@^16.4.2".
warning "gatsby > @pmmmwh/react-refresh-webpack-plugin@0.3.3" has incorrect peer dependency "react-refresh@^0.8.2".
warning "gatsby > @reach/router@1.3.4" has unmet peer dependency "react@15.x || 16.x || 16.4.0-alpha.0911da3".
warning "gatsby > @reach/router@1.3.4" has unmet peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
warning "gatsby > gatsby-link@2.4.8" has unmet peer dependency "react@^16.4.2".
warning "gatsby > gatsby-link@2.4.8" has unmet peer dependency "react-dom@^16.4.2".
warning "gatsby > gatsby-react-router-scroll@3.0.7" has unmet peer dependency "react@^16.4.2".
warning "gatsby > gatsby-react-router-scroll@3.0.7" has unmet peer dependency "react-dom@^16.4.2".
warning "gatsby > react-hot-loader@4.12.21" has unmet peer dependency "react@^15.0.0 || ^16.0.0".
warning "gatsby > react-hot-loader@4.12.21" has unmet peer dependency "react-dom@^15.0.0 || ^16.0.0".
warning "gatsby > @reach/router > create-react-context@0.3.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
[4/4] 🔨  Building fresh packages...
success Installed "gatsby-cli@2.12.55" with binaries:
      - gatsby
✨  Done in 4.49s.
stephen@Stephens-MBP-2 starter-blog-with-redirect % gatsby develop
/Users/stephen/code/temp/starter-blog-with-redirect/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Cannot find module '../_lib/requiredArgs/index.js'
Require stack:
- /Users/stephen/code/temp/starter-blog-with-redirect/node_modules/date-fns/toDate/index.js
- /Users/stephen/code/temp/starter-blog-with-redirect/node_modules/date-fns/getDayOfYear/index.js
- /Users/stephen/code/temp/starter-blog-with-redirect/node_modules/gatsby/dist/utils/feedback.js
- /Users/stephen/code/temp/starter-blog-with-redirect/node_modules/gatsby/dist/commands/develop-process.js
- /Users/stephen/code/temp/starter-blog-with-redirect/.cache/tmp-3408-Zy19D8s7jv2t
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (/Users/stephen/code/temp/starter-blog-with-redirect/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/stephen/code/temp/starter-blog-with-redirect/node_modules/date-fns/toDate/index.js:8:37)
    at Module._compile (/Users/stephen/code/temp/starter-blog-with-redirect/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (/Users/stephen/code/temp/starter-blog-with-redirect/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/stephen/code/temp/starter-blog-with-redirect/node_modules/date-fns/getDayOfYear/index.js:8:37)
    at Module._compile (/Users/stephen/code/temp/starter-blog-with-redirect/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/stephen/code/temp/starter-blog-with-redirect/node_modules/date-fns/toDate/index.js',
    '/Users/stephen/code/temp/starter-blog-with-redirect/node_modules/date-fns/getDayOfYear/index.js',
    '/Users/stephen/code/temp/starter-blog-with-redirect/node_modules/gatsby/dist/utils/feedback.js',
    '/Users/stephen/code/temp/starter-blog-with-redirect/node_modules/gatsby/dist/commands/develop-process.js',
    '/Users/stephen/code/temp/starter-blog-with-redirect/.cache/tmp-3408-Zy19D8s7jv2t'
  ]
}
stephen@Stephens-MBP-2 starter-blog-with-redirect % yarn --version
1.22.4
```

Note -- No minimum reproducible repo is provided because the problem is _with_ the minimum reproducible repo. 

### Expected result

`gatsby develop` should not break

### Actual result

`gatsby develop` breaks _unless_ `node_modules` whether managed by `npm` or `yarn` 

When run with `npm` it specifies that `babel-plugin-remove-graphql-queries@^2.9.10`, a dependency of `gatsby` doesn't not exist.

```
stephen@Stephens-MBP-2 starter-blog-with-redirect % rm -rf yarn.lock node_modules
stephen@Stephens-MBP-2 starter-blog-with-redirect % npm i
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for babel-plugin-remove-graphql-queries@^2.9.10.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'gatsby'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stephen/.npm/_logs/2020-07-02T13_49_29_660Z-debug.log
stephen@Stephens-MBP-2 starter-blog-with-redirect % gatsby develop

 ERROR

There was a problem loading the local develop command. Gatsby may not be installed in your site's "node_modules" directory. Perhaps you need to run "npm install"? You might need to delete your "package-lock.json" as well.
```

### Environment

```
gatsby info --clipboard

  System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
  Languages:
    Python: 3.8.0 - /Users/stephen/.pyenv/shims/python
  Browsers:
    Chrome: 83.0.4103.116
    Safari: 13.1.1
```

**Comment by ascorbic** [comment]
Hi. SOrry about this. It should be fixed imminently. See #25475

**Comment by stephencweiss** [comment]
Thanks @ascorbic ! Sorry for the duplicate!
