### ISSUE TITLE
Optional catch syntax throwing syntax error

### ISSUE THREAD

**Issue by andysaktia** [gatsbyjs/gatsby#25521]
## Description

Can not create gatsby site. when finish installation.

### Steps to reproduce

`gatsby new gatsby-site`

### Expected result

gatsby-site created and can run `cd` command shell

### Actual result
```shell
/usr/local/lib/node_modules/gatsby-cli/lib/init-starter.js:117
  } catch {
          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby-cli/lib/create-cli.js:28:20)
```

### Environment
Can't run `gatsby info --clipboard` in your project directory and paste the output here.

Anyone can help me fix this?

**Comment by LekoArts** [comment]
Please follow our issue template:

````
<!--
  Please fill out each section below, otherwise, your issue will be closed. This info allows Gatsby maintainers to diagnose (and fix!) your issue as quickly as possible.

  Useful Links:
  - Documentation: https://www.gatsbyjs.org/docs/
  - How to File an Issue: https://www.gatsbyjs.org/contributing/how-to-file-an-issue/

  Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
-->

## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

````

**Comment by pieh** [comment]
What node version are you using? This errors seems to be about "optional catch binding" syntax which is supported since Node 10.3 and gatsby minimal supported node version is Node 10.16 (currently)

**Comment by sidharthachatterjee** [comment]
Thank you for reporting this @andysaktia 

As @pieh _correctly_ mentioned, this appears to occur because you're using an unsupported version of Node. Gatsby supports Node v10.13 at a minimum. Please upgrade Node. 

Also, out of curiosity, what version of Node and Gatsby CLI were you using? Thank you!

(Marking this issue as resolved and closing but feel free to reopen if upgrading doesn't fix this for you)
