### ISSUE TITLE
Gatsby-cli@2.12.70 is not working correctly for me

### ISSUE THREAD

**Issue by mpmccauley** [gatsbyjs/gatsby#26205]
## Description

After upgrading gatsby-cli to 2.12.70, when using gatsby commands, I am met with the following error:

```
gatsby -v
/usr/lib/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/index.js:12851
  return result?.value;
                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/lib/node_modules/gatsby-cli/lib/recipes.js:8:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
```

### Steps to reproduce

Install latest gatsby cli using --> npm i -g gatsby-cli

Use gatsby-cli
 
### Expected result

gatsby-cli should work as previous versions

### Actual result

I am met with the error pasted above on any gatsby command

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Note- i reverted to gatsby-cli@2.12.68 and it works fine again**

System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.6 - /usr/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: 79.0
  npmPackages:
    gatsby: ^2.23.3 => 2.24.25
    gatsby-background-image: ^1.1.1 => 1.1.1
    gatsby-image: ^2.4.7 => 2.4.14
    gatsby-plugin-manifest: ^2.4.11 => 2.4.21
    gatsby-plugin-offline: ^3.2.9 => 3.2.21
    gatsby-plugin-react-helmet: ^3.3.4 => 3.3.10
    gatsby-plugin-sharp: ^2.6.12 => 2.6.24
    gatsby-plugin-styled-components: ^3.3.4 => 3.3.10
    gatsby-source-filesystem: ^2.3.12 => 2.3.23
    gatsby-transformer-remark: ^2.8.17 => 2.8.27
    gatsby-transformer-sharp: ^2.5.5 => 2.5.12
  npmGlobalPackages:
    gatsby-cli: 2.12.68

**Comment by KyleAMathews** [comment]
Sorry about the breakage — it's fixed in 2.12.71 — PR that fixed this https://github.com/gatsbyjs/gatsby/pull/26206
