### ISSUE TITLE
events.js:182       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by nirajkiul** [gatsbyjs/gatsby#2661]
events.js:182
      throw er; // Unhandled 'error' event
      ^

RangeError: Maximum call stack size exceeded
    at clone (F:\IOT\seed-project\node_modules\mongoose\lib\utils.js:241:31)
    at cloneObject (F:\IOT\seed-project\node_modules\mongoose\lib\utils.js:343:13)
    at clone (F:\IOT\seed-project\node_modules\mongoose\lib\utils.js:260:16)
    at model.Document.$toObject (F:\IOT\seed-project\node_modules\mongoose\lib\document.js:2039:13)
    at model.Document.toJSON (F:\IOT\seed-project\node_modules\mongoose\lib\document.js:2330:15)
    at clone (F:\IOT\seed-project\node_modules\mongoose\lib\utils.js:252:18)
    at cloneArray (F:\IOT\seed-project\node_modules\mongoose\lib\utils.js:362:14)
    at clone (F:\IOT\seed-project\node_modules\mongoose\lib\utils.js:247:12)
    at cloneObject (F:\IOT\seed-project\node_modules\mongoose\lib\utils.js:343:13)
    at clone (F:\IOT\seed-project\node_modules\mongoose\lib\utils.js:260:16)
    at model.Document.$toObject (F:\IOT\seed-project\node_modules\mongoose\lib\document.js:2039:13)
    at model.Document.toJSON (F:\IOT\seed-project\node_modules\mongoose\lib\document.js:2330:15)
    at clone (F:\IOT\seed-project\node_modules\mongoose\lib\utils.js:252:18)
    at cloneObject (F:\IOT\seed-project\node_modules\mongoose\lib\utils.js:343:13)
    at clone (F:\IOT\seed-project\node_modules\mongoose\lib\utils.js:260:16)
    at model.Document.$toObject (F:\IOT\seed-project\node_modules\mongoose\lib\document.js:2039:13)

**Comment by nodox** [comment]
Can you provide a sample code snippet? This error without the proper context could be anything.
