### ISSUE TITLE
Cannot run Gatsby on Mac

### ISSUE THREAD

**Issue by justageek** [gatsbyjs/gatsby#26812]
## Description

Gatsby cli fails with the following errors

```shell
/usr/local/lib/node_modules/gatsby-cli/node_modules/uuid/dist/esm-browser/index.js:1
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1055:16)
    at Module._compile (internal/modules/cjs/loader.js:1103:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby-cli/node_modules/gatsby-telemetry/lib/telemetry.js:8:13)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
```

### Steps to reproduce

Run any Gatsby command

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

Create a new Gatsby project.
What should happen?

Just the above errors.

What happened.

Mac OS Mojave 

Run `gatsby info --clipboard` in your project directory and paste the output here.

Same errors as described above.

**Comment by alandickinson** [comment]
I'm also getting this same error w/ any cli command.

gatsby-cli v2.12.92
node v13.6.0
npm v6.13.4

**Comment by GetShortstack** [comment]
I'm having the same issue running any cli command, even gatsby --version

**Comment by LekoArts** [comment]
Please provide some more information like versions of your gatsby-cli, node, npm & operating system.

I've run `npm install -g gatsby-cli` (with `gatsby-cli@2.12.92`) and can't reproduce this with e.g. `gatsby --version`.

**Comment by LekoArts** [comment]
This seems related to https://github.com/uuidjs/uuid/issues/488#issuecomment-669024239 - please post your Node version. (with `node --version`)
