### ISSUE TITLE
[gatsby-cli] Error: Cannot find module 'lib/index.js' (STATUS: PR with fix merged)

### ISSUE THREAD

**Issue by dustinhorton** [gatsbyjs/gatsby#2686]
Any chance the release (`1.1.12`) this evening was broken? 

```
module.js:529
    throw err;
    ^

Error: Cannot find module 'lib/index.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby-cli/bin.js:4:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by dganoff** [comment]
Getting the same error here.

**Comment by dustinhorton** [comment]
As a workaround, you can edit `node_modules/gatsby-cli/bin.js`, and change line 4 to:

```js
require(`./lib/index.js`)
```

Credit to @quentin- for that.

**Comment by dustinhorton** [comment]
Should've checked the PRs. @sebastienfi was on it: https://github.com/gatsbyjs/gatsby/pull/2684

**Comment by KyleAMathews** [comment]
Merged and published. Sorry for the bother everyone.
