### ISSUE TITLE
Build HTML error: Cannot resolve 'file' or 'directory' ../public/chunk-manifest.json

### ISSUE THREAD

**Issue by syzer** [gatsbyjs/gatsby#2722]
```bash
  Error: Module not found: Error: Cannot resolve 'file' or 'directory' ../public/chunk-manifest.json in /Volumes/ramdisk 1/.  cache
  resolve file
    /Volumes/ramdisk 1/public/chunk-manifest.json doesn't exist
    /Volumes/ramdisk 1/public/chunk-manifest.json.js doesn't exist
    /Volumes/ramdisk 1/public/chunk-manifest.json.jsx doesn't exist
  resolve directory
    /Volumes/ramdisk 1/public/chunk-manifest.json doesn't exist (directory default file)
    /Volumes/ramdisk 1/public/chunk-manifest.json/package.json doesn't exist (directory description file)
  [/Volumes/ramdisk 1/public/chunk-manifest.json]
  [/Volumes/ramdisk 1/public/chunk-manifest.json.js]
  [/Volumes/ramdisk 1/public/chunk-manifest.json.jsx]
   @ ./.cache/static-entry.js 159:22-67
```

**Comment by syzer** [comment]
it's required by
static-entry.js
there it dosen't use 
```const path = require(path')```
and `path.join()`
or `path.resolve()`
but `../public/chunk-manifest.json`

Fixed by ```echo "dadas" > /Volumes/ramdisk\ 1/public/chunk-manifest.json```

**Comment by KyleAMathews** [comment]
This happens consistently? I've never seen this error. Can you verify this happens for you with a starter?

**Comment by syzer** [comment]
i removed all files from /public and ./.cache
then gatsby build will fail
error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND


  Error: Module not found: Error: Cannot resolve 'file' or 'directory' ../public/chunk-manifest.json in /Volumes/ramdisk 1/.cache
  resolve file
    /Volumes/ramdisk 1/public/chunk-manifest.json doesn't exist
    /Volumes/ramdisk 1/public/chunk-manifest.json.js doesn't exist
    /Volumes/ramdisk 1/public/chunk-manifest.json.jsx doesn't exist
  resolve directory
    /Volumes/ramdisk 1/public/chunk-manifest.json doesn't exist (directory default file)
    /Volumes/ramdisk 1/public/chunk-manifest.json/package.json doesn't exist (directory description file)
  [/Volumes/ramdisk 1/public/chunk-manifest.json]
  [/Volumes/ramdisk 1/public/chunk-manifest.json.js]
  [/Volumes/ramdisk 1/public/chunk-manifest.json.jsx]
   @ ./.cache/static-entry.js 159:22-67

➜  echo "dadas" > /Volumes/ramdisk\ 1/public/chunk-manifest.json
➜  gatsby build
info Done building in 22.503 sec

100%
```js
  const chunkManifest = require(`!raw!../public/chunk-manifest.json`)
```

**Comment by syzer** [comment]
gatsby: "^1.9.87",
and cli
gatsby --version                                                                                           
```1.1.14```

**Comment by syzer** [comment]
also would be nice to have multiprocess compilation

**Comment by syzer** [comment]
maybe this will help
```window console
build-js-styles.css:1 Uncaught SyntaxError: Unexpected token .
app-2601dcb867497ca0598a.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at app-2601dcb867497ca0598a.js:1
(anonymous) @ app-2601dcb867497ca0598a.js:1
path---contact-us-1db04e5021b40904aca6.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at path---contact-us-1db04e5021b40904aca6.js:1
(anonymous) @ path---contact-us-1db04e5021b40904aca6.js:1
component---src-pages-contact-us-index-js-25ba4615cae4d88c5bfd.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at component---src-pages-contact-us-index-js-25ba4615cae4d88c5bfd.js:1
(anonymous) @ component---src-pages-contact-us-index-js-25ba4615cae4d88c5bfd.js:1
component---src-layouts-index-js-5356c4fa85f30f7831b9.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at component---src-layouts-index-js-5356c4fa85f30f7831b9.js:1
```

**Comment by KyleAMathews** [comment]
Try installing and building one of the official starters.

**Comment by syzer** [comment]
i did two days from
oficial gatsby tutorial :)

sometimes i get:
```
info bootstrap finished - 2.678 s

error UNHANDLED REJECTION


  Error: Invariant Violation: /Volumes/ramdisk 1/src/components/category-favorites.js not found in the store components:
....
```

and without code change i restart and get
```
info bootstrap finished - 2.764 s

 DONE  Compiled successfully in 6037ms                                                                                               17:36:57

 I  Your site is running at http://localhost:8000
 I  Your graphql debugger is running at http://localhost:8000/___graphql
 WAIT  Compiling...                                                                                                                  17:36:57

 DONE  Compiled successfully in 164ms                                                                                                17:36:57

 I  Your site is running at http://localhost:8000
 I  Your graphql debugger is running at http://localhost:8000/___graphql
```

**Comment by KyleAMathews** [comment]
Double-check your on Node 6+

**Comment by syzer** [comment]
```
nvm version
v8.5.0

also nice feature would be if `gatsby-config` could handle async/promise
```js
const products = require('./data/products.json')  // this is cache for graphql

module.exports = {
  siteMetadata: {
    // fake meta
    title: `Meta loaded OK, superb`,
    // this can come via square space or wordpress
    articles: [
      {
        title: 'works ok',
        html: '<p>fragments</p>'
      },
    ],
    products: newProductsForGraphQl(products),
```
right now i need to run custom script before runnign ```gatsby build```
its ok.. but for gatsby develop i have no way to do it

**Comment by syzer** [comment]
so if i could `await newProductsForGraphQl` that would be awesome

**Comment by syzer** [comment]
Also: I very much liked idea about giving link how to handle webpack errors (in `gulp build`)
👍 
Would be good to include also this link (more information):
[stack webpack](https://stackoverflow.com/questions/37656592/define-global-variable-with-webpack)

**Comment by neilyoung** [comment]
@syzer Would you mind to share how you fixed the chunk-manifest.json issue? I can confirm, deleting cache and public is the dead for the gatsby build.

**Comment by neilyoung** [comment]
@syzer I'm also now hanging on "missing chunk-manifest". Any idea, how to solve?

**Comment by syzer** [comment]
@neilyoung made a workaround for development
and for production have test before deployment.

**Comment by neilyoung** [comment]
@syzer I'm absolutely have no issue during development. Nothing at all. What do you mean "have a test before deployment?"

**Comment by syzer** [comment]
Before I deploy the application I have a test did it compile correctly.
There is/was a bug in gatsby that caused compilation non deterministic(stochastic) process.

So i take my chances and compile... run test and if it dosen't pass
I redo compilation.

And workaround that was one liner.. did post it because I think it depends on version of gatsby you use.

Wish I could help you more.

**Comment by neilyoung** [comment]
@syzer Ah, ok. Yes, of course, this is what I'm doing too. Better - was doing. I did give up Gatsby, there was no specific reason for me to use it, it just was on the very first Google items searching for "static SPA" or so. I have switched to react-static and everything works w/o problems. Opting out here.

**Comment by syzer** [comment]
Oh...
How is your experience with react-static ?
I glanced over and looks very webpack/configuration based approach.

**Comment by neilyoung** [comment]
It works for me. I don't need that markdown overhead, gatsby brings. I was just looking for a quick way to build a more technically oriented, self-contained dashboard app, based on ReactJS and bootstrap,  which I wanted to be hosted by my Java app in order to control a REST API exposed by the same Java app. Q&D, though, but I had to fight gatsby more than the other problems. :)

But I don't want to advertise react-static in a Gatsby thread... it was just so, that in my particular case the other worked better than Gatsby. Just for the "go productive" part, development was OK

**Comment by syzer** [comment]
Can i ask what is your  time to first meaningful (you can check that in performance tab in chrome) ?

**Comment by neilyoung** [comment]
Is it this, what you are looking for?
<img width="375" alt="performance" src="https://user-images.githubusercontent.com/731020/34101982-c04f9dac-e3e7-11e7-82a1-306e3cbc329b.png">

**Comment by syzer** [comment]
Sorry.. audits tab :) (AKA lighthouse)

**Comment by neilyoung** [comment]
Hmm. Seems to be not useable 

<img width="785" alt="perf" src="https://user-images.githubusercontent.com/731020/34105707-b07c87a6-e3f5-11e7-9824-314b763a1acb.png">

**Comment by syzer** [comment]
Did you broke the lighthouse ? :D

**Comment by IvanMiIosevic** [comment]
Hi,

I've tried to deploy 2 gatsby sites on netlify and the first one did well but now the second one (which is using the same starter) is failing build on netlify

```
9:28:10 PM: info bootstrap finished - 4.069 s
9:28:28 PM: success Building CSS — 18.309 s
9:28:58 PM: success Building production JavaScript bundles — 29.926 s
9:29:20 PM: Error: Cannot find module './/opt/build/repo/public/styles.css'.
9:29:20 PM:     at render-page.js:75687:42
9:29:20 PM:     at webpackContextResolve (render-page.js:75687:90)
9:29:20 PM:     at webpackContext (render-page.js:75684:30)
9:29:20 PM:     at Object.map../opt/build/repo/public/styles.css (render-page.js:75621:43)
9:29:20 PM:     at __webpack_require__ (render-page.js:30:30)
9:29:20 PM:     at Object.<anonymous> (render-page.js:94:13)
9:29:20 PM:     at __webpack_require__ (render-page.js:30:30)
9:29:20 PM:     at Object.assign.i (render-page.js:50:18)
9:29:20 PM:     at render-page.js:53:10
9:29:20 PM:     at webpackUniversalModuleDefinition (render-page.js:3:20)
9:29:20 PM: error Building static HTML for pages failed
9:29:20 PM: See our docs page on debugging HTML builds for help https://goo.gl/yL9lND
9:29:20 PM:    6 | };
9:29:20 PM:    7 | function webpackContextResolve(req) {
9:29:20 PM: >  8 | 	return map[req] || (function() { throw new Error("Cannot find module '" + req + "'.") }());
9:29:20 PM:      | 	                                ^
9:29:20 PM:    9 | };
9:29:20 PM:   10 | webpackContext.keys = function webpackContextKeys() {
9:29:20 PM:   11 | 	return Object.keys(map);
9:29:20 PM: 
9:29:20 PM:   WebpackError: Cannot find module './/opt/build/repo/public/chunk-manifest.json  '.
9:29:20 PM:   
9:29:20 PM:   - .json$:8 
9:29:20 PM:     ^/.//.*//chunk/-manifest/.json$:8:34
9:29:20 PM:   
9:29:20 PM:   - .json$:8 webpackContextResolve
9:29:20 PM:     ^/.//.*//chunk/-manifest/.json$:8:89
9:29:20 PM:   
9:29:20 PM:   - .json$:5 webpackContext
9:29:20 PM:     ^/.//.*//chunk/-manifest/.json$:5:1
9:29:20 PM:   
9:29:20 PM:   - static-entry.js:188 module.exports
9:29:20 PM:     .cache/static-entry.js:188:25
9:29:20 PM:   
9:29:20 PM:   - static-entry.js:99 Function.Promise.fromNode.Promise.fromCallback
9:29:20 PM:     .cache/static-entry.js:99:27
9:29:21 PM:   
9:29:21 PM:   
9:29:21 PM:   
9:29:21 PM:   
9:29:21 PM:   
9:29:21 PM: 
9:29:21 PM: Caching artifacts
9:29:21 PM: Started saving node modules
9:29:21 PM: Finished saving node modules
9:29:21 PM: Started saving yarn cache
9:29:21 PM: Finished saving yarn cache
9:29:21 PM: Started saving pip cache
9:29:21 PM: Finished saving pip cache
9:29:21 PM: Started saving emacs cask dependencies
9:29:21 PM: Finished saving emacs cask dependencies
9:29:21 PM: Started saving maven dependencies
9:29:21 PM: Finished saving maven dependencies
9:29:21 PM: Started saving boot dependencies
9:29:21 PM: Finished saving boot dependencies
9:29:21 PM: Started saving go dependencies
9:29:21 PM: Finished saving go dependencies
9:29:21 PM: Cached node version v8.11.2
9:29:21 PM: Error running command: Build script returned non-zero exit code: 1
9:29:21 PM: Failing build: Failed to build site
9:29:21 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
9:29:21 PM: Finished processing build request in 2m22.14451847s
```

It builds without errors locally but on Netlify i get problems :( 

I don't know how to fix this problem, can somebody help ? 

The one getting errors : https://github.com/Zya04/Portfolio

The one online on netlify : https://github.com/Bennnj/Portfolio

they are absolutely the same, only the content is different...

locally 
```
info bootstrap finished - 2.068 s

success Building CSS — 8.296 s
success Building production JavaScript bundles — 13.253 s
success Building static HTML for pages — 6.760 s
info Done building in 30.38 sec
ivan @ horizonzeromac /Applications/MAMP/htdocs/zya/Portfolio (master)
```
