### ISSUE TITLE
Gatsby Build fails: Cannot read property "pathname" of undefined

### ISSUE THREAD

**Issue by jarodpeachey** [gatsbyjs/gatsby#27701]
## Description

I just started a new gatsby project using my configuration from a previous project. However, after running `npm install` and `gatsby build`, I get an error:

```
failed Building static HTML for pages - 3.529s
error Building static HTML failed for path "/404/"
TypeError: Cannot read property 'pathname' of undefined
```

Here's my `package.json`:

```
{
  "name": "tribesafe-headless",
  "private": true,
  "description": "TribeSafe's Gatsby Site",
  "version": "0.0.1",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,ts,tsx,json,md}\"",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1",
    "production": "npm run clean && npm run build && npm run serve"
  },
  "dependencies": {
    "gatsby": "^2.23.12",
    "gatsby-cli": "^2.12.60",
    "gatsby-plugin-google-tagmanager": "^2.3.15",
    "gatsby-plugin-html-attributes": "^1.0.5",
    "gatsby-plugin-no-javascript": "^2.0.5",
    "gatsby-plugin-no-javascript-utils": "^0.5.0",
    "gatsby-plugin-purgecss": "^5.0.0",
    "gatsby-plugin-react-helmet": "^3.3.9",
    "gatsby-plugin-sass": "^2.3.7",
    "gatsby-plugin-sharp": "^2.6.14",
    "gatsby-plugin-split-css": "^1.0.2",
    "gatsby-react-router-scroll": "^3.0.3",
    "gatsby-source-filesystem": "^2.3.14",
    "gatsby-source-graphql": "^2.6.1",
    "gatsby-transformer-json": "^2.4.12",
    "gatsby-transformer-remark": "^2.8.35",
    "react": "^16.12.0",
    "react-body-classname": "^1.3.1",
    "react-dom": "^16.12.0",
    "react-helmet": "^6.1.0",
    "react-markdown": "^4.3.1",
    "sass": "^1.26.10"
  },
  "devDependencies": {
    "prettier": "2.0.5"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/mindtrustlabs/mindtrust-headless"
  },
  "bugs": {
    "url": "https://github.com/mindtrustlabs/mindtrust-headless/issues"
  }
}

```

### Environment
```
  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.4 - /c/Users/Able Family Life/AppData/Local/Programs/Python/Python37-32/python
  Browsers:
    Edge: 44.19041.423.0
  npmPackages:
    gatsby: ^2.23.12 => 2.24.90
    gatsby-cli: ^2.12.60 => 2.12.113
    gatsby-plugin-google-tagmanager: ^2.3.15 => 2.3.16
    gatsby-plugin-html-attributes: ^1.0.5 => 1.0.5
    gatsby-plugin-no-javascript: ^2.0.5 => 2.0.5
    gatsby-plugin-no-javascript-utils: ^0.5.0 => 0.5.0
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0
    gatsby-plugin-react-helmet: ^3.3.9 => 3.3.14
    gatsby-plugin-sass: ^2.3.7 => 2.3.21
    gatsby-plugin-sharp: ^2.6.14 => 2.6.43
    gatsby-plugin-split-css: ^1.0.2 => 1.0.2
    gatsby-react-router-scroll: ^3.0.3 => 3.0.15
    gatsby-source-filesystem: ^2.3.14 => 2.3.37
    gatsby-source-graphql: ^2.6.1 => 2.7.6
    gatsby-transformer-json: ^2.4.12 => 2.4.15
    gatsby-transformer-remark: ^2.8.35 => 2.8.46
```

**Comment by pvdz** [comment]
I'd suggest to first try and upgrade Gatsby to the current version. the `2.23` minor is a months old. Possibly it's now mixing current versions of the plugin with a very old Gatsby core. I guess this shouldn't happen but it's also a little hard to give any more details without a lot more context :)

**Comment by vladar** [comment]
Hi @jarodpeachey !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by jarodpeachey** [comment]
You can clone https://github.com/jarodpeachey/craft2care and run `npm install`, and then `gatsby build`.

**Comment by abhiaiyer91** [comment]
Hi @jarodpeachey, the reason the build fails is `useLocation`'s return values are not available during SSR. Heres a great article from CSS tricks explaining the issue https://css-tricks.com/how-to-the-get-current-page-url-in-gatsby/

**Comment by jarodpeachey** [comment]
Awesome, thanks for the tip. However, now it says:

```
[                            ]   0.056 s 0/2 0% Building static HTML for pages
C:\Users\Able Family Life\AppData\Roaming\npm\node_modules\gatsby-cli\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

TypeError: Unexpected response from worker: undefined
    at ChildProcessWorker.onMessage (D:\Craft2Care\craft2care\node_modules\jest-worker\build\workers\ChildProcessWorker.js:257:15)
    at ChildProcess.emit (events.js:189:13)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
null
```

**Comment by ascorbic** [comment]
Hi @jarodpeachey ,
Did you fix this? I just cloned your repo and it builds fine. If it's still failing you might need to do the old delete and reinstall node_modules dance.
