### ISSUE TITLE
[Webpack] Some js files are not minified after `gatsby build`

### ISSUE THREAD

**Issue by sebastienfi** [gatsbyjs/gatsby#2771]
Hello!

Some of my JS files are not being minified after `gatsby build`.
These are pretty heavy JS files (1.5Mo), I wonder if that's Webpack ignoring them because it's more than 500Kb.

**Comment by KyleAMathews** [comment]
Do you see warnings in your terminal when you do a build?

Have you tried googling around if this is a thing? I haven't heard of webpack automatically not minifying larger files.

**Comment by sebastienfi** [comment]
@KyleAMathews The thing is that I don't see any error message...
It could be related to that https://github.com/gatsbyjs/gatsby/issues/2318 but in my case I cannot split the file into smaller files because it's what Gatsby generates for me `./public/component---src-pages-index-js-b8616a9891b7fadea35c.js`

**Comment by sebastienfi** [comment]
Maybe you know a command to run post build to isolate and minify these files before publishing ?

**Comment by angeloocana** [comment]
Hi @sebastienfi

I had the same problem, Is it really impossible to break your page in small components?

Could I take a look to your code?

**Comment by KyleAMathews** [comment]
@sebastienfi yeah also like @angeloocana said, I'd focus on slimming down your page. That's a massive amount of JS to load. Odds are there's a lot there you could remove.

**Comment by sebastienfi** [comment]
![pasted image at 2017_10_31 02_35 am](https://user-images.githubusercontent.com/5808108/32408912-6520b79e-c1a1-11e7-81ca-b6f03d2fdad3.png)

**Comment by sebastienfi** [comment]
Ok so I solved my issue.

The problem preventing from identifying the error at the first place was that the error raised by the webpack uglify-js plugin was shut. Problem had been spotted after running Google PageSpeed tests, reporting that one of our files was not being minified.
This kind of errors shouldn't be shut to my opinion. 
@jquense Were you the one working on formatting errors on CLI and choosing which one to filter ? Do you think that this kind of error can be displayed nicely with a message like `Your file [file].js cannot be minified because of Unexpected token: name (allowable_tags) in /public/[file].js line 10351. Your file will be puslihed raw.` ?

Then the source of the problem was a plugin using ES6 variables declaration where Webpack 1 doesn't support it.

To track down the source of the problem, I placed a console log in `node_modules\webpack\lib\optimize\UglifyJsPlugin.js` and ran `yarn build`.

![image](https://user-images.githubusercontent.com/5808108/32415679-c18760fe-c23d-11e7-927a-4e4940805430.png)

From there I could see an error pop out : 
```bash
optimize-chunk-assets err is component---src-pages-index-js-bfc0fa419f4036509684.js JS_Parse_Error {
  message: 'SyntaxError: Unexpected token: name (allowable_tags)',
  filename: 'component---src-pages-index-js-bfc0fa419f4036509684.js',
  line: 10351,
  col: 13,
  pos: 346307,
  stack: 'Error\n    
at new JS_Parse_Error (eval at <anonymous> ([...my-path-to-gatsby-site]\\node_modules\\webpack\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:1547:18)\n
at js_error (eval at <anonymous> ([...my-path-to-gatsby-site]\\node_modules\\webpack\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:1555:11)\n    
at croak (eval at <anonymous> ([...my-path-to-gatsby-site]\\node_modules\\webpack\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2094:9)\n    
at token_error (eval at <anonymous> ([...my-path-to-gatsby-site]\\node_modules\\webpack\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2102:9)\n    
at unexpected (eval at <anonymous> ([...my-path-to-gatsby-site]\\node_modules\\webpack\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2108:9)\n    
at semicolon (eval at <anonymous> ([...my-path-to-gatsby-site]\\node_modules\\webpack\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2128:56)\n    
at simple_statement (eval at <anonymous> ([...my-path-to-gatsby-site]\\node_modules\\webpack\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2319:73)\n    
at eval (eval at <anonymous> ([...my-path-to-gatsby-site]\\node_modules\\webpack\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2188:19)\n    
at eval (eval at <anonymous> ([...my-path-to-gatsby-site]\\node_modules\\webpack\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2141:24)\n    
at block_ (eval at <anonymous> ([...my-path-to-gatsby-site]\\node_modules\\webpack\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2434:20)\n    
at eval (eval at <anonymous> ([...my-path-to-gatsby-site]\\node_modules\\webpack\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2406:25)\n    
at function_ (eval at <anonymous> ([...my-path-to-gatsby-site]\\node_modules\\webpack\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2412:15)\n    
at eval (eval at <anonymous> ([...my-path-to-gatsby-site]\\node_modules\\webpack\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2237:24)\n    
at eval (eval at <anonymous> ([...my-path-to-gatsby-site]\\node_modules\\webpack\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2141:24)\n
at block_ (eval at <anonymous> ([...my-path-to-gatsby-site]\\node_modules\\webpack\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2434:20)\n    
at eval (eval at <anonymous>([...my-path-to-gatsby-site]\\node_modules\\webpack\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2406:25)' }
```

So I openned the file `./public/component---src-pages-index-js-bfc0fa419f4036509684.js` and went on the line 10351. There I found this name `allowable_tags` was declared on a dependency using `let allowable_tags = '';`. I replaced `let` by `var` and the build finally minified my file.

**Comment by jquense** [comment]
The reporter isn't intending to filter out errors, it should surface all of them, would oyu mind seeing where in the code this is getting silenced so we can address it? More than likely it's just a webpack error format that is breaking the formatting somehow and getting lost
