### ISSUE TITLE
Flaky CLI e2e tests

### ISSUE THREAD

**Issue by mxstbr** [gatsbyjs/gatsby#27781]
I've seen these tests specifically fail multiple times across multiple PRs and they always seem to resolve themselves after a CI rerun:

```
 FAIL  __tests__/build-ssr-errors.js (21.407s)
  ● gatsby build (SSR errors) › should log build errors with useful outputs

    expect(received).toBe(expected) // Object.is equality

    Expected: "failed Building static HTML for pages"
    Received: ["success open and validate gatsby-configs - 0.009s", "success load plugins - 0.059s", "success onPreInit - 0.021s", "success delete html and css files from previous builds - 0.004s", "success initialize cache - 0.004s", "success copy gatsby files - 0.025s", "success onPreBootstrap - 0.011s", "success createSchemaCustomization - 0.001s", "success Checking for changed pages - 0.001s", "success source and transform nodes - 0.072s", "success building schema - 0.209s", "info Total nodes: 18, SitePage nodes: 1 (use --verbose for breakdown)", "success createPages - 0.002s", "success Checking for changed pages - 0.000s", "success createPagesStatefully - 0.033s", "success update schema - 0.020s", "success onPreExtractQueries - 0.001s", "success extract queries from components - 0.128s", "success write out redirect data - 0.001s", "success onPostBootstrap - 0.001s", "info bootstrap finished - 4.673s", "success run page queries - 0.008s - 1/1 131.68/s", "success write out requires - 0.003s", "failed Building production JavaScript and CSS bundles - 8.891s", "", " ERROR #98123  WEBPACK", "", "Generating JavaScript bundles failed", "", "polyfill-d1bc6c58897c88a979f3.js from Terser", "Error: Call retries were exceeded", "    at ChildProcessWorker.initialize (/home/circleci/project/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/ChildProcessWorker.js:191:21)", "    at ChildProcessWorker._onExit (/home/circleci/project/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/ChildProcessWorker.js:268:12)", "    at ChildProcess.emit (events.js:182:13)", "    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)", "", "", " ERROR #98123  WEBPACK", "", "Generating JavaScript bundles failed", "", "framework-d4f4657aa3c761f089e7.js from Terser", "Error: Call retries were exceeded", "    at ChildProcessWorker.initialize (/home/circleci/project/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/ChildProcessWorker.js:191:21)", "    at ChildProcessWorker._onExit (/home/circleci/project/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/ChildProcessWorker.js:268:12)", "    at ChildProcess.emit (events.js:182:13)", "    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)", "", "", " ERROR #98123  WEBPACK", "", "Generating JavaScript bundles failed", "", "app-4442bc8f2ce7730714b0.js from Terser", "Error: Call retries were exceeded", "    at ChildProcessWorker.initialize (/home/circleci/project/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/ChildProcessWorker.js:191:21)", "    at ChildProcessWorker._onExit (/home/circleci/project/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/ChildProcessWorker.js:268:12)", "    at ChildProcess.emit (events.js:182:13)", "    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)", "", "", ""]

      19 |         if (!foundMatch) {
      20 |           // This will never pass, but lets user see the issues
    > 21 |           expect(logs).toBe(match)
         |                        ^
      22 |           return
      23 |         }
      24 | 

      at Object.contain (integration-tests/gatsby-cli/test-helpers/matcher.js:21:24)
      at Object.it (integration-tests/gatsby-cli/__tests__/build-ssr-errors.js:16:17)
```

```
 FAIL  __tests__/new.js (66.307s)
  ● gatsby new › a default starter creates a gatsby site

    expect(received).toBe(expected) // Object.is equality

    Expected: "success Saved lockfile."
    Received: ["info Creating new site from git: https://github.com/gatsbyjs/gatsby-starter-default.git", "success Created starter directory layout", "info Installing packages...", "[1/4] Resolving packages...", "[2/4] Fetching packages...", "info If you think this is a bug, please open a bug report with the information provided in \"/home/circleci/project/integration-tests/gatsby-cli/execution-folder/gatsby-default/yarn-error.log\".", "info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.", "", " ERROR ", "", "Command failed with exit code 1: yarnpkg", "", "", "", "  Error: Command failed with exit code 1: yarnpkg", "  ", "  - error.js:56 makeError", "    [gatsby-cli-CMd8YJ]/[execa]/lib/error.js:56:11", "  ", "  - index.js:114 handlePromise", "    [gatsby-cli-CMd8YJ]/[execa]/index.js:114:26", "  ", "  - next_tick.js:68 process._tickCallback", "    internal/process/next_tick.js:68:7", "  ", "", ""]

      19 |         if (!foundMatch) {
      20 |           // This will never pass, but lets user see the issues
    > 21 |           expect(logs).toBe(match)
         |                        ^
      22 |           return
      23 |         }
      24 | 

      at Object.contain (integration-tests/gatsby-cli/test-helpers/matcher.js:21:24)
      at Object.it (integration-tests/gatsby-cli/__tests__/new.js:39:17)
```

**Comment by mxstbr** [comment]
Definitely still an issue. 😬
