### ISSUE TITLE
Module not found. New Gatsby Install

### ISSUE THREAD

**Issue by daviemola** [gatsbyjs/gatsby#28762]
Commands I am running
npm install -g gatsby-cli
I am getting this error

npm ERR! code EEXIST
npm ERR! path C:\Users\David Mola\AppData\Roaming\npm\node_modules\gatsby-cli\cli.js
npm ERR! dest C:\Users\David Mola\AppData\Roaming\npm\gatsby
npm ERR! EEXIST: file already exists, cmd shim 'C:\Users\David Mola\AppData\Roaming\npm\node_modules\gatsby-cli\cli.js' -> 'C:\Users\David Mola\AppData\Roaming\npm\gatsby'
npm ERR! File exists: C:\Users\David Mola\AppData\Roaming\npm\gatsby
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\David Mola\AppData\Roaming\npm-cache\_logs\2020-12-26T20_51_17_426Z-debug.log

**When** I try to run this command
_gatsby_ _add_
I am getting this error

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\David Mola\AppData\Roaming\npm\node_modules\gatsby-cli\cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Any help to make this work will be appreciated

**Comment by daviemola** [comment]
Got it sorted. Ensure and npm global packages are  installed  in the right folder.
