### ISSUE TITLE
Error on Netlify deployment - [(...variantsValue),(...extensions)].flat is not a function

### ISSUE THREAD

**Issue by ohduran** [gatsbyjs/gatsby#29217]
## Description

I seem to have the following error when I deploy my project on Netlify:

```shell
Module build failed (from ./node_modules/gatsby-plugin-postcss/node_modules/postcss-loader/dist/cjs.js):
10:16:27 PM: TypeError: [(...variantsValue),(...extensions)].flat is not a function
```

Funny thing is, this doesn't happen when I do `gatsby build` on my local machine. There, everything seems to be fine.

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

See the contents of the following PR: https://github.com/ohduran/ohduran.github.io/pull/93

And the full deploy logs:

```shell
10:16:00 PM: $ gatsby build
10:16:04 PM: success open and validate gatsby-configs - 0.064s
10:16:05 PM: success load plugins - 0.504s
10:16:05 PM: success onPreInit - 0.030s
10:16:05 PM: success delete html and css files from previous builds - 0.004s
10:16:05 PM: success initialize cache - 0.006s
10:16:05 PM: success copy gatsby files - 0.056s
10:16:05 PM: success onPreBootstrap - 0.016s
10:16:05 PM: success createSchemaCustomization - 0.001s
10:16:06 PM: success Checking for changed pages - 0.000s
10:16:06 PM: success source and transform nodes - 1.331s
10:16:07 PM: success building schema - 0.480s
10:16:07 PM: info Total nodes: 51, SitePage nodes: 4 (use --verbose for breakdown)
10:16:07 PM: success createPages - 0.042s
10:16:07 PM: success Checking for changed pages - 0.000s
10:16:07 PM: success createPagesStatefully - 0.071s
10:16:07 PM: success update schema - 0.034s
10:16:07 PM: success onPreExtractQueries - 0.000s
10:16:07 PM: success extract queries from components - 0.318s
10:16:07 PM: success write out redirect data - 0.001s
10:16:07 PM: success onPostBootstrap - 0.001s
10:16:07 PM: info bootstrap finished - 7.055s
10:16:07 PM: success run static queries - 0.013s - 1/1 78.09/s
10:16:08 PM: success run page queries - 0.714s - 7/7 9.80/s
10:16:08 PM: success write out requires - 0.004s
10:16:27 PM: failed Building production JavaScript and CSS bundles - 19.247s
10:16:27 PM: error Generating JavaScript bundles failed
10:16:27 PM: Module build failed (from ./node_modules/gatsby-plugin-postcss/node_modules/postcss-loader/dist/cjs.js):
10:16:27 PM: TypeError: [(...variantsValue),(...extensions)].flat is not a function
10:16:27 PM:     at /opt/build/repo/node_modules/tailwindcss/lib/util/resolveConfig.js:219:73
10:16:27 PM:     at baseMergeDeep (/opt/build/repo/node_modules/lodash/_baseMergeDeep.js:42:7)
10:16:27 PM:     at /opt/build/repo/node_modules/lodash/_baseMerge.js:27:7
10:16:27 PM:     at /opt/build/repo/node_modules/lodash/_createBaseFor.js:17:11
10:16:27 PM:     at baseMerge (/opt/build/repo/node_modules/lodash/_baseMerge.js:24:3)
10:16:27 PM:     at /opt/build/repo/node_modules/lodash/mergeWith.js:36:3
10:16:27 PM:     at /opt/build/repo/node_modules/lodash/_createAssigner.js:30:9
10:16:27 PM:     at apply (/opt/build/repo/node_modules/lodash/_apply.js:15:25)
10:16:27 PM:     at /opt/build/repo/node_modules/lodash/_overRest.js:32:12
10:16:27 PM:     at mergeVariantExtensions (/opt/build/repo/node_modules/tailwindcss/lib/util/resolveConfig.js:218:33)
10:16:27 PM:     at resolveVariants (/opt/build/repo/node_modules/tailwindcss/lib/util/resolveConfig.js:235:10)
10:16:27 PM:     at resolveConfig (/opt/build/repo/node_modules/tailwindcss/lib/util/resolveConfig.js:271:15)
10:16:27 PM:     at /opt/build/repo/node_modules/tailwindcss/lib/index.js:75:37
10:16:27 PM:     at /opt/build/repo/node_modules/tailwindcss/lib/processTailwindFeatures.js:52:20
10:16:27 PM:     at LazyResult.runOnRoot (/opt/build/repo/node_modules/postcss/lib/lazy-result.js:303:16)
10:16:27 PM:     at LazyResult.runAsync (/opt/build/repo/node_modules/postcss/lib/lazy-result.js:355:26)
10:16:27 PM: error Generating JavaScript bundles failed
10:16:27 PM: Module build failed (from ./node_modules/gatsby-plugin-postcss/node_modules/postcss-loader/dist/cjs.js):
10:16:27 PM: TypeError: [(...variantsValue),(...extensions)].flat is not a function
10:16:27 PM:     at /opt/build/repo/node_modules/tailwindcss/lib/util/resolveConfig.js:219:73
10:16:27 PM:     at baseMergeDeep (/opt/build/repo/node_modules/lodash/_baseMergeDeep.js:42:7)
10:16:27 PM:     at /opt/build/repo/node_modules/lodash/_baseMerge.js:27:7
10:16:27 PM:     at /opt/build/repo/node_modules/lodash/_createBaseFor.js:17:11
10:16:27 PM:     at baseMerge (/opt/build/repo/node_modules/lodash/_baseMerge.js:24:3)
10:16:27 PM:     at /opt/build/repo/node_modules/lodash/mergeWith.js:36:3
10:16:27 PM:     at /opt/build/repo/node_modules/lodash/_createAssigner.js:30:9
10:16:27 PM:     at apply (/opt/build/repo/node_modules/lodash/_apply.js:15:25)
10:16:27 PM:     at /opt/build/repo/node_modules/lodash/_overRest.js:32:12
10:16:27 PM:     at mergeVariantExtensions (/opt/build/repo/node_modules/tailwindcss/lib/util/resolveConfig.js:218:33)
10:16:27 PM:     at resolveVariants (/opt/build/repo/node_modules/tailwindcss/lib/util/resolveConfig.js:235:10)
10:16:27 PM:     at resolveConfig (/opt/build/repo/node_modules/tailwindcss/lib/util/resolveConfig.js:271:15)
10:16:27 PM:     at /opt/build/repo/node_modules/tailwindcss/lib/index.js:75:37
10:16:27 PM:     at /opt/build/repo/node_modules/tailwindcss/lib/processTailwindFeatures.js:52:20
10:16:27 PM:     at LazyResult.runOnRoot (/opt/build/repo/node_modules/postcss/lib/lazy-result.js:303:16)
10:16:27 PM:     at LazyResult.runAsync (/opt/build/repo/node_modules/postcss/lib/lazy-result.js:355:26)
10:16:27 PM: error Generating JavaScript bundles failed
10:16:27 PM: [(...variantsValue),(...extensions)].flat is not a function
10:16:27 PM: error Generating JavaScript bundles failed
10:16:27 PM: [(...variantsValue),(...extensions)].flat is not a function
10:16:27 PM: ​
10:16:27 PM: ────────────────────────────────────────────────────────────────
10:16:27 PM:   "build.command" failed                                        
10:16:27 PM: ────────────────────────────────────────────────────────────────
```

Given the circumstances I hope it's enough information to reproduce the bug. Do let me know if there's more information needed.

### Expected result

The build should go fine and the deploy would eventually happened.

### Actual result

Netlify's build failed.

### Environment

System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.6.0 - /usr/local/bin/node
    npm: 7.4.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.96
    Firefox: 85.0
    Safari: 14.0.2
  npmPackages:
    gatsby: ^2.26.1 => 2.31.1
    gatsby-plugin-feed-mdx: ^1.0.1 => 1.0.1
    gatsby-plugin-mdx: ^1.9.0 => 1.9.0
    gatsby-plugin-postcss: ^3.6.0 => 3.6.0
    gatsby-source-filesystem: ^2.10.0 => 2.10.0
    gatsby-source-github-api: ^0.2.1 => 0.2.1
  npmGlobalPackages:
    gatsby-cli: 2.18.0

**Comment by LekoArts** [comment]
Thank you for opening this!

> Funny thing is, this doesn't happen when I do gatsby build on my local machine. There, everything seems to be fine.

This is an indication that your error is inside Netlify and not necessarily something with Gatsby.

If you Google the error (in combination with Tailwind CSS) you'll get:
https://stackoverflow.com/questions/65311936/node-error-when-i-run-npm-with-laravel-breeze

So your Netlify instance is probably running Node 10, and not the required Node 12 version. If that doesn't work please reach out to Netlify's support.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by ohduran** [comment]
Thanks so much for your help @LekoArts I managed to solve the issue by adding a `.nvmrc` file with the correct version.

**Comment by DanielRuf** [comment]
For others who come here from the Hyva checkout module for Magento 2, simply change your node version to 12 or newer (nvm, nodenv etc).
