### ISSUE TITLE
[gatsby-plugin-netlify] error when building schema

### ISSUE THREAD

**Issue by danielkov** [gatsbyjs/gatsby#2925]
`gatsby --version`: 1.1.20
`node --version`: 8.6.0
## Summary

I am trying to set some basic security headers on Netlify, using `gatsby-plugin-netlify` and so far without much success. It appears to run into some conflicts with the GraphQL Schema builder.

My config related to the plugin:
```javascript
{
      resolve: 'gatsby-plugin-netlify',
      options: {
        headers: {
          '/*': [
            `Content-Security-Policy: script-src 'self'`,
            `X-Frame-Options: DENY`,
            `X-Xss-Protection: 1; mode=block`,
            `X-Content-Type-Options: nosniff`,
            `Referrer-Policy: same-origin`,
            `Expect-CT: enforce,max-age=604800`
          ]
       }
    }
}
```

The error I'm getting when running `gatsby develop` or `gatsby build`:

```bash
⠁ Name "__" must not begin with "__", which is reserved by GraphQL introspection. In a future release of graphql this will become a hard error.
    at assertValidName (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\utilities\assertValidName.js:37:19)
    at C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\type\definition.js:693:44
    at Array.forEach (<anonymous>)
    at GraphQLInputObjectType._defineFieldMap (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\type\definition.js:692:16)
    at GraphQLInputObjectType.getFields (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\type\definition.js:681:49)
    at typeMapReducer (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\type\schema.js:223:26)
    at C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\type\schema.js:226:20
    at Array.forEach (<anonymous>)
    at typeMapReducer (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\type\schema.js:224:28)
    at C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\type\schema.js:226:20
    at Array.forEach (<anonymous>)
    at typeMapReducer (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\type\schema.js:224:28)
    at Array.reduce (<anonymous>)
    at C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\type\schema.js:216:36
    at Array.forEach (<anonymous>)
    at typeMapReducer (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\type\schema.js:209:27)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\type\schema.js:97:34)
    at _callee$ (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\gatsby\dist\schema\index.js:52:20)
    at tryCatch (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:117:21)
```

This particular time it was running on a Windows machine but the issue persists on my Linux machine too so I would imagine the Netlify servers wouldn't be able to make use of this either.

I believe the issue is caused by the plugin prefixing some things with "__", thus tripping up GraphQL Builder when it tries to build the schema. I did place the config part as the last plugin, as suggested.

**Comment by benedfit** [comment]
I'm experiencing this issue too

**Comment by KyleAMathews** [comment]
Would either of you like to put together a PR fixing the issue?
