### ISSUE TITLE
Gatsby build now requires sudo

### ISSUE THREAD

**Issue by chris-hammond** [gatsbyjs/gatsby#29255]
## Description

Attempting to run `gatsby build` as a non-privileged user in a Linux container (e.g. Netlify, CircleCI, etc.) results in a connection timeout error, presumably due to gatsby attempting to do something using a low-numbered TCP port. The displayed error is as follows:
```
$ gatsby build
success open and validate gatsby-configs - 0.078s
success load plugins - 0.836s
success onPreInit - 0.033s
success delete html and css files from previous builds - 0.002s
success initialize cache - 0.004s
success copy gatsby files - 0.026s
success onPreBootstrap - 0.253s
success createSchemaCustomization - 0.028s
/tmp/workspace/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: socket hang up
    at connResetException (internal/errors.js:609:14)
    at TLSSocket.socketOnEnd (_http_client.js:458:23)
    at TLSSocket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET'
}
error Command failed with exit code 7.
```

Rerunning the command as `sudo gatsby build` succeeds.

### Steps to reproduce

Using the starter example, run `yarn build` using CircleCI.

### Expected result

The site should build.

### Actual result

An ECONNRESET error occurs.

### Environment

```
System:
    OS: Linux 4.15 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (36) x64 Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.20.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
  Browsers:
    Firefox: 84.0.2
  npmPackages:
    gatsby: ^2.24.12 => 2.31.1
    gatsby-background-image: ^1.1.1 => 1.4.0
    gatsby-image: ^2.1.4 => 2.10.0
    gatsby-link: ^2.10.0 => 2.10.0
    gatsby-parallel-runner: ^1.3.0 => 1.3.0
    gatsby-plugin-anchor-links: ^1.1.1 => 1.2.1
    gatsby-plugin-env-variables: ^2.0.0 => 2.0.0
    gatsby-plugin-google-analytics: ^2.3.13 => 2.10.0
    gatsby-plugin-manifest: ^2.4.21 => 2.11.0
    gatsby-plugin-netlify: ^2.0.6 => 2.10.0
    gatsby-plugin-offline: ^3.2.21 => 3.9.0
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0
    gatsby-plugin-react-helmet: ^3.0.4 => 3.9.0
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.5
    gatsby-plugin-sass: ^2.0.7 => 2.8.0
    gatsby-plugin-sharp: ^2.6.23 => 2.13.3
    gatsby-plugin-sitemap: ^2.3.5 => 2.11.0
    gatsby-plugin-tawk: ^1.0.0 => 1.0.0
    gatsby-plugin-webfonts: ^1.1.3 => 1.1.4
    gatsby-remark-copy-linked-files: ^2.3.12 => 2.9.0
    gatsby-remark-images: ^3.3.22 => 3.10.0
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0
    gatsby-source-filesystem: ^2.3.23 => 2.10.0
    gatsby-transformer-remark: ^2.8.27 => 2.15.0
    gatsby-transformer-sharp: ^2.1.9 => 2.11.0
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by chris-hammond** [comment]
After various attempts to reproduce minimally, I located the issue as a call to `got` in gatsby-node.js that was hanging. We can close this issue.
