### ISSUE TITLE
Fails to run after installing with `pnpm`

### ISSUE THREAD

**Issue by vjpr** [gatsbyjs/gatsby#2948]
```
Error: Cannot find module 'regenerator-runtime/runtime'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Vaughan/nvm/versions/node/v8.9.0/pnpm-global/1/node_modules/.registry.npmjs.org/gatsby-cli/1.1.20/node_modules/gatsby-cli/lib/index.js:88:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

---

This is usually a babel transpilation config issue.

---

BTW, pnpm does not create a flat `node_modules` structure. So if you depend on a module in code, it must be present in the closest package.json - relying on hoisting modules is bad.

Also, related: https://github.com/gatsbyjs/gatsby/issues/1815

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍

**Comment by vjpr** [comment]
To use pnpm with Gatsby see https://github.com/pnpm/pnpm/issues/991#issuecomment-446330885
