### ISSUE TITLE
Gastby installation fails in starter Code Sandbox

### ISSUE THREAD

**Issue by jaredjgebel** [gatsbyjs/gatsby#29502]
## Description

The initial installation on the example Code Sandbox site for [gatsby-starter-default](https://codesandbox.io/s/github/gatsbyjs/gatsby-starter-default) fails.

### Steps to reproduce

Visit [Code Sandbox](https://codesandbox.io/s/github/gatsbyjs/gatsby-starter-default), watch initial develop fail. Received this specific error in Chrome. Meanwhile, on Edge and Firefox, the starter sandbox hangs at ```Sandbox Container: Sandbox [id] started```.

### Expected result

Code sandbox should run installation successfully.

### Actual result

```
An unexpected error occurred: "ENOSPC: no space left on device, copyfile '/home/sandbox/.cache/yarn/v6/npm-@babel-plugin-transform-named-capturing-groups-regex-7.12.13-2213725a5f5bbbe364b50c3ba5998c9599c5c9d9-integrity/node_modules/@babel/plugin-transform-named-capturing-groups-regex/package.json' -> '/sandbox/node_modules/@babel/plugin-transform-named-capturing-groups-regex/package.json'".
info If you think this is a bug, please open a bug report with the information provided in "/sandbox/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> Sandbox Container: Sandbox m4q82k8ry9 started
yarn run v1.22.10
$ gatsby develop
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './util/escape'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/sandbox/node_modules/cross-spawn/lib/parse.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment
OS: Windows 10 10.0.19041
Chrome: 88.0.4324.150
Edge: Spartan (44.19041.423.0), Chromium (88.0.705.68)
Firefox: 85.0.2

**Comment by LekoArts** [comment]
Hello!

Please reach out to codesandbox for that matter, we can't affect any upstream issues:
https://github.com/codesandbox/codesandbox-client
https://codesandbox.io/?from-app=1

Thanks!
