### ISSUE TITLE
Incorrect OutputType error with gatsby-source-filesystem and npm link

### ISSUE THREAD

**Issue by lorensr** [gatsbyjs/gatsby#29774]
## Description

When I use `npm link` to use the local version of a theme, `gatsby develop` hangs on `building schema` with the error `Error: File.publicURL provided incorrect OutputType: 'String'`, seemingly due to `gatsby-source-filesystem`. Several others had this error in various circumstances: see https://github.com/gatsbyjs/gatsby/issues/20718.

### Steps to reproduce

```
git clone git@github.com:apollographql/gatsby-theme-apollo.git
cd gatsby-theme-apollo/packages/gatsby-theme-apollo-docs/
npm install
npm link
```

```
git clone git@github.com:apollographql/apollo-client.git
cd apollo-client/docs
npm install
npm link gatsby-theme-apollo-docs
npm start
```

### Expected result

`gatsby develop` should finish starting up.

### Actual result

`gatsby develop` hangs:

```
$ npm start

> @ prestart /Users/me/test/grepro/apollo-client/docs
> gatsby clean

info Deleting .cache, public, /Users/me/test/grepro/apollo-client/docs/node_modules/.cache/babel-loader,
/Users/me/test/grepro/apollo-client/docs/node_modules/.cache/terser-webpack-plugin
info Successfully deleted directories


> @ start /Users/me/test/grepro/apollo-client/docs
> gatsby develop

success open and validate gatsby-configs - 0.342s
success load plugins - 3.360s
success onPreInit - 0.029s
success initialize cache - 0.006s
success copy gatsby files - 0.074s
success onPreBootstrap - 0.015s
success createSchemaCustomization - 0.220s
warn code block or inline code language not specified in markdown. applying generic code block
warn Browserslist: caniuse-lite is outdated. Please run next command `npm update`

 ERROR 

[BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.

success Checking for changed pages - 0.001s
success source and transform nodes - 35.610s
warn Plugin `gatsby-source-filesystem` has customized the built-in Gatsby GraphQL type `File`. This is allowed, but could potentially cause
conflicts.

 ERROR 

Missing onError handler for invocation 'building-schema', error was 'Error: File.publicURL provided incorrect OutputType: 'String''.
Stacktrace was 'Error: File.publicURL provided incorrect OutputType: 'String'
    at TypeMapper.convertOutputFieldConfig (/Users/me/test/grepro/apollo-client/docs/node_modules/graphql-compose/lib/TypeMapper.js:294:15)
    at resolveOutputConfigAsThunk (/Users/me/test/grepro/apollo-client/docs/node_modules/graphql-compose/lib/utils/configAsThunk.js:19:41)
    at ObjectTypeComposer.getFieldConfig
(/Users/me/test/grepro/apollo-client/docs/node_modules/graphql-compose/lib/ObjectTypeComposer.js:300:58)
    at fieldNames.forEach.fieldName
(/Users/me/test/grepro/apollo-client/docs/node_modules/graphql-compose/lib/utils/toInputObjectType.js:44:19)
    at Array.forEach (<anonymous>)
    at toInputObjectType (/Users/me/test/grepro/apollo-client/docs/node_modules/graphql-compose/lib/utils/toInputObjectType.js:38:14)
    at ObjectTypeComposer.getInputTypeComposer
(/Users/me/test/grepro/apollo-client/docs/node_modules/graphql-compose/lib/ObjectTypeComposer.js:600:84)
    at getSortInput (/Users/me/test/grepro/apollo-client/docs/node_modules/gatsby/src/schema/types/sort.ts:152:42)
    at addTypeToRootQuery (/Users/me/test/grepro/apollo-client/docs/node_modules/gatsby/src/schema/schema.js:1133:23)
    at processTypeComposer (/Users/me/test/grepro/apollo-client/docs/node_modules/gatsby/src/schema/schema.js:216:13)'

⠹ building schema
```

### Environment

```
  System:
    OS: macOS 11.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.22.0 - ~/.nvm/versions/node/v10.22.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v10.22.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.192
    Safari: 14.0.3
  npmPackages:
    gatsby: 2.32.4 => 2.32.4
    gatsby-theme-apollo-docs: 4.6.1 => 4.6.1
  npmGlobalPackages:
    gatsby-cli: 2.19.1
    gatsby-theme-apollo-docs: 4.6.1
```

**Comment by vladar** [comment]
This can potentially happen with outdated `gatsby-source-filesystem`. Have you tried bumping `gatsby-source-filesystem` version to the latest version?

**Comment by lorensr** [comment]
That worked, thank you! ☺️

**Comment by lorensr** [comment]
I also found that in order to get it working with a local theme, I had to use https://github.com/hugomrdias/connect-deps/ instead of `npm link`.
