### ISSUE TITLE
Failing tests on master?

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#2977]
I have a clone of Gatsby, with HEAD set to the latest commit from master (6780cac881c8c6243ea2d6162299f5c6c2229a8d). 

I run:

- `rm -rf node_modules/`
- `yarn run bootstrap`
- `yarn test`

and get 6 failing tests. Is that expected? Should the tests all be passing?

Versions:
```shell
node --version
v8.7.0
yarn --version
1.3.2
```

<details>
  <summary>Click to see test summary</summary>

```
Summary of all failing tests
 FAIL  packages/gatsby/src/schema/__tests__/infer-graphql-type-test.js
  ● GraphQL type inferance › Linked inference by __NODE convention › Errors clearly when missing nodes

    expect(function).toThrow(string)

    Expected the function to throw an error matching:
      "Encountered an error trying to infer a GraphQL type for: \"linked___NODE\". There is no corresponding node with the id field matching: \"baz\""
    Instead, it threw:
      Invariant Violation: Encountered an error trying to infer a GraphQL type for: "linked___NODE". There is no corresponding GraphQL type "Bar" available to link to this node.
          at invariant (node_modules/invariant/invariant.js:42:15)
          at validateField (packages/gatsby/src/schema/infer-graphql-type.js:561:58)
          at inferFromFieldName (packages/gatsby/src/schema/infer-graphql-type.js:566:731)
          at _.each (packages/gatsby/src/schema/infer-graphql-type.js:600:93)
          at node_modules/lodash/lodash.js:4944:15
          at baseForOwn (node_modules/lodash/lodash.js:3001:24)
          at node_modules/lodash/lodash.js:4913:18
          at Function.forEach (node_modules/lodash/lodash.js:9359:14)
          at inferObjectStructureFromNodes (packages/gatsby/src/schema/infer-graphql-type.js:592:120)
          at expect (packages/gatsby/src/schema/__tests__/infer-graphql-type-test.js:273:9)
          at Object.it (packages/gatsby/src/schema/__tests__/infer-graphql-type-test.js:277:10)
              at new Promise (<anonymous>)
          at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
              at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)

      at Object.it (packages/gatsby/src/schema/__tests__/infer-graphql-type-test.js:277:10)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

 FAIL  packages/gatsby/src/schema/__tests__/build-node-types-test.js
  ● build-node-types › should build types

    TypeError: Cannot read property 'map' of undefined

      at _.flatMap (packages/gatsby/src/schema/build-node-types.js:55:40)
      at arrayMap (node_modules/lodash/lodash.js:660:23)
      at map (node_modules/lodash/lodash.js:9571:14)
      at Function.flatMap (node_modules/lodash/lodash.js:9274:26)
      at node_modules/lodash/lodash.js:4379:28
      at arrayReduce (node_modules/lodash/lodash.js:704:21)
      at baseWrapperValue (node_modules/lodash/lodash.js:4378:14)
      at LodashWrapper.wrapperValue (node_modules/lodash/lodash.js:9067:14)
      at createNodeFields (packages/gatsby/src/schema/build-node-types.js:59:5)
      at fields (packages/gatsby/src/schema/build-node-types.js:143:21)
      at resolveThunk (node_modules/graphql/type/definition.js:168:40)
      at defineFieldMap (node_modules/graphql/type/definition.js:349:18)
      at GraphQLObjectType.getFields (node_modules/graphql/type/definition.js:310:44)
      at typeMapReducer (node_modules/graphql/type/schema.js:208:25)
      at node_modules/graphql/type/schema.js:218:20
          at Array.forEach (<anonymous>)
      at typeMapReducer (node_modules/graphql/type/schema.js:209:27)
          at Array.reduce (<anonymous>)
      at new GraphQLSchema (node_modules/graphql/type/schema.js:97:34)
      at Object.beforeEach (packages/gatsby/src/schema/__tests__/build-node-types-test.js:48:14)
          at <anonymous>

  ● build-node-types › should build types

    expect(received).toHaveLength(length)

    Expected value to have length:
      3
    Received:
      ["bar", "parent", "relative", "child"]
    received.length:
      4

      at Object.it (packages/gatsby/src/schema/__tests__/build-node-types-test.js:57:32)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>

  ● build-node-types › should result in a valid queryable schema

    TypeError: Cannot read property 'map' of undefined

      at _.flatMap (packages/gatsby/src/schema/build-node-types.js:55:40)
      at arrayMap (node_modules/lodash/lodash.js:660:23)
      at map (node_modules/lodash/lodash.js:9571:14)
      at Function.flatMap (node_modules/lodash/lodash.js:9274:26)
      at node_modules/lodash/lodash.js:4379:28
      at arrayReduce (node_modules/lodash/lodash.js:704:21)
      at baseWrapperValue (node_modules/lodash/lodash.js:4378:14)
      at LodashWrapper.wrapperValue (node_modules/lodash/lodash.js:9067:14)
      at createNodeFields (packages/gatsby/src/schema/build-node-types.js:59:5)
      at fields (packages/gatsby/src/schema/build-node-types.js:143:21)
      at resolveThunk (node_modules/graphql/type/definition.js:168:40)
      at defineFieldMap (node_modules/graphql/type/definition.js:349:18)
      at GraphQLObjectType.getFields (node_modules/graphql/type/definition.js:310:44)
      at typeMapReducer (node_modules/graphql/type/schema.js:208:25)
      at node_modules/graphql/type/schema.js:218:20
          at Array.forEach (<anonymous>)
      at typeMapReducer (node_modules/graphql/type/schema.js:209:27)
          at Array.reduce (<anonymous>)
      at new GraphQLSchema (node_modules/graphql/type/schema.js:97:34)
      at Object.beforeEach (packages/gatsby/src/schema/__tests__/build-node-types-test.js:48:14)
          at <anonymous>

  ● build-node-types › should result in a valid queryable schema

    Must provide schema

      at invariant (node_modules/graphql/jsutils/invariant.js:18:11)
      at validate (node_modules/graphql/validation/validate.js:57:37)
      at node_modules/graphql/graphql.js:69:51
          at new Promise (<anonymous>)
      at graphqlImpl (node_modules/graphql/graphql.js:59:10)
      at graphql (node_modules/graphql/graphql.js:48:227)
      at runQuery (packages/gatsby/src/schema/__tests__/build-node-types-test.js:10:34)
      at Object.it (packages/gatsby/src/schema/__tests__/build-node-types-test.js:61:45)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>

  ● build-node-types › should link children automatically

    TypeError: Cannot read property 'map' of undefined

      at _.flatMap (packages/gatsby/src/schema/build-node-types.js:55:40)
      at arrayMap (node_modules/lodash/lodash.js:660:23)
      at map (node_modules/lodash/lodash.js:9571:14)
      at Function.flatMap (node_modules/lodash/lodash.js:9274:26)
      at node_modules/lodash/lodash.js:4379:28
      at arrayReduce (node_modules/lodash/lodash.js:704:21)
      at baseWrapperValue (node_modules/lodash/lodash.js:4378:14)
      at LodashWrapper.wrapperValue (node_modules/lodash/lodash.js:9067:14)
      at createNodeFields (packages/gatsby/src/schema/build-node-types.js:59:5)
      at fields (packages/gatsby/src/schema/build-node-types.js:143:21)
      at resolveThunk (node_modules/graphql/type/definition.js:168:40)
      at defineFieldMap (node_modules/graphql/type/definition.js:349:18)
      at GraphQLObjectType.getFields (node_modules/graphql/type/definition.js:310:44)
      at typeMapReducer (node_modules/graphql/type/schema.js:208:25)
      at node_modules/graphql/type/schema.js:218:20
          at Array.forEach (<anonymous>)
      at typeMapReducer (node_modules/graphql/type/schema.js:209:27)
          at Array.reduce (<anonymous>)
      at new GraphQLSchema (node_modules/graphql/type/schema.js:97:34)
      at Object.beforeEach (packages/gatsby/src/schema/__tests__/build-node-types-test.js:48:14)
          at <anonymous>

  ● build-node-types › should link children automatically

    Must provide schema

      at invariant (node_modules/graphql/jsutils/invariant.js:18:11)
      at validate (node_modules/graphql/validation/validate.js:57:37)
      at node_modules/graphql/graphql.js:69:51
          at new Promise (<anonymous>)
      at graphqlImpl (node_modules/graphql/graphql.js:59:10)
      at graphql (node_modules/graphql/graphql.js:48:227)
      at runQuery (packages/gatsby/src/schema/__tests__/build-node-types-test.js:10:34)
      at Object.it (packages/gatsby/src/schema/__tests__/build-node-types-test.js:82:28)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>

  ● build-node-types › should create typed children fields

    TypeError: Cannot read property 'map' of undefined

      at _.flatMap (packages/gatsby/src/schema/build-node-types.js:55:40)
      at arrayMap (node_modules/lodash/lodash.js:660:23)
      at map (node_modules/lodash/lodash.js:9571:14)
      at Function.flatMap (node_modules/lodash/lodash.js:9274:26)
      at node_modules/lodash/lodash.js:4379:28
      at arrayReduce (node_modules/lodash/lodash.js:704:21)
      at baseWrapperValue (node_modules/lodash/lodash.js:4378:14)
      at LodashWrapper.wrapperValue (node_modules/lodash/lodash.js:9067:14)
      at createNodeFields (packages/gatsby/src/schema/build-node-types.js:59:5)
      at fields (packages/gatsby/src/schema/build-node-types.js:143:21)
      at resolveThunk (node_modules/graphql/type/definition.js:168:40)
      at defineFieldMap (node_modules/graphql/type/definition.js:349:18)
      at GraphQLObjectType.getFields (node_modules/graphql/type/definition.js:310:44)
      at typeMapReducer (node_modules/graphql/type/schema.js:208:25)
      at node_modules/graphql/type/schema.js:218:20
          at Array.forEach (<anonymous>)
      at typeMapReducer (node_modules/graphql/type/schema.js:209:27)
          at Array.reduce (<anonymous>)
      at new GraphQLSchema (node_modules/graphql/type/schema.js:97:34)
      at Object.beforeEach (packages/gatsby/src/schema/__tests__/build-node-types-test.js:48:14)
          at <anonymous>

  ● build-node-types › should create typed children fields

    Must provide schema

      at invariant (node_modules/graphql/jsutils/invariant.js:18:11)
      at validate (node_modules/graphql/validation/validate.js:57:37)
      at node_modules/graphql/graphql.js:69:51
          at new Promise (<anonymous>)
      at graphqlImpl (node_modules/graphql/graphql.js:59:10)
      at graphql (node_modules/graphql/graphql.js:48:227)
      at runQuery (packages/gatsby/src/schema/__tests__/build-node-types-test.js:10:34)
      at Object.it (packages/gatsby/src/schema/__tests__/build-node-types-test.js:98:28)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>

  ● build-node-types › should create typed child field for singular children

    TypeError: Cannot read property 'map' of undefined

      at _.flatMap (packages/gatsby/src/schema/build-node-types.js:55:40)
      at arrayMap (node_modules/lodash/lodash.js:660:23)
      at map (node_modules/lodash/lodash.js:9571:14)
      at Function.flatMap (node_modules/lodash/lodash.js:9274:26)
      at node_modules/lodash/lodash.js:4379:28
      at arrayReduce (node_modules/lodash/lodash.js:704:21)
      at baseWrapperValue (node_modules/lodash/lodash.js:4378:14)
      at LodashWrapper.wrapperValue (node_modules/lodash/lodash.js:9067:14)
      at createNodeFields (packages/gatsby/src/schema/build-node-types.js:59:5)
      at fields (packages/gatsby/src/schema/build-node-types.js:143:21)
      at resolveThunk (node_modules/graphql/type/definition.js:168:40)
      at defineFieldMap (node_modules/graphql/type/definition.js:349:18)
      at GraphQLObjectType.getFields (node_modules/graphql/type/definition.js:310:44)
      at typeMapReducer (node_modules/graphql/type/schema.js:208:25)
      at node_modules/graphql/type/schema.js:218:20
          at Array.forEach (<anonymous>)
      at typeMapReducer (node_modules/graphql/type/schema.js:209:27)
          at Array.reduce (<anonymous>)
      at new GraphQLSchema (node_modules/graphql/type/schema.js:97:34)
      at Object.beforeEach (packages/gatsby/src/schema/__tests__/build-node-types-test.js:48:14)
          at <anonymous>

  ● build-node-types › should create typed child field for singular children

    Must provide schema

      at invariant (node_modules/graphql/jsutils/invariant.js:18:11)
      at validate (node_modules/graphql/validation/validate.js:57:37)
      at node_modules/graphql/graphql.js:69:51
          at new Promise (<anonymous>)
      at graphqlImpl (node_modules/graphql/graphql.js:59:10)
      at graphql (node_modules/graphql/graphql.js:48:227)
      at runQuery (packages/gatsby/src/schema/__tests__/build-node-types-test.js:10:34)
      at Object.it (packages/gatsby/src/schema/__tests__/build-node-types-test.js:114:28)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>


Test Suites: 2 failed, 60 passed, 62 total
Tests:       6 failed, 4 skipped, 401 passed, 411 total
Snapshots:   146 passed, 146 total
Time:        15.752s
```
</details>

**Comment by calcsam** [comment]
No, this isn't normal. Is this still occurring? What's your system information?

**Comment by m-allanson** [comment]
Hmm.. Closing as this works on a fresh checkout of Gatsby.

My previously checked out copy of Gatsby (updated to commit 18c513c01d9f8acfbcc944c8c3a957a6e549f54c) still has test failures, but that must be a problem on my side. (I'm on MacOS Sierra 10.12.6)
