### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by MichaelCereda** [gatsbyjs/gatsby#301]
gatsby develop works perfectly and smoothly..
when i try to build (gatsby build) i receive the following error..
I couldn't come up with an answer.

```
$ gatsby build
Generating static html pages
failed at generating static html pages

....node_modules/gatsby/dist/bin/cli.js:39
      throw err;
      ^
Error: ReferenceError: _ is not defined
    at Signature.render (bundle.js:73722:21)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (bundle.js:14218:35)

    at ReactCompositeComponentMixin._renderValidatedComponent (bundle.js:14238:33)
    at ReactCompositeComponentMixin.performInitialMount (bundle.js:13822:31)
    at ReactCompositeComponentMixin.mountComponent (bundle.js:13753:22)
    at Object.ReactReconciler.mountComponent (bundle.js:7078:36)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (bundle.js:13025:45)
    at ReactDOMComponent.Mixin._createContentMarkup (bundle.js:9994:33)
    at ReactDOMComponent.Mixin.mountComponent (bundle.js:9879:30)
    at Object.ReactReconciler.mountComponent (bundle.js:7078:36)
```

I'm on mac.
Thanks in advance

**Comment by KyleAMathews** [comment]
Do you have a component names Signature? Perhaps it's missing an import for underscore/lodash?

**Comment by MichaelCereda** [comment]
Yes... my fault.

I apologize, troubleshooting while tired is the worst thing to do when you have deadlines.
Thanks

**Comment by KyleAMathews** [comment]
👍
