### ISSUE TITLE
[gatsby-source-wordpress] Previews break after making a menu item change following a content preview

### ISSUE THREAD

**Issue by peteluffman** [gatsbyjs/gatsby#30203]
## Description

Gatsby fails to rebuild after making a menu item change following a content preview. The only way to get previews working again is to run `gatsby clean`.

Restarting develop and making a menu change without a prior content change completes successfully. 

I'm using my own custom menu locations, not the WP Gatsby ones.

My static query for the menu location is as follows: 

```
query HeaderMenuQuery {
    primary: wpMenu(slug: { eq: "primary" }) {
      menuItems {
        nodes {
          label
          url
          description
          id
          parentId
          megaMenu {
            columnCount
          }
          connectedNode {
            node {
              uri
              ... on WpPage {
                nodeType
              }
              ... on WpServiceCategory {
                nodeType
              }
              ... on WpLocation {
                nodeType
                locationDetails {
                  gallery {
                    ...WpImage
                  }
                }
              }
              ... on WpLocationCategory {
                nodeType
                name
                locations {
                  nodes {
                    locationDetails {
                      gallery {
                        ...WpImage
                        localFile {
                          ...Thumbnail
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
}
```

### Steps to reproduce

1. Open a page or post in wordpress. 
2. Make a change to the title
3. Click 'Preview changes'
4. Wait for preview to complete
5. Edit a menu item, change label or delete something.
6. Save

### Expected result

Rebuild should complete successfully.

### Actual result

Error:

```
Missing onError handler for invocation 'rebuildSchemaWithSitePage', error was 'Error: Cannot get field
'_xwpGatsbyNodeModified' from type 'SitePageContext'. Field does not exist.'. Stacktrace was 'Error: Cannot get
field '_xwpGatsbyNodeModified' from type 'SitePageContext'. Field does not exist.
    at ObjectTypeComposer.getField (/Users/pete/Projects/website-name/node_modules/graphql-compose/lib/ObjectTypeComposer.js:196:13)
    at ObjectTypeComposer.getFieldExtensions (/Users/pete/Projects/website-name/node_modules/graphql-compose/lib/ObjectTypeComposer.js:1127:24)
    at ObjectTypeComposer.getFieldExtension (/Users/pete/Projects/website-name/node_modules/graphql-compose/lib/ObjectTypeComposer.js:1151:29)
    at forEach (/Users/pete/Projects/website-name/node_modules/gatsby/src/schema/types/sort.ts:73:24)
    at Array.forEach (<anonymous>)
    at convert (/Users/pete/Projects/website-name/node_modules/gatsby/src/schema/types/sort.ts:67:23)
    at forEach (/Users/pete/Projects/website-name/node_modules/gatsby/src/schema/types/sort.ts:98:11)
    at Array.forEach (<anonymous>)
    at convert (/Users/pete/Projects/website-name/node_modules/gatsby/src/schema/types/sort.ts:67:23)
    at getFieldsEnum (/Users/pete/Projects/website-name/node_modules/gatsby/src/schema/types/sort.ts:137:18)
    at getSortInput (/Users/pete/Projects/website-name/node_modules/gatsby/src/schema/types/sort.ts:163:24)
    at addTypeToRootQuery (/Users/pete/Projects/website-name/node_modules/gatsby/src/schema/schema.js:1204:23)
    at processTypeComposer (/Users/pete/Projects/website-name/node_modules/gatsby/src/schema/schema.js:244:13)
    at rebuildSchemaWithSitePage (/Users/pete/Projects/website-name/node_modules/gatsby/src/schema/schema.js:111:3)
    at rebuildWithSitePage (/Users/pete/Projects/website-name/node_modules/gatsby/src/schema/index.js:156:18)
    at rebuildSchemaWithSitePage (/Users/pete/Projects/website-name/node_modules/gatsby/src/services/rebuild-schema-with-site-pages.ts:12:3)'
```

### Environment

```
System:
    OS: macOS 11.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.5/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.82
    Firefox: 86.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.0.4 => 3.0.4
    gatsby-image: ^2.4.19 => 2.4.21
    gatsby-plugin-compile-es6-packages: ^2.1.0 => 2.1.0
    gatsby-plugin-google-analytics: ^3.0.0 => 3.0.0
    gatsby-plugin-preload-fonts: ^2.0.0 => 2.0.0
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sass: ^4.0.2 => 4.0.2
    gatsby-plugin-sharp: ^3.0.1 => 3.0.1
    gatsby-plugin-sitemap: ^3.0.0 => 3.0.0
    gatsby-source-filesystem: ^3.0.0 => 3.0.0
    gatsby-source-wordpress: ^5.0.0 => 5.0.0
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0
    gatsby-wordpress-experimental-inline-images: ^0.0.3 => 0.0.3
  npmGlobalPackages:
    gatsby-cli: 2.19.1
```

#### Wordpress 5.7

Plugins:

- Advanced Custom Fields PRO 5.9.3 
- WP Gatsby 1.0.6
- WP GraphQL 1.2.5
- WPGraphQL for Advanced Custom Fields 0.4.1
- WPGraphQL Tax Query 0.1.0

**Comment by TylerBarnes** [comment]
@vladar `__wpGatsbyNodeModified` is automatically added to previewed pageContext by the WP plugin but it doesn't always exist. Do I need to use schema customization to type it so `rebuildSchemaWithSitePage` doesn't error?

**Comment by vladar** [comment]
@TylerBarnes Was it working in V2? If yes, then it is likely a bug. I would like to investigate but need a repro for this. 

But as a workaround, you can try adding the field to schema customization.

**Comment by vladar** [comment]
@peteluffman By chance, can you prepare a [minimal reproduction][reproduction] for this issue? We need to reproduce it to deliver a fix.

[reproduction]: https://gatsby.dev/reproduction

**Comment by pieh** [comment]
Here's simplified reproduction with steps - https://github.com/pieh/i30203

**Comment by peteluffman** [comment]
@vladar Is what @pieh put together enough or do you need the full shebang with the gatsby-source-wordpress plugin and a barebones WP install?

**Comment by vladar** [comment]
@peteluffman This reproduction is enough. #30426 should fix it.
