### ISSUE TITLE
yarn add gatsby-plugin-netlify-cms throws error due to typo in webpack version

### ISSUE THREAD

**Issue by musosoft** [gatsbyjs/gatsby#30291]
## Description

Error: webpack@^5.23.00 isn't supported by any available resolver. 
The issue is resolved by changing webpack version from "5.23.00" to "5.23.0" in package.json

### Steps to reproduce

```
mkdir test
cd test
yarn set version berry
yarn init
yarn add gatsby-plugin-netlify-cms
```

### Expected result

Completed installation

### Actual result

```
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: webpack@^5.23.00 isn't supported by any available resolver
    at n.getResolverByDescriptor (/Users/muso/.yarn/releases/yarn-berry.cjs:2:337763)
    at n.bindDescriptor (/Users/muso/.yarn/releases/yarn-berry.cjs:2:337128)
    at d (/Users/muso/.yarn/releases/yarn-berry.cjs:2:358489)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Promise.all (index 0)
    at async ie.resolveEverything (/Users/muso/.yarn/releases/yarn-berry.cjs:2:359694)
    at async /Users/muso/.yarn/releases/yarn-berry.cjs:2:378351
    at async f.startTimerPromise (/Users/muso/.yarn/releases/yarn-berry.cjs:2:390820)
    at async ie.install (/Users/muso/.yarn/releases/yarn-berry.cjs:2:378290)
    at async /Users/muso/.yarn/releases/yarn-berry.cjs:2:77082
➤ YN0000: └ Completed
➤ YN0000: Failed with errors in 0s 21ms
```

### Environment

```
  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.11.0 - /usr/local/bin/node
    Yarn: 2.4.1 - /usr/local/bin/yarn
    npm: 7.6.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.90
    Safari: 13.0.5
  npmGlobalPackages:
    gatsby-cli: 3.1.0
```

**Comment by musosoft** [comment]
Fixed by https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#handling-dependencies-for-plugins-that-are-not-yet-updated

**Comment by ridem** [comment]
@LekoArts Even if the OP closed this, I think the issue remains and this will come up again, even if it can be solved with a custom resolution.

Yarn 2+ is stricter about semvers and the problem is about fixing the typo in `^5.23.00`, which is invalid semver.
