### ISSUE TITLE
On AllWpPost, it's not possible to get a comment author's name

### ISSUE THREAD

**Issue by tharsheblows** [gatsbyjs/gatsby#30311]
I'm trying this query on my localhost's graphiql instance using:
 v2.1.3 of this
 v0.15.0 of the wp-graphql plugin
 v0.5.4 of wp-gatsby plugin

with the starter theme here (but with an updated version of this 😊) https://github.com/TylerBarnes/using-gatsby-source-wordpress-experimental

I can't get to the author's name for the comments. This is an example of the type of query I'm running:
```
query MyQuery {
  allWpPost {
    nodes {
      date
      content
      comments {
        nodes {
          content
          author {
            node {
              name
            }
}}}}}}
```

which is returning this error for comments.author.node.name (the rest is correct): 
```
"message": "Abstract type WpCommenter must resolve to an Object type at runtime for field WpCommentToCommenterConnectionEdge.node with value { id: \"Y29tbWVudF9hdXRob3I6Mjc=\", __typename: \"CommentAuthor\" }, received \"undefined\". Either the WpCommenter type should provide a \"resolveType\" function or each possible type should provide an \"isTypeOf\" function.",
      "locations": [
        {
          "line": 10,
          "column": 13
        }
      ],
      "path": [
        "allWpPost",
        "nodes",
        0,
        "comments",
        "nodes",
        0,
        "author",
        "node"
      ],
      "stack": [
        "GraphQLError: Abstract type WpCommenter must resolve to an Object type at runtime for field WpCommentToCommenterConnectionEdge.node with value { id: \"Y29tbWVudF9hdXRob3I6Mjc=\", __typename: \"CommentAuthor\" }, received \"undefined\". Either the WpCommenter type should provide a \"resolveType\" function or each possible type should provide an \"isTypeOf\" function.",
        "    at ensureValidRuntimeType ([path to theme]/node_modules/graphql/execution/execute.js:667:11)",
        "    at completeAbstractValue ([path to theme]/node_modules/graphql/execution/execute.js:660:42)",
        "    at completeValue ([path to theme]/node_modules/graphql/execution/execute.js:585:12)",
        "    at [path to theme]/node_modules/graphql/execution/execute.js:492:16",
        "    at runMicrotasks (<anonymous>)",
        "    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
        "    at async Promise.all (index 0)",
        "    at async Promise.all (index 1)",
        "    at async Promise.all (index 0)",
        "    at async Promise.all (index 0)",
        "    at async Promise.all (index 2)",
        "    at async Promise.all (index 0)",
        "    at async Promise.all (index 0)",
        "    at async Promise.all (index 0)"
      ]
```

If I pick up a comment id and use that in the following, it also gives the same error:
```
query MyQuery {
  wpComment(id: {eq: "[comment id]"}) {
    author {
      node {
        name
      }
    }
  }
}
```

**Comment by amooreTO** [comment]
@tharsheblows  - were you able to resolve this issue? I am facing the same the error.

**Comment by TylerBarnes** [comment]
@amooreTO I'm working on a fix this very moment :)

**Comment by TylerBarnes** [comment]
I have a canary with a possible solution here `gatsby-source-wordpress@5.2.0-alpha-wordpress.34+e45fa4b460`. The only problem is that issue I linked above ☝️ 

To get it to work you need to exclude Commenter.databaseId to prevent WPGraphQL errors that cause the author to return null.

In your gatsby-config.js plugin options for gatsby-source-wordpress add this:

```
        type: {
          Commenter: {
            excludeFieldNames: [`databaseId`],
          },
        }
```

Once that linked issue is fixed in WPGraphQL and this PR is merged/released https://github.com/gatsbyjs/gatsby/pull/30358 it will work!
