### ISSUE TITLE
[gatsby-source-wordpress] RequestError: read ECONNRESET / 503 errors prevent build

### ISSUE THREAD

**Issue by erick-go** [gatsbyjs/gatsby#30347]
## Description
I've mentioned the issue on the WPGraphQL Slack channel as well, but because threads can be fleeting, I'm posting it here as well.
Builds keep failing, mostly on a `503` error. Sometimes on `RequestError: read ECONNRESET`.
I'm pretty desperate to get it to work, since no new content is published. The site is my main source of income, so yeah..

If more info is needed, let me know!

//edit.. Add an 525 error (added to the bottom of the list)
### Steps to reproduce

Push the repo, publish a post or trigger a manual build in Gatsby Cloud
It's pretty hard to make a minimal repro, because my Wordpress installation is the possible cause. I could give access to my repo, but I can't to Gatsby Cloud since I'm on the free plan which doesn't allow more members accessing the account.
I'd me happy to give login creds though..

### Expected result

Successful build

### Actual result

```
RequestError: read ECONNRESET
    at ClientRequest. (/usr/src/app/www/nodemodules/gatsby-source-wordpress/nodemodules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:326:22)
    at ClientRequest.origin.emit (/usr/src/app/www/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (httpclient.js:427:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at TLSWrap.onStreamRead (internal/streambasecommons.js:209:20) {
  code: 'ECONNRESET',
  timings: {
    start: 1616143324582,
    socket: 1616143324582,
    lookup: 1616143324583,
    connect: 1616143329364,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1616143329378,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 1,
      tcp: 4781,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 4796
    }
  }
}
For more details see https://gatsby.dev/issue-how-to
```
```
Error: failed to process https://site.com/wp-content/uploads/2018/03/ua-route-mexico-1.jpg
RequestError: read ECONNRESET
    at Ticket. (/usr/src/app/www/node_modules/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-remote-file-node/index.js:349:16)
    at Ticket.emit (events.js:314:20)
    at Ticket.failed (/usr/src/app/www/node_modules/better-queue/lib/ticket.js:49:8)
    at /usr/src/app/www/node_modules/better-queue/lib/tickets.js:10:16
    at Array.forEach ()
    at Tickets.apply (/usr/src/app/www/nodemodules/better-queue/lib/tickets.js:9:16)
    at Tickets. [as failed] (/usr/src/app/www/node_modules/better-queue/lib/tickets.js:30:10)
    at Worker. (/usr/src/app/www/node_modules/better-queue/lib/queue.js:616:25)
    at Worker.emit (events.js:314:20)
    at Worker.failedTask (/usr/src/app/www/node_modules/better-queue/lib/worker.js:137:10)
    at /usr/src/app/www/node_modules/better-queue/lib/worker.js:124:10
    at Array.forEach ()
    at Worker.failedBatch (/usr/src/app/www/node_modules/better-queue/lib/worker.js:122:30)
    at cb (/usr/src/app/www/node_modules/better-queue/lib/worker.js:72:14)
    at Worker.pushToQueue [as fn] (/usr/src/app/www/node_modules/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-remote-file-node/index.js:133:12)
    at runMicrotasks ()
For more details see https://gatsby.dev/issue-how-to
```
```
There was an error
For more details see https://gatsby.dev/issue-how-to
```

**503 error**
``` 
gatsby-source-wordpress  Error: Request failed with status code 503
    at handleFetchErrors (/usr/src/app/www/node_modules/gatsby-source-wordpress/src/utils/fetch-graphql.ts:342:38)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at fetchGraphql (/usr/src/app/www/node_modules/gatsby-source-wordpress/src/utils/fetch-graphql.ts:752:5)
    at paginatedWpNodeFetch (/usr/src/app/www/node_modules/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-nodes-paginated.js:68:20)
    at fetchWPGQLContentNodes (/usr/src/app/www/node_modules/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-nodes.js:44:26)
    at /usr/src/app/www/node_modules/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-nodes.js:149:30
    at /usr/src/app/www/node_modules/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-nodes.js:139:9
    at async Promise.all (index 0)
    at runFnForEachNodeQuery (/usr/src/app/www/node_modules/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-nodes.js:127:5)
    at fetchWPGQLContentNodesByContentType (/usr/src/app/www/node_modules/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-nodes.js:148:3)
    at fetchAndCreateAllNodes (/usr/src/app/www/node_modules/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-nodes.js:183:37)
    at sourceNodes (/usr/src/app/www/node_modules/gatsby-source-wordpress/src/steps/source-nodes/index.ts:55:5)
    at runSteps (/usr/src/app/www/node_modules/gatsby-source-wordpress/src/utils/run-steps.ts:41:9)
    at runAPI (/usr/src/app/www/node_modules/gatsby/src/utils/api-runner-node.js:483:16)
For more details see https://gatsby.dev/issue-how-to
 gatsby-source-wordpress  Your WordPress server at https://site.com/graphql appears to be overloaded.
Try reducing the requestConcurrency for content updates or the previewRequestConcurrency for previews, and/or reducing the schema.perPage option:
{
  resolve: 'gatsby-source-wordpress',
  options: {
    schema: {
      perPage: 20, // currently set to 1
      requestConcurrency: 5, // currently set to 1
      previewRequestConcurrency: 2, // currently set to 1
    }
  },
}
For more details see https://gatsby.dev/issue-how-to
```

After turning on the debug flags in my wp-config these returned in debug.log:
```
[19-Mar-2021 01:15:48 UTC] PHP Notice:  Undefined index: title-mediaItem in /subdomains/admin/wp-content/plugins/add-wpgraphql-seo/wp-graphql-yoast-seo.php on line 165
[19-Mar-2021 01:15:48 UTC] PHP Notice:  Undefined index: metadesc-mediaItem in /subdomains/admin/wp-content/plugins/add-wpgraphql-seo/wp-graphql-yoast-seo.php on line 166
[19-Mar-2021 01:15:48 UTC] PHP Notice:  Undefined index: noindex-mediaItem in /subdomains/admin/wp-content/plugins/add-wpgraphql-seo/wp-graphql-yoast-seo.php on line 167
[19-Mar-2021 01:15:48 UTC] PHP Notice:  Undefined index: schema-page-type-mediaItem in /subdomains/admin/wp-content/plugins/add-wpgraphql-seo/wp-graphql-yoast-seo.php on line 168
[19-Mar-2021 01:15:48 UTC] PHP Notice:  Undefined index: title-actionMonitorAction in /subdomains/admin/wp-content/plugins/add-wpgraphql-seo/wp-graphql-yoast-seo.php on line 165
[19-Mar-2021 01:15:48 UTC] PHP Notice:  Undefined index: metadesc-actionMonitorAction in /subdomains/admin/wp-content/plugins/add-wpgraphql-seo/wp-graphql-yoast-seo.php on line 166
[19-Mar-2021 01:15:48 UTC] PHP Notice:  Undefined index: noindex-actionMonitorAction in /subdomains/admin/wp-content/plugins/add-wpgraphql-seo/wp-graphql-yoast-seo.php on line 167
[19-Mar-2021 01:15:48 UTC] PHP Notice:  Undefined index: schema-page-type-actionMonitorAction in /subdomains/admin/wp-content/plugins/add-wpgraphql-seo/wp-graphql-yoast-seo.php on line 168
[19-Mar-2021 01:15:48 UTC] PHP Notice:  Trying to get property 'user_nicename' of non-object in /subdomains/admin/wp-content/plugins/add-wpgraphql-seo/wp-graphql-yoast-seo.php on line 612
```
This deprecation is like 99% of the 40k lines:
`[19-Mar-2021 08:25:36 UTC] PHP Deprecated:  acf_get_term_post_id is <strong>deprecated</strong> since version 5.9.2! Use string format term_%d instead. in /subdomains/admin/wp-includes/functions.php on line 4861`

**525 error**
```
gatsby-source-wordpress  Error: Request failed with status code 525
    at createError (/usr/src/app/www/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/src/app/www/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/src/app/www/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (streamreadable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) 

Error occurred while fetching "MediaItem" nodes in inline html.

GraphQL request to https://admin.travelaar.nl/graphql failed.

Please ensure the following statements are true 
  - your WordPress URL is correct in gatsby-config.js
  - your server is responding to requests 
  - WPGraphQL and WPGatsby are installed and active in your WordPress backend
  - Your WordPress debug.log does not contain critical errors

For more details see https://gatsby.dev/issue-how-to
```
### Environment

```
System:
    OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 15.8.0 - ~/.nvm/versions/node/v15.8.0/bin/node
    npm: 7.5.4 - ~/.nvm/versions/node/v15.8.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.150
    Firefox: 86.0
  npmPackages:
    gatsby: ^3.1.1 => 3.1.1
    gatsby-cli: ^3.1.0 => 3.1.0
    gatsby-image: ^3.1.0 => 3.1.0
    gatsby-plugin-advanced-sitemap: ^1.5.6 => 1.6.0
    gatsby-plugin-algolia: ^0.17.0 => 0.17.0
    gatsby-plugin-algolia-search: ^0.5.7 => 0.5.7
    gatsby-plugin-eslint: ^3.0.0 => 3.0.0
    gatsby-plugin-gdpr-cookies: ^1.0.10 => 1.0.14
    gatsby-plugin-google-adsense: ^1.1.3 => 1.1.3
    gatsby-plugin-google-fonts-v2: 0.0.6 => 0.0.6
    gatsby-plugin-google-tagmanager: ^3.1.0 => 3.1.0
    gatsby-plugin-image: ^1.1.1 => 1.1.1
    gatsby-plugin-loadable-components-ssr: ^2.1.0 => 2.1.0
    gatsby-plugin-manifest: ^3.1.0 => 3.1.0
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1
    gatsby-plugin-netlify: ^3.1.0 => 3.1.0
    gatsby-plugin-offline: ^4.1.0 => 4.1.0
    gatsby-plugin-preconnect: ^1.1.54 => 1.2.0
    gatsby-plugin-prettier-eslint: ^1.0.4 => 1.0.4
    gatsby-plugin-react-helmet: ^4.1.0 => 4.1.0
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-sass: ^4.1.0 => 4.1.0
    gatsby-plugin-sharp: ^3.1.1 => 3.1.1
    gatsby-plugin-smoothscroll: ^1.2.0 => 1.2.0
    gatsby-plugin-styled-components: ^4.1.0 => 4.1.0
    gatsby-plugin-stylelint: ^3.2.0 => 3.2.0
    gatsby-source-filesystem: ^3.1.0 => 3.1.0
    gatsby-source-graphql: ^3.1.0 => 3.1.0
    gatsby-source-wordpress: ^5.1.0 => 5.1.0
    gatsby-telemetry: ^2.1.0 => 2.1.0
    gatsby-transformer-sharp: ^3.1.0 => 3.1.0
  npmGlobalPackages:
```
**gatsby-source-wordpress config**
```
      resolve: `gatsby-source-wordpress`,
      options: {
        url: process.env.WPGRAPHQL_URL || `https://site.com/graphql`,
        verbose: true,
        develop: {
          hardCacheMediaFiles: true,
        },
        debug: {
          graphql: {
            writeQueriesToDisk: true,
            showQueryVarsOnError: true,
            panicOnError: true,
          },
        },
        excludeFieldNames: ['comments', 'blocksJSON', 'previewBlocks', 'previewBlocksJSON'],
        type: {
          Post: {
            limit:
              process.env.NODE_ENV === `development`
                ? // The number of posts to fetch on development
                  20
                : // ... and on build
                  null,
          },
          Comment: {
            limit: 0,
          },
          MediaItem: {
            localFile: {
              requestConcurrency: 5,
            },
            lazyNodes: false,
          },
        },
        html: {
          useGatsbyImage: true,
          fallbackImageMaxWidth: 200,
          createStaticFiles: true,
          imageMaxWidth: 756,
        },
        schema: {
          timeout: 3000000,
          requestConcurrency: 1,
          previewRequestConcurrency: 1,
          perPage: 1,
        },
        // production: {
        //   allow404Images: true,
        //   hardCacheMediaFiles: true,
        // },
      },
    },

```

**Comment by erick-go** [comment]
It looks like Cloudflare was causing the issue. The Wordpress installation is on a subdomain which was proxied by CF. Turning if off seemed to help. Since the behavior has been unstable, it might change the next time, but for now I'm closing this issue
