### ISSUE TITLE
Regression: Errors in server rendering in develop.js throw obscure errors

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#304]
Namely:

```bash
ReferenceError: setTimeout is not defined
    at ProxyComponent.tryRender [as render] (/home/kylemathews/RelateRocket/relaterocket.co/node_modules/react-transform-catch-errors/lib/index.js:36:1)
    at ProxyComponent.proxiedMethod [as render] (/home/kylemathews/RelateRocket/relaterocket.co/node_modules/react-proxy/modules/createPrototypeProxy.js:44:1)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/home/kylemathews/RelateRocket/relaterocket.co/node_modules/react/lib/ReactElement.js:51:14)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/home/kylemathews/RelateRocket/relaterocket.co/node_modules/react/lib/ReactElement.js:77:1)
    at [object Object].ReactCompositeComponentMixin.performInitialMount (webpack/bootstrap 251444d4f2d4854439a0:350:1)
    at [object Object].ReactCompositeComponentMixin.mountComponent (webpack/bootstrap 251444d4f2d4854439a0:243:1)
    at Object.ReactReconciler.mountComponent (webpack/bootstrap 251444d4f2d4854439a0:45:1)
    at webpack/bootstrap 251444d4f2d4854439a0:42:1
    at ReactServerRenderingTransaction.Mixin.perform (webpack/bootstrap 251444d4f2d4854439a0:135:1)
    at renderToStringImpl (webpack/bootstrap 251444d4f2d4854439a0:37:6)
```

Which confused me for a bit until I saw that this custom Babel config in `develop.js` had been removed. @benstepp perhaps there just filter out `react-hmre` as a preset from there?

**Comment by benstepp** [comment]
Went ahead and added the loader back to develop.js for now. There really shouldn't be any webpack config changing outside of webpack config. When I first saw that I knew it looked hardcoded, out of place, and not modifiable by a user or testable in anyway. Now that I know what it does, it's probably okay to leave there for now, but ideally it should be contained to webpack.config.js. 

However, the other solution is to introduce another stage to webpack.config.js and I'd prefer not to do that to a file coming up on 400 lines. Plugins would cut it down to the point where it wouldn't be a nightmare to modify / add another stage.

**Comment by KyleAMathews** [comment]
Yeah, totally agree that it'd be better to keep everything in `webpack.config.js`

This is what I meant btw and perhaps is less objectionable as it just filters out the hmr preset.

```javascript
let presets = htmlCompilerConfig._loaders.js.config.query.presets
presets = _.filter(presets, (preset) => !_.includes(preset, 'babel-preset-react-hmre'))
htmlCompilerConfig._loaders.js.config.query.presets = presets
```

**Comment by benstepp** [comment]
Using lodash to filter is definitely more explicit (you can see the name `react-hmre`). However it does violate the law of demeter, and I think it would be best to use the public interface if we're changing the config where it doesn't belong. We'd also have to `eslint-disable no-underscore-dangle` on two lines and between that and the comment I feel like there would be too much noise surrounding the code.

**Comment by KyleAMathews** [comment]
Ok, so add a new stage called `develop-server` (or whatever)?

**Comment by benstepp** [comment]
I came up with a solution that works with minimal code (just parse the develop-html stage down to develop) and separate out the babel stage. It's not exactly clear, but I really don't want to have massive blocks of repeated cases in the switch statements.
