### ISSUE TITLE
Custom field label named "type" breaks schema

### ISSUE THREAD

**Issue by rlenkov** [gatsbyjs/gatsby#30428]
## Description

If we create a Label named **"Type"** in WordPress with ACF, in some cases it can break the schema.

### Steps to reproduce

**I have the following setup in WordPress:**
- A **Field Group named `Chapters`** created by **ACF** that is used to provide custom fields for my pages.
- Inside `Chapters` I have a field called Content Block which is of `Flexible Content` type.
- Inside `Content Block` I define a Layout named `My Layout`.
- In `My Layout` I create a label of type `select` with the label: **`Type`**
- For the select choices I put two choices:
```
alpha
beta
```
A drawing for simplicity:
```
├── Chapters (Field Group)
│   ├── Content Block (Flexible Content)
│   │   ├── My Layout (Layout)
│   │   │   ├── Type (Label)

```

**I have the following setup in Gatsby:**
Just a basic empty Gatsby site that I use for query testing. No gatsby starter used. Environment/plugin setup listed below.

### Expected result

I would expect the data to show in the schema.

### Actual result

After using this `My Layout` in my page I run `gatsby clean && gatsby develop`. In GraphiQL I get the following error message, and the whole `My Layout` element is unavailable in the schema:
```
        "GraphQLError: Abstract type \"WpPage_HomePage_ContentBlock\" was resolve to a type \"Wpalpha\" that does not exist inside schema.",
        "    at ensureValidRuntimeType (/home/****/****/****/node_modules/graphql/execution/execute.js:698:11)",
        "    at completeAbstractValue (/home/****/****/****/node_modules/graphql/execution/execute.js:680:42)",
        "    at completeValue (/home/****/****/****/node_modules/graphql/execution/execute.js:584:12)",
        "    at /home/****/****/****/node_modules/graphql/execution/execute.js:620:25",
        "    at Array.map (<anonymous>)",
        "    at safeArrayFrom (/home/****/****/****/node_modules/graphql/jsutils/safeArrayFrom.js:36:23)",
        "    at completeListValue (/home/****/****/****/node_modules/graphql/execution/execute.js:607:53)",
        "    at completeValue (/home/****/****/****/node_modules/graphql/execution/execute.js:572:12)",
        "    at resolveField (/home/****/****/****/node_modules/graphql/execution/execute.js:472:19)",
        "    at executeFields (/home/****/****/****/node_modules/graphql/execution/execute.js:292:18)",
        "    at collectAndExecuteSubfields (/home/****/****/****/node_modules/graphql/execution/execute.js:748:10)",
        "    at completeObjectValue (/home/****/****/****/node_modules/graphql/execution/execute.js:738:10)",
        "    at completeValue (/home/****/****/****/node_modules/graphql/execution/execute.js:590:12)",
        "    at /home/****/****/****/node_modules/graphql/execution/execute.js:620:25",
        "    at Array.map (<anonymous>)",
        "    at safeArrayFrom (/home/****/****/****/node_modules/graphql/jsutils/safeArrayFrom.js:36:23)
```

### Environment

```
  System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 7.6.3 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.182
    Firefox: 86.0
  npmPackages:
    gatsby: ^3.0.1 => 3.1.0
    gatsby-plugin-sass: ^4.1.0 => 4.1.0
    gatsby-plugin-sharp: ^3.1.0 => 3.1.0
    gatsby-source-wordpress: ^5.1.0 => 5.1.0
    gatsby-transformer-sharp: ^3.1.0 => 3.1.0
  npmGlobalPackages:
    gatsby-cli: 3.0.0
```

**Comment by ardiewen** [comment]
Hey @rlenkov , I think this is fixed in #30358? Related to an issue I posted in the original experimental plugin way back #30310

You may have to upgrade to the source plugin 5.3.0 or greater to test it.
