### ISSUE TITLE
Using "case" in a scss module as class name causes build to fail

### ISSUE THREAD

**Issue by andreademasi** [gatsbyjs/gatsby#30430]
## Description

Using `case` as a name for a class in a scss module causes webpack build to fail when running `gatsby develop`. I think this has to do with reserved keywords, might be a bug outside gatsby.

### Steps to reproduce

1.  Create a scss module like `style.module.scss`
2.  Create a class named `case`
3. Import style into component (In my case I did `import * as styles from "./style.module.scss"`)
4. Assign class to component : 
    `<p className={styles.case}>Welcome to your new Gatsby site.</p>`
    
Reproduction repo: https://github.com/andreademasi/gatsby-bug

### Expected result

Build succeeds

### Actual result

Build fails. Log:
```
failed Building development bundle - 15.050s
ERROR in ./src/pages/style.module.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected keyword 'case' (8:13)
File was processed with these loaders:
 * ./node_modules/css-loader/dist/cjs.js
 * ./node_modules/postcss-loader/dist/cjs.js
 * ../node_modules/sass-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| ___CSS_LOADER_EXPORT___.push([module.id, ".style-module--case--2i5Vz {\n  color: red;\n}",
"",{"version":3,"sources":["webpack://./src/pages/style.module.scss"],"names":[],"mappings":"AAAA;EACE,UAAA;AACF","sourcesContent":[".case {\r\n  color: red;\r\n}\r\n"],"sourceRoot":""}]);
| // Exports
> export const case = "style-module--case--2i5Vz";
| export default ___CSS_LOADER_EXPORT___;
|
    at handleParseError (C:\Users\andre\gatsby-bug\node_modules\webpack\lib\NormalModule.js:881:19)
    at C:\Users\andre\gatsby-bug\node_modules\webpack\lib\NormalModule.js:982:5
    at processResult (C:\Users\andre\gatsby-bug\node_modules\webpack\lib\NormalModule.js:716:11)
    at C:\Users\andre\gatsby-bug\node_modules\webpack\lib\NormalModule.js:768:5
    at C:\Users\andre\gatsby-bug\node_modules\loader-runner\lib\LoaderRunner.js:406:3
    at iterateNormalLoaders (C:\Users\andre\gatsby-bug\node_modules\loader-runner\lib\LoaderRunner.js:232:10)
    at iterateNormalLoaders (C:\Users\andre\gatsby-bug\node_modules\loader-runner\lib\LoaderRunner.js:239:10)
    at C:\Users\andre\gatsby-bug\node_modules\loader-runner\lib\LoaderRunner.js:254:3
    at context.callback (C:\Users\andre\gatsby-bug\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (C:\Users\andre\gatsby-bug\node_modules\css-loader\dist\index.js:182:3)
 @ ./src/pages/index.js 12:0-46 38:15-26
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 21:11-23:5
 @ ./.cache/app.js 17:0-52 28:0-70 30:27-40 28:0-70
```

### Environment

```
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 7.6.3 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.0 - /c/Python39/python
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.57)
  npmPackages:
    gatsby: ^3.1.1 => 3.1.1 
    gatsby-plugin-gatsby-cloud: ^2.1.0 => 2.1.0 
    gatsby-plugin-image: ^1.1.1 => 1.1.1 
    gatsby-plugin-manifest: ^3.1.0 => 3.1.0 
    gatsby-plugin-offline: ^4.1.0 => 4.1.0 
    gatsby-plugin-react-helmet: ^4.1.0 => 4.1.0 
    gatsby-plugin-sharp: ^3.1.1 => 3.1.1 
    gatsby-source-filesystem: ^3.1.0 => 3.1.0 
    gatsby-transformer-sharp: ^3.1.0 => 3.1.0 
  npmGlobalPackages:
    gatsby-cli: 3.1.0
```

**Comment by LekoArts** [comment]
Hi!

As per `css-loader` docs: https://github.com/webpack-contrib/css-loader#namedexport

> It is not allowed to use JavaScript reserved words in css class names.

Since `case` is part of that list: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#reserved_keywords_as_of_ecmascript_2015

So you'll need to adjust your name! :)
