### ISSUE TITLE
gatsby-plugin-typescript should ignore `.d.ts` files in `pages` dir

### ISSUE THREAD

**Issue by ViliamKopecky** [gatsbyjs/gatsby#3050]
Having types declaration file in `src/pages` causes error, because Gatsby tries to build it to html. It should be ignored for creating pages.

```
 error  in ./src/pages/styleguide/image.module.sass.d.ts

Module build failed: Error: Debug Failure. False expression: Output generation failed
    at Object.transpileModule (/Users/vk/www/project/node_modules/typescript/lib/typescript.js:84062:18)
    at getTranspilationEmit (/Users/vk/www/project/node_modules/ts-loader/dist/index.js:173:32)
    at successLoader (/Users/vk/www/project/node_modules/ts-loader/dist/index.js:41:11)
    at Object.loader (/Users/vk/www/project/node_modules/ts-loader/dist/index.js:29:12)

 @ ./.cache/sync-requires.js 25:75-150
```

**Comment by KyleAMathews** [comment]
Seems reasonable! Would you like to add support for this to https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/internal-plugins/component-page-creator/validate-path.js?
