### ISSUE TITLE
Build Process fails inside of Netlify but works locally (wordpress)

### ISSUE THREAD

**Issue by iamkevingreen** [gatsbyjs/gatsby#3061]
I have a site using gatsby-source-wordpress that builds when I run the commands locally but fails when I run it within netlify auto deploy. 

I have a .nvmrc file and followed this guide https://www.netlify.com/blog/2016/02/24/a-step-by-step-guide-gatsby-on-netlify/

was using the a 1.0 version of gatsby wordpress but upgraded it to 2 and the problem continues.

```js
7:57:06 PM: 
7:57:06 PM: =START PLUGIN=====================================
7:57:06 PM: 
7:57:06 PM: Site URL: https://removed.pantheonsite.io
Site hosted on Wordpress.com: false
7:57:06 PM: Using ACF: true
7:57:07 PM: 
7:57:07 PM: Plugin gatsby-source-wordpress returned an error:
7:57:07 PM: TypeError: Cannot read property 'user' of undefined
    at _callee$ (/opt/build/repo/node_modules/gatsby-source-wordpress/gatsby-node.js:292:61)
    at tryCatch (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/opt/build/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /opt/build/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (/opt/build/repo/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:191:7)
    at Object.<anonymous> (/opt/build/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Object.sourceNodes (/opt/build/repo/node_modules/gatsby-source-wordpress/gatsby-node.js:457:17)
    at runAPI (/opt/build/repo/node_modules/gatsby/dist/utils/api-runner-node.js:105:36)
    at /opt/build/repo/node_modules/gatsby/dist/utils/api-runner-node.js:179:33
    at /opt/build/repo/node_modules/async/internal/map.js:26:9
    at replenish (/opt/build/repo/node_modules/async/internal/eachOfLimit.js:64:17)
    at iterateeCallback (/opt/build/repo/node_modules/async/internal/eachOfLimit.js:49:17)
    at /opt/build/repo/node_modules/async/internal/onlyOnce.js:12:16
    at /opt/build/repo/node_modules/async/internal/map.js:28:13
7:57:07 PM: success source and transform nodes — 0.037 s
7:57:07 PM: success building schema — 0.186 s
7:57:07 PM: errors [ { GraphQLError: Cannot query field "allWordpressPage" on type "RootQueryType". Did you mean "allSitePage"?
    at Object.Field (/opt/build/repo/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:66:31)
    at Object.enter (/opt/build/repo/node_modules/graphql/language/visitor.js:297:29)
    at Object.enter (/opt/build/repo/node_modules/graphql/language/visitor.js:339:25)
    at visit (/opt/build/repo/node_modules/graphql/language/visitor.js:229:26)
    at visitUsingRules (/opt/build/repo/node_modules/graphql/validation/validate.js:76:22)
    at validate (/opt/build/repo/node_modules/graphql/validation/validate.js:61:10)
    at /opt/build/repo/node_modules/graphql/graphql.js:72:51
    at Promise._execute (/opt/build/repo/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/opt/build/repo/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/opt/build/repo/node_modules/bluebird/js/release/promise.js:79:10)
    at graphqlImpl (/opt/build/repo/node_modules/graphql/graphql.js:62:10)
    at graphql (/opt/build/repo/node_modules/graphql/graphql.js:50:148)
    at graphqlRunner (/opt/build/repo/node_modules/gatsby/dist/bootstrap/index.js:333:22)
    at Promise (/opt/build/repo/gatsby-node.js:21:5)
    at Promise._execute (/opt/build/repo/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/opt/build/repo/node_modules/bluebird/js/release/promise.js:483:18)
    message: 'Cannot query field "allWordpressPage" on type "RootQueryType". Did you mean "allSitePage"?',
    locations: [ [Object] ],
    path: undefined } ]
7:57:07 PM: 
7:57:07 PM: Plugin default-site-plugin returned an error:
7:57:07 PM: 
```
I can continue to deploy locally but not sure what the difference is between the netlify `gatsby build` and my local?

**Comment by KyleAMathews** [comment]
First two things I'd try are

1. `rm -r node_modules && npm install`
2. Try building your site on a linux VM

**Comment by KyleAMathews** [comment]
Also you could look at the source code for gatsby-source-wordpress to see what's happening.

**Comment by iamkevingreen** [comment]
not sure if this is related https://github.com/yarnpkg/yarn/issues/4799 but I am on a really old version of yarn 0.18.1, so I'll play around with that as well.

**Comment by iamkevingreen** [comment]
I got this operational by getting yarn build to work locally, I had to add the url-loader and json-loader and now it works in netlify as well.
