### ISSUE TITLE
RequestError: self signed certificate

### ISSUE THREAD

**Issue by Dave-Lindberg** [gatsbyjs/gatsby#31064]
Updated gatsby-cli to v3.3.0, using Local as a source for `gatsby-source-wordpress` plugin. 

Running gatsby develop now produces:

```

 ERROR 

RequestError: self signed certificate
    at ClientRequest.<anonymous> (/Users/dlindberg/Code/dl-wpgql/node_modules/g
atsby-source-wordpress/node_modules/got/dist/source/core/index.js:953:111)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:215:7)
    at ClientRequest.origin.emit
(/Users/dlindberg/Code/dl-wpgql/node_modules/gatsby-source-wordpress/node_modul
es/got/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
  name: 'RequestError',
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT',
  timings: {
    start: 1619467443036,
    socket: 1619467443037,
    lookup: 1619467443045,
    connect: 1619467443048,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1619467443065,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 8,
      tcp: 3,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 29
    }
  }
}


 ERROR 

Error: failed to process https://gatsbywpsource.local/wp-content/uploads/2020/0
6/Screen-Shot-2020-06-30-at-6.15.31-PM.png
RequestError: self signed certificate
    at Ticket.<anonymous>
(/Users/dlindberg/Code/dl-wpgql/node_modules/gatsby-source-wordpress/src/steps/
source-nodes/create-nodes/create-remote-file-node/index.js:349:16)
    at Ticket.emit (events.js:210:5)
    at Ticket.failed
(/Users/dlindberg/Code/dl-wpgql/node_modules/better-queue/lib/ticket.js:49:8)
    at
/Users/dlindberg/Code/dl-wpgql/node_modules/better-queue/lib/tickets.js:10:16
    at Array.forEach (<anonymous>)
    at Tickets._apply
(/Users/dlindberg/Code/dl-wpgql/node_modules/better-queue/lib/tickets.js:9:16)
    at Tickets.<computed> [as failed]
(/Users/dlindberg/Code/dl-wpgql/node_modules/better-queue/lib/tickets.js:30:10)
    at Worker.<anonymous>
(/Users/dlindberg/Code/dl-wpgql/node_modules/better-queue/lib/queue.js:616:25)
    at Worker.emit (events.js:210:5)
    at Worker.failedTask
(/Users/dlindberg/Code/dl-wpgql/node_modules/better-queue/lib/worker.js:137:10)
    at
/Users/dlindberg/Code/dl-wpgql/node_modules/better-queue/lib/worker.js:124:10
    at Array.forEach (<anonymous>)
    at Worker.failedBatch
(/Users/dlindberg/Code/dl-wpgql/node_modules/better-queue/lib/worker.js:122:30)
    at cb
(/Users/dlindberg/Code/dl-wpgql/node_modules/better-queue/lib/worker.js:72:14)
    at Worker.pushToQueue [as fn]
(/Users/dlindberg/Code/dl-wpgql/node_modules/gatsby-source-wordpress/src/steps/
source-nodes/create-nodes/create-remote-file-node/index.js:133:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)


 ERROR 

There was an error

not finished source and transform nodes - 5.441s
not finished  gatsby-source-wordpress  fetching nodes - 5.407s - 57 total
not finished  gatsby-source-wordpress  creating nodes - 1.361s
not finished  gatsby-source-wordpress  MediaItem - 1.362s - fetched 10
not finished Downloading remote files - 0.113s

npm ERR! code 1
npm ERR! path /Users/dlindberg/Code/dl-wpgql
npm ERR! command failed
npm ERR! command sh -c gatsby develop

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dlindberg/.npm/_logs/2021-04-26T20_04_03_290Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Here's the log contents:
```
0 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'develop' ]
1 info using npm@7.5.4
2 info using node@v12.12.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/Users/dlindberg/Code/dl-wpgql/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/dlindberg/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 2ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 9ms
19 verbose npm-session 1a0deecc7ac12ed1
20 timing npm:load Completed in 26ms
21 timing command:run-script Completed in 20780ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:210:5)
22 verbose stack     at maybeClose (internal/child_process.js:1021:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
23 verbose pkgid gatsby-starter-default@0.1.0
24 verbose cwd /Users/dlindberg/Code/dl-wpgql
25 verbose Darwin 20.3.0
26 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "develop"
27 verbose node v12.12.0
28 verbose npm  v7.5.4
29 error code 1
30 error path /Users/dlindberg/Code/dl-wpgql
31 error command failed
32 error command sh -c gatsby develop
33 verbose exit 1
```
Currently running 
Gatsby CLI version: 2.12.49
Gatsby version: 2.32.9
My Local installation config has `gastbywpsource.local.crt` set as a trusted SSL.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

To make the process of resolving problems quicker for both sides we need you to fill out the issue template and give us a minimal reproduction:

```md
<!--
  Please fill out each section below, otherwise, your issue will be closed. This info allows Gatsby maintainers to diagnose (and fix!) your issue as quickly as possible.

  Useful Links:
  - Documentation: https://www.gatsbyjs.com/docs/
  - How to File an Issue: https://www.gatsbyjs.com/contributing/how-to-file-an-issue/

  Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
-->

## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```

**Comment by Dave-Lindberg** [comment]
Thanks, I received guidance on this issue from @TylerBarnes and am all set. 

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/tutorials/using-self-signed-certificates.md
