### ISSUE TITLE
Incorrect `reportWebpackWarnings` usage

### ISSUE THREAD

**Issue by rnmKeshav** [gatsbyjs/gatsby#31474]
## Description

`gatsby develop` works fine but `gatsby build` throws error `failed Building production JavaScript and CSS bundles ` 

```
failed Building production JavaScript and CSS bundles - 10.208s

 ERROR #98123  WEBPACK

Generating JavaScript bundles failed

Cannot read property 'split' of undefined
```

Repo Link: https://github.com/rnmKeshav/portfolio

### Steps to reproduce

```
npm install
npm run build
```

### Expected result

Build should pass successfully

### Actual result

```> portfolio@1.0.0 build /Users/keshavkumar/Documents/practices/portfolio
> gatsby build

success open and validate gatsby-configs - 0.053s
success load plugins - 0.449s
success onPreInit - 0.021s
success initialize cache - 0.004s
success copy gatsby files - 0.056s
success onPreBootstrap - 0.013s
success createSchemaCustomization - 0.008s
success Checking for changed pages - 0.001s
success source and transform nodes - 0.194s
success building schema - 0.294s
info Total nodes: 127, SitePage nodes: 1 (use --verbose for breakdown)
success createPages - 0.003s
success Checking for changed pages - 0.001s
success createPagesStatefully - 0.041s
success update schema - 0.044s
success onPreExtractQueries - 0.001s
success extract queries from components - 3.498s
success write out redirect data - 0.005s
success Build manifest and related icons - 0.040s
success onPostBootstrap - 0.044s
info bootstrap finished - 6.547s
success run page queries - 0.017s - 5/5 298.88/s
success write out requires - 0.005s
failed Building production JavaScript and CSS bundles - 10.208s

 ERROR #98123  WEBPACK

Generating JavaScript bundles failed

Cannot read property 'split' of undefined


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! portfolio@1.0.0 build: `gatsby build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the portfolio@1.0.0 build script.
```

### Environment
 System:
    OS: macOS 11.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.212
    Safari: 14.1
  npmPackages:
    gatsby: 3.2.1 => 3.2.1
    gatsby-cli: 3.5.0 => 3.5.0
    gatsby-plugin-google-analytics: 3.3.0 => 3.3.0
    gatsby-plugin-image: 1.3.0 => 1.3.0
    gatsby-plugin-manifest: 3.5.0 => 3.5.0
    gatsby-plugin-react-helmet: 4.5.0 => 4.5.0
    gatsby-plugin-sass: 4.3.0 => 4.3.0
    gatsby-plugin-sharp: 3.3.0 => 3.3.0
    gatsby-source-filesystem: 3.3.0 => 3.3.0
    gatsby-transformer-sharp: 3.3.0 => 3.3.0
  npmGlobalPackages:
    gatsby-cli: 3.5.0

**Comment by KyleAMathews** [comment]
The actual error is getting swallowed. Can you edit node_modules/gatsby/dist/utils/webpack-error-utils.js line 20 to add console.log(webpackError) and report back what it says?

**Comment by rnmKeshav** [comment]
Hi @KyleAMathews,
here is the log

```
success write out requires - 0.005s
TypeError: Cannot read property 'split' of undefined
    at formatMessage (/Users/keshavkumar/Documents/practices/portfolio/node_modules/react-dev-utils/formatWebpackMessages.js:18:23)
    at Array.map (<anonymous>)
    at warningMessages (/Users/keshavkumar/Documents/practices/portfolio/node_modules/react-dev-utils/formatWebpackMessages.js:107:43)
    at reportWebpackWarnings (/Users/keshavkumar/Documents/practices/portfolio/node_modules/gatsby/src/utils/webpack-error-utils.ts:155:15)
    at build (/Users/keshavkumar/Documents/practices/portfolio/node_modules/gatsby/src/commands/build.ts:132:7)
failed Building production JavaScript and CSS bundles - 9.104s

 ERROR #98123  WEBPACK

Generating JavaScript bundles failed

Cannot read property 'split' of undefined


```

**Comment by KyleAMathews** [comment]
Hmm can you delete your lock file & `node_modules` and reinstall?

**Comment by rnmKeshav** [comment]
Hi @KyleAMathews I have `package-lock=false` in my `.npmrc` file so i don't have `package-lock` file. I tried `gatsby clean`, reinstalling `node_modules` and running `gatsby build`. Nothing works.

**Comment by KyleAMathews** [comment]
could you log what's passed to `reportWebpackWarnings`? One of the messages is undefined apparently.

**Comment by rnmKeshav** [comment]
```
warnings:  [
  'Css Minimizer Plugin: cssnano: /Users/keshavkumar/Documents/practices/portfolio/styles.4af3d71e4f2ad083cf01.css:8:3: Error in parsing SVG: Non-whitespace before first tag.\n' +
    'Line: 0\n' +
    'Column: 1\n' +
    'Char: d ',
  'Css Minimizer Plugin: cssnano: /Users/keshavkumar/Documents/practices/portfolio/styles.4af3d71e4f2ad083cf01.css:8:3: Error in parsing SVG: Non-whitespace before first tag.\n' +
    'Line: 0\n' +
    'Column: 1\n' +
    'Char: d ',
  'Css Minimizer Plugin: cssnano: /Users/keshavkumar/Documents/practices/portfolio/styles.4af3d71e4f2ad083cf01.css:8:3: Error in parsing SVG: Non-whitespace before first tag.\n' +
    'Line: 0\n' +
    'Column: 1\n' +
    'Char: d ',
  'Css Minimizer Plugin: cssnano: /Users/keshavkumar/Documents/practices/portfolio/styles.4af3d71e4f2ad083cf01.css:8:3: Error in parsing SVG: Non-whitespace before first tag.\n' +
    'Line: 0\n' +
    'Column: 1\n' +
    'Char: d ',
  'Css Minimizer Plugin: cssnano: /Users/keshavkumar/Documents/practices/portfolio/styles.4af3d71e4f2ad083cf01.css:8:3: Error in parsing SVG: Text data outside of root node.\n' +
    'Line: 25\n' +
    'Column: 7\n' +
    'Char: ~ '
]



webpackError: TypeError: Cannot read property 'split' of undefined
    at formatMessage (/Users/keshavkumar/Documents/practices/portfolio/node_modules/react-dev-utils/formatWebpackMessages.js:18:23)
    at Array.map (<anonymous>)
    at formatWebpackMessages (/Users/keshavkumar/Documents/practices/portfolio/node_modules/react-dev-utils/formatWebpackMessages.js:107:43)
    at reportWebpackWarnings (/Users/keshavkumar/Documents/practices/portfolio/node_modules/gatsby/src/utils/webpack-error-utils.ts:153:25)
    at build (/Users/keshavkumar/Documents/practices/portfolio/node_modules/gatsby/src/commands/build.ts:132:7)
failed Building production JavaScript and CSS bundles - 10.211s
```

**Comment by KyleAMathews** [comment]
hmm odd, so this code is wrong:

```
  const warningMessages = warnings.map(
    warning => `${warning.moduleName}\n\n${warning.message}`
  )
```

It's assuming the warnings are objects and they're just strings in this case.

So we should check if the warnings are objects first before mapping over them.

Does it work if you just pass `warnings` into `formatWebpackMessages` instead of `warningMessages`?

**Comment by rnmKeshav** [comment]
Hi @KyleAMathews, Yes it works with following changes:
```
const reportWebpackWarnings = (warnings, reporter) => {
  //console.log("warnings: ", warnings);
  //const warningMessages = warnings.map(warning => warning.message);
  (0, _formatWebpackMessages.default)({
    errors: [],
    warnings: warnings
  }).warnings.forEach(warning => reporter.warn(warning));
};
```


Output: 

```
success open and validate gatsby-configs - 0.053s
success load plugins - 0.436s
success onPreInit - 0.029s
success initialize cache - 0.005s
success copy gatsby files - 0.077s
success onPreBootstrap - 0.013s
success createSchemaCustomization - 0.010s
success Checking for changed pages - 0.001s
success source and transform nodes - 0.179s
success building schema - 0.320s
info Total nodes: 127, SitePage nodes: 1 (use --verbose for breakdown)
success createPages - 0.003s
success Checking for changed pages - 0.001s
success createPagesStatefully - 0.049s
success Cleaning up stale page-data - 0.002s
success update schema - 0.049s
success onPreExtractQueries - 0.001s
success extract queries from components - 3.990s
success write out redirect data - 0.001s
success Build manifest and related icons - 0.044s
success onPostBootstrap - 0.048s
info bootstrap finished - 7.357s
success write out requires - 0.005s
warn Css Minimizer Plugin: cssnano: /Users/keshavkumar/Documents/practices/portfolio/styles.4af3d71e4f2ad083cf01.css:8:3: Error in parsing SVG: Non-whitespace before first tag.
Line: 0
Column: 1
Char: d
warn Css Minimizer Plugin: cssnano: /Users/keshavkumar/Documents/practices/portfolio/styles.4af3d71e4f2ad083cf01.css:8:3: Error in parsing SVG: Non-whitespace before first tag.
Line: 0
Column: 1
Char: d
warn Css Minimizer Plugin: cssnano: /Users/keshavkumar/Documents/practices/portfolio/styles.4af3d71e4f2ad083cf01.css:8:3: Error in parsing SVG: Non-whitespace before first tag.
Line: 0
Column: 1
Char: d
warn Css Minimizer Plugin: cssnano: /Users/keshavkumar/Documents/practices/portfolio/styles.4af3d71e4f2ad083cf01.css:8:3: Error in parsing SVG: Non-whitespace before first tag.
Line: 0
Column: 1
Char: d
warn Css Minimizer Plugin: cssnano: /Users/keshavkumar/Documents/practices/portfolio/styles.4af3d71e4f2ad083cf01.css:8:3: Error in parsing SVG: Text data outside of root node.
Line: 25
Column: 7
Char: ~
success Building production JavaScript and CSS bundles - 6.933s
success Building HTML renderer - 1.811s
info There are no new or changed html files to build.
success onPostBuild - 0.001s
info Done building in 16.356241336 sec
```

**Comment by rnmKeshav** [comment]
Hi @KyleAMathews, i am facing problem in deploying to netlify. Deployment is failing due to this issue. This is [deployment log](https://app.netlify.com/sites/pensive-mestorf-381f77/deploys/60a4a09e5d77180007a182fe) from netlify. Is there any chance we can fix this issue in next minor release?

**Comment by KyleAMathews** [comment]
I put up a PR which should fix the issue https://github.com/gatsbyjs/gatsby/pull/31489
