### ISSUE TITLE
"Sorting on fields that need arguments to resolve is deprecated" warning (w/ example repo)

### ISSUE THREAD

**Issue by rejas** [gatsbyjs/gatsby#31523]
Following up on https://github.com/gatsbyjs/gatsby/issues/28565 I created a repo with a sample where this warning occurs:

https://github.com/rejas/deprecate_repo

## Description

When building my site I get this warning:

`warn The enum value "MdxFieldsEnum.fields___slug" is deprecated. Sorting on fields that need arguments to resolve is deprecated.`

### Steps to reproduce

Build the example repo  https://github.com/rejas/deprecate_repo

### Expected result

No warnings should appear

### Actual result

Warnings appear

### Environment

  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.1.0 - ~/.nvm/versions/node/v16.1.0/bin/node
    Yarn: 1.22.5 - /snap/bin/yarn
    npm: 7.11.2 - ~/.nvm/versions/node/v16.1.0/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0.1
  npmPackages:
    gatsby: ^3.5.1 => 3.5.1
    gatsby-background-image: ^1.5.3 => 1.5.3
    gatsby-plugin-feed: ^3.5.0 => 3.5.0
    gatsby-plugin-image: ^1.5.0 => 1.5.0
    gatsby-plugin-manifest: ^3.5.0 => 3.5.0
    gatsby-plugin-mdx: ^2.5.1 => 2.5.1
    gatsby-plugin-no-sourcemaps: ^3.5.0 => 3.5.0
    gatsby-plugin-offline: ^4.5.1 => 4.5.1
    gatsby-plugin-react-helmet: ^4.5.0 => 4.5.0
    gatsby-plugin-robots-txt: ^1.6.2 => 1.6.2
    gatsby-plugin-sharp: ^3.5.0 => 3.5.0
    gatsby-plugin-sitemap: ^4.1.0 => 4.1.0
    gatsby-remark-copy-linked-files: ^4.2.1 => 4.2.1
    gatsby-remark-images: ^5.2.1 => 5.2.1
    gatsby-source-filesystem: ^3.5.0 => 3.5.0
    gatsby-theme-material-ui: ^2.0.1 => 2.0.1
    gatsby-transformer-sharp: ^3.5.0 => 3.5.0
    gatsby-transformer-yaml: ^3.5.0 => 3.5.0

**Comment by el7cosmos** [comment]
This happens to me also with custom schema. It is weird because without custom schema, the field also need argument to resolve.

Without custom schema, I'm sorting on field with type `Date` and `dateformat` extension which receive argument `fomatString`, `fromNow`, `difference`, and`locale`, but it builds without deprecation warning.
While with custom schema, my field also receive the same argument plus 1 additional argument, then builds throw deprecation warning.

It is getting weirder now, some other fields without custom schema also throw deprecation warning when sorted even if the fields didn't receive any argument at all

**Comment by RocketLL** [comment]
Having the same problem.    
I did some digging around in [/src/schema/types/sort.ts](https://github.com/gatsbyjs/gatsby/blob/fcd0b449edcca4808814fbcd89df82551d566889/packages/gatsby/src/schema/types/sort.ts#L77), and I'm not too sure what's going on.

Looks like `fields`, `childMdx.fields`, and `childrenMdx.fields` are all `SORTABLE`, yet they have the `deprecationReason` of "Sorting on fields that need arguments to resolve is deprecated." I can't find any code that should set `deprecationReason` with `depth = 0` for the recursive calls.

**Comment by phun-ky** [comment]
I'm having the same issue after upgrading to v4, and I find no documentation about this change

**Comment by meehawk** [comment]
Just upgraded to v4, facing the same issue. Any help would be awesome

**Comment by mflisikowski** [comment]
.

**Comment by izackwu** [comment]
Same issue here, no idea how to solve it :(

**Comment by anakornk** [comment]
Same issue here on gatsby 4. Any updates?

**Comment by phun-ky** [comment]
Issue still persists, need documentation on how to use slug for sorting (or equivalent)

**Comment by phun-ky** [comment]
Issue still persist, please reply to this.

**Comment by fzyzcjy** [comment]
Still have this issue, I am using something like `fields___mySlug` and it has this warning

**Comment by Undistraction** [comment]
This is now giving me problems as of `gatsby@4.8.0`. Building pages from `gatsby-node.js`:

Previously, this worked fine (until at least `4.5.0`), 

```
graphql(`
    {
      articles: allMarkdownRemark(
        sort: { fields: fields___publishedDate, order: DESC }
        filter: { 
          fields: { 
            type: { eq: "article" },
            isPublished: { eq: true }
          } 
        }
      ) {
        edges {
          node {
            fields {
              slug
              template
            }
          }
        }
      }
    }
  `)
  ```


Now it returns an error:


```
{
  errors: [
    Error: Invariant violation: inconsistent node counters detected
        at intersectNodesByCounter (/Users/x/node_modules/gatsby/src/datastore/in-memory/indexing.ts:1145:15)
        at applyFastFilters (/Users/x/node_modules/gatsby/src/datastore/in-memory/run-fast-filters.ts:118:30)
        at convertAndApplyFastFilters (/Users/x/node_modules/gatsby/src/datastore/in-memory/run-fast-filters.ts:382:18)
        at runFastFiltersAndSort (/Users/x/node_modules/gatsby/src/datastore/in-memory/run-fast-filters.ts:308:18)
        at Object.runQuery (/Users/x/node_modules/gatsby/src/datastore/lmdb/lmdb-datastore.ts:205:26)
        at LocalNodeModel._query (/Users/x/node_modules/gatsby/src/schema/node-model.js:342:58)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at LocalNodeModel.findAll (/Users/x/node_modules/gatsby/src/schema/node-model.js:379:36)
        at findManyPaginatedResolver (/Users/x/node_modules/gatsby/src/schema/resolvers.ts:94:20)
        at async Promise.all (index 0)
        at GraphQLRunner.query (/Users/x/node_modules/gatsby/src/query/graphql-runner.ts:220:14)
        at wrappedGraphQL (/Users/x/node_modules/gatsby/src/services/create-pages.ts:34:25) {
      locations: [Array],
      path: [Array]
    }
  ],
  data: null
}
```

  
If I remove the sort, it works:

 ```
graphql(`
    {
      articles: allMarkdownRemark(
        filter: { 
          fields: { 
            type: { eq: "article" },
            isPublished: { eq: true }
          } 
        }
      ) {
        edges {
          node {
            fields {
              slug
              template
            }
          }
        }
      }
    }
  `)
  ```

**Comment by mbcod3** [comment]
graphql shows warning if you use field to sort that was created using gatsby api creatNodeField
