### ISSUE TITLE
Loading Static Query White Screen

### ISSUE THREAD

**Issue by grahamd711** [gatsbyjs/gatsby#31586]
## Description

There seems to be a bug on our production builds that causes a white blank screen to show with the Loading(Static Query) in the top left corner. No other components in the application render. We are running Gatsby 3.1.2 and babel-plugin-remove-graphql-queries version 3.5.0.

Possibly related to: [Loading(Static Query) white screen on gatsby build #25920
](https://github.com/gatsbyjs/gatsby/issues/25920)

We run two StaticQueries in two separate components that render on the homepage. Here is the code for them:

Gist 1: https://gist.github.com/grahamd711/5855edb75457d804ce1d2c391a019a94

Gist 2: https://gist.github.com/grahamd711/28f62bc44b8abc82e856f14cc7b872df

### Steps to reproduce

The issue is hard to reproduce and only shows intermittently on our production Gatsby Cloud instance. We are using Gatsby Cloud for builds and then pushing to Fastly CDN for hosting.

There are no errors in the console and nothing to display besides the Loading(StaticQuery) and the white page. This error only occurs on production and not on development.

We have tried to clear the cache manually within Gatsby Cloud and the issue still occurs intermittently. Is anyone running into this same problem or have advice on how to fix?

Production URL: https://mparticlecomgatsbymain07610.gtsb.io/

### Expected result

The static queries should load without this loading description. The production application should continue running all page and static queries without the white screen.

### Actual result

In our production environment, the Loading(Static Query) text appears in the top left. The rest of the app does not render to the page and a blank white screen is shown. 

### Environment

```
System:
    OS: macOS 11.3
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 76.0.1
    Safari: 14.1
  npmPackages:
    gatsby: ^3.1.2 => 3.5.1 
    gatsby-image: ^3.1.0 => 3.1.0 
    gatsby-plugin-csp: ^1.1.3 => 1.1.3 
    gatsby-plugin-image: ^1.1.2 => 1.5.0 
    gatsby-plugin-manifest: ^3.1.0 => 3.1.0 
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1 
    gatsby-plugin-offline: ^4.1.0 => 4.1.0 
    gatsby-plugin-react-helmet: ^4.1.0 => 4.1.0 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-root-import: ^2.0.6 => 2.0.6 
    gatsby-plugin-sass: ^4.1.0 => 4.1.0 
    gatsby-plugin-sharp: ^3.1.2 => 3.1.2 
    gatsby-plugin-sitemap: ^3.1.0 => 3.1.0 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.20 => 1.1.21 
    gatsby-source-custom-api: ^2.1.4 => 2.1.4 
    gatsby-source-filesystem: ^3.1.0 => 3.1.0 
    gatsby-source-prismic: ^3.3.4 => 3.3.4 
    gatsby-transformer-sharp: ^3.1.0 => 3.1.0 
```

**Comment by grahamd711** [comment]
Any ideas here?

We are also using a `<StaticQuery>` in our layout template: https://gist.github.com/grahamd711/44250c718871632b4c9eaaa69a83fe67

Is there anything wrong with this structure?

**Comment by TylerBarnes** [comment]
Hi @grahamd711 , since this seems to be specific to your site hosted on Cloud I would recommend opening a support request from your dashboard on Gatsby Cloud. That will make it easier for our team to debug this. I'll keep this issue open though and tag the core team via some labels as well though.

**Comment by iheathers** [comment]
I have the same issue. It had been almost 2 months and no changes were made to the production build. Now out of the blue, the gatsby site shows a blank screen. It will go away after clearing the cache. 

While trying to reproduce the bug during development, I got the following logs. 

```

logger.mjs:44 workbox Using CacheFirst to respond to '/component---src-pages-accountfunding-js-40412217d06678e6ff14.js'
logger.mjs:44 workbox Using CacheFirst to respond to '/component---src-pages-disbursements-js-d443a9a21003d934f175.js'
logger.mjs:44 workbox Using CacheFirst to respond to '/component---src-pages-collections-js-de959249e1505ad5759b.js'
logger.mjs:44 workbox Router is responding to: /static/cdeb89f482e6a6642f8c89462082fe9f/ff4be/icon-higher%403x.png
logger.mjs:44 workbox Router is responding to: /static/b8901a13aae6f1e3e7ac6666bb9cfee9/ff4be/icon-lower%403x.png
logger.mjs:44 workbox Using CacheFirst to respond to '/static/cdeb89f482e6a6642f8c89462082fe9f/ff4be/icon-higher%403x.png'
logger.mjs:44 workbox Using CacheFirst to respond to '/static/b8901a13aae6f1e3e7ac6666bb9cfee9/ff4be/icon-lower%403x.png'
logger.mjs:44 workbox Router is responding to: /static/154a1c21576ef88e767cb490bd234f06/58556/higher-graph-md%403x.webp
logger.mjs:44 workbox Router is responding to: /static/c1082481544ae6dec4486ca4e2495c53/58556/lower-graph-md%403x.webp
logger.mjs:44 workbox Using CacheFirst to respond to '/static/154a1c21576ef88e767cb490bd234f06/58556/higher-graph-md%403x.webp'
logger.mjs:44 workbox Using CacheFirst to respond to '/static/c1082481544ae6dec4486ca4e2495c53/58556/lower-graph-md%403x.webp'
logger.mjs:44 workbox Router is responding to: /static/c6bfa09da80b8f7908fdfdc2ce426393/d0d38/cost-img-lg%403x.webp
logger.mjs:44 workbox Using CacheFirst to respond to '/static/c6bfa09da80b8f7908fdfdc2ce426393/d0d38/cost-img-lg%403x.webp'
logger.mjs:44 workbox Router is responding to: /static/45db3156b0cf89884039e973ff3432b4/0ed73/i-phone-lg.webp
logger.mjs:44 workbox Using CacheFirst to respond to '/static/45db3156b0cf89884039e973ff3432b4/0ed73/i-phone-lg.webp'
logger.mjs:44 workbox Router is responding to: /static/7e7ef65553684e08ca6d72d59c8d4cb0/58556/code-md%403x.webp
logger.mjs:44 workbox Using CacheFirst to respond to '/static/7e7ef65553684e08ca6d72d59c8d4cb0/58556/code-md%403x.webp'
logger.mjs:44 workbox Router is responding to: /static/9a94db3f306a63d1978621dc64a737ba/48562/icon-connections%403x.webp
logger.mjs:44 workbox Router is responding to: /static/968f3d0cf157592cc68f84aadfca400d/48562/icon-credit-card-new%403x.webp
logger.mjs:44 workbox Router is responding to: /static/dc570529b32f5f4865a36f9931940051/48562/icon-uptime%403x.webp
logger.mjs:44 workbox Using CacheFirst to respond to '/static/9a94db3f306a63d1978621dc64a737ba/48562/icon-connections%403x.webp'
logger.mjs:44 workbox Using CacheFirst to respond to '/static/968f3d0cf157592cc68f84aadfca400d/48562/icon-credit-card-new%403x.webp'
logger.mjs:44 workbox Using CacheFirst to respond to '/static/dc570529b32f5f4865a36f9931940051/48562/icon-uptime%403x.webp'
logger.mjs:44 workbox Router is responding to: /static/42ee715637150586e446b7f5bcce8927/30305/alex%403x.webp
logger.mjs:44 workbox Router is responding to: /static/1337fd2f939e79c52b70f3384620e99c/30305/angela%403x.webp
logger.mjs:44 workbox Using CacheFirst to respond to '/static/42ee715637150586e446b7f5bcce8927/30305/alex%403x.webp'
logger.mjs:44 workbox Using CacheFirst to respond to '/static/1337fd2f939e79c52b70f3384620e99c/30305/angela%403x.webp'
logger.mjs:44 workbox Router is responding to: /page-data/app-data.json
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/page-data/app-data.json'
logger.mjs:44 workbox Router is responding to: /component---src-pages-contact-js-6991263f528bc84135bf.js
logger.mjs:44 workbox Router is responding to: /page-data/sq/d/2312333847.json
logger.mjs:44 workbox Using CacheFirst to respond to '/component---src-pages-contact-js-6991263f528bc84135bf.js'
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/page-data/sq/d/2312333847.json'
logger.mjs:44 workbox Router is responding to: /contact
logger.mjs:44 workbox Precaching is responding to: /webpack-runtime-c751f3a1687d5a63bf47.js
logger.mjs:44 workbox Precaching is responding to: /app-f68f5922d1dbd62812ed.js
logger.mjs:44 workbox Precaching is responding to: /framework-c8d3a5345e3f321d7da5.js
logger.mjs:44 workbox Precaching is responding to: /component---cache-caches-gatsby-plugin-offline-app-shell-js-fd4fb51a6fac1c18bdde.js
logger.mjs:44 workbox Router is responding to: https://script.crazyegg.com/pages/scripts/unde/fined.js
logger.mjs:44 workbox Network request for 'https://script.crazyegg.com/pages/scripts/unde/fined.js' threw an error. TypeError: Failed to fetch
print @ logger.mjs:44
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to 'https://script.crazyegg.com/pages/scripts/unde/fined.js'
The FetchEvent for "https://script.crazyegg.com/pages/scripts/unde/fined.js" resulted in a network error response: the promise was rejected.
StaleWhileRevalidate.mjs:168 Uncaught (in promise) no-response: The strategy could not generate a response for 'https://script.crazyegg.com/pages/scripts/unde/fined.js'. The underlying error is TypeError: Failed to fetch.
    at StaleWhileRevalidate.makeRequest (http://localhost:9000/workbox-v4.3.1/workbox-strategies.dev.js:1005:15)
script.crazyegg.com/pages/scripts/unde/fined.js:1 Failed to load resource: net::ERR_FAILED
logger.mjs:44 workbox Router is responding to: /page-data/app-data.json
logger.mjs:44 workbox Router is responding to: /page-data/contact/page-data.json
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/page-data/app-data.json'
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/page-data/contact/page-data.json'
logger.mjs:44 workbox Router is responding to: /styles.f351d7f0f5a4a2a66c40.css
logger.mjs:44 workbox Router is responding to: /styles-e9d24b1846c7d6eb9685.js
logger.mjs:44 workbox Router is responding to: /501f03c7e8682769d387b93d6f17eef16f038e51-0d300e08b3025f28fb70.js
logger.mjs:44 workbox Router is responding to: /e2f60280ae1c3cdfbf16cad8521319ce9527a183-1f19ce6d628ededec277.js
logger.mjs:44 workbox Router is responding to: /component---src-pages-contact-js-6991263f528bc84135bf.js
logger.mjs:44 workbox Using CacheFirst to respond to '/styles.f351d7f0f5a4a2a66c40.css'
logger.mjs:44 workbox Router is responding to: /page-data/sq/d/2312333847.json
logger.mjs:44 workbox Using CacheFirst to respond to '/styles-e9d24b1846c7d6eb9685.js'
logger.mjs:44 workbox Using CacheFirst to respond to '/501f03c7e8682769d387b93d6f17eef16f038e51-0d300e08b3025f28fb70.js'
logger.mjs:44 workbox Using CacheFirst to respond to '/e2f60280ae1c3cdfbf16cad8521319ce9527a183-1f19ce6d628ededec277.js'
logger.mjs:44 workbox Using CacheFirst to respond to '/component---src-pages-contact-js-6991263f528bc84135bf.js'
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/page-data/sq/d/2312333847.json'
logger.mjs:44 workbox Router is responding to: https://sc.lfeeder.com/lftracker_v1_ywVkO4X2ym18Z6Bj.js
logger.mjs:44 workbox Network request for 'https://sc.lfeeder.com/lftracker_v1_ywVkO4X2ym18Z6Bj.js' threw an error. TypeError: Failed to fetch
print @ logger.mjs:44
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to 'https://sc.lfeeder.com/lftracker_v1_ywVkO4X2ym18Z6Bj.js'
The FetchEvent for "https://sc.lfeeder.com/lftracker_v1_ywVkO4X2ym18Z6Bj.js" resulted in a network error response: the promise was rejected.
StaleWhileRevalidate.mjs:168 Uncaught (in promise) no-response: The strategy could not generate a response for 'https://sc.lfeeder.com/lftracker_v1_ywVkO4X2ym18Z6Bj.js'. The underlying error is TypeError: Failed to fetch.
    at StaleWhileRevalidate.makeRequest (http://localhost:9000/workbox-v4.3.1/workbox-strategies.dev.js:1005:15)
sc.lfeeder.com/lftracker_v1_ywVkO4X2ym18Z6Bj.js:1 Failed to load resource: net::ERR_FAILED
logger.mjs:44 workbox Router is responding to: https://css.zohostatic.com/recruit/embed_careers_site/css/v1.0/embed_jobs.css
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to 'https://css.zohostatic.com/recruit/embed_careers_site/css/v1.0/embed_jobs.css'
logger.mjs:44 workbox Router is responding to: /static/GothamPro-dfd2ec9d3d6f00024cb06d36fd93eaa6.ttf
logger.mjs:44 workbox Router is responding to: /static/GothamPro-Medium-be1f696524e0050cc7d8d5011b5e5712.ttf
logger.mjs:44 workbox Using CacheFirst to respond to '/static/GothamPro-dfd2ec9d3d6f00024cb06d36fd93eaa6.ttf'
logger.mjs:44 workbox Using CacheFirst to respond to '/static/GothamPro-Medium-be1f696524e0050cc7d8d5011b5e5712.ttf'
logger.mjs:44 workbox Router is responding to: /static/b0dec972caf83b5470ad65d8f4fb78e7/d4d8a/marqeta%403x.webp
logger.mjs:44 workbox Router is responding to: /static/b869bf3a44b19eca15f1b6af88c016e1/d4d8a/earnin%403x.webp
logger.mjs:44 workbox Router is responding to: /static/4c2e97ee3db017ed5afd530202b7d973/d4d8a/branch-logo%403x.webp
logger.mjs:44 workbox Router is responding to: /static/d0ee46b7f52eee90b92991fcb6877027/d4d8a/coinstar-logo%403x.webp
logger.mjs:44 workbox Router is responding to: /static/ac706819921994a522dae38133a6c2dc/d4d8a/paynearme%403x.webp
logger.mjs:44 workbox Router is responding to: /static/38ce482efc43c930816b570fedf82cf4/d4d8a/da-vinci-logo%403x.webp
logger.mjs:44 workbox Using CacheFirst to respond to '/static/b0dec972caf83b5470ad65d8f4fb78e7/d4d8a/marqeta%403x.webp'
logger.mjs:44 workbox Using CacheFirst to respond to '/static/b869bf3a44b19eca15f1b6af88c016e1/d4d8a/earnin%403x.webp'
logger.mjs:44 workbox Router is responding to: /icons-8cd709f5d7ebee7ffc421faa62286f1d/manifest.json
logger.mjs:44 workbox Using CacheFirst to respond to '/static/4c2e97ee3db017ed5afd530202b7d973/d4d8a/branch-logo%403x.webp'
logger.mjs:44 workbox Using CacheFirst to respond to '/static/d0ee46b7f52eee90b92991fcb6877027/d4d8a/coinstar-logo%403x.webp'
logger.mjs:44 workbox Using CacheFirst to respond to '/static/ac706819921994a522dae38133a6c2dc/d4d8a/paynearme%403x.webp'
logger.mjs:44 workbox Router is responding to: /page-data/index/page-data.json
logger.mjs:44 workbox Using CacheFirst to respond to '/static/38ce482efc43c930816b570fedf82cf4/d4d8a/da-vinci-logo%403x.webp'
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/icons-8cd709f5d7ebee7ffc421faa62286f1d/manifest.json'
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/page-data/index/page-data.json'
icons-8cd709f5d7ebee7ffc421faa62286f1d/manifest.json:1 Manifest: property 'description' ignored, type string expected.
logger.mjs:44 workbox Router is responding to: /icons-8cd709f5d7ebee7ffc421faa62286f1d/android-chrome-144x144.png
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/icons-8cd709f5d7ebee7ffc421faa62286f1d/android-chrome-144x144.png'
logger.mjs:44 workbox Router is responding to: /page-data/index/page-data.json
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/page-data/index/page-data.json'
logger.mjs:44 workbox Router is responding to: /component---src-pages-index-js-ad849310733fa8ce47bc.js
logger.mjs:44 workbox Using CacheFirst to respond to '/component---src-pages-index-js-ad849310733fa8ce47bc.js'
logger.mjs:44 workbox Router is responding to: /page-data/careers/page-data.json
logger.mjs:44 workbox Router is responding to: /page-data/about/page-data.json
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/page-data/about/page-data.json'
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/page-data/careers/page-data.json'
logger.mjs:44 workbox Router is responding to: /page-data/careers/page-data.json
logger.mjs:44 workbox Router is responding to: /page-data/about/page-data.json
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/page-data/careers/page-data.json'
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/page-data/about/page-data.json'
logger.mjs:44 workbox Router is responding to: /component---src-pages-careers-js-88f29600a9680fa01ff0.js
logger.mjs:44 workbox Router is responding to: /component---src-pages-about-js-9e3875c7d6edbc69869a.js
logger.mjs:44 workbox Using CacheFirst to respond to '/component---src-pages-careers-js-88f29600a9680fa01ff0.js'
logger.mjs:44 workbox Using CacheFirst to respond to '/component---src-pages-about-js-9e3875c7d6edbc69869a.js'
logger.mjs:44 workbox Router is responding to: /page-data/app-data.json
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/page-data/app-data.json'
logger.mjs:44 workbox Router is responding to: /component---src-pages-about-js-9e3875c7d6edbc69869a.js
logger.mjs:44 workbox Router is responding to: /page-data/sq/d/1025482396.json
logger.mjs:44 workbox Router is responding to: /page-data/sq/d/2078260279.json
logger.mjs:44 workbox Router is responding to: /page-data/sq/d/2156606666.json
logger.mjs:44 workbox Router is responding to: /page-data/sq/d/3468780003.json
logger.mjs:44 workbox Router is responding to: /page-data/sq/d/3480846893.json
logger.mjs:44 workbox Router is responding to: /page-data/sq/d/3544841708.json
logger.mjs:44 workbox Router is responding to: /page-data/sq/d/4150898826.json
logger.mjs:44 workbox Router is responding to: /page-data/sq/d/879917867.json
logger.mjs:44 workbox Using CacheFirst to respond to '/component---src-pages-about-js-9e3875c7d6edbc69869a.js'
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/page-data/sq/d/1025482396.json'
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/page-data/sq/d/2078260279.json'
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/page-data/sq/d/2156606666.json'
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/page-data/sq/d/3468780003.json'
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/page-data/sq/d/3480846893.json'
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/page-data/sq/d/3544841708.json'
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/page-data/sq/d/4150898826.json'
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/page-data/sq/d/879917867.json'
react-dom.production.min.js:209 Error: The result of this StaticQuery could not be fetched.

This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues
    at h (gatsby-browser-entry.js:77)
    at bM (leaderships.jsx:11)
    at Ki (react-dom.production.min.js:153)
    at vo (react-dom.production.min.js:261)
    at cu (react-dom.production.min.js:246)
    at ou (react-dom.production.min.js:246)
    at Zo (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at scheduler.production.min.js:19
    at Ql (react-dom.production.min.js:122)
Za @ react-dom.production.min.js:209
react-dom.production.min.js:209 Error: The result of this StaticQuery could not be fetched.

This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues
    at h (gatsby-browser-entry.js:77)
    at bM (leaderships.jsx:11)
    at Ki (react-dom.production.min.js:153)
    at vo (react-dom.production.min.js:261)
    at cu (react-dom.production.min.js:246)
    at ou (react-dom.production.min.js:246)
    at Zo (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at scheduler.production.min.js:19
    at Ql (react-dom.production.min.js:122)
Za @ react-dom.production.min.js:209
react-dom.production.min.js:123 Uncaught Error: The result of this StaticQuery could not be fetched.

This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues
    at h (gatsby-browser-entry.js:77)
    at bM (leaderships.jsx:11)
    at Ki (react-dom.production.min.js:153)
    at vo (react-dom.production.min.js:261)
    at cu (react-dom.production.min.js:246)
    at ou (react-dom.production.min.js:246)
    at Zo (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at scheduler.production.min.js:19
    at Ql (react-dom.production.min.js:122)
logger.mjs:44 workbox Router is responding to: /styles.f351d7f0f5a4a2a66c40.css
logger.mjs:44 workbox Router is responding to: https://unpkg.com/ionicons@4.4.4/dist/css/ionicons.min.css
logger.mjs:44 workbox Router is responding to: https://css.zohostatic.com/recruit/embed_careers_site/css/v1.0/embed_jobs.css
logger.mjs:44 workbox Router is responding to: /icons-8cd709f5d7ebee7ffc421faa62286f1d/manifest.json
logger.mjs:44 workbox Using CacheFirst to respond to '/styles.f351d7f0f5a4a2a66c40.css'
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to 'https://unpkg.com/ionicons@4.4.4/dist/css/ionicons.min.css'
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to 'https://css.zohostatic.com/recruit/embed_careers_site/css/v1.0/embed_jobs.css'
logger.mjs:44 workbox Using StaleWhileRevalidate to respond to '/icons-8cd709f5d7ebee7ffc421faa62286f1d/manifest.json'

```

**Comment by marco-lambdas** [comment]
got the same issue the site we have been working on shows "Loading (StaticQuery)" on the component where it uses "StaticQuery" of gatsby.

This issue only shows during the production build while the development build is fine.

does this have something to do with the build because it seems to be showing this
![gatsby_build](https://user-images.githubusercontent.com/72480297/120432090-f9a38800-c3ab-11eb-968b-319b9a0229d7.JPG)
