### ISSUE TITLE
Sitemap Plugin: Includes breaking changes not reflected in documentation.

### ISSUE THREAD

**Issue by MANTENN** [gatsbyjs/gatsby#32324]
### Preliminary Checks

- [x] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

Working config
```
{
      resolve: `gatsby-plugin-sitemap`,
      options: {
        output: `/sitemap.xml`,
        // Exclude specific pages or groups of pages using glob parameters
        // See: https://github.com/isaacs/minimatch
        // The example below will exclude the single `path/to/page` and all routes beginning with `category`
        exclude: [
          `/privacy-policy`,
        ],
        query: `
          {
            site {
              siteMetadata {
                siteUrl
              }
            }
  
            allSitePage {
              edges {
                node {
                  path
                }
              }
            }
        }`,
        serialize: ([pathObj, path, matches]) => ({
          url: site.siteMetadata.siteUrl + path,
          changefreq: `daily`,
          priority: 0.7,
        }),
        resolveSiteUrl: ({ site }) => site.siteMetadata.siteUrl,
        resolvePages: ({ allSitePage }) =>
          allSitePage.edges.map(({ node }) => ({ path: node.path })),
        excludes: [
          `/privacy-policy`,
        ],
        filterPages: (...params) => {
          return params
        },
        // needs all these aditional options otherwise build fails; 5.9 includes breaking changes not reflected in gatsby docs; temp patch until its fixed in future gatsby releases
      },
    },
```

`exclude` option seems irrelevant with the following base

`resolveSiteUrl`,`resolvePages`,`excludes`, and`filterPages` are required otherwise build fails with previous configuration.

```
function serialize(page, _ref3) {
  var resolvePagePath = _ref3.resolvePagePath;
  return {
    url: "" + resolvePagePath(page),
    changefreq: "daily",
    priority: 0.7
  };
}
```

Version: `"gatsby-plugin-sitemap": "^4.5.0",` 

`filterPages` seems to be more like `filterPage` as it returns the data to serialize in the same structure. 

Serialize function takes in an array(pathObj, pathString, matchObject) and returns an object.

### Steps to Resolve this Issue

Add the working config added above.

**Comment by MANTENN** [comment]
Sorry for the wrong flag, fails at the end.

```
⠴ Caching JavaScript and CSS webpack compilation
⠧ Caching HTML renderer compilation
⠋ onPostBuild
/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

EmptySitemap: You ended the stream without writing anything.
Emitted 'error' event on SitemapStream instance at:
    at done (_stream_transform.js:209:19)
    at _stream_transform.js:143:7
    at SitemapStream._flush (/node_modules/sitemap/dist/lib/sitemap-stream.js:82:13)
    at SitemapStream.prefinish (_stream_transform.js:142:10)
    at SitemapStream.emit (events.js:315:20)
    at prefinish (_stream_writable.js:618:14)
    at finishMaybe (_stream_writable.js:626:5)
    at SitemapStream.Writable.end (_stream_writable.js:570:5)
    at SitemapAndIndexStream._flush (/node_modules/sitemap/dist/lib/sitemap-index-stream.js:101:29)
    at SitemapAndIndexStream.prefinish (_stream_transform.js:142:10)
    at SitemapAndIndexStream.emit (events.js:315:20)
    at prefinish (_stream_writable.js:618:14)
    at finishMaybe (_stream_writable.js:626:5)
    at SitemapAndIndexStream.Writable.end (_stream_writable.js:570:5)
    at Readable.onend (_stream_readable.js:677:10)
    at Object.onceWrapper (events.js:421:28)
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by justinkneff** [comment]
@MANTENN How did you resolve this issue? I have the same as the config above but I don't see how you resolved it. I get the same "yoga-layout" modules error and my sitemap.xml returns a 404.

**Comment by MANTENN** [comment]
@justinneff I updated the config by adding the core functionality of the plugin.

Heres what I got exactly in the config for the sitemap.

```javascript
{
      resolve: `gatsby-plugin-sitemap`,
      options: {
        output: `/sitemap.xml`,
        query: `
          {
            site {
              siteMetadata {
                siteUrl
              }
            }
  
            allSitePage {
              edges {
                node {
                  path
                }
              }
            }
        }`,
        serialize: (page, { resolvePagePath }) => ({
          url: resolvePagePath(page),
          changefreq: `daily`,
          priority: 0.7,
        }),
        resolveSiteUrl: ({ site }) => site.siteMetadata.siteUrl,
        resolvePagePath: (page) => {
          if (!(page !== null && page !== void 0 && page.path)) {
            throw Error(
              '`path` does not exist on your page object.\nMake the page URI available at `path` or provide a custom `resolvePagePath` function.\nhttps://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap/#api-reference\n      '
            )
          }

          return page.path
        },
        resolvePages: (data) =>
          data.allSitePage.edges.map(({ node }) => ({ path: node.path })),
        // Exclude specific pages or groups of pages using glob parameters
        // See: https://github.com/isaacs/minimatch
        // The example below will exclude the single `path/to/page` and all routes beginning with `category`
        excludes: [
          `/privacy-policy`,
          `/reviews/*`,
        ],
        filterPages: (
          page,
          excludedRoute,
          { minimatch, withoutTrailingSlash, resolvePagePath }
        ) => {
          if (typeof excludedRoute !== 'string') {
            throw new Error(
              "You've passed something other than string to the exclude array. This is supported, but you'll have to write a custom filter function.\nIgnoring the input for now: " +
                JSON.stringify(excludedRoute, null, 2) +
                '\nhttps://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap/#api-reference\n      '
            )
          }
          return minimatch(
            withoutTrailingSlash(resolvePagePath(page)),
            withoutTrailingSlash(excludedRoute)
          )
        },
        // needs all these additional options otherwise build fails; 5.9 includes breaking changes not reflected in gatsby docs; temp patch until its fixed in future gatsby releases
```

I went into the node_modules and copied the functions to temporarily patch the errors. I know I can create a npm patch but that's more work. 

Let me know if that works for you. 

Also, the output is a folder now instead of a sitemap.xml.

**Comment by MANTENN** [comment]
@justinkneff Also there is a different sitemap plugin by ghost I haven't tried it but was enticed to try it out after ironing out the issues. 

https://www.gatsbyjs.com/plugins/gatsby-plugin-advanced-sitemap/
