### ISSUE TITLE
Upgrade sharp version to at least 0.18.2 in gatsby-plugin-sharp npm package

### ISSUE THREAD

**Issue by trigun539** [gatsbyjs/gatsby#3264]
Unable to install gatsby-remark-images due to firewall proxy strict rules. Since the gatsby-remark-images relies on gatsby-plugin-sharp and that in turns relies on sharp 0.17.3 I am unable to install it due to the fact that it is trying to download the libvips from the internet directly.

Is there anyway we could upgrade the gatsby-plugin-sharp npm module to use a version greater than 0.18.2? There was a feature to have sharp download libvips from local path instead of trying to download it from the internet.

I have already followed up with sharp author to see if there was anyway around it but it is proving hard to implement a fix for this. [Issue](https://github.com/lovell/sharp/issues/1053#issuecomment-352087843)

### Environment

Gatsby version: 1.9.73
Node.js version: 6.11.2
Operating System: Windows

### Actual result

`ERROR: Download of https://dl.bintray.com/lovell/sharp/libvips-8.4.2-win32-x64.tar.gz failed:`

`npm verb stack Error: sharp@0.17.3 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\mde-tools\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (C:\mde-tools\npm\node_modules\npm\lib\utils\spawn.js:40:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:886:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm verb pkgid sharp@0.17.3
`

### Expected behavior

Should install without errors and set an environment variable to download libvips locally as per the documentation [here](http://sharp.dimens.io/en/stable/install/#pre-compiled-libvips-binaries).

I appreciate your guys' help with this. Thanks

**Comment by fk** [comment]
👍
