### ISSUE TITLE
`gatsby new` creates a broken project

### ISSUE THREAD

**Issue by chungwu** [gatsbyjs/gatsby#33160]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When I create a new project using `gatsby new`, the new project has missing dependencies; specifically, it complains about missing `gatsby-core-utils`.

### Reproduction Link

https://github.com/chungwu/gatsby-new-broken

### Steps to Reproduce

1. `npx -p gatsby gatsby new /tmp/blah`
2. `cd /tmp/blah`
3. `npm run develop`

### Expected Result

Brings up the development server

### Actual Result

See this error:

```
/tmp/blah/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Cannot find module 'gatsby-core-utils'
Require stack:
- /tmp/blah/node_modules/babel-plugin-remove-graphql-queries/index.js
- /tmp/blah/node_modules/gatsby/dist/query/file-parser.js
- /tmp/blah/node_modules/gatsby/dist/query/query-compiler.js
- /tmp/blah/node_modules/gatsby/dist/query/query-watcher.js
- /tmp/blah/node_modules/gatsby/dist/services/extract-queries.js
- /tmp/blah/node_modules/gatsby/dist/services/index.js
- /tmp/blah/node_modules/gatsby/dist/state-machines/develop/services.js
- /tmp/blah/node_modules/gatsby/dist/state-machines/develop/index.js
- /tmp/blah/node_modules/gatsby/dist/commands/develop-process.js
- /tmp/blah/.cache/tmp-22818-ODc7MlE67XMs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/tmp/blah/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/tmp/blah/node_modules/babel-plugin-remove-graphql-queries/index.js:19:24)
    at Module._compile (/tmp/blah/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/tmp/blah/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/tmp/blah/node_modules/gatsby/src/query/file-parser.js:15:5)
    at Module._compile (/tmp/blah/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/blah/node_modules/babel-plugin-remove-graphql-queries/index.js',
    '/tmp/blah/node_modules/gatsby/dist/query/file-parser.js',
    '/tmp/blah/node_modules/gatsby/dist/query/query-compiler.js',
    '/tmp/blah/node_modules/gatsby/dist/query/query-watcher.js',
    '/tmp/blah/node_modules/gatsby/dist/services/extract-queries.js',
    '/tmp/blah/node_modules/gatsby/dist/services/index.js',
    '/tmp/blah/node_modules/gatsby/dist/state-machines/develop/services.js',
    '/tmp/blah/node_modules/gatsby/dist/state-machines/develop/index.js',
    '/tmp/blah/node_modules/gatsby/dist/commands/develop-process.js',
    '/tmp/blah/.cache/tmp-22818-ODc7MlE67XMs'
  ]
}
```

### Environment

```shell
System:
    OS: Linux 5.11 Pop!_OS 20.04 LTS
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.1 - ~/.node/14.16.1/bin/node
    Yarn: 1.22.10 - ~/.node/14.16.1/bin/yarn
    npm: 6.14.12 - ~/.node/14.16.1/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 92.0.4515.159
    Firefox: 91.0.2
  npmPackages:
    gatsby: ^3.13.0 => 3.13.0 
    gatsby-plugin-image: ^1.13.0 => 1.13.0 
    gatsby-plugin-manifest: ^3.13.0 => 3.13.0 
    gatsby-plugin-offline: ^4.13.0 => 4.13.0 
    gatsby-plugin-react-helmet: ^4.13.0 => 4.13.0 
    gatsby-plugin-sharp: ^3.13.0 => 3.13.0 
    gatsby-source-filesystem: ^3.13.0 => 3.13.0 
    gatsby-transformer-sharp: ^3.13.0 => 3.13.0
```

### Config Flags

No

**Comment by chungwu** [comment]
Hmm actually cannot reproduce this elsewhere; probably the problem is with me :sweat_smile: Closing.

**Comment by ComputerCarl** [comment]
I am getting this `gatsby-core-utils` error. Same reproduction steps.
Win 10 build 18362.30
```
$ gatsby develop
Q:\Libraries\Desktop\gatsby-virgin\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

Error: Cannot find module 'gatsby-core-utils'
Require stack:
- Q:\Libraries\Desktop\gatsby-virgin\node_modules\babel-plugin-remove-graphql-queries\index.js
- Q:\Libraries\Desktop\gatsby-virgin\node_modules\gatsby\dist\query\file-parser.js
- Q:\Libraries\Desktop\gatsby-virgin\node_modules\gatsby\dist\query\query-compiler.js
- Q:\Libraries\Desktop\gatsby-virgin\node_modules\gatsby\dist\query\query-watcher.js
- Q:\Libraries\Desktop\gatsby-virgin\node_modules\gatsby\dist\services\extract-queries.js
- Q:\Libraries\Desktop\gatsby-virgin\node_modules\gatsby\dist\services\index.js
- Q:\Libraries\Desktop\gatsby-virgin\node_modules\gatsby\dist\state-machines\develop\services.js
- Q:\Libraries\Desktop\gatsby-virgin\node_modules\gatsby\dist\state-machines\develop\index.js
- Q:\Libraries\Desktop\gatsby-virgin\node_modules\gatsby\dist\commands\develop-process.js
- Q:\Libraries\Desktop\gatsby-virgin\.cache\tmp-1044-wDfZR8Flz0iC
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (Q:\Libraries\Desktop\gatsby-virgin\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (Q:\Libraries\Desktop\gatsby-virgin\node_modules\babel-plugin-remove-graphql-queries\index.js:19:24)
    at Module._compile (Q:\Libraries\Desktop\gatsby-virgin\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (Q:\Libraries\Desktop\gatsby-virgin\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (Q:\Libraries\Desktop\gatsby-virgin\node_modules\gatsby\src\query\file-parser.js:15:5)
    at Module._compile (Q:\Libraries\Desktop\gatsby-virgin\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'Q:\\Libraries\\Desktop\\gatsby-virgin\\node_modules\\babel-plugin-remove-graphql-queries\\index.js',
    'Q:\\Libraries\\Desktop\\gatsby-virgin\\node_modules\\gatsby\\dist\\query\\file-parser.js',
    'Q:\\Libraries\\Desktop\\gatsby-virgin\\node_modules\\gatsby\\dist\\query\\query-compiler.js',
    'Q:\\Libraries\\Desktop\\gatsby-virgin\\node_modules\\gatsby\\dist\\query\\query-watcher.js',
    'Q:\\Libraries\\Desktop\\gatsby-virgin\\node_modules\\gatsby\\dist\\services\\extract-queries.js',
    'Q:\\Libraries\\Desktop\\gatsby-virgin\\node_modules\\gatsby\\dist\\services\\index.js',
    'Q:\\Libraries\\Desktop\\gatsby-virgin\\node_modules\\gatsby\\dist\\state-machines\\develop\\services.js',
    'Q:\\Libraries\\Desktop\\gatsby-virgin\\node_modules\\gatsby\\dist\\state-machines\\develop\\index.js',
    'Q:\\Libraries\\Desktop\\gatsby-virgin\\node_modules\\gatsby\\dist\\commands\\develop-process.js',
    'Q:\\Libraries\\Desktop\\gatsby-virgin\\.cache\\tmp-1044-wDfZR8Flz0iC'
  ]
}
```

**Comment by mikbeach** [comment]
I'm also running into a similar issue. I will post more details soon.

**Comment by mekeor** [comment]
I get a similar issue with Node 14.7.6 and npm 6.14.15:

```
$ npm run develop

> gatsby-project-name@1.0.0 develop /home/user/gatsby-project-path
> gatsby develop


 ERROR

Error in "/home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/gatsby-node.js": Cannot find module 'gatsby-plugin-sharp'
Require stack:
- /home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/dist/steps/source-nodes/create-nodes/process-node.js
- /home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/dist/steps/source-nodes/create-nodes/create-local-file-node.js
- /home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/dist/steps/create-schema-customization/type-filters.js
- /home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/dist/steps/create-schema-customization/helpers.js
- /home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/dist/models/remoteSchema.js
- /home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/dist/models/index.js
- /home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/dist/store.js
- /home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/dist/utils/format-log-message.js
- /home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/dist/utils/run-steps.js
- /home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/dist/gatsby-node.js
- /home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/gatsby-node.js
- /home/user/gatsby-project-path/node_modules/gatsby/dist/bootstrap/resolve-module-exports.js
- /home/user/gatsby-project-path/node_modules/gatsby/dist/bootstrap/load-plugins/validate.js
- /home/user/gatsby-project-path/node_modules/gatsby/dist/bootstrap/load-plugins/load.js
- /home/user/gatsby-project-path/node_modules/gatsby/dist/bootstrap/load-plugins/index.js
- /home/user/gatsby-project-path/node_modules/gatsby/dist/bootstrap/load-config-and-plugins.js
- /home/user/gatsby-project-path/node_modules/gatsby/dist/services/initialize.js
- /home/user/gatsby-project-path/node_modules/gatsby/dist/services/index.js
- /home/user/gatsby-project-path/node_modules/gatsby/dist/state-machines/develop/services.js
- /home/user/gatsby-project-path/node_modules/gatsby/dist/state-machines/develop/index.js
- /home/user/gatsby-project-path/node_modules/gatsby/dist/commands/develop-process.js
- /home/user/gatsby-project-path/.cache/tmp-45431-50VIcNNOnCg4



  Error: Cannot find module 'gatsby-plugin-sharp'
  Require stack:
  - /home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/dist/steps/source-nodes/create-nodes/process-node.js
  - /home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/dist/steps/source-nodes/create-nodes/create-local-file-node.js
  - /home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/dist/steps/create-schema-customization/type-filters.js
  - /home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/dist/steps/create-schema-customization/helpers.js
  - /home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/dist/models/remoteSchema.js
  - /home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/dist/models/index.js
  - /home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/dist/store.js
  - /home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/dist/utils/format-log-message.js
  - /home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/dist/utils/run-steps.js
  - /home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/dist/gatsby-node.js
  - /home/user/gatsby-project-path/node_modules/gatsby-source-wordpress/gatsby-node.js
  - /home/user/gatsby-project-path/node_modules/gatsby/dist/bootstrap/resolve-module-exports.js
  - /home/user/gatsby-project-path/node_modules/gatsby/dist/bootstrap/load-plugins/validate.js
  - /home/user/gatsby-project-path/node_modules/gatsby/dist/bootstrap/load-plugins/load.js
  - /home/user/gatsby-project-path/node_modules/gatsby/dist/bootstrap/load-plugins/index.js
  - /home/user/gatsby-project-path/node_modules/gatsby/dist/bootstrap/load-config-and-plugins.js
  - /home/user/gatsby-project-path/node_modules/gatsby/dist/services/initialize.js
  - /home/user/gatsby-project-path/node_modules/gatsby/dist/services/index.js
  - /home/user/gatsby-project-path/node_modules/gatsby/dist/state-machines/develop/services.js
  - /home/user/gatsby-project-path/node_modules/gatsby/dist/state-machines/develop/index.js
  - /home/user/gatsby-project-path/node_modules/gatsby/dist/commands/develop-process.js
  - /home/user/gatsby-project-path/.cache/tmp-45431-50VIcNNOnCg4
```

@chungwu, can you please re-open this issue? :)

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by ComputerCarl** [comment]
@LekoArts -- The first entry has link **Reproduction Link**, which does not work for me.

**Comment by LekoArts** [comment]
I've cloned the repository linked at _Reproduction Link_, removed the lock file, used `yarn` and then `yarn develop` and it works fine.

I've also created it from scratch with the reproduction steps and don't see a problem:

```shell
development/playground via ⬢ v14.17.6
➜ npx -p gatsby gatsby new blahblah
info Creating new site from git: https://github.com/gatsbyjs/gatsby-starter-default.git

Cloning into 'blahblah'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 28 (delta 3), reused 12 (delta 0), pack-reused 0
Receiving objects: 100% (28/28), 550.62 KiB | 2.37 MiB/s, done.
success Created starter directory layout
info Installing packages...

yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "gatsby > eslint-config-react-app@6.0.0" has unmet peer dependency "babel-eslint@^10.0.0".
warning "gatsby > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning "gatsby > eslint-plugin-graphql > graphql-config > @endemolshinegroup/cosmiconfig-typescript-loader > ts-node@9.1.1" has unmet peer dependency "typescript@>=2.7".
warning " > gatsby-plugin-image@1.13.0" has unmet peer dependency "@babel/core@^7.12.3".
[4/4] Building fresh packages...
info Initialising git in blahblah

info Create initial git commit in blahblah
info
Your new Gatsby site has been successfully bootstrapped. Start developing it by running:

  cd blahblah
  gatsby develop



development/playground via ⬢ v14.17.6 took 1m 22s
➜ cd blahblah

blahblah on  main is 📦 v0.1.0 via ⬢ v14.17.6
➜ yarn develop
yarn run v1.22.5
$ gatsby develop
success open and validate gatsby-configs, load plugins - 0.380s
success onPreInit - 0.020s
success initialize cache - 0.014s
success copy gatsby files - 0.059s
success Compiling Gatsby Functions - 0.171s
success onPreBootstrap - 0.181s
success createSchemaCustomization - 0.005s
success Checking for changed pages - 0.001s
success source and transform nodes - 0.043s
success building schema - 0.303s
success createPages - 0.001s
success createPagesStatefully - 0.061s
info Total nodes: 42, SitePage nodes: 6 (use --verbose for breakdown)
success Checking for changed pages - 0.001s
success update schema - 0.046s
success write out redirect data - 0.001s
success Build manifest and related icons - 0.052s
success onPostBootstrap - 0.056s
info bootstrap finished - 2.515s
success onPreExtractQueries - 0.001s
success extract queries from components - 1.099s
success write out requires - 0.004s
success run static queries - 0.011s - 2/2 188.07/s
success run page queries - 0.009s - 3/3 342.23/s
⠀
You can now view gatsby-starter-default in the browser.
⠀
  http://localhost:8000/
```

Please provide more information on how to reproduce this, e.g. how you install your project, your environment, etc.

**Comment by ComputerCarl** [comment]
`npx gatsby new project-name` is working for me once again.
