### ISSUE TITLE
gatsby-recipe has remark-mdx set to type: module as dependency, throws ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by phun-ky** [gatsbyjs/gatsby#33682]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

After a standard `npm i` install (after splatting `node_modules` and `package-lock.json`) I suddenly get this error when running `gatsby develop`:

```
> gatsby clean && gatsby develop

info Deleting .cache, public, /home/alexander/Workspace/if/if-design-system-site/node_modules/.cache/babel-loader,
/home/alexander/Workspace/if/if-design-system-site/node_modules/.cache/terser-webpack-plugin
info Successfully deleted directories

internal/modules/cjs/loader.js:1102
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/alexander/Workspace/if/if-design-system-site/node_modules/gatsby-recipes/node_modules/remark-mdx/index.js
require() of ES modules is not supported.
require() of /home/alexander/Workspace/if/if-design-system-site/node_modules/gatsby-recipes/node_modules/remark-mdx/index.js from
/home/alexander/Workspace/if/if-design-system-site/node_modules/gatsby-recipes/dist/graphql-server/server.js is an ES module file as it is a .js file whose nearest parent
package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from
/home/alexander/Workspace/if/if-design-system-site/node_modules/gatsby-recipes/node_modules/remark-mdx/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/alexander/Workspace/if/if-design-system-site/node_modules/gatsby-recipes/dist/graphql-server/server.js:52:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14) {
  code: 'ERR_REQUIRE_ESM'
}

```

What it tells me, is that `/home/alexander/Workspace/if/if-design-system-site/node_modules/gatsby-recipes/node_modules/remark-mdx/package.json.` is now suddenly an ESM module, but `gatsby` is not supporting ESM. 

What happened here?

### Reproduction Link

https://github.com/phun-ky/gatsby-module-bug

### Steps to Reproduce

1. `git clone https://github.com/phun-ky/gatsby-module-bug.git`
2. cd `gatsby-module-bug`
3. `npm i`
4. `npm run develop`

### Expected Result

No errors

### Actual Result

The error described above

### Environment

```shell
System:
    OS: Linux 4.15 Ubuntu 18.04.6 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 94.0.4606.81
    Firefox: 93.0
  npmPackages:
    gatsby: ^2.32.3 => 2.32.13 
    gatsby-image: ^2.4.1 => 2.11.0 
    gatsby-plugin-catch-links: ^2.3.3 => 2.10.0 
    gatsby-plugin-google-tagmanager: ^2.3.1 => 2.11.0 
    gatsby-plugin-manifest: ^2.4.2 => 2.12.1 
    gatsby-plugin-mdx: ^2.0.0 => 2.14.0 
    gatsby-plugin-offline: ^3.2.1 => 3.10.2 
    gatsby-plugin-react-helmet: ^3.3.1 => 3.10.0 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-sharp: ^2.6.1 => 2.14.4 
    gatsby-plugin-stylus: ^2.3.1 => 2.10.0 
    gatsby-plugin-twitter: ^2.3.1 => 2.10.0 
    gatsby-remark-autolink-headers: ^2.3.3 => 2.11.0 
    gatsby-remark-classes: ^1.0.0 => 1.0.2 
    gatsby-remark-copy-linked-files: ^2.10.0 => 2.10.0 
    gatsby-remark-images: ^3.11.0 => 3.11.1 
    gatsby-remark-prismjs: ^3.5.1 => 3.13.0 
    gatsby-source-filesystem: ^2.3.1 => 2.11.1 
    gatsby-transformer-remark: ^2.8.7 => 2.16.1 
    gatsby-transformer-sharp: ^2.5.1 => 2.12.1
```

**Comment by drewlustro** [comment]
@phun-ky – could you note which versions worked? I'm dealing with the same issue, but don't know how far I need to downgrade.
