### ISSUE TITLE
Missing onError handler for invocation 'building-schema', error was ' Error: Type with name "GatsbyImageLayout" does not exists'

### ISSUE THREAD

**Issue by aaronbentley** [gatsbyjs/gatsby#33733]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hello Gatsby Community 👋

I'm unable to start Gatsby (develop or build) and am receiving the following error:

```Missing onError handler for invocation 'building-schema', error was 'Error: Type with name "GatsbyImageLayout" does not exists'. Stacktrace was 'Error: Type with name
"GatsbyImageLayout" does not exists

at SchemaComposer.get (/Users/aaron/Apps/nosy/web/node_modules/graphql-compose/lib/TypeStorage.js:44:13)
    at ThunkComposer._thunk (/Users/aaron/Apps/nosy/web/node_modules/graphql-compose/lib/TypeMapper.js:585:34)
    at ThunkComposer.get ofType [as ofType] (/Users/aaron/Apps/nosy/web/node_modules/graphql-compose/lib/ThunkComposer.js:20:34)
    at getTypeNode (/Users/aaron/Apps/nosy/web/node_modules/graphql-compose/lib/utils/definitionNode.js:265:28)
    at /Users/aaron/Apps/nosy/web/node_modules/graphql-compose/lib/utils/definitionNode.js:296:18
    at Array.map (<anonymous>)
    at getArgumentsDefinitionNodes (/Users/aaron/Apps/nosy/web/node_modules/graphql-compose/lib/utils/definitionNode.js:294:19)
    at /Users/aaron/Apps/nosy/web/node_modules/graphql-compose/lib/utils/definitionNode.js:326:18
    at Array.map (<anonymous>)
    at getFieldDefinitionNodes (/Users/aaron/Apps/nosy/web/node_modules/graphql-compose/lib/utils/definitionNode.js:315:21)
    at getObjectTypeDefinitionNode (/Users/aaron/Apps/nosy/web/node_modules/graphql-compose/lib/utils/definitionNode.js:40:13)
    at ObjectTypeComposer.getType (/Users/aaron/Apps/nosy/web/node_modules/graphql-compose/lib/ObjectTypeComposer.js:700:76)
    at getGraphQLType (/Users/aaron/Apps/nosy/web/node_modules/graphql-compose/lib/utils/typeHelpers.js:164:17)
    at /Users/aaron/Apps/nosy/web/node_modules/graphql-compose/lib/SchemaComposer.js:167:79
    at Array.forEach (<anonymous>)
    at SchemaComposer.buildSchema (/Users/aaron/Apps/nosy/web/node_modules/graphql-compose/lib/SchemaComposer.js:166:31)
```

The cli then remains stuck at 'building schema'. As far as I'm aware nothing has changed since I was working on the site yesterday so I'm at a loss to try and diagnose/debug this.

Here's hoping someone can identify what's throwing it out.

### Reproduction Link

https://github.com/Nosy-Marketing/Nosy

### Steps to Reproduce

Try to run gatsby develop.

### Expected Result

I'm expecting the Gatsby cli commands to start up the dev server or build the site.

### Actual Result

The gatsby-cli remains stuck at 'building schema'.

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/Cellar/node@16/16.13.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/Cellar/node@16/16.13.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 95.0.4638.54
    Edge: 95.0.1020.38
    Firefox: 93.0
    Safari: 15.0
  npmPackages:
    gatsby: ^3.14.0 => 3.14.5 
    gatsby-background-image: ^1.5.3 => 1.5.3 
    gatsby-plugin-facebook-pixel: ^1.0.8 => 1.0.8 
    gatsby-plugin-gatsby-cloud: ^3.2.0 => 3.2.1 
    gatsby-plugin-gdpr-cookies: ^2.0.6 => 2.0.8 
    gatsby-plugin-google-analytics: ^3.14.0 => 3.14.0 
    gatsby-plugin-google-tagmanager: ^3.14.0 => 3.14.0 
    gatsby-plugin-hotjar: ^1.1.1 => 1.1.1 
    gatsby-plugin-image: ^1.14.0 => 1.14.1 
    gatsby-plugin-linkedin-insight: ^1.0.1 => 1.0.1 
    gatsby-plugin-manifest: ^3.14.0 => 3.14.0 
    gatsby-plugin-offline: ^4.14.0 => 4.14.0 
    gatsby-plugin-preconnect: ^1.2.1 => 1.2.1 
    gatsby-plugin-react-helmet: ^4.14.0 => 4.14.0 
    gatsby-plugin-react-svg: ^3.0.1 => 3.1.0 
    gatsby-plugin-robots-txt: ^1.6.10 => 1.6.14 
    gatsby-plugin-sanity-image: ^0.8.0 => 0.8.0 
    gatsby-plugin-sitemap: ^4.10.0 => 4.10.0 
    gatsby-plugin-twitter-pixel: ^2.0.2 => 2.0.2 
    gatsby-source-filesystem: ^3.14.0 => 3.14.0 
    gatsby-source-sanity: ^7.0.7 => 7.1.0 
  npmGlobalPackages:
    gatsby-cli: 4.0.0
```

### Config Flags

FAST_DEV: true,
PRESERVE_FILE_DOWNLOAD_CACHE: true,
PARALLEL_SOURCING: true,
LMDB_STORE: true

**Comment by IvayloNikolov** [comment]
How did you fix this issue? Im experiencing the same issue.

**Comment by AaronBentley** [comment]
Hey @IvayloNikolov, If I recall correctly I think  the issue was because I was missing `gatsby-plugin-image` in the `gatsby-config.js` plugins array.

**Comment by AaronBentley** [comment]
Anytime @IvayloNikolov, happy to help 😃
It's worth noting that I don't actually use `gatsby-plugin-image` at all in the site I'm working on, but I still need the type definitions for `GatsbyImageLayout` - I've no idea why though without taking a proper look 🤷‍♂️
