### ISSUE TITLE
Build fails when adding state management (Context) to gatsby-browser (Gatsby v4)

### ISSUE THREAD

**Issue by shalawfatah** [gatsbyjs/gatsby#33845]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I needed to add some state management to my app as it was impossible to do prop drilling, so I added some code to the gatsby-browser, at first it was just this: 

```
import React from "react"
import {SearchProvider} from "./src/store/SearchProvider"
export const wrapPageElement = ({ element }) => {
  return <SearchProvider>{element}</SearchProvider>
}
```
However, since then, I get this error which does not explain anything, and it does not even provide any explanation when checked with `` --verbose ``, I wonder why ?
Please know the attached gitlab is not the original project, it was just put there for explanation. The error reads like this:
 
```
success run queries in workers - 60.732s - 16/16 0.26/s
⠋ Merge worker state
/usr/local/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: write EPIPE
    at ChildProcess.target._send (node:internal/child_process:849:20)
    at ChildProcess.target.send (node:internal/child_process:722:19)
    at WorkerPool.sendMessage (/Users/skarim/Desktop/guidedby-react/node_modules/gatsby-worker/dist/index.js:290:19)
    at /Users/skarim/Desktop/guidedby-react/node_modules/gatsby/src/utils/jobs/worker-messaging.ts:22:22
Emitted 'error' event on ChildProcess instance at:
    at node:internal/child_process:853:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
skarim@CABCVAN7BPR008 guidedby-react % 
```

### Reproduction Link

https://gitlab.com/somegroup18/learn-gitlab-ultimate-trial.git

### Steps to Reproduce

1. git clone https://gitlab.com/somegroup18/learn-gitlab-ultimate-trial.git
2. unzip src folder
3. You should have a Wordpress backend as a CMS, connected to your plugin in gatsby-config.
4. run npm install
5. run gatsby build

### Expected Result

1. The build should go smoothly and without any bug or error. 

### Actual Result

The build fails all the time. It starts and ends like this:

```
success initialize cache - 8.252s
success copy gatsby files - 0.405s
success Compiling Gatsby Functions - 0.682s
success onPreBootstrap - 0.705s
success  gatsby-source-wordpress  ensuring plugin requirements are met - 1.938s
⠀
info  gatsby-source-wordpress 

        This is either your first build or the cache was cleared.
        Please wait while your WordPress data is synced to your Gatsby cache.

        Maybe now's a good time to get up and stretch? :D

success  gatsby-source-wordpress  ingest WPGraphQL schema - 2.786s
success createSchemaCustomization - 4.825s
success  gatsby-source-wordpress  fetch root fields - 0.898s
success  gatsby-source-wordpress  Category - 0.937s - fetched 1
success  gatsby-source-wordpress  Comment - 1.625s - fetched 0
success  gatsby-source-wordpress  ContentType - 2.129s - fetched 5
success  gatsby-source-wordpress  Faqcategory - 2.190s - fetched 0
success  gatsby-source-wordpress  Businesses - 197.422s - fetched 2058
success  gatsby-source-wordpress  Menu - 0.921s - fetched 2
success  gatsby-source-wordpress  Faq - 1.438s - fetched 1
success  gatsby-source-wordpress  MenuItem - 1.501s - fetched 10
success  gatsby-source-wordpress  Locations - 5.178s - fetched 37
success  gatsby-source-wordpress  PostFormat - 0.867s - fetched 0
success  gatsby-source-wordpress  Page - 1.131s - fetched 9
success  gatsby-source-wordpress  Promotags - 1.529s - fetched 0
success  gatsby-source-wordpress  Publications - 4.845s - fetched 21
success  gatsby-source-wordpress  Post - 28.730s - fetched 298
success  gatsby-source-wordpress  Tag - 1.000s - fetched 0
success  gatsby-source-wordpress  Taxonomy - 1.616s - fetched 11
success  gatsby-source-wordpress  Sponsors - 2.388s - fetched 5
warn  gatsby-source-wordpress  Found a duplicate ID in WordPress - this means you will have fewer
nodes in Gatsby than in WordPress. This will need to be resolved in WP by identifying and fixing the
underlying bug with your WP plugins or custom code.
info  gatsby-source-wordpress  #675 (/topics/architects-builders-engineers/) is a duplicate of 675
(/topics/architects-builders-engineers/)
success  gatsby-source-wordpress  Spotlights - 4.590s - fetched 32
success  gatsby-source-wordpress  Topics - 39.135s - fetched 495
success  gatsby-source-wordpress  UserRole - 1.346s - fetched 0
success  gatsby-source-wordpress  Visibility - 1.646s - fetched 2
success  gatsby-source-wordpress  User - 3.232s - fetched 39
 gatsby-source-wordpress  Fetching /wp-content/uploads/2021/01/RedDoorBistro-archive-img.jpg is taking
 a long time time (longer than 15 seconds). This file is 34.9 KB
success  gatsby-source-wordpress  MediaItem - 518.295s - fetched 5947
success  gatsby-source-wordpress  creating nodes - 518.305s
success  gatsby-source-wordpress  fetching nodes - 792.028s - 8973 total
success Downloading remote files - 515.121s - 5939/5939 11.53/s
success Checking for changed pages - 0.001s
success source and transform nodes - 792.889s
info Writing GraphQL type definitions to /Users/skarim/Desktop/guidedby-react/.cache/schema.gql
success building schema - 2.145s
success createPages - 0.001s
success createPagesStatefully - 0.117s
info Total nodes: 20786, SitePage nodes: 10 (use --verbose for breakdown)
success Checking for changed pages - 0.000s
success Cleaning up stale page-data - 0.012s
success onPreExtractQueries - 0.001s
success  gatsby-source-wordpress  diff schemas - 2.038s
success  gatsby-source-wordpress  ingest WPGraphQL schema - 2.168s
success extract queries from components - 3.397s
success write out redirect data - 0.007s
success Build manifest and related icons - 0.126s
success onPostBootstrap - 0.144s
info bootstrap finished - 829.194s
success write out requires - 0.013s
warn ./node_modules/gatsby-source-wordpress/dist/gatsby-browser.js
Attempted import error: 'createRoot' is not exported from 'react-dom' (imported as 'ReactDOM').
warn ./node_modules/gatsby-source-wordpress/dist/gatsby-browser.js
Attempted import error: 'createRoot' is not exported from 'react-dom' (imported as 'ReactDOM').
success Building production JavaScript and CSS bundles - 3.643s
success Building HTML renderer - 2.735s
success Caching Webpack compilations - 0.001s
warn Query takes too long:
File path: /Users/skarim/Desktop/guidedby-react/src/components/map/GridView.tsx
warn Query takes too long:
File path: /Users/skarim/Desktop/guidedby-react/src/components/map/Map.tsx
warn Query takes too long:
File path: /Users/skarim/Desktop/guidedby-react/src/components/sections/BusinessSection.tsx
success run queries in workers - 60.732s - 16/16 0.26/s
⠋ Merge worker state
/usr/local/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: write EPIPE
    at ChildProcess.target._send (node:internal/child_process:849:20)
    at ChildProcess.target.send (node:internal/child_process:722:19)
    at WorkerPool.sendMessage (/Users/skarim/Desktop/guidedby-react/node_modules/gatsby-worker/dist/index.js:290:19)
    at /Users/skarim/Desktop/guidedby-react/node_modules/gatsby/src/utils/jobs/worker-messaging.ts:22:22
Emitted 'error' event on ChildProcess instance at:
    at node:internal/child_process:853:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
skarim@CABCVAN7BPR008 guidedby-react % 
```

### Environment

```shell
System:
   OS: macOS Big Sur
   CPU: 2.6 GHz 6-Core Intel Core i7
Binaries: 
   Node: v16.6.1
   NPM: 7.20.3
Languages:
   Javascript: ES2015
Browsers:
   Chrome: Version 95.0.4638.54
npmPackages:
   gatsby: 4.0
```

**Comment by LekoArts** [comment]
Closing in favour of https://github.com/gatsbyjs/gatsby/discussions/33847
