### ISSUE TITLE
After running gatsby develop, I receive an error: 'YAMLException...'

### ISSUE THREAD

**Issue by edouerd** [gatsbyjs/gatsby#339]
Hi there!

After running `gatsby develop`, I received the following error, one I haven't run into:

```
/Users/edouard/Sites/edouard/projects/edouard/node_modules/js-yaml/lib/js-yaml/loader.js:168
  throw generateError(state, message);
  ^
YAMLException: incomplete explicit mapping pair; a key node is missed at line 2, column 335:
     ... mposing interface. Spoiler alert: The product ended up failing.  ...
                                         ^
  at generateError (/Users/edouard/Sites/edouard/projects/edouard/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
  at throwError (/Users/edouard/Sites/edouard/projects/edouard/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
  at readBlockMapping (/Users/edouard/Sites/edouard/projects/edouard/node_modules/js-yaml/lib/js-yaml/loader.js:994:9)
  at composeNode (/Users/edouard/Sites/edouard/projects/edouard/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
  at readDocument (/Users/edouard/Sites/edouard/projects/edouard/node_modules/js-yaml/lib/js-yaml/loader.js:1488:3)
  at loadDocuments (/Users/edouard/Sites/edouard/projects/edouard/node_modules/js-yaml/lib/js-yaml/loader.js:1544:5)
  at Object.load (/Users/edouard/Sites/edouard/projects/edouard/node_modules/js-yaml/lib/js-yaml/loader.js:1561:19)
  at parse (/Users/edouard/Sites/edouard/projects/edouard/node_modules/front-matter/index.js:40:27)
  at extractor (/Users/edouard/Sites/edouard/projects/edouard/node_modules/front-matter/index.js:23:12)
  at loadFrontmatter (/Users/edouard/Sites/edouard/projects/edouard/node_modules/gatsby/dist/utils/build-page/load-frontmatter.js:40:45)
  at buildPage (/Users/edouard/Sites/edouard/projects/edouard/node_modules/gatsby/dist/utils/build-page/index.js:27:48)
  at /Users/edouard/Sites/edouard/projects/edouard/node_modules/gatsby/dist/utils/glob-pages.js:36:46
  at Array.forEach (native)
  at /Users/edouard/Sites/edouard/projects/edouard/node_modules/gatsby/dist/utils/glob-pages.js:35:11
  at f (/Users/edouard/Sites/edouard/projects/edouard/node_modules/once/once.js:17:25)
  at Glob.<anonymous> (/Users/edouard/Sites/edouard/projects/edouard/node_modules/glob/glob.js:146:7)
  at emitOne (events.js:96:13)
  at Glob.emit (events.js:188:7)
  at Glob._finish (/Users/edouard/Sites/edouard/projects/edouard/node_modules/glob/glob.js:194:8)
  at done (/Users/edouard/Sites/edouard/projects/edouard/node_modules/glob/glob.js:179:14)
  at Glob._processGlobStar2 (/Users/edouard/Sites/edouard/projects/edouard/node_modules/glob/glob.js:631:12)
  at /Users/edouard/Sites/edouard/projects/edouard/node_modules/glob/glob.js:620:10
  at RES (/Users/edouard/Sites/edouard/projects/edouard/node_modules/inflight/inflight.js:23:14)
  at f (/Users/edouard/Sites/edouard/projects/edouard/node_modules/once/once.js:17:25)
  at lstatcb_ (/Users/edouard/Sites/edouard/projects/edouard/node_modules/glob/glob.js:513:7)
  at RES (/Users/edouard/Sites/edouard/projects/edouard/node_modules/inflight/inflight.js:23:14)
  at f (/Users/edouard/Sites/edouard/projects/edouard/node_modules/once/once.js:17:25)
  at FSReqWrap.oncomplete (fs.js:117:15)
```

I'm not sure why this is happening, I didn't edit or change up any files to prompt the error.

Thanks!

**Comment by KyleAMathews** [comment]
This looks like a YAML error. You'll want to look closely at the "frontmatter" in your markdown files (which needs to be proper YAML) for what's wrong. From this page, it might be that one of your yaml strings has a colon in it: https://hexo.io/docs/troubleshooting.html
