### ISSUE TITLE
How to debug Error: write EPIPE during build for a 1000+ pages site

### ISSUE THREAD

**Issue by gvocale** [gatsbyjs/gatsby#34033]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

During `yarn build`, the following `Error: write EPIPE` happens. What does this error mean? How can I debug it?

My site has around 1100 pages.

Thanks

### Reproduction Link

https://github.com/

### Steps to Reproduce

1. `yarn develop`
2. Wait wait wait...
3. Error happens Error: write EPIPE
...

### Expected Result

Build to work

### Actual Result

```tsx
success run queries in workers - 84.981s - 1613/1613 18.98/s
⠋ Merge worker state
/site/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: write EPIPE
    at ChildProcess.target._send (node:internal/child_process:849:20)
    at ChildProcess.target.send (node:internal/child_process:722:19)
    at WorkerPool.sendMessage (/site/node_modules/gatsby-worker/dist/index.js:290:19)
    at /site/node_modules/gatsby/src/utils/jobs/worker-messaging.ts:22:22
Emitted 'error' event on ChildProcess instance at:
    at node:internal/child_process:853:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
error Command failed with exit code 7.
```

### Environment

```shell
System:
    OS: macOS 12.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.6.0 - /var/folders/k0/zk60y_zj5v518rw_4hp4k0840000gn/T/yarn--1637333410517-0.2146436190636809/node
    Yarn: 1.22.11 - /var/folders/k0/zk60y_zj5v518rw_4hp4k0840000gn/T/yarn--1637333410517-0.2146436190636809/yarn
    npm: 7.19.1 - ~/.nvm/versions/node/v16.6.0/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    gatsby: ^4.1.4 => 4.1.6
    gatsby-plugin-disqus: ^1.2.3 => 1.2.3
    gatsby-plugin-google-analytics: ^4.1.0 => 4.1.0
    gatsby-plugin-image: ^2.1.2 => 2.1.3
    gatsby-plugin-manifest: ^4.1.3 => 4.1.4
    gatsby-plugin-react-helmet: ^5.1.0 => 5.1.0
    gatsby-plugin-sass: ^5.1.1 => 5.1.1
    gatsby-plugin-sharp: ^4.1.3 => 4.1.4
    gatsby-plugin-sitemap: ^5.1.1 => 5.1.1
    gatsby-plugin-theme-ui: ^0.12.0 => 0.12.0
    gatsby-plugin-typescript: ^4.1.2 => 4.1.3
    gatsby-source-filesystem: ^4.1.2 => 4.1.3
    gatsby-transformer-json: ^4.1.0 => 4.1.0
    gatsby-transformer-remark: ^5.1.3 => 5.1.4
    gatsby-transformer-sharp: ^4.1.0 => 4.1.0


✨  Done in 2.27s.
```

**Comment by KyleAMathews** [comment]
Generally this means a worker process was killed by your OS as the machine was running out of memory. `Error: write EPIPE` means the parent Gatsby processed was unable to write to the child anymore.

**Comment by gvocale** [comment]
Thank you, very helpful! I will try to run my build process with:
```
"build": "export NODE_OPTIONS=--max_old_space_size=8192 && gatsby build",
```
And see if it helps
