### ISSUE TITLE
gatsbygram scrape broken by new instagram url encoding?

### ISSUE THREAD

**Issue by eghan** [gatsbyjs/gatsby#3442]
It appears the new instagram url encoding broke scrape.js

I rewrote the post parser section of scrape.js, however instagram is also now limiting to top 12 posts, good enough?

branch me and I'll push it over for review?

**Comment by fk** [comment]
Hi @eghan! 👋 
I believe @daaain was working on the same in #3349, maybe you guys want to join efforts?

**Comment by graysonhicks** [comment]
Not sure about the 'top 12 posts' aspect, but the Instagram API is still an ongoing issue.  I tried `scrape.js` this morning and getting the following error:

```undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request.request [as _callback] (/Users/ghicks/Documents/Exploration/graysonhicks.com/gatsby/src/utils/instascrape.js:54:19)
    at Request.self.callback (/Users/ghicks/Documents/Exploration/graysonhicks.com/gatsby/node_modules/request/request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/Users/ghicks/Documents/Exploration/graysonhicks.com/gatsby/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/Users/ghicks/Documents/Exploration/graysonhicks.com/gatsby/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
```


This is from a fresh clone and install of gatsbygram.  Also tried several Instagram usernames, a mix of public and private.  Could be tied to what looks like Instagram rapidly altering this API, per the comments going on in this StackOverflow post: 

https://stackoverflow.com/questions/49265339/instagram-a-1-url-doesnt-allow-max-id

I see several PRs that seem to have address Instagram API changes recently (#3349, #4777, and #4534).

**Comment by AnalogMemory** [comment]
@graysonhicks I'm not sure if it was just a hiccup but this url to access a users graphql feed wasn't working earlier today `https://www.instagram.com/${username}/?__a=1`

But now it's working again. 🤷‍♀️ 

Who know for how long though

**Comment by congomonster** [comment]
And i thought it was aconfiguration problem. I have the same problem. Didn't work for me.

**Comment by daaain** [comment]
I finally got around to look into this issue (again) and it seems that there's no unauthenticated API any more, at the very least you need to reuse cookie data which is a no go for open source.

However there's some baked in JSON data based on the GraphQL API in the HTML page of a user's profile, so it's possible to parse the data without much fuss and have the first 9 photos (see code example at the bottom).

I'm happy to submit a PR to implement this and have scraping working at least for the first 9 photos if that would be considered enough improvement over the current (broken) situation.

```
let url = "https://www.instagram.com/"+username;
$.ajax({
    type: 'GET',
    url: url,
    error: function () {
        //..
    },
    success: function (data) {
        data = JSON.parse(data.split("window._sharedData = ")[1].split(";</script>")[0]).entry_data.ProfilePage[0].graphql;
        console.log(data);
    }
})
```

From: https://stackoverflow.com/a/49812302/21217

**Comment by tulsileathers** [comment]
@daaain It seems like that's the best we're going to get without using the authenticated api, which only works for business accounts 🙁

**Comment by AnalogMemory** [comment]
I've been using https://www.instapi.io/ to get the normal public feed data.

**Comment by kakadiadarpan** [comment]
@fk can we close this issue if it has been fixed?

**Comment by fk** [comment]
@kakadiadarpan Just tried `node scrape.js kyle__mathews`, and as the previous commenters reported, scraping seems (again/still) broken. 😿
