### ISSUE TITLE
Gatsby Develop > ERROR #98123  WEBPACK

### ISSUE THREAD

**Issue by benackles** [gatsbyjs/gatsby#35607]
### Preliminary Checks
Please make sure that you verify each checkbox and follow the instructions for them.

- [x]  This issue is not a duplicate. Before opening a new issue, please search existing issues: [https://github.com/gatsbyjs/gatsby/issue](https://github.com/gatsbyjs/gatsby/issues) *

- [x]  This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: [https://github.com/gatsbyjs/gatsby/discussions](https://github.com/gatsbyjs/gatsby/discussions) *

### Description

I have a new laptop and I am setting up my environment following the [Gatsby tutorial.](https://www.gatsbyjs.com/docs/tutorial/part-1/). I am running into issues when I get to the step to "[Run your site locally](https://www.gatsbyjs.com/docs/tutorial/part-1/)" specifically with the `gatsby develop` command. I get a webpack error on two files. 

I have not made it to the step to make my first commit to my GitHub repo, so the repo linked is the new repo without my initial commit (not a Gatsby site).

### Reproduction Link

https://github.com/benackles/whatsgatsby

### Steps to Reproduce

1. Run `gatsby develop`
2.  Get two `ERROR #98123 WEBPACK` errors

### Expected Result

Successfully fire up locally

```
Copycopy code to clipboard
You can now view whatsgatsby in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and
schema
⠀
  http://localhost:8000/___graphql
```

### Actual Result

 ```
ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({
'lib/mappings.wasm': ... }) before using SourceMapConsumer

File: .cache/app.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({
'lib/mappings.wasm': ... }) before using SourceMapConsumer

File: .cache/polyfill-entry.js

failed Building development bundle - 3.925s
ERROR in ./.cache/app.js
Module build failed (from 
./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js):
Error: You must provide the URL of lib/mappings.wasm by calling 
SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm
(/Users/benjamins/Sites/whatsgatsby/node_modules/source-map/lib/read-wasm.js:8:13)
    at wasm (/Users/benjamins/Sites/whatsgatsby/node_modules/source-map/lib/wasm.js:25:16)
    at /Users/benjamins/Sites/whatsgatsby/node_modules/source-map/lib/source-map-consumer.
js:264:14
    at Object._loader (/Users/benjamins/Sites/whatsgatsby/node_modules/@pmmmwh/react-refre
sh-webpack-plugin/loader/index.js:81:9)

ERROR in ./.cache/polyfill-entry.js
Module build failed (from 
./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js):
Error: You must provide the URL of lib/mappings.wasm by calling 
SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm
(/Users/benjamins/Sites/whatsgatsby/node_modules/source-map/lib/read-wasm.js:8:13)
    at wasm (/Users/benjamins/Sites/whatsgatsby/node_modules/source-map/lib/wasm.js:25:16)
    at /Users/benjamins/Sites/whatsgatsby/node_modules/source-map/lib/source-map-consumer.
js:264:14
    at Object._loader (/Users/benjamins/Sites/whatsgatsby/node_modules/@pmmmwh/react-refre
sh-webpack-plugin/loader/index.js:81:9)

develop compiled with 2 errors
```

### Environment

```shell
System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /opt/homebrew/bin/node
    npm: 8.9.0 - /opt/homebrew/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 101.0.4951.54
    Safari: 15.3
  npmPackages:
    gatsby: ^4.13.1 => 4.13.1
    gatsby-plugin-gatsby-cloud: ^4.13.0 => 4.13.0
    gatsby-plugin-image: ^2.13.0 => 2.13.0
    gatsby-plugin-manifest: ^4.13.0 => 4.13.0
    gatsby-plugin-offline: ^5.13.0 => 5.13.0
    gatsby-plugin-react-helmet: ^5.13.0 => 5.13.0
    gatsby-plugin-sharp: ^4.13.0 => 4.13.0
    gatsby-source-filesystem: ^4.13.0 => 4.13.0
    gatsby-transformer-sharp: ^4.13.0 => 4.13.0
  npmGlobalPackages:
    gatsby-cli: 4.13.0
```

**Comment by gvorbeck** [comment]
Been having a very similar error happen any time I make a syntax error like forgetting quotes around a string or missing a required prop on a component. Completely crashes my development server so I'm having to restart it frequently and troubleshooting becomes very difficult and time consuming. I don't understand it and google has not helped.

`You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({
'lib/mappings.wasm': ... }) before using SourceMapConsumer`

**Comment by LekoArts** [comment]
Can you try using Node.js v16? I'm pretty sure it's this issue: https://github.com/mozilla/source-map/issues/454

We'll need to see what we do with this upstream dependency

**Comment by benackles** [comment]
@LekoArts That did resolve it. New Macs ship with Node.js v18

**Comment by yihuajack** [comment]
Moving back to node.js 16 may not be a final solution, see https://github.com/gatsbyjs/gatsby/pull/13713 and https://github.com/nodejs/node/issues/42638.

**Comment by LekoArts** [comment]
We'll try to migrate away so that it works also on Node 18

**Comment by bre7** [comment]
"Same" as https://github.com/parcel-bundler/parcel/issues/8005

Try forcing `"source-map": "^0.8.0-beta.0"`

**Comment by TheOtterlord** [comment]
> Try forcing resolution "source-map": "^0.8.0-beta.0"

This works for the time being on the latest version of Node.js
Thanks

**Comment by antoinetielbeke** [comment]
I use node.js v18.0.0, set my `package.json` to:
```
  "resolutions": {
    "source-map": "^0.8.0-beta.0"
  },
```
deleted the `node_modules` folder and `package-lock.json`, ran `npm install` again but I still end up with this error.

Anyone suggestions?

**Comment by TheOtterlord** [comment]
maybe placing it as a dependency?

**Comment by antoinetielbeke** [comment]
@TheOtterlord That worked! Thank you.

I added it as a depedency in my `package.json` file:
```
  "resolutions": {
    "source-map": "^0.8.0-beta.0"
  },
  "dependencies": {
    "source-map": "^0.8.0-beta.0",
    ...
```

**Comment by gvorbeck** [comment]
if I'm using yarn workspaces to build a theme as described in this [Gatsby guide](https://www.gatsbyjs.com/tutorial/building-a-theme/) and I'm running into this error, which `package.json` file should I put this source-map in? The root, the site or the theme?

**Comment by TheOtterlord** [comment]
Probably root because it should effect all workspaces. I'm not too familiar with dependency resolution for workspaces though, so they might work differently.

**Comment by LekoArts** [comment]
Please try using `gatsby@next` (e.g. via `npm install gatsby@next`)

**Comment by OliverHuntsman** [comment]
This fixed everything:

Stop server (ctrl+C)
Run gatsby clean
Delete node_modules folder
Delete package-lock.json file
Install Yarn if it isn't installed already (npm install -g yarn)
Run yarn install (yarn install)
Restart your server and test (gatsby develop)
Credit goes to [Ferran](https://stackoverflow.com/questions/65970921/error-98123-webpack-generating-development-javascript-bundle-failed-on-gatsby/65971584#65971584).

**Comment by AKlaus** [comment]
> Same as [parcel-bundler/parcel#8005](https://github.com/parcel-bundler/parcel/issues/8005) ?
> 
> Try forcing resolution `"source-map": "^0.8.0-beta.0"`

That worked! 👍 
Open `package-lock.json` and find `"source-map"` under `"node_modules/gatsby" --> "dependencies"` and update the version.
