### ISSUE TITLE
Inner exception message : "The OAuth2 token is invalid."

### ISSUE THREAD

**Issue by sebhewelt** [gatsbyjs/gatsby#3571]
## Description

Pulling posts from wordpress doesn't work on netlify, but works fine locally.

### Environment

Gatsby version: 1.9.92
Node.js version: 8.5.0

### Actual result

Netlify build log:

```
11:02:21 PM: Build ready to start
11:02:23 PM: Fetching cached dependencies
11:02:23 PM: Failed to fetch cache, continuing with build
11:02:23 PM: Starting to prepare the repo for build
11:02:24 PM: No cached dependencies found. Cloning fresh repo
11:02:24 PM: git clone git@github.com:sebhewelt/sebhewelt-gatsby
11:02:25 PM: Preparing Git Reference refs/heads/master
11:02:25 PM: Running build command: gatsby build --prefix-paths
11:02:25 PM: Installing dependencies
11:02:26 PM: Using node version 'v8.5.0' from .nvmrc
11:02:26 PM: Downloading and installing node v8.5.0...
11:02:27 PM: Downloading https://nodejs.org/dist/v8.5.0/node-v8.5.0-linux-x64.tar.xz...
11:02:27 PM: 
#
11:02:27 PM:                                                            2.5%
11:02:27 PM: #
11:02:27 PM: #####                                                                     9.1%
11:02:27 PM: #
11:02:27 PM: ##########                                                               16.6%
11:02:27 PM: #
11:02:27 PM: ################                                                         24.5%
11:02:27 PM: 
################
11:02:27 PM: #######                                                   32.6%
11:02:27 PM: #
11:02:27 PM: ############################                                             40.8%
11:02:28 PM: #
11:02:28 PM: #################################                                        48.5%
11:02:28 PM: #
11:02:28 PM: #######################################                                  56.4%
11:02:28 PM: #
11:02:28 PM: #############################################                            64.4%
11:02:28 PM: #
11:02:28 PM: ###################################################                      72.7%
11:02:28 PM: #
11:02:28 PM: #########################################################                80.6%
11:02:28 PM: #
11:02:28 PM: ##############################################################           88.3%
11:02:28 PM: 
###################
11:02:28 PM: #################################################      95.7%
11:02:28 PM: 
##################
11:02:28 PM: ###################################################### 100.0%
11:02:28 PM: Computing checksum with sha256sum
11:02:28 PM: Checksums matched!
11:02:31 PM: Now using node v8.5.0 (npm v5.3.0)
11:02:31 PM: Using version v8.5.0 of node
11:02:31 PM: Using /opt/buildhome/.rvm/gems/ruby-2.1.2
11:02:32 PM: Installing NPM modules using NPM version 5.3.0
11:02:34 PM: npm
11:02:34 PM: WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
11:03:19 PM: > uws@0.14.5 install /opt/build/repo/node_modules/uws
11:03:19 PM: > node-gyp rebuild > build_log.txt 2>&1 || exit 0
11:03:30 PM: > node-sass@4.7.2 install /opt/build/repo/node_modules/node-sass
11:03:31 PM: > node scripts/install.js
11:03:31 PM: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/linux-x64-57_binding.node
11:03:38 PM: Download complete
11:03:38 PM: Binary saved to /opt/build/repo/node_modules/node-sass/vendor/linux-x64-57/binding.node
11:03:38 PM: Caching binary to /opt/buildhome/.npm/node-sass/4.7.2/linux-x64-57_binding.node
11:03:39 PM: > node-sass@4.7.2 postinstall /opt/build/repo/node_modules/node-sass
11:03:39 PM: > node scripts/build.js
11:03:39 PM: Binary found at /opt/build/repo/node_modules/node-sass/vendor/linux-x64-57/binding.node
11:03:39 PM: Testing binary
11:03:39 PM: Binary is fine
11:03:42 PM: npm
11:03:42 PM: notice created a lockfile as package-lock.json. You should commit this file.
11:03:42 PM: npm WARN eslint-plugin-import@2.8.0 requires a peer of eslint@2.x - 4.x but none was installed.
11:03:42 PM: npm WARN eslint-plugin-jsx-a11y@5.1.1 requires a peer of eslint@^2.10.2 || ^3 || ^4 but none was installed.
11:03:42 PM: npm WARN eslint-plugin-react@7.5.1 requires a peer of eslint@^3.0.0 || ^4.0.0 but none was installed.
11:03:42 PM: npm WARN gatsby-starter-default@1.0.0 No repository field.
11:03:42 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
11:03:42 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
11:03:42 PM: added 1762 packages in 69.626s
11:03:42 PM: NPM modules installed
11:03:43 PM: Installing missing commands
11:03:43 PM: Executing user command: gatsby build --prefix-paths
11:03:44 PM: success delete html files from previous builds — 0.010 s
11:03:44 PM: success open and validate gatsby-config.js — 0.005 s
11:03:45 PM: success copy gatsby files — 0.020 s
11:03:45 PM: success onPreBootstrap — 0.005 s
11:03:45 PM: Starting to fetch data from Contentful
11:03:45 PM: Fetching default locale
11:03:45 PM: default local is : en-US
11:03:45 PM: contentTypes fetched 3
11:03:45 PM: Updated entries  6
11:03:45 PM: Deleted entries  0
11:03:45 PM: Updated assets  6
11:03:45 PM: Deleted assets  0
11:03:45 PM: Fetch Contentful data: 685.099ms
11:03:46 PM: The server response was "400 Bad Request"
11:03:46 PM: The server response was "401 Unauthorized"
11:03:46 PM: Inner exception message : "The OAuth2 token is invalid."
11:03:46 PM: The server response was "401 Unauthorized"
11:03:46 PM: Inner exception message : "The OAuth2 token is invalid."
11:03:46 PM: The server response was "401 Unauthorized"
11:03:46 PM: Inner exception message : "The OAuth2 token is invalid."
11:03:47 PM: The server response was "401 Unauthorized"
11:03:47 PM: Inner exception message : "The OAuth2 token is invalid."
11:03:47 PM: The server response was "401 Unauthorized"
11:03:47 PM: Inner exception message : "The OAuth2 token is invalid."
11:03:47 PM: The server response was "401 Unauthorized"
11:03:47 PM: Inner exception message : "The OAuth2 token is invalid."
11:03:47 PM: The server response was "401 Unauthorized"
11:03:47 PM: Inner exception message : "The OAuth2 token is invalid."
11:03:47 PM: The server response was "401 Unauthorized"
11:03:47 PM: Inner exception message : "The OAuth2 token is invalid."
11:03:47 PM: The server response was "401 Unauthorized"
11:03:47 PM: Inner exception message : "The OAuth2 token is invalid."
11:03:47 PM: The server response was "401 Unauthorized"
11:03:47 PM: Inner exception message : "The OAuth2 token is invalid."
11:03:47 PM: The server response was "401 Unauthorized"
11:03:47 PM: Inner exception message : "The OAuth2 token is invalid."
11:03:47 PM: The server response was "401 Unauthorized"
11:03:47 PM: Inner exception message : "The OAuth2 token is invalid."
11:03:48 PM: The server response was "401 Unauthorized"
11:03:48 PM: Inner exception message : "The OAuth2 token is invalid."
11:03:48 PM: The server response was "401 Unauthorized"
11:03:48 PM: Inner exception message : "The OAuth2 token is invalid."
11:03:48 PM: The server response was "401 Unauthorized"
11:03:48 PM: Inner exception message : "The OAuth2 token is invalid."
11:03:48 PM: The server response was "404 Not Found"
11:03:48 PM: Inner exception message : "No route was found matching the URL and request method"
11:03:48 PM: warning The gatsby-source-wordpress plugin has generated no Gatsby nodes. Do you need it?
11:03:48 PM: success source and transform nodes — 3.319 s
11:03:48 PM: success building schema — 0.251 s
11:03:48 PM: success createLayouts — 0.024 s
11:03:48 PM: [ { GraphQLError: Cannot query field "allWordpressPost" on type "RootQueryType".
11:03:48 PM:       at Object.Field (/opt/build/repo/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:65:31)
11:03:48 PM:       at Object.enter (/opt/build/repo/node_modules/graphql/language/visitor.js:295:29)
11:03:48 PM:       at Object.enter (/opt/build/repo/node_modules/graphql/language/visitor.js:337:25)
11:03:48 PM:       at visit (/opt/build/repo/node_modules/graphql/language/visitor.js:227:26)
11:03:48 PM:       at visitUsingRules (/opt/build/repo/node_modules/graphql/validation/validate.js:75:22)
11:03:48 PM:       at validate (/opt/build/repo/node_modules/graphql/validation/validate.js:60:10)
11:03:48 PM:       at /opt/build/repo/node_modules/graphql/graphql.js:69:51
11:03:48 PM:       at Promise._execute (/opt/build/repo/node_modules/bluebird/js/release/debuggability.js:303:9)
11:03:48 PM:       at Promise._resolveFromExecutor (/opt/build/repo/node_modules/bluebird/js/release/promise.js:483:18)
11:03:48 PM:       at new Promise (/opt/build/repo/node_modules/bluebird/js/release/promise.js:79:10)
11:03:48 PM:       at graphqlImpl (/opt/build/repo/node_modules/graphql/graphql.js:59:10)
11:03:48 PM:       at graphql (/opt/build/repo/node_modules/graphql/graphql.js:48:227)
11:03:48 PM:       at graphqlRunner (/opt/build/repo/node_modules/gatsby/dist/bootstrap/index.js:368:22)
11:03:48 PM:       at Promise (/opt/build/repo/gatsby-node.js:10:5)
11:03:49 PM:       at Promise._execute (/opt/build/repo/node_modules/bluebird/js/release/debuggability.js:303:9)
11:03:49 PM:       at Promise._resolveFromExecutor (/opt/build/repo/node_modules/bluebird/js/release/promise.js:483:18)
11:03:49 PM:     message: 'Cannot query field "allWordpressPost" on type "RootQueryType".',
11:03:49 PM:     locations: [ [Object] ],
11:03:49 PM:     path: undefined } ]
11:03:49 PM: error gatsby-node.js returned an error
11:03:49 PM: 
11:03:49 PM:   Error: 
11:03:49 PM: 
11:03:49 PM: success createPages — 0.034 s
11:03:49 PM: error Cannot read property 'allWordpressPost' of undefined
11:03:49 PM: 
11:03:49 PM:   TypeError: Cannot read property 'allWordpressPost' of undefined
11:03:49 PM:   
11:03:49 PM:   - gatsby-node.js:30 graphql.then.result
11:03:49 PM:     /opt/build/repo/gatsby-node.js:30:25
11:03:49 PM:   
11:03:49 PM:   - util.js:16 tryCatcher
11:03:49 PM:     [repo]/[bluebird]/js/release/util.js:16:23
11:03:49 PM:   
11:03:49 PM:   - promise.js:512 Promise._settlePromiseFromHandler
11:03:49 PM:     [repo]/[bluebird]/js/release/promise.js:512:31
11:03:49 PM:   
11:03:49 PM:   - promise.js:569 Promise._settlePromise
11:03:49 PM:     [repo]/[bluebird]/js/release/promise.js:569:18
11:03:49 PM:   
11:03:49 PM:   - promise.js:606 Promise._settlePromiseCtx
11:03:49 PM:     [repo]/[bluebird]/js/release/promise.js:606:10
11:03:49 PM:   
11:03:49 PM:   - async.js:138 Async._drainQueue
11:03:49 PM:     [repo]/[bluebird]/js/release/async.js:138:12
11:03:49 PM:   
11:03:49 PM:   - async.js:143 Async._drainQueues
11:03:49 PM:     [repo]/[bluebird]/js/release/async.js:143:10
11:03:49 PM:   
11:03:49 PM:   - async.js:17 Immediate.Async.drainQueues
11:03:49 PM:     [repo]/[bluebird]/js/release/async.js:17:14
11:03:49 PM:   
11:03:49 PM: 
11:03:49 PM: error UNHANDLED REJECTION
11:03:49 PM: 
11:03:49 PM:   TypeError: Cannot read property 'allWordpressPost' of undefined
11:03:49 PM:   
11:03:49 PM:   - gatsby-node.js:30 graphql.then.result
11:03:49 PM:     /opt/build/repo/gatsby-node.js:30:25
11:03:49 PM:   
11:03:49 PM:   - util.js:16 tryCatcher
11:03:49 PM:     [repo]/[bluebird]/js/release/util.js:16:23
11:03:49 PM:   
11:03:49 PM:   - promise.js:512 Promise._settlePromiseFromHandler
11:03:49 PM:     [repo]/[bluebird]/js/release/promise.js:512:31
11:03:49 PM:   
11:03:49 PM:   - promise.js:569 Promise._settlePromise
11:03:49 PM:     [repo]/[bluebird]/js/release/promise.js:569:18
11:03:49 PM:   
11:03:49 PM:   - promise.js:606 Promise._settlePromiseCtx
11:03:49 PM:     [repo]/[bluebird]/js/release/promise.js:606:10
11:03:49 PM:   
11:03:49 PM:   - async.js:138 Async._drainQueue
11:03:49 PM:     [repo]/[bluebird]/js/release/async.js:138:12
11:03:49 PM:   
11:03:49 PM:   - async.js:143 Async._drainQueues
11:03:49 PM:     [repo]/[bluebird]/js/release/async.js:143:10
11:03:49 PM:   
11:03:49 PM:   - async.js:17 Immediate.Async.drainQueues
11:03:49 PM:     [repo]/[bluebird]/js/release/async.js:17:14
11:03:49 PM:   
11:03:50 PM: 
11:03:50 PM: Caching artifacts
11:03:50 PM: Cached NPM modules
11:03:50 PM: Saved Cache Directory
11:03:50 PM: Build complete: exit code: 1
11:03:50 PM: Error running command: Build script returned non-zero exit code: 1
11:03:50 PM: Failing build: Failed to build site
11:03:50 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
11:03:50 PM: Finished processing build request in 1m27.474470802s
```

### Expected behavior

The same as locally. To pull all the data from wordpress without a problem. Here's the console log on running `gatsby develop `locally: 

````
$ gatsby develop
success delete html files from previous builds — 0.069 s
success open and validate gatsby-config.js — 0.023 s
success copy gatsby files — 0.187 s
success onPreBootstrap — 0.014 s
⠁ Starting to fetch data from Contentful
Fetching default locale
⡀ source and transform nodesdefault local is : en-US
⠁ source and transform nodescontentTypes fetched 3
Updated entries  0
Deleted entries  0
Updated assets  0
Deleted assets  0
Fetch Contentful data: 510.572ms
⠠ source and transform nodes -> wordpress__POST fetched : 2
⠄ source and transform nodes -> wordpress__PAGE fetched : 1
⠁ source and transform nodes -> wordpress__wp_media fetched : 1
⠐ source and transform nodes -> wordpress__wp_jp_pay_order fetched : 0
⡀ source and transform nodes -> wordpress__wp_jp_pay_product fetched : 0
⠂ source and transform nodes -> wordpress__wp_feedback fetched : 0
⠈ source and transform nodes -> wordpress__wp_types fetched : 1
⡀ source and transform nodes -> wordpress__wp_statuses fetched : 1
⠁ source and transform nodes -> wordpress__wp_taxonomies fetched : 1
⠐ source and transform nodes -> wordpress__CATEGORY fetched : 2
⡀ source and transform nodes -> wordpress__TAG fetched : 8
⠂ source and transform nodes -> wordpress__wp_users fetched : 1
⠐ source and transform nodes -> wordpress__wp_me fetched : 1
⡀ source and transform nodes -> wordpress__wp_comments fetched : 0
⠁ source and transform nodes -> wordpress__wp_settings fetched : 1
⢀ source and transform nodesThe server response was "404 Not Found"
Inner exception message : "No route was found matching the URL and request method"
success source and transform nodes — 7.587 s
success building schema — 4.292 s
success createLayouts — 0.021 s
success createPages — 0.186 s
success createPagesStatefully — 0.045 s
success onPreExtractQueries — 0.004 s
success update schema — 0.479 s
success extract queries from components — 0.657 s
success run graphql queries — 0.030 s
success write out page data — 0.014 s
success write out redirect data — 0.002 s
success onPostBootstrap — 0.002 s

info bootstrap finished - 54 s

DONE  Compiled successfully in 19851ms                                                                                               23:36:13

You can now view gatsby-starter-default in the browser.

  http://localhost:8000/

View GraphiQL, an in-browser IDE, to explore your site's data and schema

  http://localhost:8000/___graphql

Note that the development build is not optimized.
To create a production build, use gatsby build

````

I can provide additional info if needed. The repo is private, though I can give access if needed. 
I don't have any env variables, all access tokens/keys are directly in gatsby-config file:

```
module.exports = {
  siteMetadata: {
    title: `Sebastian Hewelt - portfolio`
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-sass`,
    {
      resolve: `gatsby-source-contentful`,
      options: {
        spaceId: 'spaceIdhere',
        accessToken:
          'accessTokenHere'
      }
    },
    {
      resolve: 'gatsby-source-wordpress',
      options: {
        baseUrl: 'sebastianheweltportfolioprojekty.wordpress.com',
        protocol: 'http',
        hostingWPCOM: true,
        useACF: true,
        auth: {
          wpcom_app_clientSecret:
            'clientSecretHere',
          wpcom_app_clientId: 'clientIdHere',
          wpcom_user: 'sebastianhewelt@gmail.com',
          wpcom_pass: 'wpcomPassHere'
        },
        verboseOutput: false
      }
    },
    `gatsby-transformer-remark`,
    `gatsby-plugin-styled-components`
  ]
};
```

**Comment by gllmt** [comment]
Hello @sebhewelt , same problem, did you find a solution ?

**Comment by patilswapnilv** [comment]
Was someone able to resolve this?

**Comment by octalmage** [comment]
Same issue, looking into it!

**Comment by octalmage** [comment]
I switched to Yarn and it has been resolved. 🤷‍♀️

**Comment by gllmt** [comment]
@octalmage Thanks, I try it 👍 !

**Comment by kakadiadarpan** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub issues, we have to clean some of the old issues as many of them have already been resolved with the latest updates.

Please make sure to update to the latest Gatsby version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

**Comment by kakadiadarpan** [comment]
@gllmt was your issue resolved?

**Comment by jezallan** [comment]
This was resolved for my build on v2 when wordpress credentials were removed from environment variables and into the config directly, which was necessitated by the sensitive information leakage detailed in [#7277](https://github.com/gatsbyjs/gatsby/issues/7277)

**Comment by agyeiarcher** [comment]
I'm having this problem connecting to WordPress, has anyone else had it and got it resolved?

**Comment by agyeiarcher** [comment]
I've done some more work on it and it works fine for wp.org websites, but not for wp.com. Maybe there's a paid account caveat in there

**Comment by jezallan** [comment]
@agyeiarcher Are you using environment variables or referencing another config file to set the `gatsby-source-wordpress` auth options in `gatsby-config.js`? Setting them directly in `gatsby-config.js` solved this issue for me on a wp.com with a free account

**Comment by agyeiarcher** [comment]
@jezallan Yeah, i'd set all the auth options in gatsby-config.js but got no luck. I'd still be able to work it out if it's a possibility for future project
