### ISSUE TITLE
Error: Cannot find module 'gatsby-plugin-utils/polyfill-remote-file'

### ISSUE THREAD

**Issue by MaralS** [gatsbyjs/gatsby#35862]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I tried to create a new Gatsby project using the blog starter using the command `gatsby new` and after the configuration and the installation, I can't run the command `gatsby develop`.

Here is the error message 

```
$ gatsby develop
D:\Maral Sabbagh\Documents\Sites\maral-et-david-v2\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

Error: Cannot find module 'gatsby-plugin-utils/polyfill-remote-file'
Require stack:
- D:\Maral Sabbagh\Documents\Sites\maral-et-david-v2\node_modules\gatsby\dist\utils\start-server.js
- D:\Maral Sabbagh\Documents\Sites\maral-et-david-v2\node_modules\gatsby\dist\services\start-webpack-server.js
- D:\Maral Sabbagh\Documents\Sites\maral-et-david-v2\node_modules\gatsby\dist\services\index.js
- D:\Maral Sabbagh\Documents\Sites\maral-et-david-v2\node_modules\gatsby\dist\state-machines\develop\services.js
- D:\Maral Sabbagh\Documents\Sites\maral-et-david-v2\node_modules\gatsby\dist\state-machines\develop\index.js
- D:\Maral Sabbagh\Documents\Sites\maral-et-david-v2\node_modules\gatsby\dist\commands\develop-process.js
- D:\Maral Sabbagh\Documents\Sites\maral-et-david-v2\.cache\tmp-13452-RjSDgOWBihk8
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)
    at Function.Module._load (internal/modules/cjs/loader.js:863:27)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\Maral Sabbagh\Documents\Sites\maral-et-david-v2\node_modules\gatsby\src\utils\start-server.ts:56:1)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\Maral Sabbagh\Documents\Sites\maral-et-david-v2\node_modules\gatsby\src\services\start-webpack-server.ts:15:1)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Maral Sabbagh\\Documents\\Sites\\maral-et-david-v2\\node_modules\\gatsby\\dist\\utils\\start-server.js',
    'D:\\Maral Sabbagh\\Documents\\Sites\\maral-et-david-v2\\node_modules\\gatsby\\dist\\services\\start-webpack-server.js',
    'D:\\Maral Sabbagh\\Documents\\Sites\\maral-et-david-v2\\node_modules\\gatsby\\dist\\services\\index.js',
    'D:\\Maral Sabbagh\\Documents\\Sites\\maral-et-david-v2\\node_modules\\gatsby\\dist\\state-machines\\develop\\services.js',
    'D:\\Maral Sabbagh\\Documents\\Sites\\maral-et-david-v2\\node_modules\\gatsby\\dist\\state-machines\\develop\\index.js',
    'D:\\Maral Sabbagh\\Documents\\Sites\\maral-et-david-v2\\node_modules\\gatsby\\dist\\commands\\develop-process.js',
    'D:\\Maral Sabbagh\\Documents\\Sites\\maral-et-david-v2\\.cache\\tmp-13452-RjSDgOWBihk8'
  ]
}
``` 

I tried to install the plugin gatsby-plugin-utils by doing `yarn add gatsby-plugin-utils` but it does not solve the problem.

Thanks in advance for your help.

Sincerly,

Maral

### Reproduction Link

https://github.com/MaralS/maral-et-david-v2

### Steps to Reproduce

1. Clone repository
2. Install the modules by running the command `yarn`
3. Run the command `gatsby develop`

### Expected Result

The creation of the development environment.

### Actual Result

An error with `gatsby-plugin-utils`

### Environment

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
  Binaries:
    Node: 12.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.19041.1266.0
  npmPackages:
    gatsby: ^4.15.2 => 4.15.2
    gatsby-plugin-feed: ^4.15.1 => 4.15.1
    gatsby-plugin-gatsby-cloud: ^4.15.0 => 4.15.0
    gatsby-plugin-google-analytics: ^4.15.0 => 4.15.0
    gatsby-plugin-image: ^2.15.1 => 2.15.1
    gatsby-plugin-manifest: ^4.15.1 => 4.15.1
    gatsby-plugin-offline: ^5.15.1 => 5.15.1
    gatsby-plugin-react-helmet: ^5.15.0 => 5.15.0
    gatsby-plugin-sharp: ^4.15.1 => 4.15.1
    gatsby-plugin-utils: ^3.9.1 => 3.9.1
    gatsby-remark-copy-linked-files: ^5.15.0 => 5.15.0
    gatsby-remark-images: ^6.15.1 => 6.15.1
    gatsby-remark-prismjs: ^6.15.0 => 6.15.0
    gatsby-remark-responsive-iframe: ^5.15.0 => 5.15.0
    gatsby-remark-smartypants: ^5.15.0 => 5.15.0
    gatsby-source-filesystem: ^4.15.0 => 4.15.0
    gatsby-transformer-remark: ^5.15.1 => 5.15.1
    gatsby-transformer-sharp: ^4.15.1 => 4.15.1
```

### Config Flags

No flags

**Comment by MaralS** [comment]
Hello I solved the problem installing the current version of NodeJS, I completly forgot. Issue closed
