### ISSUE TITLE
gatsby-source-shopify: Placeholder BLURRED error w/ Shopify CDN

### ISSUE THREAD

**Issue by lambdadev007** [gatsbyjs/gatsby#35930]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hello!
Can anyone give me a solution on the below issue or is this a kind of bug in that source plugin?
I have an issue with Gatsby-source-shopify plugin.
I am getting `TypeError: Cannot read properties of undefined (reading 'contentDigest')` error when I pass placeholder: BLURRED in `gatsbyImageData` field on shopifyProduct images.
i.e.
```
query MyQuery {
  shopifyProduct {
    id
    featuredImage {
      gatsbyImageData(placeholder: BLURRED)
    }
  }
}
```

### Reproduction Link

https://github.com/lambdadev007/gatsby-issue-repo

### Steps to Reproduce

1. Add .env and copy content from .env.example file, and then update environment variables with your Shopify credentials.
2. yarn or npm install
3. open http://localhost:8000/__graphql
4. run below query
```
query MyQuery {
  shopifyProduct {
    id
    featuredImage {
      gatsbyImageData(placeholder: BLURRED)
    }
  }
}
```

### Expected Result

```
{
  "data": {
    "shopifyProduct": {
      "id": "0ddb7b24-4dec-5f3a-9c60-3b54e316d621",
      "featuredImage": {
        "gatsbyImageData": {
          "images": {
            "sources": [
              {
                "srcSet": "https://cdn.shopify.com/s/files/1/0131/2368/2363/products/1.2mm_16g_x8mmTitaniumBarbellExternalThreadASTMf136TitaniumPolishedSilver3mmBalls_225x293_crop_center.jpg.webp?v=1653407313 225w,\nhttps://cdn.shopify.com/s/files/1/0131/2368/2363/products/1.2mm_16g_x8mmTitaniumBarbellExternalThreadASTMf136TitaniumPolishedSilver3mmBalls_450x585_crop_center.jpg.webp?v=1653407313 450w,\nhttps://cdn.shopify.com/s/files/1/0131/2368/2363/products/1.2mm_16g_x8mmTitaniumBarbellExternalThreadASTMf136TitaniumPolishedSilver3mmBalls_900x1170_crop_center.jpg.webp?v=1653407313 900w",
                "sizes": "(min-width: 900px) 900px, 100vw",
                "type": "image/webp"
              }
            ],
            "fallback": {
              "src": "https://cdn.shopify.com/s/files/1/0131/2368/2363/products/1.2mm_16g_x8mmTitaniumBarbellExternalThreadASTMf136TitaniumPolishedSilver3mmBalls_900x1170_crop_center.jpg?v=1653407313",
              "srcSet": "https://cdn.shopify.com/s/files/1/0131/2368/2363/products/1.2mm_16g_x8mmTitaniumBarbellExternalThreadASTMf136TitaniumPolishedSilver3mmBalls_225x293_crop_center.jpg?v=1653407313 225w,\nhttps://cdn.shopify.com/s/files/1/0131/2368/2363/products/1.2mm_16g_x8mmTitaniumBarbellExternalThreadASTMf136TitaniumPolishedSilver3mmBalls_450x585_crop_center.jpg?v=1653407313 450w,\nhttps://cdn.shopify.com/s/files/1/0131/2368/2363/products/1.2mm_16g_x8mmTitaniumBarbellExternalThreadASTMf136TitaniumPolishedSilver3mmBalls_900x1170_crop_center.jpg?v=1653407313 900w",
              "sizes": "(min-width: 900px) 900px, 100vw"
            }
          },
          "layout": "constrained",
          "placeholder": {
            "fallback": "data:image/png;base64,/9j/4QC8RXhpZgAASUkqAAgAAAAGABIBAwABAAAAAQAAABoBBQABAAAAVgAAABsBBQABAAAAXgAAACgBAwABAAAAAgAAABMCAwABAAAAAQAAAGmHBAABAAAAZgAAAAAAAABIAAAAAQAAAEgAAAABAAAABgAAkAcABAAAADAyMTABkQcABAAAAAECAwAAoAcABAAAADAxMDABoAMAAQAAAP//AAACoAQAAQAAABQAAAADoAQAAQAAABoAAAAAAAAA/+IBuElDQ19QUk9GSUxFAAEBAAABqGxjbXMCEAAAbW50clJHQiBYWVogB9wAAQAZAAMAKQA5YWNzcEFQUEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPbWAAEAAAAA0y1sY21zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJZGVzYwAAAPAAAABfY3BydAAAAUwAAAAMd3RwdAAAAVgAAAAUclhZWgAAAWwAAAAUZ1hZWgAAAYAAAAAUYlhZWgAAAZQAAAAUclRSQwAAAQwAAABAZ1RSQwAAAQwAAABAYlRSQwAAAQwAAABAZGVzYwAAAAAAAAAFYzJjaQAAAAAAAAAAAAAAAGN1cnYAAAAAAAAAGgAAAMsByQNjBZIIawv2ED8VURs0IfEpkDIYO5JGBVF3Xe1rcHoFibGafKxpv33Tw+kw//90ZXh0AAAAAENDMABYWVogAAAAAAAA9tYAAQAAAADTLVhZWiAAAAAAAABvogAAOPUAAAOQWFlaIAAAAAAAAGKZAAC3hQAAGNpYWVogAAAAAAAAJKAAAA+EAAC2z//bAEMABQUFBQUFBQYGBQgIBwgICwoJCQoLEQwNDA0MERoQExAQExAaFxsWFRYbFykgHBwgKS8nJScvOTMzOUdER11dff/bAEMBBQUFBQUFBQYGBQgIBwgICwoJCQoLEQwNDA0MERoQExAQExAaFxsWFRYbFykgHBwgKS8nJScvOTMzOUdER11dff/CABEIABoAFAMBEQACEQEDEQH/xAAYAAEAAwEAAAAAAAAAAAAAAAAAAQMECP/EABQBAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhADEAAAAOrgASQVGY3AA//EACAQAAMAAQIHAAAAAAAAAAAAAAECAxEEIAASITFBUXH/2gAIAQEAAT8A3XWrxqsaidSpCOV5wreCV6Z+cR0KpZNRXUWtdUZQzNhQGxnCLhR29Z2//8QAFBEBAAAAAAAAAAAAAAAAAAAAMP/aAAgBAgEBPwBP/8QAFBEBAAAAAAAAAAAAAAAAAAAAMP/aAAgBAwEBPwBP/9k="
          },
          "width": 900,
          "height": 1170
        }
      }
    }
  },
  "extensions": {}
}
```

### Actual Result

```
{
  "errors": [
    {
      "message": "Cannot read properties of undefined (reading 'contentDigest')",
      "locations": [
        {
          "line": 5,
          "column": 7
        }
      ],
      "path": [
        "shopifyProduct",
        "featuredImage",
        "gatsbyImageData"
      ],
      "extensions": {
        "stack": [
          "TypeError: Cannot read properties of undefined (reading 'contentDigest')",
          "    at resolver (F:\\www-2022\\gatsby-issue-repo\\node_modules\\gatsby-source-shopify\\src\\resolve-gatsby-image-data.ts:106:39)",
          "    at wrappedTracingResolver (F:\\www-2022\\gatsby-issue-repo\\node_modules\\gatsby\\src\\schema\\resolvers.ts:683:20)",
          "    at resolveField (F:\\www-2022\\gatsby-issue-repo\\node_modules\\graphql\\execution\\execute.js:464:18)",
          "    at executeFields (F:\\www-2022\\gatsby-issue-repo\\node_modules\\graphql\\execution\\execute.js:292:18)",
          "    at collectAndExecuteSubfields (F:\\www-2022\\gatsby-issue-repo\\node_modules\\graphql\\execution\\execute.js:748:10)",
          "    at completeObjectValue (F:\\www-2022\\gatsby-issue-repo\\node_modules\\graphql\\execution\\execute.js:738:10)",
          "    at completeValue (F:\\www-2022\\gatsby-issue-repo\\node_modules\\graphql\\execution\\execute.js:590:12)",
          "    at resolveField (F:\\www-2022\\gatsby-issue-repo\\node_modules\\graphql\\execution\\execute.js:472:19)",
          "    at executeFields (F:\\www-2022\\gatsby-issue-repo\\node_modules\\graphql\\execution\\execute.js:292:18)",
          "    at collectAndExecuteSubfields (F:\\www-2022\\gatsby-issue-repo\\node_modules\\graphql\\execution\\execute.js:748:10)",
          "    at completeObjectValue (F:\\www-2022\\gatsby-issue-repo\\node_modules\\graphql\\execution\\execute.js:738:10)",
          "    at completeValue (F:\\www-2022\\gatsby-issue-repo\\node_modules\\graphql\\execution\\execute.js:590:12)",
          "    at F:\\www-2022\\gatsby-issue-repo\\node_modules\\graphql\\execution\\execute.js:469:16",
          "    at runMicrotasks (<anonymous>)",
          "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
          "    at async Promise.all (index 0)"
        ]
      }
    }
  ],
  "data": {
    "shopifyProduct": {
      "id": "0ddb7b24-4dec-5f3a-9c60-3b54e316d621",
      "featuredImage": {
        "gatsbyImageData": null
      }
    }
  },
  "extensions": {}
}
```

### Environment

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.4
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.39)
  npmPackages:
    gatsby: ^4.0.2 => 4.13.1 
    gatsby-plugin-gatsby-cloud: ^4.0.0 => 4.13.0 
    gatsby-plugin-google-analytics: ^4.0.0 => 4.13.0 
    gatsby-plugin-image: ^2.0.0 => 2.13.0 
    gatsby-plugin-postcss: ^5.11.0 => 5.13.0 
    gatsby-plugin-react-helmet: ^5.0.0 => 5.13.0 
    gatsby-plugin-sharp: ^4.0.0 => 4.13.0 
    gatsby-plugin-sitemap: ^5.0.0 => 5.13.0 
    gatsby-source-filesystem: ^4.0.0 => 4.13.0 
    gatsby-source-shopify: ^7.6.0-next.0 => 7.6.0-next.0 
    gatsby-transformer-sharp: ^4.0.0 => 4.13.0
```

**Comment by lambdadev007** [comment]
This issue has been resolved by this pull request #35931.

**Comment by explorador** [comment]
Hey! I think we should re-open this issue until the pull request is approved

**Comment by beadlespouse** [comment]
Facing this issue too - currently there are no placeholder options that work with shopify hosted images (as far as I can tell?)

**Comment by beadlespouse** [comment]
I've changed the cacheKey for the base64 placeholder image to 'image.id' rather than 'image.internal.contentDigest' and everything is now working.

**Comment by beadlespouse** [comment]
Pull request submitted -> #37397
