### ISSUE TITLE
DSG pages are not rendering due to a missing gatsby-worker.js file. 

### ISSUE THREAD

**Issue by ashhitch** [gatsbyjs/gatsby#35937]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

DSG pages are not rendering on Gatsby cloud due to a missing `gatsby-worker.js` file. 

If I can get a minimal reproduction together I will update this issue.

### Reproduction Link

https://github.com/gatsbyjs/gatsby/

### Steps to Reproduce

1.  Build pages with `createPage` and `defer` property
2. Deploy to Gatsby Cloud
3. Visit the deferred page

### Expected Result

Pages to render via DSG, when the user visits the URL 

### Actual Result

Shows the error page and reports the following error in the SSR logs.

```
10:16:55 AM:
[ERROR]: (node:2484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2682)

10:16:55 AM:
[ERROR]: (node:2484) UnhandledPromiseRejectionWarning: WorkerError: We couldn't find a gatsby-worker.js(/tmp/cf7ad080-11a7-4102-9016-8b5fb7963f1a/6654704c-b1ae-4012-8da6-1c1da319d41e/query-engine/gatsby-worker.js) file for gatsby@4.16.0 at enqueueJob (/tmp/cf7ad080-11a7-4102-9016-8b5fb7963f1a/6654704c-b1ae-4012-8da6-1c1da319d41e/query-engine/index.js:154670:21) at /tmp/cf7ad080-11a7-4102-9016-8b5fb7963f1a/6654704c-b1ae-4012-8da6-1c1da319d41e/query-engine/index.js:154153:54 at /tmp/cf7ad080-11a7-4102-9016-8b5fb7963f1a/6654704c-b1ae-4012-8da6-1c1da319d41e/query-engine/index.js:156270:64 at /tmp/cf7ad080-11a7-4102-9016-8b5fb7963f1a/6654704c-b1ae-4012-8da6-1c1da319d41e/query-engine/index.js:55147:18 at Object.createJobV2 (/tmp/cf7ad080-11a7-4102-9016-8b5fb7963f1a/6654704c-b1ae-4012-8da6-1c1da319d41e/query-engine/index.js:32815:12) at dispatchLocalImageServiceJob (/tmp/cf7ad080-11a7-4102-9016-8b5fb7963f1a/6654704c-b1ae-4012-8da6-1c1da319d41e/query-engine/index.js:178455:11) at /tmp/cf7ad080-11a7-4102-9016-8b5fb7963f1a/6654704c-b1ae-4012-8da6-1c1da319d41e/query-engine/index.js:179000:55 at Array.map (<anonymous>) at gatsbyImageResolver (/tmp/cf7ad080-11a7-4102-9016-8b5fb7963f1a/6654704c-b1ae-4012-8da6-1c1da319d41e/query-engine/index.js:178998:37) at resolve (/tmp/cf7ad080-11a7-4102-9016-8b5fb7963f1a/6654704c-b1ae-4012-8da6-1c1da319d41e/query-engine/index.js:179179:14) at wrappedTracingResolver (/tmp/cf7ad080-11a7-4102-9016-8b5fb7963f1a/6654704c-b1ae-4012-8da6-1c1da319d41e/query-engine/index.js:133966:20) at resolveField (/tmp/cf7ad080-11a7-4102-9016-8b5fb7963f1a/6654704c-b1ae-4012-8da6-1c1da319d41e/query-engine/index.js:68925:18) at executeFields (/tmp/cf7ad080-11a7-4102-9016-8b5fb7963f1a/6654704c-b1ae-4012-8da6-1c1da319d41e/query-engine/index.js:68754:18) at collectAndExecuteSubfields (/tmp/cf7ad080-11a7-4102-9016-8b5fb7963f1a/6654704c-b1ae-4012-8da6-1c1da319d41e/query-engine/index.js:69209:10) at completeObjectValue (/tmp/cf7ad080-11a7-4102-9016-8b5fb7963f1a/6654704c-b1ae-4012-8da6-1c1da319d41e/query-engine/index.js:69199:10) at completeValue (/tmp/cf7ad080-11a7-4102-9016-8b5fb7963f1a/6654704c-b1ae-4012-8da6-1c1da319d41e/query-engine/index.js:69051:12)
```

### Environment

```shell
System:
    OS: macOS 11.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 102.0.5005.115
    Firefox: 56.0.2
    Safari: 14.1.2
  npmPackages:
    gatsby: ^4.16.0 => 4.16.0 
    gatsby-graphql-source-toolkit: ^2.0.2 => 2.0.2 
    gatsby-omni-font-loader: ^2.0.0 => 2.0.0 
    gatsby-plugin-gatsby-cloud: ^4.16.0 => 4.16.0 
    gatsby-plugin-google-analytics: ^4.16.0 => 4.16.0 
    gatsby-plugin-graphql-config: ^1.14.0 => 1.14.0 
    gatsby-plugin-image: ^2.16.1 => 2.16.1 
    gatsby-plugin-manifest: ^4.16.0 => 4.16.0 
    gatsby-plugin-page-data-preview: ^1.2.1 => 1.2.1 
    gatsby-plugin-perf-budgets: 0.0.18 => 0.0.18 
    gatsby-plugin-react-helmet: ^5.16.0 => 5.16.0 
    gatsby-plugin-sharp: ^4.16.1 => 4.16.1 
    gatsby-plugin-sitemap: ^5.16.0 => 5.16.0 
    gatsby-plugin-styled-components: ^5.16.0 => 5.16.0 
    gatsby-plugin-utils: ^3.10.0 => 3.10.0 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.27 => 1.1.27 
    gatsby-source-filesystem: ^4.16.0 => 4.16.0 
    gatsby-source-uk-bank-holidays: ^1.1.1 => 1.1.1 
    gatsby-transformer-sharp: ^4.16.0 => 4.16.0 
  npmGlobalPackages:
    gatsby-cli: 4.12.1
```

### Config Flags

 PRESERVE_FILE_DOWNLOAD_CACHE: true,

**Comment by pieh** [comment]
I can repro - https://github.com/pieh/contentful-image-cdn-dsg is "minimal reproduction" that can reproduce the issue locally (build -> serve -> visit `/image-api/` page).

It doesn't seem to happen when the `/image-api/` is SSG ( the repro sets that page as SSR to go through engines code path ).

Some additional notes for repro above - initially I thought the problem is with `gatsby-plugin-sharp` not being in `gatsby-config` and that being reason for the problem, but adding it to config doesn't change anything.

My current theory:
https://github.com/gatsbyjs/gatsby/blob/593510667e2e32ff7b5efc351410782b68f3546c/packages/gatsby-plugin-utils/src/polyfill-remote-file/jobs/dispatchers.ts#L116

this `__dirname` turns into path to query engine in compiled directory and later tries to load `<query-engine-dir>/gatsby-worker` which will never work as module like that doesn't exist.

For `gatsby-plugin-sharp` and its worker we do some special trickery to make it work in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/graphql-engine/print-plugins.ts so I suspect we will have to do something similar to get FILE_CDN / IMAGE_CDN handlers to work in engines as well

**Comment by TylerBarnes** [comment]
@pieh is there a different gatsby-worker.js for each plugin? Any docs I can read up on to understand how query engines work?

**Comment by pieh** [comment]
> is there a different gatsby-worker.js for each plugin?

`gatsby-worker.js` files are implemented by plugins that create jobs and is place for job handlers and they should be sibling to `gatsby-node` etc.

`IMAGE_CDN` (and I would assume `FILE_CDN` too) don't follow that (wrong location of gatsby-worker file), but they hack it with `resolve` field to point to current directory so `gatsby` finds `gatsby-worker` file with handlers for those jobs ( https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-utils/src/polyfill-remote-file/jobs/gatsby-worker.ts ) - - I don't know why - probably just trying to keep those modules in shared directory

The problem is that for engines we bundle the code and because of that `__dirname` usage is problematic. I would expect if we use ``resolve: `gatsby-plugin-utils/polyfill-remote-file/jobs` `` or ``resolve: require.resolve(`gatsby-plugin-utils/polyfill-remote-file/jobs`) `` (but ideally first one)

Then next step will be ensuring we DO bundle that `gatsby-worker` file for engines - this will happen somewhere here https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/graphql-engine/print-plugins.ts

The problem is that with hacked `gatsby-worker` like it is now (and also the fact that `gatsby-plugin-utils` is not a plugin itself) this will be likely pretty hacky.

I am not sure if we can know if we need to bundle it or not, so probably we will have to bundle it always (if it exists?). 

We need to change `pluginsWithWorkers` array to add hacky plugin https://github.com/gatsbyjs/gatsby/blob/b024e5a76defcc1699485e6e420f53f91d3bf9aa/packages/gatsby/src/schema/graphql-engine/print-plugins.ts#L70

```diff
   const pluginsWithWorkers = filterPluginsWithWorkers(uniqGatsbyNode)
+  pluginsWithWorkers.push({
+    resolve: <match-whats-in-jobs-dispatcher>,
+    name: <match-whats-in-jobs-dispatcher>
+  })
```

This should be enough for engine to be able to load correct module

**Comment by TylerBarnes** [comment]
Amazing! Thanks for the detailed write up on that! 😄
