### ISSUE TITLE
plugin.wrapRootElement is not a function

### ISSUE THREAD

**Issue by ViktorMeduneckij** [gatsbyjs/gatsby#35973]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Out of the blue, when building projects on Gatsby cloud, `onPostBuild` process fails with:

```
TypeError: plugin.wrapRootElement is not a function
    at wrappers (/usr/src/app/www/.cache/caches/gatsby-plugin-mdx/webpack/webpack:/bigbonktour-blog/node_modules/gatsby-plugin-mdx/utils/wrap-root-render-html-entry.js:12:33)
    at Array.reduce ()
    at WEBPACKDEFAULTEXPORT (/usr/src/app/www/.cache/caches/gatsby-plugin-mdx/webpack/webpack:/bigbonktour-blog/node_modules/gatsby-plugin-mdx/utils/wrap-root-render-html-entry.js:11:26)
    at /usr/src/app/www/node_modules/gatsby-plugin-mdx/utils/render-html.js:75:23
    at Array.map ()
    at /usr/src/app/www/node_modules/gatsby-plugin-mdx/utils/render-html.js:73:22
    at finalCallback (/usr/src/app/www/node_modules/webpack/lib/Compiler.js:441:32)
    at /usr/src/app/www/node_modules/webpack/lib/Compiler.js:505:17
    at /usr/src/app/www/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/usr/src/app/www/node_modules/tapable/lib/HookCodeFactory.js:33:10), :15:1)
    at Hook.CALLASYNCDELEGATE [as callAsync] (/usr/src/app/www/nodemodules/tapable/lib/Hook.js:18:14)
    at Cache.storeBuildDependencies (/usr/src/app/www/node_modules/webpack/lib/Cache.js:122:37)
    at /usr/src/app/www/node_modules/webpack/lib/Compiler.js:501:19
    at Hook.eval [as callAsync] (eval at create (/usr/src/app/www/node_modules/tapable/lib/HookCodeFactory.js:33:10), :15:1)
    at Hook.CALLASYNCDELEGATE [as callAsync] (/usr/src/app/www/nodemodules/tapable/lib/Hook.js:18:14)
    at /usr/src/app/www/node_modules/webpack/lib/Compiler.js:498:23
```

This was not an issue last week. At first I thought it was my code, but then I reverted it and pushed last successful commit, but that didn't help. Doesn't matter which commit I push, it fails the same.
 

### Reproduction Link

none

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

I expect it to build.

### Actual Result

It fails on `onPostBuild`

### Environment

```shell
Gatsby cloud
```

**Comment by LekoArts** [comment]
For Gatsby Cloud support please go here: https://www.gatsbyjs.com/support/
Thanks!

**Comment by cedricdelpoux** [comment]
How did you resolve it @ViktorMeduneckij? Same issue for me for a long time on Gatsby Cloud
