### ISSUE TITLE
Builds fail: "Built Rendering Engines failed validation failed validation."

### ISSUE THREAD

**Issue by jared-mcc** [gatsbyjs/gatsby#36500]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I'm helping test a new gatsby-source-prismic plugin with @angeloashmore and am running into this error message when building my site. We are 90% sure this is related to the 6.0.0-alpha.10 version of the plugin, but we are unsure what exactly is breaking on Gatsby's side. 

![image](https://user-images.githubusercontent.com/42019942/187550263-f9e377ae-9eba-4442-ab34-947aa3f25fd0.png)

### Reproduction Link

https://github.com/jared-mcc/GatsbyErrorMinimalReproduction/settings

### Steps to Reproduce

1. Clone the project
2. npm install
3. npm run build

### Expected Result

A successful build.

### Actual Result

We receive the following error message: 

> "Built Rendering Engines failed validation failed validation. Please open an issue with a reproduction at https://github.com/gatsbyjs/gatsby/issues/new for more help"

### Environment

```shell
System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.16.0/bin/yarn
    npm: 7.13.0 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Safari: 15.5
  npmPackages:
    gatsby: ^4.21.1 => 4.22.0
    gatsby-plugin-gatsby-cloud: ^4.21.0 => 4.22.0
    gatsby-plugin-image: ^2.21.0 => 2.22.0
    gatsby-plugin-manifest: ^4.21.0 => 4.22.0
    gatsby-plugin-offline: ^5.6.0 => 5.22.0
    gatsby-plugin-prismic-previews: ^6.0.0-alpha.10 => 6.0.0-alpha.11
    gatsby-plugin-react-helmet: ^5.6.0 => 5.22.0
    gatsby-plugin-sass: ^5.6.0 => 5.22.0
    gatsby-plugin-sharp: ^4.21.0 => 4.22.0
    gatsby-source-filesystem: ^4.21.1 => 4.22.0
    gatsby-source-prismic: ^6.0.0-alpha.10 => 6.0.0-alpha.11
    gatsby-transformer-sharp: ^4.21.0 => 4.22.0
  npmGlobalPackages:
    gatsby-cli: 4.21.0
```

**Comment by pieh** [comment]
Underlying error that I could extract is:

```
error "gatsby-source-prismic" threw an error while running the createSchemaCustomization lifecycle:

Module build failed: UnhandledSchemeError: Reading from "node:http" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at /home/misiek/test/i36500/node_modules/webpack/lib/NormalModule.js:832:25
    at Hook.eval [as callAsync] (eval at create (/home/misiek/test/i36500/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/misiek/test/i36500/node_modules/tapable/lib/Hook.js:18:14)
    at Object.processResource (/home/misiek/test/i36500/node_modules/webpack/lib/NormalModule.js:829:8)
    at processResource (/home/misiek/test/i36500/node_modules/loader-runner/lib/LoaderRunner.js:220:11)
    at iteratePitchingLoaders (/home/misiek/test/i36500/node_modules/loader-runner/lib/LoaderRunner.js:171:10)
    at runLoaders (/home/misiek/test/i36500/node_modules/loader-runner/lib/LoaderRunner.js:398:2)
    at NormalModule._doBuild (/home/misiek/test/i36500/node_modules/webpack/lib/NormalModule.js:819:3)
    at NormalModule.build (/home/misiek/test/i36500/node_modules/webpack/lib/NormalModule.js:963:15)
    at /home/misiek/test/i36500/node_modules/webpack/lib/Compilation.js:1371:12
    at NormalModule.needBuild (/home/misiek/test/i36500/node_modules/webpack/lib/NormalModule.js:1253:32)
    at Compilation._buildModule (/home/misiek/test/i36500/node_modules/webpack/lib/Compilation.js:1352:10)
    at /home/misiek/test/i36500/node_modules/webpack/lib/util/AsyncQueue.js:303:10
    at Hook.eval [as callAsync] (eval at create (/home/misiek/test/i36500/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncQueue._startProcessing (/home/misiek/test/i36500/node_modules/webpack/lib/util/AsyncQueue.js:293:26)
    at AsyncQueue._ensureProcessing (/home/misiek/test/i36500/node_modules/webpack/lib/util/AsyncQueue.js:280:12)


  Error: Module build failed: UnhandledSchemeError: Reading from "node:http" is not handled by plugins (Unhandled scheme).
  Webpack supports "data:" and "file:" URIs by default.
  You may need an additional plugin to handle "node:" URIs.
  
  - NormalModule.js:832 
    [i36500]/[webpack]/lib/NormalModule.js:832:25
  
  
  - Hook.js:18 Hook.CALL_ASYNC_DELEGATE [as _callAsync]
    [i36500]/[tapable]/lib/Hook.js:18:14
  
  - NormalModule.js:829 Object.processResource
    [i36500]/[webpack]/lib/NormalModule.js:829:8
  
  - LoaderRunner.js:220 processResource
    [i36500]/[loader-runner]/lib/LoaderRunner.js:220:11
  
  - LoaderRunner.js:171 iteratePitchingLoaders
    [i36500]/[loader-runner]/lib/LoaderRunner.js:171:10
  
  - LoaderRunner.js:398 runLoaders
    [i36500]/[loader-runner]/lib/LoaderRunner.js:398:2
  
  - NormalModule.js:819 NormalModule._doBuild
    [i36500]/[webpack]/lib/NormalModule.js:819:3
  
  - NormalModule.js:963 NormalModule.build
    [i36500]/[webpack]/lib/NormalModule.js:963:15
  
  - Compilation.js:1371 
    [i36500]/[webpack]/lib/Compilation.js:1371:12
  
  - NormalModule.js:1253 NormalModule.needBuild
    [i36500]/[webpack]/lib/NormalModule.js:1253:32
  
  - Compilation.js:1352 Compilation._buildModule
    [i36500]/[webpack]/lib/Compilation.js:1352:10
  
  - AsyncQueue.js:303 
    [i36500]/[webpack]/lib/util/AsyncQueue.js:303:10
  
  
  - AsyncQueue.js:293 AsyncQueue._startProcessing
    [i36500]/[webpack]/lib/util/AsyncQueue.js:293:26
  
  - AsyncQueue.js:280 AsyncQueue._ensureProcessing
    [i36500]/[webpack]/lib/util/AsyncQueue.js:280:12
  
  - 3.index.js:22 Object.2593
    /home/misiek/test/i36500/.cache/query-engine/3.index.js:22:7
  
  - index.js:372957 __webpack_require__
    /home/misiek/test/i36500/.cache/query-engine/index.js:372957:42
  
  - 2.index.js:1400 Module.2592
    /home/misiek/test/i36500/.cache/query-engine/2.index.js:1400:67
  
  - index.js:372957 Function.__webpack_require__
    /home/misiek/test/i36500/.cache/query-engine/index.js:372957:42
  
  - index.js:368846 resolveModels
    /home/misiek/test/i36500/.cache/query-engine/index.js:368846:43
  
  - index.js:369802 Object.createSchemaCustomization
    /home/misiek/test/i36500/.cache/query-engine/index.js:369802:51
  
  - index.js:252200 runAPI
    /home/misiek/test/i36500/.cache/query-engine/index.js:252200:16
```

I saw quite a bit more like that (`node:x`) when inspecting webpack stats. I think we will need to update our config for webpack to just work with this syntax ( https://github.com/webpack/webpack/issues/13290 seems related, just annoying it's not webpack's default to handle those :/ ). Currently our config is in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts~

It seems like those imports come from `fetch-blob` which is dep of that new version of `gatsby-source-prismic`, so unfortunately I don't have easy workaround for now

**Comment by pieh** [comment]
@jared-mcc @angeloashmore I started https://github.com/gatsbyjs/gatsby/pull/36506 which seems to fix this for me on the repro you provided.

**Comment by angeloashmore** [comment]
@pieh Thanks for looking into the issue and fixing a fix. 🙂

Do you have a rough estimate of when the fix might be published? I'm wondering if it's something I should attempt to fix in the plugin or if your patch will be rolled out soon. Thanks!

**Comment by pieh** [comment]
@angeloashmore @jared-mcc For now I released `@next` with the change ( `gatsby@4.23.0-next.2`) so at least you could test those things out on your end, but we will look to release this in stable next week most likely

**Comment by angeloashmore** [comment]
Great, thanks @pieh!

**Comment by marvinjude** [comment]
Closing this for now. feel free to reopen if you're stilling running into this issue after trying`@next`

**Comment by insaurabh** [comment]
I am getting this error with  "gatsby": "5.6.1"

![image](https://github.com/gatsbyjs/gatsby/assets/26545067/a9f55af1-32ca-4b0c-8fc0-42ce47c8c116)
