### ISSUE TITLE
yoga-layout-prebuilt error on FreeBSD

### ISSUE THREAD

**Issue by jboyd79** [gatsbyjs/gatsby#36696]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hello,
I installed Gatsby-minimal-starter as per the instructions. 
However when I do 'npm run develop' I get the following error:
```
...bug-repo/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Cannot find module './artifacts/index.freebsd-x64.node'
```
Note that Gatsby installs without any errors.

Any help will be appreciated.

Regards, 
John.

### Reproduction Link

https://github.com/jboyd79/bug-repo

### Steps to Reproduce

1. npm init gatsby
2. cd bug-repo
3. npm run develop
...

### Expected Result

Expected Gatsby site to be running at http://localhost:8000

### Actual Result

Got the following instead:

```
$ cd bug-repo
$ npm run develop

> bug-repo@1.0.0 develop
> gatsby develop

/home/settler/bug-repo/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Cannot find module './artifacts/index.freebsd-x64.node'
Require stack:
- /home/settler/bug-repo/node_modules/@parcel/source-map/parcel_sourcemap_node/index.js
- /home/settler/bug-repo/node_modules/@parcel/source-map/dist/node.js
- /home/settler/bug-repo/node_modules/@parcel/utils/lib/index.js
- /home/settler/bug-repo/node_modules/@parcel/core/lib/public/Config.js
- /home/settler/bug-repo/node_modules/@parcel/core/lib/utils.js
- /home/settler/bug-repo/node_modules/@parcel/core/lib/public/Environment.js
- /home/settler/bug-repo/node_modules/@parcel/core/lib/public/Asset.js
- /home/settler/bug-repo/node_modules/@parcel/core/lib/Parcel.js
- /home/settler/bug-repo/node_modules/@parcel/core/lib/index.js
- /home/settler/bug-repo/node_modules/gatsby/dist/utils/parcel/compile-gatsby-files.js
- /home/settler/bug-repo/node_modules/gatsby/dist/bootstrap/get-config-file.js
- /home/settler/bug-repo/node_modules/gatsby/dist/bootstrap/load-config/index.js
- /home/settler/bug-repo/node_modules/gatsby/dist/services/initialize.js
- /home/settler/bug-repo/node_modules/gatsby/dist/services/index.js
- /home/settler/bug-repo/node_modules/gatsby/dist/state-machines/develop/services.js
- /home/settler/bug-repo/node_modules/gatsby/dist/state-machines/develop/index.js
- /home/settler/bug-repo/node_modules/gatsby/dist/commands/develop-process.js
- /home/settler/bug-repo/.cache/tmp-27117-jVSuU3O916Nw
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/settler/bug-repo/node_modules/@parcel/source-map/parcel_sourcemap_node/index.js:15:18)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/settler/bug-repo/node_modules/@parcel/source-map/dist/node.js:14:18)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/settler/bug-repo/node_modules/@parcel/source-map/parcel_sourcemap_node/index.js',
    '/home/settler/bug-repo/node_modules/@parcel/source-map/dist/node.js',
    '/home/settler/bug-repo/node_modules/@parcel/utils/lib/index.js',
    '/home/settler/bug-repo/node_modules/@parcel/core/lib/public/Config.js',
    '/home/settler/bug-repo/node_modules/@parcel/core/lib/utils.js',
    '/home/settler/bug-repo/node_modules/@parcel/core/lib/public/Environment.js',
    '/home/settler/bug-repo/node_modules/@parcel/core/lib/public/Asset.js',
    '/home/settler/bug-repo/node_modules/@parcel/core/lib/Parcel.js',
    '/home/settler/bug-repo/node_modules/@parcel/core/lib/index.js',
    '/home/settler/bug-repo/node_modules/gatsby/dist/utils/parcel/compile-gatsby-files.js',
    '/home/settler/bug-repo/node_modules/gatsby/dist/bootstrap/get-config-file.js',
    '/home/settler/bug-repo/node_modules/gatsby/dist/bootstrap/load-config/index.js',
    '/home/settler/bug-repo/node_modules/gatsby/dist/services/initialize.js',
    '/home/settler/bug-repo/node_modules/gatsby/dist/services/index.js',
    '/home/settler/bug-repo/node_modules/gatsby/dist/state-machines/develop/services.js',
    '/home/settler/bug-repo/node_modules/gatsby/dist/state-machines/develop/index.js',
    '/home/settler/bug-repo/node_modules/gatsby/dist/commands/develop-process.js',
    '/home/settler/bug-repo/.cache/tmp-27117-jVSuU3O916Nw'
  ]
}

Node.js v18.7.0

```

### Environment

```shell
System:
    OS: freebsd
    CPU: (2) x64 Intel(R) Pentium(R) CPU 2127U @ 1.90GHz
  Binaries:
    Node: 18.7.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.19.1 - /usr/local/bin/npm
  npmPackages:
    gatsby: ^4.23.1 => 4.23.1
  npmGlobalPackages:
    gatsby-cli: 4.23.1
```

**Comment by tyhopp** [comment]
Hi @jboyd79, sorry you ran into this issue. It appears to be a [known issue](https://github.com/parcel-bundler/parcel/issues/5812) that certain Parcel modules (which are dependencies of Gatsby) do not ship FreeBSD compatible binaries, see https://github.com/parcel-bundler/parcel/issues/5812#issuecomment-1082935518.

From the stack trace you provided the issue comes from `@parcel/source-map`, which is one of the modules they mention.

I'll leave this open, but for the time being the best place to track progress on this is in https://github.com/parcel-bundler/parcel/issues/5812.

**Comment by jboyd79** [comment]
Hello @tyhopp,

Thanks very much for checking into this for me. 
I can only hope that the parcel people work it out..

John.

**Comment by jboyd79** [comment]
Hello,

I would much appreciate if you can keep the issue open....for now.

Regards,
John.

**Comment by LekoArts** [comment]
Please track progress on this in https://github.com/parcel-bundler/parcel/issues/5812 as sadly we can't do anything about it.
