### ISSUE TITLE
SSR throws `URIError: URI malformed` page when some URL encoded characters are used

### ISSUE THREAD

**Issue by rymate1234** [gatsbyjs/gatsby#36755]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When using SSR along with URL parameters, when using certain encoded characters e.g. `%ff` the following error is displayed instead:

```
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at findPageByPath (/Users/murthick/Projects/gatsby-starter-hello-world/node_modules/gatsby/src/utils/find-page-by-path.ts:50:10)
    at /Users/murthick/Projects/gatsby-starter-hello-world/node_modules/gatsby/src/utils/express-middlewares.ts:31:18
    at Layer.handle [as handle_request] (/Users/murthick/Projects/gatsby-starter-hello-world/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/murthick/Projects/gatsby-starter-hello-world/node_modules/express/lib/router/index.js:328:13)
    at /Users/murthick/Projects/gatsby-starter-hello-world/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/murthick/Projects/gatsby-starter-hello-world/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/murthick/Projects/gatsby-starter-hello-world/node_modules/express/lib/router/index.js:280:10)
    at /Users/murthick/Projects/gatsby-starter-hello-world/node_modules/webpack-dev-middleware/dist/middleware.js:45:19
    at ready (/Users/murthick/Projects/gatsby-starter-hello-world/node_modules/webpack-dev-middleware/dist/utils/ready.js:11:12)
    at /Users/murthick/Projects/gatsby-starter-hello-world/node_modules/webpack-dev-middleware/dist/middleware.js:40:28
    at new Promise (<anonymous>)
    at goNext (/Users/murthick/Projects/gatsby-starter-hello-world/node_modules/webpack-dev-middleware/dist/middleware.js:39:14)
    at processRequest (/Users/murthick/Projects/gatsby-starter-hello-world/node_modules/webpack-dev-middleware/dist/middleware.js:63:15)
    at ready (/Users/murthick/Projects/gatsby-starter-hello-world/node_modules/webpack-dev-middleware/dist/utils/ready.js:11:12)
    at middleware (/Users/murthick/Projects/gatsby-starter-hello-world/node_modules/webpack-dev-middleware/dist/middleware.js:32:24)
```

### Reproduction Link

https://github.com/rymate1234/gatsby-url-encoded-bug-reprod

### Steps to Reproduce

1. Goto page e.g `curl localhost:8000/test/my%20test%ff`
2. See error

### Expected Result

The `hello world` text plus the text in the url with encoded text

### Actual Result

The error above

### Environment

```shell
System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /var/folders/71/gbxw2h4d2tg_my_wb2b9qrgm0000gn/T/yarn--1665052384504-0.5537737608076572/node
    Yarn: 1.22.17 - /var/folders/71/gbxw2h4d2tg_my_wb2b9qrgm0000gn/T/yarn--1665052384504-0.5537737608076572/yarn
    npm: 6.14.12 - ~/.nave/installed/14.16.1/bin/npm
  Languages:
    Python: 2.7.18 - /Library/Frameworks/Python.framework/Versions/2.7/bin/python
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 105.0.2
    Safari: 16.0
  npmPackages:
    gatsby: ^4.24.1 => 4.24.1
```

**Comment by LekoArts** [comment]
Please use `gatsby@next` and try again

**Comment by rymate1234** [comment]
@LekoArts Upgraded to `gatsby@next` in the reprod repo and issue still persists -- new environment is 

```

  System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /var/folders/71/gbxw2h4d2tg_my_wb2b9qrgm0000gn/T/yarn--1665081879842-0.4
2869355614650173/node
    Yarn: 1.22.17 - /var/folders/71/gbxw2h4d2tg_my_wb2b9qrgm0000gn/T/yarn--1665081879842-0.4
2869355614650173/yarn
    npm: 8.13.2 - /usr/local/bin/npm
  Languages:
    Python: 2.7.18 - /Library/Frameworks/Python.framework/Versions/2.7/bin/python
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 105.0.2
    Safari: 16.0
  npmPackages:
    gatsby: next => 4.24.2
```

**Comment by LekoArts** [comment]
I think this is all working as intended. The error comes from `decodeURIComponent` itself as `%ff` is invalid. Gatsby just uses `decodeURIComponent` under the hood so if that errors out it must be wrong.

```shell
decodeURIComponent('%FF')
VM1046:1 Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at <anonymous>:1:1

encodeURIComponent('ÿ')
'%C3%BF'
```

You'll want to use `%C3%BF`
