### ISSUE TITLE
Gatsby doesn't add detailed logs for Parallel Queries Errors on macOS

### ISSUE THREAD

**Issue by ovflowd** [gatsbyjs/gatsby#36947]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Gatsby does not show any meaningful detail when crashing (exiting) the build process due to "Parallel Query Run" Errors.

### Reproduction Link

https://github.com/nodejs/nodejs.dev

### Steps to Reproduce

1. Try to build
2. It fails because ... (who knows?)

### Expected Result

On Windows and Linux (Fedora, Ubuntu, Debian...) it shows the actual Error, it only does not on macOS.

### Actual Result

It gives you nothing you can work with. (For me, it happens in any repository where a Parallel Query happens).

```
success Caching Webpack compilations - 0.000s

 ERROR #85928 

An error occurred during parallel query running.
Go here for troubleshooting tips: https://gatsby.dev/pqr-feedback



  Error: Worker exited before finishing task
  
  - index.js:117 ChildProcess.<anonymous>
    [nodejs.dev]/[gatsby-worker]/dist/index.js:117:45
  
  - node:events:513 ChildProcess.emit
    node:events:513:28
  
  - child_process:291 Process.ChildProcess._handle.onexit
    node:internal/child_process:291:12
  

not finished run queries in workers - 0.131s


   ~/GitHub/Personal/nodejs.dev on    main ⇡1 *3 !1 ❯ /Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53                                                  took   10s   18.7.0   28.7G with cwunder@DN226VK20N at   17:24:16
        throw ex;
        ^

Error: Channel closed
    at new NodeError (node:internal/errors:387:5)
    at process.target.send (node:internal/child_process:740:16)
    at Object.sendMessage (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-worker/dist/child.js:51:9)
    at Object.intentifiedActionCreators.<computed> [as activityTick] (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-cli/lib/reporter/reporter.js:346:9)
    at updateProgress (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-cli/lib/reporter/reporter-progress.js:35:23)
    at Object.tick (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-cli/lib/reporter/reporter-progress.js:66:7)
    at /Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby/src/query/index.ts:106:20
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/signal-exit/index.js:199:34)
    at node:internal/child_process:744:35
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}

Node.js v18.7.0
/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Channel closed
    at new NodeError (node:internal/errors:387:5)
    at process.target.send (node:internal/child_process:740:16)
    at Object.sendMessage (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-worker/dist/child.js:51:9)
    at Object.intentifiedActionCreators.<computed> [as activityTick] (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-cli/lib/reporter/reporter.js:346:9)
    at updateProgress (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-cli/lib/reporter/reporter-progress.js:35:23)
    at Object.tick (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-cli/lib/reporter/reporter-progress.js:66:7)
    at /Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby/src/query/index.ts:106:20
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/signal-exit/index.js:199:34)
    at node:internal/child_process:744:35
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}

Node.js v18.7.0
/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Channel closed
    at new NodeError (node:internal/errors:387:5)
    at process.target.send (node:internal/child_process:740:16)
    at Object.sendMessage (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-worker/dist/child.js:51:9)
    at Object.intentifiedActionCreators.<computed> [as activityTick] (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-cli/lib/reporter/reporter.js:346:9)
    at updateProgress (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-cli/lib/reporter/reporter-progress.js:35:23)
    at Object.tick (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-cli/lib/reporter/reporter-progress.js:66:7)
    at /Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby/src/query/index.ts:106:20
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/signal-exit/index.js:199:34)
    at node:internal/child_process:744:35
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}

Node.js v18.7.0
/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Channel closed
    at new NodeError (node:internal/errors:387:5)
    at process.target.send (node:internal/child_process:740:16)
    at Object.sendMessage (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-worker/dist/child.js:51:9)
    at Object.intentifiedActionCreators.<computed> [as activityTick] (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-cli/lib/reporter/reporter.js:346:9)
    at updateProgress (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-cli/lib/reporter/reporter-progress.js:35:23)
    at Object.tick (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-cli/lib/reporter/reporter-progress.js:66:7)
    at /Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby/src/query/index.ts:106:20
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/signal-exit/index.js:199:34)
    at node:internal/child_process:744:35
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}

Node.js v18.7.0
/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Channel closed
    at new NodeError (node:internal/errors:387:5)
    at process.target.send (node:internal/child_process:740:16)
    at Object.sendMessage (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-worker/dist/child.js:51:9)
    at Object.intentifiedActionCreators.<computed> [as activityTick] (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-cli/lib/reporter/reporter.js:346:9)
    at updateProgress (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-cli/lib/reporter/reporter-progress.js:35:23)
    at Object.tick (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-cli/lib/reporter/reporter-progress.js:66:7)
    at /Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby/src/query/index.ts:106:20
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/signal-exit/index.js:199:34)
    at node:internal/child_process:744:35
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}

Node.js v18.7.0
/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Channel closed
    at new NodeError (node:internal/errors:387:5)
    at process.target.send (node:internal/child_process:740:16)
    at Object.sendMessage (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-worker/dist/child.js:51:9)
    at Object.intentifiedActionCreators.<computed> [as activityTick] (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-cli/lib/reporter/reporter.js:346:9)
    at updateProgress (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-cli/lib/reporter/reporter-progress.js:35:23)
    at Object.tick (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-cli/lib/reporter/reporter-progress.js:66:7)
    at /Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby/src/query/index.ts:106:20
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/signal-exit/index.js:199:34)
    at node:internal/child_process:744:35
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}

Node.js v18.7.0
/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Channel closed
    at new NodeError (node:internal/errors:387:5)
    at process.target.send (node:internal/child_process:740:16)
    at Object.sendMessage (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-worker/dist/child.js:51:9)
    at Object.intentifiedActionCreators.<computed> [as activityTick] (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-cli/lib/reporter/reporter.js:346:9)
    at updateProgress (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-cli/lib/reporter/reporter-progress.js:35:23)
    at Object.tick (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby-cli/lib/reporter/reporter-progress.js:66:7)
    at /Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/gatsby/src/query/index.ts:106:20
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/Users/cwunder/GitHub/Personal/nodejs.dev/node_modules/signal-exit/index.js:199:34)
    at node:internal/child_process:744:35
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
```

### Environment

```shell
System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Max
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /var/folders/kr/dtpb07wj0cl0vp56klz_xc440000gq/T/yarn--1667406294277-0.07541505423483441/node
    Yarn: 1.22.19 - /var/folders/kr/dtpb07wj0cl0vp56klz_xc440000gq/T/yarn--1667406294277-0.07541505423483441/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 104.0.2
    Safari: 16.1
  npmPackages:
    gatsby: ^4.22.1 => 4.24.6 
    gatsby-link: ^4.22.0 => 4.24.1 
    gatsby-plugin-canonical-urls: ^4.22.0 => 4.24.0 
    gatsby-plugin-catch-links: ^4.22.0 => 4.24.0 
    gatsby-plugin-manifest: ^4.22.0 => 4.24.0 
    gatsby-plugin-mdx: ^3.20.0 => 3.20.0 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-sass: ^5.22.0 => 5.24.0 
    gatsby-plugin-sharp: ^4.23.0 => 4.24.0 
    gatsby-plugin-sitemap: ^5.22.0 => 5.24.0 
    gatsby-plugin-svgr: ^3.0.0-beta.0 => 3.0.0-beta.0 
    gatsby-plugin-typescript: ^4.22.0 => 4.24.0 
    gatsby-plugin-webfonts: ^2.2.2 => 2.2.2 
    gatsby-remark-autolink-headers: ^5.22.0 => 5.24.0 
    gatsby-remark-images: ^6.23.0 => 6.24.0 
    gatsby-remark-prismjs: ^6.22.0 => 6.24.0 
    gatsby-source-filesystem: ^4.22.0 => 4.24.0 
    gatsby-theme-i18n: ^3.0.0 => 3.0.0 
    gatsby-transformer-yaml: ^4.22.0 => 4.24.0
```

### Config Flags

None.

**Comment by LekoArts** [comment]
We're working on a fix for this at the moment (no ETA)
