### ISSUE TITLE
[ERROR]: Error: Unable to read file

### ISSUE THREAD

**Issue by MohdSohail** [gatsbyjs/gatsby#37232]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I'm building a Gatsby website sourcing data from WordPress using gatsby-source-wordpress plugin. Everything is working fine locally but as soon as I publish the site, it returns 500 error. The page is built using SSR method and sourcing data using graphql. I have noticed that the error goes away when I do not include any featured image in my graphql query.

For example, currently I am trying to fetch featured image of every post -

query ($id: String) {
        wpPost(id: { eq: $id }) {
            id
            excerpt
            date
            commentCount
            slug
            uri
            title
            content
            featuredImage {
                node {
                    altText
                    localFile {
                        childImageSharp {
                            gatsbyImageData(
                                placeholder: BLURRED
                                formats: [AUTO, WEBP, AVIF]
                            )
                        }
                    }
                }
            }
            categories {
                nodes {
                    id
                    name
                    uri
                }
            }
            tags {
                nodes {
                    id
                    name
                    uri
                }
            }
            author {
                node {
                    avatar {
                        url
                    }
                    name
                    description
                    uri
                }
            }
            comments {
                nodes {
                    author {
                        node {
                            avatar {
                                url
                            }
                            name
                            url
                        }
                    }
                    id
                    content
                    date
                }
            }
            seo {
                title
                metaDesc
                canonical
                schema {
                    raw
                }
                breadcrumbs {
                    text
                    url
                }
                opengraphDescription
                opengraphModifiedTime
                opengraphPublishedTime
                opengraphPublisher
                opengraphTitle
                opengraphType
                opengraphUrl
                readingTime
                opengraphSiteName
                opengraphImage {
                    localFile {
                        publicURL
                    }
                    width
                    height
                    altText
                }
            }
        }
    }

The above query works fine in the local development environment. It throws 500 error as soon as I deploy it in gatsby cloud. If I remove every image from the above query, everything works fine in production as well. The following query will work in Gatsby cloud -

query ($id: String) {
        wpPost(id: { eq: $id }) {
            id
            excerpt
            date
            commentCount
            slug
            uri
            title
            content
            categories {
                nodes {
                    id
                    name
                    uri
                }
            }
            tags {
                nodes {
                    id
                    name
                    uri
                }
            }
            author {
                node {
                    avatar {
                        url
                    }
                    name
                    description
                    uri
                }
            }
            comments {
                nodes {
                    author {
                        node {
                            avatar {
                                url
                            }
                            name
                            url
                        }
                    }
                    id
                    content
                    date
                }
            }
            seo {
                title
                metaDesc
                canonical
                schema {
                    raw
                }
                breadcrumbs {
                    text
                    url
                }
                opengraphDescription
                opengraphModifiedTime
                opengraphPublishedTime
                opengraphPublisher
                opengraphTitle
                opengraphType
                opengraphUrl
                readingTime
                opengraphSiteName
            }
        }
    }

Notice in the above query the two image tags, featuredImage and opengraphImage have been removed. Now this query will work in Gatsby cloud.

Gatsby cloud SSR Logs show the following errors -

11:39:27 AM:
[ERROR]: ENOENT: no such file or directory, stat '/usr/src/app/www/.cache/caches/gatsby-source-wordpress/0fb8b8d4ee04fd1da2c52babd95fe726/network-6926764_1920-1.jpg' at Object.statSync (node:fs:1596:3) at Object.statSync (/query-engine/index.js:6789:34) at opts.dereference.fs.lstatSync.bigint (/query-engine/index.js:7422:20) at getStatsSync (/query-engine/index.js:7424:19) at Object.checkPathsSync (/query-engine/index.js:7466:33) at Object.copySync (/query-engine/index.js:7587:38) at resolve (/query-engine/index.js:407583:14) at wrappedTracingResolver (/query-engine/index.js:121344:20) at executeField (/query-engine/index.js:58333:20) at executeFields (/query-engine/index.js:58265:20) at completeObjectValue (/query-engine/index.js:58755:10) at completeValue (/query-engine/index.js:58485:12) at executeField (/query-engine/index.js:58341:19) at executeFields (/query-engine/index.js:58265:20) at completeObjectValue (/query-engine/index.js:58755:10)

11:39:27 AM:
ENOENT: no such file or directory, stat '/usr/src/app/www/.cache/caches/gatsby-source-wordpress/0fb8b8d4ee04fd1da2c52babd95fe726/network-6926764_1920-1.jpg' 73 | opengraphModifiedTime 74 | opengraphPublishedTime 75 | opengraphPublisher 76 | opengraphTitle 77 | opengraphType 78 | opengraphUrl 79 | readingTime 80 | opengraphSiteName 81 | opengraphImage { 82 | localFile { > 83 | publicURL | ^ 84 | } 85 | width 86 | height 87 | altText 88 | } 89 | } 90 | } 91 | }

11:39:25 AM:
gatsby-source-wordpress ingest WPGraphQL schema

I have already tried clearing cache and re-deploy the app on a different server. Nothing worked so far.

### Reproduction Link

https://codesandbox.io/s/white-leaf-vnt2f9?file=/src/pages/%7BwpPost.uri%7D.js

### Steps to Reproduce

1. Create SSR page with File System Route API
2. Query any featured image in the page
3. Deploy the application in production on Gatsby
...

### Expected Result

The featured images should be fetched and be available to use on the page.

### Actual Result

Getting 500 error in production. The server SSR Log shows the following error - 

11:39:27 AM:
[ERROR]: ENOENT: no such file or directory, stat '/usr/src/app/www/.cache/caches/gatsby-source-wordpress/0fb8b8d4ee04fd1da2c52babd95fe726/network-6926764_1920-1.jpg' at Object.statSync (node:fs:1596:3) at Object.statSync (/query-engine/index.js:6789:34) at opts.dereference.fs.lstatSync.bigint (/query-engine/index.js:7422:20) at getStatsSync (/query-engine/index.js:7424:19) at Object.checkPathsSync (/query-engine/index.js:7466:33) at Object.copySync (/query-engine/index.js:7587:38) at resolve (/query-engine/index.js:407583:14) at wrappedTracingResolver (/query-engine/index.js:121344:20) at executeField (/query-engine/index.js:58333:20) at executeFields (/query-engine/index.js:58265:20) at completeObjectValue (/query-engine/index.js:58755:10) at completeValue (/query-engine/index.js:58485:12) at executeField (/query-engine/index.js:58341:19) at executeFields (/query-engine/index.js:58265:20) at completeObjectValue (/query-engine/index.js:58755:10)

11:39:27 AM:
ENOENT: no such file or directory, stat '/usr/src/app/www/.cache/caches/gatsby-source-wordpress/0fb8b8d4ee04fd1da2c52babd95fe726/network-6926764_1920-1.jpg' 73 | opengraphModifiedTime 74 | opengraphPublishedTime 75 | opengraphPublisher 76 | opengraphTitle 77 | opengraphType 78 | opengraphUrl 79 | readingTime 80 | opengraphSiteName 81 | opengraphImage { 82 | localFile { > 83 | publicURL | ^ 84 | } 85 | width 86 | height 87 | altText 88 | } 89 | } 90 | } 91 | }

11:39:25 AM:
gatsby-source-wordpress ingest WPGraphQL schema

### Environment

```shell
System:
    OS: Linux 5.15 Linux Mint 21 (Vanessa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
    Firefox: 107.0.1
  npmPackages:
    gatsby: ^5.2.0 => 5.2.0
    gatsby-plugin-image: ^3.2.0 => 3.2.0
    gatsby-plugin-next-seo: ^1.10.0 => 1.10.0
    gatsby-plugin-nprogress: ^5.2.0 => 5.2.0
    gatsby-plugin-postcss: ^6.2.0 => 6.2.0
    gatsby-plugin-sharp: ^5.2.0 => 5.2.0
    gatsby-source-filesystem: ^5.2.0 => 5.2.0
    gatsby-source-wordpress: ^7.2.0 => 7.2.0
    gatsby-transformer-sharp: ^5.2.0 => 5.2.0
  npmGlobalPackages:
    gatsby-cli: 5.0.0
```

**Comment by MohdSohail** [comment]
Hi @tyhopp, Thanks for the reply! I've emailed the Gatsby support regarding the issue.
