### ISSUE TITLE
Gatsby Head can't handle JSON properly

### ISSUE THREAD

**Issue by Kikobeats** [gatsbyjs/gatsby#37333]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Just I see this in https://www.gatsbyjs.com/docs/how-to/adding-common-features/adding-seo-component/#rich-snippets:

<img width="840" alt="CleanShot 2022-12-24 at 15 18 50@2x" src="https://user-images.githubusercontent.com/2096101/209439745-c01ee675-6ab4-4568-bb4c-2c4cd00b322b.png">

If I enable `DEV_SSR` I can see an SSR issue there:

```
Warning: Text content did not match. Server: "
  {
    &quot;@context&quot;: &quot;https://schema.org&quot;,
    &quot;@type&quot;: &quot;Organization&quot;,
    &quot;url&quot;: &quot;https://www.spookytech.com&quot;,
    &quot;name&quot;: &quot;Spooky technologies&quot;,
    &quot;contactPoint&quot;: {
      &quot;@type&quot;: &quot;ContactPoint&quot;,
      &quot;telephone&quot;: &quot;+5-601-785-8543&quot;,
      &quot;contactType&quot;: &quot;Customer Support&quot;
    }
  }
  " Client: "
  {
    "@context": "https://schema.org",
    "@type": "Organization",
    "url": "https://www.spookytech.com",
    "name": "Spooky technologies",
    "contactPoint": {
      "@type": "ContactPoint",
      "telephone": "+5-601-785-8543",
      "contactType": "Customer Support"
    }
  }
  "
    at script
    at Head (webpack-internal:///./src/components/Head.js:69:5)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:29:19680)
    at G (webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:9074)
    at Fe (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:29:17229)
    at Layout (webpack-internal:///./src/components/patterns/Layout.js:35:5)
    at HomePage (webpack-internal:///./src/pages/index.js?export=default:28:71)
    at PageRenderer (webpack-internal:///./.cache/page-renderer.js:24:76)
    at PageQueryStore (webpack-internal:///./.cache/query-result-store.js:35:30)
    at RouteHandler
    at div
    at re (webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:9865)
    at ee (webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:9680)
    at ae (webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:10957)
    at oe (webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:10831)
    at ScrollHandler (webpack-internal:///./node_modules/gatsby-react-router-scroll/scroll-handler.js:36:35)
    at RouteUpdates (webpack-internal:///./.cache/navigation.js:253:32)
    at EnsureResources (webpack-internal:///./.cache/ensure-resources.js:19:30)
    at LocationHandler (webpack-internal:///./.cache/root.js:62:29)
    at eval (webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:8283)
    at F (webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:7181)
    at H (webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:7483)
    at WithErrorBoundary()
    at G (webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:9074)
    at Root
    at ye (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:29:12788)
    at StaticQueryStore (webpack-internal:///./.cache/query-result-store.js:130:32)
    at SliceDataStore (webpack-internal:///./.cache/query-result-store.js:177:32)
    at ErrorBoundary (webpack-internal:///./.cache/fast-refresh-overlay/components/error-boundary.js:21:35)
    at DevOverlay (webpack-internal:///./.cache/fast-refresh-overlay/index.js:119:5)
    at RootWrappedWithOverlayAndProvider
    at App (webpack-internal:///./.cache/app.js:167:80)
```

### Reproduction Link

https://www.gatsbyjs.com/docs/how-to/adding-common-features/adding-seo-component/#rich-snippets

### Steps to Reproduce

1. Go to https://www.gatsbyjs.com/docs/how-to/adding-common-features/adding-seo-component/#rich-snippets
2. paste the LD+JSON snippet in your gatsby project
3. run your project with `DEV_SSR` flag.

### Expected Result

It should be the same for client and server.

### Actual Result

The server is messing with the quotes (`"`) of the JSON

### Environment

```shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 19.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - /opt/homebrew/bin/npm
  Languages:
    Python: 3.10.8 - /opt/homebrew/bin/python
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
    Safari: 16.1
  npmPackages:
    gatsby: ~5.3.2 => 5.3.3
    gatsby-plugin-advanced-sitemap: ~2.1.0 => 2.1.0
    gatsby-plugin-canonical-urls: ~5.3.0 => 5.3.0
    gatsby-plugin-catch-links: ~5.3.0 => 5.3.0
    gatsby-plugin-google-analytics: ~5.3.0 => 5.3.0
    gatsby-plugin-sass: ~6.3.1 => 6.3.1
    gatsby-plugin-styled-components: ~6.3.0 => 6.3.0
    gatsby-source-filesystem: ~5.3.1 => 5.3.1
    gatsby-transformer-javascript-frontmatter: ~5.3.0 => 5.3.0
    gatsby-transformer-json: ~5.3.0 => 5.3.0
    gatsby-transformer-remark: ~6.3.1 => 6.3.2
    gatsby-transformer-yaml: ~5.3.0 => 5.3.0
```

### Config Flags

DEV_SSR: true

**Comment by byronwilliams** [comment]
Another variant is that `<style>` tag is encoded with entities that you don't want... e.g.

```
      {fonts.map(([weight, style], idx) => {
        return (
          <style key={idx} type="text/css">
            {`@font-face {
                font-family: 'Poppins';
                font-style: ${style};
                font-display: swap;
                font-weight: ${weight};
                src: url('/fonts/poppins-latin-${weight}-${style}.woff2') format('woff2'), url('/fonts/poppins-latin-${weight}-${style}.woff') format('woff');
              }`}
          </style>
        );
      })}
```

produces this invalid HTML which doesn't pass the W3 Validator:

```
 @font-face {
      font-family: &quot;Poppins&quot;;
      font-style: normal;
      font-display: swap;
      font-weight: 300;
      src: url(&quot;/fonts/poppins-latin-300-normal.woff2&quot;) format(&quot;woff2&quot;), url(&quot;/fonts/poppins-latin-300-normal.woff&quot;) format(&quot;woff&quot;);
    }</style><style type="text/css" data-gatsby-head="true">
    @font-face {
      font-family: &quot;Poppins&quot;;
      font-style: normal;
      font-display: swap;
      font-weight: 400;
      src: url(&quot;/fonts/poppins-latin-400-normal.woff2&quot;) format(&quot;woff2&quot;), url(&quot;/fonts/poppins-latin-400-normal.woff&quot;) format(&quot;woff&quot;);
    }</style><style type="text/css" data-gatsby-head="true">
```

this happens with dangerouslySetInnerHTML as well

**Comment by marvinjude** [comment]
Hey @Kikobeats,

You should add the data block to `Head` instead. Please read https://www.gatsbyjs.com/docs/how-to/adding-common-features/adding-seo-component/#additional-information

```js
export const Head = () => {
  return (
    <>
      <script type="application/ld+json">
        {`
    {
      "@context": "https://schema.org",
      "@type": "Organization",
      "url": "https://www.spookytech.com",
      "name": "Spooky technologies",
      "contactPoint": {
        "@type": "ContactPoint",
        "telephone": "+5-601-785-8543",
        "contactType": "Customer Support"
      }
    }
  `}
      </script>
    </>
  );
};

```


For the other issue that @byronwilliams pointed out — it think we may need to do [this handling](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/head/head-export-handler-for-ssr.js#L67) for all tags or simply include `<style>` tags in the check

**Comment by marvinjude** [comment]
Closing this issue as per the comment above. @byronwilliams  I've opened a [PR](https://github.com/gatsbyjs/gatsby/pull/37410) to fix the issue you pointed out
