### ISSUE TITLE
Unable to query Union type with graphql - 'Querying GraphQLUnion types is not supported'

### ISSUE THREAD

**Issue by arsinclair** [gatsbyjs/gatsby#37720]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I have a few JSON files in a project which are linked with each other (VideoGalleryJson, TextModuleJson and ReportJson). _ReportJson_ has a field called _contentComposer_m which is a graphql Union type combining _VideoGalleryJson_ and _TextModuleJson_ in an array.

Here's is the schema:

```graphql
type VideoGalleryJson implements Node {
    node_locale: String
}

type TextModuleJson implements Node {
    node_locale: String
}

union Content = TextModuleJson | VideoGalleryJson

type ReportJson implements Node {
    contentComposer: [ Content ] @link(by: "jsonId")
}
```

When I'm trying to query the _contentComposer_ in graphiql or in my code with the following query:

```graphql
query MyQuery {
  allReportJson {
    nodes {
      contentComposer {
        ... on TextModuleJson {
          id
        }
        ... on VideoGalleryJson {
          id
        }
      }
    }
  }
}
```

I receive the following error:

```json
{
  "errors": [
    {
      "message": "Querying GraphQLUnion types is not supported.",
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "path": [
        "allReportJson",
        "nodes",
        0,
        "contentComposer"
      ],
      "extensions": {
        "stack": [
          "Invariant Violation: Querying GraphQLUnion types is not supported.",
          "    at invariant (/home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/invariant/invariant.js:40:15)",
          "    at LocalNodeModel._query (/home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/gatsby/src/schema/node-model.js:205:5)",
          "    at LocalNodeModel.findAll (/home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/gatsby/src/schema/node-model.js:346:47)",
          "    at ContextualNodeModel.findAll (/home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/gatsby/src/schema/node-model.js:665:27)",
          "    at linkResolverValue (/home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/gatsby/src/schema/resolvers.ts:462:8)",
          "    at resolver (/home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/gatsby/src/schema/resolvers.ts:393:12)",
          "    at wrappedTracingResolver (/home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/gatsby/src/schema/resolvers.ts:751:20)",
          "    at executeField (/home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/graphql/execution/execute.js:481:20)",
          "    at executeFields (/home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/graphql/execution/execute.js:413:20)",
          "    at completeObjectValue (/home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/graphql/execution/execute.js:914:10)",
          "    at completeValue (/home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/graphql/execution/execute.js:635:12)",
          "    at completeValue (/home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/graphql/execution/execute.js:584:23)",
          "    at /home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/graphql/execution/execute.js:696:25",
          "    at Function.from (<anonymous>)",
          "    at completeListValue (/home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/graphql/execution/execute.js:676:34)",
          "    at completeValue (/home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/graphql/execution/execute.js:607:12)",
          "    at completeValue (/home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/graphql/execution/execute.js:584:23)",
          "    at executeField (/home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/graphql/execution/execute.js:489:19)",
          "    at executeFields (/home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/graphql/execution/execute.js:413:20)",
          "    at completeObjectValue (/home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/graphql/execution/execute.js:914:10)",
          "    at completeValue (/home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/graphql/execution/execute.js:635:12)",
          "    at completeValue (/home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/graphql/execution/execute.js:584:23)",
          "    at /home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/graphql/execution/execute.js:486:9",
          "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
          "    at async Promise.all (index 0)",
          "    at handler (/home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/graphql-http/lib/handler.js:272:22)",
          "    at requestListener (/home/jrm/GIT/gatsby-buug/my-gatsby-site/node_modules/graphql-http/lib/use/express.js:28:34)"
        ]
      }
    }
  ],
  "data": {
    "allReportJson": {
      "nodes": [
        {
          "contentComposer": null
        }
      ]
    }
  },
  "extensions": {}
}
```

I don't see if I'm doing anything wrong, so I believe this might be a bug.

### Reproduction Link

https://github.com/arsinclair/gatsby-union-bug

### Steps to Reproduce

1. Clone the reproduction repo
2. Install dependencies and run `npm run develop`
3. After the site loads, go to http://localhost:8000/___graphql and run the following query
```grapql
query MyQuery {
  allReportJson {
    nodes {
      contentComposer {
        ... on TextModuleJson {
          id
        }
        ... on VideoGalleryJson {
          id
        }
      }
    }
  }
}
```
4. Observe the error from the description

### Expected Result

The query should run.

### Actual Result

The error.

### Environment

```shell
System:
    OS: Linux 6.0 Debian GNU/Linux bookworm/sid
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12600
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 18.13.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.4.1 - /usr/local/bin/npm
  npmPackages:
    gatsby: ^5.7.0 => 5.7.0 
    gatsby-source-filesystem: ^5.7.0 => 5.7.0 
    gatsby-transformer-json: ^5.7.0 => 5.7.0
```

**Comment by arsinclair** [comment]
Was the support dropped at some point? I've encountered this issue while upgrading from Gatsby v2 to v5.
