### ISSUE TITLE
gatsby-link within html.jsx Fails to Build

### ISSUE THREAD

**Issue by srsgores** [gatsbyjs/gatsby#3774]
## Description
If you put any template within `html.jsx` that uses `gatsby-link`, the build will fail with:

> error There was an error compiling the html.js component for the development server.
> 
> See our docs page on debugging HTML builds for help https://goo.gl/yL9lND
> 
>   106 |
>   107 |     console.log(context);
> > 108 |     var history = context.router.history;
>       | ^
>   109 |
>   110 |     var to = createLocation(props.to, history);
>   111 |
> 
> 
>   WebpackError: Cannot read property 'history' of undefined
> 
>   - index.js?04f6:108 new GatsbyLink
>     ~/gatsby-link/index.js?04f6:108:1
> 
>   - ReactCompositeComponent.js?d2b3:292
>     ~/react-dom/lib/ReactCompositeComponent.js?d2b3:292:1
> 
>   - ReactCompositeComponent.js?d2b3:73 measureLifeCyclePerf
>     ~/react-dom/lib/ReactCompositeComponent.js?d2b3:73:1
> 
>   - ReactCompositeComponent.js?d2b3:291 ReactCompositeComponentWrapper._constructComponentWithoutOwner
>     ~/react-dom/lib/ReactCompositeComponent.js?d2b3:291:1
> 
>   - ReactCompositeComponent.js?d2b3:282 ReactCompositeComponentWrapper._constructComponent
>     ~/react-dom/lib/ReactCompositeComponent.js?d2b3:282:1
> 
>   - ReactCompositeComponent.js?d2b3:185 ReactCompositeComponentWrapper.mountComponent
>     ~/react-dom/lib/ReactCompositeComponent.js?d2b3:185:1
> 
>   - ReactReconciler.js?399b:43 Object.mountComponent
>     ~/react-dom/lib/ReactReconciler.js?399b:43:1
> 
>   - ReactMultiChild.js?9682:234 ReactDOMComponent.mountChildren
>     ~/react-dom/lib/ReactMultiChild.js?9682:234:1
> 
>   - ReactDOMComponent.js?ab8a:657 ReactDOMComponent._createContentMarkup
>     ~/react-dom/lib/ReactDOMComponent.js?ab8a:657:1
> 
>   - ReactDOMComponent.js?ab8a:524 ReactDOMComponent.mountComponent
>     ~/react-dom/lib/ReactDOMComponent.js?ab8a:524:1

### Environment

Gatsby version: `1.9.172`
Node.js version: `8.5.0`
Operating System: Windows 10x64

### Actual result

Build fails.  `context.router` is `undefined`.  `context` is `{ router: undefined }`

### Expected behaviour

Build should succeed.

### Steps to reproduce

1. Place a template in `html.jsx` which uses `gatsby-link`:

(in `html.jsx`)
```<Header/>```

(`src/components/Header.jsx`)
```
import Link from "gatsby-link";

export default class Header extends React.Component {
	renderNavItems(items) {
		return items.map((navItem, index) => {
			return (
				<li className="nav-item" key={index}>
					<Link to={navItem.url} className="nav-item-link" activeClassName="active">
						{navItem.text}
					</Link>
				</li>
			);
		});
	}
	renderPrimaryNav(items, showing) {
		if (showing) {
			return <nav className="nav floating" role="navigation">
				<ul className="nav-items">
					{this.renderNavItems(items)}
				</ul>
			</nav>;
		}
	}
	render() {
		const {navItems, showNav} = this.props;

		return (
			<header role="banner" className="banner">
				{this.renderPrimaryNav(navItems, showNav)}
			</header>
		);
	}
}
```

2. Attempt to build

## Notes

Building succeeds if the same component is placed in `layouts/index.jsx`.

**Comment by KyleAMathews** [comment]
The `html.js` component is *only* used for server rendering and for things *outside* of `<body/>`. So stuff like this should go in `layout/index.js`. See the docs on html.js https://www.gatsbyjs.org/docs/building-with-components/#html-component

**Comment by iwarner** [comment]
@KyleAMathews 

I have a similar issue when running tests aagainst a Navbar component from my UI library that requires Gatsby-link

Gatsby, Link and CLI was  is installed in the UI NPM package but results in:

    Error: Uncaught [TypeError: Cannot read property 'history' of undefined]

   TypeError: Cannot read property 'history' of undefined

So for testing purposes is it possible to switch of the History push of Link ?

Stack trace below:

```
      39 | 
      40 | // Snapshot: External Link: https
    > 41 | it('Renders correctly', () => {
      42 |   const tree = renderer
      43 |     .create(<Link to='https://domain.com'>External HTTPS</Link>)
      44 |     .toJSON()
      
      at new GatsbyLink (node_modules/gatsby-link/index.js:107:34)
      at constructClassInstance (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2138:20)
      at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3622:9)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4008:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6007:16)
      at workLoop (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6071:26)
      at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1610:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1649:16)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1506:29)
      at renderRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6149:7)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6797:24)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6750:7)
      at requestWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6661:7)
      at scheduleWorkImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6515:11)
      at scheduleWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6472:12)
      at scheduleTopLevelUpdate (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6976:5)
      at Object.updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7014:7)
      at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7637:18)
      at Object.<anonymous> (component/atom/Link/Link.spec.jsx:41:42)
```
