### ISSUE TITLE
$ gatsby build > state.messages is not iterable

### ISSUE THREAD

**Issue by tswaehn** [gatsbyjs/gatsby#37757]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

build fails with nodejs v18 and v19

```
$ gatsby build
success open and validate gatsby-configs, load plugins - 0.090s
success onPreInit - 0.000s
success initialize cache - 0.035s
success copy gatsby files - 0.313s
.../docs/node_modules/gatsby-cli/lib/reporter/redux/reducer.js:29
          messages: [...state.messages, action.payload]
                              ^
TypeError: state.messages is not iterable
    at reducer (/builds/technical-documentation/docs/node_modules/gatsby-cli/lib/reporter/redux/reducer.js:29:31)
    at combination (/builds/technical-documentation/docs/node_modules/redux/lib/redux.js:536:29)
    at next (/builds/technical-documentation/docs/node_modules/redux/lib/redux.js:296:22)
    at /builds/technical-documentation/docs/node_modules/gatsby/src/redux/index.ts:72:68
    at Object.dispatch (/builds/technical-documentation/docs/node_modules/redux-thunk/lib/index.js:14:16)
    at dispatch (/usr/local/lib/node_modules/gatsby-cli/lib/reporter/redux/index.js:39:9)
    at Object.createLog (/usr/local/lib/node_modules/gatsby-cli/node_modules/redux/lib/redux.js:586:12)
    at Reporter.error (/usr/local/lib/node_modules/gatsby-cli/lib/reporter/reporter.js:164:23)
    at Reporter.panic (/usr/local/lib/node_modules/gatsby-cli/lib/reporter/reporter.js:89:32)
    at process.<anonymous> (/usr/local/lib/node_modules/gatsby-cli/lib/index.js:65:21)
    at process.emit (node:events:525:35)
    at processEmit (/usr/local/lib/node_modules/gatsby-cli/node_modules/signal-exit/index.js:199:34)
    at processEmit (/builds/technical-documentation/docs/node_modules/signal-exit/index.js:175:34)
    at process.emit (/builds/technical-documentation/docs/node_modules/@turist/fetch/dist/sourcemap-register.js:926:21)
    at process._fatalException (node:internal/process/execution:149:25)
Node.js v18.15.0


```

### Reproduction Link

https://dont-know-how-to-show-building-in-docker.com

### Steps to Reproduce

1. $ npm install -g gatsby-cli
2. $ gatsby build

### Expected Result

no error

### Actual Result

cannot build

### Environment

```shell
Pulling docker image node:18 and node:19
```

### Config Flags

gatsby config

```
module.exports = {
  /* Your site config here */
  plugins: [`gatsby-plugin-fontawesome-css`],
}
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

You can for example use https://codesandbox.io/docs/tutorial/getting-started-with-docker to show docker reproductions.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment]
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!
