### ISSUE TITLE
graphql conflicts inside gatsby dependencies

### ISSUE THREAD

**Issue by barbalex** [gatsbyjs/gatsby#37969]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I have a project I have been working on sporadically for years.

Now installing a new pc. So cloned the project, ran `npm i --force` and then `npm run dev`. As so many times on the old pc.

But getting:
```
npm WARN     node_modules/gatsby
  Date.'. Stacktrace was 'Error: Cannot create as TypeComposer the following value:
  Date.
    at SchemaComposer.createTempTC (C:\Users\alexa\bb2\node_modules\graphql-compose\src\SchemaComposer.ts:624:11)
    at SchemaComposer.createTC (C:\Users\alexa\bb2\node_modules\graphql-compose\src\SchemaComposer.ts:580:66)
    at SchemaComposer.add (C:\Users\alexa\bb2\node_modules\graphql-compose\src\SchemaComposer.ts:876:21)
    at createSchemaComposer (C:\Users\alexa\bb2\node_modules\gatsby\src\schema\schema-composer.ts:21:18)
    at build (C:\Users\alexa\bb2\node_modules\gatsby\src\schema\index.js:110:26)
    at buildSchema (C:\Users\alexa\bb2\node_modules\gatsby\src\services\build-schema.ts:19:3)'
```

Seing from other post this is supposed to be a graphql version conflict. So I ran `npm list graphql`:
```console
PS C:\Users\alexa\bb2> npm list graphql
blue-borders@3.0.2 C:\Users\alexa\bb2
├─┬ @apollo/client@3.7.3
│ ├─┬ @graphql-typed-document-node/core@3.2.0
│ │ └── graphql@16.6.0 deduped
│ ├─┬ graphql-tag@2.12.6
│ │ └── graphql@16.6.0 deduped
│ └── graphql@16.6.0 deduped
├─┬ gatsby-plugin-manifest@4.25.0
│ └─┬ gatsby-plugin-utils@3.19.0
│   └── graphql@15.8.0
├─┬ gatsby-plugin-sharp@4.25.0
│ └─┬ gatsby-plugin-utils@3.19.0
│   └── graphql@15.8.0
├─┬ gatsby-transformer-sharp@4.25.0
│ └─┬ gatsby-plugin-utils@3.19.0
│   └── graphql@15.8.0
├─┬ gatsby@4.25.1
│ ├─┬ graphql-compose@9.0.10
│ │ └─┬ graphql-type-json@0.3.2
│ │   └── graphql@16.6.0 deduped
│ └── graphql@15.8.0
└── graphql@16.6.0
```

Looks like gatsby is internally using different versions of graphql.
I have NO IDEA why this exact same configuration worked on the previous pc.
Any Idea how I can get this project to work again?

This is the package.json: https://github.com/barbalex/bb2/blob/master/package.json

After going through numerous problems upgrading gatsby projects I have become very hesitant to change anything (and have in fact migrated all the other projects away from gatsby, which immediately stopped the pain).
So the obvious thing to upgrade it all to the newest versions looks very scary to me. Especially as there is a major version upgrade there.

### Reproduction Link

https://github.com/barbalex/bb2

### Steps to Reproduce

help!

### Expected Result

help!

### Actual Result

help!

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900K
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.58)
  npmPackages:
    gatsby: 4.25.1 => 4.25.1
    gatsby-plugin-create-client-paths: 4.9.0 => 4.9.0
    gatsby-plugin-google-analytics: 4.25.0 => 4.25.0
    gatsby-plugin-manifest: 4.25.0 => 4.25.0
    gatsby-plugin-offline: 5.25.0 => 5.25.0
    gatsby-plugin-react-helmet: 5.25.0 => 5.25.0
    gatsby-plugin-sharp: 4.25.0 => 4.25.0
    gatsby-plugin-sitemap: 5.25.0 => 5.25.0
    gatsby-source-filesystem: 4.25.0 => 4.25.0
    gatsby-transformer-sharp: 4.25.0 => 4.25.0
```

### Config Flags

no

**Comment by barbalex** [comment]
Edit: On the old pc I used to use yarn. Seems that this project was not only the last to use gatsby, but also the last to use yarn. And somehow yarn mad the graphql mix work???

**Comment by barbalex** [comment]
Yeah, I installed yarn and it works.

```
PS C:\Users\alexa\bb2> yarn why graphql
├─ gatsby@npm:4.25.1
│  └─ graphql@npm:15.8.0 (via npm:^15.7.2)
│
└─ gatsby@npm:4.25.1 [145d6]
   └─ graphql@npm:15.8.0 (via npm:^15.7.2)
```

I have NO IDEA why npm and yarn behave so much different.
