### ISSUE TITLE
`key` props is omitted in Head API

### ISSUE THREAD

**Issue by just-small-potato** [gatsbyjs/gatsby#38620]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Followed the documentation [Gatsby Head API](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/) and [Adding SEO Component](https://www.gatsbyjs.com/docs/how-to/adding-common-features/adding-seo-component/#create-a-usesitemetadata-hook) to add site title and open graph tags.

The following warning is displayed in the terminal even when key is added to each children inside `Head`:
```
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <head>. See https://reactjs.org/link/warning-keys for more information.
    at title
    at HTML (/Users/code/my-gatsby-site/.cache/page-ssr/routes/render-page.js:7018:96)
```

Minimal reproduction code:
https://github.com/gatsbyjs/gatsby/files/12840412/site.zip

### Reproduction Link

https://github.com/gatsbyjs/gatsby/files/12840412/site.zip

### Steps to Reproduce

1. Run command `npm run develop` in terminal and wait until the development server to spin up
2. Open `http://localhost:8000` in any browser
3. Switch back to terminal that runs the command in step 1 and inspect the output
<img width="666" alt="Screenshot 2023-10-08 at 6 42 57 PM" src="https://github.com/gatsbyjs/gatsby/assets/68165945/7b176aac-e2df-450f-9c2d-08d703e01288">

### Expected Result

Gatsby should respect the `key` props passed to any children of `Head`. Warning should not be shown when `key` props is provided.

### Actual Result

The following warning is displayed in the terminal even when key is added to each children inside `Head`:
```
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <head>. See https://reactjs.org/link/warning-keys for more information.
    at title
    at HTML (/Users/code/my-gatsby-site/.cache/page-ssr/routes/render-page.js:7018:96)
```
<img width="666" alt="Screenshot 2023-10-08 at 6 42 57 PM" src="https://github.com/gatsbyjs/gatsby/assets/68165945/7b176aac-e2df-450f-9c2d-08d703e01288">

`Head` code:
```jsx
export const Head: HeadFC = () => {
  // useSiteMetadata() has the same code as https://www.gatsbyjs.com/docs/how-to/adding-common-features/adding-seo-component/#create-a-usesitemetadata-hook
  const { title } = useSiteMetadata();

  return (
    <>
      <title key="title">{title}</title>
      <meta key="meta-og-title" property="og:title" content={title} />
    </>
  );
}
```

### Environment

```shell
System:
    OS: macOS 13.4
    CPU: (12) arm64 Apple M2 Max
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - /var/folders/ts/fj4z6rv53mnfqn0bw3w0nvcw0000gn/T/yarn--1696762046281-0.3875366582414168/node
    Yarn: 1.22.19 - /var/folders/ts/fj4z6rv53mnfqn0bw3w0nvcw0000gn/T/yarn--1696762046281-0.3875366582414168/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
  Browsers:
    Chrome: 117.0.5938.149
    Edge: 117.0.2045.55
    Safari: 16.5
  npmPackages:
    gatsby: ^5.12.4 => 5.12.4
```

### Config Flags

```
DEV_SSR: true
PARALLEL_SOURCING: true
```

**Comment by Bilal-Shahzad** [comment]
can i be assigned to this?

**Comment by arafatamim** [comment]
I've started getting the same error for some reason:
```
 ERROR  UNKNOWN

Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <head>. See https://reactjs.org/link/warning-keys for more information.
    at script
    at HTML (/[truncated]/.cache/page-ssr/routes/render-page.js:5002:76)
 ```

**Comment by ohprettyhak** [comment]
I also encountered the same issue when enabling `DEV_SSR: true`.

- "gatsby": "^5.13.7"

Updating Gatsby to version 5.14.0 did not resolve the issue.

```
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <head>. See https://reactjs.org/link/warning-keys for more information.
    at link
```

**Comment by benomatis** [comment]
@Bilal-Shahzad do you know where this issue is coming from exactly by chance? I'm keen patching it myself if you can point to the right direction, doesn't look like a priority for the getsby team at this moment, which I understand, it's really just an annoyance, but I am keen getting rid of it 😄 .

**Comment by MikeBroders** [comment]
i guess it's caused by the Head() component.

i have a simple

`export const Head: HeadFC = (props) => (
  <title>Title</title>
);`

in my index page and getting:

`Check the top-level render call using <head>. See https://reactjs.org/link/warning-keys for more information.
    at title
    at HTML (/Volumes/Projects/dotRealities/gatsby-starter-ts-v5/.cache/page-ssr/routes/render-page.js:409:14)`

by removing the Head() component from the index page the error is not coming up.
