### ISSUE TITLE
React 19 support

### ISSUE THREAD

**Issue by Schweinepriester** [gatsbyjs/gatsby#39180]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

https://react.dev/blog/2024/12/05/react-19

### Reproduction Link

https://github.com/gatsbyjs/gatsby/blob/gatsby%405.14.0/packages/gatsby/package.json#L253

### Steps to Reproduce

1. Check https://github.com/gatsbyjs/gatsby/blob/gatsby%405.14.0/packages/gatsby/package.json#L253
2. React 19 is not matched by `^18.0.0 || ^0.0.0`
3. Probably other changes needed as well

### Expected Result

React 19 is supported

### Actual Result

React 19 is not supported

### Environment

```shell
Any
```

**Comment by CSharperMantle** [comment]
Able to confirm the incompatibility.

App fails to build w/ Gatsby 5.14.1, producing the following stacktrace:

```text
success Building HTML renderer - 62.578s
 ERROR  UNKNOWN
Cannot read properties of undefined (reading 'ContextRegistry')
  TypeError: Cannot read properties of undefined (reading 'ContextRegistry')
  - render-page.js:29242 21011
    [PROJECT]/.cache/page-ssr/routes/render-page.js:29242:461
  - render-page.js:53701 __webpack_require__
    [PROJECT]/.cache/page-ssr/routes/render-page.js:53701:42
  - render-page.js:29314 29592
    [PROJECT]/.cache/page-ssr/routes/render-page.js:29314:20
  - render-page.js:53701 __webpack_require__
    [PROJECT]/.cache/page-ssr/routes/render-page.js:53701:42
  - render-page.js:53860
    [PROJECT]/.cache/page-ssr/routes/render-page.js:53860:331
  - render-page.js:53894
    [PROJECT]/.cache/page-ssr/routes/render-page.js:53894:3
  - render-page.js:53899 Object.<anonymous>
    [PROJECT]/.cache/page-ssr/routes/render-page.js:53899:12
  [LOADER ENTRIES OMITTED...]
  - page-mode.js:108 preparePageTemplateConfigs
    [gatsby-virtual-790e62beba]/[gatsby]/dist/utils/page-mode.js:108:24

not finished Execute page configs - 0.487s
```

It seems that one of Gatsby's dependencies tries to access some React internals:

```js
/**
 * @license React
 * react-server-dom-webpack-writer.node.production.min.server.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
...
var ra=e.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED,N=ra.ContextRegistry,O=ra.ReactCurrentDispatcher;
...
```

The dependencies in included here:

https://github.com/gatsbyjs/gatsby/blob/cddc252bf4cac57486ed5f5b544d50e4a92ce769/packages/gatsby/package.json#L151

The React 19 changelog shows that they have indeed changed internal states.

<https://react.dev/blog/2024/04/25/react-19-upgrade-guide#libraries-depending-on-react-internals-may-block-upgrades>

Related lines of deps:

```json
{
    "gatsby": "^5.14.1",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
}
```

**Comment by radzionc** [comment]
Are there any plans to upgrade Gatsby to support React 19?

**Comment by JulienDefrance** [comment]
With Dependabot trying to get us on the latest react/react-dom 19.1.0, there is indeed a growing urgency in getting Gatsby to support the latest versions.

**Comment by DavidSabine** [comment]
GitHub indicates that Kyle Matthews has "committed to this repository"

But, serious question: is he committed to this repository?

<img width="988" height="1086" alt="Image" src="https://github.com/user-attachments/assets/2b126384-e602-4075-b156-939bda6a54e5" />

**Comment by lnhrdt** [comment]
I know where you're coming from @DavidSabine (I'm also frustrated enough to post here) but this isn't on Kyle Mathews. He [sold Gatsby to Netlify](https://www.gatsbyjs.com/blog/gatsby-is-joining-netlify/) a while back and co-founded something new. Good for him.

This is on Netlify and, if #38696 is any indication, things don't look great for Gatsby. In summary, in November 2023 [a Netlify founder promised](https://github.com/gatsbyjs/gatsby/issues/38696#issuecomment-1817064739) active maintenance and a forward-looking roadmap. What followed was silence from Netlify and growing disappointment from the community.

I genuinely don't get it. My best guess is they expected a wave of migrations to their platform from their "enterprise customer base," didn't see it, and silently backpedaled on their promises of continued investment. But wouldn't the bare minimum maintenance be worth it just to avoid the reputational damage? Personally, this story the first thing I'll associate with Netlify for the rest of my career.

When I saw the news this week I got kind of jealous:
https://vercel.com/blog/nuxtlabs-joins-vercel
I hope the Nuxt and Nitro communities get the kind of stewardship from Vercel that we once hoped for from Netlify. It's been something of a faceplant for us. 😬

These days, Astro's a great fit for most of the use cases Gatsby used to  cover.

**Comment by ayan4m1** [comment]
@lnhrdt Possible I'm missing something, where is the GraphQL data source/transformation layer in Astro?

**Comment by joshderochervlk-simplisafe** [comment]
> For those of us having existing Gatsby projects, though, a full rewrite doesn't seem like the preferred route.
> 
> Hopefully folks closer to this code base can manage to get it to work with React 19 and get a new version released?

Thankfully its all just a React app and migrating to a different framework isn't impossible. The first step is to disconnect from Gatsby's data layer and use a different GraphQL library. Once you've done that it's easy enough to migrate to something like React Router or Waku.

**Comment by Primajin** [comment]
Yeah but all of these advices seem to hint towards one question: Is Gatsby dead?

![Gatsby dies](https://i.makeagif.com/media/3-11-2015/9u9M3n.gif)

**Comment by chocobuckle** [comment]
I was told by a Netlify staff member a few months ago that there won't be a Gatsby 6. It's dead, folks.

**Comment by serhalp** [comment]
Hi folks. We're working on React 19 support. It's almost ready. We'll share an update in this thread when we have a canary release we can share with you all for feedback.

We're sorry for the silence on this topic (and others). We're aware that we promised Gatsby would be stable and reliable, and that not supporting React 19 nine months after its release is... not that. We will do better going forward.

Feel free to react with the 👀 emoji on this message if you'd like to try the canary release when it is ready.

Thanks for your patience

**Comment by Primajin** [comment]
First test looks very promising 🤞🏻

**Comment by DavidSabine** [comment]
I'm testing now in a large project with multiple gatsby themes as submodules in a YARN workspace. (I stopped using NPM 2 years ago due to a fatal "legacy-peer-deps" problem. Yarn "just worked" so I stuck with it.)

Architecture:

./package.json
./core/package.json
./gatsby-theme-2023/package.json (my own theme, git submodule)
./gatsby-theme-blog/package.json (my own theme, git submodule)

Updating the relevant gatsby-* modules appears to have been successful. Modules I use that have "next" versions:

"gatsby": "npm:gatsby@next",
"gatsby-plugin-emotion": "npm:gatsby-plugin-emotion@next",
"gatsby-plugin-image": "npm:gatsby-plugin-image@next",
"gatsby-plugin-sass": "npm:gatsby-plugin-sass@next",
"gatsby-plugin-sharp": "npm:gatsby-plugin-sharp@next",
"gatsby-source-filesystem": "npm:gatsby-source-filesystem@next",
"gatsby-transformer-sharp": "npm:gatsby-transformer-sharp@next",
"gatsby-plugin-mdx": "npm:gatsby-plugin-mdx@next",
"gatsby-remark-images": "npm:gatsby-remark-images@next",
"gatsby-plugin-netlify": "npm:gatsby-plugin-netlify@next",
"gatsby-plugin-sitemap": "npm:gatsby-plugin-sitemap@next",

Other critical modules I use in this build (all are up-to-date):

Stripe, Mailchimp, PostmarkApp, Cypress, Sass, Emotion, start-server-and-test, @mdex-js/react, vitest (not jest), biomejs (not eslint)

All my unit tests and cypress tests have passed with these new versions.

Will try next to upgrade to React 19.

**Comment by DavidSabine** [comment]
> I'm testing now…
> Will try next to upgrade to React 19.

Update:

Modified my package.json(s) to use react 19.2.0 and react-dom 19.2.0 (from 18.3.1).

Running tests now.

All tests pass. Here's an overview of what's been done:

`yarn && yarn clean && yarn lint && yarn test:coverage && yarn refresh-functions:G2 && yarn build && yarn workspace gatsby-theme-2023 test:headless && yarn workspace core test:headless`

* `yarn clean` = runs `gatsby clean` in all workspaces
* `yarn lint` = lints all workspaces
* `yarn test:coverage` = runs vitests in all workspaces (a few hundred tests)
* `yarn refresh-functions:G2` = rebuilds all netlify functions
* `yarn build` = builds my gatsby site
* `yarn workspace gatsby-theme-2023 test:headless` = runs cypress tests for the design system in headless mode (a few dozen tests)
* `yarn workspace core test:headless` = runs end-2-end cypress tests for the entire site including Stripe payments, Stripe customer, mailchimp intergration, postmark mail.

All tests pass. This upgrade to React 19.2.0 appears to have been successful.

@serhalp, hit me up if you have any questions or want to see for yourself. (I won't share the code directly but we could meet and screenshare.)

**Comment by katelovescode** [comment]
Steps:

1. Check for outdated dependencies

<details>
<summary><code>yarn outdated</code></summary>

```  
yarn outdated v1.22.22
warning ../package.json: No license field
info Color legend :
 "<red>"    : Major Update backward-incompatible updates
 "<yellow>" : Minor Update backward-compatible features
 "<green>"  : Patch Update backward-compatible bug fixes
Package                             Current Wanted  Latest  Package Type    URL
@fontsource/montserrat              5.1.1   5.2.8   5.2.8   dependencies    https://fontsource.org/fonts/montserrat
@fontsource/staatliches             5.1.1   5.2.8   5.2.8   dependencies    https://fontsource.org/fonts/staatliches
@fortawesome/fontawesome-svg-core   6.7.2   6.7.2   7.1.0   dependencies    https://fontawesome.com
@fortawesome/free-brands-svg-icons  6.7.2   6.7.2   7.1.0   dependencies    https://fontawesome.com
@fortawesome/free-regular-svg-icons 6.7.2   6.7.2   7.1.0   dependencies    https://fontawesome.com
@fortawesome/free-solid-svg-icons   6.7.2   6.7.2   7.1.0   dependencies    https://fontawesome.com
@fortawesome/react-fontawesome      0.2.2   0.2.6   3.1.0   dependencies    https://github.com/FortAwesome/react-fontawesome
@percy/cli                          1.30.6  1.31.4  1.31.4  dependencies    https://github.com/percy/cli#readme
@typescript-eslint/eslint-plugin    8.21.0  8.48.0  8.48.0  dependencies    https://typescript-eslint.io/packages/eslint-plugin
@typescript-eslint/parser           8.21.0  8.48.0  8.48.0  dependencies    https://typescript-eslint.io/packages/parser
autoprefixer                        10.4.20 10.4.22 10.4.22 dependencies    https://github.com/postcss/autoprefixer#readme
dayjs                               1.11.13 1.11.19 1.11.19 dependencies    https://day.js.org
dotenv                              16.4.7  16.6.1  17.2.3  dependencies    https://github.com/motdotla/dotenv#readme
eslint                              9.18.0  9.39.1  9.39.1  dependencies    https://eslint.org
gatsby                              5.14.1  5.15.0  5.15.0  dependencies    https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby#readme
gatsby-plugin-image                 3.14.0  3.15.0  3.15.0  dependencies    https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-image#readme
gatsby-plugin-postcss               6.14.0  6.15.0  6.15.0  dependencies    https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-postcss#readme
gatsby-plugin-react-helmet          6.14.0  6.15.0  6.15.0  dependencies    https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-react-helmet#readme
gatsby-source-contentful            8.15.0  8.16.0  8.16.0  dependencies    https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-contentful#readme
gatsby-transformer-remark           6.14.0  6.15.0  6.15.0  dependencies    https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-remark#readme
postcss                             8.5.1   8.5.6   8.5.6   dependencies    https://postcss.org/
prettier                            3.4.2   3.7.1   3.7.1   devDependencies https://prettier.io
react                               19.0.0  19.2.0  19.2.0  dependencies    https://react.dev/
react-dom                           19.0.0  19.2.0  19.2.0  dependencies    https://react.dev/
tailwindcss                         3.4.17  3.4.18  4.1.17  dependencies    https://tailwindcss.com
✨  Done in 1.22s.
```
</details>

2. change gatsby versions in `package.json`

<details>
<summary><code>package.json</code></summary>

```
"gatsby": "next",
"gatsby-plugin-fontawesome-css": "next",
"gatsby-plugin-html-attributes": "next",
"gatsby-plugin-image": "next",
"gatsby-plugin-percy": "next",
"gatsby-plugin-postcss": "next",
"gatsby-plugin-react-helmet": "next",
"gatsby-plugin-web-font-loader": "next",
"gatsby-source-contentful": "next",
"gatsby-transformer-remark": "next",
```
</details>

3. upgrade

<details>
<summary><code>yarn upgrade gatsby*</code></summary>

```
yarn upgrade v1.22.22
warning ../package.json: No license field
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "gatsby-plugin-fontawesome-css" that matches "next"
? Please choose a version of "gatsby-plugin-fontawesome-css" from this list: 1.2.0
Couldn't find any versions for "gatsby-plugin-html-attributes" that matches "next"
? Please choose a version of "gatsby-plugin-html-attributes" from this list: 1.0.5
Couldn't find any versions for "gatsby-plugin-percy" that matches "next"
? Please choose a version of "gatsby-plugin-percy" from this list: 1.1.0
Couldn't find any versions for "gatsby-plugin-web-font-loader" that matches "next"
? Please choose a version of "gatsby-plugin-web-font-loader" from this list: 1.0.4
[2/4] 🚚  Fetching packages...
warning bare-fs@4.0.1: The engine "bare" appears to be invalid.
warning bare-os@3.4.0: The engine "bare" appears to be invalid.
[3/4] 🔗  Linking dependencies...
warning " > @typescript-eslint/eslint-plugin@8.21.0" has unmet peer dependency "typescript@>=4.8.4 <5.8.0".
warning "@typescript-eslint/eslint-plugin > @typescript-eslint/type-utils@8.21.0" has unmet peer dependency "typescript@>=4.8.4 <5.8.0".
warning "@typescript-eslint/eslint-plugin > @typescript-eslint/utils@8.21.0" has unmet peer dependency "typescript@>=4.8.4 <5.8.0".
warning "@typescript-eslint/eslint-plugin > ts-api-utils@2.0.0" has unmet peer dependency "typescript@>=4.8.4".
warning "@typescript-eslint/parser > @typescript-eslint/typescript-estree@8.21.0" has unmet peer dependency "typescript@>=4.8.4 <5.8.0".
warning " > @typescript-eslint/parser@8.21.0" has unmet peer dependency "typescript@>=4.8.4 <5.8.0".
warning "gatsby > @gatsbyjs/reach-router@2.0.1" has incorrect peer dependency "react@18.x".
warning "gatsby > @gatsbyjs/reach-router@2.0.1" has incorrect peer dependency "react-dom@18.x".
warning "gatsby > eslint-config-react-app@6.0.0" has incorrect peer dependency "@typescript-eslint/eslint-plugin@^4.0.0".
warning "gatsby > eslint-config-react-app@6.0.0" has incorrect peer dependency "@typescript-eslint/parser@^4.0.0".
warning "gatsby > eslint-config-react-app@6.0.0" has unmet peer dependency "babel-eslint@^10.0.0".
warning "gatsby > react-server-dom-webpack@0.0.0-experimental-c8b778b7f-20220825" has incorrect peer dependency "react@0.0.0-experimental-c8b778b7f-20220825".
warning "gatsby > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning "gatsby > react-dev-utils > fork-ts-checker-webpack-plugin@6.5.3" has unmet peer dependency "typescript@>= 2.7".
warning "gatsby > babel-plugin-remove-graphql-queries@5.17.0-react19.1" has incorrect peer dependency "gatsby@^5.18.0-react19.0".
warning "gatsby > gatsby-plugin-page-creator@5.17.0-react19.1" has incorrect peer dependency "gatsby@^5.18.0-react19.0".
warning "gatsby > gatsby-plugin-utils@4.17.0-react19.1" has incorrect peer dependency "gatsby@^5.18.0-react19.0".
warning "gatsby > gatsby-plugin-typescript@5.17.0-react19.1" has incorrect peer dependency "gatsby@^5.18.0-react19.0".
warning " > gatsby-plugin-fontawesome-css@1.2.0" has incorrect peer dependency "gatsby@^4.0.0".
warning " > gatsby-plugin-fontawesome-css@1.2.0" has incorrect peer dependency "@fortawesome/fontawesome-svg-core@^1.2.0".
warning " > gatsby-plugin-image@3.17.0-next.0" has unmet peer dependency "@babel/core@^7.12.3".
warning "gatsby-plugin-postcss > postcss-loader@7.3.4" has unmet peer dependency "webpack@^5.0.0".
warning " > gatsby-source-contentful@8.18.0-next.0" has unmet peer dependency "gatsby-plugin-sharp@^5.0.0-next".
warning " > gatsby-source-contentful@8.18.0-next.0" has unmet peer dependency "sharp@^0.32.6".
warning "gatsby-source-contentful > @contentful/rich-text-react-renderer@15.22.11" has incorrect peer dependency "react@^16.8.6 || ^17.0.0 || ^18.0.0".
warning "gatsby-source-contentful > @contentful/rich-text-react-renderer@15.22.11" has incorrect peer dependency "react-dom@^16.8.6 || ^17.0.0 || ^18.0.0".
warning "gatsby-source-contentful > gatsby-source-filesystem@5.17.0-react19.1" has incorrect peer dependency "gatsby@^5.18.0-react19.0".
warning "react-helmet > react-side-effect@2.1.2" has incorrect peer dependency "react@^16.3.0 || ^17.0.0 || ^18.0.0".
warning Workspaces can only be enabled in private projects.
[4/4] 🔨  Rebuilding all packages...
success Saved lockfile.
warning Workspaces can only be enabled in private projects.
success Saved 40 new dependencies.
info Direct dependencies
├─ gatsby-plugin-fontawesome-css@1.2.0
├─ gatsby-plugin-html-attributes@1.0.5
├─ gatsby-plugin-image@3.17.0-next.0
├─ gatsby-plugin-percy@1.1.0
├─ gatsby-plugin-postcss@6.17.0-next.0
├─ gatsby-plugin-react-helmet@6.17.0-next.0
├─ gatsby-plugin-web-font-loader@1.0.4
├─ gatsby-source-contentful@8.18.0-next.0
├─ gatsby-transformer-remark@6.17.0-next.0
└─ gatsby@5.17.0-next.0
info All dependencies
├─ @expo/devcert@1.2.0
├─ @expo/sudo-prompt@9.3.2
├─ @gatsbyjs/parcel-namer-relative-to-cwd@2.17.0-next.0
├─ @pmmmwh/react-refresh-webpack-plugin@0.5.17
├─ babel-preset-gatsby@3.17.0-next.0
├─ busboy@1.6.0
├─ concat-stream@2.0.0
├─ create-gatsby@3.17.0-react19.1
├─ engine.io-client@6.6.3
├─ engine.io@6.6.4
├─ gatsby-cli@5.17.0-react19.1
├─ gatsby-graphiql-explorer@3.17.0-next.0
├─ gatsby-link@5.17.0-react19.0
├─ gatsby-parcel-config@1.17.0-next.0
diff --git a/package.json b/package.json
index cf34ee8..d882295 100644
--- a/package.json
+++ b/package.json
@@ -29,16 +29,16 @@
     "dayjs": "^1.11.13",
     "dotenv": "^16.4.7",
     "eslint": "^9.18.0",
-    "gatsby": "^5.14.1",
-    "gatsby-plugin-fontawesome-css": "^1.2.0",
-    "gatsby-plugin-html-attributes": "^1.0.5",
-    "gatsby-plugin-image": "^3.14.0",
-    "gatsby-plugin-percy": "^1.1.0",
-    "gatsby-plugin-postcss": "^6.14.0",
-    "gatsby-plugin-react-helmet": "^6.14.0",
-    "gatsby-plugin-web-font-loader": "^1.0.4",
-    "gatsby-source-contentful": "^8.15.0",
-    "gatsby-transformer-remark": "^6.14.0",
+    "gatsby": "next",
+    "gatsby-plugin-fontawesome-css": "next",
+    "gatsby-plugin-html-attributes": "next",
+    "gatsby-plugin-image": "next",
+    "gatsby-plugin-percy": "next",
+    "gatsby-plugin-postcss": "next",
+    "gatsby-plugin-react-helmet": "next",
+    "gatsby-plugin-web-font-loader": "next",
+    "gatsby-source-contentful": "next",
+    "gatsby-transformer-remark": "next",
     "jsonp": "^0.2.1",
     "postcss": "^8.5.1",
     "react": "^19.0.0",
diff --git a/yarn.lock b/yarn.lock
├─ gatsby-plugin-fontawesome-css@1.2.0
├─ gatsby-plugin-html-attributes@1.0.5
├─ gatsby-plugin-image@3.17.0-next.0
├─ gatsby-plugin-page-creator@5.17.0-react19.1
├─ gatsby-plugin-percy@1.1.0
├─ gatsby-plugin-postcss@6.17.0-next.0
├─ gatsby-plugin-react-helmet@6.17.0-next.0
├─ gatsby-plugin-typescript@5.17.0-react19.1
├─ gatsby-plugin-web-font-loader@1.0.4
├─ gatsby-react-router-scroll@6.17.0-react19.0
├─ gatsby-script@2.17.0-react19.0
├─ gatsby-sharp@1.17.0-next.0
├─ gatsby-source-contentful@8.18.0-next.0
├─ gatsby-source-filesystem@5.17.0-react19.1
├─ gatsby-transformer-remark@6.17.0-next.0
├─ gatsby-worker@2.17.0-next.0
├─ gatsby@5.17.0-next.0
├─ mkdirp@0.5.6
├─ multer@2.0.2
├─ react-refresh@0.14.2
├─ socket.io-client@4.8.1
├─ socket.io@4.8.1
├─ webpack-virtual-modules@0.6.2
├─ webpack@5.98.0
├─ xmlhttprequest-ssl@2.1.2
└─ xtend@4.0.2
✨  Done in 30.52s.
```
</details>

4. Let builds run (my app doesn't have tests; it's just a personal blog and I don't care enough to do that work, but I do run Percy visual diff tool)

<img width="862" height="387" alt="Image" src="https://github.com/user-attachments/assets/fefad7f5-ad5c-4533-956c-7e345a11d020" />

I had already upgraded to React19 and my builds just failed and it never deployed out.  So rather than downgrade and upgrade, I did the gastby upgrade on top of it.

My deploy to Netlify was successful after these steps.  I'm having some compatibility issues with *other* dependency updates (dependabot PRs are failing seemingly for a tailwind problem, so I'm assuming it's not related).  I'll do some more work on it tomorrow and see if I come up with anything.

**Comment by AntonPalmqvist** [comment]
I too have upgraded my Gatsby project now, without any issues.
Thanks for doing this!

**Comment by serhalp** [comment]
Thank you for helping test @CSharperMantle! You can safely ignore this. It's a quirk of how the pre-release versions were published (I had initially published with the `react19` preid and then again under `next`, but confusingly [semver pre-release precedence rules](https://semver.org/#spec-item-11) state that e.g. `5.17.0-react19.1 > 5.17.0-next.1` because `r > n` 😶 so the former gets picked up by some transitive deps).

All these versions are actually the same, and this quirk won't carry over to the `@latest` releases.

**Comment by AntonPalmqvist** [comment]
> 
> Are you (or anyone else) able to confirm that this occurs with `@next` + React 18?

I can't use @next on React 18. I get this error on a production build:
```
 ERROR #98123  WEBPACK.BUILD-JAVASCRIPT

Generating JavaScript bundles failed

export 'use' (imported as 'o') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, act, cloneElement, createContext, createElement, createFactory, createRef, forwardRef,
isValidElement, lazy, memo, startTransition, unstable_act, useCallback, useContext, useDebugValue, useDeferredValue, useEffect, useId, useImperativeHandle, useInsertionEffect, useLayoutEffect, useMemo, useReducer, useRef, useState, useSyncExternalStore, useTransition, version)
```

On React 19 it builds just fine.

Thanks for working on this btw! I'm so happy we still get Gatsby support.

**Comment by MonstraG** [comment]
Updated to gatsby@next (`"gatsby": "5.17.0-next.0"`), left react at 18 (including the `react-server-dom-webpack` override), reproduced broken titles.

Tried `pnpm i --shaimfully-hoist`, didn't help.

**Comment by serhalp** [comment]
@Dhanupractical would you be able to share a minimal reproduction of the issues you're encountering with gatsby-source-graphql?

**Comment by benoror** [comment]
When using "gatsby-source-filesystem" (along with decap-cms-app, related: https://github.com/decaporg/decap-cms/pull/7463) I'm getting the following error:

```
 ERROR  UNKNOWN

Missing onError handler for invocation 'building-schema', error was 'Error: Cannot create as TypeComposer the following value:
  GraphQLScalarType({ name: "Date", description: "A date string, such as 2007-12-03, compliant with the ISO 8601 standard for
representation of dates and times using the Gregorian calendar.", specifiedByURL: undefined, serialize: [function String], parseValue:
[function String], parseLiteral: [function parseLiteral], extensions: {  }, astNode: undefined, extensionASTNodes: [] }).'. Stacktrace
was 'Error: Cannot create as TypeComposer the following value:
  GraphQLScalarType({ name: "Date", description: "A date string, such as 2007-12-03, compliant with the ISO 8601 standard for
representation of dates and times using the Gregorian calendar.", specifiedByURL: undefined, serialize: [function String], parseValue:
[function String], parseLiteral: [function parseLiteral], extensions: {  }, astNode: undefined, extensionASTNodes: [] }).
    at SchemaComposer.createTempTC
(/Users/benoror/code/benoror/TylerVawserSite/node_modules/graphql-compose/lib/SchemaComposer.js:367:15)
    at SchemaComposer.createTC (/Users/benoror/code/benoror/TylerVawserSite/node_modules/graphql-compose/lib/SchemaComposer.js:326:89)
    at SchemaComposer.add (/Users/benoror/code/benoror/TylerVawserSite/node_modules/graphql-compose/lib/SchemaComposer.js:594:25)
    at createSchemaComposer (/Users/benoror/code/benoror/TylerVawserSite/node_modules/gatsby/dist/schema/schema-composer.js:21:18)
    at build (/Users/benoror/code/benoror/TylerVawserSite/node_modules/gatsby/dist/schema/index.js:153:26)
    at async buildSchema (/Users/benoror/code/benoror/TylerVawserSite/node_modules/gatsby/dist/services/build-schema.js:19:3)'

⠸ building schema
```

Getting stuck at `building schema`

Fixed resolution to `"graphql": "16.0.0"` as proposed here: https://stackoverflow.com/a/76353832

**Comment by Huaian666** [comment]
came here to request the same thing. this is basically the only thing missing from an otherwise perfect lib

**Comment by serhalp** [comment]
@Huaian666 What are you referring to?

**Comment by MWhiteFearless** [comment]
Since React 19 is now supported, can the peer dependencies for `@gatsbyjs/reach-router` be updated to include react 19? Currently, my project has to override react 19 in our package.json because we use @gatsbyjs/reach-router and its peer dependencies only include React 18.
