### ISSUE TITLE
Problem installing Gatsby in windows 7

### ISSUE THREAD

**Issue by ProphetDaniel** [gatsbyjs/gatsby#424]
Trying to install Gatsby in Windows 7 I got the following warnings:
Any idea why? What should I do to make it work?

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
C:\Users\SouzaDan\AppData\Roaming\npm\gatsby -> C:\Users\SouzaDan\AppData\Roamin
g\npm\node_modules\gatsby\bin\gatsby.js
C:\Users\SouzaDan\AppData\Roaming\npm
`-- gatsby@0.12.5
  `-- postcss-cssnext@2.7.0
    `-- postcss-color-function@2.0.1
      `-- css-color-function@1.3.0
        `-- color@0.11.3
          `-- color-convert@1.5.0

npm WARN optional Skipping failed optional dependency /gatsby/chokidar/fsevents:

npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.14
```

**Comment by MoOx** [comment]
gatsby not gastby

**Comment by ProphetDaniel** [comment]
@MoOx I've noticed, updated and got the warnings above as last edit I made.

**Comment by MoOx** [comment]
Warning should not be a problem

**Comment by jquense** [comment]
these are just warnings for the various transient dependencies.  npm always has this sort of noise, doubly so on Windows where fs events is incompatible, it's fine though because it's an _optional_ dependency. nothing in the warnings here suggests gatsby didn't  install correctly

**Comment by ProphetDaniel** [comment]
Ok, so it looks it installed well. That is something.
Now after I issue npm install command in the [ethereumclassic.github.io sources](https://github.com/ethereumclassic/ethereumclassic.github.io/tree/source) branch the following errors appear. I tought they had to do with Gatsby.

```
> fsevents@1.0.14 install C:\Users\SouzaDan\Documents\GitHub\ethereumclassic.git
hub.io\node_modules\fsevents
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amaz
onaws.com/v1.0.14/fse-v1.0.14-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@6.5.
0 (node-v48 ABI) (falling back to source compile with node-gyp)
Traceback (most recent call last):
  File "C:\Users\SouzaDan\Documents\GitHub\ethereumclassic.github.io\node_module
s\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\SouzaDan\Documents\GitHub\ethereumclassic.github.io\node_module
s\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\SouzaDan\Documents\GitHub\ethereumclassic.github.io\node_module
s\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\SouzaDan\Documents\GitHub\ethereumclassic.github.io\node_module
s\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Users\SouzaDan\Documents\GitHub\ethereumclassic.github.io\node_module
s\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2003, in GenerateOutput
    sln_projects, project_objects, flat=msvs_version.FlatSolution())
  File "C:\Users\SouzaDan\Documents\GitHub\ethereumclassic.github.io\node_module
s\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1762, in _GatherSolutionFolder
s
    return _DictsToFolders('', root, flat)
  File "C:\Users\SouzaDan\Documents\GitHub\ethereumclassic.github.io\node_module
s\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1715, in _DictsToFolders
    for folder, contents in bucket.iteritems():
AttributeError: 'MSVSProject' object has no attribute 'iteritems'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\SouzaDan\Documents\GitHub\
ethereumclassic.github.io\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\SouzaDan\\FirmwareDevTools\\Compilers\\nodeJs\\node
.exe" "C:\\Users\\SouzaDan\\Documents\\GitHub\\ethereumclassic.github.io\\node_m
odules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=
C:\\Users\\SouzaDan\\Documents\\GitHub\\ethereumclassic.github.io\\node_modules\
\fsevents\\lib\\binding\\Release\\node-v48-win32-x64\\fse.node" "--module_name=f
se" "--module_path=C:\\Users\\SouzaDan\\Documents\\GitHub\\ethereumclassic.githu
b.io\\node_modules\\fsevents\\lib\\binding\\Release\\node-v48-win32-x64" "--pyth
on=C:\\Users\\SouzaDan\\FirmwareDevTools\\Compilers\\Python\\2.7.12\\python.exe"

gyp ERR! cwd C:\Users\SouzaDan\Documents\GitHub\ethereumclassic.github.io\node_m
odules\fsevents
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Users\SouzaDan\FirmwareDevT
ools\Compilers\nodeJs\node.exe C:\Users\SouzaDan\Documents\GitHub\ethereumclassi
c.github.io\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build
--module=C:\Users\SouzaDan\Documents\GitHub\ethereumclassic.github.io\node_modul
es\fsevents\lib\binding\Release\node-v48-win32-x64\fse.node --module_name=fse --
module_path=C:\Users\SouzaDan\Documents\GitHub\ethereumclassic.github.io\node_mo
dules\fsevents\lib\binding\Release\node-v48-win32-x64 --python=C:\Users\SouzaDan
\FirmwareDevTools\Compilers\Python\2.7.12\python.exe' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\SouzaDan\Docum
ents\GitHub\ethereumclassic.github.io\node_modules\fsevents\node_modules\node-pr
e-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Users\\SouzaDan\\FirmwareDevTools\\Compilers\\nod
eJs\\node.exe" "C:\\Users\\SouzaDan\\Documents\\GitHub\\ethereumclassic.github.i
o\\node_modules\\fsevents\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "insta
ll" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\SouzaDan\Documents\GitHub\ethereumclassic.github.
io\node_modules\fsevents
node-pre-gyp ERR! node -v v6.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok
Failed to execute 'C:\Users\SouzaDan\FirmwareDevTools\Compilers\nodeJs\node.exe
C:\Users\SouzaDan\Documents\GitHub\ethereumclassic.github.io\node_modules\node-g
yp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\SouzaDan\Docu
ments\GitHub\ethereumclassic.github.io\node_modules\fsevents\lib\binding\Release
\node-v48-win32-x64\fse.node --module_name=fse --module_path=C:\Users\SouzaDan\D
ocuments\GitHub\ethereumclassic.github.io\node_modules\fsevents\lib\binding\Rele
ase\node-v48-win32-x64 --python=C:\Users\SouzaDan\FirmwareDevTools\Compilers\Pyt
hon\2.7.12\python.exe' (1)
npm WARN docs-site@1.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\SouzaDan\\FirmwareDevTools\\Compilers\\nodeJs\\node.ex
e" "C:\\Users\\SouzaDan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.
js" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! fsevents@1.0.14 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fsevents@1.0.14 install script 'node-pre-gyp install --fa
llback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fsevents
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\SouzaDan\Documents\GitHub\ethereumclassic.github.io\npm-de
bug.log
```

**Comment by KyleAMathews** [comment]
No clue about windows build errors.

But cool website! Would love it if you @ProphetDaniel or @dax-classix would create a PR to add the site to the README.md.

**Comment by ProphetDaniel** [comment]
Just created the Pull request [Gatsby pull request number 427](https://github.com/gatsbyjs/gatsby/pull/427)
