### ISSUE TITLE
Error running yarn develop

### ISSUE THREAD

**Issue by huchenme** [gatsbyjs/gatsby#4283]
After upgrading a few packages, I run into this issue when I run `yarn develop`

```sh
error There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  39 |   }
  40 | 
> 41 |   const setPreBodyComponents = components => {
     |                                              ^
  42 |     preBodyComponents = preBodyComponents.concat(components)
  43 |   }
  44 | 


  WebpackError: 
  
  - develop-static-entry.js:41 Object.module.exports
    .cache/develop-static-entry.js:41:46
  

error An unexpected error occurred: "Command failed.
```

Source code here: https://github.com/huchenme/huchenme.github.io/tree/upgrade

Steps to reproduce:

```sh
git clone git@github.com:huchenme/huchenme.github.io.git
git checkout upgrade
yarn install
yarn develop
```

Thanks for the help!

**Comment by KyleAMathews** [comment]
It looks like the storybook dependencies are installing a different version of babel or somehow affecting Gatsby's babel setup...

I removed the storybook dependencies (and added `react-helmet` which was missing) and the build succeeded.

**Comment by KyleAMathews** [comment]
This is the error I saw with storybook installed:

```shell
/p/t/huchenme.github.io (upgrade ⚡☡=) gatsby build
success delete html and css files from previous builds — 0.037 s
success open and validate gatsby-config.js — 0.008 s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's not any stale
data
success copy gatsby files — 0.023 s
success onPreBootstrap — 0.902 s
success source and transform nodes — 0.173 s
success building schema — 0.358 s
success createLayouts — 0.013 s
success createPages — 0.029 s
success createPagesStatefully — 0.034 s
success onPreExtractQueries — 0.001 s
success update schema — 0.184 s
success extract queries from components — 0.072 s
success run graphql queries — 0.061 s
success write out page data — 0.012 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.001 s

info bootstrap finished - 4.748 s

success Building CSS — 0.723 s

error Generating JavaScript bundles failed


  Error: ./.cache/production-app.js
  Module build failed: TypeError: fileSystem.statSync is not a function
      at module.exports (/private/tmp/huchenme.github.io/node_modules/babel-loader/lib/utils/exists.js:7:25)
      at find (/private/tmp/huchenme.github.io/node_modules/babel-loader/lib/resolve-rc.js:13:9)
      at Object.module.exports (/private/tmp/huchenme.github.io/node_modules/babel-loader/lib/index.js:113:132)
```

**Comment by huchenme** [comment]
@KyleAMathews Thanks! May I know how did you debug and find the above error message?
