### ISSUE TITLE
Run gatsby SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by lnkdel** [gatsbyjs/gatsby#4528]
I get an error when I run the following command on ubuntu server
gatsby new blog https://github.com/gatsbyjs/gatsby-starter-blog

Details are as follows：
/usr/local/lib/node_modules/gatsby-cli/node_modules/yurnalist/dist/reporters/console/console-reporter.js:111
      cols[i] = Math.max(...widths);
                         ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at _load_consoleReporter (/usr/local/lib/node_modules/gatsby-cli/node_modules/yurnalist/dist/index.js:6:52)
    at createReporter (/usr/local/lib/node_modules/gatsby-cli/node_modules/yurnalist/dist/index.js:19:45)
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby-cli/node_modules/yurnalist/dist/index.js:33:18)

**Comment by m-allanson** [comment]
What version of node are you using?

**Comment by DemGiran** [comment]
@m-allanson which version of node should be used? Is node v10 safe?

**Comment by KyleAMathews** [comment]
It depends on your code. Each new version of node supports new js syntax. But node 10 is the newest so would support the most.

Gatsby itself supports back to node 6. But for your own code

**Comment by KyleAMathews** [comment]
Oops didn't mean to post that. Just noticed the stack Trace is for code in node_modules. But in any case, generally newer is better so go with node 10.
