### ISSUE TITLE
`createErrorFromString` is broken

### ISSUE THREAD

**Issue by vjpr** [gatsbyjs/gatsby#4657]
https://github.com/gatsbyjs/gatsby/blob/1bb179e9f55dcb7d396ed8c616366611bf621222/packages/gatsby-cli/src/reporter/errors.js#L53-L74

## Description

Describe the issue or the enhancement that you want to see.

### Steps to reproduce

- Delete a package that gatsby depends on such as `babel-core` from your `node_modules`.

### Expected result

These are the webpack errors that were hidden. They should be passed along...

```
[ 'Cannot find module \'babel-core\'',
  'Error: Source file not found: "render-page.js"\n    at Compilation.<anonymous> (/Users/Vaughan/dev-live/gatsby-site-1/node_modules/.registry.npmjs.org/static-site-generator-webpack-plugin/3.4.1/node_modules/static-site-generator-webpack-plugin/index.js:36:17)\n    at Compilation.applyPluginsAsync (/Users/Vaughan/dev-live/gatsby-site-1/node_modules/.registry.npmjs.org/tapable/0.1.10/node_modules/tapable/lib/Tapable.js:71:13)\n    at Compilation.<anonymous> (/Users/Vaughan/dev-live/gatsby-site-1/node_modules/.registry.npmjs.org/webpack/1.15.0/node_modules/webpack/lib/Compilation.js:572:10)\n    at Compilation.applyPluginsAsync (/Users/Vaughan/dev-live/gatsby-site-1/node_modules/.registry.npmjs.org/tapable/0.1.10/node_modules/tapable/lib/Tapable.js:60:69)\n    at Compilation.<anonymous> (/Users/Vaughan/dev-live/gatsby-site-1/node_modules/.registry.npmjs.org/webpack/1.15.0/node_modules/webpack/lib/Compilation.js:567:9)\n    at Compilation.next (/Users/Vaughan/dev-live/gatsby-site-1/node_modules/.registry.npmjs.org/tapable/0.1.10/node_modules/tapable/lib/Tapable.js:67:11)\n    at ExtractTextPlugin.<anonymous> (/Users/Vaughan/dev-live/gatsby-site-1/node_modules/.registry.npmjs.org/extract-text-webpack-plugin/1.0.1/webpack@1.15.0/node_modules/extract-text-webpack-plugin/index.js:309:4)\n    at Compilation.applyPluginsAsync (/Users/Vaughan/dev-live/gatsby-site-1/node_modules/.registry.npmjs.org/tapable/0.1.10/node_modules/tapable/lib/Tapable.js:71:13)\n    at Compilation.<anonymous> (/Users/Vaughan/dev-live/gatsby-site-1/node_modules/.registry.npmjs.org/webpack/1.15.0/node_modules/webpack/lib/Compilation.js:563:8)\n    at Compilation.next (/Users/Vaughan/dev-live/gatsby-site-1/node_modules/.registry.npmjs.org/tapable/0.1.10/node_modules/tapable/lib/Tapable.js:67:11)\n    at ExtractTextPlugin.<anonymous> (/Users/Vaughan/dev-live/gatsby-site-1/node_modules/.registry.npmjs.org/extract-text-webpack-plugin/1.0.1/webpack@1.15.0/node_modules/extract-text-webpack-plugin/index.js:285:5)\n    at /Users/Vaughan/dev-live/gatsby-site-1/node_modules/.registry.npmjs.org/async/1.5.2/node_modules/async/lib/async.js:52:16\n    at Object.async.forEachOf.async.eachOf (/Users/Vaughan/dev-live/gatsby-site-1/node_modules/.registry.npmjs.org/async/1.5.2/node_modules/async/lib/async.js:236:30)\n    at Object.async.forEach.async.each (/Users/Vaughan/dev-live/gatsby-site-1/node_modules/.registry.npmjs.org/async/1.5.2/node_modules/async/lib/async.js:209:22)\n    at ExtractTextPlugin.<anonymous> (/Users/Vaughan/dev-live/gatsby-site-1/node_modules/.registry.npmjs.org/extract-text-webpack-plugin/1.0.1/webpack@1.15.0/node_modules/extract-text-webpack-plugin/index.js:237:10)\n    at Compilation.applyPluginsAsync (/Users/Vaughan/dev-live/gatsby-site-1/node_modules/.registry.npmjs.org/tapable/0.1.10/node_modules/tapable/lib/Tapable.js:71:13)\n    at Compilation.seal (/Users/Vaughan/dev-live/gatsby-site-1/node_modules/.registry.npmjs.org/webpack/1.15.0/node_modules/webpack/lib/Compilation.js:525:7)\n    at Compiler.<anonymous> (/Users/Vaughan/dev-live/gatsby-site-1/node_modules/.registry.npmjs.org/webpack/1.15.0/node_modules/webpack/lib/Compiler.js:397:15)\n    at /Users/Vaughan/dev-live/gatsby-site-1/node_modules/.registry.npmjs.org/tapable/0.1.10/node_modules/tapable/lib/Tapable.js:103:11\n    at Compilation.<anonymous> (/Users/Vaughan/dev-live/gatsby-site-1/node_modules/.registry.npmjs.org/webpack/1.15.0/node_modules/webpack/lib/Compilation.js:445:10)\n    at Compilation.errorAndCallback (/Users/Vaughan/dev-live/gatsby-site-1/node_modules/.registry.npmjs.org/webpack/1.15.0/node_modules/webpack/lib/Compilation.js:344:3)\n    at Compilation.<anonymous> (/Users/Vaughan/dev-live/gatsby-site-1/node_modules/.registry.npmjs.org/webpack/1.15.0/node_modules/webpack/lib/Compilation.js:400:12)' ]
```

### Actual result

![screen shot 2018-03-22 at 4 29 17 pm](https://user-images.githubusercontent.com/281413/37780059-31e46286-2dee-11e8-8863-5e289e9f8e00.png)

### Environment

* Gatsby version (`npm list gatsby`): gatsby@1.9.239
* gatsby-cli version (`gatsby --version`): 1.1.47
* Node.js version: 8.10.0
* Operating System: macOS

### File contents (if changed):

`gatsby-config.js`: 
`package.json`: 
`gatsby-node.js`: 
`gatsby-browser.js`: 
`gatsby-ssr.js`:

**Comment by KyleAMathews** [comment]
Thanks for the issue! Let's definitely get this fixed. Hiding errors isn't a great idea :-)

Seems like the problem isn't there but where `createErrorFromString` is called — i.e. the caller should check if what it's passing to `createErrorFromString` is actually a string. If it's an array, it should loop over the array first.

Can you add a console.trace() to `createErrorFromString` to see who the caller is and then PR a fix there to check if the error is an array before passing it in?

**Comment by vjpr** [comment]
Caller: https://github.com/gatsbyjs/gatsby/blob/1d48ad4ffa318c7b768b61dfd7abbabb191764f3/packages/gatsby/src/commands/develop-html.js#L29-L33

**Comment by KyleAMathews** [comment]
Ok cool! Does looping over the errors there produce the error output you wanted? You can setup a dev environment for Gatsby by following the instructions here: https://www.gatsbyjs.org/docs/how-to-contribute/

**Comment by vjpr** [comment]
This doesn't work.

```
                if (stats.hasErrors()) {
                  var webpackErrors = stats.toJson().errors;
                  let errStr
                  if (Array.isArray(webpackErrors)) {
                    errStr = webpackErrors.map(e => {
                      //return e
                      return createErrorFromString(e, `${outputFile}.map`)
                    }).join('\n')
                    console.log(errStr)
                  } else {
                    errStr = webpackErrors
                  }
                  return reject(errStr);
                }
```

Returning just the webpack error is better.

**Comment by jquense** [comment]
This may have to to with the most recent change to the error reporter?
