### ISSUE TITLE
Cannot find module `dist/bin/cli.js` when trying to use the command after global installation

### ISSUE THREAD

**Issue by account-archived-270316** [gatsbyjs/gatsby#511]
I'm using zsh on a macOS (El Captain 10.11.6). npm version: 3.10.8. node version: v6.8.1.

I just did a `npm install -g gatsby`. But I wasn't able to use the command `gatsby`. It always gives me an error with `dist/bin/cli.js`.

```
A local install of Gatsby was not found.
Generally you should save Gatsby as a site dependency e.g. npm install --save gatsby
Continuing with global install.

module.js:471
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/gatsby/dist/bin/cli.js'
  at Function.Module._resolveFilename (module.js:469:15)
  at Function.Module._load (module.js:417:25)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at loadGatsby (/usr/local/lib/node_modules/gatsby/bin/gatsby.js:30:3)
  at /usr/local/lib/node_modules/gatsby/bin/gatsby.js:44:5
  at LOOP (fs.js:1758:14)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

when i cd into `/usr/local/lib/node_modules/gatsby` and ls I don't see any folder named `dist` at all:

```
[gatsby] ls
CONTRIBUTING.md README.md       interfaces      node_modules    scripts
LICENSE         bin             lib             package.json    test
```

**Comment by account-archived-270316** [comment]
shouldn't it look for `cli` in `lib/bin`?

**Comment by account-archived-270316** [comment]
alright. problem solved. apparently I had cloned this repo into `gatsby` and in the same dir I did `npm install -g gatsby` so it installed my local copy of gatsby where it has gitignored `dist` so I don't have `dist` in `/usr/local/lib/node_modules/gatsby/`.
