### ISSUE TITLE
failed at enerating HTML on run deploy script

### ISSUE THREAD

**Issue by amazingBastard** [gatsbyjs/gatsby#514]
I'm getting an error trying to deploy a site. I built this site off the drunken blog project starter. Any ideas what's causing the issue? Thanks!

```
Failed at generating HTML

/Users/username/Projects/gatsby-app/node_modules/gatsby/dist/bin/cli.js:52
      throw err;
      ^
Error: ReferenceError: window is not defined
    at Object.<anonymous> (render-page.js:38477:4)
    at Object.defineProperty.value (render-page.js:38479:31)
    at __webpack_require__ (render-page.js:30:30)
    at Object.soundManager (render-page.js:31940:23)
    at __webpack_require__ (render-page.js:30:30)
    at Object.defineProperty.value (render-page.js:31809:20)
    at __webpack_require__ (render-page.js:30:30)
    at Object.defineProperty.value (render-page.js:30253:15)
    at __webpack_require__ (render-page.js:30:30)
    at module.exports (render-page.js:25468:17)
```

**Comment by KyleAMathews** [comment]
You have code (either your own or a module you're using) which is referencing the `window` object. This fails when server rendering as you're not in a browser so window doesn't exist. This is a fairly common problem. The solution is to run code references to the window in `componentDidMount` where you can be sure you're now in a browser.

**Comment by amazingBastard** [comment]
Ok got it. Thanks a lot for the help.
