### ISSUE TITLE
Gatsby develop gets stuck on "success write out redirect data"

### ISSUE THREAD

**Issue by cbillowes** [gatsbyjs/gatsby#5309]
## Description

When I execute `npm run develop` then I see the following printed to the console. It gets stuck on `success write out redirect data`. 

This was was working yesterday so I think I may have lost an environment variable or a setting has changed somewhere but I don't know where or how.

### Steps to reproduce

I can reproduce it locally by executing `rm -rf .cache && rm -rf public && gatsby develop`

### Expected result

It is supposed to execute each step and load a web server so that I can I browse.

### Actual result

```
rm -rf .cache && rm -rf public && gatsby develop
success delete html files from previous builds — 0.007 s
success open and validate gatsby-config.js — 0.012 s
success copy gatsby files — 0.063 ssuccess onPreBootstrap — 0.011 s
success source and transform nodes — 0.958 s
success building schema — 0.903 s
success createLayouts — 0.080 s
success createPages — 2.419 s
success createPagesStatefully — 0.139 s
success onPreExtractQueries — 0.002 s
success update schema — 0.378 s
success extract queries from components — 0.271 s
success run graphql queries — 2.357 s
success write out page data — 0.016 s
success write out redirect data — 0.002 s
```

When I break the execution I see the following
```
npm verb lifecycle project@1.0.5~develop: unsafe-perm in lifecycle true
npm verb lifecycle project@1.0.5~develop: PATH: c:\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\<PROJECT>\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;c:\nodejs\;C:\Program Files\Git\cmd;C:\Users\<USER>\AppData\Roaming\npm;C:\Users\<USER>\AppData\Local\Yarn\bin
npm verb lifecycle project@1.0.5~develop: CWD: C:\<PROJECT>
npm info lifecycle project@1.0.5~postdevelop: corporate-programmer@1.0.5
npm verb exit [ 0, true ]
npm info ok
```

### Environment

* Gatsby version (`npm list gatsby`): gatsby@1.9.149
* gatsby-cli version (`gatsby --version`): 1.9.259
* Node.js version: v9.5.0
* Operating System: Microsoft Windows 10 Enterprise 10.0.16299 N/A Build 16299

### File contents (attached):

[package.zip](https://github.com/gatsbyjs/gatsby/files/1978647/package.zip)

`gatsby-config.js`
`package.json`
`gatsby-node.js`
`gatsby-browser.js`: N/A
`gatsby-ssr.js`: N/A

**Comment by cbillowes** [comment]
`gatsby develop` works. It's `rm -rf .cache && rm -rf public && gatsby develop` that is causing a problem all of a sudden.

**Comment by KyleAMathews** [comment]
Can you reproduce this on a fresh site?

**Comment by dialnco** [comment]
Hi @cbillowes! I had the exact same issue yesterday! Today I just removed my `package-lock.json` and my `node_modules` directory, did a fresh `npm install` and things went back to normal. 
Give it a shot and report back!

**Comment by cbillowes** [comment]
@KyleAMathews It seems to work on a fresh site. @dialnco, your suggestion fixed it. I wonder what caused the conflict?

**Comment by cbillowes** [comment]
I wonder if we should mark this as closed though. What do you think?

**Comment by pieh** [comment]
@cbillowes agree :)

**Comment by mohoff** [comment]
I'm having the same problem but the steps above don't fix it. It hangs consistently when i run a docker container with this sample Dockerfile:

```
FROM node:10

RUN yarn global add gatsby-cli

COPY . .
RUN rm ./yarn.lock
RUN rm -rf ./node_modules
RUN rm -rf ./.cache
RUN rm -rf ./public
RUN yarn install

EXPOSE 8000
CMD ["gatsby", "develop", "-H", "0.0.0.0"] # workaround for broken `gatsby build && gatsby serve`
```

Is something wrong with these steps or does it help to narrow this issue down?

**Comment by mohoff** [comment]
Ah this step actually finished after 12mins followed by an error:

```
success onPreExtractQueries - 0.010 s
success update schema - 0.109 s
success extract queries from components - 0.202 s
success run static queries - 11.445 s — 1/1 0.09 queries/second
success run page queries - 0.890 s — 5/5 5.64 queries/second
success write out page data - 0.009 s
success write out redirect data - 0.003 s
⠀
success Build manifest and related icons - 0.361 s
success onPostBootstrap - 0.377 s
⠀
info bootstrap finished - 736.092 s
⠀
 DONE  Compiled successfully in 6925ms10:41:04 PM
⠀
⠀
You can now view photoblog in the browser.
⠀
  Local:            http://0.0.0.0:8000/
  On Your Network:  http://172.17.0.2:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://0.0.0.0:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use npm run build
⠀

/usr/local/share/.config/yarn/global/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: EPERM: operation not permitted, scandir '/proc/1/map_files/263f000-2641000'
    at Object.readdirSync (fs.js:790:3)
    at GlobSync._readdir (/node_modules/glob/sync.js:288:41)
    at GlobSync._readdirInGlobStar (/node_modules/glob/sync.js:267:20)
    at GlobSync._readdir (/node_modules/glob/sync.js:276:17)
    at GlobSync._processReaddir (/node_modules/glob/sync.js:137:22)
    at GlobSync._process (/node_modules/glob/sync.js:132:10)
    at GlobSync._processGlobStar (/node_modules/glob/sync.js:380:10)
    at GlobSync._process (/node_modules/glob/sync.js:130:10)
    at GlobSync._processGlobStar (/node_modules/glob/sync.js:383:10)
    at GlobSync._process (/node_modules/glob/sync.js:130:10)
    at GlobSync._processGlobStar (/node_modules/glob/sync.js:383:10)
    at GlobSync._process (/node_modules/glob/sync.js:130:10)
    at GlobSync._processReaddir (/node_modules/glob/sync.js:207:10)
    at GlobSync._process (/node_modules/glob/sync.js:132:10)
    at new GlobSync (/node_modules/glob/sync.js:48:10)
    at Function.globSync [as sync] (/node_modules/glob/sync.js:26:10)
```
