### ISSUE TITLE
Build failing on 'buffer without document'

### ISSUE THREAD

**Issue by SpencerCDixon** [gatsbyjs/gatsby#544]
Running into an issue when I try building my site.  It keeps throwing this error:

```
> gatsby-starter-default@1.0.0 build /Users/spence/apps/spencercdixon
> gatsby build

Generating CSS
Generating Static HTML
Failed at generating HTML

/Users/spence/apps/spencercdixon/node_modules/gatsby/dist/bin/cli.js:52
      throw err;
      ^
Error: Error: Cannot automatically buffer without a document
    at injectGeneratedCSSOnce (render-page.js:34736:24)
    at injectStyleOnce (render-page.js:34754:10)
    at injectAndGetClassName (render-page.js:34830:6)
    at css (render-page.js:34588:55)
    at NavLink (render-page.js:33348:38)
    at ReactCompositeComponentMixin._constructComponentWithoutOwner (render-page.js:13894:15)
    at ReactCompositeComponentMixin._constructComponent (render-page.js:13870:20)
    at ReactCompositeComponentMixin.mountComponent (render-page.js:13773:22)
    at Object.ReactReconciler.mountComponent (render-page.js:6838:36)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (render-page.js:12984:45),Error: Cannot automatically buffer without a document
```

Not really sure why this might be happening or where i'd go to try and fix it.  If anyone has any insights that would be much appreciated :)

**Comment by SpencerCDixon** [comment]
Looks like it might be failing from aphrodite based on this line: `    at css (render-page.js:34588:55)` is aphro not compatible with this?

**Comment by KyleAMathews** [comment]
Looks like this error:

https://github.com/Khan/aphrodite/issues/33

So... Aphrodite might not work so well with 0.x actually. For 1.0 I've added APIs so you can add the necessary code for extracting out styles while server rendering and extracting them in the head. If you look at the source for this 1.0 site you can see in the `<head>` a `<style>` element with glamor styles.

If you're feeling adventurous I can write up some docs for how to do server rendering in 1.0 with Aphrodite or if you want to stay in 0.x you can fork Gatsby to add the necessary ssr code or use another styling option.

**Comment by SpencerCDixon** [comment]
Awesome, thanks for the quick response @KyleAMathews!  (Great work on Gatsby btw I've been really enjoying it).  I'll see if I can go the 1.0 route!

**Comment by KyleAMathews** [comment]
Good to hear!

1.0 should work well if your site is JS components and markdown. Building pages from other static files aren't supported yet (out of the box anyways). There's no upgrade guide but basically it's 1) move your _template.js file to `layouts/default.js` 2) modify your html.js to match https://github.com/KyleAMathews/react-headroom/blob/master/www/html.js 3) you need to gatsby-config.js something like https://github.com/KyleAMathews/react-headroom/blob/master/www/gatsby-config.js

Markdown isn't automatically converted to pages anymore. See my blog for how to programmatically create routes https://github.com/KyleAMathews/blog/blob/master/gatsby-node.js#L12

**Comment by KyleAMathews** [comment]
When you get to the aphrodite server rendering bit — create another issue (or actually just ping me on this thread) and I'll put up some sample code.

**Comment by SpencerCDixon** [comment]
Awesome thanks man, will keep you posted

**Comment by SpencerCDixon** [comment]
In regards to this: https://github.com/KyleAMathews/blog/blob/master/gatsby-node.js#L12 I'm a little confused about what the purpose of graphql is.  Do I need to have all the graphql related code?  I've never used it before and wasn't planning on using it for a simple blog that is statically generated. (sorry if this question is better placed somewhere else)

**Comment by SpencerCDixon** [comment]
Issues:

1.  No longer knows how to find 'config'.  Before I'd do:
`import { config } from 'config'`  now I do: `import config from '../gatsby-config'`, is that correct?

When I do that and pass along siteTitle to `Helmet` I'm not seeing any titles in the tab.

2.  Graphql errors when running server:

```
graphql errors [ { GraphQLError: Syntax Error GraphQL request (1:1) Unexpected <EOF>

  1:
     ^

    at syntaxError (/Users/spence/apps/spencercdixon/node_modules/graphql/error/syntaxError.js:28:15)
    at unexpected (/Users/spence/apps/spencercdixon/node_modules/graphql/language/parser.js:982:33)
    at parseDefinition (/Users/spence/apps/spencercdixon/node_modules/graphql/language/parser.js:152:9)
    at parseDocument (/Users/spence/apps/spencercdixon/node_modules/graphql/language/parser.js:106:22)
    at parse (/Users/spence/apps/spencercdixon/node_modules/graphql/language/parser.js:43:10)
    at Promise.then.error.errors (/Users/spence/apps/spencercdixon/node_modules/graphql/graphql.js:53:41)
    at graphql (/Users/spence/apps/spencercdixon/node_modules/graphql/graphql.js:51:10)
    at graphqlRunner (/Users/spence/apps/spencercdixon/node_modules/gatsby/dist/bootstrap/index.js:233:43)
    at /Users/spence/apps/spencercdixon/node_modules/gatsby/dist/utils/query-runner.js:355:12
    at Array.map (native)
    at /Users/spence/apps/spencercdixon/node_modules/gatsby/dist/utils/query-runner.js:345:31
    at /Users/spence/apps/spencercdixon/node_modules/gatsby/node_modules/async/queue.js:9:5
    at Object.q.process (/Users/spence/apps/spencercdixon/node_modules/gatsby/node_modules/async/internal/queue.js:151:17)
    at /Users/spence/apps/spencercdixon/node_modules/gatsby/node_modules/async/internal/queue.js:100:15
    at apply (/Users/spence/apps/spencercdixon/node_modules/lodash/_apply.js:14:25)
    at /Users/spence/apps/spencercdixon/node_modules/lodash/_overRest.js:32:12
    at /Users/spence/apps/spencercdixon/node_modules/gatsby/node_modules/async/internal/onlyOnce.js:12:16
    at /Users/spence/apps/spencercdixon/node_modules/gatsby/dist/utils/query-runner.js:390:5
    at run (/Users/spence/apps/spencercdixon/node_modules/core-js/library/modules/es6.promise.js:87:22)
    at /Users/spence/apps/spencercdixon/node_modules/core-js/library/modules/es6.promise.js:100:28
    at flush (/Users/spence/apps/spencercdixon/node_modules/core-js/library/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

    message: 'Syntax Error GraphQL request (1:1) Unexpected <EOF>\n\n1: \n   ^\n',
    locations: [ [Object] ],
    path: undefined } ]
rewrote JSON for queries for /Users/spence/apps/spencercdixon/pages/blog.js
graphql query time: 2.176ms
rewrote JSON for queries for /Users/spence/apps/spencercdixon/pages/index.js
(node:26843) Warning: No such label 'graphql query time' for console.timeEnd()
```

**Comment by KyleAMathews** [comment]
Graphql is only used during development and at build time so gatsby sites remain static :-)

On site config, you can import the module or the data is also exposed through graphql to query from.

And totally ok to stay on 0.x! Things are still pretty rough. Approaching having all the features I want for 1.0 done and then will be working on upgrade and other docs plus smoothing ux.
