### ISSUE TITLE
[v2] BrowserslistError: Unknown browser query `dead`

### ISSUE THREAD

**Issue by raymondsiu** [gatsbyjs/gatsby#5979]
## Description

ERROR  Failed to compile with 1 errors                                                                                     18:54:33
 error  in ./src/layouts/index.css

Module build failed: BrowserslistError: Unknown browser query `dead`
    at error (D:\dev\homestay-organizer\node_modules\browserslist\index.js:37:11)
    at D:\dev\homestay-organizer\node_modules\browserslist\index.js:222:9
    at Array.forEach (native)
    at browserslist (D:\dev\homestay-organizer\node_modules\browserslist\index.js:196:13)
    at isSupported (D:\dev\homestay-organizer\node_modules\caniuse-api\dist\index.js:65:37)
    at D:\dev\homestay-organizer\node_modules\postcss-cssnext\lib\index.js:69:117
    at Array.forEach (native)
    at D:\dev\homestay-organizer\node_modules\postcss-cssnext\lib\index.js:56:35
    at creator (D:\dev\homestay-organizer\node_modules\postcss\lib\postcss.js:150:35)
    at Object.postcss (D:\dev\homestay-organizer\node_modules\gatsby\dist\utils\webpack.config.js:162:109)
    at Object.module.exports (D:\dev\homestay-organizer\node_modules\postcss-loader\index.js:42:27)

 @ ./src/layouts/index.css 4:14-120 13:2-17:4 14:20-126

### Steps to reproduce

Run `gatsby develop`

### Expected result

Regulat `gatsby develop` development server behavior.

### Actual result

What happened.

### Environment

  System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.1.0 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^1.9.247 => 1.9.272
    gatsby-link: ^1.6.40 => 1.6.44
    gatsby-plugin-react-helmet: ^2.0.10 => 2.0.11

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by raymondsiu** [comment]
It seems this error was caused by the `gastby new <project-name> not installing all the dependencies correctly via yarn.

To solve this, I had to do an `npm install` in the project directory to re-install all the modules. Now I am seeing a new error related to Webpack, but I will close the issue for now.
