### ISSUE TITLE
Fix live GraphQL examples

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#6015]
## Description

The docker image that runs the live GraphQL examples is failing to start. This results in 503 errors on https://www.gatsbyjs.org/docs/graphql-reference/

### Steps to reproduce

```
docker run -it -p 8080:8080 -m 1536m --memory-swap=1536m  -e PORT='8080' mikeallanson/gatsby-graphql
```

### Expected result

A running graphiql instance containing gatsbyjs.org's data.

### Actual result

```
success onPreExtractQueries — 0.026 s
success update schema — 2.465 s
success extract queries from components — 0.846 s
⠁ Error running queryRunner TypeError: Cannot read property '0' of undefined
    at /usr/src/app/www/node_modules/gatsby/dist/internal-plugins/query-runner/query-runner.js:89:34
    at Generator.next (<anonymous>)
    at step (/usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (/usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
    at <anonymous>
⠂ run graphql queriesError running queryRunner TypeError: Cannot read property '0' of undefined
    at /usr/src/app/www/node_modules/gatsby/dist/internal-plugins/query-runner/query-runner.js:89:34
    at Generator.next (<anonymous>)
    at step (/usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (/usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
    at /usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new F (/usr/src/app/www/node_modules/core-js/library/modules/_export.js:36:28)
    at /usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:7:12
    at /usr/src/app/www/node_modules/gatsby/dist/internal-plugins/query-runner/query-runner.js:121:17
    at Worker.Queue [as fn] (/usr/src/app/www/node_modules/gatsby/dist/internal-plugins/query-runner/query-queue.js:18:10)
    at Worker.start (/usr/src/app/www/node_modules/better-queue/lib/worker.js:69:29)
    at Queue._startBatch (/usr/src/app/www/node_modules/better-queue/lib/queue.js:701:12)
    at /usr/src/app/www/node_modules/better-queue/lib/queue.js:572:12
    at MemoryStore.getLock (/usr/src/app/www/node_modules/better-queue-memory/index.js:87:3)
    at /usr/src/app/www/node_modules/better-queue/lib/queue.js:533:17
    at MemoryStore.takeFirstN (/usr/src/app/www/node_modules/better-queue-memory/index.js:69:3)
Error running queryRunner TypeError: Cannot read property '0' of undefined
    at /usr/src/app/www/node_modules/gatsby/dist/internal-plugins/query-runner/query-runner.js:89:34
    at Generator.next (<anonymous>)
    at step (/usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (/usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
    at /usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new F (/usr/src/app/www/node_modules/core-js/library/modules/_export.js:36:28)
    at /usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:7:12
    at /usr/src/app/www/node_modules/gatsby/dist/internal-plugins/query-runner/query-runner.js:121:17
    at Worker.Queue [as fn] (/usr/src/app/www/node_modules/gatsby/dist/internal-plugins/query-runner/query-queue.js:18:10)
    at Worker.start (/usr/src/app/www/node_modules/better-queue/lib/worker.js:69:29)
    at Queue._startBatch (/usr/src/app/www/node_modules/better-queue/lib/queue.js:701:12)
    at /usr/src/app/www/node_modules/better-queue/lib/queue.js:572:12
    at MemoryStore.getLock (/usr/src/app/www/node_modules/better-queue-memory/index.js:87:3)
    at /usr/src/app/www/node_modules/better-queue/lib/queue.js:533:17
    at MemoryStore.takeFirstN (/usr/src/app/www/node_modules/better-queue-memory/index.js:69:3)
Error running queryRunner TypeError: Cannot read property '0' of undefined
    at /usr/src/app/www/node_modules/gatsby/dist/internal-plugins/query-runner/query-runner.js:89:34
    at Generator.next (<anonymous>)
    at step (/usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (/usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
    at /usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new F (/usr/src/app/www/node_modules/core-js/library/modules/_export.js:36:28)
    at /usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:7:12
    at /usr/src/app/www/node_modules/gatsby/dist/internal-plugins/query-runner/query-runner.js:121:17
    at Worker.Queue [as fn] (/usr/src/app/www/node_modules/gatsby/dist/internal-plugins/query-runner/query-queue.js:18:10)
    at Worker.start (/usr/src/app/www/node_modules/better-queue/lib/worker.js:69:29)
    at Queue._startBatch (/usr/src/app/www/node_modules/better-queue/lib/queue.js:701:12)
    at /usr/src/app/www/node_modules/better-queue/lib/queue.js:572:12
    at MemoryStore.getLock (/usr/src/app/www/node_modules/better-queue-memory/index.js:87:3)
    at /usr/src/app/www/node_modules/better-queue/lib/queue.js:533:17
    at MemoryStore.takeFirstN (/usr/src/app/www/node_modules/better-queue-memory/index.js:69:3)
Error running queryRunner TypeError: Cannot read property '0' of undefined
    at /usr/src/app/www/node_modules/gatsby/dist/internal-plugins/query-runner/query-runner.js:89:34
    at Generator.next (<anonymous>)
    at step (/usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (/usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
    at /usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new F (/usr/src/app/www/node_modules/core-js/library/modules/_export.js:36:28)
    at /usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:7:12
    at /usr/src/app/www/node_modules/gatsby/dist/internal-plugins/query-runner/query-runner.js:121:17
    at Worker.Queue [as fn] (/usr/src/app/www/node_modules/gatsby/dist/internal-plugins/query-runner/query-queue.js:18:10)
    at Worker.start (/usr/src/app/www/node_modules/better-queue/lib/worker.js:69:29)
    at Queue._startBatch (/usr/src/app/www/node_modules/better-queue/lib/queue.js:701:12)
    at /usr/src/app/www/node_modules/better-queue/lib/queue.js:572:12
    at MemoryStore.getLock (/usr/src/app/www/node_modules/better-queue-memory/index.js:87:3)
    at /usr/src/app/www/node_modules/better-queue/lib/queue.js:533:17
    at MemoryStore.takeFirstN (/usr/src/app/www/node_modules/better-queue-memory/index.js:69:3)
Error running queryRunner TypeError: Cannot read property '0' of undefined
    at /usr/src/app/www/node_modules/gatsby/dist/internal-plugins/query-runner/query-runner.js:89:34
    at Generator.next (<anonymous>)
    at step (/usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (/usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
    at /usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new F (/usr/src/app/www/node_modules/core-js/library/modules/_export.js:36:28)
    at /usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:7:12
    at /usr/src/app/www/node_modules/gatsby/dist/internal-plugins/query-runner/query-runner.js:121:17
    at Worker.Queue [as fn] (/usr/src/app/www/node_modules/gatsby/dist/internal-plugins/query-runner/query-queue.js:18:10)
    at Worker.start (/usr/src/app/www/node_modules/better-queue/lib/worker.js:69:29)
    at Queue._startBatch (/usr/src/app/www/node_modules/better-queue/lib/queue.js:701:12)
    at /usr/src/app/www/node_modules/better-queue/lib/queue.js:572:12
    at MemoryStore.getLock (/usr/src/app/www/node_modules/better-queue-memory/index.js:87:3)
    at /usr/src/app/www/node_modules/better-queue/lib/queue.js:533:17
    at MemoryStore.takeFirstN (/usr/src/app/www/node_modules/better-queue-memory/index.js:69:3)
Error running queryRunner TypeError: Cannot read property '0' of undefined
    at /usr/src/app/www/node_modules/gatsby/dist/internal-plugins/query-runner/query-runner.js:89:34
    at Generator.next (<anonymous>)
    at step (/usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (/usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
    at /usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new F (/usr/src/app/www/node_modules/core-js/library/modules/_export.js:36:28)
    at /usr/src/app/www/node_modules/@babel/runtime/helpers/asyncToGenerator.js:7:12
    at /usr/src/app/www/node_modules/gatsby/dist/internal-plugins/query-runner/query-runner.js:121:17
    at Worker.Queue [as fn] (/usr/src/app/www/node_modules/gatsby/dist/internal-plugins/query-runner/query-queue.js:18:10)
    at Worker.start (/usr/src/app/www/node_modules/better-queue/lib/worker.js:69:29)
    at Queue._startBatch (/usr/src/app/www/node_modules/better-queue/lib/queue.js:701:12)
    at /usr/src/app/www/node_modules/better-queue/lib/queue.js:572:12
    at MemoryStore.getLock (/usr/src/app/www/node_modules/better-queue-memory/index.js:87:3)
    at /usr/src/app/www/node_modules/better-queue/lib/queue.js:533:17
    at MemoryStore.takeFirstN (/usr/src/app/www/node_modules/better-queue-memory/index.js:69:3)
success run graphql queries — 0.162 s
error Failed to write out page data


  TypeError: Cannot read property '0' of undefined

  - pages-writer.js:44 _.sortBy.pages.reduce
    [www]/[gatsby]/dist/internal-plugins/query-runner/pages-writer.js:44:20

  - Array.reduce

  - pages-writer.js:34
    [www]/[gatsby]/dist/internal-plugins/query-runner/pages-writer.js:34:38

  - Generator.next

  - new Promise

  - pages-writer.js:111 writePages
    [www]/[gatsby]/dist/internal-plugins/query-runner/pages-writer.js:111:17

  - index.js:309
    [www]/[gatsby]/dist/bootstrap/index.js:309:13

  - Generator.next
```

**Comment by m-allanson** [comment]
Done in #6042
