### ISSUE TITLE
[using-typescript] AudioContext is not defined

### ISSUE THREAD

**Issue by jsphweid** [gatsbyjs/gatsby#6177]
## Description

Project cannot build if it contains the type AudioContext.

### Steps to reproduce

1. Copy examples/using-typescript.
2. Add this to index.tsx and `npm install`:
```javascript
export default ({ data }: IndexPageProps) => {
	const { siteName } = data.site.siteMetadata
	const audioContext: AudioContext = new AudioContext() // this line here
	return (
		<Layout>
			<h1>Hello Typescript world!</h1>
			<p>
				This site is named <strong>{siteName}</strong>
			</p>
		</Layout>
	)
}
```
3. ~~cut a hole in the~~ run `npm run build`
### Expected result

It blows up.

What should happen?

It should simply build the artifacts.

What happened.

```
Building static HTML for pagesReferenceError: AudioContext is not defined
    at ./src/pages/index.tsx.__webpack_exports__.default (/Users/josephweidinger/Desktop/using-typescript/public/render-page.js:24080:24)
    at d (/Users/josephweidinger/Desktop/using-typescript/public/render-page.js:21195:492)
    at wa (/Users/josephweidinger/Desktop/using-typescript/public/render-page.js:21197:493)
    at a../node_modules/react-dom/cjs/react-dom-server.node.production.min.js.a.render (/Users/josephweidinger/Desktop/using-typescript/public/render-page.js:21202:48)
    at a../node_modules/react-dom/cjs/react-dom-server.node.production.min.js.a.read (/Users/josephweidinger/Desktop/using-typescript/public/render-page.js:21201:288)
    at renderToString (/Users/josephweidinger/Desktop/using-typescript/public/render-page.js:21212:6)
    at Object._default [as default] (/Users/josephweidinger/Desktop/using-typescript/public/render-page.js:527:16)
    at Worker.Queue [as fn] (/Users/josephweidinger/Desktop/using-typescript/node_modules/gatsby/dist/utils/html-renderer.js:23:36)
    at Worker.start (/Users/josephweidinger/Desktop/using-typescript/node_modules/better-queue/lib/worker.js:69:29)
    at Queue._startBatch (/Users/josephweidinger/Desktop/using-typescript/node_modules/better-queue/lib/queue.js:701:12)
    at /Users/josephweidinger/Desktop/using-typescript/node_modules/better-queue/lib/queue.js:572:12
    at MemoryStore.getLock (/Users/josephweidinger/Desktop/using-typescript/node_modules/better-queue-memory/index.js:87:3)
    at /Users/josephweidinger/Desktop/using-typescript/node_modules/better-queue/lib/queue.js:533:17
    at MemoryStore.takeFirstN (/Users/josephweidinger/Desktop/using-typescript/node_modules/better-queue-memory/index.js:69:3)
    at Queue._getNextBatch (/Users/josephweidinger/Desktop/using-typescript/node_modules/better-queue/lib/queue.js:473:54)
    at Queue._processNext (/Users/josephweidinger/Desktop/using-typescript/node_modules/better-queue/lib/queue.js:530:8)
```
### Environment

OSX

**Comment by jsphweid** [comment]
It's worth noting that it DOES when running in develop mode.

Interestingly I run into the same problem with react-static :/

**Comment by KyleAMathews** [comment]
AudioContext is defined on the window object which doesn't exist during builds. Check out this issue for a way to fix things https://www.gatsbyjs.org/docs/debugging-html-builds/#how-to-check-if-code-classlanguage-textwindowcode-is-defined
