### ISSUE TITLE
Firebase build errr

### ISSUE THREAD

**Issue by ufon** [gatsbyjs/gatsby#634]
in develop mode all works fine. but in build i have this error
```
      throw err;
      ^
Error: TypeError: firebase.storage is not a function
    at Contact.render (render-page.js:113333:34)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (render-page.js:14345:31)
    at ReactCompositeComponentWrapper._renderValidatedComponent (render-page.js:14368:33)
    at ReactCompositeComponentWrapper.performInitialMount (render-page.js:13908:31)
    at ReactCompositeComponentWrapper.mountComponent (render-page.js:13804:22)
    at Object.mountComponent (render-page.js:6875:36)
    at ReactDOMComponent.mountChildren (render-page.js:12938:45)
    at ReactDOMComponent._createContentMarkup (render-page.js:9965:33)
    at ReactDOMComponent.mountComponent (render-page.js:9832:30)
    at Object.mountComponent (render-page.js:6875:36)
```
at 113333 line

`var storageRef = firebase.storage().ref('folder');`

`import * as firebase from 'firebase';`
i tried use 
`import firebase from 'firebase';`
after i got following error
`_firebase2.default.storage is not a function`

package.json

```
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "animate.css": "^3.5.2",
    "boron": "^0.2.3",
    "classnames": "^2.2.5",
    "firebase": "^3.6.5",
    "front-matter": "^2.0.7",
    "gatsby": "^0.12.6",
    "highlight.js": "^9.6.0",
    "history": "^2.0.2",
    "js-yaml": "^3.6.0",
    "markdown-it": "^7.0.1",
    "markdown-it-abbr": "^1.0.3",
    "markdown-it-attrs": "^0.6.3",
    "markdown-it-deflist": "^2.0.1",
    "markdown-it-footnote": "^3.0.1",
    "markdown-it-sub": "^1.0.0",
    "object-assign": "^4.1.0",
    "react-firebase-file-uploader": "^2.1.1",
    "react-headroom": "^2.1.2",
    "react-helmet": "^3.1.0",
    "react-responsive-grid": "^0.3.3",
    "react-reveal": "^0.1.1",
    "react-slick": "^0.14.5",
    "react-typography": "^0.12.0",
    "slick-carousel": "^1.6.0",
    "toml-js": "0.0.8",
    "typography": "^0.13.0",
    "typography-plugin-code": "^0.13.0"
  },
  "devDependencies": {
    "gh-pages": "^0.11.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "scripts": {
    "build": "gatsby build",
    "deploy": "gatsby build --prefix-links && gh-pages -d public",
    "develop": "gatsby develop",
    "test": "echo \"Error: no test specified\" && exit 1"
  }
}

```

WIN10 node v7.2.1 

Thank You!

**Comment by KyleAMathews** [comment]
I'm guessing you're not loading firebase on componentDidMount?

**Comment by ufon** [comment]
@KyleAMathews yes, I initialize firebase before class init like that:
```
var config = {
    apiKey: "***",
    authDomain: "***",
    databaseURL: "***",
    storageBucket: "***",
    messagingSenderId: "***"
};

firebase.initializeApp(config);

export default class Index extends React.Component {
```

**Comment by ufon** [comment]
@KyleAMathews thx u very much. Has solved it transfer firebase.init to componentDidMount!
