### ISSUE TITLE
Cannot find module 'opentracing'

### ISSUE THREAD

**Issue by mquandalle** [gatsbyjs/gatsby#6425]
Opentracing support (#6347) was recently merged and released in the latest beta of gatsby, but after updating my dependencies with `yarn upgrade` I'm experiencing the following error:

```
$ gatsby develop
module.js:540
    throw err;
    ^

Error: Cannot find module 'opentracing'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/maxime/react/lebonforfait/web/node_modules/gatsby-cli/lib/reporter/index.js:11:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3
```

It seems that there is a missing dependency somewhere.

**Comment by mquandalle** [comment]
cc @Moocar

**Comment by KyleAMathews** [comment]
I'm guessing there's an error with yarn upgrade. opentracing is a dependency of gatsby as you can see here https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/package.json

Try deleting your yarn.lock file and try installing again.

**Comment by mquandalle** [comment]
The issue is still present after `rm yarn.lock` and `yarn install`, I need to manually add `opentracing` as a dependency.

**Comment by mquandalle** [comment]
The issue comes from the `gatsby-cli` package (`lib/reporter/index.js`)

**Comment by KyleAMathews** [comment]
Oh oops, you're right! Will merge and publish your PR with the fix.

**Comment by Moocar** [comment]
@KyleAMathews Thanks for fixing this!
