### ISSUE TITLE
Using custom .babelrc breaks build

### ISSUE THREAD

**Issue by kmcaloon** [gatsbyjs/gatsby#6469]
## Description

Following the directions on the [Babel.js](https://next.gatsbyjs.org/docs/babel/) docs breaks the build.

### Steps to reproduce

Follow directions by copying content from the docs into a .babelrc file in the root of project. Run `gatsby develop` or `gatsby build`

### Expected result

By not modifying the file, build should process as usual.

### Actual result

Receive the following error:

```
  Error: ./.cache/production-app.js
  Module build failed (from ./node_modules/babel-loader/lib/index.js):
  Error: [BABEL] /Applications/MAMP/htdocs/nv2/.cache/production-app.js: Invalid Option: sourceType is not a valid t  op-level option.
          Maybe you meant to use 'exclude'? (While processing: "/Applications/MAMP/htdocs/nv2/node_modules/@babel/pr  eset-env/lib/index.js")
      at validateTopLevelOptions (/Applications/MAMP/htdocs/nv2/node_modules/@babel/preset-env/lib/normalize-options  .js:47:13)
      at normalizeOptions (/Applications/MAMP/htdocs/nv2/node_modules/@babel/preset-env/lib/normalize-options.js:149  :3)
      at _default (/Applications/MAMP/htdocs/nv2/node_modules/@babel/preset-env/lib/index.js:164:37)
      at /Applications/MAMP/htdocs/nv2/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
      at loadDescriptor (/Applications/MAMP/htdocs/nv2/node_modules/@babel/core/lib/config/full.js:157:14)
      at cachedFunction (/Applications/MAMP/htdocs/nv2/node_modules/@babel/core/lib/config/caching.js:32:19)
      at loadPresetDescriptor (/Applications/MAMP/htdocs/nv2/node_modules/@babel/core/lib/config/full.js:227:63)
      at config.presets.map.descriptor (/Applications/MAMP/htdocs/nv2/node_modules/@babel/core/lib/config/full.js:72  :19)
      at Array.map (<anonymous>)
      at recurseDescriptors (/Applications/MAMP/htdocs/nv2/node_modules/@babel/core/lib/config/full.js:70:38)
      at loadFullConfig (/Applications/MAMP/htdocs/nv2/node_modules/@babel/core/lib/config/full.js:100:6)
      at transformSync (/Applications/MAMP/htdocs/nv2/node_modules/@babel/core/lib/transform.js:41:38)
      at Object.transform (/Applications/MAMP/htdocs/nv2/node_modules/@babel/core/lib/transform.js:22:38)
      at transpile (/Applications/MAMP/htdocs/nv2/node_modules/babel-loader/lib/index.js:55:20)
      at /Applications/MAMP/htdocs/nv2/node_modules/babel-loader/lib/fs-cache.js:116:18
      at ReadFileContext.callback (/Applications/MAMP/htdocs/nv2/node_modules/babel-loader/lib/fs-cache.js:36:21)
      at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:437:13)
```

### Environment

  System:
    OS: OS X El Capitan 10.11.6
    CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 9.5.0 - /usr/local/bin/node
    Yarn: 1.3.2 - ~/.yarn/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 59.0.2
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.0.0-beta.29 => 2.0.0-beta.34 
    gatsby-image: ^2.0.0-beta.6 => 2.0.0-beta.6 
    gatsby-link: ^2.0.0-beta.4 => 2.0.0-beta.4 
    gatsby-plugin-babel: ^1.0.0 => 1.0.0 
    gatsby-plugin-catch-links: ^2.0.2-beta.2 => 2.0.2-beta.2 
    gatsby-plugin-google-analytics: ^2.0.0-beta.2 => 2.0.0-beta.2 
    gatsby-plugin-manifest: ^2.0.2-beta.2 => 2.0.2-beta.2 
    gatsby-plugin-offline: ^2.0.0-beta.3 => 2.0.0-beta.3 
    gatsby-plugin-react-helmet: v2 => 2.0.11 
    gatsby-plugin-sass: ^2.0.0-beta.5 => 2.0.0-beta.5 
    gatsby-plugin-sharp: ^2.0.0-beta.3 => 2.0.0-beta.5 
    gatsby-plugin-sitemap: ^2.0.0-beta.2 => 2.0.0-beta.2 
    gatsby-remark-images: ^2.0.1-beta.4 => 2.0.1-beta.6 
    gatsby-source-filesystem: ^2.0.1-beta.3 => 2.0.1-beta.3 
    gatsby-transformer-remark: ^2.1.1-beta.3 => 2.1.1-beta.3 
    gatsby-transformer-sharp: ^2.1.1-beta.3 => 2.1.1-beta.3 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

**Comment by kmcaloon** [comment]
Issue seems to be from the lack of double quotes around the option keys in the example provided on the page. Should I put in a PR?

**Comment by KyleAMathews** [comment]
PR would be great!
