### ISSUE TITLE
Problem with running Gatsby on a different port

### ISSUE THREAD

**Issue by pilarenko** [gatsbyjs/gatsby#6543]
Hello. 

I just got on board with Gatsby and it didn't start well. I run Gatsby not on localhost, but my online hosting that forces me to make a reservation for each port I'm going to use. So I went with "gatsby new xyz" and then "gatsby developer -p myReservedPort" and everything seemed to work fine except it didn't. I've got no error whatsoever, every process gets greenlighted, but when I try to access via "domain.xyz:myReservedPort" it shows something like "This site is unreachable" aka "ERR_CONNECTION_REFUSED". 

When I run npm start in a directory, for example for a pure React project, it always runs in the same address I try to access Gatsby (but on different port, of course), so it's probably not the URL issue. Do you have any clue what may cause that?

**Comment by KyleAMathews** [comment]
You'll also need to set the `host` (which by default is `localhost`) to generally `0.0.0.0` with `gatsby develop -h 0.0.0.0 -p yourPort`

**Comment by pilarenko** [comment]
Sorry for a double post, but it seems that the "hurray" moment was only temporary. The build went through once and since then it doesn't work even though nothing changed. I managed to get an error and it's pretty popular node one from what I've seen. 


```
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EMFILE: too many open files, open '/xyz/.npm-global/lib/node_modules/gatsby-cli/node_modules/yurnalist/dist/reporters/cons          ole/util.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.Module._extensions..js (module.js:645:20)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at _load_util (/xyz/.npm-global/lib/node_modules/gatsby-cli/node_modules/yurnalist/dist/reporters/console/console-reporter.js          :34:18)
    at ConsoleReporter.error (/xyz/.npm-global/lib/node_modules/gatsby-cli/node_modules/yurnalist/dist/reporters/console/console-          reporter.js:200:19)
    at ConsoleReporter.error (/xyz/.npm-global/lib/node_modules/gatsby-cli/lib/reporter/index.js:68:16)
    at ConsoleReporter.panic (/xyz/.npm-global/lib/node_modules/gatsby-cli/lib/reporter/index.js:54:16)
    at process.<anonymous> (/xyz/.npm-global/lib/node_modules/gatsby-cli/lib/index.js:123:10)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:374:26)
```

I've read that [graceful-fs](https://github.com/isaacs/node-graceful-fs) may be helpful in that case, but I failed trying to insert the code from usage/global patching anywhere. 

So the next two questions are: where do I insert the graceful-fs code in default Gatsby.js config/directories structure or is there any other way to fix this if graceful-fs is not the one?
