### ISSUE TITLE
BrowsersListError on `gatsby develop` on a fresh project

### ISSUE THREAD

**Issue by ulhas** [gatsbyjs/gatsby#6694]
## Description

I installed the new gatsby version and did a `gatsby new <project_name>`. After this, I tried to run the project I got an error stating - `Module build failed: BrowserslistError: Unknown browser query dead`

gatsby version - 2.0.0-beta.55
node version - 10.7.0
npm version - 6.2.0
OS version - macOS 10.13.4

### Steps to reproduce

1. `gatsby new <website_name>`
2. `gatsby develop`

### Expected result

It should serve the gatsby app

### Actual result

```shell
$ gatsby develop
success delete html and css files from previous builds — 0.009 s
success open and validate gatsby-config — 0.006 s
success copy gatsby files — 0.016 s
success onPreBootstrap — 0.012 s
success source and transform nodes — 0.016 s
success building schema — 0.084 s
success createLayouts — 0.021 s
success createPages — 0.000 s
success createPagesStatefully — 0.016 s
success onPreExtractQueries — 0.000 s
success update schema — 0.043 s
success extract queries from components — 0.042 s
success run graphql queries — 0.022 s
success write out page data — 0.003 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.001 s

info bootstrap finished - 2.788 s

 ERROR  Failed to compile with 1 errors                                                                                                                                 12:33:02 PM

 error  in ./src/layouts/index.css

Module build failed: BrowserslistError: Unknown browser query `dead`
    at error (/Users/ulhas/Workspace/procedure/gatsby/procedure-website/node_modules/browserslist/index.js:37:11)
    at /Users/ulhas/Workspace/procedure/gatsby/procedure-website/node_modules/browserslist/index.js:222:9
    at Array.forEach (<anonymous>)
    at browserslist (/Users/ulhas/Workspace/procedure/gatsby/procedure-website/node_modules/browserslist/index.js:196:13)
    at isSupported (/Users/ulhas/Workspace/procedure/gatsby/procedure-website/node_modules/caniuse-api/dist/index.js:65:37)
    at /Users/ulhas/Workspace/procedure/gatsby/procedure-website/node_modules/postcss-cssnext/lib/index.js:69:117
    at Array.forEach (<anonymous>)
    at /Users/ulhas/Workspace/procedure/gatsby/procedure-website/node_modules/postcss-cssnext/lib/index.js:56:35
    at creator (/Users/ulhas/Workspace/procedure/gatsby/procedure-website/node_modules/postcss/lib/postcss.js:150:35)
    at Object.postcss (/Users/ulhas/Workspace/procedure/gatsby/procedure-website/node_modules/gatsby/dist/utils/webpack.config.js:162:109)
    at Object.module.exports (/Users/ulhas/Workspace/procedure/gatsby/procedure-website/node_modules/postcss-loader/index.js:42:27)

 @ ./src/layouts/index.css 4:14-120 13:2-17:4 14:20-126```

**Comment by ulhas** [comment]
Ok, I made it to work

`gatsby new my-default-project https://github.com/gatsbyjs/gatsby-starter-default#v2` tried this and it work.

**Comment by ryanditjia** [comment]
Glad you got it working!
