### ISSUE TITLE
EMFILE: Too many open files 

### ISSUE THREAD

**Issue by pilarenko** [gatsbyjs/gatsby#6695]
Hi. 
I've had [some difficulties](https://github.com/gatsbyjs/gatsby/issues/6543) with running Gatsby on my server and my topic got closed, so I start a new one. 

Recently I struggled with what I thought was a wrong port/host property while developing a clean Gatsby build, but turns out everything was fine. Out of the blue, the build went through once and since then it doesn't work even though nothing changed. I managed to get an error and it's pretty popular node one from what I've seen. 

```
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EMFILE: too many open files, open '/xyz/.npm-global/lib/node_modules/gatsby-cli/node_modules/yurnalist/dist/reporters/cons          ole/util.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.Module._extensions..js (module.js:645:20)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at _load_util (/xyz/.npm-global/lib/node_modules/gatsby-cli/node_modules/yurnalist/dist/reporters/console/console-reporter.js          :34:18)
    at ConsoleReporter.error (/xyz/.npm-global/lib/node_modules/gatsby-cli/node_modules/yurnalist/dist/reporters/console/console-          reporter.js:200:19)
    at ConsoleReporter.error (/xyz/.npm-global/lib/node_modules/gatsby-cli/lib/reporter/index.js:68:16)
    at ConsoleReporter.panic (/xyz/.npm-global/lib/node_modules/gatsby-cli/lib/reporter/index.js:54:16)
    at process.<anonymous> (/xyz/.npm-global/lib/node_modules/gatsby-cli/lib/index.js:123:10)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:374:26)
```

I've read that [graceful-fs](https://github.com/isaacs/node-graceful-fs) may be helpful in that case, but I failed trying to insert the code from usage/global patching anywhere. 

So the next two questions are: where do I insert the graceful-fs code in default Gatsby.js config/directories structure or is there any other way to fix this if graceful-fs is not the one? 

Another thing is, almost any Linux-side is not possible, because it is not my own machine and I don't have permission to do most of the commands like reseting or changing limits of open files. 

Cheers.

**Comment by pilarenko** [comment]
Gatsby-config.js: 

```
module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
  },
  plugins: ['gatsby-plugin-react-helmet'],
}

```

Gatsby info: 

```
#!/usr/bin/env node
"use strict";

require("core-js/modules/es6.typed.array-buffer");

require("core-js/modules/es6.typed.int8-array");

require("core-js/modules/es6.typed.uint8-array");

require("core-js/modules/es6.typed.uint8-clamped-array");

require("core-js/modules/es6.typed.int16-array");

require("core-js/modules/es6.typed.uint16-array");

require("core-js/modules/es6.typed.int32-array");

require("core-js/modules/es6.typed.uint32-array");

require("core-js/modules/es6.typed.float32-array");

require("core-js/modules/es6.typed.float64-array");

require("core-js/modules/es6.map");

require("core-js/modules/es6.set");

require("core-js/modules/es6.weak-map");

require("core-js/modules/es6.weak-set");

require("core-js/modules/es6.reflect.apply");

require("core-js/modules/es6.reflect.construct");

require("core-js/modules/es6.reflect.define-property");

require("core-js/modules/es6.reflect.delete-property");

require("core-js/modules/es6.reflect.get");

require("core-js/modules/es6.reflect.get-own-property-descriptor");

require("core-js/modules/es6.reflect.get-prototype-of");

require("core-js/modules/es6.reflect.has");

require("core-js/modules/es6.reflect.is-extensible");

require("core-js/modules/es6.reflect.own-keys");

require("core-js/modules/es6.reflect.prevent-extensions");

require("core-js/modules/es6.reflect.set");

require("core-js/modules/es6.reflect.set-prototype-of");

require("core-js/modules/es6.promise");

require("core-js/modules/es6.symbol");

require("core-js/modules/es6.function.name");

require("core-js/modules/es6.regexp.flags");

require("core-js/modules/es6.regexp.match");

require("core-js/modules/es6.regexp.replace");

require("core-js/modules/es6.regexp.split");

require("core-js/modules/es6.regexp.search");

require("core-js/modules/es6.array.from");

require("core-js/modules/es7.array.includes");

require("core-js/modules/es7.object.values");

require("core-js/modules/es7.object.entries");

require("core-js/modules/es7.object.get-own-property-descriptors");

require("core-js/modules/es7.string.pad-start");

require("core-js/modules/es7.string.pad-end");

require("regenerator-runtime/runtime");

var createCli = require(`./create-cli`);

// babel-preset-env doesn't find this import if you
// use require() with backtick strings so use the es6 syntax

var report = require(`./reporter`);

global.Promise = require(`bluebird`);

var version = process.version;
var verDigit = Number(version.match(/\d+/)[0]);

var pkg = require(`../package.json`);
var updateNotifier = require(`update-notifier`);
// Check if update is available
updateNotifier({ pkg }).notify();

if (verDigit < 4) {
  report.panic(`Gatsby 1.0+ requires node.js v4 or higher (you have ${version}). \n` + `Upgrade node to the latest stable release.`);
}

Promise.onPossiblyUnhandledRejection(function (error) {
  report.error(error);
  throw error;
});

process.on(`unhandledRejection`, function (error) {
  // This will exit the process in newer Node anyway so lets be consistent
  // across versions and crash
  report.panic(`UNHANDLED REJECTION`, error);
});

process.on(`uncaughtException`, function (error) {
  report.panic(`UNHANDLED EXCEPTION`, error);
});

createCli(process.argv);
```

**Comment by pilarenko** [comment]
Hey @m-allanson, any clue? Do you need anything else from me?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
