### ISSUE TITLE
[v2?] source mongodb fails on array of collections

### ISSUE THREAD

**Issue by Amanpreet-03** [gatsbyjs/gatsby#6881]
## Description

In gatsby-config.js file, single collection is working, but if array of collections is used, I got this error: `key.includes is not a function.`

### Steps to reproduce

my gatsby-config.js is as follows,please notice the array for collection:
```
module.exports = {
    plugins: [`gatsby-plugin-emotion`,
              `gatsby-plugin-typography`,
              {
                resolve: `gatsby-source-mongodb`,
                options: { dbName: `test`, 
                           collection: [`guides`,`treks`]
                         }
              }
            ],
  };
  ```

### Expected result
gatsby build should work

### Actual result
getting error:key.includes is not a function

```error key.includes is not a function


  TypeError: key.includes is not a function
  
  - infer-graphql-type.js:348 _.each
    [sherpafeet]/[gatsby]/dist/schema/infer-graphql-type.js:348:20
  
  - lodash.js:4901 
    [sherpafeet]/[lodash]/lodash.js:4901:15
  
  - lodash.js:9342 Function.forEach
    [sherpafeet]/[lodash]/lodash.js:9342:14
  
  - infer-graphql-type.js:333 _inferObjectStructureFromNodes
    [sherpafeet]/[gatsby]/dist/schema/infer-graphql-type.js:333:5
  
  - infer-graphql-type.js:403 inferObjectStructureFromNodes
    [sherpafeet]/[gatsby]/dist/schema/infer-graphql-type.js:403:10
  
  - build-node-types.js:150 createNodeFields
    [sherpafeet]/[gatsby]/dist/schema/build-node-types.js:150:30
  
  - build-node-types.js:184 fields
    [sherpafeet]/[gatsby]/dist/schema/build-node-types.js:184:25
  
  - Array.forEach
  
  - Array.forEach
  
  - Array.forEach
  
  - Array.reduce
  
```

**Comment by Chuloo** [comment]
Hi, can you send in a minimal reproduction of your code with the error so it can be better understood? Also, what version of Gatsby are you running?

**Comment by Amanpreet-03** [comment]
Hi, you can find my code here: https://github.com/Amanpreet-03/sherpafeet
In gatsby-config file, if I am adding array of collections , then I got error:
```
success onPreBootstrap — 0.001 s
success source and transform nodes — 0.209 s
error UNHANDLED REJECTION


  TypeError: key.includes is not a function
  
  - infer-graphql-type.js:348 _.each
    [sherpa]/[gatsby]/dist/schema/infer-graphql-type.js:348:20
  
  - lodash.js:4901 
    [sherpa]/[lodash]/lodash.js:4901:15
  
  - lodash.js:9342 Function.forEach
    [sherpa]/[lodash]/lodash.js:9342:14
  
  - infer-graphql-type.js:333 _inferObjectStructureFromNodes
    [sherpa]/[gatsby]/dist/schema/infer-graphql-type.js:333:5
  
  - infer-graphql-type.js:403 inferObjectStructureFromNodes
    [sherpa]/[gatsby]/dist/schema/infer-graphql-type.js:403:10
  
  - build-node-types.js:150 createNodeFields
    [sherpa]/[gatsby]/dist/schema/build-node-types.js:150:30
  
  - build-node-types.js:184 fields
    [sherpa]/[gatsby]/dist/schema/build-node-types.js:184:25
  
  - Array.forEach
  
  - Array.forEach
  
  - Array.forEach
  
  - Array.reduce
```
But if I am using single collection, then there is no error.

`Gatsby version: v2`

**Comment by Chuloo** [comment]
@Amanpreet-03 here is the error encountered whilst running `gastby develop` on your code.
```
success open and validate gatsby-config — 0.012 s
success load plugins — 0.340 s
success onPreInit — 0.344 s
success delete html and css files from previous builds — 0.009 s
success initialize cache — 0.014 s
success copy gatsby files — 0.082 s
success onPreBootstrap — 0.003 s
⠁ { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/talentpartnershipsassociate/Desktop/WORK/gatsby/bug-repro/sherpafeet-6881/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (/Users/talentpartnershipsassociate/Desktop/WORK/gatsby/bug-repro/sherpafeet-6881/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/Users/talentpartnershipsassociate/Desktop/WORK/gatsby/bug-repro/sherpafeet-6881/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'MongoError',
  message:
   'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }
warning The gatsby-source-mongodb plugin has generated no Gatsby nodes. Do you need it?
success source and transform nodes — 0.067 s
success building schema — 0.171 s
success createPages — 0.001 s
success createPagesStatefully — 0.056 s
success onPreExtractQueries — 0.001 s
success update schema — 0.089 s
GraphQL Error Unknown field `mongodbTestGuides` on type `RootQueryType`

  file: /Users/talentpartnershipsassociate/Desktop/WORK/gatsby/bug-repro/sherpafeet-6881/src/pages/index.js

   1 |
   2 |   query IndexQuery1 {
>  3 |             mongodbTestGuides(uid: {eq: "RajeshThakur"}) {
     |             ^
   4 |                     businessname
   5 |                     firstname
   6 |                     lastname
   7 |                     age
   8 |                     address {
   9 |                                 city
  10 |                                 state
  11 |                             }
  12 |                     startwork
  13 |                     rating

success extract queries from components — 0.109 s
⠁ (node:91768) DeprecationWarning: Passing lineNumber and colNumber is deprecated to @babel/code-frame. Please use `codeFrameColumns`.
success run graphql queries — 0.029 s — 3/3 125.34 queries/second
success write out page data — 0.010 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.001 s

info bootstrap finished - 8.097 s

 ERROR  Failed to compile with 1 errors                                                                                                                 4:58:20 PM

 error  in ./src/pages/index.js

Module Error (from ./node_modules/eslint-loader/index.js):

/Users/talentpartnershipsassociate/Desktop/WORK/gatsby/bug-repro/sherpafeet-6881/src/pages/index.js
    1:17  warning  'Component' is defined but never used                                                              no-unused-vars
  129:45  warning  The href attribute is required on an anchor. Provide a valid, navigable address as the href value  jsx-a11y/anchor-is-valid
  130:45  warning  The href attribute is required on an anchor. Provide a valid, navigable address as the href value  jsx-a11y/anchor-is-valid
  163:13  error    Cannot query field "mongodbTestGuides" on type "RootQueryType"                                     graphql/template-strings
  200:1   warning  Block is redundant                                                                                 no-lone-blocks

✖ 5 problems (1 error, 4 warnings)


 @ ./.cache/sync-requires.js 14:50-160
 @ ./.cache/root.js
 @ ./.cache/app.js
 @ multi ./node_modules/react-hot-loader/patch.js (webpack)-hot-middleware/client.js?path=http://localhost:8000/__webpack_hmr&reload=true&overlay=false ./.cache/app

✖ ｢wdm｣:
ERROR in ./src/pages/index.js
Module Error (from ./node_modules/eslint-loader/index.js):

/Users/talentpartnershipsassociate/Desktop/WORK/gatsby/bug-repro/sherpafeet-6881/src/pages/index.js
    1:17  warning  'Component' is defined but never used                                                              no-unused-vars
  129:45  warning  The href attribute is required on an anchor. Provide a valid, navigable address as the href value  jsx-a11y/anchor-is-valid
  130:45  warning  The href attribute is required on an anchor. Provide a valid, navigable address as the href value  jsx-a11y/anchor-is-valid
  163:13  error    Cannot query field "mongodbTestGuides" on type "RootQueryType"                                     graphql/template-strings
  200:1   warning  Block is redundant                                                                                 no-lone-blocks

✖ 5 problems (1 error, 4 warnings)

 @ ./.cache/sync-requires.js 14:50-160
 @ ./.cache/root.js
 @ ./.cache/app.js
 @ multi ./node_modules/react-hot-loader/patch.js (webpack)-hot-middleware/client.js?path=http://localhost:8000/__webpack_hmr&reload=true&overlay=false ./.cache/app
ℹ ｢wdm｣: Failed to compile.
```
Do you have something similar?

**Comment by Chuloo** [comment]
Could you verify your database source, is it a cloud DB? Probably specify it in `gatsby-config.js`.

**Comment by Amanpreet-03** [comment]
Yes, I got similar error

**Comment by Chuloo** [comment]
@Amanpreet-03 looked through this with @pieh, couldn't reproduce your error. Verified the multiple collections feature with the [using-mongodb](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-mongodb) example and it works.
We also tried to reproduce your error using our database and couldn't as well.

Probably your error is from your database structure, you can retry with a cloud database. Also, create a mock of the database and include it in your reproduction, would be really helpful.
