### ISSUE TITLE
gatsby-plugin-preval doesn't support import comments

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#7042]
## Description

I tried to use Import comments and `preval.require` with my plugin gatsby-plugin-preval, but they don't work (see https://github.com/kripod/gatsby-plugin-preval/issues/1).

### Steps to reproduce

1. Set up a gatsby@2 project
2. `yarn add gatsby-plugin-preval babel-plugin-preval git-rev-sync`
3. Use one of the following statements on a page:

```js
import { short } from /* preval */ 'git-rev-sync';
```

```js
const { short } = preval.require('git-rev-sync');
```

### Actual result

```
i ｢wdm｣: Compiling...
 ERROR  Failed to compile with 1 errors                                                                         10:10:12
 
 error  in ./src/components/Layout.jsx
 
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'D:\Development\moc-ui\src\components\git-rev-sync'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.require.resolve (D:\Development\moc-ui\node_modules\v8-compile-cache\v8-compile-cache.js:162:23)
    at PluginPass.CallExpression (D:\Development\moc-ui\node_modules\babel-plugin-preval\dist\index.js:126:44)
    at newFn (D:\Development\moc-ui\node_modules\@babel\traverse\lib\visitors.js:193:21)
    at NodePath._call (D:\Development\moc-ui\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (D:\Development\moc-ui\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (D:\Development\moc-ui\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (D:\Development\moc-ui\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitSingle (D:\Development\moc-ui\node_modules\@babel\traverse\lib\context.js:90:19)
    at TraversalContext.visit (D:\Development\moc-ui\node_modules\@babel\traverse\lib\context.js:146:19)
    at Function.traverse.node (D:\Development\moc-ui\node_modules\@babel\traverse\lib\index.js:94:17)
    at NodePath.visit (D:\Development\moc-ui\node_modules\@babel\traverse\lib\path\context.js:95:18)
    at TraversalContext.visitQueue (D:\Development\moc-ui\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitMultiple (D:\Development\moc-ui\node_modules\@babel\traverse\lib\context.js:85:17)
    at TraversalContext.visit (D:\Development\moc-ui\node_modules\@babel\traverse\lib\context.js:144:19)
    at Function.traverse.node (D:\Development\moc-ui\node_modules\@babel\traverse\lib\index.js:94:17)
 
 @ ./src/pages/404.jsx 12:0-42 16:29-35
 @ ./.cache/sync-requires.js
 @ ./.cache/root.js
 @ ./.cache/app.js
 @ multi ./node_modules/react-hot-loader/patch.js (webpack)-hot-middleware/client.js?path=http://localhost:8000/__webpack_hmr&reload=true&overlay=false D://Development//moc-ui//.cache//app
 
× ｢wdm｣:
ERROR in ./src/components/Layout.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'D:\Development\moc-ui\src\components\git-rev-sync'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.require.resolve (D:\Development\moc-ui\node_modules\v8-compile-cache\v8-compile-cache.js:162:23)
    at PluginPass.CallExpression (D:\Development\moc-ui\node_modules\babel-plugin-preval\dist\index.js:126:44)
    at newFn (D:\Development\moc-ui\node_modules\@babel\traverse\lib\visitors.js:193:21)
    at NodePath._call (D:\Development\moc-ui\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (D:\Development\moc-ui\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (D:\Development\moc-ui\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (D:\Development\moc-ui\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitSingle (D:\Development\moc-ui\node_modules\@babel\traverse\lib\context.js:90:19)
    at TraversalContext.visit (D:\Development\moc-ui\node_modules\@babel\traverse\lib\context.js:146:19)
    at Function.traverse.node (D:\Development\moc-ui\node_modules\@babel\traverse\lib\index.js:94:17)
    at NodePath.visit (D:\Development\moc-ui\node_modules\@babel\traverse\lib\path\context.js:95:18)
    at TraversalContext.visitQueue (D:\Development\moc-ui\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitMultiple (D:\Development\moc-ui\node_modules\@babel\traverse\lib\context.js:85:17)
    at TraversalContext.visit (D:\Development\moc-ui\node_modules\@babel\traverse\lib\context.js:144:19)
    at Function.traverse.node (D:\Development\moc-ui\node_modules\@babel\traverse\lib\index.js:94:17)
 @ ./src/pages/404.jsx 12:0-42 16:29-35
 @ ./.cache/sync-requires.js
 @ ./.cache/root.js
 @ ./.cache/app.js
 @ multi ./node_modules/react-hot-loader/patch.js (webpack)-hot-middleware/client.js?path=http://localhost:8000/__webpack_hmr&reload=true&overlay=false D://Development//moc-ui//.cache//app
i ｢wdm｣: Failed to compile.
```

### Environment

```
  System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
  Binaries:
    Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.0-beta.61 => 2.0.0-beta.69
    gatsby-plugin-preval: ^1.0.0 => 1.0.0
```

### File contents (if changed)

`gatsby-config.js`:

```js
module.exports = {
  plugins: ['gatsby-plugin-preval'],
};
```

**Comment by Chuloo** [comment]
Hi @kripod seems this is related to #6850.
