### ISSUE TITLE
[1.0] How to use SCSS?

### ISSUE THREAD

**Issue by mojodna** [gatsbyjs/gatsby#728]
(It looks like it's no longer included by default in 1.0.)

`gatsby-node.js` contains:

```javascript
exports.modifyWebpackConfig = ({ args }) => {
  const { config } = args

  config.loader('scss', cfg => {
    cfg.test = /\.scss$/
    cfg.loaders = ["style-loader", "css-loader", "sass-loader"]

    return cfg
  })

  return config
}
```

This leads to the same problem as #143. By only registering the `scss` loader during `build-css` and `build-javascript`, it kind of works, although during the `build-html` stage, `css/styles.scss` can't be loaded (it wants an appropriate loader). It's referenced in https://github.com/mojodna/posm.io/blob/master/layouts/default.js#L7

(I'd also like to be able to load `foundation-sites/scss/foundation.scss` instead of the minified CSS using the Webpack loader, but I can't figure out how to get it to resolve that correctly.)

Help? Repo w/ a working development version is here: https://github.com/mojodna/posm.io

Thanks!

**Comment by mojodna** [comment]
```javascript
exports.modifyWebpackConfig = ({ args }) => {
  const { config, stage } = args

  console.log("stage:", stage)

  switch (stage) {
    case "develop":
      config.loader("sass", {
        test: /\.(sass|scss)$/,
        exclude: /\.module\.(sass|scss)$/,
        loaders: ["style", "css", "postcss", "sass"],
      })

      break

    case "build-css":
      config.loader("sass", {
        test: /\.(sass|scss)$/,
        exclude: /\.module\.(sass|scss)$/,
        loader: ExtractTextPlugin.extract(["css?minimize", "postcss", "sass"]),
      })

      break

    case "build-html":
      config.loader("sass", {
        test: /\.(sass|scss)$/,
        exclude: /\.module\.(sass|scss)$/,
        loader: "null",
      })

      break

    case "build-javascript":
      config.loader("sass", {
        test: /\.(sass|scss)$/,
        exclude: /\.module\.(sass|scss)$/,
        loader: "null",
      })

      break
  }

  return config
}
```

results in:

```
...
Generating CSS
calling api handler in /Users/seth/src/americanredcross/posm.io for api modifyWebpackConfig
stage: build-css
Compiling production bundle.js
calling api handler in /Users/seth/src/americanredcross/posm.io for api modifyWebpackConfig
stage: build-javascript
Generating Static HTML
calling api handler in /Users/seth/src/americanredcross/posm.io for api modifyWebpackConfig
stage: build-html
Generating HTML failed Error: Error: The style-loader cannot be used in a non-browser environment
    at module.exports (render-page.js:46964:43)
    at Object.<anonymous> (render-page.js:46850:39)
    at __webpack_require__ (render-page.js:30:30)
    at Object.<anonymous> (render-page.js:46626:2)
    at __webpack_require__ (render-page.js:30:30)
    at Object.defineProperty.value (render-page.js:44635:17)
    at __webpack_require__ (render-page.js:30:30)
    at Object.exports.__esModule (render-page.js:83:21)
    at __webpack_require__ (render-page.js:30:30)
    at render-page.js:50:18
Running postBuild plugins
Done
```

**Comment by KyleAMathews** [comment]
Check out the config for the current version of Gatsby and copy that. Basically you need different configuration for the different build stages.

Search for "scss" in this file: https://github.com/gatsbyjs/gatsby/blob/master/lib/utils/webpack.config.js#L310

**Comment by KyleAMathews** [comment]
If you feel up to it, my thought is all the common styling options should have official Gatsby plugins. So if you wanted to add a PR sometime to add `gatsby-plugin-sass` that'd be great!

**Comment by mojodna** [comment]
(Disregard that last update; I had some code that was explicitly using the style loader with `!style!`. Still debugging...)

**Comment by mojodna** [comment]
Perhaps, perhaps (re: `gatsby-plugin-sass`). I'll be doing a bunch of work using Gatsby in the next few weeks and will try to sneak it in during the process.

FTR, this ended up being the solution:

```javascript
exports.modifyWebpackConfig = ({ args }) => {
  const { config, stage } = args

  switch (stage) {
    case "develop":
      config.loader("sass", {
        test: /\.(sass|scss)$/,
        exclude: /\.module\.(sass|scss)$/,
        loaders: ["style", "css", "postcss", "sass"],
      })

      break

    case "build-css":
      config.loader("sass", {
        test: /\.(sass|scss)$/,
        exclude: /\.module\.(sass|scss)$/,
        loader: ExtractTextPlugin.extract(["css?minimize", "postcss", "sass"]),
      })

      break

    case "build-html":
      config.loader("sass", {
        test: /\.(sass|scss)$/,
        exclude: /\.module\.(sass|scss)$/,
        loader: "null",
      })

      break

    case "build-javascript":
      config.loader("sass", {
        test: /\.(sass|scss)$/,
        exclude: /\.module\.(sass|scss)$/,
        loader: "null",
      })

      break
  }

  return config
}
```

**Comment by 3stacks** [comment]
@KyleAMathews Might I suggest that instead of linking to files, you could paste a snippet, because I've seen a couple issues that definitely have historical relevance where you've linked out to a file that now 404s. This one is still a bit of a mystery for me
