### ISSUE TITLE
"gatsby build" fails because of bootstrap

### ISSUE THREAD

**Issue by enriquemorenotent** [gatsbyjs/gatsby#7452]
> package.json
```
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "bootstrap": "^4.1.3",
    "gatsby": "^1.9.277",
    "gatsby-link": "^1.6.46",
    "gatsby-plugin-react-helmet": "^2.0.11",
    "gatsby-plugin-sass": "^1.0.26",
    "jquery": "^3.3.1",
    "popper.js": "^1.14.4",
    "react-helmet": "^5.2.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write 'src/**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.13.7"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  }
}
```

> gatbsy build

```
$ gatsby build       
success delete html and css files from previous builds — 0.011 s
success open and validate gatsby-config — 0.006 s
success copy gatsby files — 0.025 s
success onPreBootstrap — 0.017 s
success source and transform nodes — 0.019 s
success building schema — 0.115 s
success createLayouts — 0.039 s
success createPages — 0.001 s
success createPagesStatefully — 0.040 s
success onPreExtractQueries — 0.001 s
success update schema — 0.080 s
success extract queries from components — 0.037 s
success run graphql queries — 0.022 s
success write out page data — 0.004 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.001 s

info bootstrap finished - 1.89 s

success Building CSS — 9.098 s

error Generating JavaScript bundles failed


  Error: ./src/layouts/index.css
  Module build failed: ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' ./bootstrap   in /home/dbugger/projects/personal/cosmetic-salon-huebner/src/layouts
      at /home/dbugger/projects/personal/cosmetic-salon-huebner/node_modules/webpack/lib/Compilation.js:229:38
      at onDoneResolving (/home/dbugger/projects/personal/cosmetic-salon-huebner/node_modules/webpack/lib/NormalModule  Factory.js:29:20)
      at /home/dbugger/projects/personal/cosmetic-salon-huebner/node_modules/webpack/lib/NormalModuleFactory.js:85:20
      at /home/dbugger/projects/personal/cosmetic-salon-huebner/node_modules/webpack/node_modules/async/lib/async.js:7  26:13
      at /home/dbugger/projects/personal/cosmetic-salon-huebner/node_modules/webpack/node_modules/async/lib/async.js:5  2:16
      at done (/home/dbugger/projects/personal/cosmetic-salon-huebner/node_modules/webpack/node_modules/async/lib/asyn  c.js:241:17)
      at /home/dbugger/projects/personal/cosmetic-salon-huebner/node_modules/webpack/node_modules/async/lib/async.js:4  4:16
      at /home/dbugger/projects/personal/cosmetic-salon-huebner/node_modules/webpack/node_modules/async/lib/async.js:7  23:17
      at /home/dbugger/projects/personal/cosmetic-salon-huebner/node_modules/webpack/node_modules/async/lib/async.js:1  67:37
      at /home/dbugger/projects/personal/cosmetic-salon-huebner/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js  :24:19
      at onResolved (/home/dbugger/projects/personal/cosmetic-salon-huebner/node_modules/enhanced-resolve/lib/Resolver  .js:38:18)
      at /home/dbugger/projects/personal/cosmetic-salon-huebner/node_modules/enhanced-resolve/lib/Resolver.js:127:10
      at /home/dbugger/projects/personal/cosmetic-salon-huebner/node_modules/enhanced-resolve/lib/Resolver.js:191:15
      at applyPluginsParallelBailResult.createInnerCallback.log (/home/dbugger/projects/personal/cosmetic-salon-huebne  r/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
      at loggingCallbackWrapper (/home/dbugger/projects/personal/cosmetic-salon-huebner/node_modules/enhanced-resolve/  lib/createInnerCallback.js:21:19)
      at /home/dbugger/projects/personal/cosmetic-salon-huebner/node_modules/tapable/lib/Tapable.js:134:6
      at Resolver.<anonymous> (/home/dbugger/projects/personal/cosmetic-salon-huebner/node_modules/enhanced-resolve/li  b/DirectoryDescriptionFilePlugin.js:24:12)
      at Storage.finished (/home/dbugger/projects/personal/cosmetic-salon-huebner/node_modules/enhanced-resolve/lib/Ca  chedInputFileSystem.js:38:16)
      at ReadFileContext.callback (/home/dbugger/projects/personal/cosmetic-salon-huebner/node_modules/graceful-fs/gra  ceful-fs.js:78:16)
      at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:320:13)
   @ ./src/layouts/index.js 26:0-22

```

**Comment by enriquemorenotent** [comment]
https://bitbucket.org/enmotent/cosmetic-salon-huebner/

**Comment by azdanov** [comment]
Okay, I've had a look.

The problem is with `/src/layouts/index.css`.

Inside on the first line `@import "bootstrap";` can't be resolved, and it throws an error.
When I change this line to `@import "~bulma";` or remove this line, I can compile.

So either `bootstrap` needs to be installed, or `bulma` can be used since it's already in the dependencies.

**Comment by enriquemorenotent** [comment]
@azdanov But Bootstrap is already installed. It is set as a dependency in `package.json`

**Comment by azdanov** [comment]
@enriquemorenotent Oh, didn't notice. Thanks for pointing out.

Then you need to use `@import "~bootstrap";`. `~` is used to reference something that's inside `node_modules`.

**Comment by enriquemorenotent** [comment]
In that case I get a different error https://pastebin.com/raw/LD8C5np3

I have updated the repo, if you want to reproduce it

**Comment by enriquemorenotent** [comment]
I agree with that last statement, and that is why I have decided to stop all my Gatsby projects, until v2 comes out.

Thanks for the help!
