### ISSUE TITLE
Upgrade to v2beta:  Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by ghernando** [gatsbyjs/gatsby#7665]
I'm pretty new to Gatsby and now facing an upgrade to v2.
The project I have worked in v1.

I'm seeing this error below and the server won't start.

-----------------------------------------------------------------------
It is maybe related to the file /src/html.tsx.
There is the following code in that file:

```
// Use `module.exports` to be compliant with `webpack-require` import method
module.exports = (props: HtmlProps) => {
  const head = Helmet.rewind();
```

-----------------------------------------------------------------------

There was an error requiring "src/html.js"

 TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.<anonymous> (C:\Gatsby2\proj\public\render-page.js:2417:16)
    at Module../src/html.tsx (C:\Gatsby2\proj\public\render-page.js:2441:30)
    at __webpack_require__ (C:\Gatsby2\proj\public\render-page.js:30:30)
    at Module../.cache/develop-static-entry.js (C:\Gatsby2\proj\public\render-page.js:491:10)
    at __webpack_require__ (C:\Gatsby2\proj\public\render-page.js:30:30)
    at C:\Gatsby2\proj\public\render-page.js:94:18
    at C:\Gatsby2\proj\public\render-page.js:97:10
    at webpackUniversalModuleDefinition (C:\Gatsby2\proj\public\render-page.js:3:20)
    at Object.<anonymous> (C:\Gatsby2\proj\public\render-page.js:10:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)

**Comment by ghernando** [comment]
How do I go about including a repository?

**Comment by ghernando** [comment]
How do I include a repository?

**Comment by azdanov** [comment]
Upload a Gatsby project that has this issue to GitHub.
