### ISSUE TITLE
GraphQLError: Cannot query field "slug" on type "SitePage"

### ISSUE THREAD

**Issue by aks84** [gatsbyjs/gatsby#7757]
I had a similar issue like [6654](https://github.com/gatsbyjs/gatsby/issues/6654) after that I ran into this issue. 

Please help! Thanks to the Great GatsbyJS community!

**$ gatsby develop**

success delete html and css files from previous builds — 0.027 s
success open and validate gatsby-config — 0.006 s
success copy gatsby files — 0.015 s
success onPreBootstrap — 0.042 s
⠈ source and transform nodes -> wordpress__akismet_v1 fetched : 1
⠂ source and transform nodesThe server response was "401 Unauthorized"
Inner exception message : "Sorry, you are not allowed to do that."
⠂ source and transform nodesThe server response was "401 Unauthorized"
Inner exception message : "Sorry, you are not allowed to do that."
⠈ source and transform nodesThe server response was "401 Unauthorized"
Inner exception message : "Sorry, you are not allowed to do that."
⠄ source and transform nodes -> wordpress__contact_form_7_v1 fetched : 1
⡀ source and transform nodesThe server response was "403 Forbidden"
Inner exception message : "You are not allowed to access contact forms."
⠄ source and transform nodes -> wordpress__redirection_v1 fetched : 1
⢀ source and transform nodesThe server response was "401 Unauthorized"
Inner exception message : "Sorry, you are not allowed to do that."
⠄ source and transform nodesThe server response was "401 Unauthorized"
Inner exception message : "Sorry, you are not allowed to do that."
⠄ source and transform nodesThe server response was "401 Unauthorized"
Inner exception message : "Sorry, you are not allowed to do that."
⠠ source and transform nodesThe server response was "401 Unauthorized"
Inner exception message : "Sorry, you are not allowed to do that."
⠈ source and transform nodesThe server response was "401 Unauthorized"
Inner exception message : "Sorry, you are not allowed to do that."
⠂ source and transform nodesThe server response was "401 Unauthorized"
Inner exception message : "Sorry, you are not allowed to do that."
⠄ source and transform nodesThe server response was "404 Not Found"
Inner exception message : "No route was found matching the URL and request method"
⠁ source and transform nodesThe server response was "404 Not Found"
Inner exception message : "No route was found matching the URL and request method"
⠂ source and transform nodesThe server response was "401 Unauthorized"
Inner exception message : "Sorry, you are not allowed to do that."
⠂ source and transform nodes -> wordpress__shariff_v1 fetched : 1
⠠ source and transform nodesThe server response was "400 Bad Request"
Inner exception message : "Missing parameter(s): url, services"
⠠ source and transform nodes -> wordpress__yoast_v1 fetched : 1
⠈ source and transform nodesThe server response was "401 Unauthorized"
Inner exception message : "Sorry, you are not allowed to do that."
⠐ source and transform nodesThe server response was "401 Unauthorized"
Inner exception message : "Sorry, you are not allowed to do that."
⢀ source and transform nodesThe server response was "401 Unauthorized"
Inner exception message : "Sorry, you are not allowed to do that."
⠄ source and transform nodesThe server response was "401 Unauthorized"
Inner exception message : "Sorry, you are not allowed to do that."
⠂ source and transform nodes -> wordpress__hummingbird_v1 fetched : 1
⠈ source and transform nodes -> wordpress__hummingbird_test fetched : 1
⠄ source and transform nodes -> wordpress__POST fetched : 37
⠐ source and transform nodes -> wordpress__PAGE fetched : 6
⠁ source and transform nodes -> wordpress__wp_media fetched : 185
⠄ source and transform nodes -> wordpress__wp_types fetched : 1
⢀ source and transform nodes -> wordpress__wp_statuses fetched : 1
⠁ source and transform nodes -> wordpress__wp_taxonomies fetched : 1
⠁ source and transform nodes -> wordpress__CATEGORY fetched : 13
⢀ source and transform nodes -> wordpress__TAG fetched : 3
⠄ source and transform nodesThe server response was "403 Forbidden"
⠠ source and transform nodesThe server response was "401 Unauthorized"
Inner exception message : "You are not currently logged in."
⠠ source and transform nodes -> wordpress__wp_comments fetched : 0
⠈ source and transform nodesThe server response was "401 Unauthorized"
Inner exception message : "Sorry, you are not allowed to do that."
success source and transform nodes — 101.109 s
success building schema — 0.473 s
success createLayouts — 0.020 s
⠁ [ { GraphQLError: Cannot query field "slug" on type "SitePage".
    at Object.Field (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:65:31)
    at Object.enter (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/language/visitor.js:295:29)
    at Object.enter (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/language/visitor.js:337:25)
    at visit (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/language/visitor.js:227:26)
    at visitUsingRules (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/validation/validate.js:75:22)
    at validate (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/validation/validate.js:60:10)
    at /home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/graphql.js:69:51
    at Promise._execute (/usr/lib/node_modules/gatsby-cli/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/usr/lib/node_modules/gatsby-cli/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/lib/node_modules/gatsby-cli/node_modules/bluebird/js/release/promise.js:79:10)
    at graphqlImpl (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/graphql.js:59:10)
    at graphql (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/graphql.js:48:227)
    at graphqlRunner (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/gatsby/dist/bootstrap/index.js:368:22)
    at Promise (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/gatsby-node.js:21:5)
    at Promise._execute (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/bluebird/js/release/promise.js:79:10)
    at Object.exports.createPages (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/gatsby-node.js:14:10)
    at runAPI (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/gatsby/dist/utils/api-runner-node.js:110:36)
    at /home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/gatsby/dist/utils/api-runner-node.js:187:33
    at /home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/async/internal/map.js:27:9
    at replenish (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/async/internal/eachOfLimit.js:66:17)
    message: 'Cannot query field "slug" on type "SitePage".',
    locations: [ [Object] ],
    path: undefined },
  { GraphQLError: Cannot query field "status" on type "SitePage".
    at Object.Field (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:65:31)
    at Object.enter (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/language/visitor.js:295:29)
    at Object.enter (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/language/visitor.js:337:25)
    at visit (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/language/visitor.js:227:26)
    at visitUsingRules (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/validation/validate.js:75:22)
    at validate (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/validation/validate.js:60:10)
    at /home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/graphql.js:69:51
    at Promise._execute (/usr/lib/node_modules/gatsby-cli/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/usr/lib/node_modules/gatsby-cli/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/lib/node_modules/gatsby-cli/node_modules/bluebird/js/release/promise.js:79:10)
    at graphqlImpl (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/graphql.js:59:10)
    at graphql (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/graphql.js:48:227)
    at graphqlRunner (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/gatsby/dist/bootstrap/index.js:368:22)
    at Promise (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/gatsby-node.js:21:5)
    at Promise._execute (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/bluebird/js/release/promise.js:79:10)
    at Object.exports.createPages (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/gatsby-node.js:14:10)
    at runAPI (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/gatsby/dist/utils/api-runner-node.js:110:36)
    at /home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/gatsby/dist/utils/api-runner-node.js:187:33
    at /home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/async/internal/map.js:27:9
    at replenish (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/async/internal/eachOfLimit.js:66:17)
    message: 'Cannot query field "status" on type "SitePage".',
    locations: [ [Object] ],
    path: undefined },
  { GraphQLError: Cannot query field "template" on type "SitePage".
    at Object.Field (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:65:31)
    at Object.enter (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/language/visitor.js:295:29)
    at Object.enter (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/language/visitor.js:337:25)
    at visit (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/language/visitor.js:227:26)
    at visitUsingRules (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/validation/validate.js:75:22)
    at validate (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/validation/validate.js:60:10)
    at /home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/graphql.js:69:51
    at Promise._execute (/usr/lib/node_modules/gatsby-cli/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/usr/lib/node_modules/gatsby-cli/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/lib/node_modules/gatsby-cli/node_modules/bluebird/js/release/promise.js:79:10)
    at graphqlImpl (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/graphql.js:59:10)
    at graphql (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/graphql/graphql.js:48:227)
    at graphqlRunner (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/gatsby/dist/bootstrap/index.js:368:22)
    at Promise (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/gatsby-node.js:21:5)
    at Promise._execute (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/bluebird/js/release/promise.js:79:10)
    at Object.exports.createPages (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/gatsby-node.js:14:10)
    at runAPI (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/gatsby/dist/utils/api-runner-node.js:110:36)
    at /home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/gatsby/dist/utils/api-runner-node.js:187:33
    at /home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/async/internal/map.js:27:9
    at replenish (/home/shahi/Desktop/tubemint/gatsby-wordpress-starter/node_modules/async/internal/eachOfLimit.js:66:17)
    message: 'Cannot query field "template" on type "SitePage".',
    locations: [ [Object] ],
    path: undefined } ]
error gatsby-node.js returned an error

  GraphQLError: Cannot query field "slug" on type "SitePage".
  
  - debuggability.js:303 Promise._execute
    [lib]/[gatsby-cli]/[bluebird]/js/release/debuggability.js:303:9
  
  - promise.js:483 Promise._resolveFromExecutor
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:483:18
  
  - promise.js:79 new Promise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:79:10
  
  - index.js:368 graphqlRunner
    [gatsby-wordpress-starter]/[gatsby]/dist/bootstrap/index.js:368:22
  
  - gatsby-node.js:21 Promise
    /home/shahi/Desktop/tubemint/gatsby-wordpress-starter/gatsby-node.js:21    :5
  
  - debuggability.js:303 Promise._execute
    [gatsby-wordpress-starter]/[bluebird]/js/release/debuggability.js:303:9  
  - promise.js:483 Promise._resolveFromExecutor
    [gatsby-wordpress-starter]/[bluebird]/js/release/promise.js:483:18
  
  - promise.js:79 new Promise
    [gatsby-wordpress-starter]/[bluebird]/js/release/promise.js:79:10
  
  - gatsby-node.js:14 Object.exports.createPages
    /home/shahi/Desktop/tubemint/gatsby-wordpress-starter/gatsby-node.js:14    :10
  
  - api-runner-node.js:110 runAPI
    [gatsby-wordpress-starter]/[gatsby]/dist/utils/api-runner-node.js:110:3    6
  
  - api-runner-node.js:187 
    [gatsby-wordpress-starter]/[gatsby]/dist/utils/api-runner-node.js:187:3    3
  
  - map.js:27 
    [gatsby-wordpress-starter]/[async]/internal/map.js:27:9
  
  - eachOfLimit.js:66 replenish
    [gatsby-wordpress-starter]/[async]/internal/eachOfLimit.js:66:17
  

  GraphQLError: Cannot query field "status" on type "SitePage".
  
  - debuggability.js:303 Promise._execute
    [lib]/[gatsby-cli]/[bluebird]/js/release/debuggability.js:303:9
  
  - promise.js:483 Promise._resolveFromExecutor
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:483:18
  
  - promise.js:79 new Promise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:79:10
  
  - index.js:368 graphqlRunner
    [gatsby-wordpress-starter]/[gatsby]/dist/bootstrap/index.js:368:22
  
  - gatsby-node.js:21 Promise
    /home/shahi/Desktop/tubemint/gatsby-wordpress-starter/gatsby-node.js:21    :5
  
  - debuggability.js:303 Promise._execute
    [gatsby-wordpress-starter]/[bluebird]/js/release/debuggability.js:303:9  
  - promise.js:483 Promise._resolveFromExecutor
    [gatsby-wordpress-starter]/[bluebird]/js/release/promise.js:483:18
  
  - promise.js:79 new Promise
    [gatsby-wordpress-starter]/[bluebird]/js/release/promise.js:79:10
  
  - gatsby-node.js:14 Object.exports.createPages
    /home/shahi/Desktop/tubemint/gatsby-wordpress-starter/gatsby-node.js:14    :10
  
  - api-runner-node.js:110 runAPI
    [gatsby-wordpress-starter]/[gatsby]/dist/utils/api-runner-node.js:110:3    6
  
  - api-runner-node.js:187 
    [gatsby-wordpress-starter]/[gatsby]/dist/utils/api-runner-node.js:187:3    3
  
  - map.js:27 
    [gatsby-wordpress-starter]/[async]/internal/map.js:27:9
  
  - eachOfLimit.js:66 replenish
    [gatsby-wordpress-starter]/[async]/internal/eachOfLimit.js:66:17
  

  GraphQLError: Cannot query field "template" on type "SitePage".
  
  - debuggability.js:303 Promise._execute
    [lib]/[gatsby-cli]/[bluebird]/js/release/debuggability.js:303:9
  
  - promise.js:483 Promise._resolveFromExecutor
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:483:18
  
  - promise.js:79 new Promise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:79:10
  
  - index.js:368 graphqlRunner
    [gatsby-wordpress-starter]/[gatsby]/dist/bootstrap/index.js:368:22
  
  - gatsby-node.js:21 Promise
    /home/shahi/Desktop/tubemint/gatsby-wordpress-starter/gatsby-node.js:21    :5
  
  - debuggability.js:303 Promise._execute
    [gatsby-wordpress-starter]/[bluebird]/js/release/debuggability.js:303:9  
  - promise.js:483 Promise._resolveFromExecutor
    [gatsby-wordpress-starter]/[bluebird]/js/release/promise.js:483:18
  
  - promise.js:79 new Promise
    [gatsby-wordpress-starter]/[bluebird]/js/release/promise.js:79:10
  
  - gatsby-node.js:14 Object.exports.createPages
    /home/shahi/Desktop/tubemint/gatsby-wordpress-starter/gatsby-node.js:14    :10
  
  - api-runner-node.js:110 runAPI
    [gatsby-wordpress-starter]/[gatsby]/dist/utils/api-runner-node.js:110:3    6
  
  - api-runner-node.js:187 
    [gatsby-wordpress-starter]/[gatsby]/dist/utils/api-runner-node.js:187:3    3
  
  - map.js:27 
    [gatsby-wordpress-starter]/[async]/internal/map.js:27:9
  
  - eachOfLimit.js:66 replenish
    [gatsby-wordpress-starter]/[async]/internal/eachOfLimit.js:66:17
  

error Cannot read property 'allWordpressPage' of undefined

  TypeError: Cannot read property 'allWordpressPage' of undefined
  
  - gatsby-node.js:48 graphql.then.result
    /home/shahi/Desktop/tubemint/gatsby-wordpress-starter/gatsby-node.js:48    :28
  
  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:606 Promise._settlePromiseCtx
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:606:10
  
  - async.js:138 Async._drainQueue
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:138:12
  
  - async.js:143 Async._drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:143:10
  
  - async.js:17 Immediate.Async.drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14
  

error UNHANDLED REJECTION

  TypeError: Cannot read property 'allWordpressPage' of undefined
  
  - gatsby-node.js:48 graphql.then.result
    /home/shahi/Desktop/tubemint/gatsby-wordpress-starter/gatsby-node.js:48    :28
  
  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:606 Promise._settlePromiseCtx
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:606:10
  
  - async.js:138 Async._drainQueue
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:138:12
  
  - async.js:143 Async._drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:143:10
  
  - async.js:17 Immediate.Async.drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14

**Comment by Chuloo** [comment]
what does the graphql query look like? @aks84

**Comment by aks84** [comment]
@Chuloo **Thanks! Here it is.**

```
const _ = require(`lodash`)
const Promise = require(`bluebird`)
const path = require(`path`)
const slash = require(`slash`)


exports.createPages = ({ graphql, boundActionCreators }) => {
  const { createPage } = boundActionCreators
  return new Promise((resolve, reject) => {

    // ==== PAGES (WORDPRESS NATIVE) ====
    graphql(
      `
        {
          allSitePage {
            edges {
              node {
                id
                slug
                status
                template
              }
            }
          }
        }
      `
    )
      .then(result => {
        if (result.errors) {
          console.log(result.errors)
          reject(result.errors)
        }

        // Create Page pages.
        const pageTemplate = path.resolve(`./src/templates/page.js`)
       
        _.each(result.data.allWordpressPage.edges, edge => {
          
          createPage({
            path: `/${edge.node.slug}/`,
            component: slash(pageTemplate),
            context: {
              id: edge.node.id
            }
          })
        })
      })
      // ==== END PAGES ====

      // ==== POSTS (WORDPRESS NATIVE AND ACF) ====
      .then(() => {
        graphql(
          `
            {
              allSitePost {
                edges {
                  node {
                    id
                    slug
                    status
                    template
                    format
                  }
                }
              }
            }
          `
        ).then(result => {
          if (result.errors) {
            console.log(result.errors)
            reject(result.errors)
          }
          const postTemplate = path.resolve(`./src/templates/post.js`)
       
          _.each(result.data.allWordpressPost.edges, edge => {
            createPage({
              path: edge.node.slug,
              component: slash(postTemplate),
              context: {
                id: edge.node.id
              }
            })
          })
          resolve()
        })
      })
    // ==== END POSTS ====
  })
}

```

**Comment by pieh** [comment]
You are quering for `allSitePage` (which will be empty, because those are gatsby pages not wordpress pages). You need to query `allWordpressPost`

**Comment by aks84** [comment]
Thanks, @pieh!! I am going to try...

**Comment by aks84** [comment]
Thanks a lot!! DONE  Compiled successfully in 279ms
