### ISSUE TITLE
Errors installing Typography Plugin

### ISSUE THREAD

**Issue by sethakkerman** [gatsbyjs/gatsby#7799]
Seths-MacBook-Pro-2:tutorial-part-four seth$ npm install --save gatsby-plugin-typography
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:148:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

I am working through the tutorials. It worked when I completed part 2 of the tutorial but now I am getting errors. It seems like Gatsby is always changing so I am not sure if it is something on your end or my end.

**Comment by sethakkerman** [comment]
Trying to work through this:

https://www.gatsbyjs.org/tutorial/part-four/

**Comment by KyleAMathews** [comment]
Sounds like an NPM install error — can you try removing `node_modules` and reinstalling.

**Comment by sethakkerman** [comment]
@KyleAMathews Is that globally or in the local directory? I tried removing it and reinstalling with npm update and npm install and it gave me the same error as above.

**Comment by KyleAMathews** [comment]
Locally. `gatsby-cli` is just a shell which calls the locally installed packages. Remove the directory and just run `npm install`. Or perhaps try Yarn which many people find more reliable.

**Comment by sethakkerman** [comment]
@KyleAMathews Thanks for your help! Much appreciated. I will try that.
