### ISSUE TITLE
SyntaxError: Unexpected token ...  Math.max(...widths);

### ISSUE THREAD

**Issue by alexfinchme** [gatsbyjs/gatsby#8023]
## Description

SyntaxError: Unexpected token ...  Math.max(...widths);

node -v
v4.2.6

### Steps to reproduce

Create fresh ubuntu 16 box on digital ocean and login as root. Run the following commands
    
   apt update
    apt dist-upgrade -y
    apt install npm
    npm install --global gatsby-cli
   gatsby new my-blazing-fast-site

### Expected result

Gatsby site created

### Actual result

gatsby new gatsby-site https://github.com/gatsbyjs/gatsby-starter-default#v2
/usr/bin/env: ‘node’: No such file or directory
root@paxosone:/paxos# ln -fs /usr/bin/nodejs /usr/local/bin/node
root@paxosone:/paxos# gatsby new gatsby-site https://github.com/gatsbyjs/gatsby-starter-default#v2
/usr/local/lib/node_modules/gatsby-cli/node_modules/yurnalist/dist/reporters/console/console-reporter.js:111
      cols[i] = Math.max(...widths);
                         ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at _load_consoleReporter (/usr/local/lib/node_modules/gatsby-cli/node_modules/yurnalist/dist/index.js:6:52)
    at createReporter (/usr/local/lib/node_modules/gatsby-cli/node_modules/yurnalist/dist/index.js:19:45)
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby-cli/node_modules/yurnalist/dist/index.js:33:18)

root@paxosone:/paxos# gatsby new my-blazing-fast-site
/usr/local/lib/node_modules/gatsby-cli/node_modules/yurnalist/dist/reporters/console/console-reporter.js:111
      cols[i] = Math.max(...widths);
                         ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at _load_consoleReporter (/usr/local/lib/node_modules/gatsby-cli/node_modules/yurnalist/dist/index.js:6:52)
    at createReporter (/usr/local/lib/node_modules/gatsby-cli/node_modules/yurnalist/dist/index.js:19:45)
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby-cli/node_modules/yurnalist/dist/index.js:33:18)

### Environment

Run `gatsby info --clipboard`
/usr/local/lib/node_modules/gatsby-cli/node_modules/yurnalist/dist/reporters/console/console-reporter.js:111
      cols[i] = Math.max(...widths);
                         ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at _load_consoleReporter (/usr/local/lib/node_modules/gatsby-cli/node_modules/yurnalist/dist/index.js:6:52)
    at createReporter (/usr/local/lib/node_modules/gatsby-cli/node_modules/yurnalist/dist/index.js:19:45)
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby-cli/node_modules/yurnalist/dist/index.js:33:18)

**Comment by alexfinchme** [comment]
I just had to install the latest stable version of node and the error went away

sudo npm cache clean -f
sudo npm install -g n
sudo n stable
