### ISSUE TITLE
[1.0] Cannot find module 'graphql-skip-limit' from 'run-sift.js'

### ISSUE THREAD

**Issue by 0x80** [gatsbyjs/gatsby#816]
I am trying to play with 1.0 following [these steps](https://github.com/gatsbyjs/gatsby/blob/1.0/CONTRIBUTING.md )

`yarn run test` gives me the following error:

```shell
Test suite failed to run

    Cannot find module 'graphql-skip-limit' from 'run-sift.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (packages/gatsby/lib/schema/run-sift.js:4:1)
```

The Lerna bootstrap before that seemed ok to me

```
❯ yarn && lerna bootstrap
yarn install v0.22.0
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ lerna bootstrap
Lerna v2.0.0-beta.38
Bootstrapping 27 packages
Preinstalling packages
Installing external dependencies
Symlinking packages and binaries
Postinstalling packages
Prepublishing packages
Successfully bootstrapped 27 packages.
✨  Done in 2.21s.
Lerna v2.0.0-rc.2
Bootstrapping 27 packages
Preinstalling packages
Installing external dependencies
Symlinking packages and binaries
Postinstalling packages
Prepublishing packages
Successfully bootstrapped 27 packages.
```

**Comment by KyleAMathews** [comment]
Is this still a problem?

**Comment by 0x80** [comment]
@KyleAMathews I guess not. Running the tests on the 1.0 head now gives me a different error.

```shell
 PASS  packages/gatsby/lib/schema/__tests__/infer-graphql-type-test.js
  ✓ Infers graphql type from array of nodes (1632ms)

 FAIL  packages/gatsby/lib/schema/__tests__/infer-graphql-input-type.js
  ● GraphQL Input args › encountered a declaration exception

    RootQueryType.allNode field type must be Output Type but got: TestConnection.
```

**Comment by KyleAMathews** [comment]
Gah, that's a duplicate graphql error. That error shows up everywhere.
Delete "graphql" from packages/graphql-skip-limit/node_modules and you
should be fine.

**Comment by 0x80** [comment]
If I do that I get the following error

```shell
 FAIL  packages/graphql-skip-limit/src/connection/__tests__/connection.js
  ● Test suite failed to run

    Cannot find module 'graphql' from 'connection.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (packages/graphql-skip-limit/src/connection/__tests__/connection.js:1:374)

 PASS  packages/graphql-skip-limit/src/connection/__tests__/arrayconnection.js
  connectionFromArray()
```

Then I ran `lerna bootstrap` again and running the tests then gives me this one plus the previous error.
