### ISSUE TITLE
[1.0] copy node_modules folder with gatsby-dev cli

### ISSUE THREAD

**Issue by rewop** [gatsbyjs/gatsby#827]
When copying modules `gatsby-dev` cli, and running `gatsby develop` in my repository, I encounter the following error:
```
Gatsby: Local install exists but failed to load it.
{ Error: Cannot find module 'level'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/rewop/gocode/src/github.com/housinganywhere/apollo-gatsby/node_modules/gatsby/dist/utils/cache.js:3:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/rewop/gocode/src/github.com/housinganywhere/apollo-gatsby/node_modules/gatsby/dist/utils/api-runner-node.js:26:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32) code: 'MODULE_NOT_FOUND' }
```

This happens because after the commit https://github.com/gatsbyjs/gatsby/commit/e7ad98dce032ebab84469ad1a1312a382fa26e09 `level` is now a dependency  that is not installed with `npm install` in my repository.

**Comment by KyleAMathews** [comment]
This unfortunately isn't a viable solution because of how npm's install algorithm works. NPM de-duplicates modules while installing. If you naively copy over another package's node_modules directory, you'll likely have multiple copies of packages which can cause subtle bugs. E.g. GraphQL especially has trouble here as it does a lot of object checks and if you have multiple instances of GraphQL, this will cause their internal checks to fail.

This YARN RFC goes into detail about these problems and one way it could be solved https://github.com/yarnpkg/rfcs/blob/master/text/0000-yarn-knit.md

In the meantime, you'll just have to manually install new dependencies in your sites e.g. in this case, `npm install level` (making sure not to save it).

**Comment by rewop** [comment]
I see what you mean, and I agree that copying node_modules is not the best solution. My mistake was to propose a solution to describe a problem. But the problem still persists, and it makes it hard to contribute to this project. 

How at the initial run of `gatsby-dev`, we check against the repo's package.json for the packages of the package being copied, and we `npm install` the missing modules?

**Comment by KyleAMathews** [comment]
Agree it'd really help if this was fixed.

Want to take a crack at fixing this?
