### ISSUE TITLE
TypeError: _.includes is not a function

### ISSUE THREAD

**Issue by sxu2583** [gatsbyjs/gatsby#8627]
## Summary

When running gatsby I get the below error with gatsby-transformer-sharp 

```
success delete html and css files from previous builds — 0.411 s
success open and validate gatsby-config — 0.019 s
success copy gatsby files — 0.228 s
success onPreBootstrap — 3.824 s
error Plugin gatsby-transformer-sharp returned an error


  TypeError: _.includes is not a function

  - on-node-create.js:27 Object._callee$
    [Thought at Work]/[gatsby-transformer-sharp]/on-node-create.js:27:19

  - on-node-create.js:60 Object.onCreateNode
    [Thought at Work]/[gatsby-transformer-sharp]/on-node-create.js:60:18

  - api-runner-node.js:110 runAPI
    [Thought at Work]/[gatsby]/dist/utils/api-runner-node.js:110:36

  - api-runner-node.js:187
    [Thought at Work]/[gatsby]/dist/utils/api-runner-node.js:187:33

  - map.js:27
    [Thought at Work]/[async]/internal/map.js:27:9

  - eachOfLimit.js:66 replenish
    [Thought at Work]/[async]/internal/eachOfLimit.js:66:17

  - eachOfLimit.js:50 iterateeCallback
    [Thought at Work]/[async]/internal/eachOfLimit.js:50:17

  - onlyOnce.js:12
    [Thought at Work]/[async]/internal/onlyOnce.js:12:16

  - map.js:29
    [Thought at Work]/[async]/internal/map.js:29:13

  - util.js:16 tryCatcher
    [Thought at Work]/[bluebird]/js/release/util.js:16:23

  - nodeify.js:22 Promise.successAdapter [as _fulfillmentHandler0]
    [Thought at Work]/[bluebird]/js/release/nodeify.js:22:30

  - promise.js:566 Promise._settlePromise
    [Thought at Work]/[bluebird]/js/release/promise.js:566:21

  - promise.js:614 Promise._settlePromise0
    [Thought at Work]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [Thought at Work]/[bluebird]/js/release/promise.js:694:18

  - async.js:138 _drainQueueStep
    [Thought at Work]/[bluebird]/js/release/async.js:138:12
```
I think it has to do with a missing or corrupted dependency but Im not sure.

### Environment (if relevant)

```
System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 8.11.3 - D:\Node\node.EXE
    npm: 6.4.1 - D:\Node\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^1.9.277 => 1.9.278
    gatsby-image: ^1.0.43 => 1.0.55
    gatsby-link: ^1.6.40 => 1.6.46
    gatsby-plugin-catch-links: ^1.0.19 => 1.0.24
    gatsby-plugin-google-analytics: ^1.0.31 => 1.0.31
    gatsby-plugin-meta-redirect: ^1.1.0 => 1.1.0
    gatsby-plugin-module-local-ident-name: 0.0.6 => 0.0.6
    gatsby-plugin-react-css-modules: ^1.0.15 => 1.0.15
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11
    gatsby-plugin-sass: ^1.0.26 => 1.0.26
    gatsby-plugin-sharp: ^1.6.48 => 1.6.48
    gatsby-source-filesystem: ^1.5.39 => 1.5.39
    gatsby-transformer-remark: ^1.7.44 => 1.7.44
    gatsby-transformer-sharp: ^1.6.27 => 1.6.27
 npmGlobalPackages:
    gatsby-cli: 2.4.1
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by kakadiadarpan** [comment]
@sxu2583 can you verify if `sharp` module has been properly installed in your machine?
