### ISSUE TITLE
gatsby `main` references es-module

### ISSUE THREAD

**Issue by travi** [gatsbyjs/gatsby#8821]
I'm not sure that calling this a "bug" is necessarily correct, but it seemed like the best category to have the conversation around this. This probably comes down to project conventions, but I'm hoping we can also align to community conventions.

I've been dragging my feet getting upgraded to v2, but thanks to a helpful nudge from @DSchau we're making progress. However, after [upgrading the components](https://github.com/dsmjs/components/tree/gatsby-v2) (separate repo from the [site](https://github.com/dsmjs/site)), the previously working unit tests start erroring.

## Description

<details>
  <summary>stack trace</summary>

```
.../dsmjs/components/node_modules/gatsby/cache-dir/gatsby-browser-entry.js:1
(function (exports, require, module, __filename, __dirname) { import React from "react"
                                                                     ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:73:7)
    at createScript (vm.js:245:10)
    at Object.runInThisContext (vm.js:297:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (.../dsmjs/components/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (.../dsmjs/components/node_modules/gatsby-link/index.js:25:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (.../dsmjs/components/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (.../dsmjs/components/src/atoms/links/internal.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at loader (.../dsmjs/components/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (.../dsmjs/components/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (.../dsmjs/components/src/atoms/archive-list-item/index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at loader (.../dsmjs/components/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (.../dsmjs/components/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (.../dsmjs/components/test/unit/atoms/archive-list-item/presentational-test.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at loader (.../dsmjs/components/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (.../dsmjs/components/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at .../dsmjs/components/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (.../dsmjs/components/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (.../dsmjs/components/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (.../dsmjs/components/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
```

</details>

the trace points to the [import of `gatsby-link`](https://github.com/dsmjs/components/blob/gatsby-v2/src/atoms/links/internal.js#L3), but the error is actually a result of the [`import` statement](https://github.com/gatsbyjs/gatsby/blob/aa579b63efdaef26b0ef239c53f6ac2f0b3da12e/packages/gatsby/cache-dir/gatsby-browser-entry.js#L1) in the [`main`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/package.json#L163) of gatsby. i haven't tracked down how the import of `gatsby-link` results in that, but i imagine you understand that piece better than me.

### Steps to reproduce

1. clone [the repo](https://github.com/dsmjs/components)
1. checkout the `gatsby-v2` branch
1. `nvm install`
1. `npm install`
1. `npm run tests:unit`

### Expected result

tests should execute using a common-js build of the module since the tests are run through mocha using jsdom. (the code within the project [is transpiled](https://github.com/dsmjs/components/blob/b03787e0f3d22f2d612a4e3fbd6e055e650cd46d/test/mocha.opts#L2), but `node_modules/` is not, so gatsby does not get transpiled). 

the community seems to have settled on defining `main` in `package.json` pointing to a common-js build that node uses by default in addition to `module` pointing to an es-module that webpack/rollup/etc can look for instead. i havent run into other modules that have caused transpilation problems like this with mocha/jsdom, so my assumption would have been that gatsby would work similarly.

### Actual result

the gatsby package only defines [`main`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/package.json#L163), but it points to a module [with `import` statements](https://github.com/gatsbyjs/gatsby/blob/aa579b63efdaef26b0ef239c53f6ac2f0b3da12e/packages/gatsby/cache-dir/gatsby-browser-entry.js#L1) without defining this as `module`. 

this results in the error since the mocha tests, run directly by node, can't parse the es-module without pre-transpiling `node_modules/` or pre-bundling, either of which would significantly slow down a tdd cycle. while the impact wouldn't be huge for the linked project, doing so could have a pretty big impact on larger projects (i haven't had to do so on the larger, non-gatsby projects that i maintain using the same testing approach)

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
    Shell: 4.4.23 - /usr/local/bin/bash
  Binaries:
    Node: 10.9.0 - ~/development/dotfiles/nvm/.nvm/versions/node/v10.9.0/bin/node
    npm: 6.2.0 - ~/development/dotfiles/nvm/.nvm/versions/node/v10.9.0/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.18 => 2.0.18 
    gatsby-link: ^2.0.4 => 2.0.4 
```

### Desired Solution

would you be open to building both common-js and es-module versions and defining `main` as common-js and `module` as es-module? since the current build seems to be targeted more specifically at browsers, webpack would use `module` by default, so the browser build behavior should remain essentially the same, but consumption in a node context for things like tests would also be enabled.

if the team would be open to this approach, i'd be open to contributing toward this, but lerna and type-script would be new to me, so i may need some help with the details of those.

**Comment by kakadiadarpan** [comment]
@travi With Gatsby v2, you should not be using `gatsby-link`. Please check this [link](https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#import-link-from-gatsby) of migration guide regarding this change.

Can you try fixing that and check if that resolves the issue for you?

**Comment by DSchau** [comment]
@travi I think I'll work on this today. Should be a fairly minimal/easy change!
