### ISSUE TITLE
ERR_IPC_CHANNEL_CLOSED on gatsby build

### ISSUE THREAD

**Issue by SachaG** [gatsbyjs/gatsby#9027]
## Description

I keep running into this error when trying to `gatsby build`: 

```
Unhandled rejection Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at process.target.send (internal/child_process.js:578:16)
    at reportSuccess (/Users/sacha/Dev/StateOfJS/surveys/2018/website/node_modules/jest-worker/build/child.js:59:11)
    at tryCatcher (/Users/sacha/Dev/StateOfJS/surveys/2018/website/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/sacha/Dev/StateOfJS/surveys/2018/website/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/sacha/Dev/StateOfJS/surveys/2018/website/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/sacha/Dev/StateOfJS/surveys/2018/website/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/sacha/Dev/StateOfJS/surveys/2018/website/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/sacha/Dev/StateOfJS/surveys/2018/website/node_modules/bluebird/js/release/promise.js:638:18)
    at MappingPromiseArray.PromiseArray._resolve (/Users/sacha/Dev/StateOfJS/surveys/2018/website/node_modules/bluebird/js/release/promise_array.js:126:19)
    at MappingPromiseArray._promiseFulfilled (/Users/sacha/Dev/StateOfJS/surveys/2018/website/node_modules/bluebird/js/release/map.js:101:18)
    at Promise._settlePromise (/Users/sacha/Dev/StateOfJS/surveys/2018/website/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/sacha/Dev/StateOfJS/surveys/2018/website/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/sacha/Dev/StateOfJS/surveys/2018/website/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/sacha/Dev/StateOfJS/surveys/2018/website/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/sacha/Dev/StateOfJS/surveys/2018/website/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/sacha/Dev/StateOfJS/surveys/2018/website/node_modules/bluebird/js/release/async.js:147:5)
```

Any idea what's going on? 

### Environment

```

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 61.0.2
    Safari: 12.0
  npmPackages:
    gatsby: 2.0.18 => 2.0.18 
    gatsby-link: ^2.0.4 => 2.0.4 
    gatsby-plugin-google-analytics: ^2.0.6 => 2.0.6 
    gatsby-plugin-netlify: ^2.0.1 => 2.0.1 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sass: ^2.0.1 => 2.0.1 
    gatsby-source-filesystem: ^2.0.1 => 2.0.1 
    gatsby-transformer-yaml: ^2.1.3 => 2.1.3 
  npmGlobalPackages:
    gatsby-cli: 2.4.2
```

**Comment by kakadiadarpan** [comment]
Hi @SachaG, can you provide more details regarding this error? Is it occurring every time you run `gatsby build`? Did it start happening after any updates?

**Comment by kakadiadarpan** [comment]
@zivc are you also getting `ERR_IPC_CHANNEL_CLOSED` when the build fails?

**Comment by zivc** [comment]
Hi,

Mine has magically fixed itself after removing a few console.logs and now works when I add them back.

I can invite you to a repository and you can checkout a specific commit to debug if you'd like.

Ash

**Comment by Jvalal** [comment]
I'm still getting this error

**Comment by ttstauss** [comment]
I'm getting this error as well. Currently investigating. I removed all console.logs from my project.

**Comment by snackersteph** [comment]
I'm also experiencing this issue, without any console.logs in my code

**Comment by rafael-nogueras** [comment]
@ttstauss @snackersteph I am also getting this error. Have either of you found any work-arounds?

**Comment by kpennell** [comment]
@ttstauss @snackersteph @rafael-nogueras any luck solving this?

**Comment by rafael-nogueras** [comment]
@kpennell Sorry: that was like 15 errors ago. At this point I'm not sure what fixed this particular error.

**Comment by kmcaloon** [comment]
Same here. `console.logs` seem to be the culprit.

**Comment by ardalis** [comment]
Getting it today as well with 
```
    "gatsby": "^2.20.35",
    "gatsby-dynamic-image": "^0.2.0",
    "gatsby-image": "^2.3.5",
    "gatsby-plugin-google-analytics": "^2.3.3",
    "gatsby-plugin-mailchimp": "^5.1.2",
    "gatsby-plugin-material-ui": "^2.1.8",
    "gatsby-plugin-netlify": "^2.2.4",
    "gatsby-plugin-netlify-cms": "^4.2.5",
    "gatsby-plugin-paginate": "^1.12.0",
    "gatsby-plugin-purgecss": "^5.0.0",
    "gatsby-plugin-react-helmet": "^3.2.5",
    "gatsby-plugin-sass": "^2.2.4",
    "gatsby-plugin-sharp": "^2.5.7",
    "gatsby-plugin-twitter": "^2.3.1",
    "gatsby-remark-copy-linked-files": "^2.2.4",
    "gatsby-remark-images": "^3.2.6",
    "gatsby-remark-prismjs": "^3.5.2",
    "gatsby-remark-relative-images": "^0.3.0",
    "gatsby-source-filesystem": "^2.2.5",
    "gatsby-transformer-remark": "^2.8.13",
    "gatsby-transformer-sharp": "^2.4.7",
    "lodash": "^4.17.15",
    "lodash-webpack-plugin": "^0.11.4",
    "netlify-cms-app": "^2.9.6",
    "netlify-cms-media-library-cloudinary": "^1.3.2",
    "netlify-cms-media-library-uploadcare": "^0.5.2",
    "node-sass": "^4.14.0",
    "prismjs": "^1.20.0",

```

**Comment by geochanto** [comment]
Running into this as well, even though I commented out all console logs, and also not using any gatsby image plugins... any other tips?
