### ISSUE TITLE
[Gatsby V1] "Plugin/Preset files are not allowed to export objects gatsby" after installing unit testing for jest.

### ISSUE THREAD

**Issue by diboy2** [gatsbyjs/gatsby#9455]
## Description

I followed the v1 unit testing guide and installed all the necessary plugins. Now it is running the unit tests correctly, but it is breaking gatsby develop and gatsby build.

### Steps to reproduce

I followed this guide: https://v1.gatsbyjs.org/docs/unit-testing/#unit-testing and then ran gatsby develop or gatsby build. I believe it is using babel 7 on gatsby when it should be running babel 6.

### Expected result
Running gatsby develop should not run errors. 
Running gatsby build should generate a bundle without erros. 

### Actual result

Running gatsby develop 

```
W
success write out redirect data — 0.001 s
success onPostBootstrap — 0.001 s

info bootstrap finished - 2.477 s

error There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  13 |
  14 | if (process.env.NODE_ENV !== "production") {
> 15 |   (function() {
     | ^
  16 | 'use strict';
  17 |
  18 | var _assign = require('object-assign');


  WebpackError:

  - react.development.js:15 createDescriptor
    ~/gatsby-plugin-react-next/~/react/cjs/react.development.js:15:1

  - develop-static-entry.js:37 items.map
    .cache/develop-static-entry.js:37:28


  - develop-static-entry.js:37 createDescriptors
    .cache/develop-static-entry.js:37:22

  - develop-static-entry.js:29 createPresetDescriptors
    .cache/develop-static-entry.js:29:5


  - react.development.js:152 mergeChainOpts
    ~/gatsby-plugin-react-next/~/react/cjs/react.development.js:152:1

  - react.development.js:115
    ~/gatsby-plugin-react-next/~/react/cjs/react.development.js:115:1


  - develop-static-entry.js:13 loadPrivatePartialConfig
    .cache/develop-static-entry.js:13:10


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! DigitalSafetyMicrosite@1.0.0 develop: `gatsby develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the DigitalSafetyMicrosite@1.0.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/acaga/.npm/_logs/2018-10-26T20_28_58_051Z-debug.log
```
Running gatsby build

```
Error Generating JavaScript bundles failed


  Error: ./.cache/production-app.js
  Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/acaga/t
  est_folder/DigitalSafetyMicrosite/node_modules/babel-preset-stage-0/lib/index.js
      at createDescriptor (/Users/acaga/test_folder/DigitalSafetyMicrosite/node_modules/@babel/core/lib/config/config-
  descriptors.js:178:11)
      at items.map (/Users/acaga/test_folder/DigitalSafetyMicrosite/node_modules/@babel/core/lib/config/config-descrip
  tors.js:109:50)
      at Array.map (<anonymous>)
      at createDescriptors (/Users/acaga/test_folder/DigitalSafetyMicrosite/node_modules/@babel/core/lib/config/config
  -descriptors.js:109:29)
      at createPresetDescriptors (/Users/acaga/test_folder/DigitalSafetyMicrosite/node_modules/@babel/core/lib/config/
  config-descriptors.js:101:10)
      at passPerPreset (/Users/acaga/test_folder/DigitalSafetyMicrosite/node_modules/@babel/core/lib/config/config-des
  criptors.js:58:96)
      at cachedFunction (/Users/acaga/test_folder/DigitalSafetyMicrosite/node_modules/@babel/core/lib/config/caching.j
  s:33:19)
      at presets.presets (/Users/acaga/test_folder/DigitalSafetyMicrosite/node_modules/@babel/core/lib/config/config-d
  escriptors.js:29:84)
      at mergeChainOpts (/Users/acaga/test_folder/DigitalSafetyMicrosite/node_modules/@babel/core/lib/config/config-ch
  ain.js:315:26)
      at /Users/acaga/test_folder/DigitalSafetyMicrosite/node_modules/@babel/core/lib/config/config-chain.js:278:7
      at buildRootChain (/Users/acaga/test_folder/DigitalSafetyMicrosite/node_modules/@babel/core/lib/config/config-ch
  ain.js:68:29)
      at loadPrivatePartialConfig (/Users/acaga/test_folder/DigitalSafetyMicrosite/node_modules/@babel/core/lib/config
  /partial.js:85:55)
      at loadFullConfig (/Users/acaga/test_folder/DigitalSafetyMicrosite/node_modules/@babel/core/lib/config/full.js:4
  3:39)
      at transformSync (/Users/acaga/test_folder/DigitalSafetyMicrosite/node_modules/@babel/core/lib/transform.js:41:3
  8)
      at Object.transform (/Users/acaga/test_folder/DigitalSafetyMicrosite/node_modules/@babel/core/lib/transform.js:2
  2:38)
      at transpile (/Users/acaga/test_folder/DigitalSafetyMicrosite/node_modules/babel-loader/lib/index.js:46:20)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! DigitalSafetyMicrosite@1.0.0 build: `gatsby build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the DigitalSafetyMicrosite@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/acaga/.npm/_logs/2018-10-26T20_33_52_469Z-debug.log
```
### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
  Browsers:
    Chrome: 65.0.3325.162
    Safari: 11.1.2
  npmPackages:
    gatsby: ^1.9.277 => 1.9.279
    gatsby-link: ^1.6.46 => 1.6.46
    gatsby-plugin-eslint: ^1.0.3 => 1.0.3
    gatsby-plugin-google-fonts: 0.0.3 => 0.0.3
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11
    gatsby-plugin-react-next: ^1.0.11 => 1.0.11
    gatsby-source-filesystem: 1.5.39 => 1.5.39
    gatsby-transformer-json: 1.0.20 => 1.0.20
  npmGlobalPackages:
    gatsby-cli: 2.4.2

**Comment by kakadiadarpan** [comment]
@m-allanson @pieh I think this `Unit testing` documentation is meant for Gatsby v2 and it should not be there for v1? I remember talking about this same issue earlier where we removed this section from v1 docs.

**Comment by diboy2** [comment]
@kakadiadarpan Is it possible to recover the raw text for v1 for the unit testing configuration? Unit testing setup is blocking some of my team's stories.

**Comment by pieh** [comment]
I think you are right about babel 7 - it's weird it is there in v1 docs - could you try removing babel 7 part and adjust jest babel config to use same plugins/presets that gatsby v1 is using: https://github.com/gatsbyjs/gatsby/blob/43ea95d21366d2480df403857330a2bf4ee9e3ed/packages/gatsby/src/utils/babel-config.js#L146-L174

**Comment by diboy2** [comment]
@pieh I just add babel-config in my root directory. the v1 documentation for babel is also missing.

**Comment by diboy2** [comment]
@pieh Sorry, I meant. * Do I just add the babel-config.js file in my root directory? *

**Comment by hh83917** [comment]
So we remove all babel 7 stuff and `npm i babel-preset-env babel-preset-stage-0` as stated by @pieh.
Change jest-preprocessing to
```
// jest-preprocess.js
const babelOptions = {
  presets: ["babel-preset-env", "stage-0", "react"],
}
```

That worked for us so far, thank you @pieh.
