### ISSUE TITLE
Use remark manually causes strange error

### ISSUE THREAD

**Issue by miracle2k** [gatsbyjs/gatsby#961]
I am importing remark in a file inside my `./templates` folder.

```
const Remark = require('remark');
```

This very line raises an error:

```
Generating HTML failed

Error: TypeError: Cannot read property 'data' of null
    at parse (render-page.js:55019:65)  <---- this is in remark-parse/index.js
    at Function.use (render-page.js:53795:26)
    at Object.<anonymous> (render-page.js:53471:29)
    at __webpack_require__ (render-page.js:30:30)
    at Object.assign.i (render-page.js:51012:15) <--- This is the require('remark') line
    at __webpack_require__ (render-page.js:30:30)
    at ComponentBeerdigung.render (render-page.js:50912:38)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (render-page.js:14981:31)
    at ReactCompositeComponentWrapper._renderValidatedComponent (render-page.js:15004:33)
    at ReactCompositeComponentWrapper.performInitialMount (render-page.js:14544:31)
```

It works fine if I, say, import it in the node CLI.

Any ideas Is gatsby doing anything in particular?

**Comment by KyleAMathews** [comment]
No idea. Perhaps there's something about remark that doesn't like being in a browser environment.
