### ISSUE TITLE
[1.0] [Alpha14] Which version of node.js ??

### ISSUE THREAD

**Issue by MarcCoet** [gatsbyjs/gatsby#963]
Hey, I am having issues deploying to Netlify.
Building locally works fine with Alpha14 and Node version 7.10 but it fails on Netlify with Node v6.10 and v7.10 but with different errors though.

v6.10
```
UNHANDLED REJECTION Error: Schema must be an instance of GraphQLSchema. Also ensure that
there are not multiple versions of GraphQL installed in your node_modules directory.
```
-> which never fails btw. It stays stuck on ```---saved redux state``` after the error

v7.10
```
Error: The module '/opt/build/repo/node_modules/sharp/build/Release/sharp.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
```
What does this second error mean exactly? Why does it trigger on Netlify and not locally?

**Comment by KyleAMathews** [comment]
Could you try reproducing this with the gatsbygram example site or gatsbyjs
(at www)? Both use sharp and work fine on netlify.

**Comment by MarcCoet** [comment]
out of the box Gatsbygram is working just fine with both node versions...
Any idea how I could approach debugging this?

**Comment by jquense** [comment]
I think you need to blow you node modules away and reinstall fresh. You have old Dependencies stuck there.

**Comment by jquense** [comment]
e.g. Image sharp was compiled against v6 of node but your are running v7 now

**Comment by MarcCoet** [comment]
did that already. =/
And even though... how could it be on Netlify that it fails? It is building on my machine.

**Comment by MarcCoet** [comment]
Tried to clear the cache on Netlify as well but same same.

**Comment by jquense** [comment]
Did you try clearing the gatsby .cache directory could be incompatible with the never version of leveldown...

**Comment by MarcCoet** [comment]
yep. deleted ```.cache```, ```node_modules```, ```public``` and ```yarn.lock``` every time I tried something new but no difference.

**Comment by MarcCoet** [comment]
btw, I am now trying to break gatsbygram by adding my code pieces by pieces and noticed something worth mentioning I think.
Now that I removed all the images and the posts.json I get a never ending build with error:
```
UNHANDLED REJECTION Error: You supplied a GraphQL document with validation errors:
Unknown type "PostsJson".
Unknown type "PostsJson".
Unknown type "PostsJson".
Unknown type "PostsJson".
at Object.validateOrThrow [as validate] (/opt/build/repo/node_modules/relay-compiler/lib/RelayValidator.js:46:17)
at convertASTDefinitions (/opt/build/repo/node_modules/relay-compiler/lib/ASTConvert.js:107:31)
at Object.convertASTDocuments (/opt/build/repo/node_modules/relay-compiler/lib/ASTConvert.js:42:10)
at Runner._callee3$ (/opt/build/repo/node_modules/gatsby/dist/query-runner/query-compiler.js:184:79)
at tryCatch (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:65:40)
at Generator.invoke [as _invoke] (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:303:22)
at Generator.prototype.(anonymous function) [as next] (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:117:21)
at step (/opt/build/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
at /opt/build/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
at new Promise (/opt/build/repo/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:191:7)
at Runner.<anonymous> (/opt/build/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
at Runner.write (/opt/build/repo/node_modules/gatsby/dist/query-runner/query-compiler.js:221:22)
at Runner._callee$ (/opt/build/repo/node_modules/gatsby/dist/query-runner/query-compiler.js:108:55)
at tryCatch (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:65:40)
at Generator.invoke [as _invoke] (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:303:22)
at Generator.prototype.(anonymous function) [as next] (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:117:21)
```
I guess this error should break the build process, right?

**Comment by MarcCoet** [comment]
ok, seems it's on Netlify's fault somehow...
After replacing all the code of gatsbygram it was still working so i decided to create a new project and new github repo. I literally copy/pasted my whole project (the one that is not building on netlify) and just deleted the .git to start from scratch. Then once push on github again, did netlify init and there it is, working like a charm...
I guess nobody is going to give me back those 9 hours of my life but I hope this issue will be found on time of despair.
I still need to figure out if I can afford losing my git history and reboot my project like that but closing this as I don't see how it could be related to Gatsby in the end.

**Comment by KyleAMathews** [comment]
Sorry you had a bad experience! Another guess what was happening is netlify
keeps a cache between builds to speed things up. Did you try building
without that cache?

**Comment by MarcCoet** [comment]
Thanks. Sure there are better ways to spend a sunny Sunday but s**t happens. ;)
I tried to "trigger deploy" with "clear build cache" option checked. I don't know of any other way to do that (because this only triggers a deploy on master) but I guess it would have done the trick.
I messaged Netlify support to see if they know about this kind of issues.
